function tests = testPlanAzElAvoidance
tests = functiontests(localfunctions);
end

function setupOnce(~)
suiteRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(genpath(fullfile(suiteRoot, "src")));
end

function testExactPublicApiAndLongHorizon(testCase)
time_s = (2700:0.1:3000).';
azElData = emptyData(time_s);
startState = struct( ...
    "time_s", 2700, ...
    "position_deg", [-30 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stopState = struct( ...
    "time_s", 3000, ...
    "position_deg", [80 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-90 90], ...
    "maxVelocity_deg_s", [1 1], ...
    "maxAcceleration_deg_s2", [3 3]);
options = struct( ...
    "SampleTime_s", 0.1, ...
    "GridStep_deg", 0.1, ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", true);

plan = planAzElAvoidance( ...
    azElData, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, numel(plan.time_s), 3001);
verifyEqual(testCase, plan.time_s([1 end]), [2700; 3000], ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.position_deg(end, :), [80 0], ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.velocity_deg_s(end, :), [0 0], ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.acceleration_deg_s2(end, :), [0 0], ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.objective, "minimumAngularDistance");
verifyTrue(testCase, plan.optimalGlobally);
verifyEqual(testCase, plan.angularPathLength_deg, 110, "AbsTol", 1e-9);
verifyEqual(testCase, plan.angularLowerBound_deg, 110, "AbsTol", 1e-9);
verifyEqual(testCase, plan.suboptimalityBound, 1, "AbsTol", 1e-12);
verifyTrue(testCase, isnan(plan.internalSampleTime_s));
end

function testAvoidsExpandedPolygon(testCase)
time_s = (0:0.5:20).';
n = numel(time_s);
azimuth = repmat({[-1; 1; 1; -1; -1]}, n, 1);
elevation = repmat({[43; 43; 47; 47; 43]}, n, 1);
azElData = struct( ...
    "targetName", "Block", ...
    "time_s", time_s, ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", repmat("visible", n, 1));
startState = boundaryState(0, [-6 45]);
stopState = boundaryState(20, [6 45]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [40 50], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0.5, ...
    "AllowAzimuthWrap", true);

plan = planAzElAvoidance( ...
    azElData, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct("SafetyMarginDeg", options.SafetyMargin_deg));
verifyFalse(testCase, any(blocked));
verifyGreaterThan(testCase, ...
    max(abs(plan.position_deg(:, 2) - 45)), 2);
verifyEqual(testCase, plan.objective, "minimumAngularDistance");
verifyGreaterThanOrEqual(testCase, plan.suboptimalityBound, 1);
end

function testAcceptsMultipleObstacles(testCase)
time_s = (0:1:8).';
left = emptyData(time_s);
left.targetName = "Left";
right = emptyData(time_s);
right.targetName = "Right";
startState = boundaryState(0, [-2 0]);
stopState = boundaryState(8, [2 0]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [1 1], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 1, ...
    "GridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumTime");

plan = planAzElAvoidance( ...
    {left, right}, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.workspace.ObstacleCount, 2);
verifyEqual(testCase, plan.objective, "minimumTime");
verifyTrue(testCase, plan.optimalOnLattice);
end

function testAnimatorSupportsTwoAndThreeDimensionalViews(testCase)
time_s = (0:1:4).';
azElData = emptyData(time_s);
workspace = buildAzElTimeObstacleWorkspace(azElData);
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", [time_s, time_s], ...
    "workspace", workspace, ...
    "limits", struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-90 90]));

modes = ["2d", "3d", "combined"];
for mode = modes
    handles = animateAzElAvoidancePlan(azElData, plan, struct( ...
        "ViewMode", mode, ...
        "MaximumAnimationFrames", 3, ...
        "MaximumDisplayedSlices", 2, ...
        "PauseSeconds", 0, ...
        "FigureVisible", "off"));
    cleanup = onCleanup(@() closeIfValid(handles.Figure));

    verifyTrue(testCase, handles.Completed);
    verifyEqual(testCase, handles.FrameCount, 3);
    verifyEqual(testCase, isgraphics(handles.AzElAxes), ...
        mode ~= "3d");
    verifyEqual(testCase, isgraphics(handles.WorkspaceAxes), ...
        mode ~= "2d");
    if mode ~= "2d"
        marker = [ ...
            handles.ThreeDimensional.CurrentBoresight.XData, ...
            handles.ThreeDimensional.CurrentBoresight.YData, ...
            handles.ThreeDimensional.CurrentBoresight.ZData];
        verifyEqual(testCase, marker, [4 4 4]);
    end
    closeIfValid(handles.Figure);
    clear cleanup;
end
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function data = emptyData(time_s)
n = numel(time_s);
empty = repmat({zeros(0, 1)}, n, 1);
data = struct( ...
    "targetName", "Empty", ...
    "time_s", time_s, ...
    "az_deg", {empty}, ...
    "el_deg", {empty}, ...
    "status", repmat("visible", n, 1));
end

function closeIfValid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
