function sceneData = createSceneData(study, sunDirectionProvider)
%% Section 0: Header & Readme
% SYNTAX
%   sceneData = scenario.integrations.threejs.createSceneData(study)
%   sceneData = scenario.integrations.threejs.createSceneData( ...
%       study, sunDirectionProvider)
%**************************************************************************
% PURPOSE
%   - Convert a MATLAB Scenario into an ITRF Three.js snapshot payload.
%**************************************************************************
% INPUTS
%   - study (scenario.Scenario)
%       Scenario containing satellites and WGS84 places. Satellites outside
%       ITRF are omitted because this integration has no transform provider.
%   - sunDirectionProvider (function handle, optional)
%       Function accepting one zoned datetime and returning the documented
%       environment Sun-direction result contract. The default is the
%       provider-independent scenario.environment calculation.
%**************************************************************************
% OUTPUTS
%   - sceneData (scalar struct)
%       Renderer payload containing names, ITRF positions, WGS84 places,
%       reference-frame provenance, and warnings.
%**************************************************************************
% UNITS
%   - Position and Earth radius are metres. Place coordinates are degrees and
%     ellipsoidal metres. The snapshot epoch uses the Scenario datetime.
%**************************************************************************

%% Section 1: Validate The Scenario

if ~isa(study, "scenario.Scenario")
    error("createSceneData:InvalidScenario", ...
        "study must be a scenario.Scenario instance.");
end
if nargin < 2 || isempty(sunDirectionProvider)
    sunDirectionProvider = @scenario.environment.calculateSunDirection;
end
if ~isa(sunDirectionProvider, "function_handle")
    error("createSceneData:InvalidSunProvider", ...
        "sunDirectionProvider must be a function handle.");
end

%% Section 2: Collect ITRF Satellites

emptySatellite = struct( ...
    "name", "", ...
    "positionEcef_m", zeros(1, 3), ...
    "positionEci_m", zeros(1, 3), ...
    "hasEphemeris", false, ...
    "orbitPathEcef_m", zeros(0, 3), ...
    "orbitPathEci_m", zeros(0, 3));
satellites = repmat(emptySatellite, 0, 1);
warnings = strings(0, 1);

for satelliteIndex = 1:numel(study.Satellites)
    satellite = study.Satellites{satelliteIndex};
    if satellite.InitialState.frame ~= "ITRF"
        warnings(end + 1, 1) = "Satellite '" + satellite.Name + ...
            "' was omitted because its frame is not ITRF."; %#ok<AGROW>
        continue
    end

    satelliteData = emptySatellite;
    satelliteData.name = satellite.Name;
    satelliteData.positionEcef_m = satellite.InitialState.position_m;
    satelliteData.positionEci_m = ...
        scenario.frames.convertEarthFixedToInertial( ...
            study.StartTime, satellite.InitialState.position_m);
    satellites(end + 1, 1) = satelliteData; %#ok<AGROW>
end

%% Section 3: Collect WGS84 Places

emptyPlace = struct( ...
    "name", "", ...
    "positionEcef_m", zeros(1, 3), ...
    "positionEci_m", zeros(1, 3));
places = repmat(emptyPlace, 0, 1);

for placeIndex = 1:numel(study.Places)
    place = study.Places{placeIndex};
    placeData = emptyPlace;
    placeData.name = place.Name;
    geodetic_lla = [ ...
        place.Latitude_deg, place.Longitude_deg, place.Altitude_m];
    placeData.positionEcef_m = ...
        scenario.frames.convertGeodeticToEarthFixed(geodetic_lla);
    placeData.positionEci_m = ...
        scenario.frames.convertEarthFixedToInertial( ...
            study.StartTime, placeData.positionEcef_m);
    places(end + 1, 1) = placeData; %#ok<AGROW>
end

%% Section 4: Calculate The Sun Direction

sunDirection = sunDirectionProvider(study.StartTime);
validateSunDirection(sunDirection);
sun = struct( ...
    "name", "Sun", ...
    "unitDirectionEcef", sunDirection.UnitDirectionEcef, ...
    "unitDirectionEci", sunDirection.UnitDirectionEci, ...
    "model", sunDirection.Model, ...
    "accuracy", sunDirection.Accuracy);
transformedBasis = scenario.frames.convertEarthFixedToInertial( ...
    study.StartTime, eye(3));
ecefToEciMatrix = transformedBasis';

%% Section 5: Assemble The Renderer Payload

sceneData = struct( ...
    "kind", "scene", ...
    "scenarioName", study.Name, ...
    "epoch", string(study.StartTime), ...
    "availableReferenceFrames", ["ECEF", "ECI"], ...
    "inertialFrame", sunDirection.InertialFrame, ...
    "ecefToEciMatrix", ecefToEciMatrix, ...
    "earthRadius_m", 6378137, ...
    "satellites", satellites, ...
    "places", places, ...
    "sun", sun, ...
    "warnings", warnings);
end

function validateSunDirection(sunDirection)
% Enforce the renderer's provider-neutral Sun-direction contract.

requiredFields = [ ...
    "UnitDirectionEcef", "UnitDirectionEci", "InertialFrame", ...
    "Model", "Accuracy"];
if ~(isstruct(sunDirection) && isscalar(sunDirection) && ...
        all(isfield(sunDirection, requiredFields)))
    error("createSceneData:InvalidSunResult", ...
        "The Sun provider must return UnitDirectionEcef, " + ...
        "UnitDirectionEci, InertialFrame, Model, and Accuracy fields.");
end
validateattributes(sunDirection.UnitDirectionEcef, {'numeric'}, ...
    {'real', 'finite', 'size', [1, 3]});
validateattributes(sunDirection.UnitDirectionEci, {'numeric'}, ...
    {'real', 'finite', 'size', [1, 3]});
end
