function diagnostics = analyzeBlinkingChessboardIntercept(problem, plan)
%% Section 0: Header & Readme
% SYNTAX
%   diagnostics = analyzeBlinkingChessboardIntercept(problem, plan)
%**************************************************************************
% PURPOSE
%   - Measure safety, board transfers, and terminal tracking error for one
%     randomized blinking-board interception.
%**************************************************************************
% INPUTS
%   - problem (scalar struct)
%       Generated board, moving target, planner options, and cell centers.
%   - plan (scalar struct)
%       Successful planAzElMovingTargetIntercept result.
%**************************************************************************
% OUTPUTS
%   - diagnostics (scalar struct)
%       Reproducibility, safety, transfer, target-motion, and timing metrics.
%**************************************************************************
% UNITS
%   - Positions and distances are degrees; times are seconds.

%% Section 1: Validate The Successful Plan
if ~isstruct(plan) || ~isfield(plan, "success") || ~plan.success
    error("analyzeBlinkingChessboardIntercept:InvalidPlan", ...
        "plan must be a successful blinking-board interception.");
end

%% Section 2: Recheck Boresight & Target Safety
blockedBoresightSamples = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", problem.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
blockedTargetSamples = queryAzElTimeObstacle(plan.obstacleField, ...
    problem.target.position_deg(:, 1), ...
    problem.target.position_deg(:, 2), problem.target.time_s, ...
    struct("SafetyMarginDeg", problem.options.SafetyMargin_deg));

%% Section 3: Measure Board Transfers & Interception Error
boresightCellIndex = nearestCells( ...
    plan.position_deg, problem.geometry.cellCenters_deg);
cellTransferCount = nnz(diff(boresightCellIndex) ~= 0);
targetStep_deg = diff(problem.target.position_deg, 1, 1);
targetTravelDistance_deg = sum(hypot( ...
    targetStep_deg(:, 1), targetStep_deg(:, 2)));
targetPositionAtIntercept_deg = interp1( ...
    problem.target.time_s, problem.target.position_deg, ...
    plan.time_s(end), "linear");
interceptError_deg = hypot( ...
    plan.position_deg(end, 1) - targetPositionAtIntercept_deg(1), ...
    plan.position_deg(end, 2) - targetPositionAtIntercept_deg(2));

%% Section 4: Assemble Diagnostics
diagnostics = struct( ...
    "seed", problem.seed, ...
    "interceptTime_s", plan.time_s(end), ...
    "interceptPosition_deg", plan.position_deg(end, :), ...
    "targetPositionAtIntercept_deg", targetPositionAtIntercept_deg, ...
    "catchError_deg", interceptError_deg, ...
    "blockedBoresightSampleCount", nnz(blockedBoresightSamples), ...
    "blockedTargetSampleCount", nnz(blockedTargetSamples), ...
    "cellTransferCount", cellTransferCount, ...
    "boardSwitchCount", ...
        numel(problem.geometry.switchTimes_s), ...
    "targetTravelDistance_deg", targetTravelDistance_deg, ...
    "waitingSampleCount", nnz(plan.isWaiting), ...
    "attemptCount", numel(plan.interceptAttempts), ...
    "searchElapsed_s", plan.interceptSearchElapsed_s);
end

%% Section 5: Local Functions
function nearestCellIndex = nearestCells(position_deg, cellCenters_deg)
%% Section 0: Header & Readme
% Return the nearest board cell for each position sample. This helper is
% retained because the full pairwise distance matrix would obscure the
% diagnostic stages above if written inline.
squaredDistance_deg2 = ( ...
    position_deg(:, 1) - cellCenters_deg(:, 1).').^2 + ...
    (position_deg(:, 2) - cellCenters_deg(:, 2).').^2;
[~, nearestCellIndex] = min(squaredDistance_deg2, [], 2);
end
