function diagnostics = analyzeRotatingSlotGauntlet(problem, plan)
%ANALYZEROTATINGSLOTGAUNTLET Measure crossings, waits, and slot alignment.

if ~isstruct(plan) || ~isfield(plan, "success") || ~plan.success
    error("analyzeRotatingSlotGauntlet:InvalidPlan", ...
        "plan must be a successful rotating-slot gauntlet plan.");
end
radius = hypot(plan.position_deg(:, 1), plan.position_deg(:, 2));
geometry = problem.geometry;
ringCount = numel(geometry.innerRadius_deg);
crossingTime = nan(1, ringCount);
slotError = nan(1, ringCount);
crossingIndex = zeros(1, ringCount);
for ring = 1:ringCount
    crossing = find(radius <= ...
        geometry.innerRadius_deg(ring) - ...
        problem.options.SafetyMargin_deg, 1);
    if isempty(crossing)
        continue;
    end
    crossingIndex(ring) = crossing;
    crossingTime(ring) = plan.time_s(crossing);
    pathAngle = atan2d( ...
        plan.position_deg(crossing, 2), ...
        plan.position_deg(crossing, 1));
    slotCenter = geometry.phase_deg(ring) + ...
        geometry.angularRate_deg_s(ring) * crossingTime(ring);
    slotError(ring) = abs(wrapAngle(pathAngle - slotCenter));
end

chamberCount = ringCount - 1;
chamberWait = zeros(1, chamberCount);
sampleStep = median(diff(plan.time_s));
for chamber = 1:chamberCount
    insideOuterRing = radius < ...
        geometry.innerRadius_deg(chamber) - ...
        problem.options.SafetyMargin_deg;
    outsideInnerRing = radius > ...
        geometry.outerRadius_deg(chamber + 1) + ...
        problem.options.SafetyMargin_deg;
    chamberWait(chamber) = sampleStep * nnz( ...
        plan.isWaiting & insideOuterRing & outsideInnerRing);
end
blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", problem.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
diagnostics = struct( ...
    "radius_deg", radius, ...
    "crossingIndex", crossingIndex, ...
    "crossingTime_s", crossingTime, ...
    "slotCenterError_deg", slotError, ...
    "chamberWait_s", chamberWait, ...
    "totalWaiting_s", sampleStep * nnz(plan.isWaiting), ...
    "blockedSampleCount", nnz(blocked));
end

function angle = wrapAngle(angle)
angle = mod(angle + 180, 360) - 180;
end
