function diagnostics = analyzeBlinkingChessboardIntercept(problem, plan)
%ANALYZEBLINKINGCHESSBOARDINTERCEPT Measure one stochastic interception.

if ~isstruct(plan) || ~isfield(plan, "success") || ~plan.success
    error("analyzeBlinkingChessboardIntercept:InvalidPlan", ...
        "plan must be a successful blinking-board interception.");
end
blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", problem.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
targetBlocked = queryAzElTimeObstacle(plan.obstacleField, ...
    problem.target.position_deg(:, 1), ...
    problem.target.position_deg(:, 2), problem.target.time_s, ...
    struct("SafetyMarginDeg", problem.options.SafetyMargin_deg));

planCell = nearestCells( ...
    plan.position_deg, problem.geometry.cellCenters_deg);
cellTransfers = nnz(diff(planCell) ~= 0);
targetDelta = diff(problem.target.position_deg, 1, 1);
targetDistance = sum(hypot(targetDelta(:, 1), targetDelta(:, 2)));
targetAtCatch = interp1( ...
    problem.target.time_s, problem.target.position_deg, ...
    plan.time_s(end), "linear");
catchError = hypot( ...
    plan.position_deg(end, 1) - targetAtCatch(1), ...
    plan.position_deg(end, 2) - targetAtCatch(2));

diagnostics = struct( ...
    "seed", problem.seed, ...
    "interceptTime_s", plan.time_s(end), ...
    "interceptPosition_deg", plan.position_deg(end, :), ...
    "targetPositionAtIntercept_deg", targetAtCatch, ...
    "catchError_deg", catchError, ...
    "blockedBoresightSampleCount", nnz(blocked), ...
    "blockedTargetSampleCount", nnz(targetBlocked), ...
    "cellTransferCount", cellTransfers, ...
    "boardSwitchCount", ...
        numel(problem.geometry.switchTimes_s), ...
    "targetTravelDistance_deg", targetDistance, ...
    "waitingSampleCount", nnz(plan.isWaiting), ...
    "attemptCount", numel(plan.interceptAttempts), ...
    "searchElapsed_s", plan.interceptSearchElapsed_s);
end

function index = nearestCells(position, centers)
distance = (position(:, 1) - centers(:, 1).').^2 + ...
    (position(:, 2) - centers(:, 2).').^2;
[~, index] = min(distance, [], 2);
end
