function diagnostics = analyzeChasedBoresightGauntlet(problem, plan)
%ANALYZECHASEDBORESIGHTGAUNTLET Measure pursuit, motion, and goal timing.

if ~isstruct(plan) || ~isfield(plan, "success") || ~plan.success
    error("analyzeChasedBoresightGauntlet:InvalidPlan", ...
        "plan must be a successful chased-boresight plan.");
end
sampleStep = median(diff(plan.time_s));
goalDistance = hypot( ...
    plan.position_deg(:, 1) - problem.stopState.position_deg(1), ...
    plan.position_deg(:, 2) - problem.stopState.position_deg(2));
goalIndex = find(goalDistance <= 0.15, 1);
if isempty(goalIndex)
    goalArrivalTime = NaN;
else
    goalArrivalTime = plan.time_s(goalIndex);
end
beforeOpen = plan.time_s < problem.geometry.goalOpenTime_s;
movingBeforeOpen = beforeOpen & ~plan.isWaiting;
movingFraction = nnz(movingBeforeOpen) / max(1, nnz(beforeOpen));
longestWait = longestTrueRun(plan.isWaiting & beforeOpen) * sampleStep;
blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", problem.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
diagnostics = struct( ...
    "goalArrivalTime_s", goalArrivalTime, ...
    "goalOpenTime_s", problem.geometry.goalOpenTime_s, ...
    "movingFractionBeforeGoalOpen", movingFraction, ...
    "longestWaitBeforeGoalOpen_s", longestWait, ...
    "totalMovingTime_s", sampleStep * nnz(~plan.isWaiting), ...
    "totalWaitingTime_s", sampleStep * nnz(plan.isWaiting), ...
    "angularPathLength_deg", plan.angularPathLength_deg, ...
    "blockedSampleCount", nnz(blocked));
end

function longest = longestTrueRun(mask)
changes = diff([false; mask(:); false]);
starts = find(changes == 1);
stops = find(changes == -1) - 1;
if isempty(starts)
    longest = 0;
else
    longest = max(stops - starts + 1);
end
end
