function diagnostics = analyzeSpinningRodSpiralGauntlet(problem, plan)
%ANALYZESPINNINGRODSPIRALGAUNTLET Measure winding and protected waits.

if ~isstruct(plan) || ~isfield(plan, "success") || ~plan.success
    error("analyzeSpinningRodSpiralGauntlet:InvalidPlan", ...
        "plan must be a successful spinning-rod spiral plan.");
end

position = plan.position_deg;
radius = hypot(position(:, 1), position(:, 2));
inside = radius >= 0.8;
pathAngle = unwrap(atan2(position(inside, 2), position(inside, 1)));
windingTurns = abs(pathAngle(end) - pathAngle(1)) / (2 * pi);

sampleStep_s = median(diff(plan.time_s));
notchCenters = problem.geometry.notchCenters_deg;
notchRadius = problem.geometry.notchSafeRadius_deg + ...
    problem.options.SafetyMargin_deg;
notchWait_s = zeros(1, size(notchCenters, 1));
notchVisited = false(size(notchWait_s));
waitInAnyNotch = false(size(plan.isWaiting));
for notch = 1:size(notchCenters, 1)
    distance = hypot( ...
        position(:, 1) - notchCenters(notch, 1), ...
        position(:, 2) - notchCenters(notch, 2));
    insideNotch = distance <= notchRadius;
    notchVisited(notch) = any(insideNotch);
    notchWait = plan.isWaiting & insideNotch;
    notchWait_s(notch) = sampleStep_s * nnz(notchWait);
    waitInAnyNotch = waitInAnyNotch | notchWait;
end

moving = ~plan.isWaiting & radius >= 1.5;
unwrappedAngle_deg = rad2deg(unwrap(atan2( ...
    position(:, 2), position(:, 1))));
angularRate_deg_s = zeros(size(plan.time_s));
angularRate_deg_s(2:end) = abs(diff(unwrappedAngle_deg) ./ ...
    diff(plan.time_s));
maximumBoresightAngularRate_deg_s = ...
    max(angularRate_deg_s(moving), [], "omitmissing");

blocked = queryAzElTimeObstacle(plan.workspace, ...
    position(:, 1), position(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", problem.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
waitEpisodes = nnz(diff([false; plan.isWaiting; false]) == 1);
protectedWaitEpisodes = nnz(diff( ...
    [false; waitInAnyNotch; false]) == 1);
diagnostics = struct( ...
    "windingTurns", windingTurns, ...
    "notchVisited", notchVisited, ...
    "notchWait_s", notchWait_s, ...
    "visitedNotchCount", nnz(notchVisited), ...
    "waitingNotchCount", nnz(notchWait_s >= sampleStep_s), ...
    "totalWaiting_s", sampleStep_s * nnz(plan.isWaiting), ...
    "protectedWaiting_s", sampleStep_s * nnz(waitInAnyNotch), ...
    "waitingEpisodeCount", waitEpisodes, ...
    "protectedWaitingEpisodeCount", protectedWaitEpisodes, ...
    "maximumBoresightAngularRate_deg_s", ...
        maximumBoresightAngularRate_deg_s, ...
    "rodAngularRate_deg_s", ...
        problem.geometry.rodAngularRate_deg_s, ...
    "blockedSampleCount", nnz(blocked));
end
