function boundary = loadCountryBoundaryLatLon(country)
%LOADCOUNTRYBOUNDARYLATLON Load a bundled ADM0 latitude/longitude boundary.
%
% boundary = loadCountryBoundaryLatLon("Vietnam")
% boundary = loadCountryBoundaryLatLon("China")

requested = lower(strtrim(string(country)));
if ~isscalar(requested)
    error("loadCountryBoundaryLatLon:InvalidCountry", ...
        "country must be Vietnam, VNM, China, or CHN.");
end
switch requested
    case {"vietnam", "viet nam", "vnm"}
        iso3 = "VNM";
        fileName = "vietnam_adm0_latlon.csv";
    case {"china", "chn"}
        iso3 = "CHN";
        fileName = "china_adm0_latlon.csv";
    otherwise
        error("loadCountryBoundaryLatLon:InvalidCountry", ...
            "country must be Vietnam, VNM, China, or CHN.");
end

supportDirectory = fileparts(mfilename("fullpath"));
packageRoot = fileparts(fileparts(supportDirectory));
dataDirectory = fullfile(packageRoot, "data");
values = readmatrix(fullfile(dataDirectory, fileName));
if size(values, 2) < 3
    error("loadCountryBoundaryLatLon:InvalidData", ...
        "%s must contain latitude, longitude, and part columns.", fileName);
end
latitude_deg = double(values(:, 1));
longitude_deg = double(values(:, 2));
partIndex = double(values(:, 3));
finite = isfinite(latitude_deg) & isfinite(longitude_deg);
if nnz(finite) > 500 || nnz(finite) < 4 || ...
        any(isfinite(latitude_deg) ~= isfinite(longitude_deg))
    error("loadCountryBoundaryLatLon:InvalidData", ...
        "%s has invalid separators or exceeds 500 vertices.", fileName);
end

manifest = jsondecode(fileread( ...
    fullfile(dataDirectory, "boundary_manifest.json")));
entry = manifest(strcmpi(string({manifest.iso3}), iso3));
if numel(entry) ~= 1
    error("loadCountryBoundaryLatLon:InvalidManifest", ...
        "No unique %s entry exists in boundary_manifest.json.", iso3);
end

boundary = struct( ...
    "name", string(entry.country), ...
    "iso3", iso3, ...
    "latitude_deg", latitude_deg, ...
    "longitude_deg", longitude_deg, ...
    "partIndex", partIndex, ...
    "vertexCount", nnz(finite), ...
    "polygonPartCount", double(entry.polygonParts), ...
    "boundaryID", string(entry.boundaryID), ...
    "boundaryYearRepresented", ...
    string(entry.boundaryYearRepresented), ...
    "license", string(entry.license), ...
    "sourceUrl", string(entry.sourceUrl));
end
