function problem = makeChasedBoresightGauntlet()
%MAKECHASEDBORESIGHTGAUNTLET Create a loop pursuit with a late-open goal.
%
% A moving cross-track barrier follows the boresight around a square loop.
% The barrier is slightly slower than the feasible boresight command, but it
% spans the corridor width, so stopping on the loop eventually causes a
% collision. The goal alcove remains sealed until near the final time.

time_s = (0:1:80).';
trackHalfWidth_deg = 6;
chaserSpeed_deg_s = 2;
chaserStartDistance_deg = 40;
goalOpenTime_s = 72;

[wallAzimuth, wallElevation] = trackWallBoundary();
walls = makeAzElObstacleData( ...
    "Square-loop walls", time_s, wallAzimuth, wallElevation);

chaserAzimuth = cell(numel(time_s), 1);
chaserElevation = cell(numel(time_s), 1);
for sample = 1:numel(time_s)
    distance = chaserStartDistance_deg + ...
        chaserSpeed_deg_s * time_s(sample);
    [center, tangent] = squareTrackState( ...
        distance, trackHalfWidth_deg);
    [chaserAzimuth{sample}, chaserElevation{sample}] = ...
        orientedRectangle(center, tangent, 1.2, 2.2);
end
chaser = makeAzElObstacleData( ...
    "Pursuing barrier", time_s, chaserAzimuth, chaserElevation);

gateAzimuth = cell(numel(time_s), 1);
gateElevation = cell(numel(time_s), 1);
for sample = 1:numel(time_s)
    if time_s(sample) < goalOpenTime_s
        center = [8.2 0];
    else
        center = [14 0];
    end
    [gateAzimuth{sample}, gateElevation{sample}] = ...
        axisAlignedRectangle(center, 0.45, 2.05);
end
goalGate = makeAzElObstacleData( ...
    "Late-opening goal gate", time_s, ...
    gateAzimuth, gateElevation);

azElData = {walls, chaser, goalGate};
startState = boundaryState(0, [-6 0]);
stopState = boundaryState(80, [9 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [4 4], ...
    "maxAcceleration_deg_s2", [4 4]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.2, ...
    "GridStep_deg", 1, ...
    "PrimitiveRadii_deg", [2 4 8 12], ...
    "CollisionCheckStep_s", 0.2, ...
    "MaximumSafeIntervalSamples", 81, ...
    "MaximumDepartureTrials", 4, ...
    "DepartureBatchSize", 2, ...
    "MaxExpansions", 200000, ...
    "SafetyMargin_deg", 0.1, ...
    "MaxSearchTime_s", 55);
geometry = struct( ...
    "trackHalfWidth_deg", trackHalfWidth_deg, ...
    "trackInnerLimit_deg", 4, ...
    "trackOuterLimit_deg", 8, ...
    "trackPerimeter_deg", 8 * trackHalfWidth_deg, ...
    "chaserSpeed_deg_s", chaserSpeed_deg_s, ...
    "chaserStartDistance_deg", chaserStartDistance_deg, ...
    "goalOpenTime_s", goalOpenTime_s, ...
    "goalPosition_deg", stopState.position_deg);
problem = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

function [azimuth, elevation] = trackWallBoundary()
regions = { ...
    rectangleVertices([-4 4], [-4 4]), ...
    rectangleVertices([-10 10], [8 10]), ...
    rectangleVertices([-10 10], [-10 -8]), ...
    rectangleVertices([-10 -8], [-8 8]), ...
    rectangleVertices([8 10], [2.05 8]), ...
    rectangleVertices([8 10], [-8 -2.05])};
azimuth = zeros(0, 1);
elevation = zeros(0, 1);
for k = 1:numel(regions)
    if k > 1
        azimuth(end + 1, 1) = NaN; %#ok<AGROW>
        elevation(end + 1, 1) = NaN; %#ok<AGROW>
    end
    azimuth = [azimuth; regions{k}(:, 1)]; %#ok<AGROW>
    elevation = [elevation; regions{k}(:, 2)]; %#ok<AGROW>
end
end

function vertices = rectangleVertices(xLimits, yLimits)
vertices = [ ...
    xLimits(1), yLimits(1); ...
    xLimits(2), yLimits(1); ...
    xLimits(2), yLimits(2); ...
    xLimits(1), yLimits(2); ...
    xLimits(1), yLimits(1)];
end

function [center, tangent] = squareTrackState(distance, halfWidth)
perimeter = 8 * halfWidth;
s = mod(distance, perimeter);
if s < halfWidth
    center = [-halfWidth, s];
    tangent = [0 1];
elseif s < 3 * halfWidth
    center = [-halfWidth + (s - halfWidth), halfWidth];
    tangent = [1 0];
elseif s < 5 * halfWidth
    center = [halfWidth, halfWidth - (s - 3 * halfWidth)];
    tangent = [0 -1];
elseif s < 7 * halfWidth
    center = [halfWidth - (s - 5 * halfWidth), -halfWidth];
    tangent = [-1 0];
else
    center = [-halfWidth, -halfWidth + (s - 7 * halfWidth)];
    tangent = [0 1];
end
end

function [azimuth, elevation] = orientedRectangle( ...
        center, tangent, alongHalfWidth, crossHalfWidth)
normal = [-tangent(2), tangent(1)];
vertices = [ ...
    center - alongHalfWidth * tangent - crossHalfWidth * normal; ...
    center + alongHalfWidth * tangent - crossHalfWidth * normal; ...
    center + alongHalfWidth * tangent + crossHalfWidth * normal; ...
    center - alongHalfWidth * tangent + crossHalfWidth * normal; ...
    center - alongHalfWidth * tangent - crossHalfWidth * normal];
azimuth = vertices(:, 1);
elevation = vertices(:, 2);
end

function [azimuth, elevation] = axisAlignedRectangle( ...
        center, xHalfWidth, yHalfWidth)
vertices = rectangleVertices( ...
    center(1) + [-xHalfWidth xHalfWidth], ...
    center(2) + [-yHalfWidth yHalfWidth]);
azimuth = vertices(:, 1);
elevation = vertices(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
