function problem = makeSpinningRodSpiralGauntlet()
%MAKESPINNINGRODSPIRALGAUNTLET Build a notched spiral and rotating sweeper.
%
% The spiral wall contains three recessed shelters. A faster rotating sector
% sweeps the traversable spiral corridor, but is geometrically clipped out
% inside each shelter. The planner receives only canonical azElData and must
% discover both the winding route and all wait locations autonomously.

activeTime_s = (0:0.25:15.50).';
time_s = [activeTime_s; 240];
geometry = struct( ...
    "turnCount", 2, ...
    "innerRadius_deg", 2, ...
    "turnSpacing_deg", 6, ...
    "wallHalfWidth_deg", 0.60, ...
    "wallSampleCount", 181, ...
    "notchTheta_rad", pi * [3.45 2.25 1.05], ...
    "notchDepth_deg", 1.00, ...
    "notchAngularSigma_rad", 0.18, ...
    "notchSafeRadius_deg", 0.65, ...
    "rodHubRadius_deg", 1.35, ...
    "rodOuterRadius_deg", 17, ...
    "rodHalfAngle_deg", 30, ...
    "rodAngularRate_deg_s", 60, ...
    "rodPhase_deg", 90, ...
    "rodActiveStart_s", 0, ...
    "rodActiveEnd_s", 15, ...
    "rodNotchCutHalfWidth_deg", 1.30);

[wallAzimuth, wallElevation, notchCenters] = ...
    notchedSpiralWall(geometry);
geometry.notchCenters_deg = notchCenters;
[rodAzimuth, rodElevation] = spinningRodSlices( ...
    time_s, geometry);

wall = makeAzElObstacleData( ...
    "Notched two-turn spiral wall", time_s([1 end]), ...
    wallAzimuth, wallElevation);
rod = makeAzElObstacleData( ...
    "Fast spinning rod", time_s, rodAzimuth, rodElevation);
azElData = combineAzElObstacles(wall, rod);

startState = boundaryState(0, notchCenters(1, :));
stopState = boundaryState(240, [0 0]);
limits = struct( ...
    "azimuth_deg", [-18 18], ...
    "elevation_deg", [-18 18], ...
    "maxVelocity_deg_s", [0.8 0.8], ...
    "maxAcceleration_deg_s2", [1.2 1.2]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "ValidationStep_s", 0.08, ...
    "GridStep_deg", 2, ...
    "GridStepSchedule_deg", 2, ...
    "PrimitiveRadii_deg", 2, ...
    "HeuristicWeight", 12, ...
    "SafetyMargin_deg", 0.20, ...
    "Objective", "minimumAngularDistance", ...
    "CollisionCheckStep_s", 0.08, ...
    "MaximumSafeIntervalSamples", 150, ...
    "MaximumDepartureTrials", 8, ...
    "DepartureBatchSize", 4, ...
    "MaxExpansions", 300000, ...
    "MaxSearchTime_s", 150, ...
    "AllowAzimuthWrap", false);

problem = struct( ...
    "azElData", azElData, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

function [azimuth, elevation, notchCenters] = ...
        notchedSpiralWall(geometry)
theta = linspace( ...
    0, 2 * pi * geometry.turnCount, ...
    geometry.wallSampleCount).';
radius = geometry.innerRadius_deg + ...
    geometry.turnSpacing_deg * theta / (2 * pi);
baseAzimuth = radius .* cos(theta);
baseElevation = radius .* sin(theta);
[normalAzimuth, normalElevation] = curveNormals( ...
    baseAzimuth, baseElevation);

notchCenters = zeros(numel(geometry.notchTheta_rad), 2);
normalShift = zeros(size(theta));
for notch = 1:numel(geometry.notchTheta_rad)
    centerTheta = geometry.notchTheta_rad(notch);
    bump = exp(-0.5 * ((theta - centerTheta) ./ ...
        geometry.notchAngularSigma_rad).^2);
    normalShift = normalShift + geometry.notchDepth_deg * bump;
    centerRadius = geometry.innerRadius_deg + ...
        geometry.turnSpacing_deg * centerTheta / (2 * pi);
    notchCenters(notch, :) = ...
        centerRadius * [cos(centerTheta) sin(centerTheta)];
end

% Shift the wall toward the inner neighboring turn. On the traversed side,
% this produces a smooth recess without opening a shortcut through the wall.
centerAzimuth = baseAzimuth + normalShift .* normalAzimuth;
centerElevation = baseElevation + normalShift .* normalElevation;
[shiftedNormalAzimuth, shiftedNormalElevation] = curveNormals( ...
    centerAzimuth, centerElevation);
halfWidth = geometry.wallHalfWidth_deg;
leftAzimuth = centerAzimuth + halfWidth * shiftedNormalAzimuth;
leftElevation = centerElevation + halfWidth * shiftedNormalElevation;
rightAzimuth = centerAzimuth - halfWidth * shiftedNormalAzimuth;
rightElevation = centerElevation - halfWidth * shiftedNormalElevation;
azimuth = [leftAzimuth; flipud(rightAzimuth); leftAzimuth(1)];
elevation = [leftElevation; flipud(rightElevation); leftElevation(1)];
end

function [normalAzimuth, normalElevation] = curveNormals( ...
        azimuth, elevation)
deltaAzimuth = gradient(azimuth);
deltaElevation = gradient(elevation);
lengthValue = max(hypot(deltaAzimuth, deltaElevation), eps);
normalAzimuth = -deltaElevation ./ lengthValue;
normalElevation = deltaAzimuth ./ lengthValue;
end

function [azimuth, elevation] = spinningRodSlices(time_s, geometry)
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for sample = 1:numel(time_s)
    if time_s(sample) < geometry.rodActiveStart_s || ...
            time_s(sample) > geometry.rodActiveEnd_s
        azimuth{sample} = zeros(0, 1);
        elevation{sample} = zeros(0, 1);
        continue;
    end
    centerAngle_deg = geometry.rodPhase_deg + ...
        geometry.rodAngularRate_deg_s * time_s(sample);
    [azimuth{sample}, elevation{sample}] = ...
        clippedRodSector(centerAngle_deg, geometry);
end
end

function [azimuth, elevation] = clippedRodSector( ...
        centerAngle_deg, geometry)
[firstAzimuth, firstElevation] = clippedRodArm( ...
    centerAngle_deg, geometry);
[secondAzimuth, secondElevation] = clippedRodArm( ...
    centerAngle_deg + 180, geometry);
azimuth = [firstAzimuth; NaN; secondAzimuth];
elevation = [firstElevation; NaN; secondElevation];
end

function [azimuth, elevation] = clippedRodArm( ...
        centerAngle_deg, geometry)
angle = deg2rad(centerAngle_deg);
intervals = [geometry.rodHubRadius_deg geometry.rodOuterRadius_deg];
for notch = 1:size(geometry.notchCenters_deg, 1)
    center = geometry.notchCenters_deg(notch, :);
    notchRadius = hypot(center(1), center(2));
    notchAngle = atan2(center(2), center(1));
    angularAllowance = deg2rad(geometry.rodHalfAngle_deg) + ...
        asin(min(1, geometry.notchSafeRadius_deg / notchRadius));
    if abs(wrapRadians(notchAngle - angle)) <= angularAllowance
        cut = notchRadius + ...
            geometry.rodNotchCutHalfWidth_deg * [-1 1];
        intervals = subtractInterval(intervals, cut);
    end
end

azimuthParts = cell(size(intervals, 1), 1);
elevationParts = cell(size(intervals, 1), 1);
for part = 1:size(intervals, 1)
    [azimuthParts{part}, elevationParts{part}] = annularSector( ...
        intervals(part, 1), intervals(part, 2), ...
        centerAngle_deg, geometry.rodHalfAngle_deg);
end
[azimuth, elevation] = joinRegions(azimuthParts, elevationParts);
end

function output = subtractInterval(input, cut)
parts = zeros(0, 2);
for k = 1:size(input, 1)
    first = input(k, 1);
    last = input(k, 2);
    if cut(2) <= first || cut(1) >= last
        parts(end + 1, :) = [first last]; %#ok<AGROW>
        continue;
    end
    if cut(1) > first
        parts(end + 1, :) = [first min(cut(1), last)]; %#ok<AGROW>
    end
    if cut(2) < last
        parts(end + 1, :) = [max(cut(2), first) last]; %#ok<AGROW>
    end
end
output = parts(diff(parts, 1, 2) > 1e-6, :);
end

function [azimuth, elevation] = annularSector( ...
        innerRadius, outerRadius, centerAngle_deg, halfAngle_deg)
angle = deg2rad(linspace( ...
    centerAngle_deg - halfAngle_deg, ...
    centerAngle_deg + halfAngle_deg, 7)).';
outerAzimuth = outerRadius * cos(angle);
outerElevation = outerRadius * sin(angle);
innerAngle = flipud(angle);
innerAzimuth = innerRadius * cos(innerAngle);
innerElevation = innerRadius * sin(innerAngle);
azimuth = [outerAzimuth; innerAzimuth; outerAzimuth(1)];
elevation = [outerElevation; innerElevation; outerElevation(1)];
end

function [azimuth, elevation] = joinRegions( ...
        azimuthParts, elevationParts)
if isempty(azimuthParts)
    azimuth = zeros(0, 1);
    elevation = zeros(0, 1);
    return;
end
regionCount = numel(azimuthParts);
total = sum(cellfun(@numel, azimuthParts)) + regionCount - 1;
azimuth = nan(total, 1);
elevation = nan(total, 1);
cursor = 1;
for region = 1:regionCount
    count = numel(azimuthParts{region});
    output = cursor:cursor + count - 1;
    azimuth(output) = azimuthParts{region};
    elevation(output) = elevationParts{region};
    cursor = cursor + count + 1;
end
end

function angle = wrapRadians(angle)
angle = mod(angle + pi, 2 * pi) - pi;
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
