function problem = makeRotatingSlotGauntlet()
%% Section 0: Header & Readme
% SYNTAX
%   problem = makeRotatingSlotGauntlet()
%**************************************************************************
% PURPOSE
%   - Create four independently rotating slotted rings whose intervening
%     annular chambers permit explicit waiting.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - problem (scalar struct)
%       Canonical obstacles, endpoint states, limits, options, and geometry.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Define Ring Geometry & Timing
time_s = (0:1:90).';
innerRadius_deg = [10 7 4 1];
outerRadius_deg = [11 8 5 2];
slotWidth_deg = [80 80 80 80];
angularRate_deg_s = [3 -4 5 -6];
nominalCrossingTime_s = [12 32 52 72];
phase_deg = -angularRate_deg_s .* nominalCrossingTime_s;
verticesPerArc = 18;

%% Section 2: Sample Every Rotating Ring
azElData = cell(1, 4);
for ringIndex = 1:numel(innerRadius_deg)
    azimuth_deg = cell(numel(time_s), 1);
    elevation_deg = cell(numel(time_s), 1);
    for sampleIndex = 1:numel(time_s)
        slotCenter_deg = phase_deg(ringIndex) + ...
            angularRate_deg_s(ringIndex) * time_s(sampleIndex);
        [azimuth_deg{sampleIndex}, elevation_deg{sampleIndex}] = slottedRing( ...
            innerRadius_deg(ringIndex), outerRadius_deg(ringIndex), ...
            slotCenter_deg, slotWidth_deg(ringIndex), verticesPerArc);
    end
    azElData{ringIndex} = makeAzElObstacleData( ...
        sprintf('Rotating slot %d', ringIndex), ...
        time_s, azimuth_deg, elevation_deg);
end

%% Section 3: Assemble The Planning Problem
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [12.5 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stopState = struct( ...
    "time_s", 90, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-14 14], ...
    "elevation_deg", [-14 14], ...
    "maxVelocity_deg_s", [1.5 1.5], ...
    "maxAcceleration_deg_s2", [0.75 0.75]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.1, ...
    "GridStep_deg", 0.5, ...
    ... % Cardinal chamber transitions keep this concentric graph compact.
    "PrimitiveRadii_deg", [2 4], ...
    "DirectionStep_deg", 90, ...
    "CollisionCheckStep_s", 0.4, ...
    "MaximumSafeIntervalSamples", 23, ...
    "MaximumDepartureTrials", 3, ...
    "DepartureBatchSize", 3, ...
    "MaxExpansions", 150000, ...
    "SafetyMargin_deg", 0.5, ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 30);
geometry = struct( ...
    "innerRadius_deg", innerRadius_deg, ...
    "outerRadius_deg", outerRadius_deg, ...
    "slotWidth_deg", slotWidth_deg, ...
    "angularRate_deg_s", angularRate_deg_s, ...
    "phase_deg", phase_deg, ...
    "nominalCrossingTime_s", nominalCrossingTime_s);
problem = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

%% Section 4: Local Geometry Functions
% Ring construction stays separate because it maps polar slot geometry to
% one closed polygon and would interrupt the scenario sampling loop above.
function [azimuth_deg, elevation_deg] = slottedRing( ...
        innerRadius_deg, outerRadius_deg, slotCenter_deg, slotWidth_deg, ...
        verticesPerArc)
halfSlot_rad = deg2rad(slotWidth_deg / 2);
slotCenter_rad = deg2rad(slotCenter_deg);
blockedAngle_rad = linspace( ...
    slotCenter_rad + halfSlot_rad, ...
    slotCenter_rad + 2 * pi - halfSlot_rad, verticesPerArc).';
outerAzimuth_deg = outerRadius_deg * cos(blockedAngle_rad);
outerElevation_deg = outerRadius_deg * sin(blockedAngle_rad);
innerAngle_rad = flipud(blockedAngle_rad);
innerAzimuth_deg = innerRadius_deg * cos(innerAngle_rad);
innerElevation_deg = innerRadius_deg * sin(innerAngle_rad);
azimuth_deg = [ ...
    outerAzimuth_deg; innerAzimuth_deg; outerAzimuth_deg(1)];
elevation_deg = [ ...
    outerElevation_deg; innerElevation_deg; outerElevation_deg(1)];
end
