function problem = makeRotatingSlotGauntlet()
%MAKEROTATINGSLOTGAUNTLET Create four independently rotating slotted rings.
%
% The generated case is standalone canonical azElData. A boresight begins
% outside four concentric C-shaped barriers and must time each slot crossing.
% The annular voids between rings provide safe places to wait.

time_s = (0:1:90).';
innerRadius_deg = [10 7 4 1];
outerRadius_deg = [11 8 5 2];
slotWidth_deg = [80 80 80 80];
angularRate_deg_s = [3 -4 5 -6];
nominalCrossingTime_s = [12 32 52 72];
phase_deg = -angularRate_deg_s .* nominalCrossingTime_s;
verticesPerArc = 18;

azElData = cell(1, 4);
for ring = 1:4
    azimuth = cell(numel(time_s), 1);
    elevation = cell(numel(time_s), 1);
    for sample = 1:numel(time_s)
        slotCenter_deg = phase_deg(ring) + ...
            angularRate_deg_s(ring) * time_s(sample);
        [azimuth{sample}, elevation{sample}] = slottedRing( ...
            innerRadius_deg(ring), outerRadius_deg(ring), ...
            slotCenter_deg, slotWidth_deg(ring), verticesPerArc);
    end
    azElData{ring} = makeAzElObstacleData( ...
        sprintf('Rotating slot %d', ring), ...
        time_s, azimuth, elevation);
end

startState = boundaryState(0, [12.5 0]);
stopState = boundaryState(90, [0 0]);
limits = struct( ...
    "azimuth_deg", [-14 14], ...
    "elevation_deg", [-14 14], ...
    "maxVelocity_deg_s", [1.5 1.5], ...
    "maxAcceleration_deg_s2", [0.75 0.75]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.1, ...
    "GridStep_deg", 0.5, ...
    "PrimitiveRadii_deg", [1 2 4], ...
    "HeuristicWeight", 8, ...
    "CollisionCheckStep_s", 0.2, ...
    "MaximumSafeIntervalSamples", 46, ...
    "MaximumDepartureTrials", 8, ...
    "DepartureBatchSize", 2, ...
    "MaxExpansions", 150000, ...
    "SafetyMargin_deg", 0.5, ...
    "MaxSearchTime_s", 50);
geometry = struct( ...
    "innerRadius_deg", innerRadius_deg, ...
    "outerRadius_deg", outerRadius_deg, ...
    "slotWidth_deg", slotWidth_deg, ...
    "angularRate_deg_s", angularRate_deg_s, ...
    "phase_deg", phase_deg, ...
    "nominalCrossingTime_s", nominalCrossingTime_s);
problem = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

function [azimuth_deg, elevation_deg] = slottedRing( ...
        innerRadius, outerRadius, slotCenter_deg, slotWidth_deg, ...
        verticesPerArc)
halfSlot = deg2rad(slotWidth_deg / 2);
slotCenter = deg2rad(slotCenter_deg);
blockedAngle = linspace( ...
    slotCenter + halfSlot, ...
    slotCenter + 2 * pi - halfSlot, verticesPerArc).';
outerAzimuth = outerRadius * cos(blockedAngle);
outerElevation = outerRadius * sin(blockedAngle);
innerAngle = flipud(blockedAngle);
innerAzimuth = innerRadius * cos(innerAngle);
innerElevation = innerRadius * sin(innerAngle);
azimuth_deg = [ ...
    outerAzimuth; innerAzimuth; outerAzimuth(1)];
elevation_deg = [ ...
    outerElevation; innerElevation; outerElevation(1)];
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
