function problem = makeSpinningRodSpiralGauntlet()
%% Section 0: Header & Readme
% SYNTAX
%   problem = makeSpinningRodSpiralGauntlet()
%**************************************************************************
% PURPOSE
%   - Build a notched two-turn spiral and a faster rotating two-arm sector.
%   - Preserve safe recesses where the boresight can wait for the rod.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - problem (scalar struct)
%       Canonical obstacles, endpoint states, limits, options, and geometry.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees except fields ending in _rad.
%   - Temporal quantities are seconds.

%% Section 1: Define The Time Base & Geometry
activeTime_s = (0:0.25:15.50).';
time_s = [activeTime_s; 240];
geometry = struct( ...
    "turnCount", 2, ...
    "innerRadius_deg", 2, ...
    "turnSpacing_deg", 6, ...
    "wallHalfWidth_deg", 0.60, ...
    "wallSampleCount", 181, ...
    "notchTheta_rad", pi * [3.45 2.25 1.05], ...
    "notchDepth_deg", 1.00, ...
    "notchAngularSigma_rad", 0.18, ...
    "notchSafeRadius_deg", 0.65, ...
    "rodHubRadius_deg", 1.35, ...
    "rodOuterRadius_deg", 17, ...
    "rodHalfAngle_deg", 30, ...
    "rodAngularRate_deg_s", 60, ...
    "rodPhase_deg", 90, ...
    "rodActiveStart_s", 0, ...
    "rodActiveEnd_s", 15, ...
    "rodNotchCutHalfWidth_deg", 1.30);

%% Section 2: Build The Static Spiral & Moving Rod
[wallAzimuth_deg, wallElevation_deg, notchCenters_deg] = notchedSpiralWall( ...
    geometry);
geometry.notchCenters_deg = notchCenters_deg;
[rodAzimuth_deg, rodElevation_deg] = spinningRodSlices( ...
    time_s, geometry);

wall = makeAzElObstacleData( ...
    "Notched two-turn spiral wall", time_s([1 end]), ...
    wallAzimuth_deg, wallElevation_deg);
rod = makeAzElObstacleData( ...
    "Fast spinning rod", time_s, rodAzimuth_deg, rodElevation_deg);
azElData = combineAzElObstacles(wall, rod);

%% Section 3: Assemble The Planning Problem
startState = struct( ...
    "time_s", 0, ...
    "position_deg", notchCenters_deg(1, :), ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stopState = struct( ...
    "time_s", 240, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-18 18], ...
    "elevation_deg", [-18 18], ...
    "maxVelocity_deg_s", [0.8 0.8], ...
    "maxAcceleration_deg_s2", [1.2 1.2]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "ValidationStep_s", 0.08, ...
    "GridStep_deg", 2, ...
    "GridStepSchedule_deg", 2, ...
    "PrimitiveRadii_deg", 2, ...
    "SafetyMargin_deg", 0.20, ...
    "Objective", "minimumAngularDistance", ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "CollisionCheckStep_s", 0.08, ...
    "MaximumSafeIntervalSamples", 150, ...
    "MaximumDepartureTrials", 8, ...
    "DepartureBatchSize", 4, ...
    "MaxExpansions", 300000, ...
    "MaxSearchTime_s", 150, ...
    "AllowAzimuthWrap", false);

problem = struct( ...
    "azElData", azElData, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

%% Section 4: Local Geometry Functions
% These routines share the spiral/rod geometric invariants. Keeping them
% local prevents the scenario assembly above from becoming a vertex-level
% implementation while avoiding extra single-purpose files.
function [azimuth_deg, elevation_deg, notchCenters_deg] = notchedSpiralWall(geometry)
theta_rad = linspace( ...
    0, 2 * pi * geometry.turnCount, ...
    geometry.wallSampleCount).';
radius_deg = geometry.innerRadius_deg + ...
    geometry.turnSpacing_deg * theta_rad / (2 * pi);
baseAzimuth_deg = radius_deg .* cos(theta_rad);
baseElevation_deg = radius_deg .* sin(theta_rad);
[normalAzimuth, normalElevation] = curveNormals( ...
    baseAzimuth_deg, baseElevation_deg);

notchCenters_deg = zeros(numel(geometry.notchTheta_rad), 2);
normalShift_deg = zeros(size(theta_rad));
for notchIndex = 1:numel(geometry.notchTheta_rad)
    notchCenterTheta_rad = geometry.notchTheta_rad(notchIndex);
    notchWeight = exp(-0.5 * ((theta_rad - notchCenterTheta_rad) ./ ...
        geometry.notchAngularSigma_rad).^2);
    normalShift_deg = normalShift_deg + ...
        geometry.notchDepth_deg * notchWeight;
    notchCenterRadius_deg = geometry.innerRadius_deg + ...
        geometry.turnSpacing_deg * notchCenterTheta_rad / (2 * pi);
    notchCenters_deg(notchIndex, :) = notchCenterRadius_deg * ...
        [cos(notchCenterTheta_rad) sin(notchCenterTheta_rad)];
end

% Shift the wall toward the inner neighboring turn. On the traversed side,
% this produces a smooth recess without opening a shortcut through the wall.
centerAzimuth_deg = baseAzimuth_deg + normalShift_deg .* normalAzimuth;
centerElevation_deg = baseElevation_deg + normalShift_deg .* normalElevation;
[shiftedNormalAzimuth, shiftedNormalElevation] = curveNormals( ...
    centerAzimuth_deg, centerElevation_deg);
wallHalfWidth_deg = geometry.wallHalfWidth_deg;
leftAzimuth_deg = centerAzimuth_deg + ...
    wallHalfWidth_deg * shiftedNormalAzimuth;
leftElevation_deg = centerElevation_deg + ...
    wallHalfWidth_deg * shiftedNormalElevation;
rightAzimuth_deg = centerAzimuth_deg - ...
    wallHalfWidth_deg * shiftedNormalAzimuth;
rightElevation_deg = centerElevation_deg - ...
    wallHalfWidth_deg * shiftedNormalElevation;
azimuth_deg = [ ...
    leftAzimuth_deg; flipud(rightAzimuth_deg); leftAzimuth_deg(1)];
elevation_deg = [ ...
    leftElevation_deg; flipud(rightElevation_deg); leftElevation_deg(1)];
end

function [normalAzimuth, normalElevation] = curveNormals( ...
        azimuth_deg, elevation_deg)
tangentAzimuth_deg = gradient(azimuth_deg);
tangentElevation_deg = gradient(elevation_deg);
tangentMagnitude_deg = max( ...
    hypot(tangentAzimuth_deg, tangentElevation_deg), eps);
normalAzimuth = -tangentElevation_deg ./ tangentMagnitude_deg;
normalElevation = tangentAzimuth_deg ./ tangentMagnitude_deg;
end

function [azimuth_deg, elevation_deg] = spinningRodSlices( ...
        time_s, geometry)
azimuth_deg = cell(numel(time_s), 1);
elevation_deg = cell(numel(time_s), 1);
for sampleIndex = 1:numel(time_s)
    rodIsInactive = time_s(sampleIndex) < geometry.rodActiveStart_s || ...
        time_s(sampleIndex) > geometry.rodActiveEnd_s;
    if rodIsInactive
        azimuth_deg{sampleIndex} = zeros(0, 1);
        elevation_deg{sampleIndex} = zeros(0, 1);
        continue;
    end
    rodCenterAngle_deg = geometry.rodPhase_deg + ...
        geometry.rodAngularRate_deg_s * time_s(sampleIndex);
    [azimuth_deg{sampleIndex}, elevation_deg{sampleIndex}] = clippedRodSector( ...
        rodCenterAngle_deg, geometry);
end
end

function [azimuth_deg, elevation_deg] = clippedRodSector( ...
        centerAngle_deg, geometry)
[firstAzimuth_deg, firstElevation_deg] = clippedRodArm( ...
    centerAngle_deg, geometry);
[secondAzimuth_deg, secondElevation_deg] = clippedRodArm( ...
    centerAngle_deg + 180, geometry);
azimuth_deg = [firstAzimuth_deg; NaN; secondAzimuth_deg];
elevation_deg = [firstElevation_deg; NaN; secondElevation_deg];
end

function [azimuth_deg, elevation_deg] = clippedRodArm( ...
        centerAngle_deg, geometry)
centerAngle_rad = deg2rad(centerAngle_deg);
radialIntervals_deg = [ ...
    geometry.rodHubRadius_deg geometry.rodOuterRadius_deg];
for notchIndex = 1:size(geometry.notchCenters_deg, 1)
    notchCenter_deg = geometry.notchCenters_deg(notchIndex, :);
    notchRadius_deg = hypot(notchCenter_deg(1), notchCenter_deg(2));
    notchAngle_rad = atan2(notchCenter_deg(2), notchCenter_deg(1));
    angularAllowance_rad = deg2rad(geometry.rodHalfAngle_deg) + ...
        asin(min(1, geometry.notchSafeRadius_deg / notchRadius_deg));
    notchIntersectsArm = abs(wrapRadians( ...
        notchAngle_rad - centerAngle_rad)) <= angularAllowance_rad;
    if notchIntersectsArm
        cutInterval_deg = notchRadius_deg + ...
            geometry.rodNotchCutHalfWidth_deg * [-1 1];
        radialIntervals_deg = subtractInterval( ...
            radialIntervals_deg, cutInterval_deg);
    end
end

azimuthParts_deg = cell(size(radialIntervals_deg, 1), 1);
elevationParts_deg = cell(size(radialIntervals_deg, 1), 1);
for intervalIndex = 1:size(radialIntervals_deg, 1)
    [azimuthParts_deg{intervalIndex}, ...
            elevationParts_deg{intervalIndex}] = annularSector( ...
        radialIntervals_deg(intervalIndex, 1), ...
        radialIntervals_deg(intervalIndex, 2), ...
        centerAngle_deg, geometry.rodHalfAngle_deg);
end
[azimuth_deg, elevation_deg] = joinRegions( ...
    azimuthParts_deg, elevationParts_deg);
end

function remainingIntervals_deg = subtractInterval( ...
        inputIntervals_deg, cutInterval_deg)
remainingIntervals_deg = zeros(0, 2);
for intervalIndex = 1:size(inputIntervals_deg, 1)
    intervalFirst_deg = inputIntervals_deg(intervalIndex, 1);
    intervalLast_deg = inputIntervals_deg(intervalIndex, 2);
    intervalsDoNotOverlap = cutInterval_deg(2) <= intervalFirst_deg || ...
        cutInterval_deg(1) >= intervalLast_deg;
    if intervalsDoNotOverlap
        remainingIntervals_deg(end + 1, :) = [ ...
            intervalFirst_deg intervalLast_deg]; %#ok<AGROW>
        continue;
    end
    if cutInterval_deg(1) > intervalFirst_deg
        remainingIntervals_deg(end + 1, :) = [ ...
            intervalFirst_deg, ...
            min(cutInterval_deg(1), intervalLast_deg)]; %#ok<AGROW>
    end
    if cutInterval_deg(2) < intervalLast_deg
        remainingIntervals_deg(end + 1, :) = [ ...
            max(cutInterval_deg(2), intervalFirst_deg), ...
            intervalLast_deg]; %#ok<AGROW>
    end
end
intervalHasLength = diff(remainingIntervals_deg, 1, 2) > 1e-6;
remainingIntervals_deg = remainingIntervals_deg(intervalHasLength, :);
end

function [azimuth_deg, elevation_deg] = annularSector( ...
        innerRadius_deg, outerRadius_deg, centerAngle_deg, halfAngle_deg)
angle_rad = deg2rad(linspace( ...
    centerAngle_deg - halfAngle_deg, ...
    centerAngle_deg + halfAngle_deg, 7)).';
outerAzimuth_deg = outerRadius_deg * cos(angle_rad);
outerElevation_deg = outerRadius_deg * sin(angle_rad);
innerAngle_rad = flipud(angle_rad);
innerAzimuth_deg = innerRadius_deg * cos(innerAngle_rad);
innerElevation_deg = innerRadius_deg * sin(innerAngle_rad);
azimuth_deg = [ ...
    outerAzimuth_deg; innerAzimuth_deg; outerAzimuth_deg(1)];
elevation_deg = [ ...
    outerElevation_deg; innerElevation_deg; outerElevation_deg(1)];
end

function [azimuth_deg, elevation_deg] = joinRegions( ...
        azimuthParts_deg, elevationParts_deg)
if isempty(azimuthParts_deg)
    azimuth_deg = zeros(0, 1);
    elevation_deg = zeros(0, 1);
    return;
end
regionCount = numel(azimuthParts_deg);
regionVertexCount = zeros(regionCount, 1);
for regionIndex = 1:regionCount
    regionVertexCount(regionIndex) = numel(azimuthParts_deg{regionIndex});
end
packedVertexCount = sum(regionVertexCount) + regionCount - 1;
azimuth_deg = nan(packedVertexCount, 1);
elevation_deg = nan(packedVertexCount, 1);
nextOutputRow = 1;
for regionIndex = 1:regionCount
    outputRows = nextOutputRow:( ...
        nextOutputRow + regionVertexCount(regionIndex) - 1);
    azimuth_deg(outputRows) = azimuthParts_deg{regionIndex};
    elevation_deg(outputRows) = elevationParts_deg{regionIndex};
    nextOutputRow = outputRows(end) + 2;
end
end

function wrappedAngle_rad = wrapRadians(angle_rad)
wrappedAngle_rad = mod(angle_rad + pi, 2 * pi) - pi;
end
