function problem = makeWorldsHardestWindmillGauntlet()
%% Section 0: Header & Readme
% SYNTAX
%   problem = makeWorldsHardestWindmillGauntlet()
%**************************************************************************
% PURPOSE
%   - Create a level-6-inspired S corridor with eight synchronized dotted
%     windmills and no coin-collection constraints.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - problem (scalar struct)
%       Canonical obstacles, endpoint states, limits, options, and geometry.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Define The Corridor & Windmill Motion
time_s = (0:1:100).';
angularRate_deg_s = 12;
topCenters = [-12 4; -4 4; 4 4; 12 4];
bottomCenters = [12 -4; 4 -4; -4 -4; -12 -4];
centers_deg = [topCenters; bottomCenters];
phase_deg = [0 22.5 45 67.5 67.5 45 22.5 0];

%% Section 2: Build Static Corridor Walls
[wallAzimuth_deg, wallElevation_deg] = corridorWalls();
walls = makeAzElObstacleData( ...
    "Level 6 corridor walls", time_s, ...
    wallAzimuth_deg, wallElevation_deg);

%% Section 3: Sample The Synchronized Windmills
windmills = cell(1, size(centers_deg, 1));
for windmillIndex = 1:size(centers_deg, 1)
    azimuth_deg = cell(numel(time_s), 1);
    elevation_deg = cell(numel(time_s), 1);
    for sampleIndex = 1:numel(time_s)
        windmillAngle_deg = phase_deg(windmillIndex) + ...
            angularRate_deg_s * time_s(sampleIndex);
        [azimuth_deg{sampleIndex}, elevation_deg{sampleIndex}] = windmillBoundary( ...
            centers_deg(windmillIndex, :), windmillAngle_deg);
    end
    windmills{windmillIndex} = makeAzElObstacleData( ...
        sprintf('Windmill %d', windmillIndex), ...
        time_s, azimuth_deg, elevation_deg);
end
azElData = [{walls}, windmills];

%% Section 4: Assemble The Planning Problem
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-16 4], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stopState = struct( ...
    "time_s", 100, ...
    "position_deg", [-16 -4], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-18 18], ...
    "elevation_deg", [-8 8], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.2, ...
    "GridStep_deg", 1, ...
    "PrimitiveRadii_deg", [2 4 8], ...
    "CollisionCheckStep_s", 0.4, ...
    "MaximumSafeIntervalSamples", 51, ...
    "MaximumDepartureTrials", 4, ...
    "DepartureBatchSize", 2, ...
    "MaxExpansions", 250000, ...
    "SafetyMargin_deg", 0.15, ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaximumVerticesPerRegion", 500, ...
    "MaxSearchTime_s", 60);
geometry = struct( ...
    "centers_deg", centers_deg, ...
    "angularRate_deg_s", ...
    repmat(angularRate_deg_s, 1, size(centers_deg, 1)), ...
    "phase_deg", phase_deg, ...
    "bladeCount", 4, ...
    "bladeRadii_deg", [0.75 1.5 2.25], ...
    "dotRadius_deg", 0.34, ...
    "rightConnectorAzimuth_deg", 14);
problem = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

%% Section 5: Local Geometry Functions
% The retained helpers define reusable geometric invariants within this
% generator; keeping them here leaves the time-sampling stages readable.
function [azimuth_deg, elevation_deg] = corridorWalls()
regions = { ...
    rectangleVertices([-18 18], [7 8]), ...
    rectangleVertices([-18 18], [-8 -7]), ...
    rectangleVertices([-18 -17], [-7 7]), ...
    rectangleVertices([17 18], [-7 7]), ...
    rectangleVertices([-17 14], [-1 1])};
[azimuth_deg, elevation_deg] = joinRegions(regions);
end

function [azimuth_deg, elevation_deg] = windmillBoundary( ...
        center_deg, angle_deg)
bladeCount = 4;
bladeRadii_deg = [0.75 1.5 2.25];
dotRadius_deg = 0.34;
diskVertexCount = 10;
regions = cell(1, 1 + bladeCount * numel(bladeRadii_deg));
regions{1} = diskVertices(center_deg, dotRadius_deg, diskVertexCount);
regionWriteIndex = 1;
for bladeIndex = 0:bladeCount - 1
    bladeAngle_rad = deg2rad( ...
        angle_deg + bladeIndex * 360 / bladeCount);
    bladeDirection = [cos(bladeAngle_rad), sin(bladeAngle_rad)];
    for bladeRadius_deg = bladeRadii_deg
        regionWriteIndex = regionWriteIndex + 1;
        regions{regionWriteIndex} = diskVertices( ...
            center_deg + bladeRadius_deg * bladeDirection, ...
            dotRadius_deg, diskVertexCount);
    end
end
[azimuth_deg, elevation_deg] = joinRegions(regions);
end

function vertices_deg = diskVertices(center_deg, radius_deg, vertexCount)
angle_rad = linspace(0, 2 * pi, vertexCount + 1).';
vertices_deg = center_deg + ...
    radius_deg * [cos(angle_rad), sin(angle_rad)];
end

function vertices_deg = rectangleVertices( ...
        azimuthLimits_deg, elevationLimits_deg)
vertices_deg = [ ...
    azimuthLimits_deg(1), elevationLimits_deg(1); ...
    azimuthLimits_deg(2), elevationLimits_deg(1); ...
    azimuthLimits_deg(2), elevationLimits_deg(2); ...
    azimuthLimits_deg(1), elevationLimits_deg(2); ...
    azimuthLimits_deg(1), elevationLimits_deg(1)];
end

function [azimuth_deg, elevation_deg] = joinRegions(regions_deg)
regionCount = numel(regions_deg);
regionRowCount = zeros(regionCount, 1);
for regionIndex = 1:regionCount
    regionRowCount(regionIndex) = size(regions_deg{regionIndex}, 1);
end
packedRowCount = sum(regionRowCount) + regionCount - 1;
combinedBoundary_deg = nan(packedRowCount, 2);
nextOutputRow = 1;
for regionIndex = 1:regionCount
    regionRows = nextOutputRow:( ...
        nextOutputRow + regionRowCount(regionIndex) - 1);
    combinedBoundary_deg(regionRows, :) = regions_deg{regionIndex};
    nextOutputRow = regionRows(end) + 2;
end
azimuth_deg = combinedBoundary_deg(:, 1);
elevation_deg = combinedBoundary_deg(:, 2);
end
