function problem = makeRandomBlinkingChessboardGauntlet(seed, input)
%% Section 0: Header & Readme
% SYNTAX
%   problem = makeRandomBlinkingChessboardGauntlet()
%   problem = makeRandomBlinkingChessboardGauntlet(seed)
%   problem = makeRandomBlinkingChessboardGauntlet(seed, input)
%**************************************************************************
% PURPOSE
%   - Generate one reproducible stochastic moving-target interception on a
%     blinking checkerboard obstacle field.
%**************************************************************************
% INPUTS
%   - seed (positive integer or empty)
%       Random seed. Empty selects a fresh seed without changing the
%       caller's global random stream.
%   - input (scalar struct)
%       Partial generation options. Empty fields receive defaults.
%**************************************************************************
% OUTPUTS
%   - problem (scalar struct)
%       Canonical obstacles, initial state, target, limits, planner options,
%       seed, and generation geometry.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Resolve & Validate Generation Inputs
if nargin < 1 || isempty(seed)
    callerRandomState = rng;
    rng("shuffle");
    seed = randi([1, intmax("int32")]);
    rng(callerRandomState);
end
if nargin < 2
    input = struct();
end
validateattributes(seed, {'numeric'}, ...
    {'scalar', 'integer', 'positive', '<=', intmax("int32")});

defaultGenerationOptions = struct( ...
    "RowCount", 5, ...
    "ColumnCount", 7, ...
    "CellSize_deg", 2, ...
    "TimeStep_s", 0.5, ...
    "Horizon_s", 50, ...
    "MinimumSwitchInterval_s", 4.5, ...
    "MaximumSwitchInterval_s", 6.5, ...
    "OverlapDuration_s", 2, ...
    "TransitionJitter_s", 0.25, ...
    "DropoutProbability", 0.12, ...
    "DropoutDuration_s", 0.5);
generationOptions = input;
defaultOptionNames = fieldnames(defaultGenerationOptions);
for optionIndex = 1:numel(defaultOptionNames)
    optionName = defaultOptionNames{optionIndex};
    if ~isfield(generationOptions, optionName) || ...
            isempty(generationOptions.(optionName))
        defaultOptionValue = defaultGenerationOptions.(optionName);
        generationOptions.(optionName) = defaultOptionValue;
    end
end

positiveIntegerOptions = ["RowCount", "ColumnCount"];
for optionName = positiveIntegerOptions
    validateattributes(generationOptions.(optionName), {'numeric'}, ...
        {'scalar', 'integer', '>=', 3});
end
positiveOptions = ["CellSize_deg", "TimeStep_s", "Horizon_s", ...
    "MinimumSwitchInterval_s", "MaximumSwitchInterval_s", ...
    "OverlapDuration_s", "DropoutDuration_s"];
for optionName = positiveOptions
    validateattributes(generationOptions.(optionName), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(generationOptions.TransitionJitter_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(generationOptions.DropoutProbability, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', 1});
switchRangeIsReversed = generationOptions.MaximumSwitchInterval_s < ...
    generationOptions.MinimumSwitchInterval_s;
minimumOverlapDuration_s = 2 * generationOptions.TransitionJitter_s;
overlapSurplus_s = generationOptions.OverlapDuration_s - ...
    minimumOverlapDuration_s;
overlapCannotAbsorbJitter = overlapSurplus_s <= 0;
if switchRangeIsReversed || overlapCannotAbsorbJitter
    error("makeRandomBlinkingChessboardGauntlet:InvalidTiming", ...
        "Switch intervals and overlap/jitter settings are inconsistent.");
end

%% Section 2: Build The Board Geometry
randomStream = RandStream("mt19937ar", "Seed", double(seed));
time_s = (0:generationOptions.TimeStep_s: ...
    generationOptions.Horizon_s).';
rowCount = generationOptions.RowCount;
columnCount = generationOptions.ColumnCount;
cellSize_deg = generationOptions.CellSize_deg;
azimuthCenters_deg = ((1:columnCount) - (columnCount + 1) / 2) * ...
    cellSize_deg;
elevationCenters_deg = ((1:rowCount) - (rowCount + 1) / 2) * ...
    cellSize_deg;
[columnGrid, rowGrid] = meshgrid(1:columnCount, 1:rowCount);
cellRow = rowGrid(:);
cellColumn = columnGrid(:);
cellCenters_deg = [ ...
    azimuthCenters_deg(cellColumn).', ...
    elevationCenters_deg(cellRow).'];
cellParity = mod(cellRow + cellColumn, 2);

%% Section 3: Generate The Blinking Schedule
% The random draw order in this section is part of seeded reproducibility.
% Cases are never regenerated based on whether the planner later succeeds.
switchTimes_s = zeros(0, 1);
nextSwitchTime_s = generationOptions.MinimumSwitchInterval_s + ...
    rand(randomStream) * (generationOptions.MaximumSwitchInterval_s - ...
    generationOptions.MinimumSwitchInterval_s);
latestSwitchTime_s = generationOptions.Horizon_s - ...
    generationOptions.OverlapDuration_s;
while nextSwitchTime_s < latestSwitchTime_s
    nextSwitchTime_s = round( ...
        nextSwitchTime_s / generationOptions.TimeStep_s) * ...
        generationOptions.TimeStep_s;
    if isempty(switchTimes_s) || nextSwitchTime_s > switchTimes_s(end)
        switchTimes_s(end + 1, 1) = nextSwitchTime_s; %#ok<AGROW>
    end
    nextSwitchTime_s = nextSwitchTime_s + ...
        generationOptions.MinimumSwitchInterval_s + ...
        rand(randomStream) * ( ...
        generationOptions.MaximumSwitchInterval_s - ...
        generationOptions.MinimumSwitchInterval_s);
end

initialOpenParity = randi(randomStream, 2) - 1;
sampleCount = numel(time_s);
cellCount = numel(cellParity);
cellOpen = repmat( ...
    cellParity(:).' == initialOpenParity, sampleCount, 1);
activeOpenParity = initialOpenParity;
for switchIndex = 1:numel(switchTimes_s)
    nextOpenParity = 1 - activeOpenParity;
    openingCellIndices = find(cellParity == nextOpenParity);
    closingCellIndices = find(cellParity == activeOpenParity);
    cellOpenTime_s = switchTimes_s(switchIndex) - ...
        generationOptions.OverlapDuration_s + ...
        generationOptions.TransitionJitter_s * ...
        rand(randomStream, numel(openingCellIndices), 1);
    cellCloseTime_s = switchTimes_s(switchIndex) - ...
        generationOptions.TransitionJitter_s * ...
        rand(randomStream, numel(closingCellIndices), 1);
    for openingIndex = 1:numel(openingCellIndices)
        openingCell = openingCellIndices(openingIndex);
        cellOpen(time_s >= cellOpenTime_s(openingIndex), openingCell) = true;
    end
    for closingIndex = 1:numel(closingCellIndices)
        closingCell = closingCellIndices(closingIndex);
        cellOpen(time_s >= cellCloseTime_s(closingIndex), closingCell) = false;
    end
    activeOpenParity = nextOpenParity;
end

for cellIndex = 1:cellCount
    if rand(randomStream) >= generationOptions.DropoutProbability
        continue;
    end
    openSampleIndices = find(cellOpen(:, cellIndex) & time_s > 0);
    if isempty(openSampleIndices)
        continue;
    end
    firstDropoutSample = openSampleIndices( ...
        randi(randomStream, numel(openSampleIndices)));
    dropoutSampleCount = max(1, round( ...
        generationOptions.DropoutDuration_s / ...
        generationOptions.TimeStep_s));
    lastDropoutSample = min( ...
        sampleCount, firstDropoutSample + dropoutSampleCount - 1);
    cellOpen(firstDropoutSample:lastDropoutSample, cellIndex) = false;
end

%% Section 4: Select The Initial State & Moving Target
firstTransferWindowEnd_s = switchTimes_s(1) - ...
    generationOptions.OverlapDuration_s + ...
    generationOptions.TransitionJitter_s;
firstTransferTolerance_s = firstTransferWindowEnd_s + 1e-9;
isInsideFirstTransferWindow = time_s <= firstTransferTolerance_s;
isSafeThroughFirstTransfer = all( ...
    cellOpen(isInsideFirstTransferWindow, :), 1).';
leftCandidateCells = find( ...
    cellColumn <= 2 & isSafeThroughFirstTransfer);
if isempty(leftCandidateCells)
    error("makeRandomBlinkingChessboardGauntlet:NoSafeStart", ...
        "No left-side cell remains safe through the first transfer window.");
end
startCellIndex = leftCandidateCells( ...
    randi(randomStream, numel(leftCandidateCells)));
startState = struct( ...
    "time_s", 0, ...
    "position_deg", cellCenters_deg(startCellIndex, :), ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);

targetWaypointTime_s = unique([0; switchTimes_s; time_s(end)]);
rightCandidateCells = find(cellColumn >= columnCount - 1);
targetWaypointCells = zeros(numel(targetWaypointTime_s), 1);
targetWaypointCells(1) = rightCandidateCells( ...
    randi(randomStream, numel(rightCandidateCells)));
if targetWaypointCells(1) == startCellIndex
    currentRightCandidate = find( ...
        rightCandidateCells == targetWaypointCells(1), 1);
    nextRightCandidate = mod( ...
        currentRightCandidate, numel(rightCandidateCells)) + 1;
    targetWaypointCells(1) = rightCandidateCells(nextRightCandidate);
end
for waypointIndex = 2:numel(targetWaypointCells)
    previousCellIndex = targetWaypointCells(waypointIndex - 1);
    rowStep = randi(randomStream, 5) - 3;
    columnStep = randi(randomStream, 5) - 3;
    if rowStep == 0 && columnStep == 0
        columnStep = 1;
    end
    nextRow = min( ...
        rowCount, max(1, cellRow(previousCellIndex) + rowStep));
    nextColumn = min( ...
        columnCount, max(1, cellColumn(previousCellIndex) + columnStep));
    targetWaypointCells(waypointIndex) = sub2ind( ...
        [rowCount columnCount], nextRow, nextColumn);
end
targetWaypointPosition_deg = cellCenters_deg(targetWaypointCells, :);
targetPosition_deg = interp1( ...
    targetWaypointTime_s, targetWaypointPosition_deg, time_s, "linear");
target = struct( ...
    "time_s", time_s, ...
    "position_deg", targetPosition_deg, ...
    "waypointTime_s", targetWaypointTime_s, ...
    "waypointPosition_deg", targetWaypointPosition_deg);

%% Section 5: Convert Closed Cells To Canonical Obstacle Polygons
% Each closed board cell becomes one polygon region. NaN separator rows keep
% adjacent closed cells independent in the packed obstacle representation.
obstacleAzimuth_deg = cell(sampleCount, 1);
obstacleElevation_deg = cell(sampleCount, 1);
cellHalfWidth_deg = 0.49 * cellSize_deg;
for sampleIndex = 1:sampleCount
    closedCellIndices = find(~cellOpen(sampleIndex, :));
    closedCellCount = numel(closedCellIndices);
    if closedCellCount == 0
        obstacleAzimuth_deg{sampleIndex} = zeros(0, 1);
        obstacleElevation_deg{sampleIndex} = zeros(0, 1);
        continue;
    end

    rowsPerClosedCell = 5;
    separatorCount = closedCellCount - 1;
    packedRowCount = rowsPerClosedCell * closedCellCount + separatorCount;
    packedBoundary_deg = nan(packedRowCount, 2);
    packedRow = 1;
    for closedCellIndex = 1:closedCellCount
        cellCenter_deg = cellCenters_deg( ...
            closedCellIndices(closedCellIndex), :);
        cellRows = packedRow:(packedRow + rowsPerClosedCell - 1);
        packedBoundary_deg(cellRows, :) = [ ...
            cellCenter_deg(1) - cellHalfWidth_deg, ...
                cellCenter_deg(2) - cellHalfWidth_deg; ...
            cellCenter_deg(1) + cellHalfWidth_deg, ...
                cellCenter_deg(2) - cellHalfWidth_deg; ...
            cellCenter_deg(1) + cellHalfWidth_deg, ...
                cellCenter_deg(2) + cellHalfWidth_deg; ...
            cellCenter_deg(1) - cellHalfWidth_deg, ...
                cellCenter_deg(2) + cellHalfWidth_deg; ...
            cellCenter_deg(1) - cellHalfWidth_deg, ...
                cellCenter_deg(2) - cellHalfWidth_deg];
        packedRow = cellRows(end) + 2;
    end
    obstacleAzimuth_deg{sampleIndex} = packedBoundary_deg(:, 1);
    obstacleElevation_deg{sampleIndex} = packedBoundary_deg(:, 2);
end
azElData = makeAzElObstacleData( ...
    "Random blinking chessboard", time_s, ...
    obstacleAzimuth_deg, obstacleElevation_deg);

%% Section 6: Assemble The Planning Problem
limits = struct( ...
    "azimuth_deg", [min(azimuthCenters_deg), max(azimuthCenters_deg)], ...
    "elevation_deg", [min(elevationCenters_deg), ...
        max(elevationCenters_deg)], ...
    "maxVelocity_deg_s", [3 3], ...
    "maxAcceleration_deg_s2", [4 4]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "ValidationStep_s", 0.125, ...
    "GridStep_deg", cellSize_deg, ...
    "PrimitiveRadii_deg", cellSize_deg * [1 2], ...
    "CollisionCheckStep_s", 0.125, ...
    "MaximumDepartureTrials", 12, ...
    "DepartureBatchSize", 3, ...
    "MaxExpansions", 120000, ...
    "SafetyMargin_deg", 0.05, ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 9, ...
    "EarliestInterceptTime_s", 16, ...
    "LatestInterceptTime_s", generationOptions.Horizon_s, ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 12, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "CatchTolerance_deg", 0.35);
geometry = struct( ...
    "rowCount", rowCount, ...
    "columnCount", columnCount, ...
    "cellSize_deg", cellSize_deg, ...
    "cellCenters_deg", cellCenters_deg, ...
    "cellRow", cellRow, ...
    "cellColumn", cellColumn, ...
    "cellParity", cellParity, ...
    "cellOpen", cellOpen, ...
    "initialOpenParity", initialOpenParity, ...
    "switchTimes_s", switchTimes_s, ...
    "targetWaypointCells", targetWaypointCells, ...
    "generationOptions", generationOptions);
problem = struct( ...
    "seed", double(seed), ...
    "azElData", azElData, ...
    "startState", startState, ...
    "target", target, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end
