function problem = makeRandomBlinkingChessboardGauntlet(seed, input)
%MAKERANDOMBLINKINGCHESSBOARDGAUNTLET Generate one stochastic intercept.
%
% A fresh seed is drawn when seed is empty. Supplying the printed seed
% reproduces the exact field for debugging; no generated case is rejected
% or regenerated based on whether the planner can solve it.

if nargin < 1 || isempty(seed)
    previous = rng;
    rng("shuffle");
    seed = randi([1, intmax("int32")]);
    rng(previous);
end
if nargin < 2
    input = struct();
end
validateattributes(seed, {'numeric'}, ...
    {'scalar', 'integer', 'positive', '<=', intmax("int32")});
generation = applyDefaults(input, struct( ...
    "RowCount", 5, ...
    "ColumnCount", 7, ...
    "CellSize_deg", 2, ...
    "TimeStep_s", 0.5, ...
    "Horizon_s", 50, ...
    "MinimumSwitchInterval_s", 4.5, ...
    "MaximumSwitchInterval_s", 6.5, ...
    "OverlapDuration_s", 2, ...
    "TransitionJitter_s", 0.25, ...
    "DropoutProbability", 0.12, ...
    "DropoutDuration_s", 0.5));
validateGenerationOptions(generation);

stream = RandStream("mt19937ar", "Seed", double(seed));
time_s = (0:generation.TimeStep_s:generation.Horizon_s).';
rowCount = generation.RowCount;
columnCount = generation.ColumnCount;
cellSize = generation.CellSize_deg;
xCenters = ((1:columnCount) - (columnCount + 1) / 2) * cellSize;
yCenters = ((1:rowCount) - (rowCount + 1) / 2) * cellSize;
[columnGrid, rowGrid] = meshgrid(1:columnCount, 1:rowCount);
cellRow = rowGrid(:);
cellColumn = columnGrid(:);
cellCenters = [ ...
    xCenters(cellColumn).', yCenters(cellRow).'];
cellParity = mod(cellRow + cellColumn, 2);

switchTimes_s = randomSwitchTimes(stream, generation);
initialParity = randi(stream, 2) - 1;
cellOpen = blinkingSchedule( ...
    stream, time_s, switchTimes_s, cellParity, ...
    initialParity, generation);

firstTransferWindow_s = switchTimes_s(1) - ...
    generation.OverlapDuration_s + generation.TransitionJitter_s;
initialWindow = time_s <= firstTransferWindow_s + 1e-9;
safeThroughFirstTransfer = all(cellOpen(initialWindow, :), 1).';
leftCandidates = find(cellColumn <= 2 & safeThroughFirstTransfer);
if isempty(leftCandidates)
    error("makeRandomBlinkingChessboardGauntlet:NoSafeStart", ...
        "No left-side cell remains safe through the first transfer window.");
end
startCell = leftCandidates(randi(stream, numel(leftCandidates)));
startState = boundaryState(0, cellCenters(startCell, :));

[target, targetCells] = movingTarget( ...
    stream, time_s, switchTimes_s, cellCenters, ...
    cellRow, cellColumn, startCell, rowCount, columnCount);

[obstacleAzimuth, obstacleElevation] = closedCellBoundaries( ...
    cellOpen, cellCenters, cellSize);
azElData = makeAzElObstacleData( ...
    "Random blinking chessboard", time_s, ...
    obstacleAzimuth, obstacleElevation);

limits = struct( ...
    "azimuth_deg", [min(xCenters), max(xCenters)], ...
    "elevation_deg", [min(yCenters), max(yCenters)], ...
    "maxVelocity_deg_s", [3 3], ...
    "maxAcceleration_deg_s2", [4 4]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "ValidationStep_s", 0.125, ...
    "GuideGridStep_deg", cellSize, ...
    "GuidePrimitiveRadii_deg", cellSize * [1 2], ...
    "GuideHeuristicWeight", 6, ...
    "GuideCollisionCheckStep_s", 0.125, ...
    "MaximumDepartureTrials", 12, ...
    "DepartureBatchSize", 3, ...
    "GuideMaxExpansions", 120000, ...
    "GuideMaxWallTime_s", 8, ...
    "SafetyMargin_deg", 0.05, ...
    "EnableARARefinement", false, ...
    "FallbackToGlobalSearch", false, ...
    "MaxSearchTime_s", 9, ...
    "EarliestInterceptTime_s", 16, ...
    "LatestInterceptTime_s", generation.Horizon_s, ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 12, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "CatchTolerance_deg", 0.35);
geometry = struct( ...
    "rowCount", rowCount, ...
    "columnCount", columnCount, ...
    "cellSize_deg", cellSize, ...
    "cellCenters_deg", cellCenters, ...
    "cellRow", cellRow, ...
    "cellColumn", cellColumn, ...
    "cellParity", cellParity, ...
    "cellOpen", cellOpen, ...
    "initialOpenParity", initialParity, ...
    "switchTimes_s", switchTimes_s, ...
    "targetWaypointCells", targetCells, ...
    "generationOptions", generation);
problem = struct( ...
    "seed", double(seed), ...
    "azElData", azElData, ...
    "startState", startState, ...
    "target", target, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

function times = randomSwitchTimes(stream, options)
times = zeros(0, 1);
next = options.MinimumSwitchInterval_s + ...
    rand(stream) * (options.MaximumSwitchInterval_s - ...
    options.MinimumSwitchInterval_s);
while next < options.Horizon_s - options.OverlapDuration_s
    next = round(next / options.TimeStep_s) * options.TimeStep_s;
    if isempty(times) || next > times(end)
        times(end + 1, 1) = next; %#ok<AGROW>
    end
    next = next + options.MinimumSwitchInterval_s + ...
        rand(stream) * (options.MaximumSwitchInterval_s - ...
        options.MinimumSwitchInterval_s);
end
end

function cellOpen = blinkingSchedule( ...
        stream, time_s, switchTimes_s, cellParity, ...
        initialParity, options)
sampleCount = numel(time_s);
cellCount = numel(cellParity);
cellOpen = repmat(cellParity(:).' == initialParity, sampleCount, 1);
activeParity = initialParity;
for switchIndex = 1:numel(switchTimes_s)
    nextParity = 1 - activeParity;
    opens = find(cellParity == nextParity);
    closes = find(cellParity == activeParity);
    openTime = switchTimes_s(switchIndex) - ...
        options.OverlapDuration_s + ...
        options.TransitionJitter_s * rand(stream, numel(opens), 1);
    closeTime = switchTimes_s(switchIndex) - ...
        options.TransitionJitter_s * rand(stream, numel(closes), 1);
    for k = 1:numel(opens)
        cellOpen(time_s >= openTime(k), opens(k)) = true;
    end
    for k = 1:numel(closes)
        cellOpen(time_s >= closeTime(k), closes(k)) = false;
    end
    activeParity = nextParity;
end

for cellIndex = 1:cellCount
    if rand(stream) >= options.DropoutProbability
        continue;
    end
    openSamples = find(cellOpen(:, cellIndex) & time_s > 0);
    if isempty(openSamples)
        continue;
    end
    first = openSamples(randi(stream, numel(openSamples)));
    duration = max(1, round( ...
        options.DropoutDuration_s / options.TimeStep_s));
    last = min(sampleCount, first + duration - 1);
    cellOpen(first:last, cellIndex) = false;
end
end

function [target, waypointCells] = movingTarget( ...
        stream, time_s, switchTimes_s, centers, rows, columns, ...
        startCell, rowCount, columnCount)
waypointTime = unique([0; switchTimes_s; time_s(end)]);
right = find(columns >= columnCount - 1);
waypointCells = zeros(numel(waypointTime), 1);
waypointCells(1) = right(randi(stream, numel(right)));
if waypointCells(1) == startCell
    waypointCells(1) = right(mod( ...
        find(right == waypointCells(1), 1), numel(right)) + 1);
end
for k = 2:numel(waypointCells)
    previous = waypointCells(k - 1);
    rowStep = randi(stream, 5) - 3;
    columnStep = randi(stream, 5) - 3;
    if rowStep == 0 && columnStep == 0
        columnStep = 1;
    end
    nextRow = min(rowCount, max(1, rows(previous) + rowStep));
    nextColumn = min(columnCount, ...
        max(1, columns(previous) + columnStep));
    waypointCells(k) = sub2ind( ...
        [rowCount columnCount], nextRow, nextColumn);
end
waypointPosition = centers(waypointCells, :);
position = interp1(waypointTime, waypointPosition, ...
    time_s, "linear");
target = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "waypointTime_s", waypointTime, ...
    "waypointPosition_deg", waypointPosition);
end

function [azimuth, elevation] = closedCellBoundaries( ...
        cellOpen, centers, cellSize)
sampleCount = size(cellOpen, 1);
azimuth = cell(sampleCount, 1);
elevation = cell(sampleCount, 1);
halfWidth = 0.49 * cellSize;
for sample = 1:sampleCount
    closed = find(~cellOpen(sample, :));
    regions = cell(numel(closed), 1);
    for k = 1:numel(closed)
        center = centers(closed(k), :);
        regions{k} = [ ...
            center(1) - halfWidth, center(2) - halfWidth; ...
            center(1) + halfWidth, center(2) - halfWidth; ...
            center(1) + halfWidth, center(2) + halfWidth; ...
            center(1) - halfWidth, center(2) + halfWidth; ...
            center(1) - halfWidth, center(2) - halfWidth];
    end
    [azimuth{sample}, elevation{sample}] = joinRegions(regions);
end
end

function [azimuth, elevation] = joinRegions(regions)
if isempty(regions)
    azimuth = zeros(0, 1);
    elevation = zeros(0, 1);
    return;
end
count = sum(cellfun(@(region) size(region, 1), regions)) + ...
    numel(regions) - 1;
combined = nan(count, 2);
cursor = 1;
for k = 1:numel(regions)
    index = cursor:cursor + size(regions{k}, 1) - 1;
    combined(index, :) = regions{k};
    cursor = index(end) + 2;
end
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function validateGenerationOptions(options)
integerPositive = ["RowCount", "ColumnCount"];
for name = integerPositive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'integer', '>=', 3});
end
positive = ["CellSize_deg", "TimeStep_s", "Horizon_s", ...
    "MinimumSwitchInterval_s", "MaximumSwitchInterval_s", ...
    "OverlapDuration_s", "DropoutDuration_s"];
for name = positive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.TransitionJitter_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.DropoutProbability, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', 1});
if options.MaximumSwitchInterval_s < ...
        options.MinimumSwitchInterval_s || ...
        options.OverlapDuration_s <= ...
        2 * options.TransitionJitter_s
    error("makeRandomBlinkingChessboardGauntlet:InvalidTiming", ...
        "Switch intervals and overlap/jitter settings are inconsistent.");
end
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
