function problem = makeStopGoGatesGauntlet()
%MAKESTOPGOGATESGAUNTLET Three sequentially opening timed gates.
%
% Scenario data for example06StopGoGates and the planner comparison
% benchmark. Gates are closed rectangles that vanish inside their open
% windows, forcing wait-move-wait behavior.

time_s = (0:0.5:45).';
gateCenters = [-6, 0, 6];
openWindows = [8, 12; 20, 24; 32, 36];
obstacles = cell(3, 1);
for gateIndex = 1:3
    [azimuth, elevation] = temporalGate( ...
        time_s, gateCenters(gateIndex), openWindows(gateIndex, :));
    obstacles{gateIndex} = makeAzElObstacleData( ...
        "Gate " + gateIndex, time_s, azimuth, elevation);
end
problem = struct( ...
    "azElData", {combineAzElObstacles(obstacles)}, ...
    "startState", boundaryState(0, [-12, 0]), ...
    "stopState", boundaryState(45, [12, 0]), ...
    "limits", struct( ...
        "azimuth_deg", [-14, 14], ...
        "elevation_deg", [-1, 1], ...
        "maxVelocity_deg_s", [2, 2], ...
        "maxAcceleration_deg_s2", [2, 2]), ...
    "options", struct( ...
        "SampleTime_s", 0.5, ...
        "GridStep_deg", 0.5, ...
        "SafetyMargin_deg", 0.1, ...
        "AllowAzimuthWrap", false, ...
        "Objective", "minimumAngularDistance", ...
        "MaxSearchTime_s", 60, ...
        "MaxExpansions", 750000), ...
    "geometry", struct( ...
        "gateCenters_deg", gateCenters, ...
        "openWindows_s", openWindows));
end

function [azimuth, elevation] = temporalGate( ...
        time_s, centerAzimuth, openWindow)
sampleCount = numel(time_s);
azimuth = cell(sampleCount, 1);
elevation = cell(sampleCount, 1);
closedAzimuth = centerAzimuth + 0.75 * [-1; 1; 1; -1; -1];
closedElevation = [-2; -2; 2; 2; -2];
for sample = 1:sampleCount
    if time_s(sample) >= openWindow(1) && ...
            time_s(sample) <= openWindow(2)
        azimuth{sample} = zeros(0, 1);
        elevation{sample} = zeros(0, 1);
    else
        azimuth{sample} = closedAzimuth;
        elevation{sample} = closedElevation;
    end
end
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
