function problem = makeWrappedAzimuthSeamGauntlet()
%MAKEWRAPPEDAZIMUTHSEAMGAUNTLET Static blocker straddling the +/-180 seam.
%
% Scenario data for example07WrappedAzimuthSeam and the planner comparison
% benchmark. The shortest route must cross the azimuth wrap seam and detour
% in elevation around the two seam rectangles.

time_s = (0:0.5:30).';
[azimuth, elevation] = seamObstacle();
problem = struct( ...
    "azElData", makeAzElObstacleData( ...
        "Wrapped seam blocker", time_s, azimuth, elevation), ...
    "startState", boundaryState(0, [170, 0]), ...
    "stopState", boundaryState(30, [-170, 0]), ...
    "limits", struct( ...
        "azimuth_deg", [-180, 180], ...
        "elevation_deg", [-20, 20], ...
        "maxVelocity_deg_s", [2, 2], ...
        "maxAcceleration_deg_s2", [2, 2]), ...
    "options", struct( ...
        "SampleTime_s", 0.5, ...
        "GridStep_deg", 0.5, ...
        "SafetyMargin_deg", 0.5, ...
        "AllowAzimuthWrap", true, ...
        "Objective", "minimumAngularDistance", ...
        "MaxSearchTime_s", 30), ...
    "geometry", struct("blockerHalfHeight_deg", 5));
end

function [azimuth, elevation] = seamObstacle()
positive = [ ...
    174, -5; ...
    180, -5; ...
    180, 5; ...
    174, 5; ...
    174, -5];
negative = [ ...
    -180, -5; ...
    -174, -5; ...
    -174, 5; ...
    -180, 5; ...
    -180, -5];
combined = [positive; NaN, NaN; negative];
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
