function problem = makeFiveTurnSpiralGauntlet()
%MAKEFIVETURNSPIRALGAUNTLET Static five-turn spiral wall scenario.
%
% Scenario data for example05FiveTurnSpiral and the planner comparison
% benchmark. Returns azElData, startState, stopState, limits, options.

time_s = (0:0.5:400).';
[wallAzimuth_deg, wallElevation_deg] = spiralWall(5, 2, 3, 0.4, 241);
problem = struct( ...
    "azElData", makeAzElObstacleData("Five-turn spiral wall", time_s, ...
        wallAzimuth_deg, wallElevation_deg), ...
    "startState", boundaryState(0, [18, 1.5]), ...
    "stopState", boundaryState(400, [0, 0]), ...
    "limits", struct( ...
        "azimuth_deg", [-20, 20], ...
        "elevation_deg", [-20, 20], ...
        "maxVelocity_deg_s", [3, 3], ...
        "maxAcceleration_deg_s2", [3, 3]), ...
    "options", struct( ...
        "SampleTime_s", 0.5, ...
        "GridStep_deg", 0.5, ...
        "SafetyMargin_deg", 0.5, ...
        "AllowAzimuthWrap", false, ...
        "Objective", "minimumAngularDistance", ...
        "MaxSearchTime_s", 30, ...
        "MaxExpansions", 1000000, ...
        "MaximumVerticesPerRegion", 500), ...
    "geometry", struct( ...
        "turnCount", 5, ...
        "innerRadius_deg", 2, ...
        "turnSpacing_deg", 3, ...
        "wallHalfWidth_deg", 0.4));
end

function [azimuth_deg, elevation_deg] = spiralWall( ...
        turnCount, innerRadius, turnSpacing, halfWidth, sampleCount)
theta = linspace(0, 2 * pi * turnCount, sampleCount).';
radius = innerRadius + turnSpacing * theta / (2 * pi);
centerAzimuth = radius .* cos(theta);
centerElevation = radius .* sin(theta);
deltaAzimuth = gradient(centerAzimuth);
deltaElevation = gradient(centerElevation);
tangentMagnitude = hypot(deltaAzimuth, deltaElevation);
normalAzimuth = -deltaElevation ./ tangentMagnitude;
normalElevation = deltaAzimuth ./ tangentMagnitude;
leftAzimuth = centerAzimuth + halfWidth * normalAzimuth;
leftElevation = centerElevation + halfWidth * normalElevation;
rightAzimuth = centerAzimuth - halfWidth * normalAzimuth;
rightElevation = centerElevation - halfWidth * normalElevation;
azimuth_deg = [leftAzimuth; flipud(rightAzimuth); leftAzimuth(1)];
elevation_deg = [ ...
    leftElevation; flipud(rightElevation); leftElevation(1)];
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
