function problem = makeChasedBoresightGauntlet()
%% Section 0: Header & Readme
% SYNTAX
%   problem = makeChasedBoresightGauntlet()
%**************************************************************************
% PURPOSE
%   - Create a square-loop pursuit problem with a late-opening goal.
%   - Force sustained motion by making a slower cross-track barrier follow
%     the boresight corridor until the goal alcove opens.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - problem (scalar struct)
%       Canonical obstacles, endpoint states, limits, options, and geometry.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Define The Time Base & Scenario Constants
time_s = (0:1:80).';
trackHalfWidth_deg = 6;
chaserSpeed_deg_s = 2;
chaserStartDistance_deg = 40;
goalOpenTime_s = 72;

%% Section 2: Build Static Corridor Walls
[wallAzimuth_deg, wallElevation_deg] = trackWallBoundary();
walls = makeAzElObstacleData( ...
    "Square-loop walls", time_s, wallAzimuth_deg, wallElevation_deg);

%% Section 3: Sample The Pursuing Cross-Track Barrier
chaserAzimuth_deg = cell(numel(time_s), 1);
chaserElevation_deg = cell(numel(time_s), 1);
for sampleIndex = 1:numel(time_s)
    chaserTrackDistance_deg = chaserStartDistance_deg + ...
        chaserSpeed_deg_s * time_s(sampleIndex);
    [chaserCenter_deg, chaserTangent] = squareTrackState( ...
        chaserTrackDistance_deg, trackHalfWidth_deg);
    [chaserAzimuth_deg{sampleIndex}, chaserElevation_deg{sampleIndex}] = orientedRectangle( ...
        chaserCenter_deg, chaserTangent, 1.2, 2.2);
end
chaser = makeAzElObstacleData( ...
    "Pursuing barrier", time_s, chaserAzimuth_deg, chaserElevation_deg);

%% Section 4: Sample The Late-Opening Goal Gate
gateAzimuth_deg = cell(numel(time_s), 1);
gateElevation_deg = cell(numel(time_s), 1);
for sampleIndex = 1:numel(time_s)
    if time_s(sampleIndex) < goalOpenTime_s
        gateCenter_deg = [8.2 0];
    else
        gateCenter_deg = [14 0];
    end
    [gateAzimuth_deg{sampleIndex}, gateElevation_deg{sampleIndex}] = axisAlignedRectangle( ...
        gateCenter_deg, 0.45, 2.05);
end
goalGate = makeAzElObstacleData( ...
    "Late-opening goal gate", time_s, ...
    gateAzimuth_deg, gateElevation_deg);

%% Section 5: Assemble The Planning Problem
azElData = {walls, chaser, goalGate};
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-6 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stopState = struct( ...
    "time_s", 80, ...
    "position_deg", [9 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [4 4], ...
    "maxAcceleration_deg_s2", [4 4]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.2, ...
    "GridStep_deg", 1, ...
    "PrimitiveRadii_deg", [2 4 8 12], ...
    "CollisionCheckStep_s", 0.2, ...
    "MaximumSafeIntervalSamples", 81, ...
    "MaximumDepartureTrials", 4, ...
    "DepartureBatchSize", 2, ...
    "MaxExpansions", 200000, ...
    "SafetyMargin_deg", 0.1, ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 55);
geometry = struct( ...
    "trackHalfWidth_deg", trackHalfWidth_deg, ...
    "trackInnerLimit_deg", 4, ...
    "trackOuterLimit_deg", 8, ...
    "trackPerimeter_deg", 8 * trackHalfWidth_deg, ...
    "chaserSpeed_deg_s", chaserSpeed_deg_s, ...
    "chaserStartDistance_deg", chaserStartDistance_deg, ...
    "goalOpenTime_s", goalOpenTime_s, ...
    "goalPosition_deg", stopState.position_deg);
problem = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

%% Section 6: Local Geometry Functions
% These helpers each isolate a complete geometry construction. Folding them
% into the sampling loops would hide the scenario timeline behind vertices.
function [azimuth_deg, elevation_deg] = trackWallBoundary()
regions = { ...
    rectangleVertices([-4 4], [-4 4]), ...
    rectangleVertices([-10 10], [8 10]), ...
    rectangleVertices([-10 10], [-10 -8]), ...
    rectangleVertices([-10 -8], [-8 8]), ...
    rectangleVertices([8 10], [2.05 8]), ...
    rectangleVertices([8 10], [-8 -2.05])};
azimuth_deg = zeros(0, 1);
elevation_deg = zeros(0, 1);
for regionIndex = 1:numel(regions)
    if regionIndex > 1
        azimuth_deg(end + 1, 1) = NaN; %#ok<AGROW>
        elevation_deg(end + 1, 1) = NaN; %#ok<AGROW>
    end
    azimuth_deg = [ ...
        azimuth_deg; regions{regionIndex}(:, 1)]; %#ok<AGROW>
    elevation_deg = [ ...
        elevation_deg; regions{regionIndex}(:, 2)]; %#ok<AGROW>
end
end

function vertices_deg = rectangleVertices(azimuthLimits_deg, ...
        elevationLimits_deg)
vertices_deg = [ ...
    azimuthLimits_deg(1), elevationLimits_deg(1); ...
    azimuthLimits_deg(2), elevationLimits_deg(1); ...
    azimuthLimits_deg(2), elevationLimits_deg(2); ...
    azimuthLimits_deg(1), elevationLimits_deg(2); ...
    azimuthLimits_deg(1), elevationLimits_deg(1)];
end

function [center_deg, tangent] = squareTrackState( ...
        trackDistance_deg, trackHalfWidth_deg)
trackPerimeter_deg = 8 * trackHalfWidth_deg;
wrappedTrackDistance_deg = mod(trackDistance_deg, trackPerimeter_deg);
if wrappedTrackDistance_deg < trackHalfWidth_deg
    center_deg = [-trackHalfWidth_deg, wrappedTrackDistance_deg];
    tangent = [0 1];
elseif wrappedTrackDistance_deg < 3 * trackHalfWidth_deg
    center_deg = [ ...
        -trackHalfWidth_deg + ...
        (wrappedTrackDistance_deg - trackHalfWidth_deg), ...
        trackHalfWidth_deg];
    tangent = [1 0];
elseif wrappedTrackDistance_deg < 5 * trackHalfWidth_deg
    center_deg = [ ...
        trackHalfWidth_deg, ...
        trackHalfWidth_deg - ...
        (wrappedTrackDistance_deg - 3 * trackHalfWidth_deg)];
    tangent = [0 -1];
elseif wrappedTrackDistance_deg < 7 * trackHalfWidth_deg
    center_deg = [ ...
        trackHalfWidth_deg - ...
        (wrappedTrackDistance_deg - 5 * trackHalfWidth_deg), ...
        -trackHalfWidth_deg];
    tangent = [-1 0];
else
    center_deg = [ ...
        -trackHalfWidth_deg, ...
        -trackHalfWidth_deg + ...
        (wrappedTrackDistance_deg - 7 * trackHalfWidth_deg)];
    tangent = [0 1];
end
end

function [azimuth_deg, elevation_deg] = orientedRectangle( ...
        center_deg, tangent, alongHalfWidth_deg, crossHalfWidth_deg)
normal = [-tangent(2), tangent(1)];
vertices_deg = [ ...
    center_deg - alongHalfWidth_deg * tangent - ...
        crossHalfWidth_deg * normal; ...
    center_deg + alongHalfWidth_deg * tangent - ...
        crossHalfWidth_deg * normal; ...
    center_deg + alongHalfWidth_deg * tangent + ...
        crossHalfWidth_deg * normal; ...
    center_deg - alongHalfWidth_deg * tangent + ...
        crossHalfWidth_deg * normal; ...
    center_deg - alongHalfWidth_deg * tangent - ...
        crossHalfWidth_deg * normal];
azimuth_deg = vertices_deg(:, 1);
elevation_deg = vertices_deg(:, 2);
end

function [azimuth_deg, elevation_deg] = axisAlignedRectangle( ...
        center_deg, azimuthHalfWidth_deg, elevationHalfWidth_deg)
vertices_deg = rectangleVertices( ...
    center_deg(1) + [-azimuthHalfWidth_deg azimuthHalfWidth_deg], ...
    center_deg(2) + [-elevationHalfWidth_deg elevationHalfWidth_deg]);
azimuth_deg = vertices_deg(:, 1);
elevation_deg = vertices_deg(:, 2);
end
