function problem = makeAlternatingSlalomGauntlet()
%MAKEALTERNATINGSLALOMGAUNTLET Four static barriers with alternating gaps.
%
% Scenario data for example08AlternatingSlalom and the planner comparison
% benchmark. Consecutive barriers leave openings on opposite sides.

time_s = (0:0.5:60).';
centers = [-9, -3, 3, 9];
passAbove = [true, false, true, false];
obstacles = cell(numel(centers), 1);
for obstacleIndex = 1:numel(centers)
    [azimuth, elevation] = slalomBarrier( ...
        centers(obstacleIndex), passAbove(obstacleIndex));
    obstacles{obstacleIndex} = makeAzElObstacleData( ...
        "Slalom " + obstacleIndex, time_s, azimuth, elevation);
end
problem = struct( ...
    "azElData", {combineAzElObstacles(obstacles)}, ...
    "startState", boundaryState(0, [-15, 0]), ...
    "stopState", boundaryState(60, [15, 0]), ...
    "limits", struct( ...
        "azimuth_deg", [-17, 17], ...
        "elevation_deg", [-7, 7], ...
        "maxVelocity_deg_s", [3, 3], ...
        "maxAcceleration_deg_s2", [3, 3]), ...
    "options", struct( ...
        "SampleTime_s", 0.5, ...
        "GridStep_deg", 0.25, ...
        "SafetyMargin_deg", 0.25, ...
        "AllowAzimuthWrap", false, ...
        "Objective", "minimumAngularDistance", ...
        "MaxSearchTime_s", 75, ...
        "MaxExpansions", 1000000), ...
    "geometry", struct( ...
        "barrierCenters_deg", centers, ...
        "passAbove", passAbove));
end

function [azimuth, elevation] = slalomBarrier(center, passAbove)
azimuth = center + 1.25 * [-1; 1; 1; -1; -1];
if passAbove
    elevation = [-7; -7; 1; 1; -7];
else
    elevation = [-1; -1; 7; 7; -1];
end
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
