function problem = makeCrossyRoadRendezvousGauntlet()
%MAKECROSSYROADRENDEZVOUSGAUNTLET Crossy Road traffic plus a moving target.
%
% Scenario data for example14MovingRendezvousAndTrail and the planner
% comparison benchmark. Forty-eight vehicles occupy twelve dense horizontal
% traffic rows between two corridor walls. Rows 1-8 keep a narrow vertical
% slot aligned; rows 9-12 sweep it laterally as timed gates. The moving
% target curves upward through all twelve rows and must be caught with
% matched velocity and acceleration, then chased.

time_s = (0:0.5:76).';
targetPhaseAz = 0.12 * time_s;
targetPhaseEl = 0.11 * time_s - 0.40;
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [ ...
        -3.20 + 0.055 * time_s + 0.75 * sin(targetPhaseAz), ...
        -6 + 0.16 * time_s + 1.40 * sin(targetPhaseEl)], ...
    "velocity_deg_s", [ ...
        0.055 + 0.090 * cos(targetPhaseAz), ...
        0.16 + 0.154 * cos(targetPhaseEl)], ...
    "acceleration_deg_s2", [ ...
        -0.01080 * sin(targetPhaseAz), ...
        -0.01694 * sin(targetPhaseEl)]);

[vehicleData, trafficDiagnostics] = makeCrossyRoadTraffic(time_s);
corridorData = makeCentralCorridorWalls(time_s);
problem = struct( ...
    "azElData", {combineAzElObstacles([vehicleData; corridorData])}, ...
    "startState", struct( ...
        "time_s", 0, ...
        "position_deg", [0 -8], ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]), ...
    "target", target, ...
    "limits", struct( ...
        "azimuth_deg", [-9 9], ...
        "elevation_deg", [-9 9], ...
        "maxVelocity_deg_s", [2.2 2.2], ...
        "maxAcceleration_deg_s2", [1.2 1.2]), ...
    "options", struct( ...
        "EarliestInterceptTime_s", 48, ...
        "LatestInterceptTime_s", 56, ...
        "InterceptTimeStep_s", 4, ...
        "MaximumInterceptAttempts", 3, ...
        "PerAttemptMaxSearchTime_s", 120, ...
        "CatchTolerance_deg", 0.06, ...
        "CatchVelocityTolerance_deg_s", 0.015, ...
        "CatchAccelerationTolerance_deg_s2", 0.015, ...
        "MatchTargetVelocity", true, ...
        "MatchTargetAcceleration", true, ...
        "ContinueTrackingAfterIntercept", true, ...
        "TrackingEndTime_s", 74, ...
        "TrackingSampleTime_s", 0.2, ...
        "GridStep_deg", 2, ...
        "GridStepSchedule_deg", 2, ...
        "PrimitiveRadiusMultipliers", [1 2], ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.05, ...
        "CollisionCheckStep_s", 0.08, ...
        "SafetyMargin_deg", 0.12, ...
        "MaximumSafeIntervalSamples", 40, ...
        "MaxSearchTime_s", 120), ...
    "trafficDiagnostics", trafficDiagnostics);
end

function [vehicles, diagnostics] = makeCrossyRoadTraffic(time_s)
rowElevation_deg = linspace(-5.6, 5.4, 12);
halfWidth_deg = 0.75;
halfHeight_deg = 0.36;
centerSlotWidth_deg = 0.90;
innerCenter_deg = halfWidth_deg + centerSlotWidth_deg / 2;
outerCenter_deg = 5.50;
vehicleOffset_deg = [-outerCenter_deg -innerCenter_deg ...
    innerCenter_deg outerCenter_deg];
sameRowEdgeGaps_deg = diff(vehicleOffset_deg) - 2 * halfWidth_deg;
corridorHalfWidth_deg = 8;
rowCount = numel(rowElevation_deg);
vehiclesPerRow = numel(vehicleOffset_deg);
vehicleCount = rowCount * vehiclesPerRow;
vehicles = cell(vehicleCount, 1);
velocityParts = cell(vehicleCount, 1);
centerAzimuth_deg = zeros(numel(time_s), vehicleCount);
centerElevation_deg = zeros(numel(time_s), vehicleCount);
rowCenterAzimuth_deg = zeros(numel(time_s), rowCount);
rowCenterVelocity_deg_s = zeros(numel(time_s), rowCount);
rowPhase_rad = zeros(1, rowCount);
rowOmega_rad_s = zeros(1, rowCount);

% Rows 1-8 hold a narrow vertical slot at azimuth zero. Rows 9-12 move that
% slot laterally, creating timed gates without giving the planner a route
% hint. All four vehicles in a row move together and retain fixed spacing.
endPacingRows = 9:12;
rowOmega_rad_s(endPacingRows) = [0.17 0.18 0.19 0.20];
gateCrossingTimes_s = [55 60 63 66];
gateCenterAtCrossing_deg = [0 0.65 0.95 0];
for k = 1:numel(endPacingRows)
    row = endPacingRows(k);
    rowPhase_rad(row) = asin(gateCenterAtCrossing_deg(k) / 1.20) - ...
        rowOmega_rad_s(row) * gateCrossingTimes_s(k);
end

cursor = 0;
for row = 1:numel(rowElevation_deg)
    omega = rowOmega_rad_s(row);
    phase = rowPhase_rad(row);
    if ismember(row, endPacingRows)
        rowCenterAzimuth_deg(:, row) = ...
            1.20 * sin(omega * time_s + phase);
        rowCenterVelocity_deg_s(:, row) = ...
            1.20 * omega * cos(omega * time_s + phase);
    end
    for laneVehicle = 1:vehiclesPerRow
        cursor = cursor + 1;
        centerAzimuth = rowCenterAzimuth_deg(:, row) + ...
            vehicleOffset_deg(laneVehicle);
        centerElevation = rowElevation_deg(row) + ...
            zeros(size(time_s));
        centerAzimuth_deg(:, cursor) = centerAzimuth;
        centerElevation_deg(:, cursor) = centerElevation;
        vehicles{cursor} = movingRectangle( ...
            sprintf('Row %02d vehicle %d', row, laneVehicle), ...
            time_s, centerAzimuth, centerElevation, ...
            halfWidth_deg, halfHeight_deg);
        velocityParts{cursor} = rowCenterVelocity_deg_s(:, row);
    end
end

reversals = cellfun(@countDirectionReversals, velocityParts);
[overlapSampleCount, minimumClearance_deg] = vehicleOverlapDiagnostics( ...
    centerAzimuth_deg, centerElevation_deg, ...
    halfWidth_deg, halfHeight_deg);
maximumRowExcursion_deg = max(abs(rowCenterAzimuth_deg), [], "all");
minimumWallClearance_deg = corridorHalfWidth_deg - ...
    (outerCenter_deg + halfWidth_deg + maximumRowExcursion_deg);
diagnostics = struct( ...
    "vehicleCount", numel(vehicles), ...
    "rowCount", numel(rowElevation_deg), ...
    "vehiclesPerRow", vehiclesPerRow, ...
    "rowElevation_deg", rowElevation_deg, ...
    "directionReversalsByVehicle", reversals, ...
    "totalDirectionReversals", sum(reversals), ...
    "endPacingRowIndices", endPacingRows, ...
    "endPacingVehicleIndices", ...
        (endPacingRows(1) - 1) * vehiclesPerRow + 1:vehicleCount, ...
    "movingRowCount", numel(endPacingRows), ...
    "vehicleHalfSize_deg", [halfWidth_deg halfHeight_deg], ...
    "centerCorridorWidth_deg", centerSlotWidth_deg, ...
    "wallCorridorWidth_deg", 2 * corridorHalfWidth_deg, ...
    "sameRowEdgeGaps_deg", sameRowEdgeGaps_deg, ...
    "minimumSameRowEdgeGap_deg", min(sameRowEdgeGaps_deg), ...
    "maximumSameRowEdgeGap_deg", max(sameRowEdgeGaps_deg), ...
    "overlapSampleCount", overlapSampleCount, ...
    "minimumVehicleClearance_deg", minimumClearance_deg, ...
    "minimumWallClearance_deg", minimumWallClearance_deg);
end

function walls = makeCentralCorridorWalls(time_s)
corridorHalfWidth_deg = 8;
domainHalfWidth_deg = 9;
wallHalfWidth_deg = ...
    (domainHalfWidth_deg - corridorHalfWidth_deg) / 2;
wallCenter_deg = corridorHalfWidth_deg + wallHalfWidth_deg;
centerElevation = zeros(size(time_s));
walls = {
    movingRectangle("Left corridor wall", time_s, ...
        -wallCenter_deg + zeros(size(time_s)), centerElevation, ...
        wallHalfWidth_deg, 9)
    movingRectangle("Right corridor wall", time_s, ...
        wallCenter_deg + zeros(size(time_s)), centerElevation, ...
        wallHalfWidth_deg, 9)
    };
end

function data = movingRectangle( ...
        name, time_s, centerAzimuth, centerElevation, ...
        halfWidth, halfHeight)
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    azimuth{k} = centerAzimuth(k) + ...
        halfWidth * [-1; 1; 1; -1; -1];
    elevation{k} = centerElevation(k) + ...
        halfHeight * [-1; -1; 1; 1; -1];
end
data = makeAzElObstacleData(name, time_s, azimuth, elevation);
end

function count = countDirectionReversals(velocity)
signValue = sign(velocity(:));
signValue(signValue == 0) = 1;
count = nnz(diff(signValue) ~= 0);
end

function [overlapCount, minimumClearance] = vehicleOverlapDiagnostics( ...
        centerAzimuth, centerElevation, halfWidth, halfHeight)
vehicleCount = size(centerAzimuth, 2);
overlapCount = 0;
minimumClearance = Inf;
for first = 1:vehicleCount - 1
    for second = first + 1:vehicleCount
        azimuthGap = abs(centerAzimuth(:, first) - ...
            centerAzimuth(:, second)) - 2 * halfWidth;
        elevationGap = abs(centerElevation(:, first) - ...
            centerElevation(:, second)) - 2 * halfHeight;
        overlapCount = overlapCount + ...
            nnz(azimuthGap < 0 & elevationGap < 0);
        minimumClearance = min( ...
            minimumClearance, min(max(azimuthGap, elevationGap)));
    end
end
end
