function problem = makeUTrapEscapeGauntlet()
%MAKEUTRAPESCAPEGAUNTLET Static U-trap that requires backtracking.
%
% Scenario data for example09UTrapEscape and the planner comparison
% benchmark. The start sits inside a U whose opening faces away from the
% goal, so any route must first move away from the goal.

time_s = (0:0.5:60).';
regions = { ...
    [3, -6; 6, -6; 6, 6; 3, 6; 3, -6], ...
    [-6, 5; 6, 5; 6, 6; -6, 6; -6, 5], ...
    [-6, -6; 6, -6; 6, -5; -6, -5; -6, -6]};
[azimuth, elevation] = joinRegions(regions);
problem = struct( ...
    "azElData", makeAzElObstacleData( ...
        "U-shaped trap", time_s, azimuth, elevation), ...
    "startState", boundaryState(0, [0, 0]), ...
    "stopState", boundaryState(60, [15, 0]), ...
    "limits", struct( ...
        "azimuth_deg", [-10, 18], ...
        "elevation_deg", [-10, 10], ...
        "maxVelocity_deg_s", [3, 3], ...
        "maxAcceleration_deg_s2", [3, 3]), ...
    "options", struct( ...
        "SampleTime_s", 0.5, ...
        "GridStep_deg", 0.125, ...
        "GridStepSchedule_deg", [1, 0.5, 0.25, 0.125], ...
        "SafetyMargin_deg", 0.25, ...
        "AllowAzimuthWrap", false, ...
        "Objective", "minimumAngularDistance", ...
        "MaxSearchTime_s", 60, ...
        "MaxExpansions", 1000000), ...
    "geometry", struct("trapOpeningAzimuth_deg", -6));
end

function [azimuth, elevation] = joinRegions(regions)
rowCount = sum(cellfun(@(region) size(region, 1), regions)) + ...
    numel(regions) - 1;
combined = nan(rowCount, 2);
cursor = 1;
for regionIndex = 1:numel(regions)
    region = regions{regionIndex};
    output = cursor:cursor + size(region, 1) - 1;
    combined(output, :) = region;
    cursor = output(end) + 2;
end
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
