function result = optimizeCircularBoundedJerkTrajectory( ...
        initialState, goalState, limits, circle, seedPlan, options)
%% Section 0: Header & Readme
% SYNTAX
%   options = optimizeCircularBoundedJerkTrajectory()
%   result = optimizeCircularBoundedJerkTrajectory( ...
%       initialState, goalState, limits, circle, seedPlan)
%   result = optimizeCircularBoundedJerkTrajectory( ...
%       initialState, goalState, limits, circle, seedPlan, options)
%**************************************************************************
% PURPOSE
%   - Refine a safe azimuth/elevation seed into a continuous, bounded-jerk
%     trajectory around one static circular keep-out region.
%   - Optimize elapsed time and traveled angular distance in the same
%     physical problem instead of comparing with unrelated lower bounds.
%   - Return dense state samples and an optimization receipt that can be
%     checked without trusting the optimizer's success flag.
%**************************************************************************
% INPUTS
%   - initialState (scalar struct)
%       Initial time, position, velocity, and acceleration.
%   - goalState (scalar struct)
%       Goal position, velocity, acceleration, and latest allowed time.
%   - limits (scalar struct)
%       Axis bounds plus maximum velocity and acceleration.
%   - circle (scalar struct)
%       Center_deg and ProtectedRadius_deg of the keep-out region.
%   - seedPlan (scalar struct)
%       Successful joint bounded-jerk plan or a previously verified result
%       from this function. The latter supports warm-started Pareto studies.
%   - options (scalar struct, optional)
%       Partial optimization settings. Omitted fields receive defaults.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Continuous trajectory, physical checks, objective values, and the
%       raw fmincon completion receipt. With no inputs, returns defaults.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Apply Defaults & Validate The Physical Request
defaultOptions = circularRefinementDefaults();
if nargin == 0
    result = defaultOptions;
    return
end
if nargin < 6 || isempty(options)
    options = struct();
end
options = mergeCircularRefinementOptions(options, defaultOptions);

requiredStateFields = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
for stateField = requiredStateFields
    if ~isfield(initialState, stateField) || ...
            ~isfield(goalState, stateField)
        error("optimizeCircularBoundedJerkTrajectory:MissingStateField", ...
            "Both endpoint states require the %s field.", stateField);
    end
end
requiredLimitFields = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
for limitField = requiredLimitFields
    if ~isfield(limits, limitField)
        error("optimizeCircularBoundedJerkTrajectory:MissingLimitField", ...
            "The limits structure requires the %s field.", limitField);
    end
end
if ~isfield(circle, "Center_deg") || ...
        ~isfield(circle, "ProtectedRadius_deg")
    error("optimizeCircularBoundedJerkTrajectory:MissingCircleField", ...
        "Circle data require Center_deg and ProtectedRadius_deg.");
end
seedIsJointPlan = isfield(seedPlan, "success") && seedPlan.success && ...
    isfield(seedPlan, "retiming") && ...
    isfield(seedPlan.retiming, "StateSpaceSearch");
seedIsContinuousResult = isfield(seedPlan, "duration_s") && ...
    isfield(seedPlan, "jerkByInterval_deg_s3") && ...
    isfield(seedPlan, "maximumInequalityViolation") && ...
    isfield(seedPlan, "maximumEqualityViolation");
if ~seedIsJointPlan && ~seedIsContinuousResult
    error("optimizeCircularBoundedJerkTrajectory:InvalidSeed", ...
        ["The seed must be a successful joint state-space plan or a " ...
        "verified continuous refinement result."]);
end
if options.Optimize && exist("fmincon", "file") ~= 2
    error("optimizeCircularBoundedJerkTrajectory:MissingOptimizer", ...
        "This optional study refinement requires Optimization Toolbox.");
end

validateattributes(options.IntervalCount, {'numeric'}, ...
    {'scalar', 'integer', '>=', 4});
validateattributes(options.SamplesPerInterval, {'numeric'}, ...
    {'scalar', 'integer', '>=', 2});
validateattributes(options.MaximumJerk_deg_s3, {'numeric'}, ...
    {'row', 'numel', 2, 'positive', 'finite'});
validateattributes(circle.Center_deg, {'numeric'}, ...
    {'row', 'numel', 2, 'finite'});
validateattributes(circle.ProtectedRadius_deg, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});

%% Section 2: Turn The Lattice Receipt Into A Feasible Initial Guess
% The state search already supplies constant-jerk actions whose exact
% integration reaches the requested terminal state. Repeating those actions
% on a finer time partition preserves the same motion exactly when the
% partitions align. This gives the nonlinear optimizer a safe starting
% point, which matters because the circular avoidance constraint has two
% disconnected choices: go above or go below.
intervalCount = options.IntervalCount;
if seedIsJointPlan
    stateSearch = seedPlan.retiming.StateSpaceSearch;
    seedJerk_deg_s3 = stateSearch.JerkCommand_deg_s3;
    seedActionCount = size(seedJerk_deg_s3, 1);
    seedDuration_s = stateSearch.TimeStep_s * seedActionCount;
    seedMidpointTime_s = ((1:intervalCount).' - 0.5) * ...
        seedDuration_s / intervalCount;
    seedActionIndex = floor(seedMidpointTime_s / ...
        stateSearch.TimeStep_s) + 1;
    seedActionIndex = min(seedActionIndex, seedActionCount);
    initialJerk_deg_s3 = seedJerk_deg_s3(seedActionIndex, :);
else
    seedDuration_s = seedPlan.duration_s;
    seedJerk_deg_s3 = seedPlan.jerkByInterval_deg_s3;
    seedIntervalCount = size(seedJerk_deg_s3, 1);
    seedTimeStep_s = seedDuration_s / seedIntervalCount;
    seedMidpointTime_s = ((1:intervalCount).' - 0.5) * ...
        seedDuration_s / intervalCount;
    seedIntervalIndex = floor(seedMidpointTime_s / seedTimeStep_s) + 1;
    seedIntervalIndex = min(seedIntervalIndex, seedIntervalCount);
    initialJerk_deg_s3 = seedJerk_deg_s3(seedIntervalIndex, :);
end

maximumDuration_s = min(options.MaximumDuration_s, ...
    goalState.time_s - initialState.time_s);
if seedDuration_s > maximumDuration_s + options.ConstraintTolerance
    error("optimizeCircularBoundedJerkTrajectory:SeedTooLong", ...
        "The %.3f-second seed exceeds the %.3f-second duration limit.", ...
        seedDuration_s, maximumDuration_s);
end

initialDecision = [seedDuration_s; initialJerk_deg_s3(:)];
minimumJerkByInterval_deg_s3 = repmat( ...
    -options.MaximumJerk_deg_s3, intervalCount, 1);
maximumJerkByInterval_deg_s3 = repmat( ...
    options.MaximumJerk_deg_s3, intervalCount, 1);
lowerBound = [options.MinimumDuration_s; ...
    minimumJerkByInterval_deg_s3(:)];
upperBound = [maximumDuration_s; ...
    maximumJerkByInterval_deg_s3(:)];

%% Section 3: Optimize Time & Distance On The Continuous State Equations
% Only duration and jerk are decision variables. Position, velocity, and
% acceleration are always produced by exact constant-jerk integration. That
% removes hundreds of redundant state variables and prevents an optimizer
% from reporting a visually plausible path whose state columns disagree.
objectiveFunction = @(decision) circularTrajectoryObjective( ...
    decision, initialState, intervalCount, options);
constraintFunction = @(decision) circularTrajectoryConstraints( ...
    decision, initialState, goalState, limits, circle, ...
    intervalCount, options);
if options.Optimize
    optimizerOptions = optimoptions("fmincon", ...
        "Algorithm", options.Algorithm, ...
        "Display", options.Display, ...
        "MaxIterations", options.MaximumIterations, ...
        "MaxFunctionEvaluations", options.MaximumFunctionEvaluations, ...
        "ConstraintTolerance", options.ConstraintTolerance, ...
        "OptimalityTolerance", options.OptimalityTolerance, ...
        "StepTolerance", options.StepTolerance, ...
        "FiniteDifferenceType", options.FiniteDifferenceType);
    [winningDecision, objectiveValue, exitFlag, optimizerOutput] = fmincon( ...
        objectiveFunction, initialDecision, [], [], [], [], ...
        lowerBound, upperBound, constraintFunction, optimizerOptions);
else
    % Evaluation-only mode makes a stored optimum independently auditable
    % on machines without Optimization Toolbox. It still uses the exact
    % state equations and all dense physical checks below.
    winningDecision = initialDecision;
    objectiveValue = objectiveFunction(winningDecision);
    exitFlag = NaN;
    optimizerOutput = struct( ...
        "algorithm", "stored-reference replay", ...
        "iterations", 0, ...
        "funcCount", 1, ...
        "message", "Optimization was disabled; the seed was rechecked.");
end

%% Section 4: Densely Recheck & Report The Winning Trajectory
duration_s = winningDecision(1);
jerkByInterval_deg_s3 = reshape( ...
    winningDecision(2:end), intervalCount, 2);
sample = sampleCircularTrajectory(initialState, duration_s, ...
    jerkByInterval_deg_s3, options.SampleTime_s);
pathStep_deg = diff(sample.Position_deg, 1, 1);
angularPathLength_deg = sum(hypot( ...
    pathStep_deg(:, 1), pathStep_deg(:, 2)));
circleOffset_deg = sample.Position_deg - circle.Center_deg;
circleDistance_deg = hypot(circleOffset_deg(:, 1), ...
    circleOffset_deg(:, 2));
minimumCircleClearance_deg = min(circleDistance_deg) - ...
    circle.ProtectedRadius_deg;
maximumDenseLimitViolation = maximumCircularLimitViolation( ...
    sample, limits, circle, options.MaximumJerk_deg_s3);

[inequalityResidual, equalityResidual] = constraintFunction( ...
    winningDecision);
maximumInequalityViolation = max([0; inequalityResidual]);
maximumEqualityViolation = max(abs(equalityResidual));
isPhysicallyVerified = maximumInequalityViolation <= ...
    10 * options.ConstraintTolerance && ...
    maximumEqualityViolation <= 10 * options.ConstraintTolerance && ...
    maximumDenseLimitViolation <= 10 * options.ConstraintTolerance;
success = (exitFlag > 0 || ~options.Optimize) && isPhysicallyVerified;
if success
    if options.Optimize
        message = "Continuous bounded-jerk refinement converged and passed.";
    else
        message = "Stored bounded-jerk reference passed an independent replay.";
    end
elseif isPhysicallyVerified
    % A limit exit can still be a useful feasible incumbent. It is returned
    % honestly as incomplete so a stored benchmark never treats it as a
    % proved optimizer convergence.
    message = "A feasible trajectory was found, but optimization stopped early.";
else
    message = "Continuous refinement did not return a verified trajectory.";
end

result = struct( ...
    "success", success, ...
    "message", message, ...
    "exitFlag", exitFlag, ...
    "optimizerOutput", optimizerOutput, ...
    "objectiveValue", objectiveValue, ...
    "time_s", initialState.time_s + sample.TimeFromStart_s, ...
    "position_deg", sample.Position_deg, ...
    "positionUnwrapped_deg", sample.Position_deg, ...
    "velocity_deg_s", sample.Velocity_deg_s, ...
    "acceleration_deg_s2", sample.Acceleration_deg_s2, ...
    "jerk_deg_s3", sample.Jerk_deg_s3, ...
    "duration_s", duration_s, ...
    "angularPathLength_deg", angularPathLength_deg, ...
    "minimumCircleClearance_deg", minimumCircleClearance_deg, ...
    "maximumDenseLimitViolation", maximumDenseLimitViolation, ...
    "maximumInequalityViolation", maximumInequalityViolation, ...
    "maximumEqualityViolation", maximumEqualityViolation, ...
    "decision", winningDecision, ...
    "jerkByInterval_deg_s3", jerkByInterval_deg_s3, ...
    "options", options);
end

function defaults = circularRefinementDefaults()
defaults = struct( ...
    "Optimize", true, ...
    "Objective", "balanced", ...
    "IntervalCount", 40, ...
    "SamplesPerInterval", 6, ...
    "SampleTime_s", 0.02, ...
    "MinimumDuration_s", 1, ...
    "MaximumDuration_s", inf, ...
    "MaximumJerk_deg_s3", [8 8], ...
    "TimeScale_s", 7, ...
    "DistanceScale_deg", 21, ...
    "TimeWeight", 0.5, ...
    "DistanceWeight", 0.5, ...
    "MaximumIterations", 500, ...
    "MaximumFunctionEvaluations", 150000, ...
    "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "Algorithm", "sqp", ...
    "FiniteDifferenceType", "forward", ...
    "Display", "off");
end

function maximumViolation = maximumCircularLimitViolation( ...
        sample, limits, circle, maximumJerk_deg_s3)
position_deg = sample.Position_deg;
velocity_deg_s = sample.Velocity_deg_s;
acceleration_deg_s2 = sample.Acceleration_deg_s2;
jerk_deg_s3 = sample.Jerk_deg_s3;
circleOffset_deg = position_deg - circle.Center_deg;
circleClearance_deg = hypot(circleOffset_deg(:, 1), ...
    circleOffset_deg(:, 2)) - circle.ProtectedRadius_deg;

violations = [ ...
    limits.azimuth_deg(1) - position_deg(:, 1); ...
    position_deg(:, 1) - limits.azimuth_deg(2); ...
    limits.elevation_deg(1) - position_deg(:, 2); ...
    position_deg(:, 2) - limits.elevation_deg(2); ...
    abs(velocity_deg_s(:, 1)) - limits.maxVelocity_deg_s(1); ...
    abs(velocity_deg_s(:, 2)) - limits.maxVelocity_deg_s(2); ...
    abs(acceleration_deg_s2(:, 1)) - ...
        limits.maxAcceleration_deg_s2(1); ...
    abs(acceleration_deg_s2(:, 2)) - ...
        limits.maxAcceleration_deg_s2(2); ...
    abs(jerk_deg_s3(:, 1)) - maximumJerk_deg_s3(1); ...
    abs(jerk_deg_s3(:, 2)) - maximumJerk_deg_s3(2); ...
    -circleClearance_deg];
maximumViolation = max([0; violations]);
end

function options = mergeCircularRefinementOptions(options, defaults)
optionNames = fieldnames(defaults);
for optionIndex = 1:numel(optionNames)
    optionName = optionNames{optionIndex};
    if ~isfield(options, optionName) || isempty(options.(optionName))
        options.(optionName) = defaults.(optionName);
    end
end
unknownOptionNames = setdiff(fieldnames(options), optionNames);
if ~isempty(unknownOptionNames)
    warning("optimizeCircularBoundedJerkTrajectory:UnknownOptions", ...
        "Ignored unknown options: %s.", ...
        strjoin(string(unknownOptionNames), ", "));
    options = rmfield(options, unknownOptionNames);
end
end

function objective = circularTrajectoryObjective( ...
        decision, initialState, intervalCount, options)
duration_s = decision(1);
jerkByInterval_deg_s3 = reshape( ...
    decision(2:end), intervalCount, 2);
sample = sampleCircularTrajectoryAtFractions(initialState, duration_s, ...
    jerkByInterval_deg_s3, options.SamplesPerInterval);
pathStep_deg = diff(sample.Position_deg, 1, 1);
pathLength_deg = sum(sqrt(sum(pathStep_deg.^2, 2) + 1e-12));

switch string(options.Objective)
    case "minimumTime"
        objective = duration_s / options.TimeScale_s + ...
            1e-5 * pathLength_deg / options.DistanceScale_deg;
    case "minimumDistance"
        objective = pathLength_deg / options.DistanceScale_deg + ...
            1e-5 * duration_s / options.TimeScale_s;
    case "balanced"
        objective = options.TimeWeight * duration_s / ...
            options.TimeScale_s + options.DistanceWeight * ...
            pathLength_deg / options.DistanceScale_deg;
    otherwise
        error("optimizeCircularBoundedJerkTrajectory:UnknownObjective", ...
            "Objective must be minimumTime, minimumDistance, or balanced.");
end
end

function [inequality, equality] = circularTrajectoryConstraints( ...
        decision, initialState, goalState, limits, circle, ...
        intervalCount, options)
duration_s = decision(1);
jerkByInterval_deg_s3 = reshape( ...
    decision(2:end), intervalCount, 2);
sample = sampleCircularTrajectoryAtFractions(initialState, duration_s, ...
    jerkByInterval_deg_s3, options.SamplesPerInterval);

position_deg = sample.Position_deg;
velocity_deg_s = sample.Velocity_deg_s;
acceleration_deg_s2 = sample.Acceleration_deg_s2;
circleOffset_deg = position_deg - circle.Center_deg;
insideCircleResidual_deg2 = circle.ProtectedRadius_deg^2 - ...
    sum(circleOffset_deg.^2, 2);

inequality = [ ...
    limits.azimuth_deg(1) - position_deg(:, 1); ...
    position_deg(:, 1) - limits.azimuth_deg(2); ...
    limits.elevation_deg(1) - position_deg(:, 2); ...
    position_deg(:, 2) - limits.elevation_deg(2); ...
    -limits.maxVelocity_deg_s(1) - velocity_deg_s(:, 1); ...
    velocity_deg_s(:, 1) - limits.maxVelocity_deg_s(1); ...
    -limits.maxVelocity_deg_s(2) - velocity_deg_s(:, 2); ...
    velocity_deg_s(:, 2) - limits.maxVelocity_deg_s(2); ...
    -limits.maxAcceleration_deg_s2(1) - acceleration_deg_s2(:, 1); ...
    acceleration_deg_s2(:, 1) - limits.maxAcceleration_deg_s2(1); ...
    -limits.maxAcceleration_deg_s2(2) - acceleration_deg_s2(:, 2); ...
    acceleration_deg_s2(:, 2) - limits.maxAcceleration_deg_s2(2); ...
    insideCircleResidual_deg2];

terminalPosition_deg = position_deg(end, :);
terminalVelocity_deg_s = velocity_deg_s(end, :);
terminalAcceleration_deg_s2 = acceleration_deg_s2(end, :);
equality = [ ...
    terminalPosition_deg - goalState.position_deg, ...
    terminalVelocity_deg_s - goalState.velocity_deg_s, ...
    terminalAcceleration_deg_s2 - goalState.acceleration_deg_s2].';
end

function sample = sampleCircularTrajectoryAtFractions( ...
        initialState, duration_s, jerkByInterval_deg_s3, ...
        samplesPerInterval)
intervalCount = size(jerkByInterval_deg_s3, 1);
timeStep_s = duration_s / intervalCount;
sampleCount = intervalCount * samplesPerInterval + 1;
position_deg = zeros(sampleCount, 2);
velocity_deg_s = zeros(sampleCount, 2);
acceleration_deg_s2 = zeros(sampleCount, 2);
jerk_deg_s3 = zeros(sampleCount, 2);
position_deg(1, :) = initialState.position_deg;
velocity_deg_s(1, :) = initialState.velocity_deg_s;
acceleration_deg_s2(1, :) = initialState.acceleration_deg_s2;

writeIndex = 1;
for intervalIndex = 1:intervalCount
    intervalJerk_deg_s3 = jerkByInterval_deg_s3(intervalIndex, :);
    intervalPosition_deg = position_deg(writeIndex, :);
    intervalVelocity_deg_s = velocity_deg_s(writeIndex, :);
    intervalAcceleration_deg_s2 = acceleration_deg_s2(writeIndex, :);
    for fractionIndex = 1:samplesPerInterval
        localTime_s = timeStep_s * fractionIndex / samplesPerInterval;
        sampleIndex = writeIndex + fractionIndex;
        position_deg(sampleIndex, :) = intervalPosition_deg + ...
            intervalVelocity_deg_s * localTime_s + 0.5 * ...
            intervalAcceleration_deg_s2 * localTime_s^2 + ...
            (1 / 6) * intervalJerk_deg_s3 * localTime_s^3;
        velocity_deg_s(sampleIndex, :) = intervalVelocity_deg_s + ...
            intervalAcceleration_deg_s2 * localTime_s + 0.5 * ...
            intervalJerk_deg_s3 * localTime_s^2;
        acceleration_deg_s2(sampleIndex, :) = ...
            intervalAcceleration_deg_s2 + ...
            intervalJerk_deg_s3 * localTime_s;
        jerk_deg_s3(sampleIndex, :) = intervalJerk_deg_s3;
    end
    writeIndex = writeIndex + samplesPerInterval;
end

sample = struct( ...
    "Position_deg", position_deg, ...
    "Velocity_deg_s", velocity_deg_s, ...
    "Acceleration_deg_s2", acceleration_deg_s2, ...
    "Jerk_deg_s3", jerk_deg_s3);
end

function sample = sampleCircularTrajectory( ...
        initialState, duration_s, jerkByInterval_deg_s3, sampleTime_s)
intervalCount = size(jerkByInterval_deg_s3, 1);
timeStep_s = duration_s / intervalCount;
timeFromStart_s = (0:sampleTime_s:duration_s).';
if timeFromStart_s(end) < duration_s
    timeFromStart_s(end + 1, 1) = duration_s;
end
sampleCount = numel(timeFromStart_s);
position_deg = zeros(sampleCount, 2);
velocity_deg_s = zeros(sampleCount, 2);
acceleration_deg_s2 = zeros(sampleCount, 2);
jerk_deg_s3 = zeros(sampleCount, 2);

nodePosition_deg = initialState.position_deg;
nodeVelocity_deg_s = initialState.velocity_deg_s;
nodeAcceleration_deg_s2 = initialState.acceleration_deg_s2;
nextNodeIndex = 2;
for intervalIndex = 1:intervalCount
    intervalStartTime_s = (intervalIndex - 1) * timeStep_s;
    intervalEndTime_s = intervalIndex * timeStep_s;
    intervalJerk_deg_s3 = jerkByInterval_deg_s3(intervalIndex, :);
    while nextNodeIndex <= sampleCount && ...
            timeFromStart_s(nextNodeIndex) <= ...
            intervalEndTime_s + 10 * eps(intervalEndTime_s)
        localTime_s = timeFromStart_s(nextNodeIndex) - ...
            intervalStartTime_s;
        position_deg(nextNodeIndex, :) = nodePosition_deg + ...
            nodeVelocity_deg_s * localTime_s + 0.5 * ...
            nodeAcceleration_deg_s2 * localTime_s^2 + ...
            (1 / 6) * intervalJerk_deg_s3 * localTime_s^3;
        velocity_deg_s(nextNodeIndex, :) = nodeVelocity_deg_s + ...
            nodeAcceleration_deg_s2 * localTime_s + 0.5 * ...
            intervalJerk_deg_s3 * localTime_s^2;
        acceleration_deg_s2(nextNodeIndex, :) = ...
            nodeAcceleration_deg_s2 + ...
            intervalJerk_deg_s3 * localTime_s;
        jerk_deg_s3(nextNodeIndex, :) = intervalJerk_deg_s3;
        nextNodeIndex = nextNodeIndex + 1;
    end
    nodePosition_deg = nodePosition_deg + ...
        nodeVelocity_deg_s * timeStep_s + 0.5 * ...
        nodeAcceleration_deg_s2 * timeStep_s^2 + (1 / 6) * ...
        intervalJerk_deg_s3 * timeStep_s^3;
    nodeVelocity_deg_s = nodeVelocity_deg_s + ...
        nodeAcceleration_deg_s2 * timeStep_s + 0.5 * ...
        intervalJerk_deg_s3 * timeStep_s^2;
    nodeAcceleration_deg_s2 = nodeAcceleration_deg_s2 + ...
        intervalJerk_deg_s3 * timeStep_s;
end
position_deg(1, :) = initialState.position_deg;
velocity_deg_s(1, :) = initialState.velocity_deg_s;
acceleration_deg_s2(1, :) = initialState.acceleration_deg_s2;
jerk_deg_s3(1, :) = jerkByInterval_deg_s3(1, :);

sample = struct( ...
    "TimeFromStart_s", timeFromStart_s, ...
    "Position_deg", position_deg, ...
    "Velocity_deg_s", velocity_deg_s, ...
    "Acceleration_deg_s2", acceleration_deg_s2, ...
    "Jerk_deg_s3", jerk_deg_s3);
end
