function result = runAzElGauntletCase( ...
        name, description, azElData, startState, stopState, limits, ...
        options, planner)
%% Section 0: Header & Readme
% SYNTAX
%   result = runAzElGauntletCase(name, description, azElData, ...
%       startState, stopState, limits, options)
%   result = runAzElGauntletCase(name, description, azElData, ...
%       startState, stopState, limits, options, planner)
%**************************************************************************
% PURPOSE
%   - Run, independently collision-check, animate, and summarize one example.
%**************************************************************************
% INPUTS
%   - name, description (scalar text)
%       Display identity and concise scenario objective.
%   - azElData (canonical obstacle collection)
%       Obstacles passed unchanged to the planner and animation.
%   - startState, stopState, limits, options (scalar structs)
%       Public planner inputs.
%   - planner (function handle, optional)
%       Defaults to the maintained planAzElDijkstra entry point.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Inputs, successful plan, independent safety count, and plot handles.
%**************************************************************************
% UNITS
%   - Units follow the public planner schema.

%% Section 1: Select & Run The Planner
if nargin < 8 || isempty(planner)
    planner = @planAzElDijkstra;
end
plan = planner( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("runAzElGauntletCase:NoPath", ...
        "%s failed: %s", name, plan.message);
end

%% Section 2: Independently Recheck The Returned Command
blockedCommandSamples = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
if any(blockedCommandSamples)
    error("runAzElGauntletCase:Collision", ...
        "%s returned %d occupied command samples.", ...
        name, nnz(blockedCommandSamples));
end

%% Section 3: Animate The Planning Result
animationHandles = animateAzElAvoidancePlan( ...
    azElData, plan, defaultAzElAnimationOptions( ...
    struct(), struct( ...
    "MaximumAnimationFrames", 240, ...
    "MaximumDisplayedSlices", 100)));
title(animationHandles.AzElAxes, ...
    string(name) + ": " + string(description));

%% Section 4: Assemble & Print The Example Result
result = struct( ...
    "name", string(name), ...
    "description", string(description), ...
    "azElData", azElData, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "blockedSampleCount", nnz(blockedCommandSamples), ...
    "plotHandles", animationHandles, ...
    "animationHandles", animationHandles, ...
    "diagnostics", struct());
fprintf("%s: %.3f deg, %.2f s search, %d command samples.\n", ...
    name, plan.angularPathLength_deg, ...
    plan.searchElapsed_s, numel(plan.time_s));
end
