function opportunities = computePointTargetTrackOpportunities(scenario, task, options)
%COMPUTEPOINTTARGETTRACKOPPORTUNITIES Generate point-target tracking candidates.

if nargin < 3
    options = SchedulerOptions();
end
options = normalizeSchedulerOptions(options);
opportunities = emptyTaskCandidateTable(scenario.Config.Epoch.TimeZone);
targetName = string(taskField(task, "TargetName", ""));
target = scenario.getObject(targetName);
if isa(target, "AreaTargetObject")
    error("computePointTargetTrackOpportunities:AreaTarget", ...
        "Task target '%s' is an area target. Use computeAreaScanOpportunities.", targetName);
end

sensors = allowedSensorRows(scenario, task);
[earliest, latest] = taskTimeBounds(task, scenario);
requiredDwell = max([taskField(task, "RequiredDwellTimeSeconds", 0), ...
    taskField(task, "MinDurationSeconds", 0), options.MinimumCandidateDurationSeconds]);
maxDuration = taskField(task, "MaxDurationSeconds", Inf);
taskID = string(taskField(task, "TaskID", SensorTask.newID()));
taskName = string(taskField(task, "TaskName", taskID));
taskType = string(taskField(task, "TaskType", "TrackPointTarget"));
priority = taskField(task, "Priority", 1);

for s = 1:height(sensors)
    parentName = sensors.PlatformName(s);
    sensorName = sensors.SensorName(s);
    parent = scenario.getObject(parentName);
    sensor = parent.getSensor(sensorName);
    try
        access = computeSensorAccess(scenario, parentName, sensorName, targetName);
    catch err
        row = rejectedCandidate(taskID, taskName, taskType, sensorName, ...
            parentName, targetName, "", scenario.Config.Epoch, ...
            "Access computation failed: " + string(err.message), priority, ...
            taskField(task, "RequiresSimultaneousSensors", false), ...
            taskField(task, "RequiredSensorCount", 1));
        opportunities = [opportunities; row]; %#ok<AGROW>
        continue;
    end

    windows = access.AccessWindows;
    for w = 1:height(windows)
        startTime = max(windows.StartTime(w), earliest);
        stopTime = min(windows.StopTime(w), latest);
        durationSeconds = seconds(stopTime - startTime);
        if durationSeconds < requiredDwell || durationSeconds <= 0
            continue;
        end
        durationSeconds = min(durationSeconds, maxDuration);
        stopTime = startTime + seconds(durationSeconds);
        inWindow = access.TimeVector >= startTime & access.TimeVector <= stopTime;
        if ~any(inWindow)
            inWindow = access.TimeVector >= windows.StartTime(w) & access.TimeVector <= windows.StopTime(w);
        end
        meanRangeKm = mean(access.RangeKm(inWindow), "omitnan");
        minRangeKm = min(access.RangeKm(inWindow), [], "omitnan");
        maxElevationDeg = max(access.ElevationDeg(inWindow), [], "omitnan");
        meanOffNadirDeg = mean(access.OffBoresightAngleDeg(inWindow), "omitnan");
        maxOffNadirDeg = max(access.OffBoresightAngleDeg(inWindow), [], "omitnan");
        slewTimeSeconds = estimateCandidateSlewSeconds(sensor, maxOffNadirDeg);
        dwellTimeSeconds = min(durationSeconds, sensor.MaxDwellTimeSeconds);
        dataVolumeMb = sensor.estimateDataVolume(task, dwellTimeSeconds);
        powerUsedWh = sensor.PowerWatts * dwellTimeSeconds / 3600.0;
        quality = estimatePointQuality(sensor, meanOffNadirDeg, meanRangeKm, requiredDwell, dwellTimeSeconds);
        values = struct( ...
            "CandidateID", nextCandidateID(taskID, height(opportunities) + 1), ...
            "TaskID", taskID, ...
            "TaskName", taskName, ...
            "TaskType", taskType, ...
            "SensorName", sensorName, ...
            "PlatformName", parentName, ...
            "TargetName", targetName, ...
            "StartTime", startTime, ...
            "StopTime", stopTime, ...
            "DurationSeconds", durationSeconds, ...
            "SlewTimeSeconds", slewTimeSeconds, ...
            "DwellTimeSeconds", dwellTimeSeconds, ...
            "CoveragePercent", 100, ...
            "CoveredGridPointCount", 1, ...
            "TotalGridPointCount", 1, ...
            "MeanRangeKm", meanRangeKm, ...
            "MinRangeKm", minRangeKm, ...
            "MaxElevationDeg", maxElevationDeg, ...
            "MeanOffNadirDeg", meanOffNadirDeg, ...
            "MaxOffNadirDeg", maxOffNadirDeg, ...
            "EstimatedSwathKm", sensor.SwathWidthKm, ...
            "QualityScore", quality, ...
            "Priority", priority, ...
            "DataVolumeMb", dataVolumeMb, ...
            "PowerUsedWh", powerUsedWh, ...
            "Feasible", true, ...
            "RejectReason", "", ...
            "ConflictGroup", sensorName, ...
            "RequiresSimultaneousSensors", taskField(task, "RequiresSimultaneousSensors", false), ...
            "RequiredSensorCount", taskField(task, "RequiredSensorCount", 1));
        row = makeTaskCandidateRow(values, scenario.Config.Epoch.TimeZone);
        row.QualityScore(1) = scoreTaskCandidate(row, task, options);
        opportunities = [opportunities; row]; %#ok<AGROW>
    end
end
end

function row = rejectedCandidate(taskID, taskName, taskType, sensorName, parentName, ...
        targetName, areaTargetName, epoch, reason, priority, requiresSimultaneous, requiredSensorCount)
values = struct("CandidateID", nextCandidateID(taskID, 0), ...
    "TaskID", taskID, "TaskName", taskName, "TaskType", taskType, ...
    "SensorName", sensorName, "PlatformName", parentName, ...
    "TargetName", targetName, "AreaTargetName", areaTargetName, ...
    "StartTime", epoch, "StopTime", epoch, "DurationSeconds", 0, ...
    "Priority", priority, "Feasible", false, "RejectReason", reason, ...
    "RequiresSimultaneousSensors", requiresSimultaneous, ...
    "RequiredSensorCount", requiredSensorCount);
row = makeTaskCandidateRow(values, epoch.TimeZone);
end

function slewTimeSeconds = estimateCandidateSlewSeconds(sensor, angleDeg)
if ~isfinite(angleDeg)
    angleDeg = 0;
end
slewTimeSeconds = computeSlewTime(angleDeg, ...
    sensor.effectiveSlewRateDegPerSec(), sensor.effectiveSlewAccelDegPerSec2()) + ...
    sensor.SettlingTimeSeconds;
end

function quality = estimatePointQuality(sensor, meanOffNadirDeg, meanRangeKm, requiredDwell, dwellTimeSeconds)
if ~isfinite(meanOffNadirDeg)
    meanOffNadirDeg = sensor.effectiveConeHalfAngleDeg();
end
angleQuality = max(0, 1 - meanOffNadirDeg / max(sensor.FieldOfRegardDeg, eps));
if isfinite(sensor.MaxRangeKm)
    rangeQuality = max(0, 1 - meanRangeKm / max(sensor.MaxRangeKm, eps));
else
    rangeQuality = 1;
end
dwellQuality = min(1, dwellTimeSeconds / max(requiredDwell, eps));
quality = max(0, min(1, 0.45 * angleQuality + 0.25 * rangeQuality + 0.30 * dwellQuality));
end

function id = nextCandidateID(taskID, index)
id = string(taskID) + "-C" + compose("%03d", max(index, 1));
end
