function opportunities = computeAreaScanOpportunities(scenario, task, options)
%COMPUTEAREASCANOPPORTUNITIES Generate area scan candidates from grid coverage estimates.

if nargin < 3
    options = SchedulerOptions();
end
options = normalizeSchedulerOptions(options);
opportunities = emptyTaskCandidateTable(scenario.Config.Epoch.TimeZone);

areaTargetName = string(taskField(task, "TargetName", ""));
areaTarget = scenario.getObject(areaTargetName);
if ~isa(areaTarget, "AreaTargetObject")
    error("computeAreaScanOpportunities:NotAreaTarget", ...
        "Task target '%s' is not an AreaTargetObject.", areaTargetName);
end
gridPoints = areaTarget.getGridPoints();
totalGridPointCount = max(height(gridPoints), 1);
requiredCoverage = max([taskField(task, "RequiredCoveragePercent", areaTarget.RequiredCoveragePercent), ...
    options.MinimumCoveragePercent]);
requiredDwell = max([taskField(task, "RequiredDwellTimeSeconds", 0), ...
    areaTarget.RequiredDwellPerGridPointSeconds, ...
    options.MinimumCandidateDurationSeconds]);
taskID = string(taskField(task, "TaskID", SensorTask.newID()));
taskName = string(taskField(task, "TaskName", taskID));
taskType = string(taskField(task, "TaskType", "ScanAreaTarget"));
priority = taskField(task, "Priority", areaTarget.Priority);
[earliest, latest] = taskTimeBounds(task, scenario);
sensors = allowedSensorRows(scenario, task);

for s = 1:height(sensors)
    parentName = sensors.PlatformName(s);
    sensorName = sensors.SensorName(s);
    parent = scenario.getObject(parentName);
    sensor = parent.getSensor(sensorName);
    try
        access = computeSensorAccess(scenario, parentName, sensorName, ...
            areaTargetName, taskAccessOptions(scenario, options));
    catch err
        values = struct("CandidateID", string(taskID) + "-C000", ...
            "TaskID", taskID, "TaskName", taskName, "TaskType", taskType, ...
            "SensorName", sensorName, "PlatformName", parentName, ...
            "TargetName", areaTargetName, "AreaTargetName", areaTargetName, ...
            "StartTime", scenario.Config.Epoch, "StopTime", scenario.Config.Epoch, ...
            "Priority", priority, "Feasible", false, ...
            "RejectReason", "Access computation failed: " + string(err.message), ...
            "RequiresSimultaneousSensors", taskField(task, "RequiresSimultaneousSensors", false), ...
            "RequiredSensorCount", taskField(task, "RequiredSensorCount", 1));
        opportunities = [opportunities; makeTaskCandidateRow(values, scenario.Config.Epoch.TimeZone)]; %#ok<AGROW>
        continue;
    end

    windows = access.AccessWindows;
    for w = 1:height(windows)
        startTime = max(windows.StartTime(w), earliest);
        stopTime = min(windows.StopTime(w), latest);
        durationSeconds = seconds(stopTime - startTime);
        if durationSeconds <= 0 || durationSeconds < max(requiredDwell, options.MinimumCandidateDurationSeconds)
            continue;
        end
        [coveredCount, coveragePercent, estimatedSwathKm] = estimateAreaCoverage( ...
            sensor, areaTarget, durationSeconds, totalGridPointCount, requiredDwell);
        feasible = coveragePercent >= requiredCoverage || options.AllowPartialAreaCoverage;
        rejectReason = "";
        if ~feasible
            rejectReason = "Coverage below required threshold.";
        end
        inWindow = access.TimeVector >= startTime & access.TimeVector <= stopTime;
        if ~any(inWindow)
            inWindow = access.TimeVector >= windows.StartTime(w) & access.TimeVector <= windows.StopTime(w);
        end
        meanRangeKm = mean(access.RangeKm(inWindow), "omitnan");
        minRangeKm = min(access.RangeKm(inWindow), [], "omitnan");
        maxElevationDeg = max(access.ElevationDeg(inWindow), [], "omitnan");
        meanOffNadirDeg = mean(access.OffBoresightAngleDeg(inWindow), "omitnan");
        maxOffNadirDeg = max(access.OffBoresightAngleDeg(inWindow), [], "omitnan");
        slewTimeSeconds = computeSlewTime(maxOffNadirDeg, ...
            sensor.effectiveSlewRateDegPerSec(), sensor.effectiveSlewAccelDegPerSec2()) + ...
            sensor.SettlingTimeSeconds;
        dataVolumeMb = sensor.estimateDataVolume(task, durationSeconds);
        powerUsedWh = sensor.PowerWatts * durationSeconds / 3600.0;
        quality = max(0, min(1, coveragePercent / 100));
        values = struct( ...
            "CandidateID", string(taskID) + "-C" + compose("%03d", height(opportunities) + 1), ...
            "TaskID", taskID, ...
            "TaskName", taskName, ...
            "TaskType", taskType, ...
            "SensorName", sensorName, ...
            "PlatformName", parentName, ...
            "TargetName", areaTargetName, ...
            "AreaTargetName", areaTargetName, ...
            "StartTime", startTime, ...
            "StopTime", stopTime, ...
            "DurationSeconds", durationSeconds, ...
            "SlewTimeSeconds", slewTimeSeconds, ...
            "DwellTimeSeconds", durationSeconds, ...
            "CoveragePercent", coveragePercent, ...
            "CoveredGridPointCount", coveredCount, ...
            "TotalGridPointCount", totalGridPointCount, ...
            "MeanRangeKm", meanRangeKm, ...
            "MinRangeKm", minRangeKm, ...
            "MaxElevationDeg", maxElevationDeg, ...
            "MeanOffNadirDeg", meanOffNadirDeg, ...
            "MaxOffNadirDeg", maxOffNadirDeg, ...
            "EstimatedSwathKm", estimatedSwathKm, ...
            "QualityScore", quality, ...
            "Priority", priority, ...
            "DataVolumeMb", dataVolumeMb, ...
            "PowerUsedWh", powerUsedWh, ...
            "Feasible", feasible, ...
            "RejectReason", rejectReason, ...
            "ConflictGroup", sensorName, ...
            "RequiresSimultaneousSensors", taskField(task, "RequiresSimultaneousSensors", false), ...
            "RequiredSensorCount", taskField(task, "RequiredSensorCount", 1));
        row = makeTaskCandidateRow(values, scenario.Config.Epoch.TimeZone);
        row.QualityScore(1) = scoreTaskCandidate(row, task, options);
        opportunities = [opportunities; row]; %#ok<AGROW>
    end
end
end

function [coveredCount, coveragePercent, estimatedSwathKm] = estimateAreaCoverage( ...
        sensor, areaTarget, durationSeconds, totalGridPointCount, requiredDwell)
estimatedSwathKm = sensor.SwathWidthKm;
if ~isfinite(estimatedSwathKm) || estimatedSwathKm <= 0
    estimatedSwathKm = max(1, areaTarget.GridResolutionKm) * ...
        max(1, sensor.effectiveConeHalfAngleDeg() / 5);
end
pointsPerDwell = max(1, round(estimatedSwathKm / max(areaTarget.GridResolutionKm, eps)));
if requiredDwell <= 0
    requiredDwell = 1;
end
coveredCount = min(totalGridPointCount, max(1, floor(durationSeconds / requiredDwell) * pointsPerDwell));
coveragePercent = 100 * coveredCount / totalGridPointCount;
end
