function opportunities = computeMultiSensorTaskOpportunities(scenario, task, options)
%COMPUTEMULTISENSORTASKOPPORTUNITIES Combine single-sensor candidates into cooperative candidates.

if nargin < 3
    options = SchedulerOptions();
end
options = normalizeSchedulerOptions(options);
opportunities = emptyTaskCandidateTable(scenario.Config.Epoch.TimeZone);
if ~options.AllowMultiSensorTasks
    return;
end

singleTask = task;
if isobject(singleTask) && isprop(singleTask, "RequiredSensorCount")
    singleTask.RequiredSensorCount = 1;
    singleTask.RequiresSimultaneousSensors = false;
elseif isstruct(singleTask)
    singleTask.RequiredSensorCount = 1;
    singleTask.RequiresSimultaneousSensors = false;
end

taskType = upper(string(taskField(task, "TaskType", "")));
if contains(taskType, "AREA")
    singles = computeAreaScanOpportunities(scenario, singleTask, options);
else
    singles = computePointTargetTrackOpportunities(scenario, singleTask, options);
end
singles = singles(singles.Feasible, :);
requiredSensorCount = taskField(task, "RequiredSensorCount", 2);
if height(singles) < requiredSensorCount
    return;
end

taskID = string(taskField(task, "TaskID", SensorTask.newID()));
taskName = string(taskField(task, "TaskName", taskID));
priority = taskField(task, "Priority", 1);
requiresSimultaneous = taskField(task, "RequiresSimultaneousSensors", true);

for a = 1:height(singles)
    for b = a + 1:height(singles)
        if singles.SensorName(a) == singles.SensorName(b)
            continue;
        end
        startTime = max(singles.StartTime(a), singles.StartTime(b));
        stopTime = min(singles.StopTime(a), singles.StopTime(b));
        overlapSeconds = seconds(stopTime - startTime);
        if requiresSimultaneous && overlapSeconds < options.SimultaneousToleranceSeconds
            continue;
        end
        if ~requiresSimultaneous
            startTime = min(singles.StartTime(a), singles.StartTime(b));
            stopTime = max(singles.StopTime(a), singles.StopTime(b));
            overlapSeconds = seconds(stopTime - startTime);
        end
        sensorNames = singles.SensorName(a) + "," + singles.SensorName(b);
        platformNames = singles.PlatformName(a) + "," + singles.PlatformName(b);
        coveragePercent = min(100, singles.CoveragePercent(a) + singles.CoveragePercent(b));
        quality = mean([singles.QualityScore(a), singles.QualityScore(b)], "omitnan");
        values = struct( ...
            "CandidateID", taskID + "-M" + compose("%03d", height(opportunities) + 1), ...
            "TaskID", taskID, ...
            "TaskName", taskName, ...
            "TaskType", string(taskField(task, "TaskType", "MultiSensorTrackPointTarget")), ...
            "SensorName", sensorNames, ...
            "PlatformName", platformNames, ...
            "TargetName", string(taskField(task, "TargetName", "")), ...
            "AreaTargetName", singles.AreaTargetName(a), ...
            "StartTime", startTime, ...
            "StopTime", stopTime, ...
            "DurationSeconds", overlapSeconds, ...
            "SlewTimeSeconds", max(singles.SlewTimeSeconds(a), singles.SlewTimeSeconds(b)), ...
            "DwellTimeSeconds", min(singles.DwellTimeSeconds(a), singles.DwellTimeSeconds(b)), ...
            "CoveragePercent", coveragePercent, ...
            "CoveredGridPointCount", singles.CoveredGridPointCount(a) + singles.CoveredGridPointCount(b), ...
            "TotalGridPointCount", max(singles.TotalGridPointCount(a), singles.TotalGridPointCount(b)), ...
            "MeanRangeKm", mean([singles.MeanRangeKm(a), singles.MeanRangeKm(b)], "omitnan"), ...
            "MinRangeKm", min([singles.MinRangeKm(a), singles.MinRangeKm(b)], [], "omitnan"), ...
            "MaxElevationDeg", max([singles.MaxElevationDeg(a), singles.MaxElevationDeg(b)], [], "omitnan"), ...
            "MeanOffNadirDeg", mean([singles.MeanOffNadirDeg(a), singles.MeanOffNadirDeg(b)], "omitnan"), ...
            "MaxOffNadirDeg", max([singles.MaxOffNadirDeg(a), singles.MaxOffNadirDeg(b)], [], "omitnan"), ...
            "EstimatedSwathKm", sum([singles.EstimatedSwathKm(a), singles.EstimatedSwathKm(b)], "omitnan"), ...
            "QualityScore", quality, ...
            "Priority", priority, ...
            "DataVolumeMb", singles.DataVolumeMb(a) + singles.DataVolumeMb(b), ...
            "PowerUsedWh", singles.PowerUsedWh(a) + singles.PowerUsedWh(b), ...
            "Feasible", true, ...
            "RejectReason", "", ...
            "ConflictGroup", sensorNames, ...
            "RequiresSimultaneousSensors", requiresSimultaneous, ...
            "RequiredSensorCount", requiredSensorCount);
        row = makeTaskCandidateRow(values, scenario.Config.Epoch.TimeZone);
        row.QualityScore(1) = scoreTaskCandidate(row, task, options);
        opportunities = [opportunities; row]; %#ok<AGROW>
    end
end
end
