function data = createSlewTransitionData(scenario, parentName, sensorName, ...
        targetName, startTime, stopTime)
%CREATESLEWTRANSITIONDATA Serialize one sensor's endpoint transition model.
% Times are Unix seconds; pointing vectors use SensorObject's parent body
% frame (satellite orbital basis or fixed-site ENU). Limits are deg/s and
% deg/s^2. String limits preserve Inf through JSON and CSV round trips.
% Area scans and moving-parent attitudes have no known endpoint commands;
% their resource occupancy is retained with HasSlewGeometry=false.
parent = scenario.getObject(parentName);
target = scenario.getObject(targetName);
sensor = parent.getSensor(sensorName);
known = ~isa(target, "AreaTargetObject") && ...
    ~(isa(parent, "TargetObject") && parent.isMoving());
entry = struct("PlatformName", string(parentName), ...
    "SensorName", string(sensorName), ...
    "StartTimeUnixSeconds", posixtime(startTime), ...
    "StopTimeUnixSeconds", posixtime(stopTime), ...
    "HasSlewGeometry", known, ...
    "Frame", "ParentBody", ...
    "StartPointing", zeros(0, 3), "StopPointing", zeros(0, 3), ...
    "RateDegPerSec", string(sensor.effectiveSlewRateDegPerSec()), ...
    "AccelerationDegPerSec2", string(sensor.effectiveSlewAccelDegPerSec2()), ...
    "AxisRatesDegPerSec", string([sensor.AzimuthRateLimitDegPerSec, ...
        sensor.ElevationRateLimitDegPerSec]), ...
    "AxisAccelerationsDegPerSec2", ...
        string([sensor.AzimuthAccelerationLimitDegPerSec2, ...
        sensor.ElevationAccelerationLimitDegPerSec2]), ...
    "SettlingTimeSeconds", sensor.SettlingTimeSeconds);
if known
    entry.StartPointing = endpointPointing(parent, target, startTime);
    entry.StopPointing = endpointPointing(parent, target, stopTime);
end
data = string(jsonencode(entry));
end

function pointing = endpointPointing(parent, target, time)
% Express the line of sight in the same parent coordinates at each endpoint.
look = SensorObject.objectPositionECEF(target, time) - ...
    SensorObject.objectPositionECEF(parent, time);
if any(~isfinite(look)) || norm(look) == 0
    error("createSlewTransitionData:InvalidPointing", ...
        "Target line of sight must be finite and nonzero at each endpoint.");
end
basis = zeros(3);
for axisIndex = 1:3
    direction = zeros(1, 3);
    direction(axisIndex) = 1;
    basis(axisIndex, :) = SensorObject.bodyVectorToECEF(parent, time, direction);
end
pointing = (look / norm(look)) * basis.';
end
