function candidates = emptyTaskCandidateTable(timeZone)
%EMPTYTASKCANDIDATETABLE Create an empty scheduler-ready candidate table.

if nargin < 1 || strlength(string(timeZone)) == 0
    timeZone = "UTC";
end

candidates = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    NaT(0, 1, "TimeZone", char(timeZone)), ...
    NaT(0, 1, "TimeZone", char(timeZone)), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), nan(0, 1), nan(0, 1), nan(0, 1), ...
    nan(0, 1), nan(0, 1), nan(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), false(0, 1), strings(0, 1), ...
    strings(0, 1), false(0, 1), zeros(0, 1), ...
    'VariableNames', {'CandidateID', 'TaskID', 'TaskName', 'TaskType', ...
    'SensorName', 'PlatformName', 'TargetName', 'AreaTargetName', ...
    'StartTime', 'StopTime', 'DurationSeconds', 'SlewTimeSeconds', ...
    'DwellTimeSeconds', 'CoveragePercent', 'CoveredGridPointCount', ...
    'TotalGridPointCount', 'MeanRangeKm', 'MinRangeKm', 'MaxElevationDeg', ...
    'MeanOffNadirDeg', 'MaxOffNadirDeg', 'EstimatedSwathKm', 'QualityScore', ...
    'Priority', 'DataVolumeMb', 'PowerUsedWh', 'Feasible', 'RejectReason', ...
    'ConflictGroup', 'RequiresSimultaneousSensors', 'RequiredSensorCount'});
end
