function conflicts = emptyTaskConflictTable()
%EMPTYTASKCONFLICTTABLE Create an empty task conflict table.

conflicts = table(strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    'VariableNames', {'ConflictID', 'CandidateID_1', 'CandidateID_2', ...
    'ConflictType', 'SensorName', 'OverlapSeconds', 'RequiredSlewSeconds', ...
    'AvailableSlewSeconds', 'Explanation'});
end
