function row = makeTaskCandidateRow(values, timeZone)
%MAKETASKCANDIDATEROW Build one row matching emptyTaskCandidateTable.

if nargin < 2
    timeZone = "UTC";
end
defaults = struct( ...
    "CandidateID", "", ...
    "TaskID", "", ...
    "TaskName", "", ...
    "TaskType", "", ...
    "SensorName", "", ...
    "PlatformName", "", ...
    "TargetName", "", ...
    "AreaTargetName", "", ...
    "StartTime", NaT(1, 1, "TimeZone", char(timeZone)), ...
    "StopTime", NaT(1, 1, "TimeZone", char(timeZone)), ...
    "DurationSeconds", 0, ...
    "SlewTimeSeconds", 0, ...
    "DwellTimeSeconds", 0, ...
    "CoveragePercent", 0, ...
    "CoveredGridPointCount", 0, ...
    "TotalGridPointCount", 0, ...
    "MeanRangeKm", NaN, ...
    "MinRangeKm", NaN, ...
    "MaxElevationDeg", NaN, ...
    "MeanOffNadirDeg", NaN, ...
    "MaxOffNadirDeg", NaN, ...
    "EstimatedSwathKm", NaN, ...
    "QualityScore", 0, ...
    "Priority", 0, ...
    "DataVolumeMb", 0, ...
    "PowerUsedWh", 0, ...
    "Feasible", false, ...
    "RejectReason", "", ...
    "ConflictGroup", "", ...
    "RequiresSimultaneousSensors", false, ...
    "RequiredSensorCount", 1);
fields = fieldnames(defaults);
for k = 1:numel(fields)
    if isfield(values, fields{k})
        defaults.(fields{k}) = values.(fields{k});
    end
end

row = table( ...
    string(defaults.CandidateID), string(defaults.TaskID), ...
    string(defaults.TaskName), string(defaults.TaskType), ...
    string(defaults.SensorName), string(defaults.PlatformName), ...
    string(defaults.TargetName), string(defaults.AreaTargetName), ...
    defaults.StartTime, defaults.StopTime, defaults.DurationSeconds, ...
    defaults.SlewTimeSeconds, defaults.DwellTimeSeconds, ...
    defaults.CoveragePercent, defaults.CoveredGridPointCount, ...
    defaults.TotalGridPointCount, defaults.MeanRangeKm, defaults.MinRangeKm, ...
    defaults.MaxElevationDeg, defaults.MeanOffNadirDeg, defaults.MaxOffNadirDeg, ...
    defaults.EstimatedSwathKm, defaults.QualityScore, defaults.Priority, ...
    defaults.DataVolumeMb, defaults.PowerUsedWh, defaults.Feasible, ...
    string(defaults.RejectReason), string(defaults.ConflictGroup), ...
    defaults.RequiresSimultaneousSensors, defaults.RequiredSensorCount, ...
    'VariableNames', {'CandidateID', 'TaskID', 'TaskName', 'TaskType', ...
    'SensorName', 'PlatformName', 'TargetName', 'AreaTargetName', ...
    'StartTime', 'StopTime', 'DurationSeconds', 'SlewTimeSeconds', ...
    'DwellTimeSeconds', 'CoveragePercent', 'CoveredGridPointCount', ...
    'TotalGridPointCount', 'MeanRangeKm', 'MinRangeKm', 'MaxElevationDeg', ...
    'MeanOffNadirDeg', 'MaxOffNadirDeg', 'EstimatedSwathKm', 'QualityScore', ...
    'Priority', 'DataVolumeMb', 'PowerUsedWh', 'Feasible', 'RejectReason', ...
    'ConflictGroup', 'RequiresSimultaneousSensors', 'RequiredSensorCount'});
end
