function diagnostics = analyzeWorldsHardestWindmillGauntlet(problem, plan)
%ANALYZEWORLDSHARDESTWINDMILLGAUNTLET Measure traversal and following.

if ~isstruct(plan) || ~isfield(plan, "success") || ~plan.success
    error("analyzeWorldsHardestWindmillGauntlet:InvalidPlan", ...
        "plan must be a successful windmill-gauntlet plan.");
end
centers = problem.geometry.centers_deg;
followAngle = zeros(1, size(centers, 1));
encounterDuration = zeros(1, size(centers, 1));
sampleStep = median(diff(plan.time_s));
for windmill = 1:size(centers, 1)
    delta = plan.position_deg - centers(windmill, :);
    distance = hypot(delta(:, 1), delta(:, 2));
    near = distance <= 3.1;
    encounterDuration(windmill) = sampleStep * nnz(near);
    if nnz(near) >= 2
        angle = unwrap(atan2(delta(near, 2), delta(near, 1)));
        followAngle(windmill) = rad2deg(max(angle) - min(angle));
    end
end
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", problem.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
diagnostics = struct( ...
    "maximumAzimuth_deg", max(plan.position_deg(:, 1)), ...
    "visitedUpperCorridor", any(plan.position_deg(:, 2) >= 3), ...
    "visitedLowerCorridor", any(plan.position_deg(:, 2) <= -3), ...
    "followAngle_deg", followAngle, ...
    "encounterDuration_s", encounterDuration, ...
    "maximumFollowAngle_deg", max(followAngle), ...
    "maximumEncounterDuration_s", max(encounterDuration), ...
    "blockedSampleCount", nnz(blocked));
end
