function result = exampleWorldsHardestWindmillGauntlet(viewOptions)
%EXAMPLEWORLDSHARDESTWINDMILLGAUNTLET Animate a level-6-inspired run.
%
% Coins are intentionally omitted. Eight dotted windmills share one angular
% rate, and the boresight must time their gaps through an S-shaped corridor.

if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 500, ...
    "MaximumDisplayedSlices", 140, ...
    "PauseSeconds", 0.01, ...
    "ObstacleFaceAlpha", 0.045));

problem = makeWorldsHardestWindmillGauntlet();
plan = planAzElSpaceTimeFunnel( ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
if ~plan.success
    error("exampleWorldsHardestWindmillGauntlet:NoPath", ...
        "Planner failed: %s", plan.message);
end
diagnostics = analyzeWorldsHardestWindmillGauntlet(problem, plan);
if diagnostics.blockedSampleCount > 0
    error("exampleWorldsHardestWindmillGauntlet:Collision", ...
        "The planned command contains %d blocked samples.", ...
        diagnostics.blockedSampleCount);
end
if diagnostics.maximumAzimuth_deg < ...
        problem.geometry.rightConnectorAzimuth_deg
    error("exampleWorldsHardestWindmillGauntlet:MissedConnector", ...
        "The boresight did not traverse the right-side connector.");
end
if ~diagnostics.visitedUpperCorridor || ...
        ~diagnostics.visitedLowerCorridor
    error("exampleWorldsHardestWindmillGauntlet:IncompleteTraversal", ...
        "The path did not traverse both windmill rows.");
end
if diagnostics.maximumFollowAngle_deg < 35
    error("exampleWorldsHardestWindmillGauntlet:NoWindmillFollow", ...
        "The path did not follow any windmill long enough to find a gap.");
end

view = animateAzElAvoidancePlan( ...
    problem.azElData, plan, viewOptions);
result = problem;
result.plan = plan;
result.diagnostics = diagnostics;
result.view = view;
fprintf(['Windmill gauntlet: %.3f deg, %.3f s search, ' ...
    'maximum windmill-follow angle %.1f deg.\n'], ...
    plan.angularPathLength_deg, plan.searchElapsed_s, ...
    diagnostics.maximumFollowAngle_deg);
end
