function result = exampleGauntlet05UTrapEscape()
%EXAMPLEGAUNTLET05UTRAPESCAPE Move away from the goal to escape a U-trap.

time_s = (0:0.5:60).';
regions = { ...
    [3, -6; 6, -6; 6, 6; 3, 6; 3, -6], ...
    [-6, 5; 6, 5; 6, 6; -6, 6; -6, 5], ...
    [-6, -6; 6, -6; 6, -5; -6, -5; -6, -6]};
[azimuth, elevation] = joinRegions(regions);
azElData = makeAzElObstacleData( ...
    "U-shaped trap", time_s, azimuth, elevation);
startState = boundaryState(0, [0, 0]);
stopState = boundaryState(60, [15, 0]);
limits = struct( ...
    "azimuth_deg", [-10, 18], ...
    "elevation_deg", [-10, 10], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 1, ...
    "SafetyMargin_deg", 0.25, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumTime", ...
    "MaxSearchTime_s", 60, ...
    "MaxExpansions", 750000);

result = runAzElGauntletCase( ...
    "Gauntlet 5", ...
    "U-trap escape by backtracking", ...
    azElData, startState, stopState, limits, options);
result.diagnostics.minimumAzimuth_deg = ...
    min(result.plan.positionUnwrapped_deg(:, 1));
if result.diagnostics.minimumAzimuth_deg > -6.25
    error("exampleGauntlet05UTrapEscape:DidNotBacktrack", ...
        "The route did not move left far enough to escape the U-trap.");
end
fprintf("  Furthest move away from goal: azimuth %.2f deg.\n", ...
    result.diagnostics.minimumAzimuth_deg);
end

function [azimuth, elevation] = joinRegions(regions)
rowCount = sum(cellfun(@(region) size(region, 1), regions)) + ...
    numel(regions) - 1;
combined = nan(rowCount, 2);
cursor = 1;
for regionIndex = 1:numel(regions)
    region = regions{regionIndex};
    output = cursor:cursor + size(region, 1) - 1;
    combined(output, :) = region;
    cursor = output(end) + 2;
end
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
