function plan = exampleVietnamChinaAzElAvoidance( ...
        vietnamAzElData, chinaAzElData, viewOptions)
%EXAMPLEVIETNAMCHINAAZELAVOIDANCE Avoid Vietnam and China together.
%
% plan = exampleVietnamChinaAzElAvoidance(vietnam, china)
%
% vietnam and china are independent calculateAreaTargetAzEl-style structs.
% With no inputs, bundled ADM0 latitude/longitude boundaries are mapped by
% azimuth = longitude - 110 degrees and elevation = latitude. This
% translation-only map preserves the geographic outlines for a standalone
% visualization, but it is not a physical sensor-frame projection.

if nargin == 0
    [vietnamAzElData, chinaAzElData] = demoCountryProjections();
    viewOptions = struct();
elseif nargin == 2
    viewOptions = struct();
elseif nargin ~= 3
    error("exampleVietnamChinaAzElAvoidance:InvalidInputCount", ...
        "Provide both Vietnam and China azElData structs, or no inputs.");
end

azElData = combineAzElObstacles( ...
    vietnamAzElData, chinaAzElData);
if numel(azElData) ~= 2
    error("exampleVietnamChinaAzElAvoidance:InvalidObstacleCount", ...
        "The example requires exactly one Vietnam and one China obstacle.");
end

startTime_s = max(arrayfun( ...
    @(item) item.time_s(1), azElData));
stopTime_s = min(arrayfun( ...
    @(item) item.time_s(end), azElData));
if stopTime_s - startTime_s < 150
    error("exampleVietnamChinaAzElAvoidance:ShortOverlap", ...
        ["Vietnam and China must have at least 150 seconds of " ...
        "overlapping azElData."]);
end

startState = boundaryState(startTime_s, [-30, 0]);
stopState = boundaryState(stopTime_s, [80, 80]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-90, 90], ...
    "maxVelocity_deg_s", [1, 1], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 1, ...
    "GridStep_deg", 0.5, ...
    "TopologyGridStep_deg", 0.5, ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance", ...
    "FallbackToExistingPlanner", false, ...
    "MaxSearchTime_s", 30, ...
    "MaximumVerticesPerRegion", 500);

plan = planAzElAutonomousCorridor( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("exampleVietnamChinaAzElAvoidance:NoPath", ...
        "%s", plan.message);
end
if plan.workspace.ObstacleCount ~= 2
    error("exampleVietnamChinaAzElAvoidance:WorkspaceMismatch", ...
        "Expected two independently packed obstacles.");
end

names = string({plan.workspace.Obstacles.Name});
fprintf("Packed obstacles: %s\n", strjoin(names, ", "));
fprintf("Path length: %.3f deg (<= %.3fx global optimum).\n", ...
    plan.angularPathLength_deg, plan.suboptimalityBound);
animationHandles = animateAzElAvoidancePlan( ...
    azElData, plan, defaultAzElAnimationOptions( ...
    viewOptions, struct( ...
    "MaximumAnimationFrames", 240, ...
    "MaximumDisplayedSlices", 120)));
title(animationHandles.AzElAxes, ...
    "ADM0 boundaries in the demo az/el map");
plan.animationHandles = animationHandles;
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end

function [vietnam, china] = demoCountryProjections()
time_s = (2700:1:3000).';
vietnamBoundary = loadCountryBoundaryLatLon("Vietnam");
chinaBoundary = loadCountryBoundaryLatLon("China");
vietnam = geographicDemoObstacle(vietnamBoundary, time_s);
china = geographicDemoObstacle(chinaBoundary, time_s);
fprintf("Boundary vertices: Vietnam %d, China %d.\n", ...
    vietnamBoundary.vertexCount, chinaBoundary.vertexCount);
end

function data = geographicDemoObstacle(boundary, time_s)
sampleCount = numel(time_s);
azimuthBoundary = boundary.longitude_deg - 110;
elevationBoundary = boundary.latitude_deg;
azimuth = repmat({azimuthBoundary}, sampleCount, 1);
elevation = repmat({elevationBoundary}, sampleCount, 1);
data = struct( ...
    "targetName", boundary.name, ...
    "time_s", time_s, ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", repmat("visible", sampleCount, 1));
end
