function result = exampleGauntlet05UTrapEscape()
%EXAMPLEGAUNTLET05UTRAPESCAPE Move away from the goal to escape a U-trap.

time_s = (0:0.5:60).';
regions = { ...
    [3, -6; 6, -6; 6, 6; 3, 6; 3, -6], ...
    [-6, 5; 6, 5; 6, 6; -6, 6; -6, 5], ...
    [-6, -6; 6, -6; 6, -5; -6, -5; -6, -6]};
[azimuth, elevation] = joinRegions(regions);
azElData = makeAzElObstacleData( ...
    "U-shaped trap", time_s, azimuth, elevation);
startState = boundaryState(0, [0, 0]);
stopState = boundaryState(60, [15, 0]);
limits = struct( ...
    "azimuth_deg", [-10, 18], ...
    "elevation_deg", [-10, 10], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 1, ...
    "TopologyGridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0.25, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "UseAnyAngleRelaxation", true, ...
    "EnableTopologyRefinement", true, ...
    "RefinementGridStep_deg", 0.125, ...
    "RefinementCorridorHalfWidth_deg", 1.5, ...
    "FallbackToExistingPlanner", false, ...
    "MaxSearchTime_s", 60, ...
    "MaxExpansions", 1000000);

result = runAzElGauntletCase( ...
    "Gauntlet 5", ...
    "U-trap escape by backtracking", ...
    azElData, startState, stopState, limits, options, ...
    @planAzElAutonomousCorridor);
result.diagnostics.minimumAzimuth_deg = ...
    min(result.plan.positionUnwrapped_deg(:, 1));
result.diagnostics.minimumElevation_deg = ...
    min(result.plan.position_deg(:, 2));
result.diagnostics.maximumElevation_deg = ...
    max(result.plan.position_deg(:, 2));
if result.diagnostics.minimumAzimuth_deg > -6.25
    error("exampleGauntlet05UTrapEscape:DidNotBacktrack", ...
        "The route did not move left far enough to escape the U-trap.");
end
if result.plan.angularPathLength_deg >= 33 || ...
        max(abs(result.plan.position_deg(:, 2))) >= 7
    error("exampleGauntlet05UTrapEscape:LongEscape", ...
        "The planner did not find a compact wall-hugging escape.");
end
fprintf("  Furthest move away from goal: azimuth %.2f deg.\n", ...
    result.diagnostics.minimumAzimuth_deg);
fprintf("  Compact wall-hugging escape length: %.3f deg.\n", ...
    result.plan.angularPathLength_deg);
end

function [azimuth, elevation] = joinRegions(regions)
rowCount = sum(cellfun(@(region) size(region, 1), regions)) + ...
    numel(regions) - 1;
combined = nan(rowCount, 2);
cursor = 1;
for regionIndex = 1:numel(regions)
    region = regions{regionIndex};
    output = cursor:cursor + size(region, 1) - 1;
    combined(output, :) = region;
    cursor = output(end) + 2;
end
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
