function result = exampleGauntlet03WrappedSeamDetour()
%EXAMPLEGAUNTLET03WRAPPEDSEAMDETOUR Detour across the azimuth wrap seam.

time_s = (0:0.5:30).';
[azimuth, elevation] = seamObstacle();
azElData = makeAzElObstacleData( ...
    "Wrapped seam blocker", time_s, azimuth, elevation);
startState = boundaryState(0, [170, 0]);
stopState = boundaryState(30, [-170, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-20, 20], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [2, 2]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", 0.5, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 30);

result = runAzElGauntletCase( ...
    "Gauntlet 3", ...
    "wrapped-azimuth seam detour", ...
    azElData, startState, stopState, limits, options);
unwrappedAzimuth = result.plan.positionUnwrapped_deg(:, 1);
result.diagnostics.maximumUnwrappedStep_deg = ...
    max(abs(diff(unwrappedAzimuth)));
result.diagnostics.maximumElevationDetour_deg = ...
    max(abs(result.plan.position_deg(:, 2)));
if result.diagnostics.maximumUnwrappedStep_deg > 2 || ...
        result.diagnostics.maximumElevationDetour_deg < 5
    error("exampleGauntlet03WrappedSeamDetour:InvalidDetour", ...
        "The seam path is discontinuous or did not clear the blocker.");
end
fprintf("  Maximum unwrapped step %.2f deg; elevation detour %.2f deg.\n", ...
    result.diagnostics.maximumUnwrappedStep_deg, ...
    result.diagnostics.maximumElevationDetour_deg);
end

function [azimuth, elevation] = seamObstacle()
positive = [ ...
    174, -5; ...
    180, -5; ...
    180, 5; ...
    174, 5; ...
    174, -5];
negative = [ ...
    -180, -5; ...
    -174, -5; ...
    -174, 5; ...
    -180, 5; ...
    -180, -5];
combined = [positive; NaN, NaN; negative];
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
