function result = exampleChasedBoresightGauntlet(viewOptions)
%EXAMPLECHASEDBORESIGHTGAUNTLET Animate pursuit until a late goal opens.
%
% result = exampleChasedBoresightGauntlet()
% result = exampleChasedBoresightGauntlet(viewOptions)

if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 500, ...
    "MaximumDisplayedSlices", 120, ...
    "PauseSeconds", 0.01, ...
    "ShowFuturePath", true, ...
    "ShowObstacleSlices", true, ...
    "ObstacleFaceAlpha", 0.05));

problem = makeChasedBoresightGauntlet();
plan = planAzElSpaceTimeFunnel( ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
if ~plan.success
    error("exampleChasedBoresightGauntlet:NoPath", ...
        "Planner failed: %s", plan.message);
end
diagnostics = analyzeChasedBoresightGauntlet(problem, plan);
if diagnostics.blockedSampleCount > 0
    error("exampleChasedBoresightGauntlet:Collision", ...
        "The planned command contains %d blocked samples.", ...
        diagnostics.blockedSampleCount);
end
if diagnostics.goalArrivalTime_s < ...
        problem.geometry.goalOpenTime_s - 1e-9
    error("exampleChasedBoresightGauntlet:EarlyGoalArrival", ...
        "The boresight reached the sealed goal too early.");
end
if diagnostics.movingFractionBeforeGoalOpen < 0.8
    error("exampleChasedBoresightGauntlet:InsufficientMotion", ...
        "The boresight did not keep steering while pursued.");
end
if diagnostics.longestWaitBeforeGoalOpen_s > 12
    error("exampleChasedBoresightGauntlet:WaitedTooLong", ...
        "The pursued boresight stopped long enough to invalidate the test.");
end
if diagnostics.angularPathLength_deg < 120
    error("exampleChasedBoresightGauntlet:ShortPath", ...
        "The route did not complete the expected defensive loop.");
end

view = animateAzElAvoidancePlan( ...
    problem.azElData, plan, viewOptions);
result = problem;
result.plan = plan;
result.diagnostics = diagnostics;
result.view = view;
fprintf(['Chased-boresight gauntlet: %.3f deg, %.3f s search, ' ...
    'goal opened at %.1f s and reached at %.1f s.\n'], ...
    plan.angularPathLength_deg, plan.searchElapsed_s, ...
    diagnostics.goalOpenTime_s, diagnostics.goalArrivalTime_s);
end
