function result = exampleRandomBlinkingChessboardIntercept( ...
        seed, viewOptions)
%EXAMPLERANDOMBLINKINGCHESSBOARDINTERCEPT Catch a stochastic moving point.
%
% Leave seed empty for a new case on every run. The printed seed replays
% the exact board and moving endpoint if a failure needs investigation.

if nargin < 1
    seed = [];
end
if nargin < 2
    viewOptions = struct();
end
problem = makeRandomBlinkingChessboardGauntlet(seed);
plan = planAzElMovingTargetIntercept( ...
    problem.azElData, problem.startState, problem.target, ...
    problem.limits, problem.options);
if ~plan.success
    error("exampleRandomBlinkingChessboardIntercept:NoIntercept", ...
        "Seed %u failed: %s", uint32(problem.seed), plan.message);
end
diagnostics = analyzeBlinkingChessboardIntercept(problem, plan);
if diagnostics.blockedBoresightSampleCount > 0
    error("exampleRandomBlinkingChessboardIntercept:Collision", ...
        "Seed %u returned %d blocked boresight samples.", ...
        uint32(problem.seed), ...
        diagnostics.blockedBoresightSampleCount);
end
if diagnostics.catchError_deg > ...
        problem.options.CatchTolerance_deg
    error("exampleRandomBlinkingChessboardIntercept:MissedTarget", ...
        "Seed %u missed the moving endpoint by %.3f deg.", ...
        uint32(problem.seed), diagnostics.catchError_deg);
end
if diagnostics.cellTransferCount < 2
    error("exampleRandomBlinkingChessboardIntercept:NoBoardTraversal", ...
        "Seed %u did not require multiple cell transfers.", ...
        uint32(problem.seed));
end

viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 260, ...
    "MaximumDisplayedSlices", 20, ...
    "PauseSeconds", 0.015, ...
    "ObstacleFaceAlpha", 0.035, ...
    "MovingTarget", problem.target));
view = animateAzElAvoidancePlan( ...
    problem.azElData, plan, viewOptions);
result = problem;
result.plan = plan;
result.diagnostics = diagnostics;
result.view = view;
fprintf([ ...
    'Blinking chessboard seed %u: catch at %.1f s, ' ...
    '%d transfers, %d attempts, %.2f s search, %.3f deg error.\n'], ...
    uint32(problem.seed), diagnostics.interceptTime_s, ...
    diagnostics.cellTransferCount, diagnostics.attemptCount, ...
    diagnostics.searchElapsed_s, diagnostics.catchError_deg);
end
