function plan = examplePlanAzElAvoidance(azElData)
%EXAMPLEPLANAZELAVOIDANCE Run the standalone planner from azElData.

startState = struct( ...
    "time_s", 2700, ...
    "position_deg", [-30, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);

stopState = struct( ...
    "time_s", 3000, ...
    "position_deg", [80, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);

limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-90, 90], ...
    "maxVelocity_deg_s", [1, 1], ...
    "maxAcceleration_deg_s2", [3, 3]);

options = struct( ...
    "SampleTime_s", 0.1, ...
    "GridStep_deg", 0.1, ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", true);

plan = planAzElAvoidance( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("examplePlanAzElAvoidance:NoPath", "%s", plan.message);
end
plotAzElAvoidancePlan(azElData, plan);
end
