function [plan, handles] = ...
        example_simple_azEl_time_kinodynamic_birrt(showPlot)
%% Section 0: Header & Readme
% SYNTAX
%   plan = example_simple_azEl_time_kinodynamic_birrt()
%   plan = example_simple_azEl_time_kinodynamic_birrt(showPlot)
%   [plan, handles] = ...
%       example_simple_azEl_time_kinodynamic_birrt(showPlot)
%**************************************************************************
% PURPOSE
%   - Build a compact moving-obstacle scenario and run the first-principles
%     simple kinodynamic bidirectional RRT planner.
%   - Show the two time-directed trees and reconstructed trajectory.
%**************************************************************************
% INPUTS
%   - showPlot (logical scalar)
%       True creates the three-dimensional tree visualization.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Result from planSimpleAzElTimeKinodynamicBiRRT.
%   - handles (scalar struct or empty)
%       Plot handles when showPlot is true.
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.
if nargin < 1
    showPlot = true;
end
validateattributes(showPlot, {'logical', 'numeric'}, {'scalar'});
showPlot = logical(showPlot);

%% Section 1: Create Time-Varying Azimuth/Elevation Obstacles
time_s = (0:5).';
azimuthBoundaryByTime_deg = cell(numel(time_s), 1);
elevationBoundaryByTime_deg = cell(numel(time_s), 1);
for timeIndex = 1:numel(time_s)
    % This small block translates across the field above the nominal path.
    % It exercises the moving-polygon query without turning the introductory
    % example into an obstacle-course tuning exercise.
    obstacleCenterAzimuth_deg = -3 + 1.2 * time_s(timeIndex);
    azimuthBoundaryByTime_deg{timeIndex} = ...
        obstacleCenterAzimuth_deg + [-0.6; 0.6; 0.6; -0.6; -0.6];
    elevationBoundaryByTime_deg{timeIndex} = [3; 3; 5; 5; 3];
end
azElData = makeAzElObstacleData( ...
    "Translating block", time_s, azimuthBoundaryByTime_deg, ...
    elevationBoundaryByTime_deg);

%% Section 2: Define Boundary States, Limits, And Planner Options
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
destinationState = struct( ...
    "time_s", 5, ...
    "position_deg", [3, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-10, 10], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [2, 2], ...
    "maxJerk_deg_s3", [1, 1]);
options = struct( ...
    "TimeStep_s", 1, ...
    "CollisionCheckStep_s", 0.1, ...
    "DestinationSampleProbability", 0.3, ...
    "JerkCommands_deg_s3", [-1, 0; 0, 0; 1, 0], ...
    "ConnectionPositionTolerance_deg", [0.5, 0.5], ...
    "ConnectionVelocityTolerance_deg_s", [0.5, 0.5], ...
    "ConnectionAccelerationTolerance_deg_s2", [0.5, 0.5], ...
    "MaximumIterations", 500, ...
    "MaximumTreeNodes", 500, ...
    "RandomSeed", 2);

%% Section 3: Plan And Verify The Forward-Time Trajectory
plan = planSimpleAzElTimeKinodynamicBiRRT( ...
    azElData, initialState, destinationState, limits, options);
if ~plan.success
    error("exampleSimpleAzElTimeKinodynamicBiRRT:NoPath", ...
        "Planner failed: %s", plan.message);
end
if ~plan.forwardDynamicsValidated || ~plan.exactCollisionValidated
    error("exampleSimpleAzElTimeKinodynamicBiRRT:InvalidPath", ...
        "The returned trajectory did not pass final forward validation.");
end

%% Section 4: Plot Both Trees And The Final Trajectory
handles = [];
if showPlot
    handles = plotSimpleAzElTimeKinodynamicBiRRT(azElData, plan);
end
fprintf("Simple bidirectional RRT: %d iterations, %d nodes, " + ...
    "%.3f deg path cost.\n", plan.iterationCount, ...
    plan.generatedNodeCount, plan.totalCost);
end
