function problem = makeRandomAzElPlannerScenario(seed, familyName)
%MAKERANDOMAZELPLANNERSCENARIO Generate one reproducible fixed-goal case.
%
% problem = makeRandomAzElPlannerScenario(seed, familyName)
%
% Supported families are wall, slalom, trap, movingGates, and
% rotatingRods. Geometry is never regenerated after a planner result, so a
% reported failure remains part of the validation population.

if nargin < 1 || isempty(seed)
    previousRandomState = rng;
    rng("shuffle");
    seed = randi([1, intmax("int32")]);
    rng(previousRandomState);
end
validateattributes(seed, {'numeric'}, ...
    {'scalar', 'integer', 'positive', '<=', intmax("int32")});
randomStream = RandStream("mt19937ar", "Seed", double(seed));
supportedFamilies = [ ...
    "wall", "slalom", "trap", "movingGates", "rotatingRods"];
if nargin < 2 || isempty(familyName)
    familyIndex = randi(randomStream, numel(supportedFamilies));
    familyName = supportedFamilies(familyIndex);
else
    familyName = string(familyName);
end
if ~isscalar(familyName) || ~any(familyName == supportedFamilies)
    error("makeRandomAzElPlannerScenario:InvalidFamily", ...
        "familyName must be one of: %s.", ...
        strjoin(supportedFamilies, ", "));
end

%% Static wall with a randomly placed passage
if familyName == "wall"
    missionTime_s = (0:0.5:30).';
    limits = struct( ...
        "azimuth_deg", [-12 12], ...
        "elevation_deg", [-10 10], ...
        "maxVelocity_deg_s", [4 4], ...
        "maxAcceleration_deg_s2", [4 4]);
    wallCenter_deg = -0.8 + 1.6 * rand(randomStream);
    wallHalfWidth_deg = 2.2 + 1.0 * rand(randomStream);
    passageWidth_deg = 0.8 + 4.2 * rand(randomStream);
    maximumCenterMagnitude_deg = 7 - passageWidth_deg / 2;
    passageCenter_deg = maximumCenterMagnitude_deg * ...
        (2 * rand(randomStream) - 1);
    passageBottom_deg = passageCenter_deg - passageWidth_deg / 2;
    passageTop_deg = passageCenter_deg + passageWidth_deg / 2;
    wallLeft_deg = wallCenter_deg - wallHalfWidth_deg;
    wallRight_deg = wallCenter_deg + wallHalfWidth_deg;
    regions = { ...
        [wallLeft_deg -10; wallRight_deg -10; ...
        wallRight_deg passageBottom_deg; ...
        wallLeft_deg passageBottom_deg; wallLeft_deg -10], ...
        [wallLeft_deg passageTop_deg; ...
        wallRight_deg passageTop_deg; wallRight_deg 10; ...
        wallLeft_deg 10; wallLeft_deg passageTop_deg]};
    [obstacleAzimuth_deg, obstacleElevation_deg] = packRegions(regions);
    azElData = makeAzElObstacleData( ...
        "Random wall", missionTime_s, ...
        repmat({obstacleAzimuth_deg}, numel(missionTime_s), 1), ...
        repmat({obstacleElevation_deg}, numel(missionTime_s), 1));
    initialState = boundaryState(0, ...
        [-10, -1 + 2 * rand(randomStream)]);
    goalState = boundaryState(30, ...
        [10, -1 + 2 * rand(randomStream)]);
    referenceOptions = struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 0.25, ...
        "GridStepSchedule_deg", [2 1 0.5 0.25], ...
        "SafetyMargin_deg", 0.1, ...
        "MaxExpansions", 600000, ...
        "MaxSearchTime_s", 30, ...
        "PrintFailureSuggestions", false);

%% Alternating static barriers with randomized widths and pass sides
elseif familyName == "slalom"
    missionTime_s = (0:0.5:55).';
    limits = struct( ...
        "azimuth_deg", [-18 18], ...
        "elevation_deg", [-8 8], ...
        "maxVelocity_deg_s", [3 3], ...
        "maxAcceleration_deg_s2", [3 3]);
    barrierCount = randi(randomStream, [2 5]);
    barrierCenters_deg = linspace(-10, 10, barrierCount);
    barrierCenters_deg = barrierCenters_deg + ...
        0.5 * (2 * rand(randomStream, 1, barrierCount) - 1);
    firstPassesAbove = rand(randomStream) >= 0.5;
    obstacles = cell(barrierCount, 1);
    for barrierIndex = 1:barrierCount
        barrierHalfWidth_deg = 0.35 + ...
            0.25 * rand(randomStream);
        passageEdgeMagnitude_deg = 1.0 + ...
            1.4 * rand(randomStream);
        passesAbove = xor(mod(barrierIndex, 2) == 0, ...
            firstPassesAbove);
        barrierLeft_deg = barrierCenters_deg(barrierIndex) - ...
            barrierHalfWidth_deg;
        barrierRight_deg = barrierCenters_deg(barrierIndex) + ...
            barrierHalfWidth_deg;
        if passesAbove
            barrierElevation_deg = [ ...
                -8; -8; passageEdgeMagnitude_deg; ...
                passageEdgeMagnitude_deg; -8];
        else
            barrierElevation_deg = [ ...
                -passageEdgeMagnitude_deg; ...
                -passageEdgeMagnitude_deg; 8; 8; ...
                -passageEdgeMagnitude_deg];
        end
        barrierAzimuth_deg = [ ...
            barrierLeft_deg; barrierRight_deg; barrierRight_deg; ...
            barrierLeft_deg; barrierLeft_deg];
        obstacles{barrierIndex} = makeAzElObstacleData( ...
            "Random slalom " + barrierIndex, missionTime_s, ...
            repmat({barrierAzimuth_deg}, numel(missionTime_s), 1), ...
            repmat({barrierElevation_deg}, numel(missionTime_s), 1));
    end
    azElData = combineAzElObstacles(obstacles);
    initialState = boundaryState(0, [-16 0]);
    goalState = boundaryState(55, [16 0]);
    referenceOptions = struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 0.25, ...
        "GridStepSchedule_deg", [1 0.5 0.25], ...
        "SafetyMargin_deg", 0.15, ...
        "MaxExpansions", 800000, ...
        "MaxSearchTime_s", 35, ...
        "PrintFailureSuggestions", false);

%% Static U-trap that requires an initial move away from the goal
elseif familyName == "trap"
    missionTime_s = (0:0.5:60).';
    limits = struct( ...
        "azimuth_deg", [-11 18], ...
        "elevation_deg", [-10 10], ...
        "maxVelocity_deg_s", [3 3], ...
        "maxAcceleration_deg_s2", [3 3]);
    trapLeft_deg = -6.5 + 1.5 * rand(randomStream);
    trapRight_deg = 3 + 2 * rand(randomStream);
    trapBottom_deg = -6 + 1.5 * rand(randomStream);
    trapTop_deg = 4.5 + 1.5 * rand(randomStream);
    wallThickness_deg = 0.6 + 0.5 * rand(randomStream);
    regions = { ...
        [trapRight_deg trapBottom_deg; ...
        trapRight_deg + wallThickness_deg trapBottom_deg; ...
        trapRight_deg + wallThickness_deg trapTop_deg; ...
        trapRight_deg trapTop_deg; trapRight_deg trapBottom_deg], ...
        [trapLeft_deg trapTop_deg; ...
        trapRight_deg + wallThickness_deg trapTop_deg; ...
        trapRight_deg + wallThickness_deg ...
            trapTop_deg + wallThickness_deg; ...
        trapLeft_deg trapTop_deg + wallThickness_deg; ...
        trapLeft_deg trapTop_deg], ...
        [trapLeft_deg trapBottom_deg - wallThickness_deg; ...
        trapRight_deg + wallThickness_deg ...
            trapBottom_deg - wallThickness_deg; ...
        trapRight_deg + wallThickness_deg trapBottom_deg; ...
        trapLeft_deg trapBottom_deg; ...
        trapLeft_deg trapBottom_deg - wallThickness_deg]};
    [obstacleAzimuth_deg, obstacleElevation_deg] = packRegions(regions);
    azElData = makeAzElObstacleData( ...
        "Random U-trap", missionTime_s, ...
        repmat({obstacleAzimuth_deg}, numel(missionTime_s), 1), ...
        repmat({obstacleElevation_deg}, numel(missionTime_s), 1));
    initialState = boundaryState(0, ...
        [0, -0.5 + rand(randomStream)]);
    goalState = boundaryState(60, ...
        [14, -0.5 + rand(randomStream)]);
    referenceOptions = struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 0.25, ...
        "GridStepSchedule_deg", [1 0.5 0.25], ...
        "SafetyMargin_deg", 0.15, ...
        "MaxExpansions", 800000, ...
        "MaxSearchTime_s", 40, ...
        "PrintFailureSuggestions", false);

%% Moving gates whose safe side changes independently
elseif familyName == "movingGates"
    missionTime_s = (0:0.5:45).';
    limits = struct( ...
        "azimuth_deg", [-12 12], ...
        "elevation_deg", [-8 8], ...
        "maxVelocity_deg_s", [3 3], ...
        "maxAcceleration_deg_s2", [3 3]);
    gateCount = randi(randomStream, [2 4]);
    gateCenters_deg = linspace(-6, 6, gateCount);
    obstacles = cell(gateCount, 1);
    for gateIndex = 1:gateCount
        gateHalfWidth_deg = 0.35 + 0.2 * rand(randomStream);
        openElevationMagnitude_deg = 2.6 + ...
            0.8 * rand(randomStream);
        openHalfHeight_deg = 1.2 + 0.4 * rand(randomStream);
        switchPeriod_s = 8 + 6 * rand(randomStream);
        switchPhase_rad = 2 * pi * rand(randomStream);
        azimuthByTime = cell(numel(missionTime_s), 1);
        elevationByTime = cell(numel(missionTime_s), 1);
        for timeIndex = 1:numel(missionTime_s)
            phase_rad = 2 * pi * missionTime_s(timeIndex) / ...
                switchPeriod_s + switchPhase_rad;
            opensAbove = sin(phase_rad) >= 0;
            if opensAbove
                obstacleTop_deg = openElevationMagnitude_deg - ...
                    openHalfHeight_deg;
                gateElevation_deg = [ ...
                    -8; -8; obstacleTop_deg; obstacleTop_deg; -8];
            else
                obstacleBottom_deg = -openElevationMagnitude_deg + ...
                    openHalfHeight_deg;
                gateElevation_deg = [ ...
                    obstacleBottom_deg; obstacleBottom_deg; ...
                    8; 8; obstacleBottom_deg];
            end
            gateLeft_deg = gateCenters_deg(gateIndex) - ...
                gateHalfWidth_deg;
            gateRight_deg = gateCenters_deg(gateIndex) + ...
                gateHalfWidth_deg;
            azimuthByTime{timeIndex} = [ ...
                gateLeft_deg; gateRight_deg; gateRight_deg; ...
                gateLeft_deg; gateLeft_deg];
            elevationByTime{timeIndex} = gateElevation_deg;
        end
        obstacles{gateIndex} = makeAzElObstacleData( ...
            "Random moving gate " + gateIndex, ...
            missionTime_s, azimuthByTime, elevationByTime);
    end
    azElData = combineAzElObstacles(obstacles);
    initialState = boundaryState(0, [-10 0]);
    goalState = boundaryState(45, [10 0]);
    referenceOptions = struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.1, ...
        "GridStep_deg", 0.5, ...
        "GridStepSchedule_deg", [1 0.5], ...
        "PrimitiveRadii_deg", [1 2 4], ...
        "DirectionStep_deg", 45, ...
        "CollisionCheckStep_s", 0.2, ...
        "MaximumSafeIntervalSamples", 101, ...
        "MaximumDepartureTrials", 12, ...
        "DepartureBatchSize", 4, ...
        "SafetyMargin_deg", 0.1, ...
        "MaxExpansions", 250000, ...
        "MaxSearchTime_s", 45, ...
        "PrintFailureSuggestions", false);

%% Independently rotating rods that alter both shape and occupancy
else
    missionTime_s = (0:0.5:60).';
    limits = struct( ...
        "azimuth_deg", [-12 12], ...
        "elevation_deg", [-8 8], ...
        "maxVelocity_deg_s", [2.5 2.5], ...
        "maxAcceleration_deg_s2", [2.5 2.5]);
    rodCount = randi(randomStream, [1 3]);
    rodCenters_deg = [ ...
        linspace(-5, 5, rodCount).', ...
        -1.5 + 3 * rand(randomStream, rodCount, 1)];
    obstacles = cell(rodCount, 1);
    for rodIndex = 1:rodCount
        rodHalfLength_deg = 2.5 + 1.5 * rand(randomStream);
        rodHalfWidth_deg = 0.3 + 0.25 * rand(randomStream);
        rodRate_deg_s = 3 + 6 * rand(randomStream);
        rodPhase_deg = 360 * rand(randomStream);
        localCorners_deg = [ ...
            -rodHalfLength_deg -rodHalfWidth_deg; ...
            rodHalfLength_deg -rodHalfWidth_deg; ...
            rodHalfLength_deg rodHalfWidth_deg; ...
            -rodHalfLength_deg rodHalfWidth_deg; ...
            -rodHalfLength_deg -rodHalfWidth_deg];
        azimuthByTime = cell(numel(missionTime_s), 1);
        elevationByTime = cell(numel(missionTime_s), 1);
        for timeIndex = 1:numel(missionTime_s)
            rodAngle_deg = rodPhase_deg + ...
                rodRate_deg_s * missionTime_s(timeIndex);
            cosine = cosd(rodAngle_deg);
            sine = sind(rodAngle_deg);
            rotation = [cosine -sine; sine cosine];
            worldCorners_deg = localCorners_deg * rotation.' + ...
                rodCenters_deg(rodIndex, :);
            azimuthByTime{timeIndex} = worldCorners_deg(:, 1);
            elevationByTime{timeIndex} = worldCorners_deg(:, 2);
        end
        obstacles{rodIndex} = makeAzElObstacleData( ...
            "Random rotating rod " + rodIndex, ...
            missionTime_s, azimuthByTime, elevationByTime);
    end
    azElData = combineAzElObstacles(obstacles);
    initialState = boundaryState(0, ...
        [-10, -5 + 2 * rand(randomStream)]);
    goalState = boundaryState(60, ...
        [10, 3 + 2 * rand(randomStream)]);
    referenceOptions = struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.1, ...
        "GridStep_deg", 1, ...
        "GridStepSchedule_deg", [2 1], ...
        "PrimitiveRadii_deg", [1 2 4], ...
        "DirectionStep_deg", 45, ...
        "CollisionCheckStep_s", 0.2, ...
        "MaximumSafeIntervalSamples", 121, ...
        "MaximumDepartureTrials", 12, ...
        "DepartureBatchSize", 4, ...
        "SafetyMargin_deg", 0.1, ...
        "MaxExpansions", 300000, ...
        "MaxSearchTime_s", 60, ...
        "PrintFailureSuggestions", false);
end

agentOptions = struct( ...
    "SafetyMargin_deg", referenceOptions.SafetyMargin_deg, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "AgentMaxSearchTime_s", ...
        max(60, 2 * referenceOptions.MaxSearchTime_s), ...
    "AgentFallbackReserve_s", referenceOptions.MaxSearchTime_s, ...
    "AgentFallback", true, ...
    "AgentPrintDiagnostics", false, ...
    "PrintFailureSuggestions", false);
problem = struct( ...
    "Seed", double(seed), ...
    "Family", familyName, ...
    "azElData", azElData, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits, ...
    "referenceOptions", referenceOptions, ...
    "agentOptions", agentOptions);
end

function state = boundaryState(time_s, position_deg)
% Every randomized family currently uses rest-to-rest boundary conditions.
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function [azimuth_deg, elevation_deg] = packRegions(regions)
% Multiple families need NaN-separated polygon rings; one implementation
% avoids subtle separator/count differences between training cases.
combinedRowCount = numel(regions) - 1;
for regionIndex = 1:numel(regions)
    combinedRowCount = combinedRowCount + size(regions{regionIndex}, 1);
end
combined_deg = nan(combinedRowCount, 2);
nextRow = 1;
for regionIndex = 1:numel(regions)
    regionRowCount = size(regions{regionIndex}, 1);
    regionRows = nextRow:nextRow + regionRowCount - 1;
    combined_deg(regionRows, :) = regions{regionIndex};
    nextRow = regionRows(end) + 2;
end
azimuth_deg = combined_deg(:, 1);
elevation_deg = combined_deg(:, 2);
end
