function problem = makeWorldsHardestWindmillGauntlet()
%MAKEWORLDSHARDESTWINDMILLGAUNTLET Create a level-6-inspired S corridor.
%
% Eight dotted four-blade windmills rotate at one common angular rate.
% There are no coin or collection constraints. The boresight must traverse
% the upper corridor, turn through the right connector, and return through
% the lower corridor while timing the moving gaps.

time_s = (0:1:100).';
angularRate_deg_s = 12;
topCenters = [-12 4; -4 4; 4 4; 12 4];
bottomCenters = [12 -4; 4 -4; -4 -4; -12 -4];
centers_deg = [topCenters; bottomCenters];
phase_deg = [0 22.5 45 67.5 67.5 45 22.5 0];

[wallAzimuth, wallElevation] = corridorWalls();
walls = makeAzElObstacleData( ...
    "Level 6 corridor walls", time_s, ...
    wallAzimuth, wallElevation);

windmills = cell(1, size(centers_deg, 1));
for windmill = 1:size(centers_deg, 1)
    azimuth = cell(numel(time_s), 1);
    elevation = cell(numel(time_s), 1);
    for sample = 1:numel(time_s)
        angle = phase_deg(windmill) + ...
            angularRate_deg_s * time_s(sample);
        [azimuth{sample}, elevation{sample}] = windmillBoundary( ...
            centers_deg(windmill, :), angle);
    end
    windmills{windmill} = makeAzElObstacleData( ...
        sprintf('Windmill %d', windmill), ...
        time_s, azimuth, elevation);
end
azElData = [{walls}, windmills];

startState = boundaryState(0, [-16 4]);
stopState = boundaryState(100, [-16 -4]);
limits = struct( ...
    "azimuth_deg", [-18 18], ...
    "elevation_deg", [-8 8], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.2, ...
    "GuideGridStep_deg", 1, ...
    "GuidePrimitiveRadii_deg", [2 4 8], ...
    "GuideHeuristicWeight", 8, ...
    "GuideCollisionCheckStep_s", 0.4, ...
    "MaximumSafeIntervalSamples", 51, ...
    "MaximumDepartureTrials", 4, ...
    "DepartureBatchSize", 2, ...
    "GuideMaxExpansions", 250000, ...
    "GuideMaxWallTime_s", 55, ...
    "SafetyMargin_deg", 0.15, ...
    "MaximumVerticesPerRegion", 500, ...
    "EnableARARefinement", false, ...
    "FallbackToGlobalSearch", false, ...
    "MaxSearchTime_s", 60);
geometry = struct( ...
    "centers_deg", centers_deg, ...
    "angularRate_deg_s", ...
    repmat(angularRate_deg_s, 1, size(centers_deg, 1)), ...
    "phase_deg", phase_deg, ...
    "bladeCount", 4, ...
    "bladeRadii_deg", [0.75 1.5 2.25], ...
    "dotRadius_deg", 0.34, ...
    "rightConnectorAzimuth_deg", 14);
problem = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "geometry", geometry);
end

function [azimuth, elevation] = corridorWalls()
regions = { ...
    rectangleVertices([-18 18], [7 8]), ...
    rectangleVertices([-18 18], [-8 -7]), ...
    rectangleVertices([-18 -17], [-7 7]), ...
    rectangleVertices([17 18], [-7 7]), ...
    rectangleVertices([-17 14], [-1 1])};
[azimuth, elevation] = joinRegions(regions);
end

function [azimuth, elevation] = windmillBoundary(center, angle_deg)
bladeCount = 4;
bladeRadii = [0.75 1.5 2.25];
dotRadius = 0.34;
diskVertexCount = 10;
regions = cell(1, 1 + bladeCount * numel(bladeRadii));
regions{1} = diskVertices(center, dotRadius, diskVertexCount);
write = 1;
for blade = 0:bladeCount - 1
    bladeAngle = deg2rad(angle_deg + blade * 360 / bladeCount);
    direction = [cos(bladeAngle), sin(bladeAngle)];
    for radius = bladeRadii
        write = write + 1;
        regions{write} = diskVertices( ...
            center + radius * direction, ...
            dotRadius, diskVertexCount);
    end
end
[azimuth, elevation] = joinRegions(regions);
end

function vertices = diskVertices(center, radius, count)
angle = linspace(0, 2 * pi, count + 1).';
vertices = center + radius * [cos(angle), sin(angle)];
end

function vertices = rectangleVertices(xLimits, yLimits)
vertices = [ ...
    xLimits(1), yLimits(1); ...
    xLimits(2), yLimits(1); ...
    xLimits(2), yLimits(2); ...
    xLimits(1), yLimits(2); ...
    xLimits(1), yLimits(1)];
end

function [azimuth, elevation] = joinRegions(regions)
rowCount = sum(cellfun(@(item) size(item, 1), regions)) + ...
    numel(regions) - 1;
combined = nan(rowCount, 2);
cursor = 1;
for region = 1:numel(regions)
    count = size(regions{region}, 1);
    output = cursor:cursor + count - 1;
    combined(output, :) = regions{region};
    cursor = output(end) + 2;
end
azimuth = combined(:, 1);
elevation = combined(:, 2);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
