function compact = planOrbitUiSlew(requestFile, resultFile)
%PLANORBITUISLEW File bridge for Orbit Console's geographic keep-out export.
% Frame: nadir boresight, projected inertial velocity up. Angles are degrees.
% This plans boresight clearance, not clearance of the entire sensor cone.
% Uses the pinned AzElObsAvoid bmtp-cleanup-codex copy and validator.
repositoryRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
plannerRoot = fullfile(repositoryRoot, 'vendor', 'AzElObsAvoid');
addpath(plannerRoot, fullfile(plannerRoot, 'trajectory'), '-begin');
request = jsondecode(fileread(requestFile));
assert(request.version == 1, "Unsupported Orbit Console slew format.");
obstacles = request.obstacles;
azElData = cell(numel(obstacles), 1);
protectedObstacles = cell(numel(obstacles), 1);
for k = 1:numel(obstacles)
    obstacle = obstacles(k);
    az = cell(numel(obstacle.time_s), 1); el = az;
    for j = 1:numel(az)
        az{j} = obstacle.slices(j).az_deg(:);
        el{j} = obstacle.slices(j).el_deg(:);
    end
    azElData{k} = makeAzElObstacleData(string(obstacle.targetName), ...
        obstacle.time_s(:), az, el);
    protectedObstacles{k} = obstacleAvoidance.obstacles.createObstacle( ...
        string(obstacle.targetName), obstacle.time_s(:), az, el, request.options.SafetyMargin_deg);
end
% The upstream planner is coordinate-neutral. Translate the Orbit Console's
% explicit azimuth/elevation units only at this file boundary.
initialState = struct('time_s', request.initialState.time_s, ...
    'position_units', request.initialState.position_deg, ...
    'velocity_units_s', request.initialState.velocity_deg_s, ...
    'acceleration_units_s2', request.initialState.acceleration_deg_s2);
goalState = struct('time_s', request.goalState.time_s, ...
    'position_units', request.goalState.position_deg, ...
    'velocity_units_s', request.goalState.velocity_deg_s, ...
    'acceleration_units_s2', request.goalState.acceleration_deg_s2);
limits = struct('maxVelocity_units_s', request.limits.maxVelocity_deg_s, ...
    'maxAcceleration_units_s2', request.limits.maxAcceleration_deg_s2, ...
    'maxJerk_units_s3', [4 4], ...
    'xInterval_units', request.limits.azimuth_deg, ...
    'yInterval_units', request.limits.elevation_deg);
options = struct('GoalTimeMode', 'fixedArrival', 'SampleTime_s', 0.05, ...
    'WrapX', false, 'WrapY', false);
outputFolder = fileparts(resultFile);
save(fullfile(outputFolder, "request.mat"), "azElData", "protectedObstacles", "initialState", "goalState", "limits", "options", "request");
plan = obstacleAvoidance.planTrajectory(protectedObstacles, initialState, goalState, limits, options);
validation = obstacleAvoidance.validateTrajectory(plan);
compact = struct('success', plan.Success && validation.Passed, ...
    'message', plan.Message, 'method', 'AzElObsAvoid / BMTP', ...
    'plannerRevision', 'a28ae6425bf4e6e5ff6bde20050b1b3e51f35922', ...
    'exactCollisionValidated', validation.Passed && validation.CollisionFree && validation.CollisionResolved, ...
    'terminationReason', plan.TerminationReason, 'validation', validation, ...
    'angularPathLength_deg', sum(vecnorm(diff(plan.position_units), 2, 2)), ...
    'searchElapsed_s', plan.ElapsedPlanningTime_s);
if ~validation.Passed, compact.message = plan.Message + " " + validation.Message; end
fieldMap = ["time_s", "time_s"; ...
    "position_units", "position_deg"; ...
    "velocity_units_s", "velocity_deg_s"; ...
    "acceleration_units_s2", "acceleration_deg_s2"; ...
    "jerk_units_s3", "jerk_deg_s3"];
for fieldIndex = 1:size(fieldMap, 1)
    if isfield(plan, fieldMap(fieldIndex, 1))
        compact.(fieldMap(fieldIndex, 2)) = plan.(fieldMap(fieldIndex, 1));
    end
end
fid = fopen(resultFile, 'w');
assert(fid >= 0, "Cannot open planner result file.");
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, jsonencode(compact), 'char');
fprintf('Orbit Console slew: %s | %s\n', string(plan.TerminationReason), string(validation.Message));
end
