function plan = planAzElMovingTargetIntercept( ...
        azElData, initialState, target, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   options = planAzElMovingTargetIntercept( ...
%       initialState, target, limits, "defaults")
%   plan = planAzElMovingTargetIntercept( ...
%       azElData, initialState, target, limits)
%   plan = planAzElMovingTargetIntercept( ...
%       azElData, initialState, target, limits, options)
%**************************************************************************
% PURPOSE
%   - Preserve the moving-target public signature while translating one
%     request into the unified planAzElTrajectory scenario contract.
%**************************************************************************
% INPUTS
%   - azElData (canonical obstacle data or packed obstacle field)
%       Geometry passed unchanged to the authoritative planner.
%   - initialState (scalar struct)
%       Initial time, position, velocity, and acceleration.
%   - target (scalar struct)
%       Sample times and positions, with optional derivative samples.
%   - limits (scalar struct)
%       Angular, velocity, acceleration, and optional jerk limits.
%   - options (scalar struct, optional)
%       Legacy interception, tracking, and planner settings.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Unified result plus documented moving-target compatibility fields.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s powers.

%% Section 1: Resolve Defaults & Validate Compatibility Inputs
isDefaultsRequest = nargin == 4 && ...
    (ischar(limits) || isstring(limits)) && ...
    isscalar(string(limits)) && ...
    strcmpi(strtrim(string(limits)), "defaults");
if isDefaultsRequest
    requestedInitialState = azElData;
    requestedTarget = initialState;
    requestedLimits = target;
    baseDefaults = planAzElDijkstra(requestedLimits, "defaults");
    plan = compatibilityDefaults( ...
        requestedInitialState, requestedTarget, baseDefaults);
    return;
end
if nargin < 5 || isempty(options)
    options = struct();
end
initialState = normalizeState(initialState, "initialState");
limits = normalizeLimits(limits);
target = normalizeTarget(target, limits, initialState.position_deg(1));
baseDefaults = planAzElDijkstra(limits, "defaults");
resolvedOptions = resolveOptions(options, ...
    compatibilityDefaults(initialState, target, baseDefaults), ...
    initialState, target);

%% Section 2: Translate One Neutral Moving-Goal Scenario
if resolvedOptions.ContinueTrackingAfterIntercept
    requestKind = "tracking";
else
    requestKind = "intercept";
end
collisionCheckStep_s = resolvedOptions.CollisionCheckStep_s;
if isempty(collisionCheckStep_s)
    collisionCheckStep_s = resolvedOptions.ValidationStep_s;
end
if isempty(collisionCheckStep_s)
    collisionCheckStep_s = min(0.2, resolvedOptions.SampleTime_s);
end
scenarioOptions = struct( ...
    "sampleTime_s", resolvedOptions.SampleTime_s, ...
    "collisionCheckStep_s", collisionCheckStep_s, ...
    "safetyMargin_deg", resolvedOptions.SafetyMargin_deg, ...
    "allowAzimuthWrap", resolvedOptions.AllowAzimuthWrap, ...
    "objective", "minimumTime", ...
    "earliestInterceptTime_s", ...
        resolvedOptions.EarliestInterceptTime_s, ...
    "latestInterceptTime_s", ...
        resolvedOptions.LatestInterceptTime_s, ...
    "interceptTimeStep_s", resolvedOptions.InterceptTimeStep_s, ...
    "maximumInterceptCandidates", ...
        resolvedOptions.MaximumInterceptAttempts, ...
    "matchTargetVelocity", resolvedOptions.MatchTargetVelocity, ...
    "matchTargetAcceleration", resolvedOptions.MatchTargetAcceleration, ...
    "trackingEndTime_s", resolvedOptions.TrackingEndTime_s, ...
    "trackingSampleTime_s", resolvedOptions.TrackingSampleTime_s);
maximumWallTime_s = min( ...
    resolvedOptions.MaxSearchTime_s, ...
    resolvedOptions.PerAttemptMaxSearchTime_s);
scenario = struct( ...
    "requestKind", requestKind, ...
    "azElData", azElData, ...
    "initialState", initialState, ...
    "goalState", [], ...
    "target", target, ...
    "limits", limits, ...
    "options", scenarioOptions, ...
    "resourceBudget", struct( ...
        "maximumWallTime_s", maximumWallTime_s, ...
        "maximumExpansions", resolvedOptions.MaxExpansions));
coreOverrides = coreOptionOverrides( ...
    resolvedOptions, collisionCheckStep_s);

%% Section 3: Call The Authoritative Planner Once
plan = planAzElTrajectory(scenario, coreOverrides);

%% Section 4: Add Compatibility Data Without Search Logic
if isempty(azElData)
    obstacleField = emptyObstacleField();
elseif isPackedObstacleField(azElData)
    obstacleField = azElData;
else
    obstacleField = buildAzElTimeObstacleField(azElData, struct( ...
        "MaximumVerticesPerRegion", ...
        resolvedOptions.MaximumVerticesPerRegion));
end
plan = addCompatibilityFields( ...
    plan, obstacleField, initialState, target, limits, resolvedOptions);
end

%% Section 5: Local Functions
function options = compatibilityDefaults(initialState, target, baseDefaults)
if ~isstruct(initialState) || ~isscalar(initialState) || ...
        ~isfield(initialState, "time_s") || ...
        ~isstruct(target) || ~isscalar(target) || ...
        ~isfield(target, "time_s") || isempty(target.time_s)
    error("planAzElMovingTargetIntercept:InvalidDefaultsArguments", ...
        "Defaults require initialState.time_s and target.time_s.");
end
targetTime_s = double(target.time_s(:));
options = baseDefaults;
movingDefaults = struct( ...
    "EarliestInterceptTime_s", ...
        max(double(initialState.time_s), targetTime_s(1)), ...
    "LatestInterceptTime_s", targetTime_s(end), ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 12, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "CatchTolerance_deg", 0.35, ...
    "CatchVelocityTolerance_deg_s", 0.05, ...
    "CatchAccelerationTolerance_deg_s2", 0.1, ...
    "MatchTargetVelocity", false, ...
    "MatchTargetAcceleration", false, ...
    "ContinueTrackingAfterIntercept", false, ...
    "TrackingEndTime_s", targetTime_s(end), ...
    "TrackingSampleTime_s", baseDefaults.SampleTime_s);
fieldNames = fieldnames(movingDefaults);
for fieldIndex = 1:numel(fieldNames)
    fieldName = fieldNames{fieldIndex};
    options.(fieldName) = movingDefaults.(fieldName);
end
end

function options = resolveOptions(options, defaults, initialState, target)
if ~isstruct(options) || ~isscalar(options)
    error("planAzElMovingTargetIntercept:InvalidOptions", ...
        "options must be a scalar struct.");
end
unknownFields = setdiff(fieldnames(options), fieldnames(defaults), "stable");
if ~isempty(unknownFields)
    warning("planAzElMovingTargetIntercept:UnknownOptions", ...
        "Ignoring unknown option fields: %s.", ...
        strjoin(string(unknownFields), ", "));
    options = rmfield(options, unknownFields);
end
defaultFields = fieldnames(defaults);
for fieldIndex = 1:numel(defaultFields)
    fieldName = defaultFields{fieldIndex};
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        options.(fieldName) = defaults.(fieldName);
    end
end
positiveFields = ["InterceptTimeStep_s" ...
    "PerAttemptMaxSearchTime_s" "CatchTolerance_deg" ...
    "CatchVelocityTolerance_deg_s" ...
    "CatchAccelerationTolerance_deg_s2" "TrackingSampleTime_s"];
for fieldName = positiveFields
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.MaximumInterceptAttempts, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
minimumInterceptTime_s = max(initialState.time_s, target.time_s(1));
validateattributes(options.EarliestInterceptTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', minimumInterceptTime_s});
validateattributes(options.LatestInterceptTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '<=', target.time_s(end)});
if options.LatestInterceptTime_s <= options.EarliestInterceptTime_s
    error("planAzElMovingTargetIntercept:InvalidInterceptWindow", ...
        "LatestInterceptTime_s must follow EarliestInterceptTime_s.");
end
validateattributes(options.TrackingEndTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '<=', target.time_s(end)});
logicalFields = ["MatchTargetVelocity" "MatchTargetAcceleration" ...
    "ContinueTrackingAfterIntercept" "PrintFailureSuggestions"];
for fieldName = logicalFields
    validateattributes(options.(fieldName), ...
        {'logical', 'numeric'}, {'scalar'});
    options.(fieldName) = logical(options.(fieldName));
end
if options.MatchTargetAcceleration && ~options.MatchTargetVelocity
    error("planAzElMovingTargetIntercept:AccelerationWithoutVelocity", ...
        "MatchTargetAcceleration requires MatchTargetVelocity.");
end
if options.ContinueTrackingAfterIntercept && ...
        ~options.MatchTargetVelocity
    error("planAzElMovingTargetIntercept:TrackingWithoutVelocityMatch", ...
        "Tracking requires MatchTargetVelocity.");
end
end

function target = normalizeTarget(target, limits, referenceAzimuth_deg)
requiredFields = ["time_s" "position_deg"];
if ~isstruct(target) || ~isscalar(target) || ...
        ~all(isfield(target, requiredFields))
    error("planAzElMovingTargetIntercept:InvalidTarget", ...
        "target requires time_s and position_deg.");
end
target.time_s = double(target.time_s(:));
target.position_deg = double(target.position_deg);
validateattributes(target.time_s, {'numeric'}, ...
    {'vector', 'real', 'finite', 'increasing'});
validateattributes(target.position_deg, {'numeric'}, ...
    {'2d', 'nrows', numel(target.time_s), 'ncols', 2, ...
    'real', 'finite'});
allowWrap = diff(limits.azimuth_deg) >= 360 - 1e-9;
if allowWrap
    target.position_deg(:, 1) = referenceAzimuth_deg + rad2deg(unwrap( ...
        deg2rad(target.position_deg(:, 1) - referenceAzimuth_deg)));
end
sampleCount = numel(target.time_s);
if isfield(target, "velocity_deg_s") && ...
        ~isempty(target.velocity_deg_s)
    target.velocity_deg_s = normalizeTargetSamples( ...
        target.velocity_deg_s, sampleCount, "velocity_deg_s");
else
    target.velocity_deg_s = sampledDerivative( ...
        target.position_deg, target.time_s);
end
if isfield(target, "acceleration_deg_s2") && ...
        ~isempty(target.acceleration_deg_s2)
    target.acceleration_deg_s2 = normalizeTargetSamples( ...
        target.acceleration_deg_s2, sampleCount, ...
        "acceleration_deg_s2");
else
    target.acceleration_deg_s2 = sampledDerivative( ...
        target.velocity_deg_s, target.time_s);
end
end

function samples = normalizeTargetSamples(samples, sampleCount, name)
validateattributes(samples, {'numeric'}, ...
    {'2d', 'nrows', sampleCount, 'ncols', 2, 'real', 'finite'}, ...
    mfilename, name);
samples = double(samples);
end

function derivative = sampledDerivative(values, time_s)
sampleCount = numel(time_s);
derivative = zeros(sampleCount, 2);
if sampleCount == 1
    return;
end
derivative(1, :) = (values(2, :) - values(1, :)) / ...
    (time_s(2) - time_s(1));
derivative(end, :) = (values(end, :) - values(end - 1, :)) / ...
    (time_s(end) - time_s(end - 1));
for sampleIndex = 2:sampleCount - 1
    derivative(sampleIndex, :) = ...
        (values(sampleIndex + 1, :) - values(sampleIndex - 1, :)) / ...
        (time_s(sampleIndex + 1) - time_s(sampleIndex - 1));
end
end

function state = normalizeState(input, name)
requiredFields = ["time_s" "position_deg" ...
    "velocity_deg_s" "acceleration_deg_s2"];
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(isfield(input, requiredFields))
    error("planAzElMovingTargetIntercept:InvalidState", ...
        "%s is missing a boundary-state field.", name);
end
state = struct( ...
    "time_s", double(input.time_s), ...
    "position_deg", reshape(double(input.position_deg), 1, 2), ...
    "velocity_deg_s", reshape(double(input.velocity_deg_s), 1, 2), ...
    "acceleration_deg_s2", ...
        reshape(double(input.acceleration_deg_s2), 1, 2));
if any(~isfinite([state.time_s state.position_deg ...
        state.velocity_deg_s state.acceleration_deg_s2]))
    error("planAzElMovingTargetIntercept:InvalidState", ...
        "%s must contain finite values.", name);
end
end

function limits = normalizeLimits(input)
requiredFields = ["azimuth_deg" "elevation_deg" ...
    "maxVelocity_deg_s" "maxAcceleration_deg_s2"];
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(isfield(input, requiredFields))
    error("planAzElMovingTargetIntercept:InvalidLimits", ...
        "limits is incomplete.");
end
limits = input;
for fieldName = requiredFields
    limits.(fieldName) = reshape(double(limits.(fieldName)), 1, 2);
end
if ~isfield(limits, "maxJerk_deg_s3") || ...
        isempty(limits.maxJerk_deg_s3)
    limits.maxJerk_deg_s3 = max( ...
        10, 20 * limits.maxAcceleration_deg_s2);
else
    limits.maxJerk_deg_s3 = reshape( ...
        double(limits.maxJerk_deg_s3), 1, 2);
end
end

function coreOptions = coreOptionOverrides(options, collisionStep_s)
maximumPrimitiveDistance_deg = NaN;
if ~isempty(options.PrimitiveRadii_deg)
    maximumPrimitiveDistance_deg = max(options.PrimitiveRadii_deg);
elseif ~isempty(options.PrimitiveRadiusMultipliers)
    maximumPrimitiveDistance_deg = options.GridStep_deg * ...
        max(options.PrimitiveRadiusMultipliers);
end
directionCount = max(8, round(360 / options.DirectionStep_deg));
coreOptions = struct( ...
    "GridStep_deg", options.GridStep_deg, ...
    "SampleTime_s", options.SampleTime_s, ...
    "CollisionCheckStep_s", collisionStep_s, ...
    "MaxJerk_deg_s3", options.MaxJerk_deg_s3, ...
    "MaxWallTime_s", min(options.MaxSearchTime_s, ...
        options.PerAttemptMaxSearchTime_s), ...
    "MaxExpandedStates", options.MaxExpansions, ...
    "MaxGeneratedStates", max(10000, 4 * options.MaxExpansions), ...
    "MaximumPrimitiveDistance_deg", maximumPrimitiveDistance_deg, ...
    "DirectionCount", directionCount, ...
    "HeuristicMode", options.HeuristicMode);
end

function plan = addCompatibilityFields( ...
        plan, obstacleField, initialState, target, limits, options)
plan.options = options;
plan.obstacleField = obstacleField;
plan.workspace = obstacleField; % deprecated compatibility alias
plan.startState = initialState;
plan.limits = limits;
plan.targetTrajectory = target;
plan.interceptSuccess = plan.success;
plan.interceptTime_s = NaN;
plan.interceptPosition_deg = [NaN NaN];
plan.targetPositionAtIntercept_deg = [NaN NaN];
plan.targetVelocityAtIntercept_deg_s = [NaN NaN];
plan.targetAccelerationAtIntercept_deg_s2 = [NaN NaN];
plan.catchError_deg = Inf;
plan.catchVelocityError_deg_s = Inf;
plan.catchAccelerationError_deg_s2 = Inf;
candidateTimes_s = interceptCandidateTimes(options);
plan.interceptCandidateCount = numel(candidateTimes_s);
plan.interceptAttempts = interceptAttemptRecords( ...
    candidateTimes_s, target, plan);
plan.interceptFilter = struct( ...
    "sampleCount", numel(candidateTimes_s), ...
    "insideLimitCount", numel(candidateTimes_s), ...
    "safeCount", numel(candidateTimes_s), ...
    "reachableCount", numel(candidateTimes_s), ...
    "eligibleCount", numel(candidateTimes_s));
plan.interceptSearchElapsed_s = plan.searchElapsed_s;
plan.trackingRequested = options.ContinueTrackingAfterIntercept;
plan.trackingSuccess = false;
plan.trackingTerminationReason = "notRequested";
plan.trackingTerminatedByObstacle = false;
plan.trackingTime_s = zeros(0, 1);
plan.trackingPosition_deg = zeros(0, 2);
plan.trackingVelocity_deg_s = zeros(0, 2);
plan.trackingAcceleration_deg_s2 = zeros(0, 2);
plan.trackingEndTime_s = NaN;
plan.commandEndState = struct();
plan.expandedNodeCount = plan.expandedStateCount;
plan.generatedNodeCount = plan.generatedStateCount;
plan.selectedGridStep_deg = plan.options.GridStep_deg;
plan.cost_s = Inf;
if ~plan.success
    plan.failureCategory = string(plan.failureAssessment.classification);
    plan.failureCause = string(plan.failureAssessment.reason);
    plan.failureSuggestions = strings(0, 1);
    plan.failureSummary = string(plan.message);
    return;
end

plan.interceptTime_s = plan.stopState.time_s;
targetState = interpolateTarget(target, plan.interceptTime_s);
plan.interceptPosition_deg = plan.stopState.position_deg;
plan.targetPositionAtIntercept_deg = targetState.position_deg;
plan.targetVelocityAtIntercept_deg_s = targetState.velocity_deg_s;
plan.targetAccelerationAtIntercept_deg_s2 = ...
    targetState.acceleration_deg_s2;
plan.catchError_deg = hypot( ...
    plan.interceptPosition_deg(1) - targetState.position_deg(1), ...
    plan.interceptPosition_deg(2) - targetState.position_deg(2));
plan.catchVelocityError_deg_s = hypot( ...
    plan.stopState.velocity_deg_s(1) - targetState.velocity_deg_s(1), ...
    plan.stopState.velocity_deg_s(2) - targetState.velocity_deg_s(2));
plan.catchAccelerationError_deg_s2 = hypot( ...
    plan.stopState.acceleration_deg_s2(1) - ...
        targetState.acceleration_deg_s2(1), ...
    plan.stopState.acceleration_deg_s2(2) - ...
        targetState.acceleration_deg_s2(2));
trackingRows = plan.time_s > plan.interceptTime_s + 1e-9;
if options.ContinueTrackingAfterIntercept
    plan.trackingTime_s = plan.time_s(trackingRows);
    plan.trackingPosition_deg = plan.position_deg(trackingRows, :);
    plan.trackingVelocity_deg_s = plan.velocity_deg_s(trackingRows, :);
    plan.trackingAcceleration_deg_s2 = ...
        plan.acceleration_deg_s2(trackingRows, :);
    plan.trackingEndTime_s = plan.time_s(end);
    plan.trackingSuccess = plan.trackingEndTime_s > ...
        plan.interceptTime_s + 1e-9;
    if isfield(plan, "coreTrackingTerminationReason")
        plan.trackingTerminationReason = ...
            string(plan.coreTrackingTerminationReason);
    elseif plan.trackingEndTime_s >= options.TrackingEndTime_s - 1e-9
        plan.trackingTerminationReason = "trackingWindowComplete";
    else
        plan.trackingTerminationReason = "obstacle";
    end
    plan.trackingTerminatedByObstacle = ...
        plan.trackingTerminationReason == "obstacle";
else
    plan.trackingEndTime_s = plan.interceptTime_s;
end
plan.cost_s = plan.time_s(end) - plan.time_s(1);
plan.commandEndState = struct( ...
    "time_s", plan.time_s(end), ...
    "position_deg", plan.position_deg(end, :), ...
    "velocity_deg_s", plan.velocity_deg_s(end, :), ...
    "acceleration_deg_s2", plan.acceleration_deg_s2(end, :));
plan.failureCategory = string(plan.failureAssessment.classification);
plan.failureCause = string(plan.failureAssessment.reason);
plan.failureSuggestions = strings(0, 1);
plan.failureSummary = string(plan.message);
end

function times_s = interceptCandidateTimes(options)
times_s = (options.EarliestInterceptTime_s: ...
    options.InterceptTimeStep_s:options.LatestInterceptTime_s).';
if isempty(times_s) || times_s(end) < options.LatestInterceptTime_s - 1e-9
    times_s(end + 1, 1) = options.LatestInterceptTime_s;
end
if numel(times_s) > options.MaximumInterceptAttempts
    selectedRows = unique(round(linspace( ...
        1, numel(times_s), options.MaximumInterceptAttempts)));
    times_s = times_s(selectedRows);
end
end

function records = interceptAttemptRecords(times_s, target, plan)
template = struct( ...
    "time_s", NaN, ...
    "position_deg", [NaN NaN], ...
    "velocity_deg_s", [NaN NaN], ...
    "success", false, ...
    "elapsed_s", 0, ...
    "message", string(plan.message));
records = repmat(template, numel(times_s), 1);
for timeIndex = 1:numel(times_s)
    targetState = interpolateTarget(target, times_s(timeIndex));
    records(timeIndex).time_s = times_s(timeIndex);
    records(timeIndex).position_deg = targetState.position_deg;
    records(timeIndex).velocity_deg_s = targetState.velocity_deg_s;
    records(timeIndex).success = plan.success && ...
        abs(times_s(timeIndex) - plan.stopState.time_s) <= 1e-9;
end
end

function state = interpolateTarget(target, queryTime_s)
state = struct( ...
    "position_deg", interp1(target.time_s, target.position_deg, ...
        queryTime_s, "linear"), ...
    "velocity_deg_s", interp1(target.time_s, target.velocity_deg_s, ...
        queryTime_s, "linear"), ...
    "acceleration_deg_s2", interp1( ...
        target.time_s, target.acceleration_deg_s2, ...
        queryTime_s, "linear"));
end

function assertion = isPackedObstacleField(input)
assertion = isstruct(input) && isscalar(input) && ...
    isfield(input, "Format") && any(string(input.Format) == [ ...
    "AzElTimeObstacleField" "AzElTimeObstacleWorkspace"]);
end

function obstacleField = emptyObstacleField()
obstacleField = struct( ...
    "Format", "AzElTimeObstacleField", ...
    "Version", 3, ...
    "ReferenceTime", datetime(1970, 1, 1, 0, 0, 0, ...
        "TimeZone", "UTC"), ...
    "Obstacles", struct([]), ...
    "ObstacleCount", 0, ...
    "Options", buildAzElTimeObstacleField(), ...
    "EstimatedStorageBytes", 0);
end
