function plan = planAzElBidirectionalKinodynamicRRTStar( ...
        azElData, initialState, goalState, limits, options)
%PLANAZELBIDIRECTIONALKINODYNAMICRRTSTAR Plan with two space-time RRT* trees.
%
% plan = planAzElBidirectionalKinodynamicRRTStar( ...
%     azElData, initialState, goalState, limits, options)
%
% Nodes are fixed-time, zero-rate az/el states. Each edge waits at its
% source, then follows a synchronized quintic slew whose velocity and
% acceleration respect the supplied limits. One RRT* tree grows forward
% from the initial state while a second grows backward from the goal.
% Parent selection and rewiring minimize angular path length without
% changing node times, so descendants remain dynamically valid.
%
% This is a sampling planner. A finite run does not guarantee feasibility
% or global optimality; RRT* converges asymptotically under its usual
% sampling and clearance assumptions for this rest-state space-time model.

plannerTimer = tic;
if nargin < 5
    options = struct();
end
[initialState, goalState, limits, options] = normalizeInputs( ...
    initialState, goalState, limits, options);

if any(abs([initialState.velocity_deg_s, ...
        initialState.acceleration_deg_s2, ...
        goalState.velocity_deg_s, ...
        goalState.acceleration_deg_s2]) > 1e-12)
    error("planAzElBidirectionalKinodynamicRRTStar:BoundaryDynamics", ...
        "This planner currently requires rest initial and goal states.");
end

if isstruct(azElData) && isscalar(azElData) && ...
        isfield(azElData, "Format") && ...
        string(azElData.Format) == "AzElTimeObstacleWorkspace"
    workspace = azElData;
else
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", options.MaximumVerticesPerRegion));
end

previousRandomState = rng;
randomCleanup = onCleanup(@() rng(previousRandomState));
rng(options.RandomSeed, "twister");

maximumNodes = 2 * options.MaxIterations + 4;
forwardTree = initializeTree(initialState, maximumNodes);
backwardTree = initializeTree(goalState, maximumNodes);
bestConnection = struct( ...
    "ForwardIndex", uint32(0), ...
    "BackwardIndex", uint32(0), ...
    "Cost_deg", Inf, ...
    "WaypointPosition_deg", zeros(0, 2), ...
    "WaypointTime_s", zeros(0, 1));
firstSolutionIteration = Inf;
firstSolutionElapsed_s = Inf;

% A direct wait-and-slew edge is the Euclidean angular lower bound.
if edgeIsValid(initialState.position_deg, initialState.time_s, ...
        goalState.position_deg, goalState.time_s, workspace, ...
        limits, options)
    directConnection = struct( ...
        "ForwardIndex", uint32(1), ...
        "BackwardIndex", uint32(1), ...
        "Cost_deg", positionDistance(initialState.position_deg, ...
        goalState.position_deg, limits, options), ...
        "WaypointPosition_deg", zeros(0, 2), ...
        "WaypointTime_s", zeros(0, 1));
    directConnection = freezeValidatedConnection( ...
        directConnection, forwardTree, backwardTree, ...
        workspace, limits, options);
    if directConnection.ForwardIndex > 0
        bestConnection = directConnection;
        firstSolutionIteration = 0;
        firstSolutionElapsed_s = toc(plannerTimer);
    end
end

completedIterations = 0;
for iteration = 1:options.MaxIterations
    if toc(plannerTimer) >= options.MaxSearchTime_s
        break;
    end
    if isfinite(firstSolutionIteration) && ...
            iteration > firstSolutionIteration + ...
            options.IterationsAfterFirstSolution
        break;
    end

    forwardSample = sampleState( ...
        initialState, goalState, limits, options, true);
    [forwardTree, newForwardIndex] = extendTree( ...
        forwardTree, forwardSample, true, workspace, limits, options);
    if newForwardIndex > 0
        forwardTree = rewireTree( ...
            forwardTree, newForwardIndex, true, ...
            workspace, limits, options);
        candidateConnection = connectForwardNode( ...
            forwardTree, newForwardIndex, backwardTree, ...
            workspace, limits, options);
        if candidateConnection.Cost_deg < bestConnection.Cost_deg
            candidateConnection = freezeValidatedConnection( ...
                candidateConnection, forwardTree, backwardTree, ...
                workspace, limits, options);
            if candidateConnection.Cost_deg < bestConnection.Cost_deg
                bestConnection = candidateConnection;
                if ~isfinite(firstSolutionIteration)
                    firstSolutionIteration = iteration;
                    firstSolutionElapsed_s = toc(plannerTimer);
                end
            end
        end
    end

    backwardSample = sampleState( ...
        initialState, goalState, limits, options, false);
    [backwardTree, newBackwardIndex] = extendTree( ...
        backwardTree, backwardSample, false, workspace, limits, options);
    if newBackwardIndex > 0
        backwardTree = rewireTree( ...
            backwardTree, newBackwardIndex, false, ...
            workspace, limits, options);
        candidateConnection = connectBackwardNode( ...
            backwardTree, newBackwardIndex, forwardTree, ...
            workspace, limits, options);
        if candidateConnection.Cost_deg < bestConnection.Cost_deg
            candidateConnection = freezeValidatedConnection( ...
                candidateConnection, forwardTree, backwardTree, ...
                workspace, limits, options);
            if candidateConnection.Cost_deg < bestConnection.Cost_deg
                bestConnection = candidateConnection;
                if ~isfinite(firstSolutionIteration)
                    firstSolutionIteration = iteration;
                    firstSolutionElapsed_s = toc(plannerTimer);
                end
            end
        end
    end
    completedIterations = iteration;
end

forwardTree = trimTree(forwardTree);
backwardTree = trimTree(backwardTree);
elapsedTime_s = toc(plannerTimer);
if bestConnection.ForwardIndex == 0
    plan = failedPlan(workspace, initialState, goalState, limits, ...
        options, forwardTree, backwardTree, completedIterations, ...
        elapsedTime_s, firstSolutionElapsed_s);
    return;
end

waypointPosition_deg = bestConnection.WaypointPosition_deg;
waypointTime_s = bestConnection.WaypointTime_s;
profile = buildProfile(waypointPosition_deg, waypointTime_s, ...
    limits, options, options.SampleTime_s);
validationProfile = buildProfile(waypointPosition_deg, ...
    waypointTime_s, limits, options, options.ValidationStep_s);
blockedValidation = queryAzElTimeObstacle(workspace, ...
    validationProfile.position_deg(:, 1), ...
    validationProfile.position_deg(:, 2), ...
    validationProfile.time_s, collisionOptions(options));
if any(blockedValidation)
    plan = failedPlan(workspace, initialState, goalState, limits, ...
        options, forwardTree, backwardTree, completedIterations, ...
        elapsedTime_s, firstSolutionElapsed_s);
    plan.message = sprintf( ...
        "RRT* reconstruction contained %d blocked validation samples.", ...
        nnz(blockedValidation));
    plan.blockedValidationSampleCount = nnz(blockedValidation);
    return;
end

segmentDelta_deg = zeros(size(waypointPosition_deg, 1) - 1, 2);
for segmentIndex = 1:size(segmentDelta_deg, 1)
    segmentDelta_deg(segmentIndex, :) = wrappedDelta( ...
        waypointPosition_deg(segmentIndex, :), ...
        waypointPosition_deg(segmentIndex + 1, :), limits, options);
end
angularPathLength_deg = sum(hypot( ...
    segmentDelta_deg(:, 1), segmentDelta_deg(:, 2)));
endpointDelta_deg = wrappedDelta( ...
    initialState.position_deg, goalState.position_deg, limits, options);
angularLowerBound_deg = hypot(endpointDelta_deg(1), endpointDelta_deg(2));

plan = struct( ...
    "success", true, ...
    "message", ...
    "Bidirectional kinodynamic RRT* found an exact-checked trajectory.", ...
    "method", "bidirectionalKinodynamicRRTStar", ...
    "time_s", profile.time_s, ...
    "position_deg", profile.position_deg, ...
    "positionUnwrapped_deg", profile.positionUnwrapped_deg, ...
    "velocity_deg_s", profile.velocity_deg_s, ...
    "acceleration_deg_s2", profile.acceleration_deg_s2, ...
    "isWaiting", profile.isWaiting, ...
    "cost_s", goalState.time_s - initialState.time_s, ...
    "objective", "minimumAngularDistance", ...
    "objectiveCost", angularPathLength_deg, ...
    "objectiveCostUnits", "deg", ...
    "angularPathLength_deg", angularPathLength_deg, ...
    "angularLowerBound_deg", angularLowerBound_deg, ...
    "suboptimalityBound", max(1, angularPathLength_deg / ...
    max(angularLowerBound_deg, eps)), ...
    "optimalOnLattice", false, ...
    "optimalGlobally", angularPathLength_deg <= ...
    angularLowerBound_deg + 1e-9, ...
    "asymptoticallyOptimal", isinf(options.MaximumParentTrials) && ...
    isinf(options.MaximumRewireTrials), ...
    "exactCollisionValidated", true, ...
    "expandedNodeCount", forwardTree.Count + backwardTree.Count - 2, ...
    "generatedNodeCount", forwardTree.Count + backwardTree.Count, ...
    "searchElapsed_s", elapsedTime_s, ...
    "selectedGridStep_deg", NaN, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "waypointPosition_deg", waypointPosition_deg, ...
    "waypointTime_s", waypointTime_s, ...
    "blockedValidationSampleCount", 0, ...
    "completedIterations", completedIterations, ...
    "firstSolutionIteration", firstSolutionIteration, ...
    "firstSolutionElapsed_s", firstSolutionElapsed_s, ...
    "forwardTree", forwardTree, ...
    "backwardTree", backwardTree);
end

function tree = initializeTree(rootState, capacity)
tree = struct( ...
    "Position_deg", zeros(capacity, 2), ...
    "Time_s", nan(capacity, 1), ...
    "ParentIndex", zeros(capacity, 1, "uint32"), ...
    "Cost_deg", inf(capacity, 1), ...
    "Count", 1);
tree.Position_deg(1, :) = rootState.position_deg;
tree.Time_s(1) = rootState.time_s;
tree.Cost_deg(1) = 0;
end

function tree = trimTree(tree)
tree.Position_deg = tree.Position_deg(1:tree.Count, :);
tree.Time_s = tree.Time_s(1:tree.Count);
tree.ParentIndex = tree.ParentIndex(1:tree.Count);
tree.Cost_deg = tree.Cost_deg(1:tree.Count);
end

function sample = sampleState( ...
        initialState, goalState, limits, options, forward)
if rand < options.GoalBias
    if forward
        position_deg = goalState.position_deg;
        timeFraction = 0.55 + 0.45 * rand;
    else
        position_deg = initialState.position_deg;
        timeFraction = 0.45 * rand;
    end
else
    position_deg = [ ...
        limits.azimuth_deg(1) + diff(limits.azimuth_deg) * rand, ...
        limits.elevation_deg(1) + diff(limits.elevation_deg) * rand];
    timeFraction = rand;
end
sample = struct( ...
    "Position_deg", position_deg, ...
    "Time_s", initialState.time_s + timeFraction * ...
    (goalState.time_s - initialState.time_s));
end

function [tree, newIndex] = extendTree( ...
        tree, sample, forward, workspace, limits, options)
newIndex = uint32(0);
nodeIndices = (1:tree.Count).';
if forward
    temporalCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) < sample.Time_s - 1e-9);
else
    temporalCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) > sample.Time_s + 1e-9);
end
if isempty(temporalCandidates)
    return;
end

sampleDistance_deg = positionDistances( ...
    tree.Position_deg(temporalCandidates, :), ...
    sample.Position_deg, limits, options);
timeDistance_s = abs(tree.Time_s(temporalCandidates) - sample.Time_s);
nearestMetric = hypot(sampleDistance_deg, ...
    options.TimeMetric_deg_s * timeDistance_s);
[~, nearestOffset] = min(nearestMetric);
nearestIndex = temporalCandidates(nearestOffset);
targetDelta_deg = wrappedDelta( ...
    tree.Position_deg(nearestIndex, :), sample.Position_deg, ...
    limits, options);
targetDistance_deg = hypot(targetDelta_deg(1), targetDelta_deg(2));
if targetDistance_deg <= options.MinimumNodeSeparation_deg
    return;
end

availableTime_s = abs(sample.Time_s - tree.Time_s(nearestIndex));
spatialScale = min(1, options.StepSize_deg / targetDistance_deg);
dynamicScale = reachableScale( ...
    targetDelta_deg, availableTime_s, limits);
candidateDelta_deg = targetDelta_deg * min(spatialScale, dynamicScale);
if hypot(candidateDelta_deg(1), candidateDelta_deg(2)) < ...
        options.MinimumNodeSeparation_deg
    return;
end
candidatePosition_deg = canonicalPosition( ...
    tree.Position_deg(nearestIndex, :) + candidateDelta_deg, ...
    limits, options);
candidateTime_s = sample.Time_s;

allDistances_deg = positionDistances( ...
    tree.Position_deg(nodeIndices, :), candidatePosition_deg, ...
    limits, options);
if forward
    parentCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) < candidateTime_s - 1e-9 & ...
        allDistances_deg <= options.RewireRadius_deg);
else
    parentCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) > candidateTime_s + 1e-9 & ...
        allDistances_deg <= options.RewireRadius_deg);
end
if ~ismember(nearestIndex, parentCandidates)
    parentCandidates = [nearestIndex; parentCandidates];
end
candidateCosts_deg = tree.Cost_deg(parentCandidates) + ...
    positionDistances(tree.Position_deg(parentCandidates, :), ...
    candidatePosition_deg, limits, options);
[~, parentOrder] = sort(candidateCosts_deg);
parentCandidates = parentCandidates(parentOrder);
parentCandidates = parentCandidates( ...
    1:min(numel(parentCandidates), options.MaximumParentTrials));

bestParentIndex = 0;
bestCost_deg = Inf;
for parentIndex = reshape(parentCandidates, 1, [])
    if forward
        edgeValid = edgeIsValid( ...
            tree.Position_deg(parentIndex, :), tree.Time_s(parentIndex), ...
            candidatePosition_deg, candidateTime_s, ...
            workspace, limits, options);
    else
        edgeValid = edgeIsValid( ...
            candidatePosition_deg, candidateTime_s, ...
            tree.Position_deg(parentIndex, :), tree.Time_s(parentIndex), ...
            workspace, limits, options);
    end
    if edgeValid
        edgeCost_deg = positionDistance( ...
            tree.Position_deg(parentIndex, :), candidatePosition_deg, ...
            limits, options);
        totalCost_deg = tree.Cost_deg(parentIndex) + edgeCost_deg;
        if totalCost_deg < bestCost_deg
            bestParentIndex = parentIndex;
            bestCost_deg = totalCost_deg;
        end
    end
end
if bestParentIndex == 0
    return;
end

tree.Count = tree.Count + 1;
newIndex = uint32(tree.Count);
tree.Position_deg(tree.Count, :) = candidatePosition_deg;
tree.Time_s(tree.Count) = candidateTime_s;
tree.ParentIndex(tree.Count) = uint32(bestParentIndex);
tree.Cost_deg(tree.Count) = bestCost_deg;
end

function tree = rewireTree( ...
        tree, newIndex, forward, workspace, limits, options)
newIndex = double(newIndex);
nodeIndices = (2:tree.Count).';
distances_deg = positionDistances(tree.Position_deg(nodeIndices, :), ...
    tree.Position_deg(newIndex, :), limits, options);
if forward
    candidates = nodeIndices( ...
        tree.Time_s(nodeIndices) > tree.Time_s(newIndex) + 1e-9 & ...
        distances_deg <= options.RewireRadius_deg);
else
    candidates = nodeIndices( ...
        tree.Time_s(nodeIndices) < tree.Time_s(newIndex) - 1e-9 & ...
        distances_deg <= options.RewireRadius_deg);
end
[~, order] = sort(distances_deg(ismember(nodeIndices, candidates)));
candidates = candidates(order);
candidates = candidates( ...
    1:min(numel(candidates), options.MaximumRewireTrials));

for candidateIndex = reshape(candidates, 1, [])
    edgeCost_deg = positionDistance( ...
        tree.Position_deg(candidateIndex, :), ...
        tree.Position_deg(newIndex, :), limits, options);
    proposedCost_deg = tree.Cost_deg(newIndex) + edgeCost_deg;
    if proposedCost_deg >= tree.Cost_deg(candidateIndex) - 1e-9
        continue;
    end
    if forward
        edgeValid = edgeIsValid( ...
            tree.Position_deg(newIndex, :), tree.Time_s(newIndex), ...
            tree.Position_deg(candidateIndex, :), ...
            tree.Time_s(candidateIndex), workspace, limits, options);
    else
        edgeValid = edgeIsValid( ...
            tree.Position_deg(candidateIndex, :), ...
            tree.Time_s(candidateIndex), ...
            tree.Position_deg(newIndex, :), tree.Time_s(newIndex), ...
            workspace, limits, options);
    end
    if ~edgeValid
        continue;
    end
    costReduction_deg = proposedCost_deg - tree.Cost_deg(candidateIndex);
    tree.ParentIndex(candidateIndex) = uint32(newIndex);
    tree.Cost_deg(candidateIndex) = proposedCost_deg;
    tree = propagateCostChange(tree, candidateIndex, costReduction_deg);
end
end

function tree = propagateCostChange(tree, changedIndex, costChange_deg)
queue = uint32(changedIndex);
queueCursor = 1;
while queueCursor <= numel(queue)
    parentIndex = queue(queueCursor);
    queueCursor = queueCursor + 1;
    children = find(tree.ParentIndex(1:tree.Count) == parentIndex);
    if isempty(children)
        continue;
    end
    tree.Cost_deg(children) = tree.Cost_deg(children) + costChange_deg;
    queue = [queue; uint32(children(:))]; %#ok<AGROW>
end
end

function connection = connectForwardNode( ...
        forwardTree, forwardIndex, backwardTree, workspace, limits, options)
forwardIndex = double(forwardIndex);
candidateIndices = find(backwardTree.Time_s(1:backwardTree.Count) > ...
    forwardTree.Time_s(forwardIndex) + 1e-9);
connection = bestConnectionForPairSet( ...
    forwardTree, forwardIndex, backwardTree, candidateIndices, true, ...
    workspace, limits, options);
end

function connection = connectBackwardNode( ...
        backwardTree, backwardIndex, forwardTree, workspace, limits, options)
backwardIndex = double(backwardIndex);
candidateIndices = find(forwardTree.Time_s(1:forwardTree.Count) < ...
    backwardTree.Time_s(backwardIndex) - 1e-9);
connection = bestConnectionForPairSet( ...
    backwardTree, backwardIndex, forwardTree, candidateIndices, false, ...
    workspace, limits, options);
end

function connection = bestConnectionForPairSet( ...
        sourceTree, sourceIndex, otherTree, candidateIndices, ...
        sourceIsForward, workspace, limits, options)
connection = emptyConnection();
if isempty(candidateIndices)
    return;
end
distances_deg = positionDistances( ...
    otherTree.Position_deg(candidateIndices, :), ...
    sourceTree.Position_deg(sourceIndex, :), limits, options);
candidateIndices = candidateIndices( ...
    distances_deg <= options.ConnectionRadius_deg);
if isempty(candidateIndices)
    return;
end
totalCosts_deg = sourceTree.Cost_deg(sourceIndex) + ...
    otherTree.Cost_deg(candidateIndices) + ...
    positionDistances(otherTree.Position_deg(candidateIndices, :), ...
    sourceTree.Position_deg(sourceIndex, :), limits, options);
[~, order] = sort(totalCosts_deg);
candidateIndices = candidateIndices(order);
candidateIndices = candidateIndices( ...
    1:min(numel(candidateIndices), options.MaximumConnectionTrials));

for otherIndex = reshape(candidateIndices, 1, [])
    if sourceIsForward
        forwardIndex = sourceIndex;
        backwardIndex = otherIndex;
        edgeValid = edgeIsValid( ...
            sourceTree.Position_deg(sourceIndex, :), ...
            sourceTree.Time_s(sourceIndex), ...
            otherTree.Position_deg(otherIndex, :), ...
            otherTree.Time_s(otherIndex), workspace, limits, options);
    else
        forwardIndex = otherIndex;
        backwardIndex = sourceIndex;
        edgeValid = edgeIsValid( ...
            otherTree.Position_deg(otherIndex, :), ...
            otherTree.Time_s(otherIndex), ...
            sourceTree.Position_deg(sourceIndex, :), ...
            sourceTree.Time_s(sourceIndex), workspace, limits, options);
    end
    if ~edgeValid
        continue;
    end
    cost_deg = sourceTree.Cost_deg(sourceIndex) + ...
        otherTree.Cost_deg(otherIndex) + positionDistance( ...
        sourceTree.Position_deg(sourceIndex, :), ...
        otherTree.Position_deg(otherIndex, :), limits, options);
    if cost_deg < connection.Cost_deg
        connection.ForwardIndex = uint32(forwardIndex);
        connection.BackwardIndex = uint32(backwardIndex);
        connection.Cost_deg = cost_deg;
    end
end
end

function connection = emptyConnection()
connection = struct( ...
    "ForwardIndex", uint32(0), ...
    "BackwardIndex", uint32(0), ...
    "Cost_deg", Inf, ...
    "WaypointPosition_deg", zeros(0, 2), ...
    "WaypointTime_s", zeros(0, 1));
end

function connection = freezeValidatedConnection( ...
        connection, forwardTree, backwardTree, workspace, limits, options)
if connection.ForwardIndex == 0
    return;
end
[waypointPosition_deg, waypointTime_s] = connectionWaypoints( ...
    forwardTree, backwardTree, connection);
validationProfile = buildProfile(waypointPosition_deg, ...
    waypointTime_s, limits, options, options.ValidationStep_s);
blocked = queryAzElTimeObstacle(workspace, ...
    validationProfile.position_deg(:, 1), ...
    validationProfile.position_deg(:, 2), ...
    validationProfile.time_s, collisionOptions(options));
if any(blocked)
    connection = emptyConnection();
    return;
end
segmentCost_deg = 0;
for segmentIndex = 1:size(waypointPosition_deg, 1) - 1
    segmentCost_deg = segmentCost_deg + positionDistance( ...
        waypointPosition_deg(segmentIndex, :), ...
        waypointPosition_deg(segmentIndex + 1, :), limits, options);
end
connection.Cost_deg = segmentCost_deg;
connection.WaypointPosition_deg = waypointPosition_deg;
connection.WaypointTime_s = waypointTime_s;
end

function valid = edgeIsValid( ...
        fromPosition_deg, fromTime_s, toPosition_deg, toTime_s, ...
        workspace, limits, options)
valid = false;
availableTime_s = toTime_s - fromTime_s;
if availableTime_s <= 1e-9
    return;
end
delta_deg = wrappedDelta( ...
    fromPosition_deg, toPosition_deg, limits, options);
motionDuration_s = minimumQuinticDuration(delta_deg, limits);
if motionDuration_s > availableTime_s + 1e-9
    return;
end
departureTime_s = toTime_s - motionDuration_s;
edgeCheckStep_s = options.CollisionCheckStep_s;
% Use the same segment-anchored samples as final reconstruction, and add
% the departure instant where the stationary wait changes into motion.
queryTimes_s = unique([ ...
    sampledTimes(fromTime_s, toTime_s, edgeCheckStep_s); ...
    departureTime_s]);
normalizedTime = max(0, queryTimes_s - departureTime_s) / ...
    max(motionDuration_s, eps);
normalizedTime = min(normalizedTime, 1);
progress = quinticProgress(normalizedTime);
queryPosition_deg = fromPosition_deg + progress .* delta_deg;
queryPosition_deg(:, 1) = canonicalAzimuth( ...
    queryPosition_deg(:, 1), limits, options);
insideLimits = queryPosition_deg(:, 2) >= ...
    limits.elevation_deg(1) - 1e-9 & ...
    queryPosition_deg(:, 2) <= limits.elevation_deg(2) + 1e-9;
if ~options.AllowAzimuthWrap
    insideLimits = insideLimits & ...
        queryPosition_deg(:, 1) >= limits.azimuth_deg(1) - 1e-9 & ...
        queryPosition_deg(:, 1) <= limits.azimuth_deg(2) + 1e-9;
end
if ~all(insideLimits)
    return;
end
blocked = queryAzElTimeObstacle(workspace, ...
    queryPosition_deg(:, 1), queryPosition_deg(:, 2), ...
    queryTimes_s, collisionOptions(options));
valid = ~any(blocked);
end

function [positions_deg, times_s] = connectionWaypoints( ...
        forwardTree, backwardTree, connection)
forwardPath = uint32(connection.ForwardIndex);
while forwardTree.ParentIndex(forwardPath(1)) ~= 0
    forwardPath = [forwardTree.ParentIndex(forwardPath(1)); ...
        forwardPath]; %#ok<AGROW>
end
backwardPath = uint32(connection.BackwardIndex);
while backwardTree.ParentIndex(backwardPath(end)) ~= 0
    backwardPath(end + 1, 1) = ...
        backwardTree.ParentIndex(backwardPath(end)); %#ok<AGROW>
end
positions_deg = [ ...
    forwardTree.Position_deg(double(forwardPath), :); ...
    backwardTree.Position_deg(double(backwardPath), :)];
times_s = [ ...
    forwardTree.Time_s(double(forwardPath)); ...
    backwardTree.Time_s(double(backwardPath))];
end

function profile = buildProfile( ...
        waypointPosition_deg, waypointTime_s, limits, options, sampleStep_s)
time_s = zeros(0, 1);
positionUnwrapped_deg = zeros(0, 2);
velocity_deg_s = zeros(0, 2);
acceleration_deg_s2 = zeros(0, 2);
isWaiting = false(0, 1);
unwrappedStart_deg = waypointPosition_deg(1, :);

for segmentIndex = 1:numel(waypointTime_s) - 1
    fromTime_s = waypointTime_s(segmentIndex);
    toTime_s = waypointTime_s(segmentIndex + 1);
    delta_deg = wrappedDelta( ...
        waypointPosition_deg(segmentIndex, :), ...
        waypointPosition_deg(segmentIndex + 1, :), limits, options);
    motionDuration_s = minimumQuinticDuration(delta_deg, limits);
    departureTime_s = toTime_s - motionDuration_s;
    segmentTimes_s = sampledTimes(fromTime_s, toTime_s, sampleStep_s);
    if segmentIndex > 1
        segmentTimes_s = segmentTimes_s(2:end);
    end
    normalizedTime = max(0, segmentTimes_s - departureTime_s) / ...
        max(motionDuration_s, eps);
    normalizedTime = min(normalizedTime, 1);
    progress = quinticProgress(normalizedTime);
    progressRate = quinticProgressRate(normalizedTime) / ...
        max(motionDuration_s, eps);
    progressAcceleration = quinticProgressAcceleration(normalizedTime) / ...
        max(motionDuration_s^2, eps);
    waiting = segmentTimes_s < departureTime_s - 1e-9 | ...
        motionDuration_s <= 1e-12;

    segmentPosition_deg = unwrappedStart_deg + progress .* delta_deg;
    segmentVelocity_deg_s = progressRate .* delta_deg;
    segmentAcceleration_deg_s2 = progressAcceleration .* delta_deg;
    segmentVelocity_deg_s(waiting, :) = 0;
    segmentAcceleration_deg_s2(waiting, :) = 0;

    time_s = [time_s; segmentTimes_s]; %#ok<AGROW>
    positionUnwrapped_deg = [ ...
        positionUnwrapped_deg; segmentPosition_deg]; %#ok<AGROW>
    velocity_deg_s = [velocity_deg_s; segmentVelocity_deg_s]; %#ok<AGROW>
    acceleration_deg_s2 = [ ...
        acceleration_deg_s2; segmentAcceleration_deg_s2]; %#ok<AGROW>
    isWaiting = [isWaiting; waiting]; %#ok<AGROW>
    unwrappedStart_deg = unwrappedStart_deg + delta_deg;
end

position_deg = positionUnwrapped_deg;
position_deg(:, 1) = canonicalAzimuth( ...
    position_deg(:, 1), limits, options);
profile = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "positionUnwrapped_deg", positionUnwrapped_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "isWaiting", isWaiting);
end

function duration_s = minimumQuinticDuration(delta_deg, limits)
absoluteDelta_deg = abs(delta_deg);
velocityDuration_s = 1.875 * absoluteDelta_deg ./ ...
    limits.maxVelocity_deg_s;
accelerationDuration_s = sqrt( ...
    (10 / sqrt(3)) * absoluteDelta_deg ./ ...
    limits.maxAcceleration_deg_s2);
duration_s = max([velocityDuration_s, accelerationDuration_s]);
end

function scale = reachableScale(delta_deg, duration_s, limits)
absoluteDelta_deg = abs(delta_deg);
nonzero = absoluteDelta_deg > 1e-12;
if ~any(nonzero)
    scale = 0;
    return;
end
velocityScale = inf(1, 2);
accelerationScale = inf(1, 2);
velocityScale(nonzero) = limits.maxVelocity_deg_s(nonzero) * ...
    duration_s ./ (1.875 * absoluteDelta_deg(nonzero));
accelerationScale(nonzero) = limits.maxAcceleration_deg_s2(nonzero) * ...
    duration_s^2 ./ ((10 / sqrt(3)) * absoluteDelta_deg(nonzero));
scale = min([1, velocityScale, accelerationScale]);
scale = max(0, 0.98 * scale);
end

function progress = quinticProgress(normalizedTime)
progress = 10 * normalizedTime.^3 - 15 * normalizedTime.^4 + ...
    6 * normalizedTime.^5;
end

function rate = quinticProgressRate(normalizedTime)
rate = 30 * normalizedTime.^2 - 60 * normalizedTime.^3 + ...
    30 * normalizedTime.^4;
end

function acceleration = quinticProgressAcceleration(normalizedTime)
acceleration = 60 * normalizedTime - 180 * normalizedTime.^2 + ...
    120 * normalizedTime.^3;
end

function times_s = sampledTimes(firstTime_s, lastTime_s, step_s)
if lastTime_s < firstTime_s - 1e-9
    times_s = zeros(0, 1);
    return;
end
if abs(lastTime_s - firstTime_s) <= 1e-9
    times_s = firstTime_s;
    return;
end
times_s = (firstTime_s:step_s:lastTime_s).';
if isempty(times_s) || times_s(end) < lastTime_s - 1e-9
    times_s(end + 1, 1) = lastTime_s;
else
    times_s(end) = lastTime_s;
end
end

function distances_deg = positionDistances( ...
        positions_deg, target_deg, limits, options)
delta_deg = positions_deg - target_deg;
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    delta_deg(:, 1) = mod(delta_deg(:, 1) + ...
        azimuthSpan_deg / 2, azimuthSpan_deg) - ...
        azimuthSpan_deg / 2;
end
distances_deg = hypot(delta_deg(:, 1), delta_deg(:, 2));
end

function distance_deg = positionDistance( ...
        firstPosition_deg, secondPosition_deg, limits, options)
delta_deg = wrappedDelta( ...
    firstPosition_deg, secondPosition_deg, limits, options);
distance_deg = hypot(delta_deg(1), delta_deg(2));
end

function delta_deg = wrappedDelta( ...
        fromPosition_deg, toPosition_deg, limits, options)
delta_deg = toPosition_deg - fromPosition_deg;
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    delta_deg(1) = mod(delta_deg(1) + ...
        azimuthSpan_deg / 2, azimuthSpan_deg) - ...
        azimuthSpan_deg / 2;
end
end

function position_deg = canonicalPosition(position_deg, limits, options)
position_deg(1) = canonicalAzimuth(position_deg(1), limits, options);
position_deg(2) = min(max(position_deg(2), ...
    limits.elevation_deg(1)), limits.elevation_deg(2));
if ~options.AllowAzimuthWrap
    position_deg(1) = min(max(position_deg(1), ...
        limits.azimuth_deg(1)), limits.azimuth_deg(2));
end
end

function azimuth_deg = canonicalAzimuth(azimuth_deg, limits, options)
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    azimuth_deg = mod(azimuth_deg - limits.azimuth_deg(1), ...
        azimuthSpan_deg) + limits.azimuth_deg(1);
end
end

function queryOptions = collisionOptions(options)
queryOptions = struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", options.TimePaddingSamples);
end

function plan = failedPlan( ...
        workspace, initialState, goalState, limits, options, ...
        forwardTree, backwardTree, completedIterations, elapsedTime_s, ...
        firstSolutionElapsed_s)
plan = struct( ...
    "success", false, ...
    "message", ...
    "Bidirectional kinodynamic RRT* exhausted its finite search budget.", ...
    "method", "bidirectionalKinodynamicRRTStar", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "positionUnwrapped_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "isWaiting", false(0, 1), ...
    "angularPathLength_deg", Inf, ...
    "optimalGlobally", false, ...
    "asymptoticallyOptimal", isinf(options.MaximumParentTrials) && ...
    isinf(options.MaximumRewireTrials), ...
    "exactCollisionValidated", false, ...
    "expandedNodeCount", forwardTree.Count + backwardTree.Count - 2, ...
    "generatedNodeCount", forwardTree.Count + backwardTree.Count, ...
    "searchElapsed_s", elapsedTime_s, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "blockedValidationSampleCount", NaN, ...
    "completedIterations", completedIterations, ...
    "firstSolutionIteration", Inf, ...
    "firstSolutionElapsed_s", firstSolutionElapsed_s, ...
    "forwardTree", forwardTree, ...
    "backwardTree", backwardTree);
end

function [initialState, goalState, limits, options] = normalizeInputs( ...
        initialState, goalState, limits, options)
stateDefaults = struct( ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
for fieldName = string(fieldnames(stateDefaults)).'
    if ~isfield(initialState, fieldName)
        initialState.(fieldName) = stateDefaults.(fieldName);
    end
    if ~isfield(goalState, fieldName)
        goalState.(fieldName) = stateDefaults.(fieldName);
    end
end
requiredStateFields = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
for fieldName = requiredStateFields
    validateattributes(initialState.(fieldName), {'numeric'}, ...
        {'real', 'finite'});
    validateattributes(goalState.(fieldName), {'numeric'}, ...
        {'real', 'finite'});
end
initialState.position_deg = reshape( ...
    double(initialState.position_deg), 1, 2);
goalState.position_deg = reshape(double(goalState.position_deg), 1, 2);
initialState.velocity_deg_s = reshape( ...
    double(initialState.velocity_deg_s), 1, 2);
goalState.velocity_deg_s = reshape( ...
    double(goalState.velocity_deg_s), 1, 2);
initialState.acceleration_deg_s2 = reshape( ...
    double(initialState.acceleration_deg_s2), 1, 2);
goalState.acceleration_deg_s2 = reshape( ...
    double(goalState.acceleration_deg_s2), 1, 2);
if goalState.time_s <= initialState.time_s
    error("planAzElBidirectionalKinodynamicRRTStar:TimeOrder", ...
        "goalState.time_s must be later than initialState.time_s.");
end

limitFields = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
for fieldName = limitFields
    validateattributes(limits.(fieldName), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    limits.(fieldName) = reshape(double(limits.(fieldName)), 1, 2);
end

defaults = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.1, ...
    "CollisionCheckStep_s", 0.25, ...
    "SafetyMargin_deg", 0, ...
    "TimePaddingSamples", 1, ...
    "AllowAzimuthWrap", diff(limits.azimuth_deg) >= 360 - 1e-9, ...
    "StepSize_deg", 4, ...
    "MinimumNodeSeparation_deg", 0.1, ...
    "RewireRadius_deg", 7, ...
    "ConnectionRadius_deg", 10, ...
    "TimeMetric_deg_s", 0.2, ...
    "GoalBias", 0.12, ...
    "MaximumParentTrials", Inf, ...
    "MaximumRewireTrials", Inf, ...
    "MaximumConnectionTrials", 16, ...
    "MaxIterations", 4000, ...
    "IterationsAfterFirstSolution", 600, ...
    "MaxSearchTime_s", 45, ...
    "RandomSeed", 5489, ...
    "MaximumVerticesPerRegion", 500);
defaultNames = fieldnames(defaults);
for defaultIndex = 1:numel(defaultNames)
    defaultName = defaultNames{defaultIndex};
    if ~isfield(options, defaultName) || isempty(options.(defaultName))
        options.(defaultName) = defaults.(defaultName);
    end
end

positiveScalars = ["SampleTime_s", "ValidationStep_s", ...
    "CollisionCheckStep_s", "StepSize_deg", ...
    "MinimumNodeSeparation_deg", "RewireRadius_deg", ...
    "ConnectionRadius_deg", "TimeMetric_deg_s", "MaxSearchTime_s"];
for fieldName = positiveScalars
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
integerScalars = ["MaximumConnectionTrials", "MaxIterations", ...
    "IterationsAfterFirstSolution", "MaximumVerticesPerRegion"];
for fieldName = integerScalars
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'scalar', 'integer', 'nonnegative'});
end
neighborLimits = ["MaximumParentTrials", "MaximumRewireTrials"];
for fieldName = neighborLimits
    value = options.(fieldName);
    if ~(isinf(value) && value > 0)
        validateattributes(value, {'numeric'}, ...
            {'scalar', 'integer', 'positive'});
    end
end
validateattributes(options.GoalBias, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1});
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.TimePaddingSamples, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);
end
