function plan = planAzElDijkstra( ...
        azElData, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   options = planAzElDijkstra(limits, "defaults")
%   plan = planAzElDijkstra( ...
%       azElData, initialState, goalState, limits)
%   plan = planAzElDijkstra( ...
%       azElData, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Preserve the legacy fixed-goal call signature while translating one
%     request into the unified planAzElTrajectory scenario contract.
%**************************************************************************
% INPUTS
%   - azElData (canonical obstacle data or packed obstacle field)
%       Geometry passed unchanged to the authoritative planner.
%   - initialState, goalState (scalar structs)
%       time_s, position_deg, velocity_deg_s, acceleration_deg_s2.
%   - limits (scalar struct)
%       Angular, velocity, acceleration, and optional jerk limits.
%   - options (scalar struct, optional)
%       Legacy public option names translated without selecting an algorithm.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Unified result plus documented compatibility aliases.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s powers.

%% Section 1: Resolve Defaults Or Validate Compatibility Inputs
isDefaultsRequest = nargin == 2 && isstruct(azElData) && ...
    (ischar(initialState) || isstring(initialState)) && ...
    isscalar(string(initialState)) && ...
    strcmpi(strtrim(string(initialState)), "defaults");
if isDefaultsRequest
    normalizedLimits = normalizeCompatibilityLimits(azElData);
    plan = compatibilityDefaults(normalizedLimits);
    return;
end
if nargin < 5 || isempty(options)
    options = struct();
end
normalizedLimits = normalizeCompatibilityLimits(limits);
resolvedOptions = resolveCompatibilityOptions( ...
    options, compatibilityDefaults(normalizedLimits));
initialState = normalizeCompatibilityState(initialState, "initialState");
goalState = normalizeCompatibilityState(goalState, "goalState");

%% Section 2: Translate One Neutral Scenario
collisionCheckStep_s = resolvedOptions.CollisionCheckStep_s;
if isempty(collisionCheckStep_s)
    collisionCheckStep_s = resolvedOptions.ValidationStep_s;
end
if isempty(collisionCheckStep_s)
    collisionCheckStep_s = min(0.2, resolvedOptions.SampleTime_s);
end
scenarioOptions = struct( ...
    "sampleTime_s", resolvedOptions.SampleTime_s, ...
    "collisionCheckStep_s", collisionCheckStep_s, ...
    "safetyMargin_deg", resolvedOptions.SafetyMargin_deg, ...
    "allowAzimuthWrap", resolvedOptions.AllowAzimuthWrap, ...
    "objective", normalizeObjective(resolvedOptions.Objective));
scenario = struct( ...
    "requestKind", "fixed-goal", ...
    "azElData", {azElData}, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "target", [], ...
    "limits", normalizedLimits, ...
    "options", scenarioOptions, ...
    "resourceBudget", struct( ...
        "maximumWallTime_s", resolvedOptions.MaxSearchTime_s, ...
        "maximumExpansions", resolvedOptions.MaxExpansions));
coreOverrides = compatibilityCoreOverrides( ...
    resolvedOptions, collisionCheckStep_s);

%% Section 3: Call The Authoritative Planner Once
plan = planAzElTrajectory(scenario, coreOverrides);

%% Section 4: Add Compatibility Data Without Search Logic
if isempty(azElData)
    obstacleField = emptyCompatibilityObstacleField();
elseif isPackedObstacleField(azElData)
    obstacleField = azElData;
else
    obstacleField = buildAzElTimeObstacleField(azElData, struct( ...
        "MaximumVerticesPerRegion", ...
        resolvedOptions.MaximumVerticesPerRegion));
end
plan = addCompatibilityFields( ...
    plan, initialState, goalState, normalizedLimits, ...
    resolvedOptions, obstacleField);
end

%% Section 5: Local Functions
function options = compatibilityDefaults(limits)
options = struct( ...
    "SampleTime_s", 0.5, ...
    "ValidationStep_s", [], ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", [], ...
    "PrimitiveRadii_deg", [], ...
    "PrimitiveRadiusMultipliers", [1 2 4 8], ...
    "DirectionStep_deg", 45, ...
    "CollisionCheckStep_s", [], ...
    "MaximumSafeIntervalSamples", 10000, ...
    "MaximumDepartureTrials", 64, ...
    "DepartureBatchSize", 8, ...
    "MaxExpansions", 100000, ...
    "MaxSearchTime_s", 45, ...
    "InitialNodeCapacity", 4096, ...
    "TimePaddingSamples", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", diff(limits.azimuth_deg) >= 360 - 1e-9, ...
    "AllowNonzeroTerminalState", true, ...
    "PrintFailureSuggestions", true, ...
    "Objective", "minimumAngularDistance", ...
    "RouteShortcutStep_deg", 0.1, ...
    "MaximumVerticesPerRegion", 500, ...
    "MaxJerk_deg_s3", limits.maxJerk_deg_s3, ...
    "HeuristicMode", "reverseDijkstra");
end

function options = resolveCompatibilityOptions(options, defaults)
if ~isstruct(options) || ~isscalar(options)
    error("planAzElDijkstra:InvalidOptions", ...
        "options must be a scalar struct.");
end
unknownFields = setdiff( ...
    fieldnames(options), fieldnames(defaults), "stable");
if ~isempty(unknownFields)
    warning("planAzElDijkstra:UnknownOptions", ...
        "Ignoring unknown option fields: %s.", ...
        strjoin(string(unknownFields), ", "));
    options = rmfield(options, unknownFields);
end
defaultFields = fieldnames(defaults);
for fieldIndex = 1:numel(defaultFields)
    fieldName = defaultFields{fieldIndex};
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        options.(fieldName) = defaults.(fieldName);
    end
end
positiveScalarFields = ["SampleTime_s", "GridStep_deg", ...
    "DirectionStep_deg", "MaxSearchTime_s"];
for fieldName = positiveScalarFields
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.MaxExpansions, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);
options.AllowNonzeroTerminalState = ...
    logical(options.AllowNonzeroTerminalState);
options.PrintFailureSuggestions = ...
    logical(options.PrintFailureSuggestions);
options.HeuristicMode = string(options.HeuristicMode);
end

function limits = normalizeCompatibilityLimits(input)
requiredFields = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(isfield(input, requiredFields))
    error("planAzElDijkstra:InvalidLimits", ...
        "limits is missing angular or kinematic bounds.");
end
limits = input;
for fieldName = requiredFields
    value = reshape(double(limits.(fieldName)), 1, 2);
    if any(~isfinite(value))
        error("planAzElDijkstra:InvalidLimits", ...
            "%s must contain two finite values.", fieldName);
    end
    limits.(fieldName) = value;
end
if any(diff([limits.azimuth_deg; limits.elevation_deg], 1, 2) <= 0)
    error("planAzElDijkstra:InvalidLimits", ...
        "Angular lower bounds must precede upper bounds.");
end
if any(limits.maxVelocity_deg_s <= 0) || ...
        any(limits.maxAcceleration_deg_s2 <= 0)
    error("planAzElDijkstra:InvalidLimits", ...
        "Velocity and acceleration limits must be positive.");
end
if isfield(limits, "maxJerk_deg_s3") && ...
        ~isempty(limits.maxJerk_deg_s3)
    limits.maxJerk_deg_s3 = reshape( ...
        double(limits.maxJerk_deg_s3), 1, 2);
else
    limits.maxJerk_deg_s3 = max( ...
        10, 20 * limits.maxAcceleration_deg_s2);
end
if any(~isfinite(limits.maxJerk_deg_s3)) || ...
        any(limits.maxJerk_deg_s3 <= 0)
    error("planAzElDijkstra:InvalidLimits", ...
        "Jerk limits must be two positive finite values.");
end
end

function state = normalizeCompatibilityState(input, name)
requiredFields = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(isfield(input, requiredFields))
    error("planAzElDijkstra:InvalidState", ...
        "%s is missing time, position, velocity, or acceleration.", name);
end
state = struct( ...
    "time_s", double(input.time_s), ...
    "position_deg", reshape(double(input.position_deg), 1, 2), ...
    "velocity_deg_s", reshape(double(input.velocity_deg_s), 1, 2), ...
    "acceleration_deg_s2", ...
        reshape(double(input.acceleration_deg_s2), 1, 2));
if ~isscalar(state.time_s) || any(~isfinite([state.time_s, ...
        state.position_deg, state.velocity_deg_s, ...
        state.acceleration_deg_s2]))
    error("planAzElDijkstra:InvalidState", ...
        "%s must contain finite scalar/vector values.", name);
end
end

function coreOptions = compatibilityCoreOverrides(options, collisionStep_s)
maximumPrimitiveDistance_deg = NaN;
if ~isempty(options.PrimitiveRadii_deg)
    maximumPrimitiveDistance_deg = max(options.PrimitiveRadii_deg);
elseif ~isempty(options.PrimitiveRadiusMultipliers)
    maximumPrimitiveDistance_deg = options.GridStep_deg * ...
        max(options.PrimitiveRadiusMultipliers);
end
directionCount = max(8, round(360 / options.DirectionStep_deg));
coreOptions = struct( ...
    "GridStep_deg", options.GridStep_deg, ...
    "SampleTime_s", options.SampleTime_s, ...
    "CollisionCheckStep_s", collisionStep_s, ...
    "MaxJerk_deg_s3", options.MaxJerk_deg_s3, ...
    "MaxWallTime_s", options.MaxSearchTime_s, ...
    "MaxExpandedStates", options.MaxExpansions, ...
    "MaxGeneratedStates", max(10000, 4 * options.MaxExpansions), ...
    "MaximumPrimitiveDistance_deg", maximumPrimitiveDistance_deg, ...
    "DirectionCount", directionCount, ...
    "HeuristicMode", options.HeuristicMode);
end

function objective = normalizeObjective(input)
name = lower(strtrim(string(input)));
if any(name == ["minimumangulardistance", "angulardistance", ...
        "distance"])
    objective = "minimumAngularDistance";
elseif any(name == ["minimumtime", "time"])
    objective = "minimumTime";
else
    error("planAzElDijkstra:InvalidObjective", ...
        "Objective must be minimumAngularDistance or minimumTime.");
end
end

function assertion = isPackedObstacleField(input)
assertion = isstruct(input) && isscalar(input) && ...
    isfield(input, "Format") && any(string(input.Format) == [ ...
    "AzElTimeObstacleField", "AzElTimeObstacleWorkspace"]);
end

function obstacleField = emptyCompatibilityObstacleField()
referenceTime = datetime(1970, 1, 1, 0, 0, 0, "TimeZone", "UTC");
obstacleField = struct( ...
    "Format", "AzElTimeObstacleField", ...
    "Version", 3, ...
    "ReferenceTime", referenceTime, ...
    "Obstacles", struct([]), ...
    "ObstacleCount", 0, ...
    "Options", buildAzElTimeObstacleField(), ...
    "EstimatedStorageBytes", 0);
end

function plan = addCompatibilityFields( ...
        plan, initialState, goalState, limits, options, obstacleField)
coreOptions = plan.options;
coreOptionFields = fieldnames(coreOptions);
for fieldIndex = 1:numel(coreOptionFields)
    fieldName = coreOptionFields{fieldIndex};
    if ~isfield(options, fieldName)
        options.(fieldName) = coreOptions.(fieldName);
    end
end
plan.options = options;
plan.limits = limits;
plan.startState = initialState;
if isempty(plan.stopState.position_deg)
    plan.stopState = goalState;
end
plan.obstacleField = obstacleField;
plan.workspace = obstacleField; % deprecated compatibility alias
plan.expandedNodeCount = plan.expandedStateCount;
plan.generatedNodeCount = plan.generatedStateCount;
plan.selectedGridStep_deg = coreOptions.GridStep_deg;
plan.cost_s = NaN;
if plan.success
    plan.cost_s = plan.time_s(end) - plan.time_s(1);
end
if string(plan.objective) == "minimumTime"
    plan.objectiveCostUnits = "s";
else
    plan.objectiveCostUnits = "deg";
end
endpointDelta_deg = goalState.position_deg - initialState.position_deg;
if options.AllowAzimuthWrap
    endpointDelta_deg(1) = mod(endpointDelta_deg(1) + 180, 360) - 180;
end
plan.angularLowerBound_deg = hypot( ...
    endpointDelta_deg(1), endpointDelta_deg(2));
plan.suboptimalityBound = NaN;
plan.optimalOnLattice = false;
plan.optimalGlobally = false;
if isfield(plan, "diagnostics") && ...
        isfield(plan.diagnostics, "forwardAStar") && ...
        isfield(plan.diagnostics.forwardAStar, "optimalityProven")
    plan.optimalOnLattice = ...
        plan.diagnostics.forwardAStar.optimalityProven;
end
plan.exactCollisionValidated = false;
plan.topologyOptimalOnLattice = plan.optimalOnLattice;
plan.topologySearch = struct();
plan.preShortcutRoute_deg = zeros(0, 2);
plan.routeShortcut = struct();
plan.autonomousRoute_deg = zeros(0, 2);
plan.retiming = struct();
plan.resolutionAttempts = struct([]);
plan.safeIntervalSearch = struct();
plan.failureCategory = string(plan.failureAssessment.classification);
plan.failureCause = string(plan.failureAssessment.reason);
plan.failureSuggestions = strings(0, 1);
plan.failureSummary = string(plan.message);
end
