function plan = planAzElAdaptiveAStar( ...
        azElData, initialState, goalState, limits, options)
%PLANAZELADAPTIVEASTAR Plan one exact-checked az/el/time trajectory.
%
% plan = planAzElAdaptiveAStar( ...
%     azElData, initialState, goalState, limits, options)
%
% The planner uses one public workflow at progressively finer spatial
% resolutions:
%   1. A spatial state is an az/el grid point.
%   2. Static costs propagate backward from the goal with Dijkstra.
%   3. Dynamic time is compressed into maximal safe intervals for A*.
%   4. Edges are analytic rest-to-rest slews plus optional waiting.
%   5. An enabled terminal edge may match nonzero velocity/acceleration.
%   6. Every returned command is checked against packed polygons.
%
% Static geometry uses goal-rooted Dijkstra at progressive grid sizes.
% Dynamic geometry uses safe-interval A*. Both branches validate the final
% command against the original packed polygons.

timer = tic;
if nargin < 5
    options = struct();
end
[initialState, goalState, limits, options] = ...
    normalizeAdaptiveAStarInputs( ...
        initialState, goalState, limits, options);

if any(abs([initialState.velocity_deg_s, ...
        initialState.acceleration_deg_s2]) > 1e-12)
    error("planAzElAdaptiveAStar:NonzeroBoundaryDynamics", ...
        "The maintainable planner requires a rest initial state.");
end
hasTerminalDynamics = any(abs([goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2]) > 1e-12);
if hasTerminalDynamics && ~options.AllowNonzeroTerminalState
    error("planAzElAdaptiveAStar:NonzeroTerminalStateDisabled", ...
        "Set AllowNonzeroTerminalState to true for terminal capture.");
end

prebuiltWorkspace = isstruct(azElData) && isscalar(azElData) && ...
    isfield(azElData, "Format") && ...
    string(azElData.Format) == "AzElTimeObstacleWorkspace";
% Reusing a packed workspace avoids repacking the same polygons when a
% caller evaluates several initial/goal pairs against one obstacle field.
if prebuiltWorkspace
    workspace = azElData;
else
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", options.MaximumVerticesPerRegion));
end

schedule = options.GridStepSchedule_deg(:).';
% A static minimum-distance case can use a cheaper complete 2-D graph.
% Terminal dynamics remain in the safe-interval search because the final
% edge must match velocity and acceleration at an exact arrival time.
if ~hasTerminalDynamics && ...
        options.Objective == "minimumAngularDistance" && ...
        isAzElTimeObstacleWorkspaceStatic( ...
        workspace, initialState.time_s, goalState.time_s)
    plan = progressiveStaticDijkstra(workspace, initialState, ...
        goalState, limits, options, schedule, timer);
    if plan.success
        return;
    end
end

attemptTemplate = struct( ...
    "GridStep_deg", NaN, ...
    "PrimitiveRadii_deg", zeros(1, 0), ...
    "Success", false, ...
    "Message", "", ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0, ...
    "TerminationReason", "", ...
    "ObjectiveCost", Inf, ...
    "CandidateTime_s", zeros(0, 1), ...
    "CandidatePosition_deg", zeros(0, 2), ...
    "Selected", false);
attempts = repmat(attemptTemplate, numel(schedule), 1);
attemptCount = 0;
search = struct();
bestSearch = struct();
bestObjective = Inf;
bestGridStep = NaN;
endpointDelta = wrappedDelta(initialState.position_deg, ...
    goalState.position_deg, limits, options);
endpointLowerBound = hypot(endpointDelta(1), endpointDelta(2));

% Coarse failures only mean that a graph could not represent a route. Retry
% the same search at progressively finer spatial resolutions.
for level = 1:numel(schedule)
    remaining = options.MaxSearchTime_s - toc(timer);
    if remaining <= 0
        break;
    end

    levelOptions = options;
    levelOptions.GridStep_deg = schedule(level);
    if isempty(options.PrimitiveRadii_deg)
        levelOptions.PrimitiveRadii_deg = unique( ...
            schedule(level) * options.PrimitiveRadiusMultipliers);
    end
    remainingLevels = numel(schedule) - level + 1;
    % Reserve time for later levels so one difficult coarse graph cannot
    % consume the complete wall-time budget.
    levelBudget = remaining / remainingLevels;
    if level == numel(schedule)
        levelBudget = remaining;
    end
    levelOptions.MaxSearchTime_s = max( ...
        min(levelBudget, options.MaxSearchTime_s), 0.05);

    candidate = searchAzElSafeIntervalAStar(workspace, ...
        initialState, goalState, limits, levelOptions);
    [candidateTime, candidatePosition, candidateCost] = ...
        dynamicCandidateTrace(candidate, options);
    attemptCount = attemptCount + 1;
    attempts(attemptCount, 1) = struct( ...
        "GridStep_deg", schedule(level), ...
        "PrimitiveRadii_deg", ...
        levelOptions.PrimitiveRadii_deg, ...
        "Success", candidate.Success, ...
        "Message", candidate.Message, ...
        "ExpandedNodeCount", candidate.ExpandedNodeCount, ...
        "GeneratedNodeCount", candidate.GeneratedNodeCount, ...
        "SearchElapsed_s", candidate.SearchElapsed_s, ...
        "TerminationReason", candidate.TerminationReason, ...
        "ObjectiveCost", candidateCost, ...
        "CandidateTime_s", candidateTime, ...
        "CandidatePosition_deg", candidatePosition, ...
        "Selected", false);
    search = candidate;
    if candidate.Success
        if ~hasTerminalDynamics && ...
                abs(candidate.Route.angularPathLength_deg - ...
                endpointLowerBound) <= 1e-9
            candidate.GlobalAngularOptimal = true;
            search = candidate;
        end
        if options.Objective == "minimumAngularDistance"
            candidateObjective = ...
                candidate.Route.angularPathLength_deg;
        else
            candidateObjective = ...
                candidate.Route.arrivalTime_s(end);
        end
        if candidateObjective < bestObjective
            bestSearch = candidate;
            bestObjective = candidateObjective;
            bestGridStep = schedule(level);
        end
        % Stop only for an objective certificate or the minimum-time policy.
        % Otherwise keep the best validated candidate and continue refining.
        if candidate.GlobalAngularOptimal || ...
                options.Objective == "minimumTime"
            break;
        end
    end
end

attempts = attempts(1:attemptCount);
if ~isempty(fieldnames(bestSearch))
    search = bestSearch;
    selected = find([attempts.Success] & ...
        abs([attempts.ObjectiveCost] - bestObjective) <= 1e-9, 1, "last");
    attempts(selected).Selected = true;
end

if isempty(fieldnames(search)) || ~search.Success
    if isempty(fieldnames(search))
        message = "The search time budget expired before A* started.";
    else
        message = search.Message;
    end
    plan = failedPlan(message, workspace, initialState, goalState, ...
        limits, options, attempts, search, toc(timer));
    plan = finalizeAzElPlanFailure(plan);
    return;
end

profile = search.Profile;
route = search.Route;
% Search nodes are maneuver breakpoints. Profile is the uniform command
% history that downstream visualization and control code consumes.
delta = wrappedDelta(initialState.position_deg, ...
    goalState.position_deg, limits, options);
lowerBound = hypot(delta(1), delta(2));
if options.Objective == "minimumAngularDistance"
    objectiveCost = route.angularPathLength_deg;
    objectiveUnits = "deg";
else
    objectiveCost = route.arrivalTime_s(end) - initialState.time_s;
    objectiveUnits = "s";
end

plan = struct( ...
    "success", true, ...
    "message", ...
    "Progressive safe-interval A* found an exact-checked trajectory.", ...
    "method", "progressiveSafeIntervalAStar", ...
    "time_s", profile.time_s, ...
    "position_deg", profile.position_deg, ...
    "positionUnwrapped_deg", profile.positionUnwrapped_deg, ...
    "velocity_deg_s", profile.velocity_deg_s, ...
    "acceleration_deg_s2", profile.acceleration_deg_s2, ...
    "isWaiting", profile.isWaiting, ...
    "cost_s", goalState.time_s - initialState.time_s, ...
    "objective", options.Objective, ...
    "objectiveCost", objectiveCost, ...
    "objectiveCostUnits", objectiveUnits, ...
    "angularPathLength_deg", route.angularPathLength_deg, ...
    "angularLowerBound_deg", lowerBound, ...
    "suboptimalityBound", ...
    max(1, route.angularPathLength_deg / max(lowerBound, eps)), ...
    "optimalOnLattice", false, ...
    "optimalGlobally", search.GlobalAngularOptimal, ...
    "exactCollisionValidated", true, ...
    "expandedNodeCount", sum([attempts.ExpandedNodeCount]), ...
    "generatedNodeCount", sum([attempts.GeneratedNodeCount]), ...
    "searchElapsed_s", toc(timer), ...
    "selectedGridStep_deg", bestGridStep, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "resolutionAttempts", attempts, ...
    "safeIntervalSearch", search);
end

function plan = progressiveStaticDijkstra( ...
        workspace, initialState, goalState, axisLimits, options, ...
        gridSchedule_deg, plannerTimer)
attemptTemplate = struct( ...
    "GridStep_deg", NaN, ...
    "PrimitiveRadii_deg", zeros(1, 0), ...
    "Success", false, ...
    "Message", "", ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0, ...
    "TerminationReason", "", ...
    "ObjectiveCost", Inf, ...
    "CandidateTime_s", zeros(0, 1), ...
    "CandidatePosition_deg", zeros(0, 2), ...
    "Selected", false);
attempts = repmat(attemptTemplate, numel(gridSchedule_deg), 1);
attemptCount = 0;
bestPlan = struct();
bestRouteDistance_deg = Inf;

% Every level is a complete finite graph. Dijkstra propagates cost backward
% from the goal, and exact packed polygons validate every returned profile.
for gridLevel = 1:numel(gridSchedule_deg)
    remainingTime_s = options.MaxSearchTime_s - toc(plannerTimer);
    if remainingTime_s <= 0
        break;
    end
    staticOptions = options;
    staticOptions.GridStep_deg = gridSchedule_deg(gridLevel);
    staticOptions.PrintFailureSuggestions = false;
    remainingLevelCount = numel(gridSchedule_deg) - gridLevel + 1;
    staticOptions.MaxSearchTime_s = remainingTime_s / remainingLevelCount;

    candidate = solveStaticGoalDijkstra( ...
        workspace, initialState, goalState, axisLimits, staticOptions);
    endpointDelta = wrappedDelta(initialState.position_deg, ...
        goalState.position_deg, axisLimits, options);
    endpointLowerBound = hypot(endpointDelta(1), endpointDelta(2));
    if candidate.success && ...
            abs(candidate.angularPathLength_deg - endpointLowerBound) <= 1e-9
        candidate.optimalGlobally = true;
        candidate.suboptimalityBound = 1;
    end
    if candidate.success
        candidateTime = candidate.time_s;
        candidatePosition = candidate.position_deg;
        candidateCost = candidate.objectiveCost;
    else
        candidateTime = zeros(0, 1);
        candidatePosition = zeros(0, 2);
        candidateCost = Inf;
    end
    attemptCount = attemptCount + 1;
    attempts(attemptCount) = struct( ...
        "GridStep_deg", gridSchedule_deg(gridLevel), ...
        "PrimitiveRadii_deg", zeros(1, 0), ...
        "Success", candidate.success, ...
        "Message", candidate.message, ...
        "ExpandedNodeCount", candidate.expandedNodeCount, ...
        "GeneratedNodeCount", candidate.generatedNodeCount, ...
        "SearchElapsed_s", candidate.searchElapsed_s, ...
        "TerminationReason", candidate.topologySearch.TerminationReason, ...
        "ObjectiveCost", candidateCost, ...
        "CandidateTime_s", candidateTime, ...
        "CandidatePosition_deg", candidatePosition, ...
        "Selected", false);
    if candidate.success && ...
            candidate.objectiveCost < bestRouteDistance_deg
        bestPlan = candidate;
        bestRouteDistance_deg = candidate.objectiveCost;
    end
    % Matching the straight-line lower bound proves global angular optimality
    % and makes further spatial refinement unnecessary.
    if candidate.success && candidate.optimalGlobally
        break;
    end
end
attempts = attempts(1:attemptCount);

if isempty(fieldnames(bestPlan))
    if attemptCount == 0
        message = "The static Dijkstra time budget expired before search.";
    else
        message = attempts(end).Message;
    end
    plan = failedPlan(message, workspace, initialState, goalState, ...
        axisLimits, options, attempts, struct(), toc(plannerTimer));
    return;
end

selected = find([attempts.Success] & ...
    abs([attempts.ObjectiveCost] - bestRouteDistance_deg) <= 1e-9, ...
    1, "last");
attempts(selected).Selected = true;

bestPlan.message = "Goal-rooted Dijkstra found an exact-checked route.";
bestPlan.method = "adaptiveGoalRootedDijkstra";
bestPlan.exactCollisionValidated = true;
bestPlan.selectedGridStep_deg = bestPlan.options.GridStep_deg;
bestPlan.resolutionAttempts = attempts;
bestPlan.safeIntervalSearch = struct();
bestPlan.searchElapsed_s = toc(plannerTimer);
bestPlan.options = options;
plan = bestPlan;
end

function plan = solveStaticGoalDijkstra( ...
        workspace, initialState, goalState, axisLimits, options)
% Propagate an exact lattice cost-to-go map backward from the goal.
staticTimer = tic;
topology = emptyGoalDijkstraResult(options);
endpointBlocked = queryAzElTimeObstacle(workspace, ...
    [initialState.position_deg(1); goalState.position_deg(1)], ...
    [initialState.position_deg(2); goalState.position_deg(2)], ...
    [initialState.time_s; goalState.time_s], struct( ...
    "CollisionMode", "polygon", ...
    "SafetyMarginDeg", options.SafetyMargin_deg));
if any(endpointBlocked)
    plan = failedStaticPlan( ...
        "The initial or goal state lies inside the inflated workspace.", ...
        workspace, initialState, goalState, axisLimits, options, ...
        topology, toc(staticTimer));
    return;
end

[azimuthGrid_deg, elevationGrid_deg] = staticGrid(axisLimits, options);
[azimuthMesh_deg, elevationMesh_deg] = meshgrid( ...
    azimuthGrid_deg, elevationGrid_deg);
blockedGrid = queryAzElTimeObstacle(workspace, ...
    azimuthMesh_deg(:), elevationMesh_deg(:), initialState.time_s, ...
    struct("CollisionMode", "polygon", ...
    "SafetyMarginDeg", options.SafetyMargin_deg));
blockedGrid = reshape(blockedGrid, size(azimuthMesh_deg));

topology = propagateGoalCostWithDijkstra( ...
    blockedGrid, azimuthGrid_deg, elevationGrid_deg, ...
    initialState.position_deg, goalState.position_deg, options);
if ~topology.Success
    plan = failedStaticPlan( ...
        "Goal-rooted Dijkstra failed: " + topology.Message, ...
        workspace, initialState, goalState, axisLimits, options, ...
        topology, toc(staticTimer));
    return;
end

routePositions_deg = [initialState.position_deg; ...
    topology.Path_deg; goalState.position_deg];
routePositions_deg = unwrapAndReduceRoute( ...
    routePositions_deg, axisLimits, options);
unshortenedRoute_deg = routePositions_deg;
shortcut = shortcutStaticRoute(workspace, routePositions_deg, ...
    initialState.time_s, axisLimits, options);
if ~shortcut.Success
    plan = failedStaticPlan( ...
        "Exact route shortcut validation failed: " + shortcut.Message, ...
        workspace, initialState, goalState, axisLimits, options, ...
        topology, toc(staticTimer));
    return;
end
routePositions_deg = shortcut.Path_deg;

retimed = retimeStaticRoute(workspace, routePositions_deg, ...
    initialState, goalState, axisLimits, options);
if ~retimed.Success
    plan = failedStaticPlan( ...
        "Static route retiming failed: " + retimed.Message, ...
        workspace, initialState, goalState, axisLimits, options, ...
        topology, toc(staticTimer));
    plan.preShortcutRoute_deg = unshortenedRoute_deg;
    plan.routeShortcut = shortcut;
    return;
end

profile = retimed.Profile;
routeDistance_deg = retimed.RouteDistance_deg;
endpointDelta_deg = wrappedDelta(initialState.position_deg, ...
    goalState.position_deg, axisLimits, options);
straightLineLowerBound_deg = hypot( ...
    endpointDelta_deg(1), endpointDelta_deg(2));
plan = struct( ...
    "success", true, ...
    "message", "Goal-rooted Dijkstra route found and retimed.", ...
    "method", "goalRootedDijkstra", ...
    "time_s", profile.time_s, ...
    "position_deg", profile.position_deg, ...
    "positionUnwrapped_deg", profile.positionUnwrapped_deg, ...
    "velocity_deg_s", profile.velocity_deg_s, ...
    "acceleration_deg_s2", profile.acceleration_deg_s2, ...
    "isWaiting", profile.isWaiting, ...
    "cost_s", goalState.time_s - initialState.time_s, ...
    "objective", "minimumAngularDistance", ...
    "objectiveCost", routeDistance_deg, ...
    "objectiveCostUnits", "deg", ...
    "angularPathLength_deg", routeDistance_deg, ...
    "angularLowerBound_deg", straightLineLowerBound_deg, ...
    "suboptimalityBound", max(1, routeDistance_deg / ...
        max(straightLineLowerBound_deg, eps)), ...
    "optimalOnLattice", false, ...
    "topologyOptimalOnLattice", true, ...
    "optimalGlobally", false, ...
    "exactCollisionValidated", true, ...
    "expandedNodeCount", topology.ExpandedNodeCount, ...
    "generatedNodeCount", topology.GeneratedNodeCount, ...
    "searchElapsed_s", toc(staticTimer), ...
    "selectedGridStep_deg", options.GridStep_deg, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", axisLimits, ...
    "options", options, ...
    "workspace", workspace, ...
    "topologySearch", topology, ...
    "preShortcutRoute_deg", unshortenedRoute_deg, ...
    "routeShortcut", shortcut, ...
    "autonomousRoute_deg", routePositions_deg, ...
    "retiming", retimed);
end

function [azimuthGrid_deg, elevationGrid_deg] = ...
        staticGrid(axisLimits, options)
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(axisLimits.azimuth_deg);
    azimuthBinCount = ceil(azimuthSpan_deg / options.GridStep_deg);
    wrappedGridStep_deg = azimuthSpan_deg / azimuthBinCount;
    azimuthGrid_deg = axisLimits.azimuth_deg(1) + ...
        (0:azimuthBinCount - 1) * wrappedGridStep_deg;
else
    azimuthGrid_deg = inclusiveGrid( ...
        axisLimits.azimuth_deg, options.GridStep_deg);
end
elevationGrid_deg = inclusiveGrid( ...
    axisLimits.elevation_deg, options.GridStep_deg);
end

function gridValues = inclusiveGrid(gridLimits, gridStep)
gridValues = gridLimits(1):gridStep:gridLimits(2);
if gridValues(end) < gridLimits(2) - 1e-9
    gridValues(end + 1) = gridLimits(2);
end
gridValues = double(gridValues);
end

function result = propagateGoalCostWithDijkstra( ...
        blockedGrid, azimuthGrid_deg, elevationGrid_deg, ...
        initialPosition_deg, goalPosition_deg, options)
searchTimer = tic;
blockedGrid = logical(blockedGrid);
elevationBinCount = numel(elevationGrid_deg);
azimuthBinCount = numel(azimuthGrid_deg);
gridStateCount = elevationBinCount * azimuthBinCount;
initialNode = nearestFreeGridNode(blockedGrid, ...
    azimuthGrid_deg, elevationGrid_deg, initialPosition_deg, ...
    options.AllowAzimuthWrap);
goalNode = nearestFreeGridNode(blockedGrid, ...
    azimuthGrid_deg, elevationGrid_deg, goalPosition_deg, ...
    options.AllowAzimuthWrap);
if initialNode == 0 || goalNode == 0
    result = emptyGoalDijkstraResult(options);
    result.Message = "No free grid state is available near an endpoint.";
    result.SearchElapsed_s = toc(searchTimer);
    return;
end

costToGoal_deg = inf(gridStateCount, 1);
nextNodeTowardGoal = zeros(gridStateCount, 1, "uint32");
settled = false(gridStateCount, 1);
costToGoal_deg(goalNode) = 0;
nextNodeTowardGoal(goalNode) = uint32(goalNode);
frontier = makeDijkstraFrontier(options.InitialNodeCapacity);
frontier = pushDijkstraFrontier(frontier, goalNode, 0);
expandedNodeCount = 0;
generatedNodeCount = 1;
terminationReason = "";
reachedInitialState = false;
elevationOffset = [-1 -1 -1 0 0 1 1 1];
azimuthOffset = [-1 0 1 -1 1 -1 0 1];

while frontier.Count > 0
    if toc(searchTimer) >= options.MaxSearchTime_s
        terminationReason = "wallTimeLimit";
        break;
    end
    if expandedNodeCount >= options.MaxExpansions
        terminationReason = "expansionLimit";
        break;
    end
    [frontier, currentNode, queuedCost_deg] = ...
        popDijkstraFrontier(frontier);
    if settled(currentNode) || ...
            queuedCost_deg > costToGoal_deg(currentNode) + 1e-12
        continue;
    end
    settled(currentNode) = true;
    expandedNodeCount = expandedNodeCount + 1;
    if currentNode == initialNode
        reachedInitialState = true;
        terminationReason = "goalCostReachedInitialState";
        break;
    end

    [currentElevationIndex, currentAzimuthIndex] = ind2sub( ...
        [elevationBinCount azimuthBinCount], currentNode);
    for neighborDirection = 1:numel(elevationOffset)
        neighborElevationIndex = currentElevationIndex + ...
            elevationOffset(neighborDirection);
        neighborAzimuthIndex = currentAzimuthIndex + ...
            azimuthOffset(neighborDirection);
        if neighborElevationIndex < 1 || ...
                neighborElevationIndex > elevationBinCount
            continue;
        end
        if options.AllowAzimuthWrap
            neighborAzimuthIndex = mod( ...
                neighborAzimuthIndex - 1, azimuthBinCount) + 1;
        elseif neighborAzimuthIndex < 1 || ...
                neighborAzimuthIndex > azimuthBinCount
            continue;
        end
        if blockedGrid(neighborElevationIndex, neighborAzimuthIndex)
            continue;
        end
        if elevationOffset(neighborDirection) ~= 0 && ...
                azimuthOffset(neighborDirection) ~= 0 && ...
                diagonalTransitionIsBlocked(blockedGrid, ...
                currentElevationIndex, currentAzimuthIndex, ...
                neighborElevationIndex, neighborAzimuthIndex, ...
                options.AllowAzimuthWrap)
            continue;
        end

        neighborNode = sub2ind([elevationBinCount azimuthBinCount], ...
            neighborElevationIndex, neighborAzimuthIndex);
        transitionDistance_deg = gridTransitionDistance( ...
            currentNode, neighborNode, azimuthGrid_deg, ...
            elevationGrid_deg, options.AllowAzimuthWrap);
        candidateCost_deg = costToGoal_deg(currentNode) + ...
            transitionDistance_deg;
        if candidateCost_deg >= costToGoal_deg(neighborNode) - 1e-12
            continue;
        end
        costToGoal_deg(neighborNode) = candidateCost_deg;
        nextNodeTowardGoal(neighborNode) = uint32(currentNode);
        frontier = pushDijkstraFrontier( ...
            frontier, neighborNode, candidateCost_deg);
        generatedNodeCount = generatedNodeCount + 1;
    end
end

if ~reachedInitialState
    result = emptyGoalDijkstraResult(options);
    if terminationReason == ""
        terminationReason = "noPath";
        result.Message = "No lattice route connects the endpoints.";
    elseif terminationReason == "wallTimeLimit"
        result.Message = "Dijkstra reached MaxSearchTime_s.";
    else
        result.Message = "Dijkstra reached MaxExpansions.";
    end
    result.ExpandedNodeCount = expandedNodeCount;
    result.GeneratedNodeCount = generatedNodeCount;
    result.SearchElapsed_s = toc(searchTimer);
    result.TerminationReason = terminationReason;
    result.CostToGoal_deg = reshape( ...
        costToGoal_deg, size(blockedGrid));
    result.SettledMask = reshape(settled, size(blockedGrid));
    return;
end

gridNodePath = reconstructGoalDirectedPath( ...
    nextNodeTowardGoal, initialNode, goalNode);
gridPath_deg = gridNodePositions(gridNodePath, ...
    azimuthGrid_deg, elevationGrid_deg, options.AllowAzimuthWrap);
routeStep_deg = diff(gridPath_deg, 1, 1);
result = struct( ...
    "Success", true, ...
    "Message", "Goal-rooted Dijkstra cost reached the initial state.", ...
    "Method", "goalRootedDijkstra", ...
    "Path_deg", gridPath_deg, ...
    "GridNodePath", gridNodePath, ...
    "LatticeDistance_deg", sum(hypot( ...
        routeStep_deg(:, 1), routeStep_deg(:, 2))), ...
    "ExpandedNodeCount", expandedNodeCount, ...
    "GeneratedNodeCount", generatedNodeCount, ...
    "SearchElapsed_s", toc(searchTimer), ...
    "TerminationReason", terminationReason, ...
    "CostToGoal_deg", reshape(costToGoal_deg, size(blockedGrid)), ...
    "SettledMask", reshape(settled, size(blockedGrid)), ...
    "BlockedMask", blockedGrid, ...
    "AzimuthGrid_deg", azimuthGrid_deg, ...
    "ElevationGrid_deg", elevationGrid_deg, ...
    "InitialGridNode", initialNode, ...
    "GoalGridNode", goalNode, ...
    "Options", options);
end

function node = nearestFreeGridNode( ...
        blockedGrid, azimuthGrid_deg, elevationGrid_deg, ...
        requestedPosition_deg, allowAzimuthWrap)
[azimuthMesh_deg, elevationMesh_deg] = meshgrid( ...
    azimuthGrid_deg, elevationGrid_deg);
azimuthDifference_deg = azimuthMesh_deg - requestedPosition_deg(1);
if allowAzimuthWrap
    azimuthSpan_deg = wrappedGridSpan(azimuthGrid_deg);
    azimuthDifference_deg = mod(azimuthDifference_deg + ...
        azimuthSpan_deg / 2, azimuthSpan_deg) - azimuthSpan_deg / 2;
end
distanceSquared_deg2 = azimuthDifference_deg.^2 + ...
    (elevationMesh_deg - requestedPosition_deg(2)).^2;
distanceSquared_deg2(blockedGrid) = Inf;
[nearestDistanceSquared_deg2, node] = min(distanceSquared_deg2(:));
if ~isfinite(nearestDistanceSquared_deg2)
    node = 0;
end
end

function blocked = diagonalTransitionIsBlocked( ...
        blockedGrid, currentElevationIndex, currentAzimuthIndex, ...
        neighborElevationIndex, neighborAzimuthIndex, allowAzimuthWrap)
azimuthBinCount = size(blockedGrid, 2);
firstAzimuthIndex = neighborAzimuthIndex;
secondAzimuthIndex = currentAzimuthIndex;
if allowAzimuthWrap
    firstAzimuthIndex = mod( ...
        firstAzimuthIndex - 1, azimuthBinCount) + 1;
    secondAzimuthIndex = mod( ...
        secondAzimuthIndex - 1, azimuthBinCount) + 1;
end
blocked = blockedGrid(currentElevationIndex, firstAzimuthIndex) || ...
    blockedGrid(neighborElevationIndex, secondAzimuthIndex);
end

function distance_deg = gridTransitionDistance( ...
        firstNode, secondNode, azimuthGrid_deg, ...
        elevationGrid_deg, allowAzimuthWrap)
elevationBinCount = numel(elevationGrid_deg);
azimuthBinCount = numel(azimuthGrid_deg);
[firstElevationIndex, firstAzimuthIndex] = ind2sub( ...
    [elevationBinCount azimuthBinCount], firstNode);
[secondElevationIndex, secondAzimuthIndex] = ind2sub( ...
    [elevationBinCount azimuthBinCount], secondNode);
azimuthDifference_deg = azimuthGrid_deg(secondAzimuthIndex) - ...
    azimuthGrid_deg(firstAzimuthIndex);
if allowAzimuthWrap
    azimuthSpan_deg = wrappedGridSpan(azimuthGrid_deg);
    azimuthDifference_deg = mod(azimuthDifference_deg + ...
        azimuthSpan_deg / 2, azimuthSpan_deg) - azimuthSpan_deg / 2;
end
elevationDifference_deg = elevationGrid_deg(secondElevationIndex) - ...
    elevationGrid_deg(firstElevationIndex);
distance_deg = hypot(azimuthDifference_deg, elevationDifference_deg);
end

function azimuthSpan_deg = wrappedGridSpan(azimuthGrid_deg)
azimuthSpan_deg = azimuthGrid_deg(end) - azimuthGrid_deg(1);
if numel(azimuthGrid_deg) > 1
    azimuthSpan_deg = azimuthSpan_deg + median(diff(azimuthGrid_deg));
end
end

function gridNodePath = reconstructGoalDirectedPath( ...
        nextNodeTowardGoal, initialNode, goalNode)
gridNodePath = zeros(128, 1, "uint32");
pathStateCount = 1;
currentNode = uint32(initialNode);
gridNodePath(pathStateCount) = currentNode;
while currentNode ~= goalNode
    nextNode = nextNodeTowardGoal(currentNode);
    if nextNode == 0
        error("planAzElAdaptiveAStar:BrokenDijkstraSuccessor", ...
            "Dijkstra produced an incomplete goal-directed successor chain.");
    end
    pathStateCount = pathStateCount + 1;
    if pathStateCount > numel(gridNodePath)
        gridNodePath(2 * numel(gridNodePath), 1) = 0;
    end
    gridNodePath(pathStateCount) = nextNode;
    currentNode = nextNode;
end
gridNodePath = gridNodePath(1:pathStateCount);
end

function gridPath_deg = gridNodePositions( ...
        gridNodePath, azimuthGrid_deg, elevationGrid_deg, ...
        allowAzimuthWrap)
elevationBinCount = numel(elevationGrid_deg);
azimuthBinCount = numel(azimuthGrid_deg);
[elevationIndex, azimuthIndex] = ind2sub( ...
    [elevationBinCount azimuthBinCount], double(gridNodePath));
gridPath_deg = [azimuthGrid_deg(azimuthIndex).', ...
    elevationGrid_deg(elevationIndex).'];
if allowAzimuthWrap
    azimuthSpan_deg = wrappedGridSpan(azimuthGrid_deg);
    for pathIndex = 2:size(gridPath_deg, 1)
        azimuthStep_deg = mod(gridPath_deg(pathIndex, 1) - ...
            gridPath_deg(pathIndex - 1, 1) + azimuthSpan_deg / 2, ...
            azimuthSpan_deg) - azimuthSpan_deg / 2;
        gridPath_deg(pathIndex, 1) = ...
            gridPath_deg(pathIndex - 1, 1) + azimuthStep_deg;
    end
end
end

function routePositions_deg = unwrapAndReduceRoute( ...
        routePositions_deg, axisLimits, options)
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(axisLimits.azimuth_deg);
    for waypointIndex = 2:size(routePositions_deg, 1)
        azimuthStep_deg = mod(routePositions_deg(waypointIndex, 1) - ...
            routePositions_deg(waypointIndex - 1, 1) + ...
            azimuthSpan_deg / 2, azimuthSpan_deg) - azimuthSpan_deg / 2;
        routePositions_deg(waypointIndex, 1) = ...
            routePositions_deg(waypointIndex - 1, 1) + azimuthStep_deg;
    end
end
keepWaypoint = true(size(routePositions_deg, 1), 1);
keepWaypoint(2:end) = hypot( ...
    diff(routePositions_deg(:, 1)), ...
    diff(routePositions_deg(:, 2))) > 1e-10;
routePositions_deg = routePositions_deg(keepWaypoint, :);
end

function shortcut = shortcutStaticRoute( ...
        workspace, routePositions_deg, queryTime_s, axisLimits, options)
shortcutTimer = tic;
inputWaypointCount = size(routePositions_deg, 1);
if inputWaypointCount <= 2
    shortcut = successfulShortcut( ...
        routePositions_deg, inputWaypointCount, 0, toc(shortcutTimer));
    return;
end

retainedRoute_deg = zeros(size(routePositions_deg));
retainedWaypointCount = 1;
retainedRoute_deg(1, :) = routePositions_deg(1, :);
currentWaypointIndex = 1;
collisionCheckCount = 0;
while currentWaypointIndex < inputWaypointCount
    farthestVisibleIndex = currentWaypointIndex;
    candidateWaypointIndex = currentWaypointIndex + 1;
    while candidateWaypointIndex <= inputWaypointCount
        collisionCheckCount = collisionCheckCount + 1;
        visible = staticSegmentIsFree(workspace, ...
            routePositions_deg(currentWaypointIndex, :), ...
            routePositions_deg(candidateWaypointIndex, :), ...
            queryTime_s, axisLimits, options);
        if ~visible
            break;
        end
        farthestVisibleIndex = candidateWaypointIndex;
        candidateWaypointIndex = candidateWaypointIndex + 1;
    end
    if farthestVisibleIndex == currentWaypointIndex
        shortcut = struct( ...
            "Success", false, ...
            "Message", "An adjacent lattice edge failed exact validation.", ...
            "Path_deg", zeros(0, 2), ...
            "RouteDistance_deg", Inf, ...
            "InputWaypointCount", inputWaypointCount, ...
            "OutputWaypointCount", 0, ...
            "CollisionCheckCount", collisionCheckCount, ...
            "Elapsed_s", toc(shortcutTimer));
        return;
    end
    retainedWaypointCount = retainedWaypointCount + 1;
    retainedRoute_deg(retainedWaypointCount, :) = ...
        routePositions_deg(farthestVisibleIndex, :);
    currentWaypointIndex = farthestVisibleIndex;
end
retainedRoute_deg = retainedRoute_deg(1:retainedWaypointCount, :);
shortcut = successfulShortcut(retainedRoute_deg, ...
    inputWaypointCount, collisionCheckCount, toc(shortcutTimer));
end

function visible = staticSegmentIsFree( ...
        workspace, firstPosition_deg, secondPosition_deg, ...
        queryTime_s, axisLimits, options)
segmentDistance_deg = hypot( ...
    secondPosition_deg(1) - firstPosition_deg(1), ...
    secondPosition_deg(2) - firstPosition_deg(2));
sampleCount = max(2, ...
    ceil(segmentDistance_deg / options.RouteShortcutStep_deg) + 1);
segmentFraction = linspace(0, 1, sampleCount).';
queryPosition_deg = firstPosition_deg + ...
    segmentFraction .* (secondPosition_deg - firstPosition_deg);
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(axisLimits.azimuth_deg);
    queryPosition_deg(:, 1) = mod(queryPosition_deg(:, 1) - ...
        axisLimits.azimuth_deg(1), azimuthSpan_deg) + ...
        axisLimits.azimuth_deg(1);
end
blocked = queryAzElTimeObstacle(workspace, ...
    queryPosition_deg(:, 1), queryPosition_deg(:, 2), queryTime_s, ...
    struct("CollisionMode", "polygon", ...
    "SafetyMarginDeg", options.SafetyMargin_deg));
visible = ~any(blocked);
end

function shortcut = successfulShortcut( ...
        routePositions_deg, inputWaypointCount, ...
        collisionCheckCount, elapsed_s)
routeStep_deg = diff(routePositions_deg, 1, 1);
shortcut = struct( ...
    "Success", true, ...
    "Message", "Exact visibility shortcutting complete.", ...
    "Path_deg", routePositions_deg, ...
    "RouteDistance_deg", sum(hypot( ...
        routeStep_deg(:, 1), routeStep_deg(:, 2))), ...
    "InputWaypointCount", inputWaypointCount, ...
    "OutputWaypointCount", size(routePositions_deg, 1), ...
    "CollisionCheckCount", collisionCheckCount, ...
    "Elapsed_s", elapsed_s);
end

function retimed = retimeStaticRoute( ...
        workspace, routePositions_deg, initialState, goalState, ...
        axisLimits, options)
retimingTimer = tic;
segmentDisplacement_deg = diff(routePositions_deg, 1, 1);
[segmentDuration_s, normalizedPeakRate, normalizedAcceleration] = ...
    segmentMotionParameters(segmentDisplacement_deg.', axisLimits);
minimumManeuverTime_s = sum(segmentDuration_s);
availableManeuverTime_s = goalState.time_s - initialState.time_s;
if minimumManeuverTime_s > availableManeuverTime_s + 1e-9
    retimed = failedRetiming(sprintf( ...
        "Route needs %.3f s but only %.3f s is available.", ...
        minimumManeuverTime_s, availableManeuverTime_s), ...
        toc(retimingTimer));
    return;
end

segmentInitialTime_s = initialState.time_s + ...
    [0, cumsum(segmentDuration_s(1:end - 1))];
profile = makeStaticRouteProfile(initialState.time_s, ...
    goalState.time_s, routePositions_deg, segmentDisplacement_deg, ...
    segmentInitialTime_s, segmentDuration_s, normalizedPeakRate, ...
    normalizedAcceleration, options.SampleTime_s, axisLimits, options);
maximumRate_deg_s = max(axisLimits.maxVelocity_deg_s);
gridCollisionStep_s = options.GridStep_deg / maximumRate_deg_s / 4;
collisionSampleStep_s = min([options.SampleTime_s, ...
    options.CollisionCheckStep_s, gridCollisionStep_s]);
validationProfile = makeStaticRouteProfile(initialState.time_s, ...
    goalState.time_s, routePositions_deg, segmentDisplacement_deg, ...
    segmentInitialTime_s, segmentDuration_s, normalizedPeakRate, ...
    normalizedAcceleration, collisionSampleStep_s, axisLimits, options);
blocked = queryAzElTimeObstacle(workspace, ...
    validationProfile.position_deg(:, 1), ...
    validationProfile.position_deg(:, 2), ...
    validationProfile.time_s, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
if any(blocked)
    retimed = failedRetiming( ...
        "The retimed route intersects the exact packed workspace.", ...
        toc(retimingTimer));
    return;
end

routeStep_deg = diff(routePositions_deg, 1, 1);
retimed = struct( ...
    "Success", true, ...
    "Message", "Static route satisfies timing and exact collision checks.", ...
    "Profile", profile, ...
    "RouteDistance_deg", sum(hypot( ...
        routeStep_deg(:, 1), routeStep_deg(:, 2))), ...
    "MinimumManeuverTime_s", minimumManeuverTime_s, ...
    "SegmentDuration_s", segmentDuration_s, ...
    "SegmentInitialTime_s", segmentInitialTime_s, ...
    "RoutePositions_deg", routePositions_deg, ...
    "SearchElapsed_s", toc(retimingTimer));
end

function profile = makeStaticRouteProfile( ...
        initialTime_s, goalTime_s, routePositions_deg, ...
        segmentDisplacement_deg, segmentInitialTime_s, ...
        segmentDuration_s, normalizedPeakRate, ...
        normalizedAcceleration, sampleTime_s, axisLimits, options)
time_s = (initialTime_s:sampleTime_s:goalTime_s).';
if time_s(end) < goalTime_s
    time_s(end + 1, 1) = goalTime_s;
end
[segmentProgress, segmentRate, segmentAcceleration] = ...
    evaluateSegmentMotion(time_s, segmentInitialTime_s, ...
    segmentDuration_s, normalizedPeakRate, normalizedAcceleration);
positionUnwrapped_deg = routePositions_deg(1, :) + ...
    segmentProgress * segmentDisplacement_deg;
velocity_deg_s = segmentRate * segmentDisplacement_deg;
acceleration_deg_s2 = ...
    segmentAcceleration * segmentDisplacement_deg;
position_deg = positionUnwrapped_deg;
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(axisLimits.azimuth_deg);
    position_deg(:, 1) = mod(position_deg(:, 1) - ...
        axisLimits.azimuth_deg(1), azimuthSpan_deg) + ...
        axisLimits.azimuth_deg(1);
end
acceleration_deg_s2([1 end], :) = 0;
profile = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "positionUnwrapped_deg", positionUnwrapped_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "isWaiting", all(abs(velocity_deg_s) <= 1e-10, 2) & ...
        all(abs(acceleration_deg_s2) <= 1e-10, 2));
end

function [segmentProgress, segmentRate, segmentAcceleration] = ...
        evaluateSegmentMotion(time_s, segmentInitialTime_s, ...
        segmentDuration_s, normalizedPeakRate, normalizedAcceleration)
elapsedSegmentTime_s = time_s - segmentInitialTime_s;
accelerationDuration_s = ...
    normalizedPeakRate ./ normalizedAcceleration;
accelerationDistance = 0.5 .* normalizedAcceleration .* ...
    accelerationDuration_s.^2;
cruiseDuration_s = max(0, ...
    segmentDuration_s - 2 .* accelerationDuration_s);
segmentProgress = zeros(size(elapsedSegmentTime_s));
segmentRate = zeros(size(elapsedSegmentTime_s));
segmentAcceleration = zeros(size(elapsedSegmentTime_s));

accelerationMatrix = repmat( ...
    normalizedAcceleration, numel(time_s), 1);
accelerationDurationMatrix_s = repmat( ...
    accelerationDuration_s, numel(time_s), 1);
accelerationDistanceMatrix = repmat( ...
    accelerationDistance, numel(time_s), 1);
peakRateMatrix = repmat(normalizedPeakRate, numel(time_s), 1);
segmentDurationMatrix_s = repmat( ...
    segmentDuration_s, numel(time_s), 1);

accelerating = elapsedSegmentTime_s > 0 & ...
    elapsedSegmentTime_s < accelerationDuration_s;
segmentProgress(accelerating) = 0.5 .* ...
    accelerationMatrix(accelerating) .* ...
    elapsedSegmentTime_s(accelerating).^2;
segmentRate(accelerating) = accelerationMatrix(accelerating) .* ...
    elapsedSegmentTime_s(accelerating);
segmentAcceleration(accelerating) = accelerationMatrix(accelerating);

cruising = elapsedSegmentTime_s >= accelerationDuration_s & ...
    elapsedSegmentTime_s < accelerationDuration_s + cruiseDuration_s;
segmentProgress(cruising) = accelerationDistanceMatrix(cruising) + ...
    peakRateMatrix(cruising) .* ...
    (elapsedSegmentTime_s(cruising) - ...
    accelerationDurationMatrix_s(cruising));
segmentRate(cruising) = peakRateMatrix(cruising);

decelerating = elapsedSegmentTime_s >= ...
    accelerationDuration_s + cruiseDuration_s & ...
    elapsedSegmentTime_s < segmentDuration_s;
remainingSegmentTime_s = ...
    segmentDurationMatrix_s - elapsedSegmentTime_s;
segmentProgress(decelerating) = 1 - 0.5 .* ...
    accelerationMatrix(decelerating) .* ...
    remainingSegmentTime_s(decelerating).^2;
segmentRate(decelerating) = accelerationMatrix(decelerating) .* ...
    remainingSegmentTime_s(decelerating);
segmentAcceleration(decelerating) = -accelerationMatrix(decelerating);
segmentProgress(elapsedSegmentTime_s >= segmentDuration_s) = 1;
end

function [segmentDuration_s, normalizedPeakRate, ...
        normalizedAcceleration] = ...
        segmentMotionParameters(segmentDisplacement_deg, axisLimits)
absoluteDisplacement_deg = abs(segmentDisplacement_deg);
rateScaleCandidate = inf(size(segmentDisplacement_deg));
accelerationScaleCandidate = inf(size(segmentDisplacement_deg));
movingAxis = absoluteDisplacement_deg > 1e-12;
rateLimit_deg_s = axisLimits.maxVelocity_deg_s(:);
accelerationLimit_deg_s2 = axisLimits.maxAcceleration_deg_s2(:);
for axisIndex = 1:2
    activeSegment = movingAxis(axisIndex, :);
    rateScaleCandidate(axisIndex, activeSegment) = ...
        rateLimit_deg_s(axisIndex) ./ ...
        absoluteDisplacement_deg(axisIndex, activeSegment);
    accelerationScaleCandidate(axisIndex, activeSegment) = ...
        accelerationLimit_deg_s2(axisIndex) ./ ...
        absoluteDisplacement_deg(axisIndex, activeSegment);
end
normalizedRateLimit = min(rateScaleCandidate, [], 1);
normalizedAcceleration = min(accelerationScaleCandidate, [], 1);
stationarySegment = ~isfinite(normalizedRateLimit);
normalizedRateLimit(stationarySegment) = 0;
normalizedAcceleration(stationarySegment) = 1;

triangularProfile = ...
    normalizedRateLimit.^2 ./ normalizedAcceleration >= 1;
accelerationDuration_s = ...
    normalizedRateLimit ./ normalizedAcceleration;
accelerationDuration_s(triangularProfile) = ...
    sqrt(1 ./ normalizedAcceleration(triangularProfile));
normalizedPeakRate = normalizedAcceleration .* accelerationDuration_s;
accelerationDistance = ...
    normalizedAcceleration .* accelerationDuration_s.^2;
cruiseDuration_s = zeros(size(normalizedRateLimit));
cruisingProfile = ~triangularProfile & ~stationarySegment;
cruiseDuration_s(cruisingProfile) = ...
    (1 - accelerationDistance(cruisingProfile)) ./ ...
    normalizedPeakRate(cruisingProfile);
segmentDuration_s = 2 .* accelerationDuration_s + cruiseDuration_s;
segmentDuration_s(stationarySegment) = 0;
end

function retimed = failedRetiming(message, elapsed_s)
retimed = struct( ...
    "Success", false, ...
    "Message", string(message), ...
    "Profile", struct(), ...
    "RouteDistance_deg", Inf, ...
    "MinimumManeuverTime_s", Inf, ...
    "SegmentDuration_s", zeros(1, 0), ...
    "SegmentInitialTime_s", zeros(1, 0), ...
    "RoutePositions_deg", zeros(0, 2), ...
    "SearchElapsed_s", elapsed_s);
end

function plan = failedStaticPlan( ...
        message, workspace, initialState, goalState, axisLimits, ...
        options, topology, elapsed_s)
plan = struct( ...
    "success", false, ...
    "message", string(message), ...
    "method", "goalRootedDijkstra", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "positionUnwrapped_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "isWaiting", false(0, 1), ...
    "cost_s", Inf, ...
    "objective", options.Objective, ...
    "objectiveCost", Inf, ...
    "objectiveCostUnits", "deg", ...
    "angularPathLength_deg", Inf, ...
    "angularLowerBound_deg", NaN, ...
    "suboptimalityBound", Inf, ...
    "optimalOnLattice", false, ...
    "topologyOptimalOnLattice", false, ...
    "optimalGlobally", false, ...
    "exactCollisionValidated", false, ...
    "expandedNodeCount", topology.ExpandedNodeCount, ...
    "generatedNodeCount", topology.GeneratedNodeCount, ...
    "searchElapsed_s", elapsed_s, ...
    "selectedGridStep_deg", options.GridStep_deg, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", axisLimits, ...
    "options", options, ...
    "workspace", workspace, ...
    "topologySearch", topology);
end

function result = emptyGoalDijkstraResult(options)
result = struct( ...
    "Success", false, ...
    "Message", "Goal-rooted Dijkstra did not run.", ...
    "Method", "goalRootedDijkstra", ...
    "Path_deg", zeros(0, 2), ...
    "GridNodePath", zeros(0, 1, "uint32"), ...
    "LatticeDistance_deg", Inf, ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0, ...
    "TerminationReason", "notRun", ...
    "CostToGoal_deg", zeros(0, 0), ...
    "SettledMask", false(0, 0), ...
    "BlockedMask", false(0, 0), ...
    "AzimuthGrid_deg", zeros(1, 0), ...
    "ElevationGrid_deg", zeros(1, 0), ...
    "InitialGridNode", 0, ...
    "GoalGridNode", 0, ...
    "Options", options);
end

function frontier = makeDijkstraFrontier(initialCapacity)
frontier = struct( ...
    "Node", zeros(initialCapacity, 1, "uint32"), ...
    "Cost_deg", inf(initialCapacity, 1), ...
    "Serial", zeros(initialCapacity, 1, "uint64"), ...
    "Count", 0, ...
    "NextSerial", uint64(0));
end

function frontier = pushDijkstraFrontier(frontier, node, cost_deg)
if frontier.Count >= numel(frontier.Node)
    previousCapacity = numel(frontier.Node);
    expandedCapacity = 2 * previousCapacity;
    frontier.Node(expandedCapacity, 1) = 0;
    frontier.Cost_deg(previousCapacity + 1:expandedCapacity, 1) = Inf;
    frontier.Serial(previousCapacity + 1:expandedCapacity, 1) = 0;
end
frontier.Count = frontier.Count + 1;
frontier.NextSerial = frontier.NextSerial + 1;
heapIndex = frontier.Count;
frontier.Node(heapIndex) = uint32(node);
frontier.Cost_deg(heapIndex) = cost_deg;
frontier.Serial(heapIndex) = frontier.NextSerial;
while heapIndex > 1
    parentIndex = floor(heapIndex / 2);
    if ~dijkstraFrontierEntryIsLess( ...
            frontier, heapIndex, parentIndex)
        break;
    end
    frontier = swapDijkstraFrontierEntries( ...
        frontier, heapIndex, parentIndex);
    heapIndex = parentIndex;
end
end

function [frontier, node, cost_deg] = popDijkstraFrontier(frontier)
node = double(frontier.Node(1));
cost_deg = frontier.Cost_deg(1);
frontier.Node(1) = frontier.Node(frontier.Count);
frontier.Cost_deg(1) = frontier.Cost_deg(frontier.Count);
frontier.Serial(1) = frontier.Serial(frontier.Count);
frontier.Count = frontier.Count - 1;
heapIndex = 1;
while true
    leftChildIndex = 2 * heapIndex;
    rightChildIndex = leftChildIndex + 1;
    if leftChildIndex > frontier.Count
        break;
    end
    smallerChildIndex = leftChildIndex;
    if rightChildIndex <= frontier.Count && ...
            dijkstraFrontierEntryIsLess( ...
            frontier, rightChildIndex, leftChildIndex)
        smallerChildIndex = rightChildIndex;
    end
    if ~dijkstraFrontierEntryIsLess( ...
            frontier, smallerChildIndex, heapIndex)
        break;
    end
    frontier = swapDijkstraFrontierEntries( ...
        frontier, smallerChildIndex, heapIndex);
    heapIndex = smallerChildIndex;
end
end

function less = dijkstraFrontierEntryIsLess( ...
        frontier, firstIndex, secondIndex)
costTolerance_deg = 1e-12;
if frontier.Cost_deg(firstIndex) < ...
        frontier.Cost_deg(secondIndex) - costTolerance_deg
    less = true;
elseif frontier.Cost_deg(firstIndex) > ...
        frontier.Cost_deg(secondIndex) + costTolerance_deg
    less = false;
else
    less = frontier.Serial(firstIndex) < frontier.Serial(secondIndex);
end
end

function frontier = swapDijkstraFrontierEntries( ...
        frontier, firstIndex, secondIndex)
fields = ["Node", "Cost_deg", "Serial"];
for fieldName = fields
    temporaryValue = frontier.(fieldName)(firstIndex);
    frontier.(fieldName)(firstIndex) = ...
        frontier.(fieldName)(secondIndex);
    frontier.(fieldName)(secondIndex) = temporaryValue;
end
end

function [time_s, position_deg, cost] = ...
        dynamicCandidateTrace(candidate, options)
if ~candidate.Success
    time_s = zeros(0, 1);
    position_deg = zeros(0, 2);
    cost = Inf;
    return;
end
time_s = candidate.Profile.time_s;
position_deg = candidate.Profile.position_deg;
if options.Objective == "minimumAngularDistance"
    cost = candidate.Route.angularPathLength_deg;
else
    cost = candidate.Route.arrivalTime_s(end);
end
end

function plan = failedPlan(message, workspace, initialState, goalState, ...
        limits, options, attempts, search, elapsed)
plan = struct( ...
    "success", false, ...
    "message", string(message), ...
    "method", "progressiveSafeIntervalAStar", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "positionUnwrapped_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "isWaiting", false(0, 1), ...
    "cost_s", Inf, ...
    "objective", options.Objective, ...
    "objectiveCost", Inf, ...
    "objectiveCostUnits", "", ...
    "angularPathLength_deg", Inf, ...
    "angularLowerBound_deg", NaN, ...
    "suboptimalityBound", Inf, ...
    "optimalOnLattice", false, ...
    "optimalGlobally", false, ...
    "exactCollisionValidated", false, ...
    "expandedNodeCount", sum([attempts.ExpandedNodeCount]), ...
    "generatedNodeCount", sum([attempts.GeneratedNodeCount]), ...
    "searchElapsed_s", elapsed, ...
    "selectedGridStep_deg", NaN, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "resolutionAttempts", attempts, ...
    "safeIntervalSearch", search);
end

function delta = wrappedDelta(first, second, limits, options)
delta = second - first;
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    delta(1) = mod(delta(1) + span / 2, span) - span / 2;
end
end

function [initialState, goalState, limits, options] = ...
        normalizeAdaptiveAStarInputs( ...
        initialState, goalState, limits, options)
explicitGraph = isstruct(options) && ...
    isfield(options, "GridStep_deg") && ...
    ~isempty(options.GridStep_deg) && ...
    isfield(options, "PrimitiveRadii_deg") && ...
    ~isempty(options.PrimitiveRadii_deg);
requiredState = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
initialState = normalizeState( ...
    initialState, "initialState", requiredState);
goalState = normalizeState(goalState, "goalState", requiredState);
if goalState.time_s <= initialState.time_s
    error("planAzElAdaptiveAStar:InvalidTime", ...
        "goalState.time_s must follow initialState.time_s.");
end

requiredLimits = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
if ~isstruct(limits) || ~isscalar(limits) || ...
        ~all(isfield(limits, cellstr(requiredLimits)))
    error("planAzElAdaptiveAStar:InvalidLimits", ...
        "limits is missing a required field.");
end
for name = requiredLimits
    validateattributes(limits.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    limits.(name) = reshape(double(limits.(name)), 1, 2);
end
if any(diff(limits.azimuth_deg) <= 0) || ...
        any(diff(limits.elevation_deg) <= 0) || ...
        any(limits.maxVelocity_deg_s <= 0) || ...
        any(limits.maxAcceleration_deg_s2 <= 0)
    error("planAzElAdaptiveAStar:InvalidLimits", ...
        "Limit ranges must increase and dynamic limits must be positive.");
end

defaults = struct( ...
    "SampleTime_s", 0.5, ...
    "ValidationStep_s", [], ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", [], ...
    "PrimitiveRadii_deg", [], ...
    "PrimitiveRadiusMultipliers", [1 2 4 8], ...
    "DirectionStep_deg", 45, ...
    "DirectionAngles_deg", [], ...
    "HeuristicWeight", 1, ...
    "CollisionCheckStep_s", [], ...
    "MaximumSafeIntervalSamples", 10000, ...
    "MaximumDepartureTrials", 64, ...
    "DepartureBatchSize", 8, ...
    "MaxExpansions", 100000, ...
    "MaxSearchTime_s", 45, ...
    "InitialNodeCapacity", 4096, ...
    "TimePaddingSamples", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", diff(limits.azimuth_deg) >= 360 - 1e-9, ...
    "AllowNonzeroTerminalState", false, ...
    "PrintFailureSuggestions", true, ...
    "Objective", "minimumAngularDistance", ...
    "RouteShortcutStep_deg", 0.1, ...
    "MaximumVerticesPerRegion", 500);
options = applyDefaults(options, defaults);

finest = options.GridStep_deg;
if isempty(options.GridStepSchedule_deg)
    if explicitGraph
        options.GridStepSchedule_deg = finest;
    else
        options.GridStepSchedule_deg = unique( ...
            [4 * finest, 2 * finest, finest], "stable");
    end
end
options.GridStepSchedule_deg = ...
    unique(double(options.GridStepSchedule_deg(:).'), "stable");
options.GridStepSchedule_deg = ...
    sort(options.GridStepSchedule_deg, "descend");
if isempty(options.ValidationStep_s)
    options.ValidationStep_s = min( ...
        options.SampleTime_s, finest / ...
        max(limits.maxVelocity_deg_s) / 8);
end
if isempty(options.CollisionCheckStep_s)
    options.CollisionCheckStep_s = options.ValidationStep_s;
end

positive = ["SampleTime_s", "ValidationStep_s", ...
    "GridStep_deg", "CollisionCheckStep_s", ...
    "DirectionStep_deg", "HeuristicWeight", "MaxSearchTime_s", ...
    "RouteShortcutStep_deg"];
for name = positive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.GridStepSchedule_deg, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
validateattributes(options.PrimitiveRadiusMultipliers, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
if ~isempty(options.PrimitiveRadii_deg)
    validateattributes(options.PrimitiveRadii_deg, {'numeric'}, ...
        {'vector', 'real', 'finite', 'positive'});
    options.PrimitiveRadii_deg = ...
        unique(double(options.PrimitiveRadii_deg(:).'));
end
integerPositive = ["MaximumSafeIntervalSamples", ...
    "MaximumDepartureTrials", "DepartureBatchSize", ...
    "MaxExpansions", "InitialNodeCapacity"];
for name = integerPositive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'integer', 'positive'});
end
validateattributes(options.TimePaddingSamples, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
if ~isempty(options.DirectionAngles_deg)
    validateattributes(options.DirectionAngles_deg, {'numeric'}, ...
        {'vector', 'real', 'finite'});
end
validateattributes(options.AllowAzimuthWrap, ...
    {'logical', 'numeric'}, {'scalar'});
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);
validateattributes(options.AllowNonzeroTerminalState, ...
    {'logical', 'numeric'}, {'scalar'});
options.AllowNonzeroTerminalState = ...
    logical(options.AllowNonzeroTerminalState);
validateattributes(options.PrintFailureSuggestions, ...
    {'logical', 'numeric'}, {'scalar'});
options.PrintFailureSuggestions = ...
    logical(options.PrintFailureSuggestions);
if options.AllowAzimuthWrap && ...
        abs(diff(limits.azimuth_deg) - 360) > 1e-6
    error("planAzElAdaptiveAStar:InvalidWrapLimits", ...
        "Wrapped azimuth limits must span exactly 360 degrees.");
end

objective = lower(strtrim(string(options.Objective)));
if any(objective == ["minimumangulardistance", ...
        "angulardistance", "distance"])
    options.Objective = "minimumAngularDistance";
elseif any(objective == ["minimumtime", "time"])
    options.Objective = "minimumTime";
else
    error("planAzElAdaptiveAStar:InvalidObjective", ...
        "Objective must be minimumAngularDistance or minimumTime.");
end
end

function state = normalizeState(state, label, requiredState)
if ~isstruct(state) || ~isscalar(state) || ...
        ~all(isfield(state, cellstr(requiredState)))
    error("planAzElAdaptiveAStar:InvalidState", ...
        "%s is missing a required field.", label);
end
validateattributes(state.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
for name = requiredState(2:end)
    validateattributes(state.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    state.(name) = reshape(double(state.(name)), 1, 2);
end
state.time_s = double(state.time_s);
end

function output = applyDefaults(input, defaults)
if ~isstruct(input) || ~isscalar(input)
    error("planAzElAdaptiveAStar:InvalidOptions", ...
        "options must be a scalar struct.");
end
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
