function plan = planAzElBidirectionalKinodynamicRRTStar( ...
        azElData, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   plan = planAzElBidirectionalKinodynamicRRTStar( ...
%       azElData, initialState, goalState, limits)
%   plan = planAzElBidirectionalKinodynamicRRTStar( ...
%       azElData, initialState, goalState, limits, options)
%   options = planAzElBidirectionalKinodynamicRRTStar(limits, "defaults")
%**************************************************************************
% PURPOSE
%   - Grow one fixed-time RRT* tree forward from the initial state and one
%     backward from the goal state.
%   - Join zero-rate nodes with synchronized quintic wait-and-slew edges
%     that obey axis rate, acceleration, and polygon-collision limits.
%   - Minimize angular path length through parent selection and rewiring.
%     A finite sampling run does not guarantee feasibility or optimality.
%**************************************************************************
% INPUTS
%   - azElData (canonical obstacle data, packed obstacle field, or limits)
%       Canonical input or a packed field for planning. In the defaults
%       call form, this argument is the limits structure.
%   - initialState (scalar struct or "defaults")
%       Fields: time_s, position_deg, velocity_deg_s, and
%       acceleration_deg_s2. RRT* currently requires zero boundary rates
%       and accelerations.
%   - goalState (scalar struct)
%       Same fields as initialState; time_s must be later.
%   - limits (scalar struct)
%       Fields: azimuth_deg, elevation_deg, maxVelocity_deg_s, and
%       maxAcceleration_deg_s2.
%   - options (scalar struct, optional)
%       Partial options. Use the defaults call form for the full schema.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       A stable success/failure schema containing the sampled command,
%       validation evidence, resolved options, and both retained trees.
%       obstacleField is preferred; workspace is a deprecated alias.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Validate Inputs & Apply Defaults
defaultsWereRequested = nargin == 2 && ...
    (ischar(initialState) || ...
    (isstring(initialState) && isscalar(initialState))) && ...
    strcmpi(string(initialState), "defaults");
if defaultsWereRequested
    plan = defaultBidirectionalRRTStarOptions(azElData);
    return;
end
narginchk(4, 5);
plannerTimer = tic;
if nargin < 5
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error("planAzElBidirectionalKinodynamicRRTStar:InvalidOptions", ...
        "options must be a scalar structure.");
end
stateDefaults = struct( ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stateDefaultNames = string(fieldnames(stateDefaults)).';
for stateDefaultName = stateDefaultNames
    if ~isfield(initialState, stateDefaultName)
        initialState.(stateDefaultName) = stateDefaults.(stateDefaultName);
    end
    if ~isfield(goalState, stateDefaultName)
        goalState.(stateDefaultName) = stateDefaults.(stateDefaultName);
    end
end
requiredStateFields = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
for requiredStateField = requiredStateFields
    validateattributes(initialState.(requiredStateField), {'numeric'}, ...
        {'real', 'finite'});
    validateattributes(goalState.(requiredStateField), {'numeric'}, ...
        {'real', 'finite'});
end
initialState.position_deg = reshape(double(initialState.position_deg), 1, 2);
goalState.position_deg = reshape(double(goalState.position_deg), 1, 2);
initialState.velocity_deg_s = reshape( ...
    double(initialState.velocity_deg_s), 1, 2);
goalState.velocity_deg_s = reshape(double(goalState.velocity_deg_s), 1, 2);
initialState.acceleration_deg_s2 = reshape( ...
    double(initialState.acceleration_deg_s2), 1, 2);
goalState.acceleration_deg_s2 = reshape( ...
    double(goalState.acceleration_deg_s2), 1, 2);
if goalState.time_s <= initialState.time_s
    error("planAzElBidirectionalKinodynamicRRTStar:TimeOrder", ...
        "goalState.time_s must be later than initialState.time_s.");
end

limitFields = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
for limitField = limitFields
    validateattributes(limits.(limitField), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    limits.(limitField) = reshape(double(limits.(limitField)), 1, 2);
end

defaultOptions = defaultBidirectionalRRTStarOptions(limits);
defaultOptionNames = fieldnames(defaultOptions);
providedOptionNames = string(fieldnames(options));
unknownOptionNames = setdiff( ...
    providedOptionNames, string(defaultOptionNames));
if ~isempty(unknownOptionNames)
    warning("planAzElBidirectionalKinodynamicRRTStar:UnknownOptions", ...
        "Ignoring unknown option fields: %s.", ...
        strjoin(unknownOptionNames, ", "));
end
for defaultOptionIndex = 1:numel(defaultOptionNames)
    defaultOptionName = defaultOptionNames{defaultOptionIndex};
    if isfield(options, defaultOptionName) && ...
            ~isempty(options.(defaultOptionName))
        defaultOptions.(defaultOptionName) = options.(defaultOptionName);
    end
end
options = defaultOptions;

positiveOptionNames = ["SampleTime_s", "ValidationStep_s", ...
    "CollisionCheckStep_s", "StepSize_deg", ...
    "MinimumNodeSeparation_deg", "RewireRadius_deg", ...
    "ConnectionRadius_deg", "TimeMetric_deg_s", "MaxSearchTime_s"];
for positiveOptionName = positiveOptionNames
    validateattributes(options.(positiveOptionName), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
integerOptionNames = ["MaximumConnectionTrials", "MaxIterations", ...
    "IterationsAfterFirstSolution", "MaximumVerticesPerRegion"];
for integerOptionName = integerOptionNames
    validateattributes(options.(integerOptionName), {'numeric'}, ...
        {'scalar', 'integer', 'nonnegative'});
end
unboundedNeighborOptions = ["MaximumParentTrials", ...
    "MaximumRewireTrials"];
for unboundedNeighborOption = unboundedNeighborOptions
    neighborLimit = options.(unboundedNeighborOption);
    if ~(isinf(neighborLimit) && neighborLimit > 0)
        validateattributes(neighborLimit, {'numeric'}, ...
            {'scalar', 'integer', 'positive'});
    end
end
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.TimePaddingSamples, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);

if any(abs([initialState.velocity_deg_s, ...
        initialState.acceleration_deg_s2, ...
        goalState.velocity_deg_s, ...
        goalState.acceleration_deg_s2]) > 1e-12)
    error("planAzElBidirectionalKinodynamicRRTStar:BoundaryDynamics", ...
        "This planner currently requires rest initial and goal states.");
end

%% Section 2: Pack The Authoritative Obstacle Field
if isstruct(azElData) && isscalar(azElData) && ...
        isfield(azElData, "Format") && ...
        string(azElData.Format) == "AzElTimeObstacleWorkspace"
    obstacleField = azElData;
else
    obstacleField = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", options.MaximumVerticesPerRegion));
end

previousRandomState = rng;
randomCleanup = onCleanup(@() rng(previousRandomState));
rng(options.RandomSeed, "twister");

%% Section 3: Initialize Both Fixed-Time Trees
maximumNodes = 2 * options.MaxIterations + 4;
forwardTree = initializeTree(initialState, maximumNodes);
backwardTree = initializeTree(goalState, maximumNodes);
bestConnection = struct( ...
    "ForwardIndex", uint32(0), ...
    "BackwardIndex", uint32(0), ...
    "Cost_deg", Inf, ...
    "WaypointPosition_deg", zeros(0, 2), ...
    "WaypointTime_s", zeros(0, 1));
firstSolutionIteration = Inf;
firstSolutionElapsed_s = Inf;

%% Section 4: Check The Direct Global Lower-Bound Trajectory
% A direct wait-and-slew edge is the Euclidean angular lower bound.
if edgeIsValid(initialState.position_deg, initialState.time_s, ...
        goalState.position_deg, goalState.time_s, obstacleField, ...
        limits, options)
    directConnection = struct( ...
        "ForwardIndex", uint32(1), ...
        "BackwardIndex", uint32(1), ...
        "Cost_deg", positionDistance(initialState.position_deg, ...
        goalState.position_deg, limits, options), ...
        "WaypointPosition_deg", zeros(0, 2), ...
        "WaypointTime_s", zeros(0, 1));
    directConnection = freezeValidatedConnection( ...
        directConnection, forwardTree, backwardTree, ...
        obstacleField, limits, options);
    if directConnection.ForwardIndex > 0
        bestConnection = directConnection;
        firstSolutionIteration = 0;
        firstSolutionElapsed_s = toc(plannerTimer);
    end
end

%% Section 5: Grow, Connect & Rewire Both Trees
completedIterations = 0;
for iteration = 1:options.MaxIterations
    if toc(plannerTimer) >= options.MaxSearchTime_s
        break;
    end
    if isfinite(firstSolutionIteration) && ...
            iteration > firstSolutionIteration + ...
            options.IterationsAfterFirstSolution
        break;
    end

    forwardSamplePosition_deg = [ ...
        limits.azimuth_deg(1) + diff(limits.azimuth_deg) * rand, ...
        limits.elevation_deg(1) + diff(limits.elevation_deg) * rand];
    forwardSampleTimeFraction = rand;
    forwardSample = struct( ...
        "Position_deg", forwardSamplePosition_deg, ...
        "Time_s", initialState.time_s + forwardSampleTimeFraction * ...
        (goalState.time_s - initialState.time_s));
    [forwardTree, newForwardIndex] = extendTree( ...
        forwardTree, forwardSample, true, obstacleField, limits, options, ...
        iteration);
    if newForwardIndex > 0
        forwardTree = rewireTree( ...
            forwardTree, newForwardIndex, true, ...
            obstacleField, limits, options);
        laterBackwardNodes = find( ...
            backwardTree.Time_s(1:backwardTree.Count) > ...
            forwardTree.Time_s(double(newForwardIndex)) + 1e-9);
        candidateConnection = bestConnectionForPairSet( ...
            forwardTree, double(newForwardIndex), backwardTree, ...
            laterBackwardNodes, true, obstacleField, limits, options);
        if candidateConnection.Cost_deg < bestConnection.Cost_deg
            candidateConnection = freezeValidatedConnection( ...
                candidateConnection, forwardTree, backwardTree, ...
                obstacleField, limits, options);
            if candidateConnection.Cost_deg < bestConnection.Cost_deg
                bestConnection = candidateConnection;
                if ~isfinite(firstSolutionIteration)
                    firstSolutionIteration = iteration;
                    firstSolutionElapsed_s = toc(plannerTimer);
                end
            end
        end
    end

    backwardSamplePosition_deg = [ ...
        limits.azimuth_deg(1) + diff(limits.azimuth_deg) * rand, ...
        limits.elevation_deg(1) + diff(limits.elevation_deg) * rand];
    backwardSampleTimeFraction = rand;
    backwardSample = struct( ...
        "Position_deg", backwardSamplePosition_deg, ...
        "Time_s", initialState.time_s + backwardSampleTimeFraction * ...
        (goalState.time_s - initialState.time_s));
    [backwardTree, newBackwardIndex] = extendTree( ...
        backwardTree, backwardSample, false, obstacleField, limits, options, ...
        iteration);
    if newBackwardIndex > 0
        backwardTree = rewireTree( ...
            backwardTree, newBackwardIndex, false, ...
            obstacleField, limits, options);
        earlierForwardNodes = find( ...
            forwardTree.Time_s(1:forwardTree.Count) < ...
            backwardTree.Time_s(double(newBackwardIndex)) - 1e-9);
        candidateConnection = bestConnectionForPairSet( ...
            backwardTree, double(newBackwardIndex), forwardTree, ...
            earlierForwardNodes, false, obstacleField, limits, options);
        if candidateConnection.Cost_deg < bestConnection.Cost_deg
            candidateConnection = freezeValidatedConnection( ...
                candidateConnection, forwardTree, backwardTree, ...
                obstacleField, limits, options);
            if candidateConnection.Cost_deg < bestConnection.Cost_deg
                bestConnection = candidateConnection;
                if ~isfinite(firstSolutionIteration)
                    firstSolutionIteration = iteration;
                    firstSolutionElapsed_s = toc(plannerTimer);
                end
            end
        end
    end
    completedIterations = iteration;
end

%% Section 6: Freeze The Retained Tree Diagnostics
forwardTree.Position_deg = forwardTree.Position_deg( ...
    1:forwardTree.Count, :);
forwardTree.Time_s = forwardTree.Time_s(1:forwardTree.Count);
forwardTree.ParentIndex = forwardTree.ParentIndex(1:forwardTree.Count);
forwardTree.Cost_deg = forwardTree.Cost_deg(1:forwardTree.Count);
forwardTree.CreationIteration = forwardTree.CreationIteration( ...
    1:forwardTree.Count);
backwardTree.Position_deg = backwardTree.Position_deg( ...
    1:backwardTree.Count, :);
backwardTree.Time_s = backwardTree.Time_s(1:backwardTree.Count);
backwardTree.ParentIndex = backwardTree.ParentIndex(1:backwardTree.Count);
backwardTree.Cost_deg = backwardTree.Cost_deg(1:backwardTree.Count);
backwardTree.CreationIteration = backwardTree.CreationIteration( ...
    1:backwardTree.Count);
elapsedTime_s = toc(plannerTimer);
if bestConnection.ForwardIndex == 0
    plan = failedPlan(obstacleField, initialState, goalState, limits, ...
        options, forwardTree, backwardTree, completedIterations, ...
        elapsedTime_s, firstSolutionElapsed_s);
    return;
end

%% Section 7: Reconstruct & Independently Validate The Command
waypointPosition_deg = bestConnection.WaypointPosition_deg;
waypointTime_s = bestConnection.WaypointTime_s;
profile = buildProfile(waypointPosition_deg, waypointTime_s, ...
    limits, options, options.SampleTime_s);
validationProfile = buildProfile(waypointPosition_deg, ...
    waypointTime_s, limits, options, options.ValidationStep_s);
blockedValidation = queryAzElTimeObstacle(obstacleField, ...
    validationProfile.position_deg(:, 1), ...
    validationProfile.position_deg(:, 2), ...
    validationProfile.time_s, collisionOptions(options));
if any(blockedValidation)
    plan = failedPlan(obstacleField, initialState, goalState, limits, ...
        options, forwardTree, backwardTree, completedIterations, ...
        elapsedTime_s, firstSolutionElapsed_s);
    plan.message = sprintf( ...
        "RRT* reconstruction contained %d blocked validation samples.", ...
        nnz(blockedValidation));
    plan.blockedValidationSampleCount = nnz(blockedValidation);
    return;
end

segmentDelta_deg = zeros(size(waypointPosition_deg, 1) - 1, 2);
for segmentIndex = 1:size(segmentDelta_deg, 1)
    segmentDelta_deg(segmentIndex, :) = wrappedDelta( ...
        waypointPosition_deg(segmentIndex, :), ...
        waypointPosition_deg(segmentIndex + 1, :), limits, options);
end
angularPathLength_deg = sum(hypot( ...
    segmentDelta_deg(:, 1), segmentDelta_deg(:, 2)));
endpointDelta_deg = wrappedDelta( ...
    initialState.position_deg, goalState.position_deg, limits, options);
angularLowerBound_deg = hypot(endpointDelta_deg(1), endpointDelta_deg(2));
optimalityTolerance_deg = angularLowerBound_deg + 1e-9;
isGloballyOptimal = angularPathLength_deg <= optimalityTolerance_deg;

%% Section 8: Assemble The Public Plan
plan = struct( ...
    "success", true, ...
    "message", ...
    "Bidirectional kinodynamic RRT* found an exact-checked trajectory.", ...
    "method", "bidirectionalKinodynamicRRTStar", ...
    "time_s", profile.time_s, ...
    "position_deg", profile.position_deg, ...
    "positionUnwrapped_deg", profile.positionUnwrapped_deg, ...
    "velocity_deg_s", profile.velocity_deg_s, ...
    "acceleration_deg_s2", profile.acceleration_deg_s2, ...
    "isWaiting", profile.isWaiting, ...
    "cost_s", goalState.time_s - initialState.time_s, ...
    "objective", "minimumAngularDistance", ...
    "objectiveCost", angularPathLength_deg, ...
    "objectiveCostUnits", "deg", ...
    "angularPathLength_deg", angularPathLength_deg, ...
    "angularLowerBound_deg", angularLowerBound_deg, ...
    "suboptimalityBound", max(1, angularPathLength_deg / ...
    max(angularLowerBound_deg, eps)), ...
    "optimalOnLattice", false, ...
    "optimalGlobally", isGloballyOptimal, ...
    "asymptoticallyOptimal", isinf(options.MaximumParentTrials) && ...
    isinf(options.MaximumRewireTrials), ...
    "exactCollisionValidated", true, ...
    "expandedNodeCount", forwardTree.Count + backwardTree.Count - 2, ...
    "generatedNodeCount", forwardTree.Count + backwardTree.Count, ...
    "searchElapsed_s", elapsedTime_s, ...
    "selectedGridStep_deg", NaN, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "obstacleField", obstacleField, ...
    "workspace", obstacleField, ...
    "waypointPosition_deg", waypointPosition_deg, ...
    "waypointTime_s", waypointTime_s, ...
    "blockedValidationSampleCount", 0, ...
    "completedIterations", completedIterations, ...
    "firstSolutionIteration", firstSolutionIteration, ...
    "firstSolutionElapsed_s", firstSolutionElapsed_s, ...
    "forwardTree", forwardTree, ...
    "backwardTree", backwardTree);
end

%% Section 9: Local Functions

function options = defaultBidirectionalRRTStarOptions(limits)
% One default source keeps the defaults request and normal planning aligned.
requiredLimitFields = ["azimuth_deg", "elevation_deg"];
for fieldIndex = 1:numel(requiredLimitFields)
    fieldName = requiredLimitFields(fieldIndex);
    if ~isfield(limits, fieldName)
        error("planAzElBidirectionalKinodynamicRRTStar:MissingLimit", ...
            "limits.%s is required to resolve planner defaults.", fieldName);
    end
end
validateattributes(limits.azimuth_deg, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite'});
allowAzimuthWrap = diff(double(limits.azimuth_deg(:).')) >= 360 - 1e-9;
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.1, ...
    "CollisionCheckStep_s", 0.25, ...
    "SafetyMargin_deg", 0, ...
    "TimePaddingSamples", 1, ...
    "AllowAzimuthWrap", allowAzimuthWrap, ...
    "StepSize_deg", 4, ...
    "MinimumNodeSeparation_deg", 0.1, ...
    "RewireRadius_deg", 7, ...
    "ConnectionRadius_deg", 10, ...
    "TimeMetric_deg_s", 0.2, ...
    "MaximumParentTrials", Inf, ...
    "MaximumRewireTrials", Inf, ...
    "MaximumConnectionTrials", 16, ...
    "MaxIterations", 4000, ...
    "IterationsAfterFirstSolution", 600, ...
    "MaxSearchTime_s", 45, ...
    "RandomSeed", 5489, ...
    "MaximumVerticesPerRegion", 500);
end

function tree = initializeTree(rootState, maximumNodeCount)
% Both trees must share one schema or connection diagnostics become unsafe.
tree = struct( ...
    "Position_deg", zeros(maximumNodeCount, 2), ...
    "Time_s", nan(maximumNodeCount, 1), ...
    "ParentIndex", zeros(maximumNodeCount, 1, "uint32"), ...
    "Cost_deg", inf(maximumNodeCount, 1), ...
    "CreationIteration", zeros(maximumNodeCount, 1, "uint32"), ...
    "Count", 1);
tree.Position_deg(1, :) = rootState.position_deg;
tree.Time_s(1) = rootState.time_s;
tree.Cost_deg(1) = 0;
end

function [tree, newIndex] = extendTree( ...
        tree, sample, forward, obstacleField, limits, options, ...
        creationIteration)
% Forward and backward growth share this logic to preserve time symmetry.
newIndex = uint32(0);
nodeIndices = (1:tree.Count).';
if forward
    temporalCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) < sample.Time_s - 1e-9);
else
    temporalCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) > sample.Time_s + 1e-9);
end
if isempty(temporalCandidates)
    return;
end

sampleDistance_deg = positionDistances( ...
    tree.Position_deg(temporalCandidates, :), ...
    sample.Position_deg, limits, options);
timeDistance_s = abs(tree.Time_s(temporalCandidates) - sample.Time_s);
nearestMetric = hypot(sampleDistance_deg, ...
    options.TimeMetric_deg_s * timeDistance_s);
[~, nearestOffset] = min(nearestMetric);
nearestIndex = temporalCandidates(nearestOffset);
targetDelta_deg = wrappedDelta( ...
    tree.Position_deg(nearestIndex, :), sample.Position_deg, ...
    limits, options);
targetDistance_deg = hypot(targetDelta_deg(1), targetDelta_deg(2));
if targetDistance_deg <= options.MinimumNodeSeparation_deg
    return;
end

availableTime_s = abs(sample.Time_s - tree.Time_s(nearestIndex));
spatialScale = min(1, options.StepSize_deg / targetDistance_deg);
absoluteTargetDelta_deg = abs(targetDelta_deg);
hasMotionByAxis = absoluteTargetDelta_deg > 1e-12;
velocityReachScale = inf(1, 2);
accelerationReachScale = inf(1, 2);
velocityReachScale(hasMotionByAxis) = limits.maxVelocity_deg_s( ...
    hasMotionByAxis) * availableTime_s ./ ...
    (1.875 * absoluteTargetDelta_deg(hasMotionByAxis));
accelerationReachScale(hasMotionByAxis) = limits.maxAcceleration_deg_s2( ...
    hasMotionByAxis) * ...
    availableTime_s^2 ./ ...
    ((10 / sqrt(3)) * absoluteTargetDelta_deg(hasMotionByAxis));
dynamicScale = 0.98 * min([ ...
    1, velocityReachScale, accelerationReachScale]);
candidateDelta_deg = targetDelta_deg * min(spatialScale, dynamicScale);
if hypot(candidateDelta_deg(1), candidateDelta_deg(2)) < ...
        options.MinimumNodeSeparation_deg
    return;
end
candidatePosition_deg = tree.Position_deg(nearestIndex, :) + ...
    candidateDelta_deg;
candidatePosition_deg(1) = canonicalAzimuth( ...
    candidatePosition_deg(1), limits, options);
candidatePosition_deg(2) = min(max(candidatePosition_deg(2), ...
    limits.elevation_deg(1)), limits.elevation_deg(2));
if ~options.AllowAzimuthWrap
    candidatePosition_deg(1) = min(max(candidatePosition_deg(1), ...
        limits.azimuth_deg(1)), limits.azimuth_deg(2));
end
candidateTime_s = sample.Time_s;

allDistances_deg = positionDistances( ...
    tree.Position_deg(nodeIndices, :), candidatePosition_deg, ...
    limits, options);
if forward
    parentCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) < candidateTime_s - 1e-9 & ...
        allDistances_deg <= options.RewireRadius_deg);
else
    parentCandidates = nodeIndices( ...
        tree.Time_s(nodeIndices) > candidateTime_s + 1e-9 & ...
        allDistances_deg <= options.RewireRadius_deg);
end
if ~ismember(nearestIndex, parentCandidates)
    parentCandidates = [nearestIndex; parentCandidates];
end
candidateCosts_deg = tree.Cost_deg(parentCandidates) + ...
    positionDistances(tree.Position_deg(parentCandidates, :), ...
    candidatePosition_deg, limits, options);
[~, parentOrder] = sort(candidateCosts_deg);
parentCandidates = parentCandidates(parentOrder);
parentCandidates = parentCandidates( ...
    1:min(numel(parentCandidates), options.MaximumParentTrials));

bestParentIndex = 0;
bestCost_deg = Inf;
for parentIndex = reshape(parentCandidates, 1, [])
    if forward
        edgeValid = edgeIsValid( ...
            tree.Position_deg(parentIndex, :), tree.Time_s(parentIndex), ...
            candidatePosition_deg, candidateTime_s, ...
            obstacleField, limits, options);
    else
        edgeValid = edgeIsValid( ...
            candidatePosition_deg, candidateTime_s, ...
            tree.Position_deg(parentIndex, :), tree.Time_s(parentIndex), ...
            obstacleField, limits, options);
    end
    if edgeValid
        edgeCost_deg = positionDistance( ...
            tree.Position_deg(parentIndex, :), candidatePosition_deg, ...
            limits, options);
        totalCost_deg = tree.Cost_deg(parentIndex) + edgeCost_deg;
        if totalCost_deg < bestCost_deg
            bestParentIndex = parentIndex;
            bestCost_deg = totalCost_deg;
        end
    end
end
if bestParentIndex == 0
    return;
end

tree.Count = tree.Count + 1;
newIndex = uint32(tree.Count);
tree.Position_deg(tree.Count, :) = candidatePosition_deg;
tree.Time_s(tree.Count) = candidateTime_s;
tree.ParentIndex(tree.Count) = uint32(bestParentIndex);
tree.Cost_deg(tree.Count) = bestCost_deg;
% Failed random samples create no node, so this stamp preserves pauses
% between successful growth events in planning-summary playback.
tree.CreationIteration(tree.Count) = uint32(creationIteration);
end

function tree = rewireTree( ...
        tree, newIndex, forward, obstacleField, limits, options)
% Both trees require identical rewiring and descendant-cost propagation.
newIndex = double(newIndex);
nodeIndices = (2:tree.Count).';
distances_deg = positionDistances(tree.Position_deg(nodeIndices, :), ...
    tree.Position_deg(newIndex, :), limits, options);
if forward
    candidates = nodeIndices( ...
        tree.Time_s(nodeIndices) > tree.Time_s(newIndex) + 1e-9 & ...
        distances_deg <= options.RewireRadius_deg);
else
    candidates = nodeIndices( ...
        tree.Time_s(nodeIndices) < tree.Time_s(newIndex) - 1e-9 & ...
        distances_deg <= options.RewireRadius_deg);
end
[~, order] = sort(distances_deg(ismember(nodeIndices, candidates)));
candidates = candidates(order);
candidates = candidates( ...
    1:min(numel(candidates), options.MaximumRewireTrials));

for candidateIndex = reshape(candidates, 1, [])
    edgeCost_deg = positionDistance( ...
        tree.Position_deg(candidateIndex, :), ...
        tree.Position_deg(newIndex, :), limits, options);
    proposedCost_deg = tree.Cost_deg(newIndex) + edgeCost_deg;
    if proposedCost_deg >= tree.Cost_deg(candidateIndex) - 1e-9
        continue;
    end
    if forward
        edgeValid = edgeIsValid( ...
            tree.Position_deg(newIndex, :), tree.Time_s(newIndex), ...
            tree.Position_deg(candidateIndex, :), ...
            tree.Time_s(candidateIndex), obstacleField, limits, options);
    else
        edgeValid = edgeIsValid( ...
            tree.Position_deg(candidateIndex, :), ...
            tree.Time_s(candidateIndex), ...
            tree.Position_deg(newIndex, :), tree.Time_s(newIndex), ...
            obstacleField, limits, options);
    end
    if ~edgeValid
        continue;
    end
    costReduction_deg = proposedCost_deg - tree.Cost_deg(candidateIndex);
    tree.ParentIndex(candidateIndex) = uint32(newIndex);
    tree.Cost_deg(candidateIndex) = proposedCost_deg;
    % Fixed node times make the edge schedules immutable. Only accumulated
    % angular cost changes, so every descendant receives one common delta.
    descendantQueue = uint32(candidateIndex);
    descendantCursor = 1;
    while descendantCursor <= numel(descendantQueue)
        changedParentIndex = descendantQueue(descendantCursor);
        descendantCursor = descendantCursor + 1;
        childIndices = find( ...
            tree.ParentIndex(1:tree.Count) == changedParentIndex);
        if isempty(childIndices)
            continue;
        end
        tree.Cost_deg(childIndices) = tree.Cost_deg(childIndices) + ...
            costReduction_deg;
        descendantQueue = [ ...
            descendantQueue; uint32(childIndices(:))]; %#ok<AGROW>
    end
end
end

function connection = bestConnectionForPairSet( ...
        sourceTree, sourceIndex, otherTree, candidateIndices, ...
        sourceIsForward, obstacleField, limits, options)
% Both growth directions use one bridge selector to avoid asymmetric tests.
connection = struct( ...
    "ForwardIndex", uint32(0), ...
    "BackwardIndex", uint32(0), ...
    "Cost_deg", Inf, ...
    "WaypointPosition_deg", zeros(0, 2), ...
    "WaypointTime_s", zeros(0, 1));
if isempty(candidateIndices)
    return;
end
distances_deg = positionDistances( ...
    otherTree.Position_deg(candidateIndices, :), ...
    sourceTree.Position_deg(sourceIndex, :), limits, options);
candidateIndices = candidateIndices( ...
    distances_deg <= options.ConnectionRadius_deg);
if isempty(candidateIndices)
    return;
end
totalCosts_deg = sourceTree.Cost_deg(sourceIndex) + ...
    otherTree.Cost_deg(candidateIndices) + ...
    positionDistances(otherTree.Position_deg(candidateIndices, :), ...
    sourceTree.Position_deg(sourceIndex, :), limits, options);
[~, order] = sort(totalCosts_deg);
candidateIndices = candidateIndices(order);
candidateIndices = candidateIndices( ...
    1:min(numel(candidateIndices), options.MaximumConnectionTrials));

for otherIndex = reshape(candidateIndices, 1, [])
    if sourceIsForward
        forwardIndex = sourceIndex;
        backwardIndex = otherIndex;
        edgeValid = edgeIsValid( ...
            sourceTree.Position_deg(sourceIndex, :), ...
            sourceTree.Time_s(sourceIndex), ...
            otherTree.Position_deg(otherIndex, :), ...
            otherTree.Time_s(otherIndex), obstacleField, limits, options);
    else
        forwardIndex = otherIndex;
        backwardIndex = sourceIndex;
        edgeValid = edgeIsValid( ...
            otherTree.Position_deg(otherIndex, :), ...
            otherTree.Time_s(otherIndex), ...
            sourceTree.Position_deg(sourceIndex, :), ...
            sourceTree.Time_s(sourceIndex), obstacleField, limits, options);
    end
    if ~edgeValid
        continue;
    end
    cost_deg = sourceTree.Cost_deg(sourceIndex) + ...
        otherTree.Cost_deg(otherIndex) + positionDistance( ...
        sourceTree.Position_deg(sourceIndex, :), ...
        otherTree.Position_deg(otherIndex, :), limits, options);
    if cost_deg < connection.Cost_deg
        connection.ForwardIndex = uint32(forwardIndex);
        connection.BackwardIndex = uint32(backwardIndex);
        connection.Cost_deg = cost_deg;
    end
end
end

function connection = freezeValidatedConnection( ...
        connection, forwardTree, backwardTree, obstacleField, limits, options)
% Direct and sampled connections must pass the same authoritative validator.
if connection.ForwardIndex == 0
    return;
end
forwardPath = uint32(connection.ForwardIndex);
while forwardTree.ParentIndex(forwardPath(1)) ~= 0
    forwardPath = [ ...
        forwardTree.ParentIndex(forwardPath(1)); forwardPath]; %#ok<AGROW>
end
backwardPath = uint32(connection.BackwardIndex);
while backwardTree.ParentIndex(backwardPath(end)) ~= 0
    nextBackwardNode = backwardTree.ParentIndex(backwardPath(end));
    backwardPath(end + 1, 1) = nextBackwardNode; %#ok<AGROW>
end
waypointPosition_deg = [ ...
    forwardTree.Position_deg(double(forwardPath), :); ...
    backwardTree.Position_deg(double(backwardPath), :)];
waypointTime_s = [ ...
    forwardTree.Time_s(double(forwardPath)); ...
    backwardTree.Time_s(double(backwardPath))];
validationProfile = buildProfile(waypointPosition_deg, ...
    waypointTime_s, limits, options, options.ValidationStep_s);
blocked = queryAzElTimeObstacle(obstacleField, ...
    validationProfile.position_deg(:, 1), ...
    validationProfile.position_deg(:, 2), ...
    validationProfile.time_s, collisionOptions(options));
if any(blocked)
    connection = struct( ...
        "ForwardIndex", uint32(0), ...
        "BackwardIndex", uint32(0), ...
        "Cost_deg", Inf, ...
        "WaypointPosition_deg", zeros(0, 2), ...
        "WaypointTime_s", zeros(0, 1));
    return;
end
segmentCost_deg = 0;
for segmentIndex = 1:size(waypointPosition_deg, 1) - 1
    segmentCost_deg = segmentCost_deg + positionDistance( ...
        waypointPosition_deg(segmentIndex, :), ...
        waypointPosition_deg(segmentIndex + 1, :), limits, options);
end
connection.Cost_deg = segmentCost_deg;
connection.WaypointPosition_deg = waypointPosition_deg;
connection.WaypointTime_s = waypointTime_s;
end

function valid = edgeIsValid( ...
        fromPosition_deg, fromTime_s, toPosition_deg, toTime_s, ...
        obstacleField, limits, options)
% Tree extension, rewiring, and bridging share one dynamic edge invariant.
valid = false;
availableTime_s = toTime_s - fromTime_s;
if availableTime_s <= 1e-9
    return;
end
delta_deg = wrappedDelta( ...
    fromPosition_deg, toPosition_deg, limits, options);
motionDuration_s = minimumQuinticDuration(delta_deg, limits);
if motionDuration_s > availableTime_s + 1e-9
    return;
end
departureTime_s = toTime_s - motionDuration_s;
edgeCheckStep_s = options.CollisionCheckStep_s;
% Use the same segment-anchored samples as final reconstruction, and add
% the departure instant where the stationary wait changes into motion.
queryTimes_s = unique([ ...
    sampledTimes(fromTime_s, toTime_s, edgeCheckStep_s); ...
    departureTime_s]);
normalizedTime = max(0, queryTimes_s - departureTime_s) / ...
    max(motionDuration_s, eps);
normalizedTime = min(normalizedTime, 1);
[progress, ~, ~] = quinticKinematics(normalizedTime, motionDuration_s);
queryPosition_deg = fromPosition_deg + progress .* delta_deg;
queryPosition_deg(:, 1) = canonicalAzimuth( ...
    queryPosition_deg(:, 1), limits, options);
insideLimits = queryPosition_deg(:, 2) >= limits.elevation_deg(1) - ...
    1e-9 & ...
    queryPosition_deg(:, 2) <= limits.elevation_deg(2) + 1e-9;
if ~options.AllowAzimuthWrap
    insideLimits = insideLimits & ...
        queryPosition_deg(:, 1) >= limits.azimuth_deg(1) - 1e-9 & ...
        queryPosition_deg(:, 1) <= limits.azimuth_deg(2) + 1e-9;
end
if ~all(insideLimits)
    return;
end
blocked = queryAzElTimeObstacle(obstacleField, ...
    queryPosition_deg(:, 1), queryPosition_deg(:, 2), ...
    queryTimes_s, collisionOptions(options));
valid = ~any(blocked);
end

function profile = buildProfile( ...
        waypointPosition_deg, waypointTime_s, limits, options, sampleStep_s)
% Candidate validation and public output must reconstruct identical motion.
time_s = zeros(0, 1);
positionUnwrapped_deg = zeros(0, 2);
velocity_deg_s = zeros(0, 2);
acceleration_deg_s2 = zeros(0, 2);
isWaiting = false(0, 1);
unwrappedStart_deg = waypointPosition_deg(1, :);

for segmentIndex = 1:numel(waypointTime_s) - 1
    fromTime_s = waypointTime_s(segmentIndex);
    toTime_s = waypointTime_s(segmentIndex + 1);
    delta_deg = wrappedDelta( ...
        waypointPosition_deg(segmentIndex, :), ...
        waypointPosition_deg(segmentIndex + 1, :), limits, options);
    motionDuration_s = minimumQuinticDuration(delta_deg, limits);
    departureTime_s = toTime_s - motionDuration_s;
    segmentTimes_s = sampledTimes(fromTime_s, toTime_s, sampleStep_s);
    if segmentIndex > 1
        segmentTimes_s = segmentTimes_s(2:end);
    end
    normalizedTime = max(0, segmentTimes_s - departureTime_s) / ...
        max(motionDuration_s, eps);
    normalizedTime = min(normalizedTime, 1);
    [progress, progressRate, progressAcceleration] = quinticKinematics( ...
        normalizedTime, motionDuration_s);
    waiting = segmentTimes_s < departureTime_s - 1e-9 | ...
        motionDuration_s <= 1e-12;

    segmentPosition_deg = unwrappedStart_deg + progress .* delta_deg;
    segmentVelocity_deg_s = progressRate .* delta_deg;
    segmentAcceleration_deg_s2 = progressAcceleration .* delta_deg;
    segmentVelocity_deg_s(waiting, :) = 0;
    segmentAcceleration_deg_s2(waiting, :) = 0;

    time_s = [time_s; segmentTimes_s]; %#ok<AGROW>
    positionUnwrapped_deg = [ ...
        positionUnwrapped_deg; segmentPosition_deg]; %#ok<AGROW>
    velocity_deg_s = [velocity_deg_s; segmentVelocity_deg_s]; %#ok<AGROW>
    acceleration_deg_s2 = [ ...
        acceleration_deg_s2; segmentAcceleration_deg_s2]; %#ok<AGROW>
    isWaiting = [isWaiting; waiting]; %#ok<AGROW>
    unwrappedStart_deg = unwrappedStart_deg + delta_deg;
end

position_deg = positionUnwrapped_deg;
position_deg(:, 1) = canonicalAzimuth( ...
    position_deg(:, 1), limits, options);
profile = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "positionUnwrapped_deg", positionUnwrapped_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "isWaiting", isWaiting);
end

function duration_s = minimumQuinticDuration(delta_deg, limits)
% Search and reconstruction share this bound so no edge changes duration.
absoluteDelta_deg = abs(delta_deg);
velocityDuration_s = 1.875 * absoluteDelta_deg ./ ...
    limits.maxVelocity_deg_s;
accelerationDuration_s = sqrt( ...
    (10 / sqrt(3)) * absoluteDelta_deg ./ ...
    limits.maxAcceleration_deg_s2);
duration_s = max([velocityDuration_s, accelerationDuration_s]);
end

function [progress, rate, acceleration] = quinticKinematics( ...
        normalizedTime, duration_s)
% Shared by search and reconstruction so their slew laws cannot diverge.
progress = 10 * normalizedTime.^3 - 15 * normalizedTime.^4 + ...
    6 * normalizedTime.^5;
safeDuration_s = max(duration_s, eps);
rate = (30 * normalizedTime.^2 - 60 * normalizedTime.^3 + ...
    30 * normalizedTime.^4) / safeDuration_s;
acceleration = (60 * normalizedTime - 180 * normalizedTime.^2 + ...
    120 * normalizedTime.^3) / safeDuration_s^2;
end

function times_s = sampledTimes(firstTime_s, lastTime_s, step_s)
% Edge and profile sampling share endpoint rules to prevent phase gaps.
if lastTime_s < firstTime_s - 1e-9
    times_s = zeros(0, 1);
    return;
end
if abs(lastTime_s - firstTime_s) <= 1e-9
    times_s = firstTime_s;
    return;
end
times_s = (firstTime_s:step_s:lastTime_s).';
if isempty(times_s) || times_s(end) < lastTime_s - 1e-9
    times_s(end + 1, 1) = lastTime_s;
else
    times_s(end) = lastTime_s;
end
end

function distances_deg = positionDistances( ...
        positions_deg, target_deg, limits, options)
% Parent, rewire, and bridge ranking require identical wrap-aware distances.
delta_deg = positions_deg - target_deg;
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    delta_deg(:, 1) = mod(delta_deg(:, 1) + ...
        azimuthSpan_deg / 2, azimuthSpan_deg) - ...
        azimuthSpan_deg / 2;
end
distances_deg = hypot(delta_deg(:, 1), delta_deg(:, 2));
end

function distance_deg = positionDistance( ...
        firstPosition_deg, secondPosition_deg, limits, options)
% Scalar cost sites share the vector distance convention used by ranking.
delta_deg = wrappedDelta( ...
    firstPosition_deg, secondPosition_deg, limits, options);
distance_deg = hypot(delta_deg(1), delta_deg(2));
end

function delta_deg = wrappedDelta( ...
        fromPosition_deg, toPosition_deg, limits, options)
% Every edge and route cost must choose the same azimuth-wrap branch.
delta_deg = toPosition_deg - fromPosition_deg;
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    delta_deg(1) = mod(delta_deg(1) + ...
        azimuthSpan_deg / 2, azimuthSpan_deg) - ...
        azimuthSpan_deg / 2;
end
end

function azimuth_deg = canonicalAzimuth(azimuth_deg, limits, options)
% Search candidates and collision queries share one wrap representation.
if options.AllowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    azimuth_deg = mod(azimuth_deg - limits.azimuth_deg(1), ...
        azimuthSpan_deg) + limits.azimuth_deg(1);
end
end

function queryOptions = collisionOptions(options)
% Every collision site must carry the same safety and time padding.
queryOptions = struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", options.TimePaddingSamples);
end

function plan = failedPlan( ...
        obstacleField, initialState, goalState, limits, options, ...
        forwardTree, backwardTree, completedIterations, elapsedTime_s, ...
        firstSolutionElapsed_s)
% Both failure exits return one stable public diagnostic schema.
endpointDelta_deg = wrappedDelta( ...
    initialState.position_deg, goalState.position_deg, limits, options);
angularLowerBound_deg = hypot(endpointDelta_deg(1), endpointDelta_deg(2));
plan = struct( ...
    "success", false, ...
    "message", ...
    "Bidirectional kinodynamic RRT* exhausted its finite search budget.", ...
    "method", "bidirectionalKinodynamicRRTStar", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "positionUnwrapped_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "isWaiting", false(0, 1), ...
    "cost_s", goalState.time_s - initialState.time_s, ...
    "objective", "minimumAngularDistance", ...
    "objectiveCost", Inf, ...
    "objectiveCostUnits", "deg", ...
    "angularPathLength_deg", Inf, ...
    "angularLowerBound_deg", angularLowerBound_deg, ...
    "suboptimalityBound", Inf, ...
    "optimalOnLattice", false, ...
    "optimalGlobally", false, ...
    "asymptoticallyOptimal", isinf(options.MaximumParentTrials) && ...
    isinf(options.MaximumRewireTrials), ...
    "exactCollisionValidated", false, ...
    "expandedNodeCount", forwardTree.Count + backwardTree.Count - 2, ...
    "generatedNodeCount", forwardTree.Count + backwardTree.Count, ...
    "searchElapsed_s", elapsedTime_s, ...
    "selectedGridStep_deg", NaN, ...
    "startState", initialState, ...
    "stopState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "obstacleField", obstacleField, ...
    "workspace", obstacleField, ...
    "waypointPosition_deg", zeros(0, 2), ...
    "waypointTime_s", zeros(0, 1), ...
    "blockedValidationSampleCount", NaN, ...
    "completedIterations", completedIterations, ...
    "firstSolutionIteration", Inf, ...
    "firstSolutionElapsed_s", firstSolutionElapsed_s, ...
    "forwardTree", forwardTree, ...
    "backwardTree", backwardTree);
end
