function plan = planAzElSpaceTimeFunnel( ...
        azElData, startState, stopState, limits, options)
%PLANAZELSPACETIMEFUNNEL Plan through a dynamic az/el/time obstacle volume.
%
% plan = planAzElSpaceTimeFunnel( ...
%     azElData, startState, stopState, limits, options)
%
% The planner has two complementary stages:
%   1. Event-compressed safe-interval search returns a dynamically feasible
%      rest-to-rest trajectory without expanding every time sample.
%   2. Widening corridor ARA* searches the full position/rate/time lattice
%      near that trajectory, improving velocity continuity and route cost.
%
% Every returned trajectory is densely checked against the original packed
% moving polygons. The safe-interval result remains available if refinement
% reaches a resource limit. azElData may also be a prebuilt
% AzElTimeObstacleWorkspace when several plans share one obstacle field.

timer = tic;
if nargin < 5
    options = struct();
end
[startState, stopState, limits, options] = ...
    normalizeInputs(startState, stopState, limits, options);
if isstruct(azElData) && isscalar(azElData) && ...
        isfield(azElData, "Format") && ...
        azElData.Format == "AzElTimeObstacleWorkspace"
    workspace = azElData;
else
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", options.MaximumVerticesPerRegion));
end
endpointDelta = wrappedDelta( ...
    startState.position_deg, stopState.position_deg, limits, options);
endpointLowerBound = hypot(endpointDelta(1), endpointDelta(2));

guide = failedGuide("Safe-interval guide was not run.");
zeroBoundary = all(abs([ ...
    startState.velocity_deg_s, stopState.velocity_deg_s, ...
    startState.acceleration_deg_s2, ...
    stopState.acceleration_deg_s2]) <= 1e-12);
if zeroBoundary
    guide = searchAzElSafeIntervalGuide( ...
        workspace, startState, stopState, limits, options);
end

attemptTemplate = struct( ...
    "RadiusDeg", NaN, ...
    "IsGlobal", false, ...
    "Success", false, ...
    "Message", "", ...
    "ObjectiveCost", Inf, ...
    "AngularPathLengthDeg", Inf, ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsedSeconds", 0, ...
    "SuboptimalityBound", Inf, ...
    "TerminationReason", "");
attempts = repmat(attemptTemplate, 0, 1);
bestSearch = struct();
bestProfile = struct();
bestObjective = Inf;
bestAttempt = 0;

if guide.Success
    guideObjective = profileObjective( ...
        guide.Profile, guide.Route.angularPathLength_deg, options);
    bestProfile = guide.Profile;
    bestObjective = guideObjective;
end

certifiedDirect = guide.Success && ...
    guide.GlobalAngularOptimal && ...
    options.Objective == "minimumAngularDistance";
if options.EnableARARefinement && ~certifiedDirect
    radii = options.CorridorRadiusSchedule_deg(:).';
    for radius = radii
        remaining = options.MaxSearchTime_s - toc(timer);
        if remaining <= options.MinimumARAAttemptTime_s
            break;
        end
        if ~guide.Success
            break;
        end
        corridor = guideCorridor( ...
            guide.Profile, startState.time_s, radius);
        search = runARAStar( ...
            workspace, startState, stopState, limits, options, ...
            corridor, remaining);
        [attempt, profile, objective] = evaluateSearch( ...
            search, workspace, startState, stopState, ...
            limits, options, radius, false);
        attempts(end + 1, 1) = attempt; %#ok<AGROW>
        if attempt.Success && objective < bestObjective - 1e-9
            bestSearch = search;
            bestProfile = profile;
            bestObjective = objective;
            bestAttempt = numel(attempts);
        end
        if attempt.Success && ...
                search.OptimalOnLattice && ...
                options.StopAfterFirstCertifiedCorridor && ...
                search.AngularPathLengthDeg <= ...
                options.TargetAngularSuboptimalityRatio * ...
                max(endpointLowerBound, eps)
            break;
        end
    end
end

if options.FallbackToGlobalSearch && ~certifiedDirect && ...
        (isempty(fieldnames(bestSearch)) || ...
        options.AlwaysTryGlobalSearch)
    remaining = options.MaxSearchTime_s - toc(timer);
    if remaining > options.MinimumARAAttemptTime_s
        search = runARAStar( ...
            workspace, startState, stopState, limits, options, ...
            [], remaining);
        [attempt, profile, objective] = evaluateSearch( ...
            search, workspace, startState, stopState, ...
            limits, options, Inf, true);
        attempts(end + 1, 1) = attempt;
        if attempt.Success && objective < bestObjective - 1e-9
            bestSearch = search;
            bestProfile = profile;
            bestObjective = objective;
            bestAttempt = numel(attempts);
        end
    end
end

if isempty(fieldnames(bestProfile))
    if guide.Success
        bestProfile = guide.Profile;
        bestObjective = profileObjective( ...
            guide.Profile, guide.Route.angularPathLength_deg, options);
    else
        plan = failedPlan( ...
            guide.Message, workspace, startState, stopState, ...
            limits, options, guide, attempts, toc(timer));
        return;
    end
end

if isempty(fieldnames(bestSearch))
    if guide.GlobalAngularOptimal
        method = "directSafeIntervalCertificate";
        message = "Direct wait-and-slew path is globally shortest in " + ...
            "continuous angular space.";
    else
        method = "eventCompressedSafeIntervalFunnel";
        message = ...
            "Safe-interval trajectory returned without ARA* refinement.";
    end
    angularLength = guide.Route.angularPathLength_deg;
    expanded = guide.ExpandedNodeCount;
    generated = guide.GeneratedNodeCount;
    optimalOnLattice = false;
    restrictedBound = Inf;
    selectedGlobal = false;
else
    method = "spaceTimeFunnelARAStar";
    angularLength = bestSearch.AngularPathLengthDeg;
    expanded = guide.ExpandedNodeCount + ...
        sum([attempts.ExpandedNodeCount]);
    generated = guide.GeneratedNodeCount + ...
        sum([attempts.GeneratedNodeCount]);
    optimalOnLattice = bestSearch.OptimalOnLattice;
    restrictedBound = bestSearch.SuboptimalityBound;
    message = "Safe-interval funnel refined by kinodynamic ARA*.";
    selectedGlobal = attempts(bestAttempt).IsGlobal;
end

lowerBound = endpointLowerBound;
plan = struct( ...
    "success", true, ...
    "message", message, ...
    "method", method, ...
    "time_s", bestProfile.time_s, ...
    "position_deg", bestProfile.position_deg, ...
    "positionUnwrapped_deg", bestProfile.positionUnwrapped_deg, ...
    "velocity_deg_s", bestProfile.velocity_deg_s, ...
    "acceleration_deg_s2", bestProfile.acceleration_deg_s2, ...
    "isWaiting", bestProfile.isWaiting, ...
    "cost_s", stopState.time_s - startState.time_s, ...
    "objective", options.Objective, ...
    "objectiveCost", bestObjective, ...
    "objectiveCostUnits", objectiveUnits(options), ...
    "angularPathLength_deg", angularLength, ...
    "angularLowerBound_deg", lowerBound, ...
    "suboptimalityBound", ...
    max(1, angularLength / max(lowerBound, eps)), ...
    "corridorLatticeSuboptimalityBound", restrictedBound, ...
    "optimalOnLattice", optimalOnLattice, ...
    "optimalOnUnrestrictedLattice", ...
    optimalOnLattice && selectedGlobal, ...
    "optimalGlobally", certifiedDirect, ...
    "expandedNodeCount", expanded, ...
    "generatedNodeCount", generated, ...
    "searchElapsed_s", toc(timer), ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "safeIntervalGuide", guide, ...
    "corridorAttempts", attempts, ...
    "selectedCorridorAttempt", bestAttempt, ...
    "kinodynamicSearch", bestSearch);
end

function search = runARAStar( ...
        workspace, startState, stopState, limits, options, ...
        corridor, remainingTime)
duration = stopState.time_s - startState.time_s;
[dt, positionResolution, rateResolution, accelerationLevel] = ...
    kinodynamicLattice(duration, limits, options);
internalLimits = struct( ...
    "AzimuthLimitsDeg", limits.azimuth_deg, ...
    "ElevationLimitsDeg", limits.elevation_deg, ...
    "AzimuthRateLimitDegPerSec", limits.maxVelocity_deg_s(1), ...
    "ElevationRateLimitDegPerSec", limits.maxVelocity_deg_s(2), ...
    "AzimuthAccelerationLimitDegPerSec2", ...
    limits.maxAcceleration_deg_s2(1), ...
    "ElevationAccelerationLimitDegPerSec2", ...
    limits.maxAcceleration_deg_s2(2));
internalStart = struct( ...
    "AzimuthDeg", startState.position_deg(1), ...
    "ElevationDeg", startState.position_deg(2), ...
    "AzimuthRateDegPerSec", startState.velocity_deg_s(1), ...
    "ElevationRateDegPerSec", startState.velocity_deg_s(2), ...
    "AzimuthAccelerationDegPerSec2", ...
    startState.acceleration_deg_s2(1), ...
    "ElevationAccelerationDegPerSec2", ...
    startState.acceleration_deg_s2(2), ...
    "Time", startState.time_s);
internalGoal = struct( ...
    "AzimuthDeg", stopState.position_deg(1), ...
    "ElevationDeg", stopState.position_deg(2), ...
    "AzimuthRateDegPerSec", stopState.velocity_deg_s(1), ...
    "ElevationRateDegPerSec", stopState.velocity_deg_s(2), ...
    "AzimuthAccelerationDegPerSec2", ...
    stopState.acceleration_deg_s2(1), ...
    "ElevationAccelerationDegPerSec2", ...
    stopState.acceleration_deg_s2(2), ...
    "EarliestTime", stopState.time_s, ...
    "LatestTime", stopState.time_s, ...
    "PositionToleranceDeg", max( ...
    options.KinodynamicGridStep_deg, positionResolution) / 2 + 1e-9, ...
    "RateToleranceDegPerSec", rateResolution / 2 + 1e-9, ...
    "AccelerationToleranceDegPerSec2", 1e-9);
internalOptions = struct( ...
    "TimeStepSeconds", dt, ...
    "MaxPlanningTimeSeconds", duration, ...
    "Objective", options.Objective, ...
    "EpsilonSchedule", options.EpsilonSchedule, ...
    "AzimuthWrap", options.AllowAzimuthWrap, ...
    "AzimuthResolutionDeg", positionResolution(1), ...
    "ElevationResolutionDeg", positionResolution(2), ...
    "AzimuthRateResolutionDegPerSec", rateResolution(1), ...
    "ElevationRateResolutionDegPerSec", rateResolution(2), ...
    "AccelerationLevels", [-accelerationLevel 0 accelerationLevel], ...
    "CollisionCheckStepSeconds", options.ValidationStep_s, ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", options.TimePaddingSamples, ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "StateCorridor", corridor, ...
    "MaxExpansions", options.ARAMaxExpansions, ...
    "MaxWallTimeSeconds", min( ...
    remainingTime, options.ARAMaxWallTime_s), ...
    "InitialNodeCapacity", options.InitialARANodeCapacity);
search = planAzElKinodynamicARAStar( ...
    workspace, internalStart, internalGoal, ...
    internalLimits, internalOptions);
end

function [attempt, profile, objective] = evaluateSearch( ...
        search, workspace, startState, stopState, ...
        limits, options, radius, isGlobal)
attempt = struct( ...
    "RadiusDeg", radius, ...
    "IsGlobal", isGlobal, ...
    "Success", false, ...
    "Message", string(search.Message), ...
    "ObjectiveCost", Inf, ...
    "AngularPathLengthDeg", Inf, ...
    "ExpandedNodeCount", search.ExpandedNodeCount, ...
    "GeneratedNodeCount", search.GeneratedNodeCount, ...
    "SearchElapsedSeconds", search.SearchElapsedSeconds, ...
    "SuboptimalityBound", search.SuboptimalityBound, ...
    "TerminationReason", string(search.TerminationReason));
profile = struct();
objective = Inf;
if ~search.Success
    return;
end
profile = densifyARAPath( ...
    search.Path, startState.time_s, stopState.time_s, ...
    options.SampleTime_s, limits, options);
validation = densifyARAPath( ...
    search.Path, startState.time_s, stopState.time_s, ...
    options.ValidationStep_s, limits, options);
blocked = queryAzElTimeObstacle(workspace, ...
    [validation.position_deg(:, 1); profile.position_deg(:, 1)], ...
    [validation.position_deg(:, 2); profile.position_deg(:, 2)], ...
    [validation.time_s; profile.time_s], struct( ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", options.TimePaddingSamples, ...
    "SafetyMarginDeg", options.SafetyMargin_deg));
if any(blocked)
    attempt.Message = sprintf( ...
        "ARA* result failed dense validation at %d samples.", ...
        nnz(blocked));
    return;
end
attempt.Success = true;
attempt.ObjectiveCost = search.ObjectiveCost;
attempt.AngularPathLengthDeg = search.AngularPathLengthDeg;
objective = search.ObjectiveCost;
end

function profile = densifyARAPath( ...
        path, startTime, stopTime, sampleStep, limits, options)
time = (startTime:sampleStep:stopTime).';
if time(end) < stopTime - 1e-9
    time(end + 1, 1) = stopTime;
else
    time(end) = stopTime;
end
elapsed = time - startTime;
position = repmat([ ...
    path.AzimuthUnwrappedDeg(1), path.ElevationDeg(1)], ...
    numel(time), 1);
velocity = zeros(numel(time), 2);
acceleration = zeros(numel(time), 2);
for edge = 1:height(path) - 1
    edgeStart = path.ElapsedSeconds(edge);
    edgeStop = path.ElapsedSeconds(edge + 1);
    active = elapsed >= edgeStart - 1e-10 & ...
        elapsed < edgeStop - 1e-10;
    if ~any(active)
        continue;
    end
    tau = elapsed(active) - edgeStart;
    startPosition = [path.AzimuthUnwrappedDeg(edge), ...
        path.ElevationDeg(edge)];
    startVelocity = [path.AzimuthRateDegPerSec(edge), ...
        path.ElevationRateDegPerSec(edge)];
    edgeAcceleration = [ ...
        path.AzimuthAccelerationDegPerSec2(edge + 1), ...
        path.ElevationAccelerationDegPerSec2(edge + 1)];
    position(active, :) = startPosition + ...
        tau .* startVelocity + 0.5 * tau.^2 .* edgeAcceleration;
    velocity(active, :) = startVelocity + tau .* edgeAcceleration;
    acceleration(active, :) = repmat( ...
        edgeAcceleration, nnz(active), 1);
end
position(end, :) = [ ...
    path.AzimuthUnwrappedDeg(end), path.ElevationDeg(end)];
velocity(end, :) = [ ...
    path.AzimuthRateDegPerSec(end), ...
    path.ElevationRateDegPerSec(end)];
acceleration(end, :) = [ ...
    path.AzimuthAccelerationDegPerSec2(end), ...
    path.ElevationAccelerationDegPerSec2(end)];
wrapped = position;
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    wrapped(:, 1) = mod( ...
        wrapped(:, 1) - limits.azimuth_deg(1), span) + ...
        limits.azimuth_deg(1);
end
profile = struct( ...
    "time_s", time, ...
    "position_deg", wrapped, ...
    "positionUnwrapped_deg", position, ...
    "velocity_deg_s", velocity, ...
    "acceleration_deg_s2", acceleration, ...
    "isWaiting", all(abs(velocity) <= 1e-10, 2) & ...
    all(abs(acceleration) <= 1e-10, 2));
end

function corridor = guideCorridor(profile, startTime, radius)
elapsed = profile.time_s - startTime;
[elapsed, keep] = unique(elapsed, "stable");
corridor = struct( ...
    "ElapsedSeconds", elapsed, ...
    "AzimuthDeg", profile.positionUnwrapped_deg(keep, 1), ...
    "ElevationDeg", profile.positionUnwrapped_deg(keep, 2), ...
    "RadiusDeg", radius);
end

function [dt, positionResolution, rateResolution, accelerationLevel] = ...
        kinodynamicLattice(duration, limits, options)
if isempty(options.KinodynamicTimeStep_s)
    desired = max(options.SampleTime_s, ...
        duration / options.MaximumKinodynamicSteps);
else
    desired = options.KinodynamicTimeStep_s;
end
stepCount = max(1, ceil(duration / desired));
dt = duration / stepCount;
accelerationLevel = min(1, min(limits.maxVelocity_deg_s ./ ...
    (limits.maxAcceleration_deg_s2 .* dt)));
activeAcceleration = limits.maxAcceleration_deg_s2 .* ...
    accelerationLevel;
baseResolution = 0.5 .* activeAcceleration .* dt^2;
subdivision = max(1, ceil( ...
    baseResolution ./ options.KinodynamicGridStep_deg));
positionResolution = baseResolution ./ subdivision;
rateResolution = activeAcceleration .* dt;
end

function objective = profileObjective(profile, angularLength, options)
if options.Objective == "minimumAngularDistance"
    objective = angularLength;
else
    moving = find(~profile.isWaiting, 1, "last");
    if isempty(moving)
        objective = 0;
    else
        objective = profile.time_s(moving) - profile.time_s(1);
    end
end
end

function units = objectiveUnits(options)
if options.Objective == "minimumAngularDistance"
    units = "degrees";
else
    units = "seconds";
end
end

function delta = wrappedDelta(first, second, limits, options)
delta = second - first;
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    delta(1) = mod(delta(1) + span / 2, span) - span / 2;
end
end

function [startState, stopState, limits, options] = ...
        normalizeInputs(startState, stopState, limits, options)
requiredState = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
startState = normalizeState(startState, "startState", requiredState);
stopState = normalizeState(stopState, "stopState", requiredState);
if stopState.time_s <= startState.time_s
    error("planAzElSpaceTimeFunnel:InvalidTime", ...
        "stopState.time_s must follow startState.time_s.");
end

requiredLimits = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
if ~isstruct(limits) || ~isscalar(limits) || ...
        ~all(isfield(limits, cellstr(requiredLimits)))
    error("planAzElSpaceTimeFunnel:InvalidLimits", ...
        "limits is missing a required field.");
end
for name = requiredLimits
    validateattributes(limits.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    limits.(name) = reshape(double(limits.(name)), 1, 2);
end
if any(diff(limits.azimuth_deg) <= 0) || ...
        any(diff(limits.elevation_deg) <= 0) || ...
        any(limits.maxVelocity_deg_s <= 0) || ...
        any(limits.maxAcceleration_deg_s2 <= 0)
    error("planAzElSpaceTimeFunnel:InvalidLimits", ...
        "Limit ranges must increase and dynamic limits must be positive.");
end

defaults = struct( ...
    "SampleTime_s", 0.5, ...
    "ValidationStep_s", [], ...
    "GuideGridStep_deg", 1, ...
    "GuidePrimitiveRadii_deg", [], ...
    "GuideDirectionStep_deg", 45, ...
    "GuideDirectionAngles_deg", [], ...
    "GuideHeuristicWeight", 1.25, ...
    "GuideCollisionCheckStep_s", [], ...
    "MaximumSafeIntervalSamples", 10000, ...
    "MaximumDepartureTrials", 64, ...
    "DepartureBatchSize", 8, ...
    "GuideMaxExpansions", 100000, ...
    "GuideMaxWallTime_s", 15, ...
    "InitialGuideNodeCapacity", 4096, ...
    "TimePaddingSamples", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", diff(limits.azimuth_deg) >= 360 - 1e-9, ...
    "Objective", "minimumAngularDistance", ...
    "MaximumVerticesPerRegion", 500, ...
    "EnableARARefinement", true, ...
    "KinodynamicTimeStep_s", [], ...
    "MaximumKinodynamicSteps", 120, ...
    "KinodynamicGridStep_deg", 0.5, ...
    "CorridorRadiusSchedule_deg", [2 4 8], ...
    "EpsilonSchedule", [2.5 1.5 1], ...
    "ARAMaxExpansions", 300000, ...
    "ARAMaxWallTime_s", 30, ...
    "InitialARANodeCapacity", 4096, ...
    "MinimumARAAttemptTime_s", 0.5, ...
    "StopAfterFirstCertifiedCorridor", true, ...
    "TargetAngularSuboptimalityRatio", 1.05, ...
    "FallbackToGlobalSearch", true, ...
    "AlwaysTryGlobalSearch", false, ...
    "MaxSearchTime_s", 45);
options = applyDefaults(options, defaults);
if isempty(options.ValidationStep_s)
    options.ValidationStep_s = min( ...
        options.SampleTime_s, options.GuideGridStep_deg / ...
        max(limits.maxVelocity_deg_s) / 8);
end
if isempty(options.GuideCollisionCheckStep_s)
    options.GuideCollisionCheckStep_s = options.ValidationStep_s;
end
if isempty(options.GuidePrimitiveRadii_deg)
    options.GuidePrimitiveRadii_deg = ...
        options.GuideGridStep_deg * [1 2 4 8];
end
scalarPositive = ["SampleTime_s", "ValidationStep_s", ...
    "GuideGridStep_deg", "GuideDirectionStep_deg", ...
    "GuideHeuristicWeight", "GuideCollisionCheckStep_s", ...
    "GuideMaxWallTime_s", "KinodynamicGridStep_deg", ...
    "MaximumKinodynamicSteps", "ARAMaxWallTime_s", ...
    "MinimumARAAttemptTime_s", "TargetAngularSuboptimalityRatio", ...
    "MaxSearchTime_s"];
for name = scalarPositive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
integerPositive = ["MaximumSafeIntervalSamples", ...
    "MaximumDepartureTrials", "DepartureBatchSize", ...
    "GuideMaxExpansions", ...
    "InitialGuideNodeCapacity", "ARAMaxExpansions", ...
    "InitialARANodeCapacity", "MaximumKinodynamicSteps"];
for name = integerPositive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'integer', 'positive'});
end
validateattributes(options.TimePaddingSamples, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.GuidePrimitiveRadii_deg, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
if ~isempty(options.GuideDirectionAngles_deg)
    validateattributes(options.GuideDirectionAngles_deg, {'numeric'}, ...
        {'vector', 'real', 'finite'});
end
validateattributes(options.CorridorRadiusSchedule_deg, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
validateattributes(options.EpsilonSchedule, {'numeric'}, ...
    {'vector', 'real', 'finite', '>=', 1});
if any(diff(options.EpsilonSchedule) > 1e-12)
    error("planAzElSpaceTimeFunnel:InvalidEpsilonSchedule", ...
        "EpsilonSchedule must be nonincreasing.");
end
logicalNames = ["AllowAzimuthWrap", "EnableARARefinement", ...
    "StopAfterFirstCertifiedCorridor", "FallbackToGlobalSearch", ...
    "AlwaysTryGlobalSearch"];
for name = logicalNames
    validateattributes(options.(name), ...
        {'logical', 'numeric'}, {'scalar'});
    options.(name) = logical(options.(name));
end
if options.AllowAzimuthWrap && ...
        abs(diff(limits.azimuth_deg) - 360) > 1e-6
    error("planAzElSpaceTimeFunnel:InvalidWrapLimits", ...
        "Wrapped azimuth limits must span exactly 360 degrees.");
end
objective = lower(strtrim(string(options.Objective)));
if any(objective == ["minimumangulardistance", ...
        "angulardistance", "distance"])
    options.Objective = "minimumAngularDistance";
elseif any(objective == ["minimumtime", "time"])
    options.Objective = "minimumTime";
else
    error("planAzElSpaceTimeFunnel:InvalidObjective", ...
        "Objective must be minimumAngularDistance or minimumTime.");
end
end

function state = normalizeState(state, label, requiredState)
if ~isstruct(state) || ~isscalar(state) || ...
        ~all(isfield(state, cellstr(requiredState)))
    error("planAzElSpaceTimeFunnel:InvalidState", ...
        "%s is missing a required field.", label);
end
validateattributes(state.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
for name = requiredState(2:end)
    validateattributes(state.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    state.(name) = reshape(double(state.(name)), 1, 2);
end
state.time_s = double(state.time_s);
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end

function guide = failedGuide(message)
guide = struct( ...
    "Success", false, ...
    "Message", string(message), ...
    "Method", "eventCompressedSafeIntervalSearch", ...
    "Route", struct(), ...
    "Profile", struct(), ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0);
guide.GlobalAngularOptimal = false;
end

function plan = failedPlan( ...
        message, workspace, startState, stopState, limits, options, ...
        guide, attempts, elapsed)
plan = struct( ...
    "success", false, ...
    "message", string(message), ...
    "method", "spaceTimeFunnelARAStar", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "positionUnwrapped_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "isWaiting", false(0, 1), ...
    "cost_s", Inf, ...
    "objective", options.Objective, ...
    "objectiveCost", Inf, ...
    "objectiveCostUnits", objectiveUnits(options), ...
    "angularPathLength_deg", Inf, ...
    "angularLowerBound_deg", NaN, ...
    "suboptimalityBound", Inf, ...
    "corridorLatticeSuboptimalityBound", Inf, ...
    "optimalOnLattice", false, ...
    "optimalOnUnrestrictedLattice", false, ...
    "optimalGlobally", false, ...
    "expandedNodeCount", guide.ExpandedNodeCount + ...
    sum([attempts.ExpandedNodeCount]), ...
    "generatedNodeCount", guide.GeneratedNodeCount + ...
    sum([attempts.GeneratedNodeCount]), ...
    "searchElapsed_s", elapsed, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "safeIntervalGuide", guide, ...
    "corridorAttempts", attempts, ...
    "selectedCorridorAttempt", 0, ...
    "kinodynamicSearch", struct());
end
