function plan = planAzElMovingTargetIntercept( ...
        azElData, startState, target, limits, options)
%PLANAZELMOVINGTARGETINTERCEPT Catch a moving point through dynamic volumes.
%
% The target trajectory is independent of the obstacle field. Candidate
% interception times are sampled across the requested interval, rejected
% only when the target itself is occupied or kinematically unreachable,
% and attempted from earliest to latest. No route or waypoint is supplied.

if nargin < 5
    options = struct();
end
requiredTarget = ["time_s", "position_deg"];
if ~isstruct(target) || ~isscalar(target) || ...
        ~all(isfield(target, requiredTarget))
    error("planAzElMovingTargetIntercept:InvalidTarget", ...
        "target requires time_s and position_deg.");
end
target.time_s = double(target.time_s(:));
target.position_deg = double(target.position_deg);
validateattributes(target.time_s, {'numeric'}, ...
    {'vector', 'real', 'finite', 'increasing'});
validateattributes(target.position_deg, {'numeric'}, ...
    {'2d', 'ncols', 2, 'real', 'finite'});
if size(target.position_deg, 1) ~= numel(target.time_s)
    error("planAzElMovingTargetIntercept:TargetSizeMismatch", ...
        "target.position_deg must contain one row per target time.");
end

defaults = struct( ...
    "EarliestInterceptTime_s", ...
        max(startState.time_s, target.time_s(1)), ...
    "LatestInterceptTime_s", target.time_s(end), ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 12, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "CatchTolerance_deg", 0.35, ...
    "SafetyMargin_deg", 0);
options = applyDefaults(options, defaults);
validateInterceptOptions(options, startState, target);

if isstruct(azElData) && isscalar(azElData) && ...
        isfield(azElData, "Format") && ...
        azElData.Format == "AzElTimeObstacleWorkspace"
    workspace = azElData;
else
    maximumVertices = fieldOr(options, ...
        "MaximumVerticesPerRegion", 500);
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", maximumVertices));
end

candidateTime = (options.EarliestInterceptTime_s: ...
    options.InterceptTimeStep_s:options.LatestInterceptTime_s).';
if isempty(candidateTime) || ...
        candidateTime(end) < options.LatestInterceptTime_s - 1e-9
    candidateTime(end + 1, 1) = options.LatestInterceptTime_s;
end
candidatePosition = interp1(target.time_s, target.position_deg, ...
    candidateTime, "linear");
inside = candidatePosition(:, 1) >= limits.azimuth_deg(1) & ...
    candidatePosition(:, 1) <= limits.azimuth_deg(2) & ...
    candidatePosition(:, 2) >= limits.elevation_deg(1) & ...
    candidatePosition(:, 2) <= limits.elevation_deg(2);
blocked = true(size(candidateTime));
blocked(inside) = queryAzElTimeObstacle(workspace, ...
    candidatePosition(inside, 1), candidatePosition(inside, 2), ...
    candidateTime(inside), struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
reachable = kinematicallyReachable( ...
    startState, candidateTime, candidatePosition, limits);
eligible = inside & ~blocked & reachable;
eligibleIndex = find(eligible);
if numel(eligibleIndex) > options.MaximumInterceptAttempts
    selected = unique(round(linspace( ...
        1, numel(eligibleIndex), options.MaximumInterceptAttempts)));
    eligibleIndex = eligibleIndex(selected);
end

attemptTemplate = struct( ...
    "time_s", NaN, ...
    "position_deg", [NaN NaN], ...
    "success", false, ...
    "elapsed_s", 0, ...
    "message", "");
attempts = repmat(attemptTemplate, numel(eligibleIndex), 1);
attemptCount = 0;
timer = tic;
for k = 1:numel(eligibleIndex)
    index = eligibleIndex(k);
    stopState = boundaryState( ...
        candidateTime(index), candidatePosition(index, :));
    plannerOptions = options;
    plannerOptions.MaxSearchTime_s = min( ...
        options.PerAttemptMaxSearchTime_s, ...
        fieldOr(options, "MaxSearchTime_s", ...
        options.PerAttemptMaxSearchTime_s));
    attemptTimer = tic;
    candidate = planAzElSpaceTimeFunnel( ...
        workspace, startState, stopState, limits, plannerOptions);
    attemptCount = attemptCount + 1;
    attempts(attemptCount, 1) = struct( ...
        "time_s", candidateTime(index), ...
        "position_deg", candidatePosition(index, :), ...
        "success", candidate.success, ...
        "elapsed_s", toc(attemptTimer), ...
        "message", string(candidate.message));
    if ~candidate.success
        continue;
    end
    targetAtCatch = interp1(target.time_s, target.position_deg, ...
        candidate.time_s(end), "linear");
    catchError = hypot( ...
        candidate.position_deg(end, 1) - targetAtCatch(1), ...
        candidate.position_deg(end, 2) - targetAtCatch(2));
    if catchError > options.CatchTolerance_deg + 1e-9
        continue;
    end
    plan = candidate;
    plan.interceptSuccess = true;
    plan.interceptTime_s = candidate.time_s(end);
    plan.interceptPosition_deg = candidate.position_deg(end, :);
    plan.targetPositionAtIntercept_deg = targetAtCatch;
    plan.catchError_deg = catchError;
    plan.targetTrajectory = target;
    plan.interceptAttempts = attempts(1:attemptCount);
    plan.interceptCandidateCount = nnz(eligible);
    plan.interceptSearchElapsed_s = toc(timer);
    return;
end

plan = struct( ...
    "success", false, ...
    "interceptSuccess", false, ...
    "message", "No sampled moving-target interception was found.", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "workspace", workspace, ...
    "startState", startState, ...
    "targetTrajectory", target, ...
    "limits", limits, ...
    "options", options, ...
    "interceptAttempts", attempts(1:attemptCount), ...
    "interceptCandidateCount", nnz(eligible), ...
    "interceptSearchElapsed_s", toc(timer));
end

function reachable = kinematicallyReachable( ...
        startState, time_s, position, limits)
delta = abs(position - startState.position_deg);
minimumTime = max( ...
    delta ./ limits.maxVelocity_deg_s, [], 2);
accelerationTime = max(sqrt( ...
    2 * delta ./ limits.maxAcceleration_deg_s2), [], 2);
minimumTime = max(minimumTime, accelerationTime);
reachable = minimumTime <= ...
    time_s - startState.time_s + 1e-9;
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function validateInterceptOptions(options, startState, target)
positive = ["InterceptTimeStep_s", "PerAttemptMaxSearchTime_s", ...
    "CatchTolerance_deg"];
for name = positive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.MaximumInterceptAttempts, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(options.EarliestInterceptTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', ...
    '>=', max(startState.time_s, target.time_s(1))});
validateattributes(options.LatestInterceptTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '<=', target.time_s(end)});
if options.LatestInterceptTime_s <= ...
        options.EarliestInterceptTime_s
    error("planAzElMovingTargetIntercept:InvalidInterceptWindow", ...
        "LatestInterceptTime_s must follow EarliestInterceptTime_s.");
end
end

function value = fieldOr(input, name, fallback)
if isfield(input, name) && ~isempty(input.(name))
    value = input.(name);
else
    value = fallback;
end
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
