function plan = planSimpleAzElTimeKinodynamicDijkstra( ...
        azElData, initialState, destinationState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   options = planSimpleAzElTimeKinodynamicDijkstra()
%   plan = planSimpleAzElTimeKinodynamicDijkstra( ...
%       azElData, initialState, destinationState, limits)
%   plan = planSimpleAzElTimeKinodynamicDijkstra( ...
%       azElData, initialState, destinationState, limits, options)
%**************************************************************************
% PURPOSE
%   - Teach a first-principles Dijkstra search over discretized azimuth,
%     elevation, time, velocity, and acceleration.
%   - Apply one constant azimuth/elevation jerk command per time step.
%   - Check every transition against time-varying azElData polygons.
%**************************************************************************
% INPUTS
%   - azElData (struct array or cell array)
%       Canonical moving obstacle data accepted by
%       buildAzElTimeObstacleField.
%   - initialState (scalar struct)
%       .time_s, .position_deg, .velocity_deg_s, and
%       .acceleration_deg_s2 describe the initial kinodynamic state.
%   - destinationState (scalar struct)
%       Same fields as initialState. Its time is an exact terminal time,
%       within options.timeTolerance_s.
%   - limits (scalar struct)
%       .azimuth_deg and .elevation_deg contain axis bounds.
%       .maxVelocity_deg_s, .maxAcceleration_deg_s2, and
%       .maxJerk_deg_s3 contain [azimuth elevation] magnitudes.
%   - options (scalar struct)
%       .timeStep_s sets the uniform time step.
%       .positionStep_deg, .velocityStep_deg_s, and
%       .accelerationStep_deg_s2 set the two-axis lattice spacing.
%       .positionStepSchedule_deg optionally runs coarse-to-fine position
%       lattices such as [4 2 1 0.5].
%       .jerkCommands_deg_s3 optionally supplies an N-by-2 command set.
%       .allowAzimuthWrap enables a complete 360-degree azimuth domain.
%       .collisionCheckStep_s and .collisionQueryOptions configure
%       transition sampling and polygon queries.
%       .positionTolerance_deg, .velocityTolerance_deg_s,
%       .accelerationTolerance_deg_s2, and .timeTolerance_s configure the
%       exact-time destination test.
%       .waitingTolerance_deg identifies unchanged position samples.
%       .accelerationWeight and .jerkWeight add nonnegative cost terms.
%       .maximumOccupancyCells, .maximumGeneratedStates, and
%       .maximumExpandedStates limit allocation and search work.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       .success, .message, and .totalCost summarize the result.
%       .time_s, .position_deg, .positionUnwrapped_deg, .velocity_deg_s,
%       .acceleration_deg_s2, .jerk_deg_s3, and .isWaiting describe the
%       reconstructed timed kinodynamic trajectory.
%       .bestKnownCost, .parentStateIndex, .parentJerk_deg_s3, and the
%       generated-state arrays expose the Dijkstra search.
%       .gridRefinement contains PascalCase per-level diagnostics.
%       State subscripts use [azimuth, elevation, time, azimuth velocity,
%       elevation velocity, azimuth acceleration, elevation acceleration].
%**************************************************************************
% UNITS
%   - Angles are degrees. Time is seconds. Velocity, acceleration, and jerk
%     use deg/s, deg/s^2, and deg/s^3, respectively.

%% Section 1: Validate Inputs
defaultOptions = defaultSimpleDijkstraOptions();
if nargin == 0
    plan = defaultOptions;
    return;
end
if nargin < 5 || isempty(options)
    options = struct();
end
limits = normalizeSimpleDijkstraLimits(limits);
initialState = normalizeSimpleDijkstraState(initialState, "initialState");
destinationState = normalizeSimpleDijkstraState( ...
    destinationState, "destinationState");

if destinationState.time_s < initialState.time_s
    error("planSimpleAzElTimeKinodynamicDijkstra:InvalidTimeOrder", ...
        "destinationState.time_s must not precede initialState.time_s.");
end
endpointStates = [initialState, destinationState];
endpointNames = ["initialState", "destinationState"];
for endpointIndex = 1:numel(endpointStates)
    endpointState = endpointStates(endpointIndex);
    elevationIsInsideLimits = ...
        endpointState.position_deg(2) >= limits.elevation_deg(1) && ...
        endpointState.position_deg(2) <= limits.elevation_deg(2);
    azimuthIsInsideLimits = ...
        endpointState.position_deg(1) >= limits.azimuth_deg(1) && ...
        endpointState.position_deg(1) <= limits.azimuth_deg(2);
    dynamicsAreInsideLimits = ...
        all(abs(endpointState.velocity_deg_s) <= ...
        limits.maxVelocity_deg_s) && ...
        all(abs(endpointState.acceleration_deg_s2) <= ...
        limits.maxAcceleration_deg_s2);
    if ~elevationIsInsideLimits || ~azimuthIsInsideLimits || ...
            ~dynamicsAreInsideLimits
        error("planSimpleAzElTimeKinodynamicDijkstra:EndpointOutsideLimits", ...
            "%s violates a position, velocity, or acceleration limit.", ...
            endpointNames(endpointIndex));
    end
end

%% Section 2: Resolve Grid And Kinodynamic Options
options = resolveSimpleDijkstraOptions(options, defaultOptions, limits);
if ~isempty(options.positionStepSchedule_deg)
    plan = runSimpleDijkstraGridRefinement( ...
        azElData, initialState, destinationState, limits, options);
    return;
end
timeStep_s = options.timeStep_s;
requestedDuration_s = ...
    destinationState.time_s - initialState.time_s;
timeStepCount = round(requestedDuration_s / timeStep_s);
mappedDuration_s = timeStepCount * timeStep_s;
if abs(mappedDuration_s - requestedDuration_s) > options.timeTolerance_s
    error("planSimpleAzElTimeKinodynamicDijkstra:TimeGridMismatch", ...
        ["The exact destination time must map to the uniform time grid " ...
        "within options.timeTolerance_s."]);
end
timeGrid_s = initialState.time_s + (0:timeStepCount).' * timeStep_s;

obstacleField = buildAzElTimeObstacleField(azElData);
% This tolerance absorbs arithmetic noise at exact configured limits. It is
% far below every default lattice step and therefore cannot admit a new cell.
limitTolerance = 1e-12;

%% Section 3: Build The Azimuth Elevation Time Occupancy
azimuthSpan_deg = diff(limits.azimuth_deg);
azimuthStepCount = round(azimuthSpan_deg / options.positionStep_deg(1));
if options.allowAzimuthWrap
    % The upper seam endpoint is omitted because it represents the same
    % direction as the lower endpoint. This avoids duplicate wrapped states.
    azimuthGrid_deg = limits.azimuth_deg(1) + ...
        (0:azimuthStepCount - 1) * options.positionStep_deg(1);
else
    azimuthGrid_deg = limits.azimuth_deg(1) + ...
        (0:azimuthStepCount) * options.positionStep_deg(1);
end
elevationStepCount = round( ...
    diff(limits.elevation_deg) / options.positionStep_deg(2));
elevationGrid_deg = limits.elevation_deg(1) + ...
    (0:elevationStepCount) * options.positionStep_deg(2);

occupancyCellCount = numel(azimuthGrid_deg) * ...
    numel(elevationGrid_deg) * numel(timeGrid_s);
if occupancyCellCount > options.maximumOccupancyCells
    error("planSimpleAzElTimeKinodynamicDijkstra:OccupancyTooLarge", ...
        ["The requested occupancy has %d cells; the configured maximum " ...
        "is %d. Increase grid steps or maximumOccupancyCells."], ...
        occupancyCellCount, options.maximumOccupancyCells);
end
[azimuthMesh_deg, elevationMesh_deg] = meshgrid( ...
    azimuthGrid_deg, elevationGrid_deg);
occupancy = false( ...
    numel(elevationGrid_deg), numel(azimuthGrid_deg), numel(timeGrid_s));
for timeIndex = 1:numel(timeGrid_s)
    occupiedAtTime = queryAzElTimeObstacle( ...
        obstacleField, azimuthMesh_deg, elevationMesh_deg, ...
        timeGrid_s(timeIndex), options.collisionQueryOptions);
    occupancy(:, :, timeIndex) = occupiedAtTime;
end

%% Section 4: Build The Discrete State Axes
azimuthVelocityCount = round( ...
    limits.maxVelocity_deg_s(1) / options.velocityStep_deg_s(1));
elevationVelocityCount = round( ...
    limits.maxVelocity_deg_s(2) / options.velocityStep_deg_s(2));
azimuthVelocityGrid_deg_s = ...
    (-azimuthVelocityCount:azimuthVelocityCount) * ...
    options.velocityStep_deg_s(1);
elevationVelocityGrid_deg_s = ...
    (-elevationVelocityCount:elevationVelocityCount) * ...
    options.velocityStep_deg_s(2);

azimuthAccelerationCount = round(limits.maxAcceleration_deg_s2(1) / ...
    options.accelerationStep_deg_s2(1));
elevationAccelerationCount = round(limits.maxAcceleration_deg_s2(2) / ...
    options.accelerationStep_deg_s2(2));
azimuthAccelerationGrid_deg_s2 = ...
    (-azimuthAccelerationCount:azimuthAccelerationCount) * ...
    options.accelerationStep_deg_s2(1);
elevationAccelerationGrid_deg_s2 = ...
    (-elevationAccelerationCount:elevationAccelerationCount) * ...
    options.accelerationStep_deg_s2(2);

% States are generated on demand. One character key encodes the seven
% integer subscripts in the ordering documented in the function header.
% A containers.Map lookup detects every repeated discretized state.

%% Section 5: Map The Initial And Destination States
if options.allowAzimuthWrap
    initialAzimuthDifference_deg = mod(azimuthGrid_deg - ...
        initialState.position_deg(1) + 180, 360) - 180;
    destinationAzimuthDifference_deg = mod(azimuthGrid_deg - ...
        destinationState.position_deg(1) + 180, 360) - 180;
else
    initialAzimuthDifference_deg = ...
        azimuthGrid_deg - initialState.position_deg(1);
    destinationAzimuthDifference_deg = ...
        azimuthGrid_deg - destinationState.position_deg(1);
end
[~, initialAzimuthIndex] = min(abs(initialAzimuthDifference_deg));
[~, destinationAzimuthIndex] = min(abs(destinationAzimuthDifference_deg));
[~, initialElevationIndex] = min(abs( ...
    elevationGrid_deg - initialState.position_deg(2)));
[~, destinationElevationIndex] = min(abs( ...
    elevationGrid_deg - destinationState.position_deg(2)));
[~, initialAzimuthVelocityIndex] = min(abs( ...
    azimuthVelocityGrid_deg_s - initialState.velocity_deg_s(1)));
[~, initialElevationVelocityIndex] = min(abs( ...
    elevationVelocityGrid_deg_s - initialState.velocity_deg_s(2)));
[~, destinationAzimuthVelocityIndex] = min(abs( ...
    azimuthVelocityGrid_deg_s - destinationState.velocity_deg_s(1)));
[~, destinationElevationVelocityIndex] = min(abs( ...
    elevationVelocityGrid_deg_s - destinationState.velocity_deg_s(2)));
[~, initialAzimuthAccelerationIndex] = min(abs( ...
    azimuthAccelerationGrid_deg_s2 - ...
    initialState.acceleration_deg_s2(1)));
[~, initialElevationAccelerationIndex] = min(abs( ...
    elevationAccelerationGrid_deg_s2 - ...
    initialState.acceleration_deg_s2(2)));
[~, destinationAzimuthAccelerationIndex] = min(abs( ...
    azimuthAccelerationGrid_deg_s2 - ...
    destinationState.acceleration_deg_s2(1)));
[~, destinationElevationAccelerationIndex] = min(abs( ...
    elevationAccelerationGrid_deg_s2 - ...
    destinationState.acceleration_deg_s2(2)));

initialSubscripts = [ ...
    initialAzimuthIndex, initialElevationIndex, 1, ...
    initialAzimuthVelocityIndex, initialElevationVelocityIndex, ...
    initialAzimuthAccelerationIndex, initialElevationAccelerationIndex];
destinationSubscripts = [ ...
    destinationAzimuthIndex, destinationElevationIndex, numel(timeGrid_s), ...
    destinationAzimuthVelocityIndex, destinationElevationVelocityIndex, ...
    destinationAzimuthAccelerationIndex, ...
    destinationElevationAccelerationIndex];

mappedInitialPosition_deg = [ ...
    azimuthGrid_deg(initialAzimuthIndex), ...
    elevationGrid_deg(initialElevationIndex)];
mappedInitialVelocity_deg_s = [ ...
    azimuthVelocityGrid_deg_s(initialAzimuthVelocityIndex), ...
    elevationVelocityGrid_deg_s(initialElevationVelocityIndex)];
mappedInitialAcceleration_deg_s2 = [ ...
    azimuthAccelerationGrid_deg_s2(initialAzimuthAccelerationIndex), ...
    elevationAccelerationGrid_deg_s2(initialElevationAccelerationIndex)];
mappedDestinationPosition_deg = [ ...
    azimuthGrid_deg(destinationAzimuthIndex), ...
    elevationGrid_deg(destinationElevationIndex)];
mappedDestinationVelocity_deg_s = [ ...
    azimuthVelocityGrid_deg_s(destinationAzimuthVelocityIndex), ...
    elevationVelocityGrid_deg_s(destinationElevationVelocityIndex)];
mappedDestinationAcceleration_deg_s2 = [ ...
    azimuthAccelerationGrid_deg_s2(destinationAzimuthAccelerationIndex), ...
    elevationAccelerationGrid_deg_s2(destinationElevationAccelerationIndex)];

if occupancy(initialElevationIndex, initialAzimuthIndex, 1)
    error("planSimpleAzElTimeKinodynamicDijkstra:InitialStateOccupied", ...
        "The mapped initial state is occupied.");
end
if occupancy(destinationElevationIndex, destinationAzimuthIndex, end)
    error("planSimpleAzElTimeKinodynamicDijkstra:DestinationStateOccupied", ...
        "The mapped destination state is occupied.");
end
specifiedInitialStateIsOccupied = queryAzElTimeObstacle( ...
    obstacleField, initialState.position_deg(1), ...
    initialState.position_deg(2), initialState.time_s, ...
    options.collisionQueryOptions);
specifiedDestinationStateIsOccupied = queryAzElTimeObstacle( ...
    obstacleField, destinationState.position_deg(1), ...
    destinationState.position_deg(2), destinationState.time_s, ...
    options.collisionQueryOptions);
if specifiedInitialStateIsOccupied
    error("planSimpleAzElTimeKinodynamicDijkstra:InitialStateOccupied", ...
        "The specified initial state is occupied.");
end
if specifiedDestinationStateIsOccupied
    error("planSimpleAzElTimeKinodynamicDijkstra:DestinationStateOccupied", ...
        "The specified destination state is occupied.");
end

%% Section 6: Define The Discrete Jerk Commands
if isempty(options.jerkCommands_deg_s3)
    azimuthJerkValues_deg_s3 = ...
        [-limits.maxJerk_deg_s3(1), 0, limits.maxJerk_deg_s3(1)];
    elevationJerkValues_deg_s3 = ...
        [-limits.maxJerk_deg_s3(2), 0, limits.maxJerk_deg_s3(2)];
    [azimuthJerkMesh_deg_s3, elevationJerkMesh_deg_s3] = ndgrid( ...
        azimuthJerkValues_deg_s3, elevationJerkValues_deg_s3);
    jerkCommands_deg_s3 = [ ...
        azimuthJerkMesh_deg_s3(:), elevationJerkMesh_deg_s3(:)];
else
    jerkCommands_deg_s3 = options.jerkCommands_deg_s3;
end
jerkCommands_deg_s3 = unique(jerkCommands_deg_s3, "rows", "stable");

%% Section 7: Initialize Dijkstra
maximumGeneratedStates = options.maximumGeneratedStates;
stateSubscripts = zeros(maximumGeneratedStates, 7, "uint32");
statePosition_deg = nan(maximumGeneratedStates, 2);
stateVelocity_deg_s = nan(maximumGeneratedStates, 2);
stateAcceleration_deg_s2 = nan(maximumGeneratedStates, 2);
stateTime_s = nan(maximumGeneratedStates, 1);

% The three lines below are the recognizable Dijkstra initialization.
bestKnownCost = inf(maximumGeneratedStates, 1);
parentStateIndex = zeros(maximumGeneratedStates, 1, "uint32");
parentJerk_deg_s3 = nan(maximumGeneratedStates, 2);
isSettled = false(maximumGeneratedStates, 1);

generatedStateCount = 1;
stateSubscripts(1, :) = uint32(initialSubscripts);
statePosition_deg(1, :) = mappedInitialPosition_deg;
stateVelocity_deg_s(1, :) = mappedInitialVelocity_deg_s;
stateAcceleration_deg_s2(1, :) = mappedInitialAcceleration_deg_s2;
stateTime_s(1) = timeGrid_s(1);
bestKnownCost(1) = 0;
parentJerk_deg_s3(1, :) = [0, 0];

initialStateKey = sprintf("%d|%d|%d|%d|%d|%d|%d", initialSubscripts);
stateIndexByKey = containers.Map( ...
    "KeyType", "char", "ValueType", "double");
stateIndexByKey(initialStateKey) = 1;
destinationStateIndex = 0;
expandedStateCount = 0;
reachedGeneratedStateLimit = false;
reachedExpandedStateLimit = false;

%% Section 8: Propagate Candidate Kinodynamic States
while true
    unsettledStateIndices = find( ...
        ~isSettled(1:generatedStateCount) & ...
        isfinite(bestKnownCost(1:generatedStateCount)));
    if isempty(unsettledStateIndices)
        break;
    end

    % Basic Dijkstra node selection is intentionally visible. A heap can
    % replace only this selection step if profiling later justifies it.
    [~, minimumCostLocation] = min( ...
        bestKnownCost(unsettledStateIndices));
    currentStateIndex = unsettledStateIndices(minimumCostLocation);
    isSettled(currentStateIndex) = true;
    expandedStateCount = expandedStateCount + 1;

    currentPosition_deg = statePosition_deg(currentStateIndex, :);
    currentVelocity_deg_s = stateVelocity_deg_s(currentStateIndex, :);
    currentAcceleration_deg_s2 = ...
        stateAcceleration_deg_s2(currentStateIndex, :);
    currentTime_s = stateTime_s(currentStateIndex);
    currentTimeIndex = double(stateSubscripts(currentStateIndex, 3));

    % The terminal tolerances apply to the specified destination, not its
    % nearest grid proxy. A coarse level therefore fails honestly when it
    % cannot represent the requested endpoint closely enough.
    azimuthError_deg = mod(destinationState.position_deg(1) - ...
        currentPosition_deg(1) + 180, 360) - 180;
    if ~options.allowAzimuthWrap
        azimuthError_deg = destinationState.position_deg(1) - ...
            currentPosition_deg(1);
    end
    positionError_deg = [ ...
        azimuthError_deg, ...
        destinationState.position_deg(2) - currentPosition_deg(2)];
    velocityError_deg_s = ...
        destinationState.velocity_deg_s - currentVelocity_deg_s;
    accelerationError_deg_s2 = ...
        destinationState.acceleration_deg_s2 - ...
        currentAcceleration_deg_s2;
    timeError_s = destinationState.time_s - currentTime_s;

    isDestinationState = ...
        all(abs(positionError_deg) <= options.positionTolerance_deg) && ...
        all(abs(velocityError_deg_s) <= options.velocityTolerance_deg_s) && ...
        all(abs(accelerationError_deg_s2) <= ...
        options.accelerationTolerance_deg_s2) && ...
        abs(timeError_s) <= options.timeTolerance_s;
    if isDestinationState
        destinationStateIndex = currentStateIndex;
        break;
    end
    if expandedStateCount >= options.maximumExpandedStates
        reachedExpandedStateLimit = true;
        break;
    end
    if currentTimeIndex >= numel(timeGrid_s)
        continue;
    end

    for jerkCommandIndex = 1:size(jerkCommands_deg_s3, 1)
        appliedJerk_deg_s3 = jerkCommands_deg_s3(jerkCommandIndex, :);

        % One constant jerk command propagates acceleration, then velocity,
        % then position independently on the two axes.
        nextAcceleration_deg_s2 = currentAcceleration_deg_s2 + ...
            appliedJerk_deg_s3 * timeStep_s;
        nextVelocity_deg_s = currentVelocity_deg_s + ...
            currentAcceleration_deg_s2 * timeStep_s + ...
            0.5 * appliedJerk_deg_s3 * timeStep_s^2;
        propagatedPosition_deg = currentPosition_deg + ...
            currentVelocity_deg_s * timeStep_s + ...
            0.5 * currentAcceleration_deg_s2 * timeStep_s^2 + ...
            (1 / 6) * appliedJerk_deg_s3 * timeStep_s^3;

        % --- Section 9: Check Limits And Collision -----------------------
        % A dashed stage keeps the search loop uninterrupted while making
        % the requested limit and collision responsibility easy to locate.
        dynamicsAreInsideLimits = ...
            all(abs(nextVelocity_deg_s) <= ...
            limits.maxVelocity_deg_s + limitTolerance) && ...
            all(abs(nextAcceleration_deg_s2) <= ...
            limits.maxAcceleration_deg_s2 + limitTolerance);
        elevationIsInsideLimits = ...
            propagatedPosition_deg(2) >= ...
            limits.elevation_deg(1) - limitTolerance && ...
            propagatedPosition_deg(2) <= ...
            limits.elevation_deg(2) + limitTolerance;
        azimuthIsInsideLimits = options.allowAzimuthWrap || ( ...
            propagatedPosition_deg(1) >= ...
            limits.azimuth_deg(1) - limitTolerance && ...
            propagatedPosition_deg(1) <= ...
            limits.azimuth_deg(2) + limitTolerance);

        % Endpoint checks alone are insufficient: quadratic velocity can
        % peak where acceleration crosses zero, and cubic position can turn
        % where velocity crosses zero. Test those analytic interior extrema
        % before accepting the constant-jerk transition.
        for axisIndex = 1:2
            axisJerk_deg_s3 = appliedJerk_deg_s3(axisIndex);
            axisAcceleration_deg_s2 = ...
                currentAcceleration_deg_s2(axisIndex);
            axisVelocity_deg_s = currentVelocity_deg_s(axisIndex);

            if abs(axisJerk_deg_s3) > limitTolerance
                velocityExtremumTime_s = ...
                    -axisAcceleration_deg_s2 / axisJerk_deg_s3;
                velocityExtremumIsInterior = ...
                    velocityExtremumTime_s > 0 && ...
                    velocityExtremumTime_s < timeStep_s;
                if velocityExtremumIsInterior
                    velocityExtremum_deg_s = axisVelocity_deg_s + ...
                        axisAcceleration_deg_s2 * velocityExtremumTime_s + ...
                        0.5 * axisJerk_deg_s3 * velocityExtremumTime_s^2;
                    dynamicsAreInsideLimits = dynamicsAreInsideLimits && ...
                        abs(velocityExtremum_deg_s) <= ...
                        limits.maxVelocity_deg_s(axisIndex) + limitTolerance;
                end
            end

            axisRequiresPositionBounds = ...
                axisIndex == 2 || ~options.allowAzimuthWrap;
            if ~axisRequiresPositionBounds
                continue;
            end
            if axisIndex == 1
                axisPositionLimits_deg = limits.azimuth_deg;
            else
                axisPositionLimits_deg = limits.elevation_deg;
            end

            positionExtremumTimes_s = zeros(2, 1);
            positionExtremumCount = 0;
            if abs(axisJerk_deg_s3) <= limitTolerance
                if abs(axisAcceleration_deg_s2) > limitTolerance
                    positionExtremumCount = 1;
                    positionExtremumTimes_s(1) = ...
                        -axisVelocity_deg_s / axisAcceleration_deg_s2;
                end
            else
                velocityDiscriminant_deg2_s4 = ...
                    axisAcceleration_deg_s2^2 - ...
                    2 * axisJerk_deg_s3 * axisVelocity_deg_s;
                if velocityDiscriminant_deg2_s4 >= 0
                    velocityRootTerm_deg_s2 = ...
                        sqrt(velocityDiscriminant_deg2_s4);
                    positionExtremumCount = 2;
                    positionExtremumTimes_s = [ ...
                        (-axisAcceleration_deg_s2 - ...
                        velocityRootTerm_deg_s2) / axisJerk_deg_s3; ...
                        (-axisAcceleration_deg_s2 + ...
                        velocityRootTerm_deg_s2) / axisJerk_deg_s3];
                end
            end
            for extremumIndex = 1:positionExtremumCount
                positionExtremumTime_s = ...
                    positionExtremumTimes_s(extremumIndex);
                positionExtremumIsInterior = ...
                    positionExtremumTime_s > 0 && ...
                    positionExtremumTime_s < timeStep_s;
                if ~positionExtremumIsInterior
                    continue;
                end
                positionExtremum_deg = currentPosition_deg(axisIndex) + ...
                    axisVelocity_deg_s * positionExtremumTime_s + ...
                    0.5 * axisAcceleration_deg_s2 * ...
                    positionExtremumTime_s^2 + ...
                    (1 / 6) * axisJerk_deg_s3 * ...
                    positionExtremumTime_s^3;
                extremumIsInsidePositionLimits = ...
                    positionExtremum_deg >= ...
                    axisPositionLimits_deg(1) - limitTolerance && ...
                    positionExtremum_deg <= ...
                    axisPositionLimits_deg(2) + limitTolerance;
                if axisIndex == 1
                    azimuthIsInsideLimits = azimuthIsInsideLimits && ...
                        extremumIsInsidePositionLimits;
                else
                    elevationIsInsideLimits = elevationIsInsideLimits && ...
                        extremumIsInsidePositionLimits;
                end
            end
        end
        if ~dynamicsAreInsideLimits || ~elevationIsInsideLimits || ...
                ~azimuthIsInsideLimits
            continue;
        end

        if options.allowAzimuthWrap
            propagatedPosition_deg(1) = mod( ...
                propagatedPosition_deg(1) - limits.azimuth_deg(1), 360) + ...
                limits.azimuth_deg(1);
        end

        % Nearest-axis snapping is the only approximation used to create a
        % finite successor lattice. Its half-cell error bounds are returned
        % in plan.maximumDiscretizationError.
        if options.allowAzimuthWrap
            candidateAzimuthDifference_deg = mod(azimuthGrid_deg - ...
                propagatedPosition_deg(1) + 180, 360) - 180;
        else
            candidateAzimuthDifference_deg = ...
                azimuthGrid_deg - propagatedPosition_deg(1);
        end
        [~, neighborAzimuthIndex] = min( ...
            abs(candidateAzimuthDifference_deg));
        [~, neighborElevationIndex] = min(abs( ...
            elevationGrid_deg - propagatedPosition_deg(2)));
        [~, neighborAzimuthVelocityIndex] = min(abs( ...
            azimuthVelocityGrid_deg_s - nextVelocity_deg_s(1)));
        [~, neighborElevationVelocityIndex] = min(abs( ...
            elevationVelocityGrid_deg_s - nextVelocity_deg_s(2)));
        [~, neighborAzimuthAccelerationIndex] = min(abs( ...
            azimuthAccelerationGrid_deg_s2 - nextAcceleration_deg_s2(1)));
        [~, neighborElevationAccelerationIndex] = min(abs( ...
            elevationAccelerationGrid_deg_s2 - nextAcceleration_deg_s2(2)));
        neighborTimeIndex = currentTimeIndex + 1;

        if occupancy(neighborElevationIndex, neighborAzimuthIndex, ...
                neighborTimeIndex)
            continue;
        end
        transitionIsBlocked = simpleDijkstraTransitionHasCollision( ...
            obstacleField, currentPosition_deg, currentVelocity_deg_s, ...
            currentAcceleration_deg_s2, appliedJerk_deg_s3, ...
            currentTime_s, timeStep_s, options.collisionCheckStep_s, ...
            limits, options);
        if transitionIsBlocked
            continue;
        end

        neighborSubscripts = [ ...
            neighborAzimuthIndex, neighborElevationIndex, ...
            neighborTimeIndex, neighborAzimuthVelocityIndex, ...
            neighborElevationVelocityIndex, ...
            neighborAzimuthAccelerationIndex, ...
            neighborElevationAccelerationIndex];
        neighborStateKey = sprintf( ...
            "%d|%d|%d|%d|%d|%d|%d", neighborSubscripts);

        if isKey(stateIndexByKey, neighborStateKey)
            neighborStateIndex = stateIndexByKey(neighborStateKey);
        else
            if generatedStateCount >= maximumGeneratedStates
                reachedGeneratedStateLimit = true;
                break;
            end
            generatedStateCount = generatedStateCount + 1;
            neighborStateIndex = generatedStateCount;
            stateIndexByKey(neighborStateKey) = neighborStateIndex;
            stateSubscripts(neighborStateIndex, :) = ...
                uint32(neighborSubscripts);
            statePosition_deg(neighborStateIndex, :) = [ ...
                azimuthGrid_deg(neighborAzimuthIndex), ...
                elevationGrid_deg(neighborElevationIndex)];
            stateVelocity_deg_s(neighborStateIndex, :) = [ ...
                azimuthVelocityGrid_deg_s(neighborAzimuthVelocityIndex), ...
                elevationVelocityGrid_deg_s( ...
                neighborElevationVelocityIndex)];
            stateAcceleration_deg_s2(neighborStateIndex, :) = [ ...
                azimuthAccelerationGrid_deg_s2( ...
                neighborAzimuthAccelerationIndex), ...
                elevationAccelerationGrid_deg_s2( ...
                neighborElevationAccelerationIndex)];
            stateTime_s(neighborStateIndex) = ...
                timeGrid_s(neighborTimeIndex);
        end

        % --- Section 10: Relax Dijkstra Costs ----------------------------
        transitionCost = timeStep_s + ...
            options.accelerationWeight * ...
            sum(nextAcceleration_deg_s2.^2) * timeStep_s + ...
            options.jerkWeight * sum(appliedJerk_deg_s3.^2) * timeStep_s;
        currentCost = bestKnownCost(currentStateIndex);
        candidateCost = currentCost + transitionCost;

        if candidateCost < bestKnownCost(neighborStateIndex)
            bestKnownCost(neighborStateIndex) = candidateCost;
            parentStateIndex(neighborStateIndex) = ...
                uint32(currentStateIndex);
            parentJerk_deg_s3(neighborStateIndex, :) = ...
                appliedJerk_deg_s3;
        end
    end
    if reachedGeneratedStateLimit
        break;
    end
end

%% Section 11: Reconstruct The Trajectory
if destinationStateIndex > 0
    trajectoryStateIndices = reconstructSimpleDijkstraParents( ...
        parentStateIndex, destinationStateIndex);
    trajectoryTime_s = stateTime_s(trajectoryStateIndices);
    trajectoryPosition_deg = statePosition_deg(trajectoryStateIndices, :);
    trajectoryVelocity_deg_s = ...
        stateVelocity_deg_s(trajectoryStateIndices, :);
    trajectoryAcceleration_deg_s2 = ...
        stateAcceleration_deg_s2(trajectoryStateIndices, :);
    trajectoryJerk_deg_s3 = parentJerk_deg_s3(trajectoryStateIndices, :);

    trajectoryPositionUnwrapped_deg = trajectoryPosition_deg;
    for trajectoryIndex = 2:numel(trajectoryStateIndices)
        wrappedAzimuthStep_deg = mod( ...
            trajectoryPosition_deg(trajectoryIndex, 1) - ...
            trajectoryPosition_deg(trajectoryIndex - 1, 1) + 180, 360) - 180;
        trajectoryPositionUnwrapped_deg(trajectoryIndex, 1) = ...
            trajectoryPositionUnwrapped_deg(trajectoryIndex - 1, 1) + ...
            wrappedAzimuthStep_deg;
    end

    trajectoryIsWaiting = false(numel(trajectoryStateIndices), 1);
    % This dynamics tolerance only absorbs floating-point zero; position
    % equality remains governed by the public waitingTolerance_deg option.
    holdDynamicsTolerance = 1e-12;
    for trajectoryIndex = 2:numel(trajectoryStateIndices)
        previousIndex = trajectoryIndex - 1;
        wrappedPositionChange_deg = mod( ...
            trajectoryPosition_deg(trajectoryIndex, 1) - ...
            trajectoryPosition_deg(previousIndex, 1) + 180, 360) - 180;
        positionDidNotChange = ...
            abs(wrappedPositionChange_deg) <= options.waitingTolerance_deg && ...
            abs(trajectoryPosition_deg(trajectoryIndex, 2) - ...
            trajectoryPosition_deg(previousIndex, 2)) <= ...
            options.waitingTolerance_deg;
        dynamicsDescribeTrueHold = all(abs( ...
            trajectoryVelocity_deg_s(previousIndex, :)) <= ...
            holdDynamicsTolerance) && ...
            all(abs(trajectoryAcceleration_deg_s2(previousIndex, :)) <= ...
            holdDynamicsTolerance) && all(abs( ...
            trajectoryJerk_deg_s3(trajectoryIndex, :)) <= ...
            holdDynamicsTolerance);
        trajectoryIsWaiting(trajectoryIndex) = ...
            positionDidNotChange && dynamicsDescribeTrueHold;
    end
else
    trajectoryStateIndices = zeros(0, 1);
    trajectoryTime_s = zeros(0, 1);
    trajectoryPosition_deg = zeros(0, 2);
    trajectoryPositionUnwrapped_deg = zeros(0, 2);
    trajectoryVelocity_deg_s = zeros(0, 2);
    trajectoryAcceleration_deg_s2 = zeros(0, 2);
    trajectoryJerk_deg_s3 = zeros(0, 2);
    trajectoryIsWaiting = false(0, 1);
end

%% Section 12: Package The Result
if destinationStateIndex > 0
    success = true;
    message = "Exact-time kinodynamic Dijkstra trajectory found.";
    totalCost = bestKnownCost(destinationStateIndex);
elseif reachedGeneratedStateLimit
    success = false;
    message = "Search reached options.maximumGeneratedStates.";
    totalCost = Inf;
elseif reachedExpandedStateLimit
    success = false;
    message = "Search reached options.maximumExpandedStates.";
    totalCost = Inf;
else
    success = false;
    message = "No discretized kinodynamic trajectory reaches the destination.";
    totalCost = Inf;
end

generatedRange = 1:generatedStateCount;
plan = struct( ...
    "success", success, ...
    "message", message, ...
    "time_s", trajectoryTime_s, ...
    "position_deg", trajectoryPosition_deg, ...
    "positionUnwrapped_deg", trajectoryPositionUnwrapped_deg, ...
    "velocity_deg_s", trajectoryVelocity_deg_s, ...
    "acceleration_deg_s2", trajectoryAcceleration_deg_s2, ...
    "jerk_deg_s3", trajectoryJerk_deg_s3, ...
    "isWaiting", trajectoryIsWaiting, ...
    "stateIndices", trajectoryStateIndices, ...
    "totalCost", totalCost, ...
    "expandedStateCount", expandedStateCount, ...
    "generatedStateCount", generatedStateCount, ...
    "azimuthGrid_deg", azimuthGrid_deg, ...
    "elevationGrid_deg", elevationGrid_deg, ...
    "timeGrid_s", timeGrid_s, ...
    "azimuthVelocityGrid_deg_s", azimuthVelocityGrid_deg_s, ...
    "elevationVelocityGrid_deg_s", elevationVelocityGrid_deg_s, ...
    "azimuthAccelerationGrid_deg_s2", ...
    azimuthAccelerationGrid_deg_s2, ...
    "elevationAccelerationGrid_deg_s2", ...
    elevationAccelerationGrid_deg_s2, ...
    "jerkCommands_deg_s3", jerkCommands_deg_s3, ...
    "occupancy", occupancy, ...
    "settledStateIndices", find(isSettled(generatedRange)), ...
    "bestKnownCost", bestKnownCost(generatedRange), ...
    "parentStateIndex", parentStateIndex(generatedRange), ...
    "parentJerk_deg_s3", parentJerk_deg_s3(generatedRange, :), ...
    "stateSubscripts", stateSubscripts(generatedRange, :), ...
    "statePosition_deg", statePosition_deg(generatedRange, :), ...
    "stateVelocity_deg_s", stateVelocity_deg_s(generatedRange, :), ...
    "stateAcceleration_deg_s2", ...
    stateAcceleration_deg_s2(generatedRange, :), ...
    "stateTime_s", stateTime_s(generatedRange), ...
    "exactCollisionValidated", false, ...
    "sampledCollisionValidated", success, ...
    "initialState", initialState, ...
    "destinationState", destinationState, ...
    "mappedInitialState", struct( ...
        "Subscripts", initialSubscripts, ...
        "Position_deg", mappedInitialPosition_deg, ...
        "Velocity_deg_s", mappedInitialVelocity_deg_s, ...
        "Acceleration_deg_s2", mappedInitialAcceleration_deg_s2), ...
    "mappedDestinationState", struct( ...
        "Subscripts", destinationSubscripts, ...
        "Position_deg", mappedDestinationPosition_deg, ...
        "Velocity_deg_s", mappedDestinationVelocity_deg_s, ...
        "Acceleration_deg_s2", mappedDestinationAcceleration_deg_s2), ...
    "maximumDiscretizationError", struct( ...
        "Position_deg", options.positionStep_deg / 2, ...
        "Velocity_deg_s", options.velocityStep_deg_s / 2, ...
        "Acceleration_deg_s2", options.accelerationStep_deg_s2 / 2), ...
    "gridRefinement", struct( ...
        "Used", false, ...
        "Schedule_deg", options.positionStep_deg(1), ...
        "Levels", struct.empty(0, 1), ...
        "SelectedLevelIndex", 1, ...
        "SelectedPositionStep_deg", options.positionStep_deg(1), ...
        "FinestLevelSucceeded", success, ...
        "TotalExpandedStateCount", expandedStateCount, ...
        "TotalGeneratedStateCount", generatedStateCount), ...
    "obstacleField", obstacleField, ...
    "limits", limits, ...
    "options", options);
end

%% Section 13: Local Functions
function options = defaultSimpleDijkstraOptions()
%% Section 0: Header & Readme
% SYNTAX
%   options = defaultSimpleDijkstraOptions()
%**************************************************************************
% PURPOSE
%   - Keep simple-planner defaults in one inspectable source of truth.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Fully populated default planner options.
%**************************************************************************
% UNITS
%   - Field suffixes state their physical units.
options = struct( ...
    "timeStep_s", 1, ...
    "positionStep_deg", [1, 1], ...
    "positionStepSchedule_deg", zeros(1, 0), ...
    "velocityStep_deg_s", [1, 1], ...
    "accelerationStep_deg_s2", [1, 1], ...
    "jerkCommands_deg_s3", zeros(0, 2), ...
    "allowAzimuthWrap", true, ...
    "collisionCheckStep_s", 0.25, ...
    "collisionQueryOptions", struct( ...
        "CollisionMode", "polygon", ...
        "TimePaddingSamples", 0, ...
        "BoundsMarginDeg", [0, 0], ...
        "SafetyMarginDeg", 0), ...
    "positionTolerance_deg", [0.5, 0.5], ...
    "velocityTolerance_deg_s", [0.5, 0.5], ...
    "accelerationTolerance_deg_s2", [0.5, 0.5], ...
    "timeTolerance_s", 1e-9, ...
    "waitingTolerance_deg", 1e-9, ...
    "accelerationWeight", 0, ...
    "jerkWeight", 0, ...
    "maximumOccupancyCells", 2e7, ...
    "maximumGeneratedStates", 100000, ...
    "maximumExpandedStates", 100000);
end

function limits = normalizeSimpleDijkstraLimits(limits)
%% Section 0: Header & Readme
% SYNTAX
%   limits = normalizeSimpleDijkstraLimits(limits)
%**************************************************************************
% PURPOSE
%   - Validate and normalize all simple-planner physical limits.
%**************************************************************************
% INPUTS
%   - limits (scalar struct)
%       Limit fields documented on the public planner.
%**************************************************************************
% OUTPUTS
%   - limits (scalar struct)
%       Double row vectors with two-axis dynamic magnitudes.
%**************************************************************************
% UNITS
%   - Field suffixes state their physical units.
requiredFields = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2", "maxJerk_deg_s3"];
if ~isstruct(limits) || ~isscalar(limits) || ...
        ~all(isfield(limits, cellstr(requiredFields)))
    error("planSimpleAzElTimeKinodynamicDijkstra:InvalidLimits", ...
        "limits must contain %s.", strjoin(requiredFields, ", "));
end
validateattributes(limits.azimuth_deg, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'increasing'});
validateattributes(limits.elevation_deg, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'increasing'});
limits.azimuth_deg = reshape(double(limits.azimuth_deg), 1, 2);
limits.elevation_deg = reshape(double(limits.elevation_deg), 1, 2);
dynamicFields = [ ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2", "maxJerk_deg_s3"];
for fieldName = dynamicFields
    value = limits.(fieldName);
    validateattributes(value, {'numeric'}, ...
        {'vector', 'real', 'finite', 'positive'});
    if isscalar(value)
        value = repmat(value, 1, 2);
    elseif numel(value) ~= 2
        error("planSimpleAzElTimeKinodynamicDijkstra:InvalidLimits", ...
            "limits.%s must be scalar or [azimuth elevation].", fieldName);
    end
    limits.(fieldName) = reshape(double(value), 1, 2);
end
end

function endpointState = normalizeSimpleDijkstraState( ...
        endpointState, argumentName)
%% Section 0: Header & Readme
% SYNTAX
%   endpointState = normalizeSimpleDijkstraState( ...
%       endpointState, argumentName)
%**************************************************************************
% PURPOSE
%   - Validate one complete azimuth/elevation kinodynamic endpoint.
%**************************************************************************
% INPUTS
%   - endpointState (scalar struct)
%       Complete state fields documented on the public planner.
%   - argumentName (text scalar)
%       Name used in diagnostics.
%**************************************************************************
% OUTPUTS
%   - endpointState (scalar struct)
%       Normalized double scalar time and two-element row vectors.
%**************************************************************************
% UNITS
%   - Field suffixes state their physical units.
requiredFields = ["time_s", "position_deg", "velocity_deg_s", ...
    "acceleration_deg_s2"];
if ~isstruct(endpointState) || ~isscalar(endpointState) || ...
        ~all(isfield(endpointState, cellstr(requiredFields)))
    error("planSimpleAzElTimeKinodynamicDijkstra:InvalidState", ...
        "%s must contain %s.", argumentName, strjoin(requiredFields, ", "));
end
validateattributes(endpointState.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
endpointState.time_s = double(endpointState.time_s);
vectorFields = ["position_deg", "velocity_deg_s", ...
    "acceleration_deg_s2"];
for fieldName = vectorFields
    validateattributes(endpointState.(fieldName), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    endpointState.(fieldName) = reshape( ...
        double(endpointState.(fieldName)), 1, 2);
end
end

function options = resolveSimpleDijkstraOptions( ...
        options, defaultOptions, limits)
%% Section 0: Header & Readme
% SYNTAX
%   options = resolveSimpleDijkstraOptions(options, defaults, limits)
%**************************************************************************
% PURPOSE
%   - Apply defaults and validate lattice compatibility before allocation.
%**************************************************************************
% INPUTS
%   - options (scalar struct)
%       Requested partial planner options.
%   - defaultOptions (scalar struct)
%       Fully populated argument-independent defaults.
%   - limits (scalar struct)
%       Normalized physical limits.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Resolved and validated options.
%**************************************************************************
% UNITS
%   - Field suffixes state their physical units.
if ~isstruct(options) || ~isscalar(options)
    error("planSimpleAzElTimeKinodynamicDijkstra:InvalidOptions", ...
        "options must be a scalar struct.");
end
unknownFields = setdiff(fieldnames(options), fieldnames(defaultOptions), ...
    "stable");
if ~isempty(unknownFields)
    warning("planSimpleAzElTimeKinodynamicDijkstra:UnknownOptions", ...
        "Ignoring unknown option fields: %s.", ...
        strjoin(string(unknownFields), ", "));
    options = rmfield(options, unknownFields);
end
resolvedOptions = defaultOptions;
providedFields = fieldnames(options);
for fieldIndex = 1:numel(providedFields)
    fieldName = providedFields{fieldIndex};
    if ~isempty(options.(fieldName)) || fieldName == "jerkCommands_deg_s3"
        resolvedOptions.(fieldName) = options.(fieldName);
    end
end
options = resolvedOptions;

% Grid ratios within this relative-scale tolerance represent the same
% integer cell count despite floating-point division noise.
gridCompatibilityTolerance = 1e-9;
limitTolerance = 1e-12;

validateattributes(options.timeStep_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
stepFields = ["positionStep_deg", "velocityStep_deg_s", ...
    "accelerationStep_deg_s2"];
for fieldName = stepFields
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite', 'positive'});
    options.(fieldName) = reshape(double(options.(fieldName)), 1, 2);
end
validateattributes(options.positionStepSchedule_deg, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
options.positionStepSchedule_deg = unique( ...
    double(options.positionStepSchedule_deg(:).'), "stable");
options.positionStepSchedule_deg = sort( ...
    options.positionStepSchedule_deg, "descend");
validateattributes(options.allowAzimuthWrap, ...
    {'logical', 'numeric'}, {'scalar'});
options.allowAzimuthWrap = logical(options.allowAzimuthWrap);
if options.allowAzimuthWrap && abs(diff(limits.azimuth_deg) - 360) > ...
        gridCompatibilityTolerance
    error("planSimpleAzElTimeKinodynamicDijkstra:InvalidWrappedDomain", ...
        "Azimuth wrapping requires a complete 360-degree domain.");
end
validateattributes(options.collisionCheckStep_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
if ~isstruct(options.collisionQueryOptions) || ...
        ~isscalar(options.collisionQueryOptions)
    error("planSimpleAzElTimeKinodynamicDijkstra:InvalidCollisionOptions", ...
        "collisionQueryOptions must be a scalar struct.");
end

toleranceFields = ["positionTolerance_deg", ...
    "velocityTolerance_deg_s", "accelerationTolerance_deg_s2"];
for fieldName = toleranceFields
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite', 'nonnegative'});
    options.(fieldName) = reshape(double(options.(fieldName)), 1, 2);
end
validateattributes(options.timeTolerance_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.waitingTolerance_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.accelerationWeight, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.jerkWeight, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
countFields = ["maximumOccupancyCells", "maximumGeneratedStates", ...
    "maximumExpandedStates"];
for fieldName = countFields
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'});
    options.(fieldName) = double(options.(fieldName));
end

if isempty(options.jerkCommands_deg_s3)
    options.jerkCommands_deg_s3 = zeros(0, 2);
else
    validateattributes(options.jerkCommands_deg_s3, {'numeric'}, ...
        {'2d', 'ncols', 2, 'real', 'finite'});
    options.jerkCommands_deg_s3 = double(options.jerkCommands_deg_s3);
    if any(any(abs(options.jerkCommands_deg_s3) > ...
            limits.maxJerk_deg_s3 + limitTolerance))
        error("planSimpleAzElTimeKinodynamicDijkstra:JerkLimitExceeded", ...
            "Every configured jerk command must satisfy limits.maxJerk_deg_s3.");
    end
end

velocityCellCounts = limits.maxVelocity_deg_s ./ ...
    options.velocityStep_deg_s;
accelerationCellCounts = limits.maxAcceleration_deg_s2 ./ ...
    options.accelerationStep_deg_s2;
dynamicCellCounts = [velocityCellCounts, accelerationCellCounts];
if any(abs(dynamicCellCounts - round(dynamicCellCounts)) > ...
        gridCompatibilityTolerance)
    error("planSimpleAzElTimeKinodynamicDijkstra:IncompatibleGrid", ...
        ["Positive velocity and acceleration limits must be integer " ...
        "multiples of their corresponding grid steps."]);
end
if isempty(options.positionStepSchedule_deg)
    positionCellCounts = [diff(limits.azimuth_deg), ...
        diff(limits.elevation_deg)] ./ options.positionStep_deg;
    if any(abs(positionCellCounts - round(positionCellCounts)) > ...
            gridCompatibilityTolerance)
        error("planSimpleAzElTimeKinodynamicDijkstra:IncompatibleGrid", ...
            ["Position spans must be integer multiples of their " ...
            "corresponding position grid steps."]);
    end
else
    scheduledPositionCellCounts = [diff(limits.azimuth_deg); ...
        diff(limits.elevation_deg)] ./ options.positionStepSchedule_deg;
    if any(abs(scheduledPositionCellCounts - ...
            round(scheduledPositionCellCounts)) > ...
            gridCompatibilityTolerance, "all")
        error("planSimpleAzElTimeKinodynamicDijkstra:IncompatibleSchedule", ...
            ["Every positionStepSchedule_deg value must divide both the " ...
            "azimuth and elevation spans into an integer number of cells."]);
    end
end
end

function plan = runSimpleDijkstraGridRefinement( ...
        azElData, initialState, destinationState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   plan = runSimpleDijkstraGridRefinement( ...
%       azElData, initialState, destinationState, limits, options)
%**************************************************************************
% PURPOSE
%   - Run independent coarse-to-fine simple Dijkstra lattices.
%   - Continue after a coarse failure and return the finest successful plan.
%**************************************************************************
% INPUTS
%   - azElData (struct array or cell array)
%       Canonical moving obstacle data.
%   - initialState, destinationState (scalar structs)
%       Validated complete endpoint states.
%   - limits (scalar struct)
%       Validated physical limits.
%   - options (scalar struct)
%       Resolved options with positionStepSchedule_deg set.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Finest successful level, or the finest failure when none succeeds,
%       plus a compact summary of every attempted resolution.
%**************************************************************************
% UNITS
%   - Position lattice steps are degrees.
schedule_deg = options.positionStepSchedule_deg;
levelTemplate = struct( ...
    "PositionStep_deg", NaN, ...
    "Success", false, ...
    "Message", "", ...
    "TotalCost", Inf, ...
    "ExpandedStateCount", 0, ...
    "GeneratedStateCount", 0, ...
    "SearchElapsed_s", 0, ...
    "Selected", false);
levels = repmat(levelTemplate, numel(schedule_deg), 1);
selectedLevelIndex = 0;
selectedPlan = struct();

for levelIndex = 1:numel(schedule_deg)
    levelOptions = options;
    levelOptions.positionStepSchedule_deg = zeros(1, 0);
    levelOptions.positionStep_deg = repmat(schedule_deg(levelIndex), 1, 2);

    levelTimer = tic;
    levelPlan = planSimpleAzElTimeKinodynamicDijkstra( ...
        azElData, initialState, destinationState, limits, levelOptions);
    searchElapsed_s = toc(levelTimer);
    levels(levelIndex) = struct( ...
        "PositionStep_deg", schedule_deg(levelIndex), ...
        "Success", levelPlan.success, ...
        "Message", string(levelPlan.message), ...
        "TotalCost", levelPlan.totalCost, ...
        "ExpandedStateCount", levelPlan.expandedStateCount, ...
        "GeneratedStateCount", levelPlan.generatedStateCount, ...
        "SearchElapsed_s", searchElapsed_s, ...
        "Selected", false);

    % The schedule is descending, so every later success is a finer plan.
    % Coarse results seed confidence and diagnostics, not a hidden corridor.
    if levelPlan.success
        selectedLevelIndex = levelIndex;
        selectedPlan = levelPlan;
    elseif selectedLevelIndex == 0
        selectedPlan = levelPlan;
    end
end

if selectedLevelIndex == 0
    selectedLevelIndex = numel(schedule_deg);
end
levels(selectedLevelIndex).Selected = true;
plan = selectedPlan;
plan.options.positionStepSchedule_deg = schedule_deg;
plan.options.positionStep_deg = ...
    repmat(schedule_deg(selectedLevelIndex), 1, 2);
plan.gridRefinement = struct( ...
    "Used", true, ...
    "Schedule_deg", schedule_deg, ...
    "Levels", levels, ...
    "SelectedLevelIndex", selectedLevelIndex, ...
    "SelectedPositionStep_deg", schedule_deg(selectedLevelIndex), ...
    "FinestLevelSucceeded", levels(end).Success, ...
    "TotalExpandedStateCount", sum([levels.ExpandedStateCount]), ...
    "TotalGeneratedStateCount", sum([levels.GeneratedStateCount]));
if plan.success
    plan.message = sprintf( ...
        "Grid refinement selected the %.4g-degree successful lattice.", ...
        schedule_deg(selectedLevelIndex));
else
    plan.message = sprintf( ...
        "No grid-refinement level succeeded; finest result: %s", ...
        levels(end).Message);
end
end

function isBlocked = simpleDijkstraTransitionHasCollision( ...
        obstacleField, currentPosition_deg, currentVelocity_deg_s, ...
        currentAcceleration_deg_s2, appliedJerk_deg_s3, currentTime_s, ...
        timeStep_s, collisionCheckStep_s, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   isBlocked = simpleDijkstraTransitionHasCollision(...)
%**************************************************************************
% PURPOSE
%   - Sample one complete constant-jerk transition for polygon collision
%     and elevation-bound violations between lattice endpoints.
%**************************************************************************
% INPUTS
%   - obstacleField (scalar struct)
%       Packed moving polygons used by the occupancy raster.
%   - currentPosition_deg (1-by-2 numeric row)
%       Current azimuth and elevation.
%   - currentVelocity_deg_s (1-by-2 numeric row)
%       Current azimuth and elevation velocity.
%   - currentAcceleration_deg_s2 (1-by-2 numeric row)
%       Current azimuth and elevation acceleration.
%   - appliedJerk_deg_s3 (1-by-2 numeric row)
%       Constant jerk command for the transition.
%   - currentTime_s, timeStep_s, collisionCheckStep_s (numeric scalars)
%       Current time, transition duration, and maximum sample spacing.
%   - limits, options (scalar structs)
%       Physical limits and resolved planner options.
%**************************************************************************
% OUTPUTS
%   - isBlocked (logical scalar)
%       True when any sampled point is occupied or outside elevation bounds.
%**************************************************************************
% UNITS
%   - Field and argument suffixes state their physical units.
sampleCount = ceil(timeStep_s / collisionCheckStep_s);
% Sampled elevation checks share the endpoint-limit noise tolerance used by
% the visible search loop; this does not enlarge the discrete state domain.
limitTolerance = 1e-12;
sampleOffset_s = linspace( ...
    timeStep_s / sampleCount, timeStep_s, sampleCount).';
samplePosition_deg = currentPosition_deg + ...
    sampleOffset_s .* currentVelocity_deg_s + ...
    0.5 * sampleOffset_s.^2 .* currentAcceleration_deg_s2 + ...
    (1 / 6) * sampleOffset_s.^3 .* appliedJerk_deg_s3;
if options.allowAzimuthWrap
    samplePosition_deg(:, 1) = mod( ...
        samplePosition_deg(:, 1) - limits.azimuth_deg(1), 360) + ...
        limits.azimuth_deg(1);
end
sampleTime_s = currentTime_s + sampleOffset_s;
sampleOutsideElevation = ...
    samplePosition_deg(:, 2) < ...
    limits.elevation_deg(1) - limitTolerance | ...
    samplePosition_deg(:, 2) > ...
    limits.elevation_deg(2) + limitTolerance;
sampleOccupied = queryAzElTimeObstacle( ...
    obstacleField, samplePosition_deg(:, 1), samplePosition_deg(:, 2), ...
    sampleTime_s, options.collisionQueryOptions);
isBlocked = any(sampleOutsideElevation | sampleOccupied);
end

function trajectoryStateIndices = reconstructSimpleDijkstraParents( ...
        parentStateIndex, destinationStateIndex)
%% Section 0: Header & Readme
% SYNTAX
%   indices = reconstructSimpleDijkstraParents(parents, destinationIndex)
%**************************************************************************
% PURPOSE
%   - Follow stored parents from the destination back to the initial state.
%**************************************************************************
% INPUTS
%   - parentStateIndex (numeric vector)
%       Zero identifies the initial root.
%   - destinationStateIndex (positive integer)
%       Terminal generated-state row.
%**************************************************************************
% OUTPUTS
%   - trajectoryStateIndices (numeric column vector)
%       Initial-to-destination generated-state rows.
%**************************************************************************
% UNITS
%   - Indices are dimensionless.
trajectoryStateIndices = zeros(numel(parentStateIndex), 1);
writeIndex = numel(parentStateIndex);
currentStateIndex = destinationStateIndex;
while currentStateIndex ~= 0
    trajectoryStateIndices(writeIndex) = currentStateIndex;
    writeIndex = writeIndex - 1;
    currentStateIndex = double(parentStateIndex(currentStateIndex));
end
trajectoryStateIndices = trajectoryStateIndices(writeIndex + 1:end);
end
