function plan = planAzElAdaptiveAStar( ...
        azElData, startState, stopState, limits, options)
%PLANAZELADAPTIVEASTAR Plan one exact-checked az/el/time trajectory.
%
% plan = planAzElAdaptiveAStar( ...
%     azElData, startState, stopState, limits, options)
%
% The planner uses one algorithm at progressively finer spatial
% resolutions:
%   1. A spatial state is an az/el grid point.
%   2. Time at that point is compressed into maximal safe intervals.
%   3. A* edges are analytic rest-to-rest slews plus optional waiting.
%   4. Every edge is checked against the original packed polygons.
%
% Coarse levels discover open topology cheaply. Finer levels are attempted
% only when a coarse graph cannot represent a valid route. Obstacle
% geometry is never rasterized, so a coarse search cannot silently approve
% an unsafe trajectory.

timer = tic;
if nargin < 5
    options = struct();
end
[startState, stopState, limits, options] = ...
    normalizeAdaptiveAStarInputs(startState, stopState, limits, options);

if any(abs([startState.velocity_deg_s, stopState.velocity_deg_s, ...
        startState.acceleration_deg_s2, ...
        stopState.acceleration_deg_s2]) > 1e-12)
    error("planAzElAdaptiveAStar:NonzeroBoundaryDynamics", ...
        "The maintainable planner currently requires rest-to-rest " + ...
        "start and stop states.");
end

prebuiltWorkspace = isstruct(azElData) && isscalar(azElData) && ...
    isfield(azElData, "Format") && ...
    string(azElData.Format) == "AzElTimeObstacleWorkspace";
if prebuiltWorkspace
    workspace = azElData;
else
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", options.MaximumVerticesPerRegion));
end

schedule = options.GridStepSchedule_deg(:).';
if options.Objective == "minimumAngularDistance" && ...
        isAzElTimeObstacleWorkspaceStatic( ...
        workspace, startState.time_s, stopState.time_s)
    plan = progressiveStaticAStar( ...
        workspace, startState, stopState, limits, options, schedule, timer);
    if plan.success
        return;
    end
end

attemptTemplate = struct( ...
    "GridStep_deg", NaN, ...
    "PrimitiveRadii_deg", zeros(1, 0), ...
    "Success", false, ...
    "Message", "", ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0, ...
    "TerminationReason", "", ...
    "ObjectiveCost", Inf, ...
    "CandidateTime_s", zeros(0, 1), ...
    "CandidatePosition_deg", zeros(0, 2), ...
    "Selected", false);
attempts = repmat(attemptTemplate, numel(schedule), 1);
attemptCount = 0;
search = struct();
bestSearch = struct();
bestObjective = Inf;
bestGridStep = NaN;
endpointDelta = wrappedDelta( ...
    startState.position_deg, stopState.position_deg, limits, options);
endpointLowerBound = hypot(endpointDelta(1), endpointDelta(2));

for level = 1:numel(schedule)
    remaining = options.MaxSearchTime_s - toc(timer);
    if remaining <= 0
        break;
    end

    levelOptions = options;
    levelOptions.GridStep_deg = schedule(level);
    if isempty(options.PrimitiveRadii_deg)
        levelOptions.PrimitiveRadii_deg = unique( ...
            schedule(level) * options.PrimitiveRadiusMultipliers);
    end
    remainingLevels = numel(schedule) - level + 1;
    levelBudget = remaining / remainingLevels;
    if level == numel(schedule)
        levelBudget = remaining;
    end
    levelOptions.MaxSearchTime_s = max( ...
        min(levelBudget, options.MaxSearchTime_s), 0.05);

    candidate = searchAzElSafeIntervalAStar( ...
        workspace, startState, stopState, limits, levelOptions);
    [candidateTime, candidatePosition, candidateCost] = ...
        dynamicCandidateTrace(candidate, options);
    attemptCount = attemptCount + 1;
    attempts(attemptCount, 1) = struct( ...
        "GridStep_deg", schedule(level), ...
        "PrimitiveRadii_deg", ...
        levelOptions.PrimitiveRadii_deg, ...
        "Success", candidate.Success, ...
        "Message", candidate.Message, ...
        "ExpandedNodeCount", candidate.ExpandedNodeCount, ...
        "GeneratedNodeCount", candidate.GeneratedNodeCount, ...
        "SearchElapsed_s", candidate.SearchElapsed_s, ...
        "TerminationReason", candidate.TerminationReason, ...
        "ObjectiveCost", candidateCost, ...
        "CandidateTime_s", candidateTime, ...
        "CandidatePosition_deg", candidatePosition, ...
        "Selected", false);
    search = candidate;
    if candidate.Success
        if abs(candidate.Route.angularPathLength_deg - ...
                endpointLowerBound) <= 1e-9
            candidate.GlobalAngularOptimal = true;
            search = candidate;
        end
        if options.Objective == "minimumAngularDistance"
            candidateObjective = ...
                candidate.Route.angularPathLength_deg;
        else
            candidateObjective = ...
                candidate.Route.arrivalTime_s(end);
        end
        if candidateObjective < bestObjective
            bestSearch = candidate;
            bestObjective = candidateObjective;
            bestGridStep = schedule(level);
        end
        if candidate.GlobalAngularOptimal || ...
                options.Objective == "minimumTime"
            break;
        end
    end
end

attempts = attempts(1:attemptCount);
if ~isempty(fieldnames(bestSearch))
    search = bestSearch;
    selected = find([attempts.Success] & ...
        abs([attempts.ObjectiveCost] - bestObjective) <= 1e-9, 1, "last");
    attempts(selected).Selected = true;
end

if isempty(fieldnames(search)) || ~search.Success
    if isempty(fieldnames(search))
        message = "The search time budget expired before A* started.";
    else
        message = search.Message;
    end
    plan = failedPlan(message, workspace, startState, stopState, ...
        limits, options, attempts, search, toc(timer));
    return;
end

profile = search.Profile;
route = search.Route;
delta = wrappedDelta( ...
    startState.position_deg, stopState.position_deg, limits, options);
lowerBound = hypot(delta(1), delta(2));
if options.Objective == "minimumAngularDistance"
    objectiveCost = route.angularPathLength_deg;
    objectiveUnits = "deg";
else
    objectiveCost = route.arrivalTime_s(end) - startState.time_s;
    objectiveUnits = "s";
end

plan = struct( ...
    "success", true, ...
    "message", ...
    "Progressive safe-interval A* found an exact-checked trajectory.", ...
    "method", "progressiveSafeIntervalAStar", ...
    "time_s", profile.time_s, ...
    "position_deg", profile.position_deg, ...
    "positionUnwrapped_deg", profile.positionUnwrapped_deg, ...
    "velocity_deg_s", profile.velocity_deg_s, ...
    "acceleration_deg_s2", profile.acceleration_deg_s2, ...
    "isWaiting", profile.isWaiting, ...
    "cost_s", stopState.time_s - startState.time_s, ...
    "objective", options.Objective, ...
    "objectiveCost", objectiveCost, ...
    "objectiveCostUnits", objectiveUnits, ...
    "angularPathLength_deg", route.angularPathLength_deg, ...
    "angularLowerBound_deg", lowerBound, ...
    "suboptimalityBound", ...
    max(1, route.angularPathLength_deg / max(lowerBound, eps)), ...
    "optimalOnLattice", false, ...
    "optimalGlobally", search.GlobalAngularOptimal, ...
    "exactCollisionValidated", true, ...
    "expandedNodeCount", sum([attempts.ExpandedNodeCount]), ...
    "generatedNodeCount", sum([attempts.GeneratedNodeCount]), ...
    "searchElapsed_s", toc(timer), ...
    "selectedGridStep_deg", bestGridStep, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "resolutionAttempts", attempts, ...
    "safeIntervalSearch", search);
end

function plan = progressiveStaticAStar( ...
        workspace, startState, stopState, limits, options, schedule, timer)
attemptTemplate = struct( ...
    "GridStep_deg", NaN, ...
    "PrimitiveRadii_deg", zeros(1, 0), ...
    "Success", false, ...
    "Message", "", ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0, ...
    "TerminationReason", "", ...
    "ObjectiveCost", Inf, ...
    "CandidateTime_s", zeros(0, 1), ...
    "CandidatePosition_deg", zeros(0, 2), ...
    "Selected", false);
attempts = repmat(attemptTemplate, numel(schedule), 1);
attemptCount = 0;
bestPlan = struct();
bestCost = Inf;

for level = 1:numel(schedule)
    remaining = options.MaxSearchTime_s - toc(timer);
    if remaining <= 0
        break;
    end
    staticOptions = options;
    staticOptions.GridStep_deg = schedule(level);
    staticOptions.TopologyGridStep_deg = schedule(level);
    staticOptions.TopologyHeuristicWeight = ...
        options.HeuristicWeight;
    staticOptions.MaximumTopologyExpansions = ...
        options.MaxExpansions;
    staticOptions.FallbackToExistingPlanner = false;
    staticOptions.EnableTopologyRefinement = ...
        options.EnableTopologyRefinement && level == numel(schedule);
    staticOptions.MaxSearchTime_s = ...
        remaining / (numel(schedule) - level + 1);

    candidate = planAzElAutonomousCorridor( ...
        workspace, startState, stopState, limits, staticOptions);
    endpointDelta = wrappedDelta( ...
        startState.position_deg, stopState.position_deg, limits, options);
    endpointLowerBound = hypot(endpointDelta(1), endpointDelta(2));
    if candidate.success && abs( ...
            candidate.angularPathLength_deg - endpointLowerBound) <= 1e-9
        candidate.optimalGlobally = true;
        candidate.suboptimalityBound = 1;
    end
    if candidate.success
        candidateTime = candidate.time_s;
        candidatePosition = candidate.position_deg;
        candidateCost = candidate.objectiveCost;
    else
        candidateTime = zeros(0, 1);
        candidatePosition = zeros(0, 2);
        candidateCost = Inf;
    end
    attemptCount = attemptCount + 1;
    attempts(attemptCount) = struct( ...
        "GridStep_deg", schedule(level), ...
        "PrimitiveRadii_deg", zeros(1, 0), ...
        "Success", candidate.success, ...
        "Message", candidate.message, ...
        "ExpandedNodeCount", candidate.expandedNodeCount, ...
        "GeneratedNodeCount", candidate.generatedNodeCount, ...
        "SearchElapsed_s", candidate.searchElapsed_s, ...
        "TerminationReason", ...
        string(ternary(candidate.success, "goalReached", "noPath")), ...
        "ObjectiveCost", candidateCost, ...
        "CandidateTime_s", candidateTime, ...
        "CandidatePosition_deg", candidatePosition, ...
        "Selected", false);
    if candidate.success && candidate.objectiveCost < bestCost
        bestPlan = candidate;
        bestCost = candidate.objectiveCost;
    end
    if candidate.success && candidate.optimalGlobally
        break;
    end
end
attempts = attempts(1:attemptCount);

if isempty(fieldnames(bestPlan))
    if attemptCount == 0
        message = "The static A* time budget expired before search.";
    else
        message = attempts(end).Message;
    end
    plan = failedPlan(message, workspace, startState, stopState, ...
        limits, options, attempts, struct(), toc(timer));
    return;
end

selected = find([attempts.Success] & ...
    abs([attempts.ObjectiveCost] - bestCost) <= 1e-9, 1, "last");
attempts(selected).Selected = true;

bestPlan.message = ...
    "Static safe intervals collapsed to exact-checked any-angle A*.";
bestPlan.method = "adaptiveAnyAngleAStar";
bestPlan.exactCollisionValidated = true;
bestPlan.selectedGridStep_deg = ...
    bestPlan.options.TopologyGridStep_deg;
bestPlan.resolutionAttempts = attempts;
bestPlan.safeIntervalSearch = struct();
bestPlan.searchElapsed_s = toc(timer);
bestPlan.options = options;
plan = bestPlan;
end

function [time_s, position_deg, cost] = ...
        dynamicCandidateTrace(candidate, options)
if ~candidate.Success
    time_s = zeros(0, 1);
    position_deg = zeros(0, 2);
    cost = Inf;
    return;
end
time_s = candidate.Profile.time_s;
position_deg = candidate.Profile.position_deg;
if options.Objective == "minimumAngularDistance"
    cost = candidate.Route.angularPathLength_deg;
else
    cost = candidate.Route.arrivalTime_s(end);
end
end

function value = ternary(condition, whenTrue, whenFalse)
if condition
    value = whenTrue;
else
    value = whenFalse;
end
end

function plan = failedPlan(message, workspace, startState, stopState, ...
        limits, options, attempts, search, elapsed)
plan = struct( ...
    "success", false, ...
    "message", string(message), ...
    "method", "progressiveSafeIntervalAStar", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "positionUnwrapped_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "isWaiting", false(0, 1), ...
    "cost_s", Inf, ...
    "objective", options.Objective, ...
    "objectiveCost", Inf, ...
    "objectiveCostUnits", "", ...
    "angularPathLength_deg", Inf, ...
    "angularLowerBound_deg", NaN, ...
    "suboptimalityBound", Inf, ...
    "optimalOnLattice", false, ...
    "optimalGlobally", false, ...
    "exactCollisionValidated", false, ...
    "expandedNodeCount", sum([attempts.ExpandedNodeCount]), ...
    "generatedNodeCount", sum([attempts.GeneratedNodeCount]), ...
    "searchElapsed_s", elapsed, ...
    "selectedGridStep_deg", NaN, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "resolutionAttempts", attempts, ...
    "safeIntervalSearch", search);
end

function delta = wrappedDelta(first, second, limits, options)
delta = second - first;
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    delta(1) = mod(delta(1) + span / 2, span) - span / 2;
end
end

function [startState, stopState, limits, options] = ...
        normalizeAdaptiveAStarInputs( ...
        startState, stopState, limits, options)
explicitGraph = isstruct(options) && ...
    isfield(options, "GridStep_deg") && ...
    ~isempty(options.GridStep_deg) && ...
    isfield(options, "PrimitiveRadii_deg") && ...
    ~isempty(options.PrimitiveRadii_deg);
requiredState = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
startState = normalizeState(startState, "startState", requiredState);
stopState = normalizeState(stopState, "stopState", requiredState);
if stopState.time_s <= startState.time_s
    error("planAzElAdaptiveAStar:InvalidTime", ...
        "stopState.time_s must follow startState.time_s.");
end

requiredLimits = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
if ~isstruct(limits) || ~isscalar(limits) || ...
        ~all(isfield(limits, cellstr(requiredLimits)))
    error("planAzElAdaptiveAStar:InvalidLimits", ...
        "limits is missing a required field.");
end
for name = requiredLimits
    validateattributes(limits.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    limits.(name) = reshape(double(limits.(name)), 1, 2);
end
if any(diff(limits.azimuth_deg) <= 0) || ...
        any(diff(limits.elevation_deg) <= 0) || ...
        any(limits.maxVelocity_deg_s <= 0) || ...
        any(limits.maxAcceleration_deg_s2 <= 0)
    error("planAzElAdaptiveAStar:InvalidLimits", ...
        "Limit ranges must increase and dynamic limits must be positive.");
end

defaults = struct( ...
    "SampleTime_s", 0.5, ...
    "ValidationStep_s", [], ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", [], ...
    "PrimitiveRadii_deg", [], ...
    "PrimitiveRadiusMultipliers", [1 2 4 8], ...
    "DirectionStep_deg", 45, ...
    "DirectionAngles_deg", [], ...
    "HeuristicWeight", 1, ...
    "CollisionCheckStep_s", [], ...
    "MaximumSafeIntervalSamples", 10000, ...
    "MaximumDepartureTrials", 64, ...
    "DepartureBatchSize", 8, ...
    "MaxExpansions", 100000, ...
    "MaxSearchTime_s", 45, ...
    "InitialNodeCapacity", 4096, ...
    "TimePaddingSamples", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", diff(limits.azimuth_deg) >= 360 - 1e-9, ...
    "Objective", "minimumAngularDistance", ...
    "EnableTopologyRefinement", false, ...
    "MaximumVerticesPerRegion", 500);
options = applyDefaults(options, defaults);

finest = options.GridStep_deg;
if isempty(options.GridStepSchedule_deg)
    if explicitGraph
        options.GridStepSchedule_deg = finest;
    else
        options.GridStepSchedule_deg = unique( ...
            [4 * finest, 2 * finest, finest], "stable");
    end
end
options.GridStepSchedule_deg = ...
    unique(double(options.GridStepSchedule_deg(:).'), "stable");
options.GridStepSchedule_deg = ...
    sort(options.GridStepSchedule_deg, "descend");
if isempty(options.ValidationStep_s)
    options.ValidationStep_s = min( ...
        options.SampleTime_s, finest / ...
        max(limits.maxVelocity_deg_s) / 8);
end
if isempty(options.CollisionCheckStep_s)
    options.CollisionCheckStep_s = options.ValidationStep_s;
end

positive = ["SampleTime_s", "ValidationStep_s", ...
    "GridStep_deg", "CollisionCheckStep_s", ...
    "DirectionStep_deg", "HeuristicWeight", "MaxSearchTime_s"];
for name = positive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.GridStepSchedule_deg, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
validateattributes(options.PrimitiveRadiusMultipliers, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
if ~isempty(options.PrimitiveRadii_deg)
    validateattributes(options.PrimitiveRadii_deg, {'numeric'}, ...
        {'vector', 'real', 'finite', 'positive'});
    options.PrimitiveRadii_deg = ...
        unique(double(options.PrimitiveRadii_deg(:).'));
end
integerPositive = ["MaximumSafeIntervalSamples", ...
    "MaximumDepartureTrials", "DepartureBatchSize", ...
    "MaxExpansions", "InitialNodeCapacity"];
for name = integerPositive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'integer', 'positive'});
end
validateattributes(options.TimePaddingSamples, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
if ~isempty(options.DirectionAngles_deg)
    validateattributes(options.DirectionAngles_deg, {'numeric'}, ...
        {'vector', 'real', 'finite'});
end
validateattributes(options.AllowAzimuthWrap, ...
    {'logical', 'numeric'}, {'scalar'});
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);
validateattributes(options.EnableTopologyRefinement, ...
    {'logical', 'numeric'}, {'scalar'});
options.EnableTopologyRefinement = ...
    logical(options.EnableTopologyRefinement);
if options.AllowAzimuthWrap && ...
        abs(diff(limits.azimuth_deg) - 360) > 1e-6
    error("planAzElAdaptiveAStar:InvalidWrapLimits", ...
        "Wrapped azimuth limits must span exactly 360 degrees.");
end

objective = lower(strtrim(string(options.Objective)));
if any(objective == ["minimumangulardistance", ...
        "angulardistance", "distance"])
    options.Objective = "minimumAngularDistance";
elseif any(objective == ["minimumtime", "time"])
    options.Objective = "minimumTime";
else
    error("planAzElAdaptiveAStar:InvalidObjective", ...
        "Objective must be minimumAngularDistance or minimumTime.");
end
end

function state = normalizeState(state, label, requiredState)
if ~isstruct(state) || ~isscalar(state) || ...
        ~all(isfield(state, cellstr(requiredState)))
    error("planAzElAdaptiveAStar:InvalidState", ...
        "%s is missing a required field.", label);
end
validateattributes(state.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
for name = requiredState(2:end)
    validateattributes(state.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    state.(name) = reshape(double(state.(name)), 1, 2);
end
state.time_s = double(state.time_s);
end

function output = applyDefaults(input, defaults)
if ~isstruct(input) || ~isscalar(input)
    error("planAzElAdaptiveAStar:InvalidOptions", ...
        "options must be a scalar struct.");
end
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
