function plan = planAzElAutonomousCorridor( ...
        azElData, startState, stopState, limits, options)
%PLANAZELAUTONOMOUSCORRIDOR Discover, retime, and validate a corridor route.
%
% This hybrid planner is intended for difficult static topology such as
% spirals, nested barriers, and cul-de-sacs. It:
%   1. proves that every packed obstacle slice is geometrically identical;
%   2. rasterizes one conservatively inflated az/el occupancy map;
%   3. discovers an any-angle route without a supplied guide path;
%   4. retimes that route with rate/acceleration-limited motion profiles;
%   5. validates the trajectory against the original packed workspace.
%
% Time-dependent problems and unsupported boundary conditions return an
% explicit failure. The public adaptive planner handles dynamic geometry
% through its safe-interval search.

timer = tic;
if nargin < 5
    options = struct();
end
[startState, stopState, limits, options] = ...
    normalizeInputs(startState, stopState, limits, options);
prebuiltWorkspace = isstruct(azElData) && isscalar(azElData) && ...
    isfield(azElData, "Format") && ...
    string(azElData.Format) == "AzElTimeObstacleWorkspace";
if prebuiltWorkspace
    workspace = azElData;
else
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", options.MaximumVerticesPerRegion));
end

unsupportedReason = "";
if options.Objective ~= "minimumAngularDistance"
    unsupportedReason = "minimum-time objective";
elseif any(abs([ ...
        startState.velocity_deg_s, stopState.velocity_deg_s, ...
        startState.acceleration_deg_s2, ...
        stopState.acceleration_deg_s2]) > 1e-12)
    unsupportedReason = "nonzero boundary rate or acceleration";
elseif ~isAzElTimeObstacleWorkspaceStatic( ...
        workspace, startState.time_s, stopState.time_s)
    unsupportedReason = "time-dependent obstacle geometry";
end
if unsupportedReason ~= ""
    plan = failedPlan( ...
        "Autonomous corridor planner did not run: " + unsupportedReason, ...
        workspace, startState, stopState, limits, options, toc(timer));
    return;
end

% This occupancy map is a topology model only. Inflation makes raster routes
% conservative, while the packed workspace later certifies the result.
[azimuthValues, elevationValues] = topologyGrid(limits, options);
[azimuthGrid, elevationGrid] = ...
    meshgrid(azimuthValues, elevationValues);
occupied = queryAzElTimeObstacle(workspace, ...
    azimuthGrid(:), elevationGrid(:), startState.time_s, struct( ...
    "CollisionMode", "polygon", ...
    "SafetyMarginDeg", options.SafetyMargin_deg));
occupied = reshape(occupied, size(azimuthGrid));

endpointBlocked = queryAzElTimeObstacle(workspace, ...
    [startState.position_deg(1); stopState.position_deg(1)], ...
    [startState.position_deg(2); stopState.position_deg(2)], ...
    [startState.time_s; stopState.time_s], struct( ...
    "CollisionMode", "polygon", ...
    "SafetyMarginDeg", options.SafetyMargin_deg));
if any(endpointBlocked)
    plan = failedPlan( ...
        "The start or stop lies inside the inflated obstacle workspace.", ...
        workspace, startState, stopState, limits, options, toc(timer));
    return;
end

% The any-angle search discovers homotopy without requiring user waypoints.
topologyOptions = struct( ...
    "AllowAzimuthWrap", options.AllowAzimuthWrap, ...
    "HeuristicWeight", options.TopologyHeuristicWeight, ...
    "UseAnyAngleRelaxation", options.UseAnyAngleRelaxation, ...
    "MaximumExpandedNodes", options.MaximumTopologyExpansions, ...
    "MaximumWallTime_s", options.MaxSearchTime_s);
topology = searchAzElAnyAngleAStar( ...
    occupied, azimuthValues, elevationValues, ...
    startState.position_deg, stopState.position_deg, topologyOptions);
if ~topology.Success
    plan = failedPlan( ...
        "Topology search failed: " + topology.Message, ...
        workspace, startState, stopState, limits, options, toc(timer));
    plan.topologySearch = topology;
    return;
end

selectedTopology = topology;
refinement = struct( ...
    "Success", false, ...
    "Message", "Refinement was not requested.");
remainingTime_s = options.MaxSearchTime_s - toc(timer);
% Optional local refinement spends only the remaining budget around the
% coarse route and is accepted solely when it reduces angular length.
if options.EnableTopologyRefinement && ...
        ~options.AllowAzimuthWrap && remainingTime_s > 0.25
    refinementOptions = options;
    refinementOptions.RefinementWallTime_s = min( ...
        options.RefinementWallTime_s, remainingTime_s);
    refinement = refineAzElTopologyCorridor( ...
        workspace, topology.Path_deg, ...
        startState.position_deg, stopState.position_deg, ...
        limits, startState.time_s, refinementOptions);
    if refinement.Success && ...
            refinement.AngularLength_deg < ...
            topology.AngularLength_deg - 1e-9
        selectedTopology = refinement;
    end
end

route = [ ...
    startState.position_deg; ...
    selectedTopology.Path_deg; ...
    stopState.position_deg];
route = unwrapAndReduceRoute(route, limits, options);
rawRoute = route;
shortcut = struct( ...
    "Success", false, ...
    "Message", "Visibility shortcutting was not requested.");
if options.EnableRouteShortcutting
    % Visibility shortcutting removes unnecessary bends, but each proposed
    % segment is checked against the packed geometry before acceptance.
    shortcut = simplifyAzElRouteVisibility( ...
        workspace, route, startState.time_s, limits, options);
    if shortcut.Success && ...
            shortcut.AngularLength_deg <= ...
            polylineLength(route) + 1e-9
        route = shortcut.Path_deg;
    end
end
retimingOptions = options;
retimingOptions.GuidePath_deg = route(2:end - 1, :);
% Limit collision spacing along a maximum-rate slew to about half a topology
% cell, independent of the output sample interval.
retimingOptions.CollisionCheckStep_s = min( ...
    options.SampleTime_s, ...
    options.TopologyGridStep_deg / ...
    max(limits.maxVelocity_deg_s) / 2);
retimed = planAzElGuidedRoute( ...
    workspace, startState, stopState, limits, retimingOptions);
if ~retimed.Success
    plan = failedPlan( ...
        "Autonomous route retiming failed: " + retimed.Message, ...
        workspace, startState, stopState, limits, options, toc(timer));
    plan.topologySearch = topology;
    plan.autonomousRoute_deg = route;
    return;
end

plan = publicPlan(retimed, topology, route, workspace, ...
    refinement, selectedTopology, rawRoute, shortcut, ...
    startState, stopState, limits, options, toc(timer));
end

function plan = publicPlan( ...
        result, topology, route, workspace, refinement, ...
        selectedTopology, rawRoute, shortcut, startState, stopState, ...
        limits, options, elapsed_s)
profile = result.Profile;
plan = struct();
plan.success = true;
plan.message = "Autonomous corridor route discovered and retimed.";
if selectedTopology.Method == "corridorRefinedAnyAngleAStar"
    plan.method = "autonomousMultiresolutionCorridor";
else
    plan.method = "autonomousAnyAngleCorridor";
end
plan.time_s = profile.time_s;
plan.position_deg = profile.position_deg;
plan.positionUnwrapped_deg = profile.positionUnwrapped_deg;
plan.velocity_deg_s = profile.velocity_deg_s;
plan.acceleration_deg_s2 = profile.acceleration_deg_s2;
plan.isWaiting = profile.isWaiting;
plan.cost_s = stopState.time_s - startState.time_s;
plan.objective = "minimumAngularDistance";
plan.optimalOnLattice = false;
plan.optimalGlobally = false;
plan.heuristicWeight = options.TopologyHeuristicWeight;
plan.suboptimalityBound = result.SuboptimalityBound;
plan.objectiveCost = result.AngularPathLengthDeg;
plan.objectiveCostUnits = "degrees";
plan.angularPathLength_deg = result.AngularPathLengthDeg;
plan.angularLowerBound_deg = result.AngularLowerBoundDeg;
plan.expandedNodeCount = topology.ExpandedNodeCount + ...
    fieldOr(refinement, "ExpandedNodeCount", 0);
plan.generatedNodeCount = topology.GeneratedNodeCount + ...
    fieldOr(refinement, "GeneratedNodeCount", 0);
plan.startState = startState;
plan.stopState = stopState;
plan.limits = limits;
plan.options = options;
plan.workspace = workspace;
plan.internalPositionResolution_deg = ...
    repmat(options.TopologyGridStep_deg, 1, 2);
plan.internalVelocityResolution_deg_s = [NaN NaN];
plan.internalSampleTime_s = NaN;
plan.searchElapsed_s = elapsed_s;
plan.searchResult = result;
plan.topologySearch = topology;
plan.topologyRefinement = refinement;
plan.selectedTopologySearch = selectedTopology;
plan.preShortcutRoute_deg = rawRoute;
plan.routeShortcut = shortcut;
plan.autonomousRoute_deg = route;
plan.minimumDistanceWaypoint = struct();
plan.minimumDistanceWaypointHistory = result.WaypointHistory;
plan.planningAttempts = struct( ...
    "Method", "autonomousAnyAngleCorridor", ...
    "Success", true, ...
    "Message", plan.message, ...
    "ObjectiveCost", plan.objectiveCost, ...
    "ObjectiveCostUnits", plan.objectiveCostUnits, ...
    "ExpandedNodeCount", plan.expandedNodeCount, ...
    "GeneratedNodeCount", plan.generatedNodeCount, ...
    "Elapsed_s", elapsed_s);
end

function plan = failedPlan( ...
        message, workspace, startState, stopState, limits, options, elapsed_s)
time_s = zeros(0, 1);
position = zeros(0, 2);
plan = struct( ...
    "success", false, ...
    "message", string(message), ...
    "method", "autonomousAnyAngleCorridor", ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "positionUnwrapped_deg", position, ...
    "velocity_deg_s", position, ...
    "acceleration_deg_s2", position, ...
    "isWaiting", false(0, 1), ...
    "cost_s", Inf, ...
    "objective", options.Objective, ...
    "optimalOnLattice", false, ...
    "optimalGlobally", false, ...
    "heuristicWeight", options.TopologyHeuristicWeight, ...
    "suboptimalityBound", Inf, ...
    "objectiveCost", Inf, ...
    "objectiveCostUnits", "degrees", ...
    "angularPathLength_deg", Inf, ...
    "angularLowerBound_deg", NaN, ...
    "expandedNodeCount", 0, ...
    "generatedNodeCount", 0, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "workspace", workspace, ...
    "searchElapsed_s", elapsed_s);
plan = finalizeAzElPlanFailure(plan);
end

function [azimuth, elevation] = topologyGrid(limits, options)
step = options.TopologyGridStep_deg;
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    binCount = ceil(span / step);
    wrappedStep = span / binCount;
    azimuth = limits.azimuth_deg(1) + ...
        (0:binCount - 1) * wrappedStep;
else
    azimuth = inclusiveGrid(limits.azimuth_deg, step);
end
elevation = inclusiveGrid(limits.elevation_deg, step);
end

function values = inclusiveGrid(limits, step)
values = limits(1):step:limits(2);
if values(end) < limits(2) - 1e-9
    values(end + 1) = limits(2);
end
values = double(values);
end

function route = unwrapAndReduceRoute(route, limits, options)
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    for k = 2:size(route, 1)
        delta = mod(route(k, 1) - route(k - 1, 1) + ...
            span / 2, span) - span / 2;
        route(k, 1) = route(k - 1, 1) + delta;
    end
end
keep = true(size(route, 1), 1);
keep(2:end) = hypot(diff(route(:, 1)), diff(route(:, 2))) > 1e-10;
route = route(keep, :);
changed = true;
while changed && size(route, 1) > 2
    first = route(2:end - 1, :) - route(1:end - 2, :);
    second = route(3:end, :) - route(2:end - 1, :);
    crossValue = first(:, 1) .* second(:, 2) - ...
        first(:, 2) .* second(:, 1);
    scale = max(1, hypot(first(:, 1), first(:, 2)) .* ...
        hypot(second(:, 1), second(:, 2)));
    remove = abs(crossValue) <= 1e-10 .* scale;
    if any(remove)
        route(find(remove, 1) + 1, :) = [];
    else
        changed = false;
    end
end
end

function [startState, stopState, limits, options] = ...
        normalizeInputs(startState, stopState, limits, options)
requiredStateFields = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
if ~isstruct(startState) || ...
        ~all(isfield(startState, cellstr(requiredStateFields))) || ...
        ~isstruct(stopState) || ...
        ~all(isfield(stopState, cellstr(requiredStateFields)))
    error("planAzElAutonomousCorridor:InvalidState", ...
        "Start and stop states require time, position, velocity, and acceleration.");
end
stateNames = ["position_deg", "velocity_deg_s", "acceleration_deg_s2"];
for name = stateNames
    validateattributes(startState.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    validateattributes(stopState.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    startState.(name) = reshape(double(startState.(name)), 1, 2);
    stopState.(name) = reshape(double(stopState.(name)), 1, 2);
end
validateattributes(startState.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateattributes(stopState.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', startState.time_s});
startState.time_s = double(startState.time_s);
stopState.time_s = double(stopState.time_s);

requiredLimitFields = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
if ~isstruct(limits) || ...
        ~all(isfield(limits, cellstr(requiredLimitFields)))
    error("planAzElAutonomousCorridor:InvalidLimits", ...
        "limits is missing a required field.");
end
for name = requiredLimitFields
    validateattributes(limits.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    limits.(name) = reshape(double(limits.(name)), 1, 2);
end
if any(limits.maxVelocity_deg_s <= 0) || ...
        any(limits.maxAcceleration_deg_s2 <= 0) || ...
        any(diff(limits.azimuth_deg) <= 0) || ...
        any(diff(limits.elevation_deg) <= 0)
    error("planAzElAutonomousCorridor:InvalidLimits", ...
        "Limit ranges must increase and dynamic limits must be positive.");
end

defaults = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "TopologyGridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", diff(limits.azimuth_deg) >= 360 - 1e-9, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 30, ...
    "MaxExpansions", 1000000, ...
    "MaximumTopologyExpansions", 2000000, ...
    "MaximumVerticesPerRegion", 500, ...
    "TopologyHeuristicWeight", 1, ...
    "UseAnyAngleRelaxation", true, ...
    "EnableTopologyRefinement", false, ...
    "RefinementGridStep_deg", 0.25, ...
    "RefinementCorridorHalfWidth_deg", 1.5, ...
    "RefinementHeuristicWeight", 1, ...
    "RefinementMaximumExpansions", 500000, ...
    "RefinementWallTime_s", 10, ...
    "EnableRouteShortcutting", true, ...
    "RouteShortcutStep_deg", 0.1, ...
    "PrintFailureSuggestions", true);
options = applyDefaults(options, defaults);
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.TopologyGridStep_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.MaxSearchTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.MaximumTopologyExpansions, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(options.TopologyHeuristicWeight, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 1});
validateattributes(options.RefinementGridStep_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.RefinementCorridorHalfWidth_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.RefinementHeuristicWeight, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 1});
validateattributes(options.RefinementMaximumExpansions, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(options.RefinementWallTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.RouteShortcutStep_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.AllowAzimuthWrap, {'logical', 'numeric'}, ...
    {'scalar'});
validateattributes(options.UseAnyAngleRelaxation, {'logical', 'numeric'}, ...
    {'scalar'});
validateattributes(options.EnableTopologyRefinement, ...
    {'logical', 'numeric'}, {'scalar'});
validateattributes(options.EnableRouteShortcutting, ...
    {'logical', 'numeric'}, {'scalar'});
validateattributes(options.PrintFailureSuggestions, ...
    {'logical', 'numeric'}, {'scalar'});
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);
options.UseAnyAngleRelaxation = logical(options.UseAnyAngleRelaxation);
options.EnableTopologyRefinement = ...
    logical(options.EnableTopologyRefinement);
options.EnableRouteShortcutting = ...
    logical(options.EnableRouteShortcutting);
options.PrintFailureSuggestions = ...
    logical(options.PrintFailureSuggestions);
objective = lower(strtrim(string(options.Objective)));
if any(objective == ["minimumangulardistance", ...
        "angulardistance", "distance"])
    options.Objective = "minimumAngularDistance";
elseif any(objective == ["minimumtime", "time"])
    options.Objective = "minimumTime";
else
    error("planAzElAutonomousCorridor:InvalidObjective", ...
        "Objective must be minimumAngularDistance or minimumTime.");
end
if options.AllowAzimuthWrap && ...
        abs(diff(limits.azimuth_deg) - 360) > 1e-6
    error("planAzElAutonomousCorridor:InvalidWrapLimits", ...
        "Wrapped azimuth limits must span exactly 360 degrees.");
end
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end

function value = fieldOr(input, name, fallback)
if isstruct(input) && isfield(input, name) && ~isempty(input.(name))
    value = input.(name);
else
    value = fallback;
end
end

function length_deg = polylineLength(route)
delta = diff(route, 1, 1);
length_deg = sum(hypot(delta(:, 1), delta(:, 2)));
end
