function plan = planAzElMovingTargetIntercept( ...
        azElData, initialState, target, limits, options)
%PLANAZELMOVINGTARGETINTERCEPT Catch a moving point through dynamic volumes.
%
% The target trajectory is independent of the obstacle field. Candidate
% interception times are sampled across the requested interval and attempted
% from earliest to latest. Optional terminal capture matches target velocity
% and acceleration, then follows the target while its path remains safe.

if nargin < 5
    options = struct();
end
requiredTarget = ["time_s", "position_deg"];
if ~isstruct(target) || ~isscalar(target) || ...
        ~all(isfield(target, requiredTarget))
    error("planAzElMovingTargetIntercept:InvalidTarget", ...
        "target requires time_s and position_deg.");
end
target.time_s = double(target.time_s(:));
target.position_deg = double(target.position_deg);
validateattributes(target.time_s, {'numeric'}, ...
    {'vector', 'real', 'finite', 'increasing'});
validateattributes(target.position_deg, {'numeric'}, ...
    {'2d', 'ncols', 2, 'real', 'finite'});
if size(target.position_deg, 1) ~= numel(target.time_s)
    error("planAzElMovingTargetIntercept:TargetSizeMismatch", ...
        "target.position_deg must contain one row per target time.");
end

defaults = struct( ...
    "EarliestInterceptTime_s", ...
        max(initialState.time_s, target.time_s(1)), ...
    "LatestInterceptTime_s", target.time_s(end), ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 12, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "CatchTolerance_deg", 0.35, ...
    "CatchVelocityTolerance_deg_s", 0.05, ...
    "CatchAccelerationTolerance_deg_s2", 0.1, ...
    "MatchTargetVelocity", false, ...
    "MatchTargetAcceleration", false, ...
    "ContinueTrackingAfterIntercept", false, ...
    "TrackingEndTime_s", target.time_s(end), ...
    "TrackingSampleTime_s", fieldOr(options, "SampleTime_s", 0.5), ...
    "SafetyMargin_deg", 0, ...
    "PrintFailureSuggestions", true);
options = applyDefaults(options, defaults);
validateInterceptOptions(options, initialState, target);
target = targetWithKinematics(target, limits, options);

% Build once because every candidate interception time reuses the same
% moving obstacle volume.
if isstruct(azElData) && isscalar(azElData) && ...
        isfield(azElData, "Format") && ...
        azElData.Format == "AzElTimeObstacleWorkspace"
    workspace = azElData;
else
    maximumVertices = fieldOr(options, ...
        "MaximumVerticesPerRegion", 500);
    workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
        "MaximumVerticesPerRegion", maximumVertices));
end

candidateTime = (options.EarliestInterceptTime_s: ...
    options.InterceptTimeStep_s:options.LatestInterceptTime_s).';
if isempty(candidateTime) || ...
        candidateTime(end) < options.LatestInterceptTime_s - 1e-9
    candidateTime(end + 1, 1) = options.LatestInterceptTime_s;
end
candidateUnwrapped = interp1( ...
    target.time_s, target.positionUnwrapped_deg, ...
    candidateTime, "linear");
candidatePosition = canonicalPosition( ...
    candidateUnwrapped, limits, options);
candidateVelocity = interp1(target.time_s, target.velocity_deg_s, ...
    candidateTime, "linear");
candidateAcceleration = interp1( ...
    target.time_s, target.acceleration_deg_s2, ...
    candidateTime, "linear");
% Cheap point, collision, and reachability filters avoid launching A* for
% interception states that cannot possibly succeed.
inside = candidatePosition(:, 1) >= limits.azimuth_deg(1) & ...
    candidatePosition(:, 1) <= limits.azimuth_deg(2) & ...
    candidatePosition(:, 2) >= limits.elevation_deg(1) & ...
    candidatePosition(:, 2) <= limits.elevation_deg(2);
blocked = true(size(candidateTime));
blocked(inside) = queryAzElTimeObstacle(workspace, ...
    candidatePosition(inside, 1), candidatePosition(inside, 2), ...
    candidateTime(inside), struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
reachable = kinematicallyReachable( ...
    initialState, candidateTime, candidatePosition, ...
    candidateVelocity, candidateAcceleration, limits, options);
eligible = inside & ~blocked & reachable;
eligibleIndex = find(eligible);
if numel(eligibleIndex) > options.MaximumInterceptAttempts
    selected = unique(round(linspace( ...
        1, numel(eligibleIndex), options.MaximumInterceptAttempts)));
    eligibleIndex = eligibleIndex(selected);
end

attemptTemplate = struct( ...
    "time_s", NaN, ...
    "position_deg", [NaN NaN], ...
    "velocity_deg_s", [NaN NaN], ...
    "success", false, ...
    "elapsed_s", 0, ...
    "message", "");
attempts = repmat(attemptTemplate, numel(eligibleIndex), 1);
attemptCount = 0;
timer = tic;
% Earliest-first attempts make the first accepted plan the earliest sampled
% rendezvous. Every attempt has its own bounded search budget.
for k = 1:numel(eligibleIndex)
    index = eligibleIndex(k);
    goalVelocity_deg_s = [0 0];
    goalAcceleration_deg_s2 = [0 0];
    if options.MatchTargetVelocity
        goalVelocity_deg_s = candidateVelocity(index, :);
    end
    if options.MatchTargetAcceleration
        goalAcceleration_deg_s2 = candidateAcceleration(index, :);
    end
    goalState = boundaryState( ...
        candidateTime(index), candidatePosition(index, :), ...
        goalVelocity_deg_s, goalAcceleration_deg_s2);
    plannerOptions = options;
    plannerOptions.AllowNonzeroTerminalState = ...
        options.MatchTargetVelocity || options.MatchTargetAcceleration;
    plannerOptions.MaxSearchTime_s = min( ...
        options.PerAttemptMaxSearchTime_s, ...
        fieldOr(options, "MaxSearchTime_s", ...
        options.PerAttemptMaxSearchTime_s));
    plannerOptions.PrintFailureSuggestions = false;
    attemptTimer = tic;
    candidate = planAzElAdaptiveAStar( ...
        workspace, initialState, goalState, limits, plannerOptions);
    attemptCount = attemptCount + 1;
    attempts(attemptCount, 1) = struct( ...
        "time_s", candidateTime(index), ...
        "position_deg", candidatePosition(index, :), ...
        "velocity_deg_s", candidateVelocity(index, :), ...
        "success", candidate.success, ...
        "elapsed_s", toc(attemptTimer), ...
        "message", string(candidate.message));
    if ~candidate.success
        continue;
    end
    % Re-evaluate target kinematics at the reported catch time. This catches
    % interpolation, wrapping, and profile-sampling inconsistencies.
    targetAtCatchUnwrapped = interp1( ...
        target.time_s, target.positionUnwrapped_deg, ...
        candidate.time_s(end), "linear");
    targetAtCatch = canonicalPosition( ...
        targetAtCatchUnwrapped, limits, options);
    targetVelocityAtCatch = interp1( ...
        target.time_s, target.velocity_deg_s, ...
        candidate.time_s(end), "linear");
    targetAccelerationAtCatch = interp1( ...
        target.time_s, target.acceleration_deg_s2, ...
        candidate.time_s(end), "linear");
    catchError = hypot( ...
        candidate.position_deg(end, 1) - targetAtCatch(1), ...
        candidate.position_deg(end, 2) - targetAtCatch(2));
    if catchError > options.CatchTolerance_deg + 1e-9
        continue;
    end
    velocityError = hypot( ...
        candidate.velocity_deg_s(end, 1) - targetVelocityAtCatch(1), ...
        candidate.velocity_deg_s(end, 2) - targetVelocityAtCatch(2));
    if options.MatchTargetVelocity && ...
            velocityError > ...
            options.CatchVelocityTolerance_deg_s + 1e-9
        continue;
    end
    accelerationError = hypot( ...
        candidate.acceleration_deg_s2(end, 1) - ...
            targetAccelerationAtCatch(1), ...
        candidate.acceleration_deg_s2(end, 2) - ...
            targetAccelerationAtCatch(2));
    if options.MatchTargetAcceleration && ...
            accelerationError > ...
            options.CatchAccelerationTolerance_deg_s2 + 1e-9
        continue;
    end
    plan = candidate;
    plan.interceptSuccess = true;
    plan.interceptTime_s = candidate.time_s(end);
    plan.interceptPosition_deg = candidate.position_deg(end, :);
    plan.targetPositionAtIntercept_deg = targetAtCatch;
    plan.targetVelocityAtIntercept_deg_s = targetVelocityAtCatch;
    plan.targetAccelerationAtIntercept_deg_s2 = ...
        targetAccelerationAtCatch;
    plan.catchError_deg = catchError;
    plan.catchVelocityError_deg_s = velocityError;
    plan.catchAccelerationError_deg_s2 = accelerationError;
    plan.targetTrajectory = target;
    plan.interceptAttempts = attempts(1:attemptCount);
    plan.interceptCandidateCount = nnz(eligible);
    plan.interceptSearchElapsed_s = toc(timer);
    plan = appendSafeTargetTracking( ...
        plan, target, workspace, limits, options);
    return;
end

plan = struct( ...
    "success", false, ...
    "interceptSuccess", false, ...
    "message", "No sampled moving-target interception was found.", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "workspace", workspace, ...
    "startState", initialState, ...
    "targetTrajectory", target, ...
    "limits", limits, ...
    "options", options, ...
    "interceptAttempts", attempts(1:attemptCount), ...
    "interceptCandidateCount", nnz(eligible), ...
    "interceptFilter", struct( ...
        "sampleCount", numel(candidateTime), ...
        "insideLimitCount", nnz(inside), ...
        "safeCount", nnz(inside & ~blocked), ...
        "reachableCount", nnz(inside & ~blocked & reachable), ...
        "eligibleCount", nnz(eligible)), ...
    "interceptSearchElapsed_s", toc(timer));
plan = finalizeAzElPlanFailure(plan);
end

function reachable = kinematicallyReachable( ...
        initialState, time_s, position, velocity, acceleration, ...
        limits, options)
delta = abs(position - initialState.position_deg);
if fieldOr(options, "AllowAzimuthWrap", ...
        diff(limits.azimuth_deg) >= 360 - 1e-9)
    span = diff(limits.azimuth_deg);
    delta(:, 1) = abs(mod( ...
        position(:, 1) - initialState.position_deg(1) + span / 2, ...
        span) - span / 2);
end
minimumTime = max( ...
    delta ./ limits.maxVelocity_deg_s, [], 2);
accelerationTime = max(sqrt( ...
    2 * delta ./ limits.maxAcceleration_deg_s2), [], 2);
minimumTime = max(minimumTime, accelerationTime);
reachable = minimumTime <= ...
    time_s - initialState.time_s + 1e-9;
if options.MatchTargetVelocity
    reachable = reachable & all(abs(velocity) <= ...
        limits.maxVelocity_deg_s + 1e-9, 2);
end
if options.MatchTargetAcceleration
    reachable = reachable & all(abs(acceleration) <= ...
        limits.maxAcceleration_deg_s2 + 1e-9, 2);
end
end

function state = boundaryState( ...
        time_s, position, velocity, acceleration)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", velocity, ...
    "acceleration_deg_s2", acceleration);
end

function validateInterceptOptions(options, initialState, target)
positive = ["InterceptTimeStep_s", "PerAttemptMaxSearchTime_s", ...
    "CatchTolerance_deg", "CatchVelocityTolerance_deg_s", ...
    "CatchAccelerationTolerance_deg_s2", "TrackingSampleTime_s"];
for name = positive
    validateattributes(options.(name), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end
validateattributes(options.MaximumInterceptAttempts, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(options.EarliestInterceptTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', ...
    '>=', max(initialState.time_s, target.time_s(1))});
validateattributes(options.LatestInterceptTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '<=', target.time_s(end)});
if options.LatestInterceptTime_s <= ...
        options.EarliestInterceptTime_s
    error("planAzElMovingTargetIntercept:InvalidInterceptWindow", ...
        "LatestInterceptTime_s must follow EarliestInterceptTime_s.");
end
validateattributes(options.TrackingEndTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '<=', target.time_s(end)});
logicalOptions = ["MatchTargetVelocity", ...
    "MatchTargetAcceleration", "ContinueTrackingAfterIntercept"];
logicalOptions(end + 1) = "PrintFailureSuggestions";
for name = logicalOptions
    validateattributes(options.(name), ...
        {'logical', 'numeric'}, {'scalar'});
    options.(name) = logical(options.(name));
end
if options.MatchTargetAcceleration && ~options.MatchTargetVelocity
    error("planAzElMovingTargetIntercept:AccelerationWithoutVelocity", ...
        "MatchTargetAcceleration requires MatchTargetVelocity.");
end
if options.ContinueTrackingAfterIntercept && ...
        ~options.MatchTargetVelocity
    error("planAzElMovingTargetIntercept:TrackingWithoutVelocityMatch", ...
        "ContinueTrackingAfterIntercept requires MatchTargetVelocity.");
end
end

function target = targetWithKinematics(target, limits, options)
sampleCount = numel(target.time_s);
allowWrap = fieldOr(options, "AllowAzimuthWrap", ...
    diff(limits.azimuth_deg) >= 360 - 1e-9);
unwrapped = target.position_deg;
% Differentiate a continuous azimuth trace. Differentiating wrapped samples
% would create artificial rate spikes at the azimuth seam.
if allowWrap
    unwrapped(:, 1) = rad2deg( ...
        unwrap(deg2rad(unwrapped(:, 1))));
end
if isfield(target, "velocity_deg_s") && ...
        ~isempty(target.velocity_deg_s)
    velocity = normalizeTargetSamples( ...
        target.velocity_deg_s, sampleCount, "velocity_deg_s");
else
    velocity = sampledDerivative(unwrapped, target.time_s);
end
if isfield(target, "acceleration_deg_s2") && ...
        ~isempty(target.acceleration_deg_s2)
    acceleration = normalizeTargetSamples( ...
        target.acceleration_deg_s2, sampleCount, ...
        "acceleration_deg_s2");
else
    acceleration = sampledDerivative(velocity, target.time_s);
end
target.positionUnwrapped_deg = unwrapped;
target.position_deg = canonicalPosition(unwrapped, limits, options);
target.velocity_deg_s = velocity;
target.acceleration_deg_s2 = acceleration;
end

function values = normalizeTargetSamples(values, sampleCount, name)
validateattributes(values, {'numeric'}, ...
    {'2d', 'nrows', sampleCount, 'ncols', 2, ...
    'real', 'finite'}, mfilename, name);
values = double(values);
end

function derivative = sampledDerivative(values, time_s)
derivative = zeros(size(values));
sampleCount = numel(time_s);
if sampleCount == 1
    return;
end
derivative(1, :) = ...
    (values(2, :) - values(1, :)) / (time_s(2) - time_s(1));
derivative(end, :) = ...
    (values(end, :) - values(end - 1, :)) / ...
    (time_s(end) - time_s(end - 1));
if sampleCount > 2
    % Centered differences reduce phase bias for interior target samples.
    duration = time_s(3:end) - time_s(1:end - 2);
    derivative(2:end - 1, :) = ...
        (values(3:end, :) - values(1:end - 2, :)) ./ duration;
end
end

function position = canonicalPosition(position, limits, options)
allowWrap = fieldOr(options, "AllowAzimuthWrap", ...
    diff(limits.azimuth_deg) >= 360 - 1e-9);
if allowWrap
    span = diff(limits.azimuth_deg);
    position(:, 1) = mod( ...
        position(:, 1) - limits.azimuth_deg(1), span) + ...
        limits.azimuth_deg(1);
end
end

function plan = appendSafeTargetTracking( ...
        plan, target, workspace, limits, options)
plan.trackingRequested = options.ContinueTrackingAfterIntercept;
plan.trackingSuccess = false;
plan.trackingTerminationReason = "notRequested";
plan.trackingTerminatedByObstacle = false;
plan.trackingTime_s = zeros(0, 1);
plan.trackingPosition_deg = zeros(0, 2);
plan.trackingVelocity_deg_s = zeros(0, 2);
plan.trackingAcceleration_deg_s2 = zeros(0, 2);
plan.trackingEndTime_s = plan.interceptTime_s;
if ~options.ContinueTrackingAfterIntercept
    return;
end

trackingStop = min(options.TrackingEndTime_s, target.time_s(end));
if trackingStop <= plan.interceptTime_s + 1e-9
    plan.trackingTerminationReason = "trackingWindowComplete";
    return;
end
time = (plan.interceptTime_s + options.TrackingSampleTime_s: ...
    options.TrackingSampleTime_s:trackingStop).';
if isempty(time) || time(end) < trackingStop - 1e-9
    time(end + 1, 1) = trackingStop;
else
    time(end) = trackingStop;
end
unwrapped = interp1( ...
    target.time_s, target.positionUnwrapped_deg, time, "linear");
targetAtIntercept = interp1( ...
    target.time_s, target.positionUnwrapped_deg, ...
    plan.interceptTime_s, "linear");
unwrapped(:, 1) = unwrapped(:, 1) + ...
    (plan.positionUnwrapped_deg(end, 1) - targetAtIntercept(1));
position = canonicalPosition(unwrapped, limits, options);
velocity = interp1( ...
    target.time_s, target.velocity_deg_s, time, "linear");
acceleration = interp1( ...
    target.time_s, target.acceleration_deg_s2, time, "linear");

inside = position(:, 2) >= limits.elevation_deg(1) - 1e-9 & ...
    position(:, 2) <= limits.elevation_deg(2) + 1e-9;
if ~fieldOr(options, "AllowAzimuthWrap", ...
        diff(limits.azimuth_deg) >= 360 - 1e-9)
    inside = inside & ...
        position(:, 1) >= limits.azimuth_deg(1) - 1e-9 & ...
        position(:, 1) <= limits.azimuth_deg(2) + 1e-9;
end
dynamicsValid = all(abs(velocity) <= ...
    limits.maxVelocity_deg_s + 1e-9, 2) & ...
    all(abs(acceleration) <= ...
    limits.maxAcceleration_deg_s2 + 1e-9, 2);
blocked = queryAzElTimeObstacle(workspace, ...
    position(:, 1), position(:, 2), time, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
safe = inside & dynamicsValid & ~blocked;
% Append only the maximal safe prefix. The first unsafe target sample is
% reported as the termination cause but never enters the command history.
firstUnsafe = find(~safe, 1);
if isempty(firstUnsafe)
    keep = (1:numel(time)).';
    reason = "trackingWindowComplete";
elseif firstUnsafe == 1
    keep = zeros(0, 1);
    reason = trackingFailureReason( ...
        blocked(firstUnsafe), inside(firstUnsafe), ...
        dynamicsValid(firstUnsafe));
else
    keep = (1:firstUnsafe - 1).';
    reason = trackingFailureReason( ...
        blocked(firstUnsafe), inside(firstUnsafe), ...
        dynamicsValid(firstUnsafe));
end

if ~isempty(keep)
    previous = plan.positionUnwrapped_deg(end, :);
    added = [previous; unwrapped(keep, :)];
    plan.angularPathLength_deg = plan.angularPathLength_deg + ...
        sum(hypot(diff(added(:, 1)), diff(added(:, 2))));
    plan.time_s = [plan.time_s; time(keep)];
    plan.position_deg = [plan.position_deg; position(keep, :)];
    plan.positionUnwrapped_deg = [ ...
        plan.positionUnwrapped_deg; unwrapped(keep, :)];
    plan.velocity_deg_s = [ ...
        plan.velocity_deg_s; velocity(keep, :)];
    plan.acceleration_deg_s2 = [ ...
        plan.acceleration_deg_s2; acceleration(keep, :)];
    plan.isWaiting = [plan.isWaiting; false(numel(keep), 1)];
    plan.trackingSuccess = true;
    plan.trackingTime_s = time(keep);
    plan.trackingPosition_deg = position(keep, :);
    plan.trackingVelocity_deg_s = velocity(keep, :);
    plan.trackingAcceleration_deg_s2 = acceleration(keep, :);
    plan.trackingEndTime_s = time(keep(end));
end
plan.cost_s = plan.time_s(end) - plan.time_s(1);
plan.trackingTerminationReason = reason;
plan.trackingTerminatedByObstacle = reason == "obstacle";
plan.commandEndState = struct( ...
    "time_s", plan.time_s(end), ...
    "position_deg", plan.position_deg(end, :), ...
    "velocity_deg_s", plan.velocity_deg_s(end, :), ...
    "acceleration_deg_s2", plan.acceleration_deg_s2(end, :));
end

function reason = trackingFailureReason(blocked, inside, dynamicsValid)
if blocked
    reason = "obstacle";
elseif ~inside
    reason = "outsidePointingLimits";
elseif ~dynamicsValid
    reason = "targetExceedsDynamicLimits";
else
    reason = "trackingStopped";
end
end

function value = fieldOr(input, name, fallback)
if isfield(input, name) && ~isempty(input.(name))
    value = input.(name);
else
    value = fallback;
end
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
