function handles = plotSimpleAzElTimeKinodynamicBiRRT( ...
        azElData, plan, options)
%% Section 0: Header & Readme
% SYNTAX
%   options = plotSimpleAzElTimeKinodynamicBiRRT()
%   handles = plotSimpleAzElTimeKinodynamicBiRRT(azElData, plan)
%   handles = plotSimpleAzElTimeKinodynamicBiRRT( ...
%       azElData, plan, options)
%**************************************************************************
% PURPOSE
%   - Display sampled time-varying obstacle outlines, both RRT trees, and
%     the accepted forward-time trajectory in azimuth/elevation/time space.
%**************************************************************************
% INPUTS
%   - azElData (struct array or cell array)
%       Canonical moving obstacle data used by the planner.
%   - plan (scalar struct)
%       Result from planSimpleAzElTimeKinodynamicBiRRT.
%   - options (scalar struct)
%       .Figure optionally supplies a matlab.ui.Figure.
%       .MaximumDisplayedObstacleSlices limits visual obstacle slices.
%       .InitialTreeColor, .DestinationTreeColor, .TrajectoryColor, and
%       .ObstacleColor are RGB triples.
%       .TreeLineWidth and .TrajectoryLineWidth set line widths.
%**************************************************************************
% OUTPUTS
%   - handles (scalar struct)
%       Figure, axes, obstacle, tree, endpoint, and trajectory handles.
%       A zero-argument call returns the fully populated options structure.
%**************************************************************************
% UNITS
%   - Plot axes use degrees and seconds.

%% Section 1: Validate Inputs & Apply Defaults
defaultOptions = struct( ...
    "Figure", [], ...
    "MaximumDisplayedObstacleSlices", 40, ...
    "InitialTreeColor", [0.10, 0.45, 0.85], ...
    "DestinationTreeColor", [0.85, 0.30, 0.20], ...
    "TrajectoryColor", [0.05, 0.65, 0.25], ...
    "ObstacleColor", [0.25, 0.25, 0.25], ...
    "TreeLineWidth", 0.7, ...
    "TrajectoryLineWidth", 2.5);
if nargin == 0
    handles = defaultOptions;
    return;
end
if nargin < 3 || isempty(options)
    options = struct();
end
if ~isstruct(plan) || ~isscalar(plan) || ...
        ~all(isfield(plan, ["initialTree", "destinationTree", ...
        "position_deg", "time_s", "success"]))
    error("plotSimpleAzElTimeKinodynamicBiRRT:InvalidPlan", ...
        "plan must be returned by planSimpleAzElTimeKinodynamicBiRRT.");
end
if ~isstruct(options) || ~isscalar(options)
    error("plotSimpleAzElTimeKinodynamicBiRRT:InvalidOptions", ...
        "options must be a scalar struct.");
end
unknownOptionFields = setdiff(fieldnames(options), ...
    fieldnames(defaultOptions), "stable");
if ~isempty(unknownOptionFields)
    warning("plotSimpleAzElTimeKinodynamicBiRRT:UnknownOptions", ...
        "Ignoring unknown option fields: %s.", ...
        strjoin(string(unknownOptionFields), ", "));
    options = rmfield(options, unknownOptionFields);
end
resolvedOptions = defaultOptions;
providedOptionFields = fieldnames(options);
for optionIndex = 1:numel(providedOptionFields)
    optionName = providedOptionFields{optionIndex};
    if ~isempty(options.(optionName))
        resolvedOptions.(optionName) = options.(optionName);
    end
end
options = resolvedOptions;
validateattributes(options.MaximumDisplayedObstacleSlices, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
colorOptionNames = ["InitialTreeColor", "DestinationTreeColor", ...
    "TrajectoryColor", "ObstacleColor"];
for colorOptionIndex = 1:numel(colorOptionNames)
    validateattributes(options.(colorOptionNames(colorOptionIndex)), ...
        {'numeric'}, {'vector', 'numel', 3, 'real', 'finite', ...
        '>=', 0, '<=', 1});
end
validateattributes(options.TreeLineWidth, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.TrajectoryLineWidth, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

%% Section 2: Create The Figure And Axes
if isempty(options.Figure)
    figureHandle = figure( ...
        "Name", "Simple Kinodynamic Bidirectional RRT", ...
        "Color", "white");
else
    figureHandle = options.Figure;
    if ~isgraphics(figureHandle, "figure")
        error("plotSimpleAzElTimeKinodynamicBiRRT:InvalidFigure", ...
            "options.Figure must be a valid figure handle.");
    end
    clf(figureHandle);
end
axesHandle = axes("Parent", figureHandle);
hold(axesHandle, "on");
grid(axesHandle, "on");
box(axesHandle, "on");
view(axesHandle, 3);
xlabel(axesHandle, "Azimuth (deg)");
ylabel(axesHandle, "Elevation (deg)");
zlabel(axesHandle, "Time (s)");
title(axesHandle, "Simple Kinodynamic Bidirectional RRT");

%% Section 3: Plot Sampled Time-Varying Obstacles
canonicalAzElData = combineAzElObstacles(azElData);
obstacleHandles = gobjects(0, 1);
for obstacleIndex = 1:numel(canonicalAzElData)
    obstacleData = canonicalAzElData(obstacleIndex);
    sliceCount = numel(obstacleData.time_s);
    displayedSliceCount = min( ...
        sliceCount, options.MaximumDisplayedObstacleSlices);
    displayedSliceIndices = unique(round(linspace( ...
        1, sliceCount, displayedSliceCount)));
    for displayedIndex = 1:numel(displayedSliceIndices)
        sliceIndex = displayedSliceIndices(displayedIndex);
        azimuthBoundary_deg = obstacleData.az_deg{sliceIndex}(:);
        elevationBoundary_deg = obstacleData.el_deg{sliceIndex}(:);
        usableVertexCount = min(numel(azimuthBoundary_deg), ...
            numel(elevationBoundary_deg));
        if usableVertexCount == 0
            continue;
        end
        timeBoundary_s = repmat(obstacleData.time_s(sliceIndex), ...
            usableVertexCount, 1);
        obstacleHandle = plot3(axesHandle, ...
            azimuthBoundary_deg(1:usableVertexCount), ...
            elevationBoundary_deg(1:usableVertexCount), ...
            timeBoundary_s, "-", ...
            "Color", options.ObstacleColor, ...
            "LineWidth", 0.6, "HandleVisibility", "off");
        obstacleHandles(end + 1, 1) = obstacleHandle; %#ok<AGROW>
    end
end

%% Section 4: Plot Both Search Trees
initialTreeEdgeHandles = gobjects(0, 1);
for nodeIndex = 2:plan.initialTree.NodeCount
    parentNodeIndex = double( ...
        plan.initialTree.ParentNodeIndex(nodeIndex));
    edgeState = plan.initialTree.State([parentNodeIndex, nodeIndex], :);
    edgeHandle = plot3(axesHandle, edgeState(:, 2), edgeState(:, 3), ...
        edgeState(:, 1), "-", "Color", options.InitialTreeColor, ...
        "LineWidth", options.TreeLineWidth, ...
        "HandleVisibility", "off");
    initialTreeEdgeHandles(end + 1, 1) = edgeHandle; %#ok<AGROW>
end
destinationTreeEdgeHandles = gobjects(0, 1);
for nodeIndex = 2:plan.destinationTree.NodeCount
    parentNodeIndex = double( ...
        plan.destinationTree.ParentNodeIndex(nodeIndex));
    % The child is earlier in time, and its parent is closer to the
    % destination root, so this plotting order is already forward-time.
    edgeState = plan.destinationTree.State([nodeIndex, parentNodeIndex], :);
    edgeHandle = plot3(axesHandle, edgeState(:, 2), edgeState(:, 3), ...
        edgeState(:, 1), "-", "Color", options.DestinationTreeColor, ...
        "LineWidth", options.TreeLineWidth, ...
        "HandleVisibility", "off");
    destinationTreeEdgeHandles(end + 1, 1) = edgeHandle; %#ok<AGROW>
end

initialLegendHandle = plot3(axesHandle, nan, nan, nan, "-", ...
    "Color", options.InitialTreeColor, ...
    "LineWidth", options.TreeLineWidth, ...
    "DisplayName", "Initial tree");
destinationLegendHandle = plot3(axesHandle, nan, nan, nan, "-", ...
    "Color", options.DestinationTreeColor, ...
    "LineWidth", options.TreeLineWidth, ...
    "DisplayName", "Destination tree");

%% Section 5: Plot Endpoints And The Final Trajectory
initialState = plan.initialTree.State(1, :);
destinationState = plan.destinationTree.State(1, :);
initialEndpointHandle = plot3(axesHandle, initialState(2), ...
    initialState(3), initialState(1), "o", ...
    "MarkerFaceColor", options.InitialTreeColor, ...
    "MarkerEdgeColor", "white", "MarkerSize", 8, ...
    "DisplayName", "Initial state");
destinationEndpointHandle = plot3(axesHandle, destinationState(2), ...
    destinationState(3), destinationState(1), "s", ...
    "MarkerFaceColor", options.DestinationTreeColor, ...
    "MarkerEdgeColor", "white", "MarkerSize", 8, ...
    "DisplayName", "Destination state");
if plan.success
    trajectoryHandle = plot3(axesHandle, plan.position_deg(:, 1), ...
        plan.position_deg(:, 2), plan.time_s, "-o", ...
        "Color", options.TrajectoryColor, ...
        "MarkerFaceColor", options.TrajectoryColor, ...
        "MarkerSize", 3, ...
        "LineWidth", options.TrajectoryLineWidth, ...
        "DisplayName", "Forward trajectory");
else
    trajectoryHandle = gobjects(0, 1);
end
legend(axesHandle, "Location", "best");

%% Section 6: Package The Graphics Handles
handles = struct( ...
    "Figure", figureHandle, ...
    "Axes", axesHandle, ...
    "Obstacle", obstacleHandles, ...
    "InitialTreeEdges", initialTreeEdgeHandles, ...
    "DestinationTreeEdges", destinationTreeEdgeHandles, ...
    "InitialTreeLegend", initialLegendHandle, ...
    "DestinationTreeLegend", destinationLegendHandle, ...
    "InitialEndpoint", initialEndpointHandle, ...
    "DestinationEndpoint", destinationEndpointHandle, ...
    "Trajectory", trajectoryHandle);
end
