function handles = plotAzElTimeWorkspacePyramid(pyramid, options)
%PLOTAZELTIMEWORKSPACEPYRAMID Inspect coarse voxels and local fine patches.
%
% handles = plotAzElTimeWorkspacePyramid(pyramid)
% handles = plotAzElTimeWorkspacePyramid(pyramid, options)
%
% Options:
%   CoarseTimeIndex              Default middle coarse page.
%   FinePatchId                  Default newest patch, or 0 for none.
%   MaximumCoarsePointsDisplayed Default 20000.
%   MaximumFinePointsDisplayed   Default 20000.
%   Figure                       Existing figure or [].

if nargin < 2
    options = struct();
end
validatePyramid(pyramid);
options = normalizeOptions(options, pyramid);

if isempty(options.Figure)
    figureHandle = figure( ...
        "Name", "Az/el/time workspace pyramid", ...
        "Color", "w");
else
    figureHandle = options.Figure;
    clf(figureHandle);
end
layout = tiledlayout(figureHandle, 1, 2, ...
    "TileSpacing", "compact", "Padding", "compact");

coarseAxes = nexttile(layout, 1);
timeIndex = options.CoarseTimeIndex;
page = pyramid.Coarse.Occupancy(:, :, timeIndex);
candidate = pyramid.RefinementCandidateMask(:, :, timeIndex);
imagesc(coarseAxes, pyramid.Coarse.AzimuthCentersDeg, ...
    pyramid.Coarse.ElevationCentersDeg, page);
set(coarseAxes, "YDir", "normal");
axis(coarseAxes, "equal", "tight");
hold(coarseAxes, "on");
contour(coarseAxes, pyramid.Coarse.AzimuthCentersDeg, ...
    pyramid.Coarse.ElevationCentersDeg, double(candidate), ...
    [0.5 0.5], "Color", [0.85 0.2 0.2], "LineWidth", 1);
xlabel(coarseAxes, "Azimuth (deg)");
ylabel(coarseAxes, "Elevation (deg)");
title(coarseAxes, sprintf( ...
    "Coarse page at t = %.3f s", ...
    pyramid.Coarse.TimeSeconds(timeIndex)));
colormap(coarseAxes, [0.96 0.97 0.98; 0.15 0.35 0.62]);

volumeAxes = nexttile(layout, 2);
hold(volumeAxes, "on");
[coarseEl, coarseAz, coarseTime] = ...
    ind2sub(size(pyramid.Coarse.Occupancy), ...
    find(pyramid.Coarse.Occupancy));
coarseKeep = displayIndices( ...
    numel(coarseAz), options.MaximumCoarsePointsDisplayed);
coarsePlot = scatter3(volumeAxes, ...
    pyramid.Coarse.AzimuthCentersDeg(coarseAz(coarseKeep)), ...
    pyramid.Coarse.ElevationCentersDeg(coarseEl(coarseKeep)), ...
    pyramid.Coarse.TimeSeconds(coarseTime(coarseKeep)), ...
    8, [0.20 0.45 0.75], "filled", ...
    "DisplayName", "Coarse occupied voxels");

finePlot = gobjects(0);
if options.FinePatchId > 0
    patch = pyramid.FinePatches(options.FinePatchId);
    [fineEl, fineAz, fineTime] = ...
        ind2sub(size(patch.Grid.Occupancy), ...
        find(patch.Grid.Occupancy));
    fineKeep = displayIndices( ...
        numel(fineAz), options.MaximumFinePointsDisplayed);
    finePlot = scatter3(volumeAxes, ...
        patch.Grid.AzimuthCentersDeg(fineAz(fineKeep)), ...
        patch.Grid.ElevationCentersDeg(fineEl(fineKeep)), ...
        patch.Grid.TimeSeconds(fineTime(fineKeep)), ...
        12, [0.70 0.15 0.65], "filled", ...
        "DisplayName", sprintf("Fine patch %d", patch.Id));
end
xlabel(volumeAxes, "Azimuth (deg)");
ylabel(volumeAxes, "Elevation (deg)");
zlabel(volumeAxes, "Time (s)");
title(volumeAxes, "Multiresolution occupied volume");
grid(volumeAxes, "on");
view(volumeAxes, 3);
if ~isempty(coarsePlot) || ~isempty(finePlot)
    legend(volumeAxes, "Location", "best");
end

handles = struct( ...
    "Figure", figureHandle, ...
    "Layout", layout, ...
    "CoarseAxes", coarseAxes, ...
    "VolumeAxes", volumeAxes, ...
    "CoarsePlot", coarsePlot, ...
    "FinePlot", finePlot);
end

function validatePyramid(pyramid)
if ~isstruct(pyramid) || ~isscalar(pyramid) || ...
        ~isfield(pyramid, "Format") || ...
        pyramid.Format ~= "AzElTimeWorkspacePyramid"
    error("plotAzElTimeWorkspacePyramid:InvalidPyramid", ...
        "Use buildAzElTimeWorkspacePyramid to create pyramid.");
end
end

function options = normalizeOptions(options, pyramid)
defaults = struct( ...
    "CoarseTimeIndex", ...
    max(1, round(numel(pyramid.Coarse.TimeSeconds) / 2)), ...
    "FinePatchId", numel(pyramid.FinePatches), ...
    "MaximumCoarsePointsDisplayed", 20000, ...
    "MaximumFinePointsDisplayed", 20000, ...
    "Figure", []);
options = applyDefaults(options, defaults);
validateattributes(options.CoarseTimeIndex, {'numeric'}, ...
    {'scalar', 'integer', '>=', 1, ...
    '<=', numel(pyramid.Coarse.TimeSeconds)});
validateattributes(options.FinePatchId, {'numeric'}, ...
    {'scalar', 'integer', '>=', 0, ...
    '<=', numel(pyramid.FinePatches)});
validateattributes(options.MaximumCoarsePointsDisplayed, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(options.MaximumFinePointsDisplayed, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
end

function index = displayIndices(count, maximum)
if count == 0
    index = zeros(0, 1);
elseif count <= maximum
    index = (1:count).';
else
    index = unique(round(linspace(1, count, maximum))).';
end
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
