function [plan, receipt] = refineAzElPlanPareto( ...
        plan, obstacleField, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   [plan, receipt] = refineAzElPlanPareto( ...
%       plan, obstacleField, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Improve a validated trajectory with adaptive piecewise-quintic direct
%     collocation after its discrete search has finished.
%   - Trade path length against completion time without requiring an
%     optimization toolbox or hiding which candidate family was searched.
%   - Preserve endpoint state, axis limits, bounded jerk, and moving-obstacle
%     safety while testing every candidate on a dense time grid.
%   - Keep the original validated plan whenever no continuous candidate is
%     both safe and better than the discrete result.
%**************************************************************************
% INPUTS
%   - plan (scalar struct)
%       Successful trajectory returned by planAzElDijkstra.
%   - obstacleField (packed obstacle field)
%       The exact obstacle representation used by the discrete search.
%   - initialState, goalState (scalar state structs)
%       Requested endpoint position, velocity, acceleration, and time.
%   - limits (scalar struct)
%       Position, velocity, and acceleration limits for both axes.
%   - options (scalar struct)
%       Resolved planner and Pareto-refinement settings.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       The improved plan, or the untouched input plan when no improvement
%       survives dense verification.
%   - receipt (scalar struct)
%       Candidate counts, selected blend/time scale, costs, and outcome.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Describe The Baseline That Must Never Regress
receipt = paretoReceiptTemplate();
receipt.Attempted = true;
receipt.BaselinePathLength_deg = plan.angularPathLength_deg;
if ~plan.success || isempty(plan.time_s)
    receipt.Message = "Continuous Pareto refinement requires a successful plan.";
    return
end

% The public command normally continues at the goal until the requested
% horizon. Refinement concerns the maneuver itself, so first find the sample
% where the requested terminal state has been reached and settled.
terminalPosition_deg = plan.positionUnwrapped_deg(end, :);
positionError_deg = hypot( ...
    plan.positionUnwrapped_deg(:, 1) - terminalPosition_deg(1), ...
    plan.positionUnwrapped_deg(:, 2) - terminalPosition_deg(2));
velocityError_deg_s = max(abs( ...
    plan.velocity_deg_s - goalState.velocity_deg_s), [], 2);
accelerationError_deg_s2 = max(abs( ...
    plan.acceleration_deg_s2 - goalState.acceleration_deg_s2), [], 2);
sampleIsTerminal = positionError_deg <= 1e-8 & ...
    velocityError_deg_s <= 1e-8 & accelerationError_deg_s2 <= 1e-8;
lastNonterminalSample = find(~sampleIsTerminal, 1, "last");
if isempty(lastNonterminalSample)
    completionSampleIndex = 1;
else
    completionSampleIndex = min( ...
        lastNonterminalSample + 1, numel(plan.time_s));
end
nodeTime_s = plan.time_s(1:completionSampleIndex);
nodePositionUnwrapped_deg = ...
    plan.positionUnwrapped_deg(1:completionSampleIndex, :);
nodeVelocity_deg_s = plan.velocity_deg_s(1:completionSampleIndex, :);
nodeAcceleration_deg_s2 = ...
    plan.acceleration_deg_s2(1:completionSampleIndex, :);
baselineDuration_s = nodeTime_s(end) - nodeTime_s(1);
receipt.BaselineCompletionTime_s = baselineDuration_s;
if baselineDuration_s <= 1e-12 || numel(nodeTime_s) < 2
    receipt.Success = true;
    receipt.Message = "The plan is already stationary at its goal.";
    receipt.RefinedPathLength_deg = plan.angularPathLength_deg;
    receipt.RefinedCompletionTime_s = baselineDuration_s;
    receipt.SelectedCombinedRatio = 1;
    receipt.PhysicalVerification = auditPublishedPlanPhysics( ...
        plan, obstacleField, limits, options);
    receipt.PhysicalVerificationPassed = ...
        receipt.PhysicalVerification.Passed;
    return
end

% A useful collocation mesh is neither every command sample nor a blind
% uniform decimation. Start with the requested time spacing, then retain
% extra original samples at sharp turns and stop/start transitions. Those
% are the places where a junior engineer would expect the physical model to
% need more freedom. The helper also enforces one explicit knot-count limit.
[refinementTime_s, adaptiveKnotCount] = selectAdaptiveKnotTimes( ...
    nodeTime_s, nodePositionUnwrapped_deg, nodeVelocity_deg_s, options);
if ~isequal(refinementTime_s, nodeTime_s)
    nodePositionUnwrapped_deg = interp1(nodeTime_s, ...
        nodePositionUnwrapped_deg, refinementTime_s, "linear");
    nodeVelocity_deg_s = interp1(nodeTime_s, nodeVelocity_deg_s, ...
        refinementTime_s, "linear");
    nodeAcceleration_deg_s2 = interp1(nodeTime_s, ...
        nodeAcceleration_deg_s2, refinementTime_s, "linear");
    nodeTime_s = refinementTime_s;
end
receipt.CollocationKnotCount = numel(nodeTime_s);
receipt.AdaptiveKnotCount = adaptiveKnotCount;

distanceLowerBound_deg = max( ...
    fieldOr(plan, "angularLowerBound_deg", 0), eps);
timeLowerBound_s = restToRestTimeLowerBound( ...
    initialState.position_deg, goalState.position_deg, limits);
timeLowerBound_s = max(timeLowerBound_s, eps);
baselineCombinedRatio = combinedParetoRatio( ...
    baselineDuration_s, plan.angularPathLength_deg, ...
    timeLowerBound_s, distanceLowerBound_deg, options);
receipt.BaselineCombinedRatio = baselineCombinedRatio;
receipt.RefinedPathLength_deg = plan.angularPathLength_deg;
receipt.RefinedCompletionTime_s = baselineDuration_s;
receipt.SelectedCombinedRatio = baselineCombinedRatio;

%% Section 2: Build Smooth Candidates Between The Safe Path & Direct Path
% Alpha zero reproduces the searched path. Larger alpha values pull every
% state toward one fifth-order endpoint polynomial. That polynomial matches
% requested position, velocity, and acceleration at both ends, so blending
% cannot corrupt the terminal-state contract.
relativeNodeTime_s = nodeTime_s - nodeTime_s(1);
referenceGoalState = goalState;
referenceGoalState.position_deg = terminalPosition_deg;
[directPosition_deg, directVelocity_deg_s, ...
    directAcceleration_deg_s2] = endpointQuinticMotion( ...
    relativeNodeTime_s, baselineDuration_s, initialState, referenceGoalState);
blendSchedule = unique([0, ...
    options.ParetoRefinementBlendSchedule(:).'], "stable");
bestCandidate = struct();
bestVerifiedCandidate = struct();
bestVerifiedCombinedRatio = Inf;
bestCombinedRatio = baselineCombinedRatio;
hasTerminalDynamics = any(abs([goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2]) > 1e-12);

for blendIndex = 1:numel(blendSchedule)
    blend = blendSchedule(blendIndex);
    blendedPosition_deg = (1 - blend) * nodePositionUnwrapped_deg + ...
        blend * directPosition_deg;
    blendedVelocity_deg_s = (1 - blend) * nodeVelocity_deg_s + ...
        blend * directVelocity_deg_s;
    blendedAcceleration_deg_s2 = ...
        (1 - blend) * nodeAcceleration_deg_s2 + ...
        blend * directAcceleration_deg_s2;

    % The searched command is the most faithful derivative seed. A second
    % family estimates one continuous state directly from the collocation
    % geometry. This gives profile fallbacks a fair bounded-jerk repair
    % attempt instead of forcing their sampled acceleration jumps into every
    % quintic candidate.
    derivativePolicies = ["searchedState", "geometryEstimate"];
    for derivativePolicy = derivativePolicies
        candidateKnotVelocity_deg_s = blendedVelocity_deg_s;
        candidateKnotAcceleration_deg_s2 = ...
            blendedAcceleration_deg_s2;
        if derivativePolicy == "geometryEstimate"
            [candidateKnotVelocity_deg_s, ...
                candidateKnotAcceleration_deg_s2] = ...
                estimateCollocationDerivatives( ...
                relativeNodeTime_s, blendedPosition_deg, ...
                initialState, referenceGoalState);
        end

        % A uniform clock change preserves the spatial curve. With rest
        % endpoint dynamics, derivatives scale predictably with 1/T, 1/T^2,
        % and 1/T^3. Nonzero terminal rates keep their original clock.
        if hasTerminalDynamics
            timeScales = 1;
        else
            unscaledDense = sampleQuinticNodeStates( ...
                relativeNodeTime_s, blendedPosition_deg, ...
                candidateKnotVelocity_deg_s, ...
                candidateKnotAcceleration_deg_s2, ...
                options.ValidationStep_s);
            requiredTimeScale = requiredPhysicalTimeScale( ...
                unscaledDense, limits, ...
                options.JointKinematicMaximumJerk_deg_s3);
            maximumTimeScale = ...
                (goalState.time_s - initialState.time_s) / ...
                baselineDuration_s;
            if requiredTimeScale > maximumTimeScale + 1e-12
                continue
            end
            minimumTimeScale = max([requiredTimeScale, ...
                options.ParetoRefinementMinimumTimeScale, 1e-3]);
            maximumCandidateScale = max(1, minimumTimeScale);
            maximumCandidateScale = min( ...
                maximumCandidateScale, maximumTimeScale);
            timeScales = linspace(minimumTimeScale, ...
                maximumCandidateScale, ...
                options.ParetoRefinementTimeScaleCount);
            timeScales = unique([timeScales, 1]);
            timeScales = ...
                timeScales(timeScales <= maximumTimeScale + 1e-12);
            timeScales = sort(timeScales);
        end

        for timeScaleIndex = 1:numel(timeScales)
            timeScale = timeScales(timeScaleIndex);
            receipt.CandidateCount = receipt.CandidateCount + 1;
            candidateNodeTime_s = initialState.time_s + ...
                timeScale * relativeNodeTime_s;
            candidateNodeVelocity_deg_s = ...
                candidateKnotVelocity_deg_s / timeScale;
            candidateNodeAcceleration_deg_s2 = ...
                candidateKnotAcceleration_deg_s2 / timeScale^2;
            validationSample = sampleQuinticNodeStates( ...
                candidateNodeTime_s - initialState.time_s, ...
                blendedPosition_deg, candidateNodeVelocity_deg_s, ...
                candidateNodeAcceleration_deg_s2, ...
                options.ValidationStep_s);
            [candidateIsSafe, validationSample] = verifyParetoCandidate( ...
                validationSample, obstacleField, initialState, goalState, ...
                limits, options);
            if ~candidateIsSafe
                continue
            end
            receipt.FeasibleCandidateCount = ...
                receipt.FeasibleCandidateCount + 1;
            pathStep_deg = diff( ...
                validationSample.PositionUnwrapped_deg, 1, 1);
            pathLength_deg = sum(hypot( ...
                pathStep_deg(:, 1), pathStep_deg(:, 2)));
            completionDuration_s = candidateNodeTime_s(end) - ...
                initialState.time_s;
            combinedRatio = combinedParetoRatio( ...
                completionDuration_s, pathLength_deg, timeLowerBound_s, ...
                distanceLowerBound_deg, options);
            candidateRecord = struct( ...
                "Blend", blend, ...
                "DerivativePolicy", derivativePolicy, ...
                "TimeScale", timeScale, ...
                "NodeTime_s", candidateNodeTime_s, ...
                "Position_deg", blendedPosition_deg, ...
                "Velocity_deg_s", candidateNodeVelocity_deg_s, ...
                "Acceleration_deg_s2", ...
                    candidateNodeAcceleration_deg_s2, ...
                "PathLength_deg", pathLength_deg, ...
                "CompletionDuration_s", completionDuration_s, ...
                "CombinedRatio", combinedRatio, ...
                "MaximumJerkRatio", max(abs( ...
                    validationSample.Jerk_deg_s3) ./ ...
                    options.JointKinematicMaximumJerk_deg_s3, [], "all"));
            if combinedRatio < bestVerifiedCombinedRatio
                bestVerifiedCombinedRatio = combinedRatio;
                bestVerifiedCandidate = candidateRecord;
            end
            improvesCost = combinedRatio < bestCombinedRatio - 1e-8;
            tiesCostAndShortensTime = abs( ...
                combinedRatio - bestCombinedRatio) <= 1e-8 && ...
                completionDuration_s < ...
                receipt.RefinedCompletionTime_s - 1e-8;
            if improvesCost || tiesCostAndShortensTime
                bestCombinedRatio = combinedRatio;
                bestCandidate = candidateRecord;
                receipt.RefinedPathLength_deg = pathLength_deg;
                receipt.RefinedCompletionTime_s = completionDuration_s;
                receipt.SelectedCombinedRatio = combinedRatio;
                receipt.SelectedBlend = blend;
                receipt.SelectedTimeScale = timeScale;
                receipt.SelectedDerivativePolicy = derivativePolicy;
            end
        end
    end
end

% The global blends above provide safe starting points. Direct collocation
% then treats interior knot positions and the common clock as local decision
% variables. Each proposal still owns an exact quintic between states; there
% are no finite-difference dynamics defects for an optimizer to hide.
if ~isempty(fieldnames(bestVerifiedCandidate))
    candidateEvaluator = @(candidate) evaluateCollocationCandidate( ...
        candidate, obstacleField, initialState, goalState, limits, ...
        options, timeLowerBound_s, distanceLowerBound_deg);
    [coordinateCandidate, coordinateReceipt] = ...
        optimizeAzElDirectCollocation(bestVerifiedCandidate, ...
        candidateEvaluator, initialState.time_s, ...
        hasTerminalDynamics, options);
    receipt.CoordinateCandidateCount = ...
        coordinateReceipt.CandidateCount;
    receipt.CoordinateFeasibleCandidateCount = ...
        coordinateReceipt.FeasibleCandidateCount;
    receipt.CoordinatePassCount = coordinateReceipt.PassCount;
    receipt.CandidateCount = receipt.CandidateCount + ...
        coordinateReceipt.CandidateCount;
    receipt.FeasibleCandidateCount = ...
        receipt.FeasibleCandidateCount + ...
        coordinateReceipt.FeasibleCandidateCount;
    if coordinateCandidate.CombinedRatio < bestCombinedRatio - 1e-8
        bestCandidate = coordinateCandidate;
        receipt.RefinedPathLength_deg = ...
            coordinateCandidate.PathLength_deg;
        receipt.RefinedCompletionTime_s = ...
            coordinateCandidate.CompletionDuration_s;
        receipt.SelectedCombinedRatio = ...
            coordinateCandidate.CombinedRatio;
        receipt.SelectedBlend = coordinateCandidate.Blend;
        receipt.SelectedTimeScale = coordinateCandidate.TimeScale;
        receipt.SelectedDerivativePolicy = ...
            coordinateCandidate.DerivativePolicy;
    end
end

%% Section 3: Publish Only A Densely Verified Improvement
receipt.Success = true;
if isempty(fieldnames(bestCandidate))
    receipt.Message = ...
        "Continuous Pareto search completed; the validated discrete " + ...
        "trajectory remained the best safe candidate.";
    receipt.PhysicalVerification = auditPublishedPlanPhysics( ...
        plan, obstacleField, limits, options);
    receipt.PhysicalVerificationPassed = ...
        receipt.PhysicalVerification.Passed;
    return
end

commandSample = sampleQuinticNodeStates( ...
    bestCandidate.NodeTime_s - initialState.time_s, ...
    bestCandidate.Position_deg, bestCandidate.Velocity_deg_s, ...
    bestCandidate.Acceleration_deg_s2, options.SampleTime_s);
[commandIsSafe, commandSample] = verifyParetoCandidate( ...
    commandSample, obstacleField, initialState, goalState, limits, options);
if ~commandIsSafe
    receipt.Success = false;
    receipt.Message = ...
        "The selected Pareto candidate failed final command validation.";
    return
end

plan.time_s = commandSample.Time_s;
plan.positionUnwrapped_deg = commandSample.PositionUnwrapped_deg;
plan.position_deg = commandSample.Position_deg;
plan.velocity_deg_s = commandSample.Velocity_deg_s;
plan.acceleration_deg_s2 = commandSample.Acceleration_deg_s2;
plan.jerk_deg_s3 = commandSample.Jerk_deg_s3;
plan.isWaiting = commandSample.IsWaiting;
plan.angularPathLength_deg = bestCandidate.PathLength_deg;
if plan.objective == "minimumTime"
    plan.objectiveCost = bestCandidate.CompletionDuration_s;
    plan.objectiveCostUnits = "s";
else
    plan.objectiveCost = bestCandidate.PathLength_deg;
    plan.objectiveCostUnits = "deg";
end
plan.suboptimalityBound = max(1, ...
    bestCandidate.PathLength_deg / distanceLowerBound_deg);
if ~isfield(plan, "retiming") || ~isstruct(plan.retiming)
    plan.retiming = struct();
end
plan.retiming.MotionStyle = "continuousTimeDistancePareto";
plan.retiming.TimeScalingStyle = "verifiedUniformTimeScale";
plan.retiming.MinimumManeuverTime_s = ...
    bestCandidate.CompletionDuration_s;
receipt.Improved = true;
receipt.Message = ...
    "Adaptive direct-collocation Pareto refinement improved the trajectory.";
receipt.PhysicalVerification = auditCollocationCandidatePhysics( ...
    bestCandidate, plan, obstacleField, initialState, goalState, ...
    limits, options);
receipt.PhysicalVerificationPassed = ...
    receipt.PhysicalVerification.Passed;
plan.retiming.ParetoRefinement = receipt;
plan.message = string(plan.message) + ...
    " Continuous time/distance Pareto refinement accepted an improvement.";
end

function receipt = paretoReceiptTemplate()
receipt = struct( ...
    "Attempted", false, ...
    "Success", false, ...
    "Improved", false, ...
    "Message", "", ...
    "OptimizationMethod", ...
        "adaptivePiecewiseQuinticDirectCollocation", ...
    "CandidateCount", 0, ...
    "FeasibleCandidateCount", 0, ...
    "BaselinePathLength_deg", Inf, ...
    "BaselineCompletionTime_s", Inf, ...
    "BaselineCombinedRatio", Inf, ...
    "RefinedPathLength_deg", Inf, ...
    "RefinedCompletionTime_s", Inf, ...
    "SelectedCombinedRatio", Inf, ...
    "SelectedBlend", 0, ...
    "SelectedTimeScale", 1, ...
    "SelectedDerivativePolicy", "", ...
    "CollocationKnotCount", 0, ...
    "AdaptiveKnotCount", 0, ...
    "CoordinateCandidateCount", 0, ...
    "CoordinateFeasibleCandidateCount", 0, ...
    "CoordinatePassCount", 0, ...
    "PhysicalVerificationPassed", false, ...
    "PhysicalVerification", physicalVerificationTemplate());
end

function [knotTime_s, adaptiveKnotCount] = selectAdaptiveKnotTimes( ...
        sampleTime_s, position_deg, velocity_deg_s, options)
% The base mesh explains the normal case: one knot every requested number
% of seconds. A small reserved part of the knot budget belongs to important
% physical events. Sharp turns and transitions between stopped and moving
% states receive those extra knots because smoothing errors concentrate
% there.
maximumKnotCount = min( ...
    options.ParetoRefinementMaximumKnotCount, numel(sampleTime_s));
if maximumKnotCount <= 2
    knotTime_s = sampleTime_s([1 end]);
    adaptiveKnotCount = 0;
    return
end

duration_s = sampleTime_s(end) - sampleTime_s(1);
requestedBaseCount = ceil(duration_s / ...
    options.ParetoRefinementNodeStep_s) + 1;
reservedAdaptiveCount = min( ...
    max(2, floor(0.2 * maximumKnotCount)), ...
    maximumKnotCount - 2);
baseKnotCount = min(requestedBaseCount, ...
    maximumKnotCount - reservedAdaptiveCount);
baseKnotCount = max(2, baseKnotCount);
baseTime_s = linspace(sampleTime_s(1), sampleTime_s(end), ...
    baseKnotCount).';

sampleCount = numel(sampleTime_s);
eventScore = zeros(sampleCount, 1);
pathStep_deg = diff(position_deg, 1, 1);
pathStepLength_deg = hypot(pathStep_deg(:, 1), pathStep_deg(:, 2));
for sampleIndex = 2:sampleCount - 1
    incomingLength_deg = pathStepLength_deg(sampleIndex - 1);
    outgoingLength_deg = pathStepLength_deg(sampleIndex);
    if incomingLength_deg > 1e-12 && outgoingLength_deg > 1e-12
        incomingDirection = pathStep_deg(sampleIndex - 1, :) / ...
            incomingLength_deg;
        outgoingDirection = pathStep_deg(sampleIndex, :) / ...
            outgoingLength_deg;
        directionAgreement = max(-1, min(1, ...
            dot(incomingDirection, outgoingDirection)));
        eventScore(sampleIndex) = 1 - directionAgreement;
    end
end
speed_deg_s = hypot(velocity_deg_s(:, 1), velocity_deg_s(:, 2));
isStopped = speed_deg_s <= 1e-8;
transitionIndex = find(diff(isStopped) ~= 0) + 1;
eventScore(transitionIndex) = eventScore(transitionIndex) + 2;
eventScore([1 end]) = -Inf;
[~, priorityOrder] = sort(eventScore, "descend");

availableAdaptiveCount = min(reservedAdaptiveCount, ...
    maximumKnotCount - numel(baseTime_s));
adaptiveSampleIndex = zeros(availableAdaptiveCount, 1);
acceptedAdaptiveCount = 0;
for priorityIndex = 1:numel(priorityOrder)
    sampleIndex = priorityOrder(priorityIndex);
    if ~isfinite(eventScore(sampleIndex)) || ...
            eventScore(sampleIndex) <= 1e-3
        break
    end
    eventTime_s = sampleTime_s(sampleIndex);
    if any(abs(baseTime_s - eventTime_s) <= 1e-10)
        continue
    end
    acceptedAdaptiveCount = acceptedAdaptiveCount + 1;
    adaptiveSampleIndex(acceptedAdaptiveCount) = sampleIndex;
    if acceptedAdaptiveCount >= availableAdaptiveCount
        break
    end
end
adaptiveSampleIndex = ...
    adaptiveSampleIndex(1:acceptedAdaptiveCount);
knotTime_s = unique([baseTime_s; sampleTime_s(adaptiveSampleIndex)]);
adaptiveKnotCount = acceptedAdaptiveCount;
end

function [velocity_deg_s, acceleration_deg_s2] = ...
        estimateCollocationDerivatives( ...
        nodeTime_s, position_deg, initialState, goalState)
% Neighboring secants provide one readable geometry-based state estimate.
% Time-weighted velocity avoids favoring the shorter adjacent interval, and
% the slope change supplies the matching local acceleration. Requested
% endpoint dynamics remain authoritative.
nodeCount = numel(nodeTime_s);
velocity_deg_s = zeros(nodeCount, 2);
acceleration_deg_s2 = zeros(nodeCount, 2);
intervalDuration_s = diff(nodeTime_s);
intervalVelocity_deg_s = diff(position_deg, 1, 1) ./ intervalDuration_s;
velocity_deg_s(1, :) = initialState.velocity_deg_s;
velocity_deg_s(end, :) = goalState.velocity_deg_s;
acceleration_deg_s2(1, :) = initialState.acceleration_deg_s2;
acceleration_deg_s2(end, :) = goalState.acceleration_deg_s2;
for knotIndex = 2:nodeCount - 1
    previousDuration_s = intervalDuration_s(knotIndex - 1);
    nextDuration_s = intervalDuration_s(knotIndex);
    totalDuration_s = previousDuration_s + nextDuration_s;
    velocity_deg_s(knotIndex, :) = ( ...
        nextDuration_s * intervalVelocity_deg_s(knotIndex - 1, :) + ...
        previousDuration_s * intervalVelocity_deg_s(knotIndex, :)) / ...
        totalDuration_s;
    acceleration_deg_s2(knotIndex, :) = 2 * ( ...
        intervalVelocity_deg_s(knotIndex, :) - ...
        intervalVelocity_deg_s(knotIndex - 1, :)) / totalDuration_s;
end
end

function [candidateIsSafe, candidate] = evaluateCollocationCandidate( ...
        candidate, obstacleField, initialState, goalState, limits, ...
        options, timeLowerBound_s, distanceLowerBound_deg)
validationSample = sampleQuinticNodeStates( ...
    candidate.NodeTime_s - initialState.time_s, ...
    candidate.Position_deg, candidate.Velocity_deg_s, ...
    candidate.Acceleration_deg_s2, options.ValidationStep_s);
[candidateIsSafe, validationSample] = verifyParetoCandidate( ...
    validationSample, obstacleField, initialState, goalState, ...
    limits, options);
if ~candidateIsSafe
    return
end
pathStep_deg = diff(validationSample.PositionUnwrapped_deg, 1, 1);
candidate.PathLength_deg = sum(hypot( ...
    pathStep_deg(:, 1), pathStep_deg(:, 2)));
candidate.CompletionDuration_s = candidate.NodeTime_s(end) - ...
    initialState.time_s;
candidate.CombinedRatio = combinedParetoRatio( ...
    candidate.CompletionDuration_s, candidate.PathLength_deg, ...
    timeLowerBound_s, distanceLowerBound_deg, options);
candidate.MaximumJerkRatio = max(abs( ...
    validationSample.Jerk_deg_s3) ./ ...
    options.JointKinematicMaximumJerk_deg_s3, [], "all");
end

function verification = auditPublishedPlanPhysics( ...
        plan, obstacleField, limits, options)
verification = physicalVerificationTemplate();
verification.Attempted = true;
verification.SampleCount = numel(plan.time_s);
if isempty(plan.time_s) || isempty(plan.positionUnwrapped_deg)
    verification.Message = "The published plan has no samples to verify.";
    return
end

verification.AnalyticJerkAvailable = isfield(plan, "jerk_deg_s3") && ...
    isequal(size(plan.jerk_deg_s3), size(plan.velocity_deg_s)) && ...
    ~isempty(plan.jerk_deg_s3);
verification.MaximumVelocityRatio = max(abs(plan.velocity_deg_s) ./ ...
    limits.maxVelocity_deg_s, [], "all");
verification.MaximumAccelerationRatio = max(abs( ...
    plan.acceleration_deg_s2) ./ limits.maxAcceleration_deg_s2, ...
    [], "all");
if verification.AnalyticJerkAvailable
    verification.MaximumJerkRatio = max(abs(plan.jerk_deg_s3) ./ ...
        options.JointKinematicMaximumJerk_deg_s3, [], "all");
    verification.MaximumJerk_deg_s3 = max(abs( ...
        plan.jerk_deg_s3), [], 1);
else
    verification.MaximumJerkRatio = Inf;
    verification.MaximumJerk_deg_s3 = [Inf Inf];
end

insideElevation = plan.positionUnwrapped_deg(:, 2) >= ...
    limits.elevation_deg(1) - 1e-8 & ...
    plan.positionUnwrapped_deg(:, 2) <= limits.elevation_deg(2) + 1e-8;
insideAzimuth = true(size(insideElevation));
if ~options.AllowAzimuthWrap
    insideAzimuth = plan.positionUnwrapped_deg(:, 1) >= ...
        limits.azimuth_deg(1) - 1e-8 & ...
        plan.positionUnwrapped_deg(:, 1) <= ...
        limits.azimuth_deg(2) + 1e-8;
end
verification.PositionLimitsPassed = all(insideAzimuth & insideElevation);
blocked = queryAzElTimeObstacle(obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", options.TimePaddingSamples));
verification.CollisionCheckPassed = ~any(blocked);
verification.BlockedSampleCount = nnz(blocked);
verification.Passed = verification.AnalyticJerkAvailable && ...
    verification.PositionLimitsPassed && ...
    verification.CollisionCheckPassed && ...
    verification.MaximumVelocityRatio <= 1 + 1e-8 && ...
    verification.MaximumAccelerationRatio <= 1 + 1e-8 && ...
    verification.MaximumJerkRatio <= 1 + 1e-8;
if verification.Passed
    verification.Message = ...
        "Published trajectory passed dense position, collision, and derivative checks.";
elseif ~verification.AnalyticJerkAvailable
    verification.Message = ...
        "Fallback trajectory is valid but has no analytic bounded-jerk receipt.";
else
    verification.Message = ...
        "Published trajectory did not pass every dense physical check.";
end
end

function verification = auditCollocationCandidatePhysics( ...
        candidate, plan, obstacleField, initialState, goalState, ...
        limits, options)
% The public command may be sampled more coarsely than collision validation.
% Reconstruct the accepted quintics on the validation grid so the physical
% receipt describes the dense trajectory, not merely the exported rows.
denseSample = sampleQuinticNodeStates( ...
    candidate.NodeTime_s - initialState.time_s, ...
    candidate.Position_deg, candidate.Velocity_deg_s, ...
    candidate.Acceleration_deg_s2, options.ValidationStep_s);
[denseSampleIsSafe, denseSample] = verifyParetoCandidate( ...
    denseSample, obstacleField, initialState, goalState, limits, options);
densePlan = plan;
densePlan.time_s = denseSample.Time_s;
densePlan.positionUnwrapped_deg = denseSample.PositionUnwrapped_deg;
densePlan.position_deg = denseSample.Position_deg;
densePlan.velocity_deg_s = denseSample.Velocity_deg_s;
densePlan.acceleration_deg_s2 = denseSample.Acceleration_deg_s2;
densePlan.jerk_deg_s3 = denseSample.Jerk_deg_s3;
verification = auditPublishedPlanPhysics( ...
    densePlan, obstacleField, limits, options);
if ~denseSampleIsSafe
    verification.Passed = false;
    verification.Message = ...
        "Accepted collocation candidate failed its repeated dense audit.";
end
end

function verification = physicalVerificationTemplate()
verification = struct( ...
    "Attempted", false, ...
    "Passed", false, ...
    "Message", "", ...
    "AnalyticJerkAvailable", false, ...
    "PositionLimitsPassed", false, ...
    "CollisionCheckPassed", false, ...
    "BlockedSampleCount", 0, ...
    "SampleCount", 0, ...
    "MaximumVelocityRatio", Inf, ...
    "MaximumAccelerationRatio", Inf, ...
    "MaximumJerkRatio", Inf, ...
    "MaximumJerk_deg_s3", [Inf Inf]);
end

function [position_deg, velocity_deg_s, acceleration_deg_s2] = ...
        endpointQuinticMotion(time_s, duration_s, initialState, goalState)
% A fifth-order polynomial is the lowest order that can match position,
% velocity, and acceleration at both endpoints. Normalized time keeps the
% small coefficient solve well conditioned for both short and long missions.
initialPosition_deg = initialState.position_deg;
initialVelocityScaled_deg = initialState.velocity_deg_s * duration_s;
initialAccelerationScaled_deg = ...
    initialState.acceleration_deg_s2 * duration_s^2;
goalVelocityScaled_deg = goalState.velocity_deg_s * duration_s;
goalAccelerationScaled_deg = ...
    goalState.acceleration_deg_s2 * duration_s^2;
coefficient0 = initialPosition_deg;
coefficient1 = initialVelocityScaled_deg;
coefficient2 = 0.5 * initialAccelerationScaled_deg;
remainingPosition_deg = goalState.position_deg - ...
    coefficient0 - coefficient1 - coefficient2;
remainingVelocity_deg = goalVelocityScaled_deg - ...
    coefficient1 - 2 * coefficient2;
remainingAcceleration_deg = goalAccelerationScaled_deg - ...
    2 * coefficient2;
coefficientMatrix = [1 1 1; 3 4 5; 6 12 20];
higherCoefficients = coefficientMatrix \ [ ...
    remainingPosition_deg; remainingVelocity_deg; ...
    remainingAcceleration_deg];
coefficient3 = higherCoefficients(1, :);
coefficient4 = higherCoefficients(2, :);
coefficient5 = higherCoefficients(3, :);
normalizedTime = time_s / duration_s;
position_deg = coefficient0 + normalizedTime .* coefficient1 + ...
    normalizedTime.^2 .* coefficient2 + ...
    normalizedTime.^3 .* coefficient3 + ...
    normalizedTime.^4 .* coefficient4 + ...
    normalizedTime.^5 .* coefficient5;
velocity_deg_s = (coefficient1 + ...
    2 * normalizedTime .* coefficient2 + ...
    3 * normalizedTime.^2 .* coefficient3 + ...
    4 * normalizedTime.^3 .* coefficient4 + ...
    5 * normalizedTime.^4 .* coefficient5) / duration_s;
acceleration_deg_s2 = (2 * coefficient2 + ...
    6 * normalizedTime .* coefficient3 + ...
    12 * normalizedTime.^2 .* coefficient4 + ...
    20 * normalizedTime.^3 .* coefficient5) / duration_s^2;
end

function sample = sampleQuinticNodeStates( ...
        nodeTime_s, nodePosition_deg, nodeVelocity_deg_s, ...
        nodeAcceleration_deg_s2, maximumSampleStep_s)
% Each neighboring state pair owns one quintic segment. Matching both
% endpoint accelerations prevents artificial velocity or acceleration jumps
% at the original planner samples.
segmentCount = numel(nodeTime_s) - 1;
sampleCapacity = max(2, ceil((nodeTime_s(end) - nodeTime_s(1)) / ...
    maximumSampleStep_s) + segmentCount + 1);
time_s = zeros(sampleCapacity, 1);
position_deg = zeros(sampleCapacity, 2);
velocity_deg_s = zeros(sampleCapacity, 2);
acceleration_deg_s2 = zeros(sampleCapacity, 2);
jerk_deg_s3 = zeros(sampleCapacity, 2);
sampleCount = 1;
time_s(1) = nodeTime_s(1);
position_deg(1, :) = nodePosition_deg(1, :);
velocity_deg_s(1, :) = nodeVelocity_deg_s(1, :);
acceleration_deg_s2(1, :) = nodeAcceleration_deg_s2(1, :);

for segmentIndex = 1:segmentCount
    duration_s = nodeTime_s(segmentIndex + 1) - ...
        nodeTime_s(segmentIndex);
    if duration_s <= 0
        continue
    end
    intervalCount = max(1, ceil(duration_s / maximumSampleStep_s));
    normalizedTime = (1:intervalCount).' / intervalCount;
    segmentSampleCount = numel(normalizedTime);
    requiredCapacity = sampleCount + segmentSampleCount;
    if requiredCapacity > sampleCapacity
        newCapacity = max(requiredCapacity, 2 * sampleCapacity);
        time_s(newCapacity, 1) = 0;
        position_deg(newCapacity, 2) = 0;
        velocity_deg_s(newCapacity, 2) = 0;
        acceleration_deg_s2(newCapacity, 2) = 0;
        jerk_deg_s3(newCapacity, 2) = 0;
        sampleCapacity = newCapacity;
    end
    positionDelta_deg = nodePosition_deg(segmentIndex + 1, :) - ...
        nodePosition_deg(segmentIndex, :);
    scaledInitialVelocity_deg = ...
        duration_s * nodeVelocity_deg_s(segmentIndex, :);
    scaledFinalVelocity_deg = ...
        duration_s * nodeVelocity_deg_s(segmentIndex + 1, :);
    scaledInitialAcceleration_deg = ...
        duration_s^2 * nodeAcceleration_deg_s2(segmentIndex, :);
    scaledFinalAcceleration_deg = ...
        duration_s^2 * nodeAcceleration_deg_s2(segmentIndex + 1, :);
    coefficient0 = nodePosition_deg(segmentIndex, :);
    coefficient1 = scaledInitialVelocity_deg;
    coefficient2 = 0.5 * scaledInitialAcceleration_deg;
    coefficient3 = 10 * positionDelta_deg - ...
        6 * scaledInitialVelocity_deg - 4 * scaledFinalVelocity_deg - ...
        1.5 * scaledInitialAcceleration_deg + ...
        0.5 * scaledFinalAcceleration_deg;
    coefficient4 = -15 * positionDelta_deg + ...
        8 * scaledInitialVelocity_deg + 7 * scaledFinalVelocity_deg + ...
        1.5 * scaledInitialAcceleration_deg - ...
        scaledFinalAcceleration_deg;
    coefficient5 = 6 * positionDelta_deg - ...
        3 * scaledInitialVelocity_deg - 3 * scaledFinalVelocity_deg - ...
        0.5 * scaledInitialAcceleration_deg + ...
        0.5 * scaledFinalAcceleration_deg;
    if segmentIndex == 1
        % The first sample is not generated by the loop below. Record its
        % exact right-hand jerk so the dense limit check includes launch.
        jerk_deg_s3(1, :) = 6 * coefficient3 / duration_s^3;
    end
    sampleRows = sampleCount + (1:segmentSampleCount);
    time_s(sampleRows) = nodeTime_s(segmentIndex) + ...
        duration_s * normalizedTime;
    position_deg(sampleRows, :) = coefficient0 + ...
        normalizedTime .* coefficient1 + ...
        normalizedTime.^2 .* coefficient2 + ...
        normalizedTime.^3 .* coefficient3 + ...
        normalizedTime.^4 .* coefficient4 + ...
        normalizedTime.^5 .* coefficient5;
    velocity_deg_s(sampleRows, :) = (coefficient1 + ...
        2 * normalizedTime .* coefficient2 + ...
        3 * normalizedTime.^2 .* coefficient3 + ...
        4 * normalizedTime.^3 .* coefficient4 + ...
        5 * normalizedTime.^4 .* coefficient5) / duration_s;
    acceleration_deg_s2(sampleRows, :) = (2 * coefficient2 + ...
        6 * normalizedTime .* coefficient3 + ...
        12 * normalizedTime.^2 .* coefficient4 + ...
        20 * normalizedTime.^3 .* coefficient5) / duration_s^2;
    jerk_deg_s3(sampleRows, :) = (6 * coefficient3 + ...
        24 * normalizedTime .* coefficient4 + ...
        60 * normalizedTime.^2 .* coefficient5) / duration_s^3;
    sampleCount = requiredCapacity;
end

sample = struct( ...
    "Time_s", time_s(1:sampleCount), ...
    "PositionUnwrapped_deg", position_deg(1:sampleCount, :), ...
    "Position_deg", position_deg(1:sampleCount, :), ...
    "Velocity_deg_s", velocity_deg_s(1:sampleCount, :), ...
    "Acceleration_deg_s2", acceleration_deg_s2(1:sampleCount, :), ...
    "Jerk_deg_s3", jerk_deg_s3(1:sampleCount, :), ...
    "IsWaiting", false(sampleCount, 1));
end

function requiredScale = requiredPhysicalTimeScale( ...
        sample, limits, maximumJerk_deg_s3)
velocityRatio = max(abs(sample.Velocity_deg_s) ./ ...
    limits.maxVelocity_deg_s, [], "all");
accelerationRatio = max(abs(sample.Acceleration_deg_s2) ./ ...
    limits.maxAcceleration_deg_s2, [], "all");
jerkRatio = max(abs(sample.Jerk_deg_s3) ./ ...
    maximumJerk_deg_s3, [], "all");
requiredScale = max([velocityRatio, sqrt(accelerationRatio), ...
    nthroot(max(jerkRatio, 0), 3), 0]);
requiredScale = requiredScale * 1.0001;
end

function [candidateIsSafe, sample] = verifyParetoCandidate( ...
        sample, obstacleField, initialState, goalState, limits, options)
% Append the terminal hold before validation. Dynamic examples can therefore
% reject an earlier arrival when the goal later becomes occupied.
completionTime_s = sample.Time_s(end) + initialState.time_s;
sample.Time_s = sample.Time_s + initialState.time_s;
hasTerminalDynamics = any(abs([goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2]) > 1e-12);
if hasTerminalDynamics && abs(completionTime_s - goalState.time_s) > 1e-8
    candidateIsSafe = false;
    return
end
if completionTime_s < goalState.time_s - 1e-12
    waitingTime_s = (completionTime_s + options.ValidationStep_s: ...
        options.ValidationStep_s:goalState.time_s).';
    if isempty(waitingTime_s) || waitingTime_s(end) < goalState.time_s
        waitingTime_s(end + 1, 1) = goalState.time_s;
    end
    waitingCount = numel(waitingTime_s);
    sample.Time_s = [sample.Time_s; waitingTime_s];
    sample.PositionUnwrapped_deg = [sample.PositionUnwrapped_deg; ...
        repmat(sample.PositionUnwrapped_deg(end, :), waitingCount, 1)];
    sample.Velocity_deg_s = [sample.Velocity_deg_s; ...
        zeros(waitingCount, 2)];
    sample.Acceleration_deg_s2 = [sample.Acceleration_deg_s2; ...
        zeros(waitingCount, 2)];
    sample.Jerk_deg_s3 = [sample.Jerk_deg_s3; zeros(waitingCount, 2)];
    sample.IsWaiting = [sample.IsWaiting; true(waitingCount, 1)];
end

sample.Position_deg = sample.PositionUnwrapped_deg;
if options.AllowAzimuthWrap
    azimuthMinimum_deg = limits.azimuth_deg(1);
    azimuthSpan_deg = diff(limits.azimuth_deg);
    sample.Position_deg(:, 1) = azimuthMinimum_deg + mod( ...
        sample.Position_deg(:, 1) - azimuthMinimum_deg, azimuthSpan_deg);
end
insideElevation = sample.PositionUnwrapped_deg(:, 2) >= ...
    limits.elevation_deg(1) - 1e-8 & ...
    sample.PositionUnwrapped_deg(:, 2) <= limits.elevation_deg(2) + 1e-8;
insideAzimuth = true(size(insideElevation));
if ~options.AllowAzimuthWrap
    insideAzimuth = sample.PositionUnwrapped_deg(:, 1) >= ...
        limits.azimuth_deg(1) - 1e-8 & ...
        sample.PositionUnwrapped_deg(:, 1) <= ...
        limits.azimuth_deg(2) + 1e-8;
end
derivativesAreSafe = all(abs(sample.Velocity_deg_s) <= ...
    limits.maxVelocity_deg_s + 1e-8, "all") && ...
    all(abs(sample.Acceleration_deg_s2) <= ...
    limits.maxAcceleration_deg_s2 + 1e-8, "all") && ...
    all(abs(sample.Jerk_deg_s3) <= ...
    options.JointKinematicMaximumJerk_deg_s3 + 1e-8, "all");
if ~all(insideAzimuth & insideElevation) || ~derivativesAreSafe
    candidateIsSafe = false;
    return
end
blocked = queryAzElTimeObstacle(obstacleField, ...
    sample.Position_deg(:, 1), sample.Position_deg(:, 2), ...
    sample.Time_s, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", options.TimePaddingSamples));
candidateIsSafe = ~any(blocked);
end

function ratio = combinedParetoRatio(duration_s, pathLength_deg, ...
        timeLowerBound_s, distanceLowerBound_deg, options)
ratio = options.JointKinematicTimeWeight * ...
    duration_s / timeLowerBound_s + ...
    options.JointKinematicDistanceWeight * ...
    pathLength_deg / distanceLowerBound_deg;
end

function lowerBound_s = restToRestTimeLowerBound( ...
        startPosition_deg, goalPosition_deg, limits)
distanceByAxis_deg = abs(goalPosition_deg - startPosition_deg);
axisTime_s = zeros(1, 2);
for axisIndex = 1:2
    maximumVelocity_deg_s = limits.maxVelocity_deg_s(axisIndex);
    maximumAcceleration_deg_s2 = ...
        limits.maxAcceleration_deg_s2(axisIndex);
    accelerationDistance_deg = maximumVelocity_deg_s^2 / ...
        maximumAcceleration_deg_s2;
    if distanceByAxis_deg(axisIndex) <= accelerationDistance_deg
        axisTime_s(axisIndex) = 2 * sqrt( ...
            distanceByAxis_deg(axisIndex) / maximumAcceleration_deg_s2);
    else
        axisTime_s(axisIndex) = distanceByAxis_deg(axisIndex) / ...
            maximumVelocity_deg_s + maximumVelocity_deg_s / ...
            maximumAcceleration_deg_s2;
    end
end
lowerBound_s = max(axisTime_s);
end

function value = fieldOr(record, fieldName, fallback)
if isstruct(record) && isfield(record, fieldName) && ...
        ~isempty(record.(fieldName)) && isfinite(record.(fieldName))
    value = record.(fieldName);
else
    value = fallback;
end
end
