function result = refineAzElTopologyCorridor( ...
        workspace, coarseRoute_deg, startPosition_deg, ...
        goalPosition_deg, limits, queryTime_s, options)
%REFINEAZELTOPOLOGYCORRIDOR Optimize a route inside its coarse corridor tube.
%
% A fine occupancy grid is evaluated only near the coarse polyline. Cells
% outside that tube are treated as occupied, concentrating refinement around
% the discovered route without querying every fine-grid point for collision.

if options.AllowAzimuthWrap
    result = failedResult( ...
        "Corridor refinement currently defers wrapped azimuth routes.");
    return;
end

timer = tic;
azimuth = inclusiveGrid( ...
    limits.azimuth_deg, options.RefinementGridStep_deg);
elevation = inclusiveGrid( ...
    limits.elevation_deg, options.RefinementGridStep_deg);
[azimuthGrid, elevationGrid] = meshgrid(azimuth, elevation);
point = [azimuthGrid(:), elevationGrid(:)];
distanceSquared = pointToPolylineDistanceSquared( ...
    point, coarseRoute_deg);
candidate = distanceSquared <= ...
    options.RefinementCorridorHalfWidth_deg^2;

occupied = true(size(point, 1), 1);
if any(candidate)
    occupied(candidate) = queryAzElTimeObstacle(workspace, ...
        point(candidate, 1), point(candidate, 2), queryTime_s, struct( ...
        "CollisionMode", "polygon", ...
        "SafetyMarginDeg", options.SafetyMargin_deg));
end
occupied = reshape(occupied, size(azimuthGrid));
searchOptions = struct( ...
    "AllowAzimuthWrap", false, ...
    "HeuristicWeight", options.RefinementHeuristicWeight, ...
    "UseAnyAngleRelaxation", true, ...
    "MaximumExpandedNodes", options.RefinementMaximumExpansions, ...
    "MaximumWallTime_s", options.RefinementWallTime_s);
search = searchAzElAnyAngleAStar( ...
    occupied, azimuth, elevation, ...
    startPosition_deg, goalPosition_deg, searchOptions);

result = search;
result.CandidateCellCount = nnz(candidate);
result.TotalCellCount = numel(candidate);
result.RasterElapsed_s = toc(timer) - search.SearchElapsed_s;
if result.Success
    result.Method = "corridorRefinedAnyAngleAStar";
    result.Message = "Fine route found inside the coarse topology tube.";
end
end

function distanceSquared = pointToPolylineDistanceSquared(point, route)
distanceSquared = inf(size(point, 1), 1);
for segment = 1:size(route, 1) - 1
    first = route(segment, :);
    delta = route(segment + 1, :) - first;
    lengthSquared = sum(delta.^2);
    if lengthSquared <= eps
        candidate = sum((point - first).^2, 2);
    else
        fraction = ((point(:, 1) - first(1)) * delta(1) + ...
            (point(:, 2) - first(2)) * delta(2)) / lengthSquared;
        fraction = min(max(fraction, 0), 1);
        closest = first + fraction .* delta;
        candidate = sum((point - closest).^2, 2);
    end
    distanceSquared = min(distanceSquared, candidate);
end
end

function values = inclusiveGrid(limits, step)
values = limits(1):step:limits(2);
if values(end) < limits(2) - 1e-9
    values(end + 1) = limits(2);
end
values = double(values);
end

function result = failedResult(message)
result = struct( ...
    "Success", false, ...
    "Message", string(message), ...
    "Method", "corridorRefinedAnyAngleAStar", ...
    "Path_deg", zeros(0, 2), ...
    "GridNodePath", zeros(0, 1, "uint32"), ...
    "AngularLength_deg", Inf, ...
    "ExpandedNodeCount", 0, ...
    "GeneratedNodeCount", 0, ...
    "SearchElapsed_s", 0, ...
    "TerminationReason", "notRun", ...
    "Options", struct(), ...
    "CandidateCellCount", 0, ...
    "TotalCellCount", 0, ...
    "RasterElapsed_s", 0);
end
