function [pyramid, patch] = refineAzElTimeWorkspacePyramid( ...
        pyramid, workspace, region, options)
%REFINEAZELTIMEWORKSPACEPYRAMID Add one local fine az/el/time raster.
%
% [pyramid, patch] = refineAzElTimeWorkspacePyramid( ...
%     pyramid, workspace, region)
%
% Required region fields:
%   AzimuthLimitsDeg    [minimum maximum]
%   ElevationLimitsDeg  [minimum maximum]
%   TimeLimitsSeconds   [minimum maximum]
%
% The requested region is clipped to the pyramid and, by default, expanded
% to complete coarse cells. Only that rectangular subvolume is rasterized.
%
% Options:
%   CellSizeDeg          Default pyramid.FineSpec.CellSizeDeg.
%   MaximumTimeSamples   Default pyramid.FineSpec.MaximumTimeSamples.
%   TimeSeconds          Explicit fine time samples, default [].
%   UseAllSourceTimes    Use every source time in the region, default false.
%   TimeMapping          'nearest' or 'bracket', default 'bracket'.
%   MarginCells          Fine-grid dilation, default 0.
%   OutOfRangeTime       Default 'free'.
%   UseParallel          Default false.
%   SnapToCoarseCells    Default true.
%   MaximumFineVoxels    Memory guard, default 5e7 logical voxels.

if nargin < 4
    options = struct();
end
validatePyramid(pyramid);
validatePackedWorkspace(workspace);
region = normalizeRegion(region, pyramid.GridSpec);
options = normalizeOptions(options, pyramid);
if options.SnapToCoarseCells
    region.AzimuthLimitsDeg = snapLimits( ...
        region.AzimuthLimitsDeg, ...
        pyramid.GridSpec.AzimuthLimitsDeg, ...
        pyramid.Options.CoarseCellSizeDeg(1));
    region.ElevationLimitsDeg = snapLimits( ...
        region.ElevationLimitsDeg, ...
        pyramid.GridSpec.ElevationLimitsDeg, ...
        pyramid.Options.CoarseCellSizeDeg(2));
    ratio = pyramid.Options.CoarseCellSizeDeg ./ options.CellSizeDeg;
    if any(abs(ratio - round(ratio)) > 1e-9)
        error("refineAzElTimeWorkspacePyramid:NonNestedCellSize", ...
            "CellSizeDeg must divide CoarseCellSizeDeg when snapping.");
    end
end

sourceTimes = sourceTimeSamples(workspace, region.TimeLimitsSeconds);
if ~isempty(options.TimeSeconds)
    fineTimes = double(options.TimeSeconds(:));
    if any(diff(fineTimes) <= 0) || ...
            fineTimes(1) < region.TimeLimitsSeconds(1) - 1e-9 || ...
            fineTimes(end) > region.TimeLimitsSeconds(2) + 1e-9
        error("refineAzElTimeWorkspacePyramid:InvalidTimeSeconds", ...
            "TimeSeconds must increase within the refinement region.");
    end
elseif options.UseAllSourceTimes
    fineTimes = sourceTimes;
else
    fineTimes = decimateTimes( ...
        sourceTimes, options.MaximumTimeSamples);
end

numAz = floor(diff(region.AzimuthLimitsDeg) / ...
    options.CellSizeDeg(1) + 1e-9);
numEl = floor(diff(region.ElevationLimitsDeg) / ...
    options.CellSizeDeg(2) + 1e-9);
voxelCount = double(numAz) * double(numEl) * numel(fineTimes);
if voxelCount > options.MaximumFineVoxels
    error("refineAzElTimeWorkspacePyramid:FineGridTooLarge", ...
        "The patch would contain %.0f voxels. Shrink the region, " + ...
        "increase CellSizeDeg, or lower MaximumTimeSamples.", ...
        voxelCount);
end

fineSpec = struct( ...
    "AzimuthLimitsDeg", region.AzimuthLimitsDeg, ...
    "ElevationLimitsDeg", region.ElevationLimitsDeg, ...
    "CellSizeDeg", options.CellSizeDeg, ...
    "TimeSeconds", fineTimes);
rasterOptions = struct( ...
    "TimeMapping", options.TimeMapping, ...
    "MarginCells", options.MarginCells, ...
    "OutOfRangeTime", options.OutOfRangeTime, ...
    "UseParallel", options.UseParallel);
fineGrid = rasterizeAzElTimeWorkspace( ...
    workspace, fineSpec, rasterOptions);

patch = struct( ...
    "Id", numel(pyramid.FinePatches) + 1, ...
    "Region", region, ...
    "Grid", fineGrid, ...
    "SourceTimeSampleCount", numel(sourceTimes), ...
    "UsedTimeSampleCount", numel(fineTimes), ...
    "TimeWasDecimated", numel(fineTimes) < numel(sourceTimes), ...
    "CoveredCandidateVoxelCount", ...
    countCoveredCandidates(pyramid, region));
pyramid.FinePatches(end + 1, 1) = patch;
pyramid.Stats.FinePatchCount = numel(pyramid.FinePatches);
pyramid.Stats.FinePatchVoxelCount = ...
    pyramid.Stats.FinePatchVoxelCount + numel(fineGrid.Occupancy);
end

function validatePyramid(pyramid)
if ~isstruct(pyramid) || ~isscalar(pyramid) || ...
        ~isfield(pyramid, "Format") || ...
        pyramid.Format ~= "AzElTimeWorkspacePyramid" || ...
        ~isfield(pyramid, "Coarse") || ...
        ~isfield(pyramid, "FinePatches")
    error("refineAzElTimeWorkspacePyramid:InvalidPyramid", ...
        "Use buildAzElTimeWorkspacePyramid to create pyramid.");
end
end

function validatePackedWorkspace(workspace)
if ~isstruct(workspace) || ~isscalar(workspace) || ...
        ~isfield(workspace, "Format") || ...
        workspace.Format ~= "AzElTimeObstacleWorkspace"
    error("refineAzElTimeWorkspacePyramid:InvalidWorkspace", ...
        "Use buildAzElTimeObstacleWorkspace to create workspace.");
end
end

function region = normalizeRegion(region, globalSpec)
required = ["AzimuthLimitsDeg", "ElevationLimitsDeg", ...
    "TimeLimitsSeconds"];
if ~isstruct(region) || ~isscalar(region) || ...
        ~all(isfield(region, cellstr(required)))
    error("refineAzElTimeWorkspacePyramid:InvalidRegion", ...
        "region must define azimuth, elevation, and time limits.");
end
region.AzimuthLimitsDeg = clippedLimits( ...
    region.AzimuthLimitsDeg, globalSpec.AzimuthLimitsDeg, ...
    "AzimuthLimitsDeg");
region.ElevationLimitsDeg = clippedLimits( ...
    region.ElevationLimitsDeg, globalSpec.ElevationLimitsDeg, ...
    "ElevationLimitsDeg");
region.TimeLimitsSeconds = clippedLimits( ...
    region.TimeLimitsSeconds, globalSpec.TimeLimitsSeconds, ...
    "TimeLimitsSeconds");
end

function options = normalizeOptions(options, pyramid)
defaults = struct( ...
    "CellSizeDeg", pyramid.FineSpec.CellSizeDeg, ...
    "MaximumTimeSamples", pyramid.FineSpec.MaximumTimeSamples, ...
    "TimeSeconds", [], ...
    "UseAllSourceTimes", false, ...
    "TimeMapping", "bracket", ...
    "MarginCells", 0, ...
    "OutOfRangeTime", "free", ...
    "UseParallel", false, ...
    "SnapToCoarseCells", true, ...
    "MaximumFineVoxels", 5e7);
options = applyDefaults(options, defaults);
options.CellSizeDeg = normalizeCellSize(options.CellSizeDeg);
validateattributes(options.MaximumTimeSamples, {'numeric'}, ...
    {'scalar', 'integer', '>=', 2});
validateattributes(options.MarginCells, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.MaximumFineVoxels, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
logicalNames = ["UseAllSourceTimes", "UseParallel", ...
    "SnapToCoarseCells"];
for name = logicalNames
    validateattributes(options.(name), ...
        {'logical', 'numeric'}, {'scalar'});
    options.(name) = logical(options.(name));
end
options.TimeMapping = string(validatestring( ...
    options.TimeMapping, {'nearest', 'bracket'}));
options.OutOfRangeTime = string(validatestring( ...
    options.OutOfRangeTime, {'error', 'clamp', 'free'}));
if ~isempty(options.TimeSeconds)
    validateattributes(options.TimeSeconds, {'numeric'}, ...
        {'vector', 'real', 'finite', 'nonempty'});
end
end

function value = clippedLimits(value, available, name)
validateattributes(value, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite'});
value = reshape(double(value), 1, 2);
if value(2) <= value(1)
    error("refineAzElTimeWorkspacePyramid:InvalidLimits", ...
        "%s must increase.", name);
end
value = [max(value(1), available(1)), ...
    min(value(2), available(2))];
if value(2) <= value(1)
    error("refineAzElTimeWorkspacePyramid:RegionOutsidePyramid", ...
        "%s does not overlap the pyramid.", name);
end
end

function value = snapLimits(value, available, cellSize)
lowerIndex = floor((value(1) - available(1)) / cellSize + 1e-10);
upperIndex = ceil((value(2) - available(1)) / cellSize - 1e-10);
value = available(1) + [lowerIndex upperIndex] * cellSize;
value(1) = max(value(1), available(1));
value(2) = min(value(2), available(2));
end

function values = sourceTimeSamples(workspace, limits)
parts = cell(numel(workspace.Obstacles), 1);
for k = 1:numel(workspace.Obstacles)
    values = double(workspace.Obstacles(k).TimeSeconds(:));
    parts{k} = values(values >= limits(1) & values <= limits(2));
end
values = unique([limits(:); vertcat(parts{:})]);
end

function selected = decimateTimes(values, maximum)
values = unique(double(values(:)));
if numel(values) <= maximum
    selected = values;
    return;
end
target = linspace(values(1), values(end), maximum).';
index = interp1(values, (1:numel(values)).', target, "nearest");
selected = values(unique([1; round(index); numel(values)]));
end

function count = countCoveredCandidates(pyramid, region)
azimuth = pyramid.Coarse.AzimuthCentersDeg;
elevation = pyramid.Coarse.ElevationCentersDeg;
time = pyramid.Coarse.TimeSeconds;
azimuthIndex = azimuth >= region.AzimuthLimitsDeg(1) & ...
    azimuth <= region.AzimuthLimitsDeg(2);
elevationIndex = elevation >= region.ElevationLimitsDeg(1) & ...
    elevation <= region.ElevationLimitsDeg(2);
timeIndex = time >= region.TimeLimitsSeconds(1) & ...
    time <= region.TimeLimitsSeconds(2);
count = nnz(pyramid.RefinementCandidateMask( ...
    elevationIndex, azimuthIndex, timeIndex));
end

function value = normalizeCellSize(value)
validateattributes(value, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
if isscalar(value)
    value = [value value];
elseif numel(value) ~= 2
    error("refineAzElTimeWorkspacePyramid:InvalidCellSize", ...
        "CellSizeDeg must be scalar or have two elements.");
end
value = reshape(double(value), 1, 2);
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
