function retiming = retimeSimpleAzElStaticTopologyRoute( ...
        staticTopology, initialState, destinationState, limits, ...
        obstacleField, options)
%% Section 0: Header & Readme
% SYNTAX
%   retiming = retimeSimpleAzElStaticTopologyRoute()
%   retiming = retimeSimpleAzElStaticTopologyRoute( ...
%       staticTopology, initialState, destinationState, limits, ...
%       obstacleField, options)
%**************************************************************************
% PURPOSE
%   - Convert one static goal-rooted topology route into synchronized
%     rest-to-rest azimuth/elevation segments.
%   - Use a quintic smoothstep whose analytic velocity, acceleration, and
%     jerk bounds select a physically admissible duration for every segment.
%   - Sample the same analytic trajectory against the packed obstacle field.
%**************************************************************************
% INPUTS
%   - staticTopology (scalar diagnostic struct)
%       Successful record from buildSimpleAzElStaticTopologyDijkstra.
%   - initialState, destinationState (scalar structs)
%       Complete endpoint states. This feature requires rest endpoints and
%       uses destinationState.time_s as the exact terminal time.
%   - limits (scalar struct)
%       Position bounds and two-axis velocity, acceleration, and jerk limits.
%   - obstacleField (scalar packed obstacle struct)
%       Geometry queried during sampled trajectory validation.
%   - options (scalar struct)
%       Resolved simple-planner wrapping, collision, and waiting options.
%**************************************************************************
% OUTPUTS
%   - retiming (scalar diagnostic struct)
%       PascalCase fields expose success, the retained topology turns,
%       segment durations and bounds, sampled trajectory, and validation.
%       A zero-argument call returns the unused record template.
%**************************************************************************
% UNITS
%   - Angles are degrees. Time is seconds. Derivatives use deg/s through
%     deg/s^3.

%% Section 1: Validate Feature Inputs
retiming = emptySimpleAzElAnalyticRetiming();
if nargin == 0
    return;
end
retiming.Used = true;
if ~isstruct(staticTopology) || ~isscalar(staticTopology) || ...
        ~isfield(staticTopology, "Success") || ...
        ~isfield(staticTopology, "InitialPath_deg")
    error("retimeSimpleAzElStaticTopologyRoute:InvalidTopology", ...
        "staticTopology must contain Success and InitialPath_deg.");
end
if ~staticTopology.Success
    retiming.Message = "Static topology did not provide a route: " + ...
        string(staticTopology.Message);
    return;
end

endpointDynamics = [ ...
    initialState.velocity_deg_s, initialState.acceleration_deg_s2; ...
    destinationState.velocity_deg_s, ...
    destinationState.acceleration_deg_s2];
restTolerance = 1e-12;
if any(abs(endpointDynamics) > restTolerance, "all")
    retiming.Message = "Analytic rest-to-rest retiming requires zero " + ...
        "initial and destination velocity and acceleration.";
    return;
end

availableManeuverTime_s = ...
    destinationState.time_s - initialState.time_s;
retiming.AvailableManeuverTime_s = availableManeuverTime_s;

%% Section 2: Retain Only Genuine Topology Turns
routePositionsUnwrapped_deg = [ ...
    initialState.position_deg; ...
    staticTopology.InitialPath_deg; ...
    destinationState.position_deg];
if options.allowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    for waypointIndex = 2:size(routePositionsUnwrapped_deg, 1)
        wrappedStep_deg = mod( ...
            routePositionsUnwrapped_deg(waypointIndex, 1) - ...
            routePositionsUnwrapped_deg(waypointIndex - 1, 1) + ...
            azimuthSpan_deg / 2, azimuthSpan_deg) - ...
            azimuthSpan_deg / 2;
        routePositionsUnwrapped_deg(waypointIndex, 1) = ...
            routePositionsUnwrapped_deg(waypointIndex - 1, 1) + ...
            wrappedStep_deg;
    end
end

duplicateTolerance_deg = 1e-10;
keepWaypoint = true(size(routePositionsUnwrapped_deg, 1), 1);
keepWaypoint(2:end) = hypot( ...
    diff(routePositionsUnwrapped_deg(:, 1)), ...
    diff(routePositionsUnwrapped_deg(:, 2))) > duplicateTolerance_deg;
routePositionsUnwrapped_deg = ...
    routePositionsUnwrapped_deg(keepWaypoint, :);
inputWaypointCount = size(routePositionsUnwrapped_deg, 1);

if inputWaypointCount > 2
    retainedRoute_deg = zeros(size(routePositionsUnwrapped_deg));
    retainedWaypointCount = 1;
    retainedRoute_deg(1, :) = routePositionsUnwrapped_deg(1, :);
    for waypointIndex = 2:inputWaypointCount - 1
        incomingStep_deg = routePositionsUnwrapped_deg(waypointIndex, :) - ...
            retainedRoute_deg(retainedWaypointCount, :);
        outgoingStep_deg = ...
            routePositionsUnwrapped_deg(waypointIndex + 1, :) - ...
            routePositionsUnwrapped_deg(waypointIndex, :);
        signedCrossProduct_deg2 = ...
            incomingStep_deg(1) * outgoingStep_deg(2) - ...
            incomingStep_deg(2) * outgoingStep_deg(1);
        directionDotProduct_deg2 = sum( ...
            incomingStep_deg .* outgoingStep_deg);
        collinearityScale_deg2 = max(1, ...
            norm(incomingStep_deg) * norm(outgoingStep_deg));
        continuesSameLine = ...
            abs(signedCrossProduct_deg2) <= ...
            1e-10 * collinearityScale_deg2 && ...
            directionDotProduct_deg2 > 0;
        if continuesSameLine
            continue;
        end
        retainedWaypointCount = retainedWaypointCount + 1;
        retainedRoute_deg(retainedWaypointCount, :) = ...
            routePositionsUnwrapped_deg(waypointIndex, :);
    end
    retainedWaypointCount = retainedWaypointCount + 1;
    retainedRoute_deg(retainedWaypointCount, :) = ...
        routePositionsUnwrapped_deg(end, :);
    routePositionsUnwrapped_deg = ...
        retainedRoute_deg(1:retainedWaypointCount, :);
end

%% Section 3: Derive Jerk-Limited Segment Durations
segmentDisplacement_deg = diff(routePositionsUnwrapped_deg, 1, 1);
segmentCount = size(segmentDisplacement_deg, 1);
segmentDuration_s = zeros(segmentCount, 1);

% For p(u)=10u^3-15u^4+6u^5 on u in [0,1], the exact maxima of
% |p'|, |p''|, and |p'''| are 15/8, 10/sqrt(3), and 60. Scaling one shared
% p(t/T) synchronizes both axes while enforcing every derivative limit.
maximumNormalizedRate = 15 / 8;
maximumNormalizedAcceleration = 10 / sqrt(3);
maximumNormalizedJerk = 60;
for segmentIndex = 1:segmentCount
    absoluteDisplacement_deg = abs( ...
        segmentDisplacement_deg(segmentIndex, :));
    velocityDuration_s = maximumNormalizedRate * ...
        absoluteDisplacement_deg ./ limits.maxVelocity_deg_s;
    accelerationDuration_s = sqrt( ...
        maximumNormalizedAcceleration * absoluteDisplacement_deg ./ ...
        limits.maxAcceleration_deg_s2);
    jerkDuration_s = (maximumNormalizedJerk * ...
        absoluteDisplacement_deg ./ limits.maxJerk_deg_s3).^(1 / 3);
    segmentDuration_s(segmentIndex) = max( ...
        [velocityDuration_s, accelerationDuration_s, jerkDuration_s]);
end

minimumManeuverTime_s = sum(segmentDuration_s);
retiming.MinimumManeuverTime_s = minimumManeuverTime_s;
retiming.RoutePositionsUnwrapped_deg = routePositionsUnwrapped_deg;
retiming.SegmentDisplacement_deg = segmentDisplacement_deg;
retiming.SegmentDuration_s = segmentDuration_s;
retiming.InputWaypointCount = inputWaypointCount;
retiming.RetainedWaypointCount = size(routePositionsUnwrapped_deg, 1);
if minimumManeuverTime_s > availableManeuverTime_s + ...
        options.timeTolerance_s
    retiming.Message = sprintf( ...
        "Jerk-limited topology route needs %.3f s but only %.3f s is available.", ...
        minimumManeuverTime_s, availableManeuverTime_s);
    return;
end

if segmentCount > 0
    segmentInitialTime_s = initialState.time_s + ...
        [0; cumsum(segmentDuration_s(1:end - 1))];
else
    segmentInitialTime_s = zeros(0, 1);
end
retiming.SegmentInitialTime_s = segmentInitialTime_s;

%% Section 4: Sample The Analytic Motion And Exact-Time Hold
segmentSampleCounts = max(1, ceil( ...
    segmentDuration_s / options.collisionCheckStep_s));
arrivalTime_s = initialState.time_s + minimumManeuverTime_s;
remainingHoldTime_s = destinationState.time_s - arrivalTime_s;
holdSampleCount = 0;
if remainingHoldTime_s > options.timeTolerance_s
    holdSampleCount = max(1, ceil( ...
        remainingHoldTime_s / options.collisionCheckStep_s));
end
profileSampleCount = 1 + sum(segmentSampleCounts) + holdSampleCount;
profileTime_s = zeros(profileSampleCount, 1);
profilePositionUnwrapped_deg = zeros(profileSampleCount, 2);
profileVelocity_deg_s = zeros(profileSampleCount, 2);
profileAcceleration_deg_s2 = zeros(profileSampleCount, 2);
profileJerk_deg_s3 = zeros(profileSampleCount, 2);
profileIsWaiting = false(profileSampleCount, 1);
profileTime_s(1) = initialState.time_s;
profilePositionUnwrapped_deg(1, :) = ...
    routePositionsUnwrapped_deg(1, :);
profileSampleIndex = 1;

for segmentIndex = 1:segmentCount
    duration_s = segmentDuration_s(segmentIndex);
    segmentSampleCount = segmentSampleCounts(segmentIndex);
    sampleOffset_s = linspace(0, duration_s, ...
        segmentSampleCount + 1).';
    normalizedTime = sampleOffset_s(2:end) / duration_s;
    normalizedProgress = 10 * normalizedTime.^3 - ...
        15 * normalizedTime.^4 + 6 * normalizedTime.^5;
    normalizedRate = 30 * normalizedTime.^2 - ...
        60 * normalizedTime.^3 + 30 * normalizedTime.^4;
    normalizedAcceleration = 60 * normalizedTime - ...
        180 * normalizedTime.^2 + 120 * normalizedTime.^3;
    normalizedJerk = 60 - 360 * normalizedTime + ...
        360 * normalizedTime.^2;

    displacement_deg = segmentDisplacement_deg(segmentIndex, :);
    sampleTime_s = segmentInitialTime_s(segmentIndex) + ...
        sampleOffset_s(2:end);
    samplePositionUnwrapped_deg = ...
        routePositionsUnwrapped_deg(segmentIndex, :) + ...
        normalizedProgress .* displacement_deg;
    sampleVelocity_deg_s = normalizedRate .* displacement_deg / ...
        duration_s;
    sampleAcceleration_deg_s2 = normalizedAcceleration .* ...
        displacement_deg / duration_s^2;
    sampleJerk_deg_s3 = normalizedJerk .* displacement_deg / ...
        duration_s^3;

    sampleIndices = profileSampleIndex + (1:segmentSampleCount);
    profileTime_s(sampleIndices) = sampleTime_s;
    profilePositionUnwrapped_deg(sampleIndices, :) = ...
        samplePositionUnwrapped_deg;
    profileVelocity_deg_s(sampleIndices, :) = sampleVelocity_deg_s;
    profileAcceleration_deg_s2(sampleIndices, :) = ...
        sampleAcceleration_deg_s2;
    profileJerk_deg_s3(sampleIndices, :) = sampleJerk_deg_s3;
    profileSampleIndex = sampleIndices(end);
end

if holdSampleCount > 0
    holdOffset_s = linspace(0, remainingHoldTime_s, ...
        holdSampleCount + 1).';
    holdTime_s = arrivalTime_s + holdOffset_s(2:end);
    holdIndices = profileSampleIndex + (1:holdSampleCount);
    profileTime_s(holdIndices) = holdTime_s;
    profilePositionUnwrapped_deg(holdIndices, :) = repmat( ...
        routePositionsUnwrapped_deg(end, :), holdSampleCount, 1);
    profileIsWaiting(holdIndices) = true;
end

profilePosition_deg = profilePositionUnwrapped_deg;
if options.allowAzimuthWrap
    azimuthSpan_deg = diff(limits.azimuth_deg);
    profilePosition_deg(:, 1) = mod( ...
        profilePosition_deg(:, 1) - limits.azimuth_deg(1), ...
        azimuthSpan_deg) + limits.azimuth_deg(1);
end

%% Section 5: Validate And Package The Retiming
sampleOccupied = queryAzElTimeObstacle( ...
    obstacleField, profilePosition_deg(:, 1), ...
    profilePosition_deg(:, 2), profileTime_s, ...
    options.collisionQueryOptions);
profile = struct( ...
    "Time_s", profileTime_s, ...
    "Position_deg", profilePosition_deg, ...
    "PositionUnwrapped_deg", profilePositionUnwrapped_deg, ...
    "Velocity_deg_s", profileVelocity_deg_s, ...
    "Acceleration_deg_s2", profileAcceleration_deg_s2, ...
    "Jerk_deg_s3", profileJerk_deg_s3, ...
    "IsWaiting", profileIsWaiting);
retiming.Profile = profile;
retiming.ArrivalTime_s = arrivalTime_s;
retiming.CollisionSampleCount = numel(profileTime_s);
retiming.MaximumVelocity_deg_s = ...
    max(abs(profileVelocity_deg_s), [], 1);
retiming.MaximumAcceleration_deg_s2 = ...
    max(abs(profileAcceleration_deg_s2), [], 1);
retiming.MaximumJerk_deg_s3 = max(abs(profileJerk_deg_s3), [], 1);
retiming.SampledCollisionValidated = ~any(sampleOccupied);
if any(sampleOccupied)
    retiming.Message = ...
        "The jerk-limited topology route intersects the " + ...
        "packed obstacle field at a collision sample.";
    return;
end

retiming.Success = true;
retiming.Message = ...
    "Static topology route was retimed with jerk-limited quintic segments.";
end

function retiming = emptySimpleAzElAnalyticRetiming()
%% Section 0: Header & Readme
% SYNTAX
%   retiming = emptySimpleAzElAnalyticRetiming()
%**************************************************************************
% PURPOSE
%   - Define one stable diagnostic schema for unused, failed, and successful
%     static analytic route retiming.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - retiming (scalar diagnostic struct)
%       Empty analytic-retiming record with PascalCase fields.
%**************************************************************************
% UNITS
%   - Field suffixes state their physical units.
emptyProfile = struct( ...
    "Time_s", zeros(0, 1), ...
    "Position_deg", zeros(0, 2), ...
    "PositionUnwrapped_deg", zeros(0, 2), ...
    "Velocity_deg_s", zeros(0, 2), ...
    "Acceleration_deg_s2", zeros(0, 2), ...
    "Jerk_deg_s3", zeros(0, 2), ...
    "IsWaiting", false(0, 1));
retiming = struct( ...
    "Used", false, ...
    "Success", false, ...
    "Message", "Analytic static route retiming was not requested.", ...
    "Profile", emptyProfile, ...
    "RoutePositionsUnwrapped_deg", zeros(0, 2), ...
    "SegmentDisplacement_deg", zeros(0, 2), ...
    "SegmentDuration_s", zeros(0, 1), ...
    "SegmentInitialTime_s", zeros(0, 1), ...
    "MinimumManeuverTime_s", Inf, ...
    "AvailableManeuverTime_s", NaN, ...
    "ArrivalTime_s", NaN, ...
    "MaximumVelocity_deg_s", [0, 0], ...
    "MaximumAcceleration_deg_s2", [0, 0], ...
    "MaximumJerk_deg_s3", [0, 0], ...
    "InputWaypointCount", 0, ...
    "RetainedWaypointCount", 0, ...
    "CollisionSampleCount", 0, ...
    "SampledCollisionValidated", false, ...
    "ExactCollisionValidated", false);
end
