function result = runAzElGauntletCase( ...
        name, description, azElData, startState, stopState, limits, ...
        options, planner)
%RUNAZELGAUNTLETCASE Plan, validate, and plot one standalone gauntlet case.

if nargin < 8 || isempty(planner)
    planner = @planAzElAvoidance;
end
plan = planner( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("runAzElGauntletCase:NoPath", ...
        "%s failed: %s", name, plan.message);
end
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
if any(blocked)
    error("runAzElGauntletCase:Collision", ...
        "%s returned %d occupied command samples.", name, nnz(blocked));
end

plotHandles = plotAzElAvoidancePlan(azElData, plan);
title(plotHandles.AzElAxes, string(name) + ": " + string(description));
result = struct( ...
    "name", string(name), ...
    "description", string(description), ...
    "azElData", azElData, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "blockedSampleCount", nnz(blocked), ...
    "plotHandles", plotHandles, ...
    "diagnostics", struct());
fprintf("%s: %.3f deg, %.2f s search, %d command samples.\n", ...
    name, plan.angularPathLength_deg, ...
    plan.searchElapsed_s, numel(plan.time_s));
end
