function report = runRandomBlinkingChessboardStressTest( ...
        caseCount, rootSeed)
%RUNRANDOMBLINKINGCHESSBOARDSTRESSTEST Run unfiltered stochastic cases.
%
% No failed case is discarded or replaced. Leave rootSeed empty for a new
% batch; replay a reported root seed to reproduce every generated case.

if nargin < 1 || isempty(caseCount)
    caseCount = 5;
end
validateattributes(caseCount, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
if nargin < 2 || isempty(rootSeed)
    previous = rng;
    rng("shuffle");
    rootSeed = randi([1, intmax("int32")]);
    rng(previous);
end
validateattributes(rootSeed, {'numeric'}, ...
    {'scalar', 'integer', 'positive', '<=', intmax("int32")});
stream = RandStream("mt19937ar", "Seed", double(rootSeed));
caseSeeds = randi(stream, intmax("int32"), caseCount, 1);

template = struct( ...
    "seed", 0, ...
    "success", false, ...
    "interceptTime_s", NaN, ...
    "catchError_deg", Inf, ...
    "blockedSampleCount", Inf, ...
    "blockedTargetSampleCount", 0, ...
    "cellTransferCount", 0, ...
    "attemptCount", 0, ...
    "searchElapsed_s", 0, ...
    "message", "");
cases = repmat(template, caseCount, 1);
for caseIndex = 1:caseCount
    seed = double(caseSeeds(caseIndex));
    timer = tic;
    try
        problem = makeRandomBlinkingChessboardGauntlet(seed);
        plan = planAzElMovingTargetIntercept( ...
            problem.azElData, problem.startState, problem.target, ...
            problem.limits, problem.options);
        if plan.success
            diagnostics = analyzeBlinkingChessboardIntercept( ...
                problem, plan);
            success = ...
                diagnostics.blockedBoresightSampleCount == 0 && ...
                diagnostics.catchError_deg <= ...
                problem.options.CatchTolerance_deg && ...
                diagnostics.cellTransferCount >= 2 && ...
                diagnostics.blockedTargetSampleCount > 0;
            cases(caseIndex) = struct( ...
                "seed", seed, ...
                "success", success, ...
                "interceptTime_s", ...
                    diagnostics.interceptTime_s, ...
                "catchError_deg", diagnostics.catchError_deg, ...
                "blockedSampleCount", ...
                    diagnostics.blockedBoresightSampleCount, ...
                "blockedTargetSampleCount", ...
                    diagnostics.blockedTargetSampleCount, ...
                "cellTransferCount", ...
                    diagnostics.cellTransferCount, ...
                "attemptCount", diagnostics.attemptCount, ...
                "searchElapsed_s", toc(timer), ...
                "message", string(plan.message));
        else
            cases(caseIndex).seed = seed;
            cases(caseIndex).attemptCount = ...
                numel(plan.interceptAttempts);
            cases(caseIndex).searchElapsed_s = toc(timer);
            cases(caseIndex).message = string(plan.message);
        end
    catch exception
        cases(caseIndex).seed = seed;
        cases(caseIndex).searchElapsed_s = toc(timer);
        cases(caseIndex).message = string(exception.message);
    end
    fprintf("  Case %d/%d seed %u: %s (%.2f s)\n", ...
        caseIndex, caseCount, uint32(seed), ...
        passFail(cases(caseIndex).success), ...
        cases(caseIndex).searchElapsed_s);
end
successMask = [cases.success].';
report = struct( ...
    "rootSeed", double(rootSeed), ...
    "caseSeeds", double(caseSeeds), ...
    "cases", cases, ...
    "successCount", nnz(successMask), ...
    "failureCount", nnz(~successMask), ...
    "successRate", mean(successMask));
fprintf("Random batch root seed %u: %d/%d passed (%.1f%%).\n", ...
    uint32(rootSeed), report.successCount, caseCount, ...
    100 * report.successRate);
end

function value = passFail(success)
if success
    value = "PASS";
else
    value = "FAIL";
end
end
