function tests = testAzElSpaceTimeFunnel
tests = functiontests(localfunctions);
end

function setupOnce(~)
addpath(fileparts(mfilename("fullpath")));
end

function testDirectWaitAndSlewIsGloballyShortest(testCase)
time_s = (0:20).';
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    center = 8 * (time_s(k) > 7);
    azimuth{k} = center + [-1; 1; 1; -1; -1];
    elevation{k} = [-2; -2; 2; 2; -2];
end
data = makeAzElObstacleData( ...
    "Opening gate", time_s, azimuth, elevation);
[startState, stopState, limits] = standardProblem(20);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "SafetyMargin_deg", 0.1);

plan = planAzElSpaceTimeFunnel( ...
    data, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, "directSafeIntervalCertificate");
verifyTrue(testCase, plan.optimalGlobally);
verifyEqual(testCase, plan.angularPathLength_deg, 8, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.suboptimalityBound, 1, ...
    "AbsTol", 1e-12);
verifyTrue(testCase, any(plan.isWaiting));
verifyPlan(testCase, plan, options);
end

function testMovingVolumeForcesSafeIntervalDetour(testCase)
time_s = (0:20).';
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    center = 0.35 * sin(time_s(k) / 3);
    azimuth{k} = [-1; 1; 1; -1; -1];
    elevation{k} = center + [-2; -2; 2; 2; -2];
end
data = makeAzElObstacleData( ...
    "Moving wall", time_s, azimuth, elevation);
[startState, stopState, limits] = standardProblem(20);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "GuideGridStep_deg", 1, ...
    "SafetyMargin_deg", 0.1, ...
    "EnableARARefinement", false, ...
    "FallbackToGlobalSearch", false, ...
    "MaxSearchTime_s", 8);

plan = planAzElSpaceTimeFunnel( ...
    data, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, ...
    "eventCompressedSafeIntervalFunnel");
verifyGreaterThan(testCase, plan.angularPathLength_deg, 8);
verifyGreaterThan(testCase, ...
    plan.safeIntervalGuide.ExpandedNodeCount, 0);
verifyPlan(testCase, plan, options);
end

function testMultipleMovingVolumesAreCombined(testCase)
time_s = (0:24).';
firstAzimuth = cell(numel(time_s), 1);
firstElevation = cell(numel(time_s), 1);
secondAzimuth = cell(numel(time_s), 1);
secondElevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    firstAzimuth{k} = [-2; 0; 0; -2; -2];
    firstElevation{k} = ...
        0.25 * sin(time_s(k) / 4) + [-2; -2; 2; 2; -2];
    secondAzimuth{k} = [1; 3; 3; 1; 1];
    secondElevation{k} = ...
        -2.8 + 0.2 * cos(time_s(k) / 5) + ...
        [-1; -1; 1; 1; -1];
end
data = { ...
    makeAzElObstacleData( ...
    "Center wall", time_s, firstAzimuth, firstElevation), ...
    makeAzElObstacleData( ...
    "Lower moving wall", time_s, secondAzimuth, secondElevation)};
[startState, stopState, limits] = standardProblem(24);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "GuideGridStep_deg", 1, ...
    "SafetyMargin_deg", 0.1, ...
    "EnableARARefinement", false, ...
    "FallbackToGlobalSearch", false, ...
    "MaxSearchTime_s", 10);

plan = planAzElSpaceTimeFunnel( ...
    data, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.workspace.ObstacleCount, 2);
verifyPlan(testCase, plan, options);
end

function testWrappedAzimuthUsesShortSpaceTimeChord(testCase)
time_s = (0:20).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
startState = boundaryState(0, [170 0]);
stopState = boundaryState(20, [-170 0]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", true);

plan = planAzElSpaceTimeFunnel( ...
    data, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.optimalGlobally);
verifyEqual(testCase, plan.angularPathLength_deg, 20, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.position_deg(end, 1), -170, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.positionUnwrapped_deg(end, 1), 190, ...
    "AbsTol", 1e-9);
verifyPlan(testCase, plan, options);
end

function testFourRotatingSlotsRequireTimedChamberWaits(testCase)
problem = makeRotatingSlotGauntlet();

plan = planAzElSpaceTimeFunnel( ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
diagnostics = analyzeRotatingSlotGauntlet(problem, plan);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.workspace.ObstacleCount, 4);
verifyEqual(testCase, diagnostics.blockedSampleCount, 0);
verifyTrue(testCase, all(isfinite(diagnostics.crossingTime_s)));
verifyGreaterThan(testCase, ...
    diff(diagnostics.crossingTime_s), zeros(1, 3));
verifyLessThanOrEqual(testCase, ...
    diagnostics.slotCenterError_deg, ...
    problem.geometry.slotWidth_deg / 2 + 8);
verifyGreaterThanOrEqual(testCase, ...
    nnz(diagnostics.chamberWait_s >= 10), 2);
verifyGreaterThan(testCase, diagnostics.totalWaiting_s, 50);
verifyLessThanOrEqual(testCase, ...
    diff(diagnostics.radius_deg), 1e-9 * ...
    ones(numel(diagnostics.radius_deg) - 1, 1));
verifyPlan(testCase, plan, problem.options);
end

function verifyPlan(testCase, plan, options)
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
verifyFalse(testCase, any(blocked));
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.velocity_deg_s), [], 1), ...
    plan.limits.maxVelocity_deg_s + 1e-8);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.acceleration_deg_s2), [], 1), ...
    plan.limits.maxAcceleration_deg_s2 + 1e-8);
verifyEqual(testCase, plan.position_deg(1, :), ...
    plan.startState.position_deg, "AbsTol", 1e-9);
verifyEqual(testCase, plan.position_deg(end, :), ...
    plan.stopState.position_deg, "AbsTol", 1e-9);
end

function [startState, stopState, limits] = standardProblem(stopTime)
startState = boundaryState(0, [-4 0]);
stopState = boundaryState(stopTime, [4 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-5 5], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
