function tests = testAzElAutonomousCorridor
tests = functiontests(localfunctions);
end

function setupOnce(~)
folder = fileparts(mfilename("fullpath"));
addpath(folder);
end

function teardown(~)
close all force;
end

function testFiveTurnSpiralNeedsNoGuide(testCase)
set(0, "DefaultFigureVisible", "off");
result = exampleGauntlet01FiveTurnSpiral();

verifyTrue(testCase, result.plan.success);
verifyTrue(testCase, startsWith(result.plan.method, "autonomous"));
verifyFalse(testCase, isfield(result.plan.options, "GuidePath_deg"));
verifyEqual(testCase, result.blockedSampleCount, 0);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.windingTurns, 4);
verifyLessThan(testCase, result.plan.angularPathLength_deg, 250);
verifyLessThan(testCase, ...
    result.diagnostics.motionCompletionTime_s, 200);
verifyLessThan(testCase, ...
    result.plan.topologySearch.SearchElapsed_s, 30);
end

function testAzimuthWrapUsesShortSeamRoute(testCase)
time_s = (0:1:30).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = obstacleData("Empty", time_s, empty, empty);
startState = boundaryState(0, [170 0]);
stopState = boundaryState(30, [-170 0]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "TopologyGridStep_deg", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance", ...
    "FallbackToExistingPlanner", false);

plan = planAzElAutonomousCorridor( ...
    azElData, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyTrue(testCase, startsWith(plan.method, "autonomous"));
verifyEqual(testCase, plan.position_deg(end, 1), -170, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.positionUnwrapped_deg(end, 1), 190, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.angularPathLength_deg, 20, ...
    "AbsTol", 1e-9);
end

function testTimeDependentGeometryFallsBack(testCase)
time_s = (0:1:10).';
azimuth = repmat({zeros(0, 1)}, numel(time_s), 1);
elevation = repmat({zeros(0, 1)}, numel(time_s), 1);
azimuth{6} = [-1; 1; 1; -1; -1];
elevation{6} = [7; 7; 9; 9; 7];
azElData = obstacleData( ...
    "Changing obstacle", time_s, azimuth, elevation);
startState = boundaryState(0, [-2 0]);
stopState = boundaryState(10, [2 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "FallbackToExistingPlanner", true);

plan = planAzElAutonomousCorridor( ...
    azElData, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, "existingPlannerFallback");
verifyTrue(testCase, contains( ...
    plan.fallbackReason, "time-dependent"));
end

function testOptionalNarrowTubeRefinement(testCase)
time_s = (0:1:20).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = obstacleData("Empty", time_s, empty, empty);
startState = boundaryState(0, [-4 0]);
stopState = boundaryState(20, [4 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-5 5], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "TopologyGridStep_deg", 2, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "EnableTopologyRefinement", true, ...
    "RefinementGridStep_deg", 0.5, ...
    "RefinementCorridorHalfWidth_deg", 1, ...
    "FallbackToExistingPlanner", false);

plan = planAzElAutonomousCorridor( ...
    azElData, startState, stopState, limits, options);

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.topologyRefinement.Success);
verifyLessThan(testCase, ...
    plan.topologyRefinement.CandidateCellCount, ...
    plan.topologyRefinement.TotalCellCount);
verifyEqual(testCase, plan.angularPathLength_deg, 8, ...
    "AbsTol", 1e-9);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function data = obstacleData(name, time_s, azimuth, elevation)
data = struct( ...
    "targetName", string(name), ...
    "time_s", double(time_s(:)), ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", repmat("visible", numel(time_s), 1));
end
