function agentArtifact = trainAzElPlannerAgent(outputFile, options)
%TRAINAZELPLANNERAGENT Train and save an auditable planner-selection agent.
%
% agentArtifact = trainAzElPlannerAgent()
% agentArtifact = trainAzElPlannerAgent(outputFile, options)
%
% The learned model ranks three Dijkstra search profiles. Training labels
% come from exact-validated planner runs on a deterministic narrow-passage
% curriculum; they are not manually assigned. The model never creates a
% route or approves a collision.
%
% Options:
%   CurriculumScenariosPerClass  Cases generated at each intended
%                                difficulty (default 6).
%   RandomSeed                   Reproducible geometry/model seed (17).
%   Verbose                      Print benchmark progress (default true).

packageRoot = fileparts(mfilename("fullpath"));
if nargin < 1 || isempty(outputFile)
    outputFile = fullfile(packageRoot, ...
        "models", "azElPlannerAgent.mat");
end
if nargin < 2
    options = struct();
end
defaultOptions = struct( ...
    "CurriculumScenariosPerClass", 6, ...
    "RandomSeed", 17, ...
    "Verbose", true);
optionNames = fieldnames(defaultOptions);
for optionIndex = 1:numel(optionNames)
    optionName = optionNames{optionIndex};
    if ~isfield(options, optionName) || isempty(options.(optionName))
        options.(optionName) = defaultOptions.(optionName);
    end
end
validateattributes(options.CurriculumScenariosPerClass, {'numeric'}, ...
    {'scalar', 'integer', '>=', 2});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.Verbose, {'logical', 'numeric'}, {'scalar'});
options.Verbose = logical(options.Verbose);
rng(options.RandomSeed, "twister");

%% Define the deployable actions
% Profiles live in the artifact so training and deployment cannot drift.
% The profile order is also the fallback order from cheap to expressive.
agentProfiles(1) = struct( ...
    "Name", "fast", ...
    "Description", "Two-degree lattice for open workspaces.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 2, ...
        "GridStepSchedule_deg", 2, ...
        "PrimitiveRadiusMultipliers", [1 2 4], ...
        "DirectionStep_deg", 90, ...
        "MaximumDepartureTrials", 24, ...
        "DepartureBatchSize", 6, ...
        "MaxExpansions", 30000, ...
        "MaxSearchTime_s", 3, ...
        "PrintFailureSuggestions", false));
agentProfiles(2) = struct( ...
    "Name", "balanced", ...
    "Description", "One-degree lattice for ordinary clutter.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 1, ...
        "GridStepSchedule_deg", 1, ...
        "PrimitiveRadiusMultipliers", [1 2 4 8], ...
        "DirectionStep_deg", 45, ...
        "MaximumDepartureTrials", 48, ...
        "DepartureBatchSize", 8, ...
        "MaxExpansions", 70000, ...
        "MaxSearchTime_s", 5, ...
        "PrintFailureSuggestions", false));
agentProfiles(3) = struct( ...
    "Name", "precise", ...
    "Description", "Half-degree lattice for narrow passages.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "GridStep_deg", 0.5, ...
        "GridStepSchedule_deg", 0.5, ...
        "PrimitiveRadiusMultipliers", [1 2 4 8], ...
        "DirectionStep_deg", 45, ...
        "MaximumDepartureTrials", 64, ...
        "DepartureBatchSize", 8, ...
        "MaxExpansions", 140000, ...
        "MaxSearchTime_s", 8, ...
        "PrintFailureSuggestions", false));

%% Build a deterministic curriculum and benchmark every needed action
scenarioCountPerClass = options.CurriculumScenariosPerClass;
scenarioCount = 3 * scenarioCountPerClass;
trainingFeatures = zeros(scenarioCount, 10);
selectedProfileNames = strings(scenarioCount, 1);
intendedProfileNames = strings(scenarioCount, 1);
plannerSucceeded = false(scenarioCount, numel(agentProfiles));
plannerElapsed_s = nan(scenarioCount, numel(agentProfiles));
plannerPathLength_deg = nan(scenarioCount, numel(agentProfiles));
axisLimits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [5 5]);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
sampleTime_s = (0:1:20).';

for scenarioIndex = 1:scenarioCount
    difficultyIndex = ceil(scenarioIndex / scenarioCountPerClass);
    withinClassIndex = mod(scenarioIndex - 1, scenarioCountPerClass) + 1;
    wallCenter_deg = -0.5 + mod(withinClassIndex - 1, 3) * 0.5;
    wallHalfWidth_deg = 2.8 + 0.1 * mod(withinClassIndex, 2);
    if difficultyIndex == 1
        intendedProfileNames(scenarioIndex) = "fast";
        passageCenter_deg = 2 * mod(withinClassIndex, 3) - 2;
        passageWidth_deg = 4.4 + 0.2 * mod(withinClassIndex, 2);
    elseif difficultyIndex == 2
        intendedProfileNames(scenarioIndex) = "balanced";
        passageCenter_deg = -3 + ...
            0.05 * (mod(withinClassIndex - 1, 3) - 1);
        passageWidth_deg = 1.35 + 0.05 * mod(withinClassIndex, 2);
    else
        intendedProfileNames(scenarioIndex) = "precise";
        passageCenter_deg = 1.5 + ...
            0.02 * (mod(withinClassIndex - 1, 3) - 1);
        passageWidth_deg = 0.72 + 0.04 * mod(withinClassIndex, 2);
    end
    passageBottom_deg = passageCenter_deg - passageWidth_deg / 2;
    passageTop_deg = passageCenter_deg + passageWidth_deg / 2;
    wallLeft_deg = wallCenter_deg - wallHalfWidth_deg;
    wallRight_deg = wallCenter_deg + wallHalfWidth_deg;

    obstacleAzimuth_deg = [ ...
        wallLeft_deg; wallRight_deg; wallRight_deg; ...
        wallLeft_deg; wallLeft_deg; NaN; ...
        wallLeft_deg; wallRight_deg; wallRight_deg; ...
        wallLeft_deg; wallLeft_deg];
    obstacleElevation_deg = [ ...
        axisLimits.elevation_deg(1); axisLimits.elevation_deg(1); ...
        passageBottom_deg; passageBottom_deg; ...
        axisLimits.elevation_deg(1); NaN; ...
        passageTop_deg; passageTop_deg; ...
        axisLimits.elevation_deg(2); axisLimits.elevation_deg(2); ...
        passageTop_deg];
    azimuthByTime = repmat({obstacleAzimuth_deg}, ...
        numel(sampleTime_s), 1);
    elevationByTime = repmat({obstacleElevation_deg}, ...
        numel(sampleTime_s), 1);
    scenarioData = makeAzElObstacleData( ...
        "Training wall " + scenarioIndex, sampleTime_s, ...
        azimuthByTime, elevationByTime);
    [scenarioFeatures, featureNames] = extractAzElPlannerFeatures( ...
        scenarioData, initialState, goalState, axisLimits);
    trainingFeatures(scenarioIndex, :) = scenarioFeatures;

    % The first successful profile is the cheapest graph that actually
    % expresses and exactly validates a route for this curriculum case.
    for profileIndex = 1:numel(agentProfiles)
        profileTimer = tic;
        candidatePlan = planAzElDijkstra( ...
            scenarioData, initialState, goalState, axisLimits, ...
            agentProfiles(profileIndex).PlannerOptions);
        plannerElapsed_s(scenarioIndex, profileIndex) = toc(profileTimer);
        plannerSucceeded(scenarioIndex, profileIndex) = candidatePlan.success && ...
            candidatePlan.exactCollisionValidated;
        if candidatePlan.success
            plannerPathLength_deg(scenarioIndex, profileIndex) = candidatePlan.angularPathLength_deg;
        end
        if plannerSucceeded(scenarioIndex, profileIndex)
            selectedProfileNames(scenarioIndex) = agentProfiles( ...
                profileIndex).Name;
            break;
        end
    end
    if selectedProfileNames(scenarioIndex) == ""
        error("trainAzElPlannerAgent:CurriculumFailure", ...
            "No profile solved curriculum scenario %d.", scenarioIndex);
    end
    if options.Verbose
        fprintf("Agent curriculum %2d/%2d: %s\n", ...
            scenarioIndex, scenarioCount, ...
            selectedProfileNames(scenarioIndex));
    end
end

observedClasses = unique(selectedProfileNames);
if numel(observedClasses) ~= numel(agentProfiles)
    error("trainAzElPlannerAgent:InsufficientClasses", ...
        "Curriculum produced %d profile classes; expected %d.", ...
        numel(observedClasses), numel(agentProfiles));
end
curriculumDrift = selectedProfileNames ~= intendedProfileNames;
if any(curriculumDrift)
    driftScenarios = find(curriculumDrift);
    error("trainAzElPlannerAgent:CurriculumProfileDrift", ...
        "Planner behavior changed the intended class of scenario(s): %s.", ...
        join(string(driftScenarios), ", "));
end

%% Fit the compact ranking model and package its evidence
% A shallow decision tree is intentional: the starter curriculum is small,
% its thresholds remain inspectable, and deployment needs no iterative
% neural inference. Exact planning fallback contains any misclassification.
classifier = fitctree( ...
    trainingFeatures, categorical(selectedProfileNames), ...
    "MinLeafSize", 1, ...
    "MinParentSize", 2);
trainingPrediction = string(predict(classifier, trainingFeatures));
trainingAccuracy = mean(trainingPrediction == selectedProfileNames);

agentArtifact = struct( ...
    "Format", "AzElPlannerSelectionAgent", ...
    "Version", 1, ...
    "CreatedUtc", string(datetime("now", "TimeZone", "UTC")), ...
    "RandomSeed", options.RandomSeed, ...
    "ModelType", "classificationTree", ...
    "FeatureNames", featureNames, ...
    "Profiles", agentProfiles, ...
    "Model", classifier, ...
    "ExactValidationRequired", true, ...
    "TrainingReport", struct( ...
        "ScenarioCount", scenarioCount, ...
        "SelectedProfileNames", selectedProfileNames, ...
        "IntendedProfileNames", intendedProfileNames, ...
        "PlannerSucceeded", plannerSucceeded, ...
        "PlannerElapsed_s", plannerElapsed_s, ...
        "PlannerPathLength_deg", plannerPathLength_deg, ...
        "TrainingFeatures", trainingFeatures, ...
        "TrainingAccuracy", trainingAccuracy));

outputFile = char(outputFile);
outputFolder = fileparts(outputFile);
if ~isempty(outputFolder) && ~isfolder(outputFolder)
    mkdir(outputFolder);
end
save(outputFile, "agentArtifact", "-v7.3");
if options.Verbose
    fprintf("Saved az/el planner agent to %s (training accuracy %.1f%%).\n", ...
        outputFile, 100 * trainingAccuracy);
end
end
