function agentArtifact = trainAzElPlannerAgent(outputFile, options)
%TRAINAZELPLANNERAGENT Train and save an auditable planner-selection agent.
%
% agentArtifact = trainAzElPlannerAgent()
% agentArtifact = trainAzElPlannerAgent(outputFile, options)
%
% A compact tree ranks three static Dijkstra profiles. Auditable mode rules
% select among six dynamic profiles because a static-wall curriculum
% cannot honestly estimate moving-topology confidence. Training labels
% require exact validity and near-best route quality; the model never
% creates a route or approves a collision.
%
% Options:
%   CurriculumScenariosPerClass  Cases generated at each intended
%                                difficulty (default 12).
%   ValidationScenariosPerClass  Unseen cases per difficulty. Empty uses
%                                min(6, CurriculumScenariosPerClass).
%   RandomSeed                   Reproducible geometry/model seed (17).
%   Verbose                      Print benchmark progress (default true).

packageRoot = fileparts(mfilename("fullpath"));
if nargin < 1 || isempty(outputFile)
    outputFile = fullfile(packageRoot, ...
        "models", "azElPlannerAgent.mat");
end
if nargin < 2
    options = struct();
end
defaultOptions = struct( ...
    "CurriculumScenariosPerClass", 12, ...
    "ValidationScenariosPerClass", [], ...
    "RandomSeed", 17, ...
    "Verbose", true);
optionNames = fieldnames(defaultOptions);
for optionIndex = 1:numel(optionNames)
    optionName = optionNames{optionIndex};
    if ~isfield(options, optionName) || isempty(options.(optionName))
        options.(optionName) = defaultOptions.(optionName);
    end
end
validateattributes(options.CurriculumScenariosPerClass, {'numeric'}, ...
    {'scalar', 'integer', '>=', 2});
if isempty(options.ValidationScenariosPerClass)
    options.ValidationScenariosPerClass = min( ...
        6, options.CurriculumScenariosPerClass);
end
validateattributes(options.ValidationScenariosPerClass, {'numeric'}, ...
    {'scalar', 'integer', '>=', 2});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(options.Verbose, {'logical', 'numeric'}, {'scalar'});
options.Verbose = logical(options.Verbose);
trainingStream = RandStream( ...
    "mt19937ar", "Seed", double(options.RandomSeed));
validationSeed = mod(double(options.RandomSeed) + 104729, ...
    double(intmax("int32")));
validationStream = RandStream( ...
    "mt19937ar", "Seed", validationSeed);

%% Define the deployable actions
% Profiles live in the artifact so training and deployment cannot drift.
% Static actions are learned; dynamic actions encode distinct observable
% search demands and are selected by the deployment mode policy.
agentProfiles(1) = struct( ...
    "Name", "fast", ...
    "Mode", "static", ...
    "Description", "Two-degree lattice for open workspaces.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 2, ...
        "GridStepSchedule_deg", 2, ...
        "PrimitiveRadiusMultipliers", [1 2 4], ...
        "DirectionStep_deg", 90, ...
        "MaximumDepartureTrials", 24, ...
        "DepartureBatchSize", 6, ...
        "MaxExpansions", 100000, ...
        "MaxSearchTime_s", 10, ...
        "PrintFailureSuggestions", false));
agentProfiles(2) = struct( ...
    "Name", "balanced", ...
    "Mode", "static", ...
    "Description", "One-degree lattice for ordinary clutter.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.25, ...
        "GridStep_deg", 1, ...
        "GridStepSchedule_deg", [2 1], ...
        "PrimitiveRadiusMultipliers", [1 2 4 8], ...
        "DirectionStep_deg", 45, ...
        "MaximumDepartureTrials", 48, ...
        "DepartureBatchSize", 8, ...
        "MaxExpansions", 300000, ...
        "MaxSearchTime_s", 20, ...
        "PrintFailureSuggestions", false));
agentProfiles(3) = struct( ...
    "Name", "precise", ...
    "Mode", "static", ...
    "Description", "Half-degree lattice for narrow passages and dense boundaries.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "GridStep_deg", 0.5, ...
        "GridStepSchedule_deg", 0.5, ...
        "PrimitiveRadiusMultipliers", [1 2 4 8], ...
        "DirectionStep_deg", 45, ...
        "MaximumDepartureTrials", 64, ...
        "DepartureBatchSize", 8, ...
        "MaxExpansions", 1000000, ...
        "MaxSearchTime_s", 30, ...
        "PrintFailureSuggestions", false));
agentProfiles(4) = struct( ...
    "Name", "topologyFine", ...
    "Mode", "static", ...
    "Description", "Progressive quarter-degree graph for traps and slaloms.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "GridStep_deg", 0.25, ...
        "GridStepSchedule_deg", [1 0.5 0.25], ...
        "PrimitiveRadiusMultipliers", [1 2 4 8], ...
        "DirectionStep_deg", 45, ...
        "MaximumDepartureTrials", 64, ...
        "DepartureBatchSize", 8, ...
        "MaxExpansions", 1000000, ...
        "MaxSearchTime_s", 45, ...
        "PrintFailureSuggestions", false));
agentProfiles(5) = struct( ...
    "Name", "dynamicSparseSweep", ...
    "Mode", "dynamic", ...
    "Description", "Coarse-to-fine graph for sparse rotating boundaries.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.1, ...
        "GridStep_deg", 1, ...
        "GridStepSchedule_deg", [2 1], ...
        "PrimitiveRadii_deg", [1 2 4], ...
        "DirectionStep_deg", 45, ...
        "CollisionCheckStep_s", 0.2, ...
        "MaximumSafeIntervalSamples", 121, ...
        "MaximumDepartureTrials", 12, ...
        "DepartureBatchSize", 4, ...
        "MaxExpansions", 300000, ...
        "MaxSearchTime_s", 60, ...
        "PrintFailureSuggestions", false));
agentProfiles(6) = struct( ...
    "Name", "dynamicLocalMotion", ...
    "Mode", "dynamic", ...
    "Description", "Fine local primitives for simple moving gates and rods.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.1, ...
        "GridStep_deg", 0.5, ...
        "GridStepSchedule_deg", [1 0.5], ...
        "PrimitiveRadii_deg", [1 2 4], ...
        "DirectionStep_deg", 45, ...
        "CollisionCheckStep_s", 0.2, ...
        "MaximumSafeIntervalSamples", 101, ...
        "MaximumDepartureTrials", 12, ...
        "DepartureBatchSize", 4, ...
        "MaxExpansions", 250000, ...
        "MaxSearchTime_s", 45, ...
        "PrintFailureSuggestions", false));
agentProfiles(7) = struct( ...
    "Name", "dynamicTiming", ...
    "Mode", "dynamic", ...
    "Description", "Fine event sampling for sparse gates and rotating slots.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.1, ...
        "GridStep_deg", 0.5, ...
        "GridStepSchedule_deg", 0.5, ...
        "PrimitiveRadii_deg", [2 4], ...
        "DirectionStep_deg", 90, ...
        "CollisionCheckStep_s", 0.2, ...
        "MaximumSafeIntervalSamples", 51, ...
        "MaximumDepartureTrials", 8, ...
        "DepartureBatchSize", 8, ...
        "MaxExpansions", 180000, ...
        "MaxSearchTime_s", 30, ...
        "PrintFailureSuggestions", false));
agentProfiles(8) = struct( ...
    "Name", "dynamicPursuit", ...
    "Mode", "dynamic", ...
    "Description", "Long spatial primitives for heavily occupied moving scenes.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.2, ...
        "GridStep_deg", 1, ...
        "GridStepSchedule_deg", 1, ...
        "PrimitiveRadii_deg", [2 4 8 12], ...
        "CollisionCheckStep_s", 0.2, ...
        "MaximumSafeIntervalSamples", 81, ...
        "MaximumDepartureTrials", 4, ...
        "DepartureBatchSize", 2, ...
        "MaxExpansions", 220000, ...
        "MaxSearchTime_s", 55, ...
        "PrintFailureSuggestions", false));
agentProfiles(9) = struct( ...
    "Name", "dynamicDense", ...
    "Mode", "dynamic", ...
    "Description", "Compact primitives for many rapidly changing obstacles.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.2, ...
        "ValidationStep_s", 0.2, ...
        "GridStep_deg", 1, ...
        "GridStepSchedule_deg", 1, ...
        "PrimitiveRadii_deg", [2 4 8], ...
        "CollisionCheckStep_s", 0.4, ...
        "MaximumSafeIntervalSamples", 51, ...
        "MaximumDepartureTrials", 4, ...
        "DepartureBatchSize", 2, ...
        "MaxExpansions", 250000, ...
        "MaxSearchTime_s", 60, ...
        "PrintFailureSuggestions", false));
agentProfiles(10) = struct( ...
    "Name", "dynamicLongHorizon", ...
    "Mode", "dynamic", ...
    "Description", "High event budget for long moving-boundary missions.", ...
    "PlannerOptions", struct( ...
        "SampleTime_s", 0.25, ...
        "ValidationStep_s", 0.08, ...
        "GridStep_deg", 2, ...
        "GridStepSchedule_deg", 2, ...
        "PrimitiveRadii_deg", 2, ...
        "CollisionCheckStep_s", 0.08, ...
        "MaximumSafeIntervalSamples", 150, ...
        "MaximumDepartureTrials", 8, ...
        "DepartureBatchSize", 4, ...
        "MaxExpansions", 300000, ...
        "MaxSearchTime_s", 150, ...
        "PrintFailureSuggestions", false));

%% Build randomized training and held-out curricula
trainingCountPerClass = options.CurriculumScenariosPerClass;
validationCountPerClass = options.ValidationScenariosPerClass;
scenarioCountPerClass = trainingCountPerClass + ...
    validationCountPerClass;
scenarioCount = 3 * scenarioCountPerClass;
allScenarioFeatures = zeros(scenarioCount, 0);
selectedProfileNames = strings(scenarioCount, 1);
intendedProfileNames = strings(scenarioCount, 1);
isTrainingScenario = false(scenarioCount, 1);
staticProfileCount = 3;
plannerSucceeded = false(scenarioCount, staticProfileCount);
plannerElapsed_s = nan(scenarioCount, staticProfileCount);
plannerPathLength_deg = nan(scenarioCount, staticProfileCount);
axisLimits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [5 5]);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
sampleTime_s = (0:1:20).';

for scenarioIndex = 1:scenarioCount
    difficultyIndex = ceil(scenarioIndex / scenarioCountPerClass);
    withinClassIndex = mod(scenarioIndex - 1, scenarioCountPerClass) + 1;
    isTrainingScenario(scenarioIndex) = withinClassIndex <= trainingCountPerClass;
    if isTrainingScenario(scenarioIndex)
        scenarioStream = trainingStream;
    else
        scenarioStream = validationStream;
    end
    wallCenter_deg = -0.4 + 0.8 * rand(scenarioStream);
    wallHalfWidth_deg = 2.7 + 0.4 * rand(scenarioStream);
    if difficultyIndex == 1
        intendedProfileNames(scenarioIndex) = "fast";
        passageCenter_deg = -2.5 + 5 * rand(scenarioStream);
        passageWidth_deg = 4.2 + 0.8 * rand(scenarioStream);
    elseif difficultyIndex == 2
        intendedProfileNames(scenarioIndex) = "balanced";
        passageCenter_deg = -3.05 + 0.1 * rand(scenarioStream);
        passageWidth_deg = 1.3 + 0.15 * rand(scenarioStream);
    else
        intendedProfileNames(scenarioIndex) = "precise";
        % Keep the narrow-passage curriculum centered. A translated wall
        % can turn this feature-label exercise into a long graph-size
        % benchmark, which belongs in the held scenario suite instead.
        wallCenter_deg = 0;
        passageCenter_deg = 1.46 + 0.08 * rand(scenarioStream);
        passageWidth_deg = 0.72 + 0.08 * rand(scenarioStream);
    end
    passageBottom_deg = passageCenter_deg - passageWidth_deg / 2;
    passageTop_deg = passageCenter_deg + passageWidth_deg / 2;
    wallLeft_deg = wallCenter_deg - wallHalfWidth_deg;
    wallRight_deg = wallCenter_deg + wallHalfWidth_deg;

    obstacleAzimuth_deg = [ ...
        wallLeft_deg; wallRight_deg; wallRight_deg; ...
        wallLeft_deg; wallLeft_deg; NaN; ...
        wallLeft_deg; wallRight_deg; wallRight_deg; ...
        wallLeft_deg; wallLeft_deg];
    obstacleElevation_deg = [ ...
        axisLimits.elevation_deg(1); axisLimits.elevation_deg(1); ...
        passageBottom_deg; passageBottom_deg; ...
        axisLimits.elevation_deg(1); NaN; ...
        passageTop_deg; passageTop_deg; ...
        axisLimits.elevation_deg(2); axisLimits.elevation_deg(2); ...
        passageTop_deg];
    azimuthByTime = repmat({obstacleAzimuth_deg}, ...
        numel(sampleTime_s), 1);
    elevationByTime = repmat({obstacleElevation_deg}, ...
        numel(sampleTime_s), 1);
    scenarioData = makeAzElObstacleData( ...
        "Training wall " + scenarioIndex, sampleTime_s, ...
        azimuthByTime, elevationByTime);
    [currentFeatures, featureNames] = extractAzElPlannerFeatures( ...
        scenarioData, initialState, goalState, axisLimits);
    if isempty(allScenarioFeatures)
        allScenarioFeatures = zeros( ...
            scenarioCount, numel(currentFeatures));
    end
    allScenarioFeatures(scenarioIndex, :) = currentFeatures;

    % Success alone is not a useful label: a coarse graph may validate a
    % large detour. Every static profile runs, then the cheapest resolution
    % within five percent of the best exact-valid path becomes the label.
    for profileIndex = 1:staticProfileCount
        profileTimer = tic;
        candidatePlan = planAzElDijkstra( ...
            scenarioData, initialState, goalState, axisLimits, ...
            agentProfiles(profileIndex).PlannerOptions);
        plannerElapsed_s(scenarioIndex, profileIndex) = toc(profileTimer);
        plannerSucceeded(scenarioIndex, profileIndex) = candidatePlan.success && ...
            candidatePlan.exactCollisionValidated;
        if candidatePlan.success
            plannerPathLength_deg(scenarioIndex, profileIndex) = candidatePlan.angularPathLength_deg;
        end
    end
    successfulPathLengths_deg = plannerPathLength_deg( ...
        scenarioIndex, plannerSucceeded(scenarioIndex, :));
    if isempty(successfulPathLengths_deg)
        error("trainAzElPlannerAgent:CurriculumFailure", ...
            "No profile solved curriculum scenario %d; elapsed times were %s s.", ...
            scenarioIndex, mat2str( ...
            plannerElapsed_s(scenarioIndex, :), 4));
    end
    bestPathLength_deg = min(successfulPathLengths_deg, [], "omitnan");
    nearBestPathLimit_deg = 1.05 * bestPathLength_deg + 1e-9;
    nearBestProfile = plannerSucceeded(scenarioIndex, :) & ...
        plannerPathLength_deg(scenarioIndex, :) <= nearBestPathLimit_deg;
    selectedProfileIndex = find(nearBestProfile, 1);
    if ~isempty(selectedProfileIndex)
        selectedProfileNames(scenarioIndex) = agentProfiles( ...
            selectedProfileIndex).Name;
    end
    if selectedProfileNames(scenarioIndex) == ""
        error("trainAzElPlannerAgent:CurriculumFailure", ...
            "No profile solved curriculum scenario %d.", scenarioIndex);
    end
    if options.Verbose
        scenarioPurpose = "validation";
        if isTrainingScenario(scenarioIndex)
            scenarioPurpose = "training";
        end
        fprintf("Agent %s %2d/%2d: %s\n", ...
            scenarioPurpose, ...
            scenarioIndex, scenarioCount, ...
            selectedProfileNames(scenarioIndex));
    end
end

trainingFeatures = allScenarioFeatures(isTrainingScenario, :);
trainingProfileNames = selectedProfileNames(isTrainingScenario);
trainingIntendedNames = intendedProfileNames(isTrainingScenario);
validationFeatures = allScenarioFeatures(~isTrainingScenario, :);
validationProfileNames = selectedProfileNames(~isTrainingScenario);
validationIntendedNames = intendedProfileNames(~isTrainingScenario);
observedClasses = unique(trainingProfileNames);
if numel(observedClasses) ~= staticProfileCount
    error("trainAzElPlannerAgent:InsufficientClasses", ...
        "Curriculum produced %d profile classes; expected %d.", ...
        numel(observedClasses), staticProfileCount);
end
curriculumDrift = trainingProfileNames ~= trainingIntendedNames;
if any(curriculumDrift)
    driftScenarios = find(curriculumDrift);
    error("trainAzElPlannerAgent:CurriculumProfileDrift", ...
        "Planner behavior changed the intended class of scenario(s): %s.", ...
        join(string(driftScenarios), ", "));
end

%% Fit the compact ranking model and package its evidence
% A shallow decision tree is intentional: the starter curriculum is small,
% its thresholds remain inspectable, and deployment needs no iterative
% neural inference. Exact planning fallback contains any misclassification.
classifier = fitctree( ...
    trainingFeatures, categorical(trainingProfileNames), ...
    "MinLeafSize", 1, ...
    "MinParentSize", 2);
trainingPrediction = string(predict(classifier, trainingFeatures));
trainingAccuracy = mean(trainingPrediction == trainingProfileNames);
validationPrediction = string(predict(classifier, validationFeatures));
validationAccuracy = mean( ...
    validationPrediction == validationProfileNames);
featureScale = max(std(trainingFeatures, 0, 1), 0.05);
trainingScenarioCount = size(trainingFeatures, 1);
nearestNeighborDistance = inf(trainingScenarioCount, 1);
for scenarioIndex = 1:trainingScenarioCount
    otherScenario = true(trainingScenarioCount, 1);
    otherScenario(scenarioIndex) = false;
    standardizedDifference = (trainingFeatures(otherScenario, :) - ...
        trainingFeatures(scenarioIndex, :)) ./ featureScale;
    nearestNeighborDistance(scenarioIndex) = min(sqrt(mean( ...
        standardizedDifference .^ 2, 2)));
end
sortedNeighborDistance = sort(nearestNeighborDistance);
distanceIndex = max(1, ceil(0.95 * trainingScenarioCount));
abstentionDistance = max( ...
    3, 2 * sortedNeighborDistance(distanceIndex));

agentArtifact = struct( ...
    "Format", "AzElPlannerSelectionAgent", ...
    "Version", 3, ...
    "CreatedUtc", string(datetime("now", "TimeZone", "UTC")), ...
    "RandomSeed", options.RandomSeed, ...
    "ValidationSeed", validationSeed, ...
    "ModelType", "classificationTree", ...
    "FeatureNames", featureNames, ...
    "Profiles", agentProfiles, ...
    "Model", classifier, ...
    "AbstentionDistance", abstentionDistance, ...
    "ExactValidationRequired", true, ...
    "TrainingReport", struct( ...
        "ScenarioCount", nnz(isTrainingScenario), ...
        "ValidationScenarioCount", nnz(~isTrainingScenario), ...
        "SelectedProfileNames", trainingProfileNames, ...
        "IntendedProfileNames", trainingIntendedNames, ...
        "PlannerSucceeded", plannerSucceeded(isTrainingScenario, :), ...
        "PlannerElapsed_s", plannerElapsed_s(isTrainingScenario, :), ...
        "PlannerPathLength_deg", ...
            plannerPathLength_deg(isTrainingScenario, :), ...
        "BenchmarkedProfileNames", ...
            string({agentProfiles(1:staticProfileCount).Name}), ...
        "NearBestPathRatio", 1.05, ...
        "TrainingFeatures", trainingFeatures, ...
        "NearestNeighborDistance", nearestNeighborDistance, ...
        "TrainingAccuracy", trainingAccuracy, ...
        "ValidationFeatures", validationFeatures, ...
        "ValidationSelectedProfileNames", validationProfileNames, ...
        "ValidationIntendedProfileNames", validationIntendedNames, ...
        "ValidationPrediction", validationPrediction, ...
        "ValidationPlannerSucceeded", ...
            plannerSucceeded(~isTrainingScenario, :), ...
        "ValidationPlannerElapsed_s", ...
            plannerElapsed_s(~isTrainingScenario, :), ...
        "ValidationPlannerPathLength_deg", ...
            plannerPathLength_deg(~isTrainingScenario, :), ...
        "ValidationAccuracy", validationAccuracy));

outputFile = char(outputFile);
outputFolder = fileparts(outputFile);
if ~isempty(outputFolder) && ~isfolder(outputFolder)
    mkdir(outputFolder);
end
save(outputFile, "agentArtifact", "-v7.3");
if options.Verbose
    fprintf("Saved az/el planner agent to %s " + ...
        "(training %.1f%%, held-out %.1f%%).\n", ...
        outputFile, 100 * trainingAccuracy, ...
        100 * validationAccuracy);
end
end
