function profile = evaluateAzElBoundaryProfile( ...
        startPosition, startVelocity, startAcceleration, ...
        stopPosition, stopVelocity, stopAcceleration, duration_s, tau_s)
%EVALUATEAZELBOUNDARYPROFILE Evaluate a two-axis quintic boundary maneuver.
%
% A quintic is the lowest-order polynomial that can independently satisfy
% position, velocity, and acceleration at both ends. Azimuth and elevation
% share normalized time but have independent coefficients.

validateattributes(duration_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
values = {startPosition, startVelocity, startAcceleration, ...
    stopPosition, stopVelocity, stopAcceleration};
for k = 1:numel(values)
    validateattributes(values{k}, {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    values{k} = reshape(double(values{k}), 1, 2);
end
startPosition = values{1};
startVelocity = values{2};
startAcceleration = values{3};
stopPosition = values{4};
stopVelocity = values{5};
stopAcceleration = values{6};
tau_s = double(tau_s(:));
validateattributes(tau_s, {'numeric'}, ...
    {'real', 'finite', '>=', 0, '<=', duration_s});

coefficient = zeros(6, 2);
coefficient(1, :) = startPosition;
coefficient(2, :) = duration_s * startVelocity;
coefficient(3, :) = 0.5 * duration_s^2 * startAcceleration;
% The first three coefficients follow from the initial conditions. This
% fixed system solves the remaining coefficients at normalized time s = 1.
rightHandSide = [ ...
    stopPosition - sum(coefficient(1:3, :), 1); ...
    duration_s * stopVelocity - ...
        coefficient(2, :) - 2 * coefficient(3, :); ...
    duration_s^2 * stopAcceleration - 2 * coefficient(3, :)];
boundaryMatrix = [1 1 1; 3 4 5; 6 12 20];
coefficient(4:6, :) = boundaryMatrix \ rightHandSide;

s = tau_s / duration_s;
positionBasis = [ones(size(s)), s, s.^2, s.^3, s.^4, s.^5];
velocityBasis = [zeros(size(s)), ones(size(s)), ...
    2 * s, 3 * s.^2, 4 * s.^3, 5 * s.^4] / duration_s;
accelerationBasis = [zeros(size(s)), zeros(size(s)), ...
    2 * ones(size(s)), 6 * s, 12 * s.^2, 20 * s.^3] / ...
    duration_s^2;
jerkBasis = [zeros(size(s)), zeros(size(s)), zeros(size(s)), ...
    6 * ones(size(s)), 24 * s, 60 * s.^2] / duration_s^3;

profile = struct( ...
    "timeFromStart_s", tau_s, ...
    "position_deg", positionBasis * coefficient, ...
    "velocity_deg_s", velocityBasis * coefficient, ...
    "acceleration_deg_s2", accelerationBasis * coefficient, ...
    "jerk_deg_s3", jerkBasis * coefficient, ...
    "coefficient", coefficient);
end
