function [featureValues, featureNames, diagnostics] = extractAzElPlannerFeatures(azElData, initialState, goalState, limits)
%EXTRACTAZELPLANNERFEATURES Describe a planning problem without rasterizing it.
%
% Training and deployment both call this function. Keeping one shared
% extractor prevents a trained model from silently seeing different units
% or feature ordering after deployment code changes.

if isstruct(azElData) && isscalar(azElData) && ...
        isfield(azElData, "Format") && ...
        string(azElData.Format) == "AzElTimeObstacleWorkspace"
    workspace = azElData;
else
    workspace = buildAzElTimeObstacleWorkspace(azElData);
end

planningDuration_s = goalState.time_s - initialState.time_s;
azimuthSpan_deg = diff(double(limits.azimuth_deg));
elevationSpan_deg = diff(double(limits.elevation_deg));
workspaceDiagonal_deg = hypot(azimuthSpan_deg, elevationSpan_deg);

endpointDelta_deg = double(goalState.position_deg) - ...
    double(initialState.position_deg);
if abs(azimuthSpan_deg - 360) <= 1e-6
    endpointDelta_deg(1) = mod(endpointDelta_deg(1) + 180, 360) - 180;
end
endpointDistance_deg = hypot( ...
    endpointDelta_deg(1), endpointDelta_deg(2));

% The exact rest-to-rest lower bound says whether the mission has generous
% time slack before obstacle geometry is considered.
axisMinimumTime_s = zeros(1, 2);
for axisIndex = 1:2
    axisTravel_deg = abs(endpointDelta_deg(axisIndex));
    axisVelocityLimit_deg_s = limits.maxVelocity_deg_s(axisIndex);
    axisAccelerationLimit_deg_s2 = limits.maxAcceleration_deg_s2( ...
        axisIndex);
    triangularDistance_deg = axisVelocityLimit_deg_s ^ 2 / ...
        axisAccelerationLimit_deg_s2;
    if axisTravel_deg <= triangularDistance_deg
        axisMinimumTime_s(axisIndex) = 2 * sqrt( ...
            axisTravel_deg / axisAccelerationLimit_deg_s2);
    else
        axisMinimumTime_s(axisIndex) = 2 * ...
            axisVelocityLimit_deg_s / ...
            axisAccelerationLimit_deg_s2 + ...
            (axisTravel_deg - triangularDistance_deg) / ...
            axisVelocityLimit_deg_s;
    end
end
kinematicLowerBound_s = max(axisMinimumTime_s);
kinematicSlackRatio = planningDuration_s / max(kinematicLowerBound_s, eps);

% A fixed-size probe costs the same for a tiny or enormous source time
% history. It measures clutter and temporal change without constructing a
% fine global occupancy tensor.
probeAzimuth_deg = linspace( ...
    limits.azimuth_deg(1), limits.azimuth_deg(2), 13);
probeElevation_deg = linspace( ...
    limits.elevation_deg(1), limits.elevation_deg(2), 11);
probeTime_s = linspace(initialState.time_s, goalState.time_s, 5);
[probeAzimuthGrid_deg, probeElevationGrid_deg, probeTimeGrid_s] = ndgrid( ...
    probeAzimuth_deg, probeElevation_deg, probeTime_s);
probeOccupied = queryAzElTimeObstacle(workspace, ...
    probeAzimuthGrid_deg, probeElevationGrid_deg, probeTimeGrid_s);
probeOccupied = reshape(probeOccupied, ...
    numel(probeAzimuth_deg), numel(probeElevation_deg), []);
occupiedProbeFraction = mean(probeOccupied, "all");
if size(probeOccupied, 3) > 1
    temporalChangeFraction = mean(abs(diff( ...
        double(probeOccupied), 1, 3)), "all");
else
    temporalChangeFraction = 0;
end

directSampleFraction = linspace(0, 1, 41).';
directSampleTime_s = initialState.time_s + ...
    directSampleFraction * planningDuration_s;
directAzimuthUnwrapped_deg = initialState.position_deg(1) + ...
    directSampleFraction * endpointDelta_deg(1);
if abs(azimuthSpan_deg - 360) <= 1e-6
    directAzimuth_deg = limits.azimuth_deg(1) + mod( ...
        directAzimuthUnwrapped_deg - limits.azimuth_deg(1), ...
        azimuthSpan_deg);
else
    directAzimuth_deg = directAzimuthUnwrapped_deg;
end
directElevation_deg = initialState.position_deg(2) + ...
    directSampleFraction * endpointDelta_deg(2);
directOccupied = queryAzElTimeObstacle(workspace, ...
    directAzimuth_deg, directElevation_deg, directSampleTime_s);
directObstructionFraction = mean(directOccupied);

% Packed bounds provide cheap scale and motion features. Bounds are used
% only by the classifier; they never replace polygon collision validation.
polygonAreaFractions = zeros(0, 1);
normalizedCentroidMotion = zeros(0, 1);
normalizedBoundaryMotion = zeros(0, 1);
verticesPerSlice = zeros(0, 1);
workspaceIsStatic = true;
dynamicObstacleCount = 0;
maximumObstacleSampleCount = 0;
maximumRingCount = 0;
minimumRingSeparation_deg = Inf;
for obstacleIndex = 1:numel(workspace.Obstacles)
    obstacle = workspace.Obstacles(obstacleIndex);
    maximumObstacleSampleCount = max( ...
        maximumObstacleSampleCount, obstacle.SampleCount);
    obstacleIsStatic = true;
    if obstacle.SampleCount > 0
        obstacleDoesNotCoverMission = obstacle.TimeSeconds(1) > ...
            initialState.time_s + 1e-9 || ...
            obstacle.TimeSeconds(end) < goalState.time_s - 1e-9;
        obstacleVertexCounts = double(diff(obstacle.SliceOffsets));
        if obstacleDoesNotCoverMission || ...
                any(obstacleVertexCounts ~= obstacleVertexCounts(1))
            obstacleIsStatic = false;
        else
            firstVertexRows = double(obstacle.SliceOffsets(1)): ...
                double(obstacle.SliceOffsets(2) - 1);
            firstAzimuth_deg = obstacle.AzimuthDeg(firstVertexRows);
            firstElevation_deg = obstacle.ElevationDeg(firstVertexRows);
            for obstacleSampleIndex = 2:obstacle.SampleCount
                sampleVertexRows = double(obstacle.SliceOffsets( ...
                    obstacleSampleIndex)):double(obstacle.SliceOffsets( ...
                    obstacleSampleIndex + 1) - 1);
                sampleMatchesFirst = isequaln( ...
                    obstacle.AzimuthDeg(sampleVertexRows), ...
                    firstAzimuth_deg) && isequaln( ...
                    obstacle.ElevationDeg(sampleVertexRows), ...
                    firstElevation_deg);
                if ~sampleMatchesFirst
                    obstacleIsStatic = false;
                    break;
                end
            end
        end
    end
    if ~obstacleIsStatic
        workspaceIsStatic = false;
        dynamicObstacleCount = dynamicObstacleCount + 1;
    end

    validSliceIndices = find(all(isfinite(obstacle.BoundsDeg), 2));
    sampledSliceCount = min(numel(validSliceIndices), 64);
    if sampledSliceCount > 0
        sampledSliceOffsets = unique(round(linspace( ...
            1, numel(validSliceIndices), sampledSliceCount)));
        sampledSliceIndices = validSliceIndices(sampledSliceOffsets);
    else
        sampledSliceIndices = zeros(0, 1);
    end
    obstacleBounds = double(obstacle.BoundsDeg( ...
        sampledSliceIndices, :));
    if ~isempty(obstacleBounds)
        obstacleCenter_deg = [ ...
            mean(obstacleBounds(:, 1:2), 2), ...
            mean(obstacleBounds(:, 3:4), 2)];
        if size(obstacleCenter_deg, 1) > 1
            centroidStep_deg = hypot( ...
                diff(obstacleCenter_deg(:, 1)), ...
                diff(obstacleCenter_deg(:, 2)));
            normalizedCentroidMotion = [normalizedCentroidMotion; ...
                centroidStep_deg / max(workspaceDiagonal_deg, eps)]; %#ok<AGROW>
        end
    end
    % A rotating shape can have a fixed centroid. Vertex displacement is
    % therefore measured separately so windmills are not mistaken for
    % static clutter.
    for sampledPairIndex = 2:numel(sampledSliceIndices)
        previousSlice = sampledSliceIndices(sampledPairIndex - 1);
        currentSlice = sampledSliceIndices(sampledPairIndex);
        previousRows = double(obstacle.SliceOffsets(previousSlice)): ...
            double(obstacle.SliceOffsets(previousSlice + 1) - 1);
        currentRows = double(obstacle.SliceOffsets(currentSlice)): ...
            double(obstacle.SliceOffsets(currentSlice + 1) - 1);
        if numel(previousRows) ~= numel(currentRows)
            normalizedBoundaryMotion(end + 1, 1) = 1; %#ok<AGROW>
            continue;
        end
        previousAzimuth_deg = double(obstacle.AzimuthDeg(previousRows));
        previousElevation_deg = double(obstacle.ElevationDeg(previousRows));
        currentAzimuth_deg = double(obstacle.AzimuthDeg(currentRows));
        currentElevation_deg = double(obstacle.ElevationDeg(currentRows));
        comparableVertex = isfinite(previousAzimuth_deg) & ...
            isfinite(previousElevation_deg) & ...
            isfinite(currentAzimuth_deg) & ...
            isfinite(currentElevation_deg);
        if any(comparableVertex)
            vertexMotion_deg = hypot( ...
                currentAzimuth_deg(comparableVertex) - ...
                    previousAzimuth_deg(comparableVertex), ...
                currentElevation_deg(comparableVertex) - ...
                    previousElevation_deg(comparableVertex));
            meanVertexMotionFraction = mean(vertexMotion_deg) / ...
                max(workspaceDiagonal_deg, eps);
            normalizedBoundaryMotion(end + 1, 1) = meanVertexMotionFraction; %#ok<AGROW>
        end
    end
    for sampledSliceIndex = reshape(sampledSliceIndices, 1, [])
        firstVertexIndex = double(obstacle.SliceOffsets( ...
            sampledSliceIndex));
        finalVertexIndex = double(obstacle.SliceOffsets( ...
            sampledSliceIndex + 1)) - 1;
        sliceAzimuth_deg = double(obstacle.AzimuthDeg( ...
            firstVertexIndex:finalVertexIndex));
        sliceElevation_deg = double(obstacle.ElevationDeg( ...
            firstVertexIndex:finalVertexIndex));
        isRealVertex = isfinite(sliceAzimuth_deg) & ...
            isfinite(sliceElevation_deg);
        runTransitions = diff([false; isRealVertex(:); false]);
        ringFirstVertex = find(runTransitions == 1);
        ringFinalVertex = find(runTransitions == -1) - 1;
        maximumRingCount = max( ...
            maximumRingCount, numel(ringFirstVertex));
        sliceArea_deg2 = 0;
        ringBounds_deg = nan(numel(ringFirstVertex), 4);
        for ringIndex = 1:numel(ringFirstVertex)
            ringRows = ringFirstVertex(ringIndex): ...
                ringFinalVertex(ringIndex);
            sliceArea_deg2 = sliceArea_deg2 + abs(polyarea( ...
                sliceAzimuth_deg(ringRows), ...
                sliceElevation_deg(ringRows)));
            ringBounds_deg(ringIndex, :) = [ ...
                min(sliceAzimuth_deg(ringRows)), ...
                max(sliceAzimuth_deg(ringRows)), ...
                min(sliceElevation_deg(ringRows)), ...
                max(sliceElevation_deg(ringRows))];
        end
        for firstRingIndex = 1:size(ringBounds_deg, 1)
            for secondRingIndex = firstRingIndex + 1:size(ringBounds_deg, 1)
                firstBounds_deg = ringBounds_deg(firstRingIndex, :);
                secondBounds_deg = ringBounds_deg(secondRingIndex, :);
                azimuthSeparation_deg = max([ ...
                    firstBounds_deg(1) - secondBounds_deg(2), ...
                    secondBounds_deg(1) - firstBounds_deg(2), 0]);
                elevationSeparation_deg = max([ ...
                    firstBounds_deg(3) - secondBounds_deg(4), ...
                    secondBounds_deg(3) - firstBounds_deg(4), 0]);
                ringSeparation_deg = hypot( ...
                    azimuthSeparation_deg, elevationSeparation_deg);
                minimumRingSeparation_deg = min( ...
                    minimumRingSeparation_deg, ringSeparation_deg);
            end
        end
        polygonAreaFractions(end + 1, 1) = sliceArea_deg2 / ...
            max(azimuthSpan_deg * elevationSpan_deg, eps); %#ok<AGROW>
    end
    verticesPerSlice(end + 1, 1) = numel(obstacle.AzimuthDeg) / ...
        max(obstacle.SampleCount, 1); %#ok<AGROW>
end
if isempty(polygonAreaFractions)
    meanPolygonAreaFraction = 0;
else
    meanPolygonAreaFraction = mean(polygonAreaFractions);
end
if isempty(normalizedCentroidMotion)
    meanNormalizedCentroidMotion = 0;
else
    meanNormalizedCentroidMotion = mean(normalizedCentroidMotion);
end
if isempty(normalizedBoundaryMotion)
    meanNormalizedBoundaryMotion = 0;
else
    meanNormalizedBoundaryMotion = mean(normalizedBoundaryMotion);
end
if isempty(verticesPerSlice)
    meanVerticesPerSlice = 0;
else
    meanVerticesPerSlice = mean(verticesPerSlice);
end
if isempty(workspace.Obstacles)
    dynamicObstacleFraction = 0;
else
    dynamicObstacleFraction = dynamicObstacleCount / ...
        numel(workspace.Obstacles);
end
obstacleSampleDensity_Hz = maximumObstacleSampleCount / ...
    max(planningDuration_s, eps);
if isinf(minimumRingSeparation_deg)
    minimumRingSeparationFraction = 1;
else
    minimumRingSeparationFraction = minimumRingSeparation_deg / ...
        max(workspaceDiagonal_deg, eps);
end

featureNames = [ ...
    "obstacleCountScaled", ...
    "planningDurationScaled", ...
    "endpointDistanceFraction", ...
    "kinematicSlackScaled", ...
    "occupiedProbeFraction", ...
    "directObstructionFraction", ...
    "meanPolygonAreaFraction", ...
    "meanCentroidMotionFraction", ...
    "meanVerticesPerSliceScaled", ...
    "temporalChangeFraction", ...
    "workspaceDynamicFlag", ...
    "obstacleSampleDensityScaled", ...
    "meanBoundaryMotionFraction", ...
    "dynamicObstacleFraction", ...
    "maximumRingCountScaled", ...
    "minimumRingSeparationFraction"];
featureValues = [ ...
    min(numel(workspace.Obstacles), 10) / 10, ...
    min(planningDuration_s, 300) / 300, ...
    endpointDistance_deg / max(workspaceDiagonal_deg, eps), ...
    min(kinematicSlackRatio, 10) / 10, ...
    occupiedProbeFraction, ...
    directObstructionFraction, ...
    min(meanPolygonAreaFraction, 1), ...
    min(meanNormalizedCentroidMotion, 1), ...
    min(meanVerticesPerSlice, 200) / 200, ...
    temporalChangeFraction, ...
    double(~workspaceIsStatic), ...
    min(obstacleSampleDensity_Hz, 20) / 20, ...
    min(meanNormalizedBoundaryMotion, 1), ...
    dynamicObstacleFraction, ...
    min(maximumRingCount, 10) / 10, ...
    min(minimumRingSeparationFraction, 1)];

diagnostics = struct( ...
    "ObstacleCount", numel(workspace.Obstacles), ...
    "WorkspaceIsStatic", workspaceIsStatic, ...
    "DynamicObstacleCount", dynamicObstacleCount, ...
    "DynamicObstacleFraction", dynamicObstacleFraction, ...
    "MaximumObstacleSampleCount", maximumObstacleSampleCount, ...
    "ObstacleSampleDensity_Hz", obstacleSampleDensity_Hz, ...
    "MeanBoundaryMotionFraction", meanNormalizedBoundaryMotion, ...
    "MaximumRingCount", maximumRingCount, ...
    "MinimumRingSeparation_deg", minimumRingSeparation_deg, ...
    "KinematicLowerBound_s", kinematicLowerBound_s, ...
    "KinematicSlackRatio", kinematicSlackRatio, ...
    "ProbeShape", size(probeOccupied), ...
    "DirectOccupiedSampleCount", sum(directOccupied));
end
