function plan = finalizeAzElPlanFailure(plan)
%% Section 0: Header & Readme
% SYNTAX
%   plan = finalizeAzElPlanFailure(plan)
%**************************************************************************
% PURPOSE
%   - Attach one evidence-ranked failure diagnosis and optionally print it.
%**************************************************************************
% INPUTS
%   - plan (scalar struct)
%       Failed planner record with any available search diagnostics.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Original schema plus stable failure classification and guidance.
%**************************************************************************
% UNITS
%   - Timing diagnostics are seconds; angular diagnostics are degrees.

%% Section 1: Validate The Failure Record
if ~isstruct(plan) || ~isscalar(plan) || ...
        ~isfield(plan, "success") || plan.success
    return;
end

%% Section 2: Recover The Termination Reason
% A failure can originate in safe-interval search, a resolution attempt, or
% static topology search. The most specific available reason is preferred;
% an empty value means the producer stopped before assigning one.
failureMessage = lower(string(fieldOr(plan, "message", "")));
terminationReason = "";
if isfield(plan, "safeIntervalSearch") && ...
        isstruct(plan.safeIntervalSearch) && ...
        isfield(plan.safeIntervalSearch, "TerminationReason")
    terminationReason = string( ...
        plan.safeIntervalSearch.TerminationReason);
end
if terminationReason == "" && ...
        isfield(plan, "resolutionAttempts") && ...
        ~isempty(plan.resolutionAttempts) && ...
        isfield(plan.resolutionAttempts, "TerminationReason")
    attemptReasons = string( ...
        {plan.resolutionAttempts.TerminationReason});
    attemptReasons = attemptReasons(attemptReasons ~= "");
    if ~isempty(attemptReasons)
        terminationReason = attemptReasons(end);
    end
end
if terminationReason == "" && isfield(plan, "topologySearch") && ...
        isstruct(plan.topologySearch) && ...
        isfield(plan.topologySearch, "TerminationReason")
    terminationReason = string(plan.topologySearch.TerminationReason);
end
terminationReason = lower(terminationReason);

%% Section 3: Derive Evidence-Based Guidance
% This is the one diagnosis that is a physical lower-bound proof rather than
% a statement about the attempted graph. It applies only to rest-to-rest
% endpoints with complete limits; all other cases deliberately remain NaN.
kinematicallyImpossible = false;
minimumObstacleFreeTime_s = NaN;
requiredPlanFields = ["startState", "stopState", "limits"];
if all(isfield(plan, requiredPlanFields))
    initialState = plan.startState;
    goalState = plan.stopState;
    axisLimits = plan.limits;
    requiredStateFields = ["time_s", "position_deg", ...
        "velocity_deg_s", "acceleration_deg_s2"];
    statesAreComplete = all(isfield( ...
        initialState, requiredStateFields)) && ...
        all(isfield(goalState, requiredStateFields));
    if statesAreComplete
        boundaryDynamics = [ ...
            initialState.velocity_deg_s, goalState.velocity_deg_s, ...
            initialState.acceleration_deg_s2, ...
            goalState.acceleration_deg_s2];
        endpointsAreAtRest = all(abs(boundaryDynamics) <= 1e-12);
        if endpointsAreAtRest
            axisDistance_deg = abs( ...
                goalState.position_deg - initialState.position_deg);
            plannerOptions = fieldOr(plan, "options", struct());
            if fieldOr(plannerOptions, "AllowAzimuthWrap", false)
                azimuthSpan_deg = diff(axisLimits.azimuth_deg);
                wrappedAzimuthDelta_deg = mod( ...
                    goalState.position_deg(1) - ...
                    initialState.position_deg(1) + ...
                    azimuthSpan_deg / 2, azimuthSpan_deg) - ...
                    azimuthSpan_deg / 2;
                axisDistance_deg(1) = abs(wrappedAzimuthDelta_deg);
            end
            switchingDistance_deg = axisLimits.maxVelocity_deg_s.^2 ./ ...
                axisLimits.maxAcceleration_deg_s2;
            usesTriangularProfile = axisDistance_deg <= switchingDistance_deg;
            axisMinimumTime_s = zeros(1, 2);
            axisMinimumTime_s(usesTriangularProfile) = 2 * sqrt( ...
                axisDistance_deg(usesTriangularProfile) ./ ...
                axisLimits.maxAcceleration_deg_s2( ...
                usesTriangularProfile));
            usesTrapezoidalProfile = ~usesTriangularProfile;
            axisMinimumTime_s(usesTrapezoidalProfile) = 2 * ...
                axisLimits.maxVelocity_deg_s(usesTrapezoidalProfile) ./ ...
                axisLimits.maxAcceleration_deg_s2( ...
                usesTrapezoidalProfile) + ( ...
                axisDistance_deg(usesTrapezoidalProfile) - ...
                switchingDistance_deg(usesTrapezoidalProfile)) ./ ...
                axisLimits.maxVelocity_deg_s(usesTrapezoidalProfile);
            minimumObstacleFreeTime_s = max(axisMinimumTime_s);
            availableTime_s = goalState.time_s - initialState.time_s;
            kinematicallyImpossible = minimumObstacleFreeTime_s > ...
                availableTime_s + 1e-9;
        end
    end
end

% --- Classify From Strongest Evidence To Weakest -------------------------
% Ordering is intentional. A proven deadline violation outranks a later
% generic "no path", and an unsafe endpoint outranks a search-budget limit.
if kinematicallyImpossible
    viability = "unlikelyWithCurrentInputs";
    reasonCode = "kinematicallyUnreachable";
    summary = sprintf( ...
        "Not viable with the current deadline and motion limits; " + ...
        "the obstacle-free rest-to-rest lower bound is %.3f s.", ...
        minimumObstacleFreeTime_s);
    suggestions = [ ...
        "Move stopState.time_s later than the lower-bound arrival time.", ...
        "Increase rate or acceleration limits only when the real " + ...
        "mechanism permits it.", ...
        "Check azimuth wrapping; enabling it can shorten a seam-crossing maneuver."];
elseif contains(failureMessage, "initial or goal") || ...
        contains(failureMessage, "start or stop") || ...
        contains(failureMessage, "start is not inside") || ...
        contains(failureMessage, "stop is not inside") || ...
        contains(failureMessage, "inside the inflated obstacle") || ...
        contains(failureMessage, "inside the inflated obstacle field") || ...
        contains(failureMessage, "inside the inflated workspace")
    viability = "unlikelyWithCurrentInputs";
    reasonCode = "unsafeEndpoint";
    summary = "Unlikely to be viable with the requested endpoint state " + ...
        "because the initial or goal state is unsafe at its required time.";
    suggestions = [ ...
        "Query the initial and goal states with queryAzElTimeObstacle.", ...
        "Move the affected endpoint or its requested time to a safe interval.", ...
        "Keep the safety margin unless the physical requirement itself changes."];
elseif contains(terminationReason, "walltimelimit") || ...
        contains(failureMessage, "time budget")
    viability = "likelyViable";
    reasonCode = "searchTimeLimit";
    summary = "The scenario may still be viable; the planner stopped " + ...
        "because its computational time budget expired.";
    suggestions = [ ...
        "Increase options.MaxSearchTime_s.", ...
        "Inspect plan.resolutionAttempts and retain only useful grid levels.", ...
        "Prebuild and reuse the obstacle field for repeated planning calls."];
elseif contains(terminationReason, "expansionlimit") || ...
        contains(failureMessage, "expansion limit")
    viability = "likelyViable";
    reasonCode = "expansionLimit";
    summary = "The scenario may still be viable; Dijkstra exhausted its node " + ...
        "budget without proving that no route exists.";
    suggestions = [ ...
        "Increase options.MaxExpansions and options.MaxSearchTime_s together.", ...
        "Use a coarse-to-fine GridStepSchedule_deg that still ends " + ...
        "at the required resolution.", ...
        "Inspect the plotted blocked states for disconnected or " + ...
        "unnecessarily large bounds."];
elseif contains(terminationReason, "densevalidationfailed") || ...
        contains(failureMessage, "dense validation")
    viability = "possiblyViable";
    reasonCode = "exactValidationRejectedCandidate";
    summary = "A candidate route existed, but exact collision validation " + ...
        "rejected it; another route may still be viable.";
    suggestions = [ ...
        "Increase MaximumSafeIntervalSamples so moving boundaries " + ...
        "are represented more densely.", ...
        "Reduce ValidationStep_s and CollisionCheckStep_s, then " + ...
        "allow more search time.", ...
        "Do not accept the rejected candidate or relax the safety " + ...
        "margin merely to make it pass."];
elseif contains(failureMessage, "moving-target interception")
    % --- Diagnose Interception Filters Before Graph Search ---------------
    interceptFilter = fieldOr(plan, "interceptFilter", struct());
    insideLimitCount = fieldOr( ...
        interceptFilter, "insideLimitCount", NaN);
    safeTargetCount = fieldOr(interceptFilter, "safeCount", NaN);
    reachableTargetCount = fieldOr( ...
        interceptFilter, "reachableCount", NaN);
    eligibleTargetCount = fieldOr( ...
        interceptFilter, "eligibleCount", ...
        fieldOr(plan, "interceptCandidateCount", NaN));
    if insideLimitCount == 0
        viability = "unlikelyWithCurrentInputs";
        reasonCode = "targetOutsideLimits";
        summary = "No sampled target state lies inside the allowed " + ...
            "azimuth/elevation bounds.";
        suggestions = [ ...
            "Correct the target frame or expand limits only to the " + ...
            "mechanism's real travel range.", ...
            "Shift the interception window to times when the target " + ...
            "is inside the allowed bounds."];
    elseif safeTargetCount == 0
        viability = "unlikelyInCurrentWindow";
        reasonCode = "targetAlwaysBlocked";
        summary = "Every in-bounds sampled target state is blocked during " + ...
            "the requested interception window.";
        suggestions = [ ...
            "Extend or shift EarliestInterceptTime_s and LatestInterceptTime_s.", ...
            "Inspect the target path against the obstacle volume " + ...
            "before launching Dijkstra.", ...
            "Do not reduce SafetyMargin_deg unless the requirement changes."];
    elseif reachableTargetCount == 0
        viability = "unlikelyInCurrentWindow";
        reasonCode = "targetKinematicallyUnreachable";
        summary = "Safe target samples exist, but none are reachable under " + ...
            "the current deadline and motion limits.";
        suggestions = [ ...
            "Move LatestInterceptTime_s later and include later target samples.", ...
            "Increase motion limits only when supported by the real actuator.", ...
            "Reduce InterceptTimeStep_s after extending the window."];
    elseif eligibleTargetCount > 0
        viability = "likelyViable";
        reasonCode = "eligibleInterceptSearchFailed";
        summary = "At least one sampled intercept was safe and kinematically " + ...
            "reachable, so the scenario may still be viable with a stronger search.";
        suggestions = [ ...
            "Increase PerAttemptMaxSearchTime_s and MaximumInterceptAttempts.", ...
            "Use a finer GridStepSchedule_deg and InterceptTimeStep_s.", ...
            "Inspect interceptAttempts to see which candidate times " + ...
            "made the most progress."];
    else
        viability = "possiblyViable";
        reasonCode = "noEligibleInterceptSample";
        summary = "The sampled interception set was empty; a continuous-time " + ...
            "intercept may still exist between samples.";
        suggestions = [ ...
            "Reduce InterceptTimeStep_s and widen the interception window.", ...
            "Inspect target safety, bounds, and reachability separately."];
    end
elseif contains(terminationReason, "nopath") || ...
        contains(failureMessage, "no safe-interval") || ...
        contains(failureMessage, "topology search failed") || ...
        contains(failureMessage, "no path")
    viability = "possiblyViable";
    reasonCode = "noPathAtAttemptedResolution";
    summary = "No route was found on the attempted graphs, but this is " + ...
        "not a proof that the continuous problem is infeasible.";
    suggestions = [ ...
        "Add a finer final value to GridStepSchedule_deg and preserve " + ...
        "exact polygon validation.", ...
        "Extend stopState.time_s when waiting for a moving opening is " + ...
        "physically allowed.", ...
        "Plot the discretized states and resolutionAttempts to check " + ...
        "connectivity near narrow gaps."];
else
    viability = "unknown";
    reasonCode = "unclassifiedFailure";
    summary = "Viability is undetermined; the returned failure does not " + ...
        "prove that the continuous problem is infeasible.";
    suggestions = [ ...
        "Inspect plan.message, plan.resolutionAttempts, and " + ...
        "plan.safeIntervalSearch.", ...
        "Verify endpoint safety and an obstacle-free kinematic lower bound first.", ...
        "Retry with more search time and one finer grid level without " + ...
        "reducing safety."];
end

plan.failureAssessment = struct( ...
    "viability", viability, ...
    "reasonCode", reasonCode, ...
    "summary", string(summary), ...
    "suggestions", string(suggestions(:)), ...
    "minimumObstacleFreeTime_s", minimumObstacleFreeTime_s);

%% Section 4: Attach & Optionally Print The Diagnosis
plannerOptions = fieldOr(plan, "options", struct());
if fieldOr(plannerOptions, "PrintFailureSuggestions", true)
    fprintf("\nAz/el plan failed: %s\n", char(string(plan.message)));
    fprintf("Viability: %s\n", char(plan.failureAssessment.summary));
    fprintf("Suggested next checks:\n");
    for suggestionIndex = 1:numel(plan.failureAssessment.suggestions)
        fprintf("  %d. %s\n", suggestionIndex, ...
            char(plan.failureAssessment.suggestions(suggestionIndex)));
    end
end
end

%% Section 5: Local Functions
function value = fieldOr(input, name, fallback)
%% Section 0: Header & Readme
% SYNTAX
%   value = fieldOr(input, name, fallback)
%**************************************************************************
% PURPOSE
%   - Read optional diagnostic fields with one empty-as-missing policy.
%**************************************************************************
% INPUTS
%   - input (scalar struct)
%       Record to inspect.
%   - name (text)
%       Field name.
%   - fallback (any)
%       Value used for a missing or empty field.
%**************************************************************************
% OUTPUTS
%   - value (any)
%       Stored or fallback value.
%**************************************************************************
% UNITS
%   - Units follow the selected value.
% Many failure schemas are intentionally partial. This shared accessor keeps
% absent and explicitly empty diagnostics equivalent during classification.
if isstruct(input) && isfield(input, name) && ~isempty(input.(name))
    value = input.(name);
else
    value = fallback;
end
end
