function plan = finalizeAzElPlanFailure(plan)
%FINALIZEAZELPLANFAILURE Attach and optionally print actionable guidance.
%
% Public planners call this once, immediately before returning a failed
% plan. Nested searches set PrintFailureSuggestions=false so a top-level
% request produces one diagnosis instead of one message per attempt.

if ~isstruct(plan) || ~isscalar(plan) || ...
        ~isfield(plan, "success") || plan.success
    return;
end

assessment = assessFailure(plan);
plan.failureAssessment = assessment;

if fieldOr(fieldOr(plan, "options", struct()), ...
        "PrintFailureSuggestions", true)
    fprintf("\nAz/el plan failed: %s\n", char(string(plan.message)));
    fprintf("Viability: %s\n", char(assessment.summary));
    fprintf("Suggested next checks:\n");
    for k = 1:numel(assessment.suggestions)
        fprintf("  %d. %s\n", k, char(assessment.suggestions(k)));
    end
end
end

function assessment = assessFailure(plan)
message = lower(string(fieldOr(plan, "message", "")));
termination = lower(terminationReason(plan));
[kinematicallyImpossible, minimumTime_s] = ...
    fixedEndpointTimingIsImpossible(plan);

if kinematicallyImpossible
    viability = "unlikelyWithCurrentInputs";
    reason = "kinematicallyUnreachable";
    summary = sprintf( ...
        "Not viable with the current deadline and motion limits; " + ...
        "the obstacle-free rest-to-rest lower bound is %.3f s.", ...
        minimumTime_s);
    suggestions = [ ...
        "Move stopState.time_s later than the lower-bound arrival time.", ...
        "Increase rate or acceleration limits only when the real mechanism permits it.", ...
        "Check azimuth wrapping; enabling it can shorten a seam-crossing maneuver."];
elseif contains(message, "initial or goal") || ...
        contains(message, "start or stop") || ...
        contains(message, "start is not inside") || ...
        contains(message, "stop is not inside") || ...
        contains(message, "inside the inflated obstacle") || ...
        contains(message, "inside the inflated workspace")
    viability = "unlikelyWithCurrentInputs";
    reason = "unsafeEndpoint";
    summary = "Unlikely to be viable with the requested endpoint state " + ...
        "because the initial or goal state is unsafe at its required time.";
    suggestions = [ ...
        "Query the initial and goal states with queryAzElTimeObstacle.", ...
        "Move the affected endpoint or its requested time to a safe interval.", ...
        "Keep the safety margin unless the physical requirement itself changes."];
elseif contains(termination, "walltimelimit") || ...
        contains(message, "time budget")
    viability = "likelyViable";
    reason = "searchTimeLimit";
    summary = "The scenario may still be viable; the planner stopped " + ...
        "because its computational time budget expired.";
    suggestions = [ ...
        "Increase options.MaxSearchTime_s.", ...
        "Inspect plan.resolutionAttempts and retain only useful grid levels.", ...
        "Prebuild and reuse the obstacle workspace for repeated planning calls."];
elseif contains(termination, "expansionlimit") || ...
        contains(message, "expansion limit")
    viability = "likelyViable";
    reason = "expansionLimit";
    summary = "The scenario may still be viable; Dijkstra exhausted its node " + ...
        "budget without proving that no route exists.";
    suggestions = [ ...
        "Increase options.MaxExpansions and options.MaxSearchTime_s together.", ...
        "Use a coarse-to-fine GridStepSchedule_deg that still ends at the required resolution.", ...
        "Inspect the plotted blocked states for disconnected or unnecessarily large bounds."];
elseif contains(termination, "densevalidationfailed") || ...
        contains(message, "dense validation")
    viability = "possiblyViable";
    reason = "exactValidationRejectedCandidate";
    summary = "A candidate route existed, but exact collision validation " + ...
        "rejected it; another route may still be viable.";
    suggestions = [ ...
        "Increase MaximumSafeIntervalSamples so moving boundaries are represented more densely.", ...
        "Reduce ValidationStep_s and CollisionCheckStep_s, then allow more search time.", ...
        "Do not accept the rejected candidate or relax the safety margin merely to make it pass."];
elseif contains(message, "moving-target interception")
    [viability, reason, summary, suggestions] = ...
        movingTargetGuidance(plan);
elseif contains(termination, "nopath") || ...
        contains(message, "no safe-interval") || ...
        contains(message, "topology search failed") || ...
        contains(message, "no path")
    viability = "possiblyViable";
    reason = "noPathAtAttemptedResolution";
    summary = "No route was found on the attempted graphs, but this is " + ...
        "not a proof that the continuous problem is infeasible.";
    suggestions = [ ...
        "Add a finer final value to GridStepSchedule_deg and preserve exact polygon validation.", ...
        "Extend stopState.time_s when waiting for a moving opening is physically allowed.", ...
        "Plot the discretized states and resolutionAttempts to check connectivity near narrow gaps."];
else
    viability = "unknown";
    reason = "unclassifiedFailure";
    summary = "Viability is undetermined; the returned failure does not " + ...
        "prove that the continuous problem is infeasible.";
    suggestions = [ ...
        "Inspect plan.message, plan.resolutionAttempts, and plan.safeIntervalSearch.", ...
        "Verify endpoint safety and an obstacle-free kinematic lower bound first.", ...
        "Retry with more search time and one finer grid level without reducing safety."];
end

assessment = struct( ...
    "viability", viability, ...
    "reasonCode", reason, ...
    "summary", string(summary), ...
    "suggestions", string(suggestions(:)), ...
    "minimumObstacleFreeTime_s", minimumTime_s);
end

function [viability, reason, summary, suggestions] = ...
        movingTargetGuidance(plan)
filter = fieldOr(plan, "interceptFilter", struct());
insideCount = fieldOr(filter, "insideLimitCount", NaN);
safeCount = fieldOr(filter, "safeCount", NaN);
reachableCount = fieldOr(filter, "reachableCount", NaN);
eligibleCount = fieldOr(filter, "eligibleCount", ...
    fieldOr(plan, "interceptCandidateCount", NaN));

if insideCount == 0
    viability = "unlikelyWithCurrentInputs";
    reason = "targetOutsideLimits";
    summary = "No sampled target state lies inside the allowed " + ...
        "azimuth/elevation bounds.";
    suggestions = [ ...
        "Correct the target frame or expand limits only to the mechanism's real travel range.", ...
        "Shift the interception window to times when the target is inside the allowed bounds."];
elseif safeCount == 0
    viability = "unlikelyInCurrentWindow";
    reason = "targetAlwaysBlocked";
    summary = "Every in-bounds sampled target state is blocked during " + ...
        "the requested interception window.";
    suggestions = [ ...
        "Extend or shift EarliestInterceptTime_s and LatestInterceptTime_s.", ...
        "Inspect the target path against the obstacle volume before launching Dijkstra.", ...
        "Do not reduce SafetyMargin_deg unless the requirement changes."];
elseif reachableCount == 0
    viability = "unlikelyInCurrentWindow";
    reason = "targetKinematicallyUnreachable";
    summary = "Safe target samples exist, but none are reachable under " + ...
        "the current deadline and motion limits.";
    suggestions = [ ...
        "Move LatestInterceptTime_s later and include later target samples.", ...
        "Increase motion limits only when supported by the real actuator.", ...
        "Reduce InterceptTimeStep_s after extending the window."];
elseif eligibleCount > 0
    viability = "likelyViable";
    reason = "eligibleInterceptSearchFailed";
    summary = "At least one sampled intercept was safe and kinematically " + ...
        "reachable, so the scenario may still be viable with a stronger search.";
    suggestions = [ ...
        "Increase PerAttemptMaxSearchTime_s and MaximumInterceptAttempts.", ...
        "Use a finer GridStepSchedule_deg and InterceptTimeStep_s.", ...
        "Inspect interceptAttempts to see which candidate times made the most progress."];
else
    viability = "possiblyViable";
    reason = "noEligibleInterceptSample";
    summary = "The sampled interception set was empty; a continuous-time " + ...
        "intercept may still exist between samples.";
    suggestions = [ ...
        "Reduce InterceptTimeStep_s and widen the interception window.", ...
        "Inspect target safety, bounds, and reachability separately."];
end
end

function reason = terminationReason(plan)
reason = "";
if isfield(plan, "safeIntervalSearch") && ...
        isstruct(plan.safeIntervalSearch) && ...
        isfield(plan.safeIntervalSearch, "TerminationReason")
    reason = string(plan.safeIntervalSearch.TerminationReason);
end
if reason == "" && isfield(plan, "resolutionAttempts") && ...
        ~isempty(plan.resolutionAttempts) && ...
        isfield(plan.resolutionAttempts, "TerminationReason")
    values = string({plan.resolutionAttempts.TerminationReason});
    values = values(values ~= "");
    if ~isempty(values)
        reason = values(end);
    end
end
if reason == "" && isfield(plan, "topologySearch") && ...
        isstruct(plan.topologySearch) && ...
        isfield(plan.topologySearch, "TerminationReason")
    reason = string(plan.topologySearch.TerminationReason);
end
end

function [impossible, minimumTime_s] = fixedEndpointTimingIsImpossible(plan)
impossible = false;
minimumTime_s = NaN;
required = ["startState", "stopState", "limits"];
if ~all(isfield(plan, required))
    return;
end
initialState = plan.startState;
goalState = plan.stopState;
limits = plan.limits;
if ~all(isfield(initialState, ...
        ["time_s", "position_deg", "velocity_deg_s", ...
        "acceleration_deg_s2"])) || ...
        ~all(isfield(goalState, ...
        ["time_s", "position_deg", "velocity_deg_s", ...
        "acceleration_deg_s2"])) || ...
        any(abs([initialState.velocity_deg_s, goalState.velocity_deg_s, ...
        initialState.acceleration_deg_s2, ...
        goalState.acceleration_deg_s2]) > 1e-12)
    return;
end

delta = abs(goalState.position_deg - initialState.position_deg);
options = fieldOr(plan, "options", struct());
if fieldOr(options, "AllowAzimuthWrap", false)
    span = diff(limits.azimuth_deg);
    delta(1) = abs(mod( ...
        goalState.position_deg(1) - initialState.position_deg(1) + ...
        span / 2, span) - span / 2);
end
axisTime = restToRestMinimumTime(delta, ...
    limits.maxVelocity_deg_s, limits.maxAcceleration_deg_s2);
minimumTime_s = max(axisTime);
availableTime_s = goalState.time_s - initialState.time_s;
impossible = minimumTime_s > availableTime_s + 1e-9;
end

function time_s = restToRestMinimumTime(distance_deg, velocity, acceleration)
switchDistance = velocity .^ 2 ./ acceleration;
triangular = distance_deg <= switchDistance;
time_s = zeros(1, 2);
time_s(triangular) = 2 * sqrt( ...
    distance_deg(triangular) ./ acceleration(triangular));
time_s(~triangular) = 2 * velocity(~triangular) ./ ...
    acceleration(~triangular) + ...
    (distance_deg(~triangular) - switchDistance(~triangular)) ./ ...
    velocity(~triangular);
end

function value = fieldOr(input, name, fallback)
if isstruct(input) && isfield(input, name) && ~isempty(input.(name))
    value = input.(name);
else
    value = fallback;
end
end
