function result = planAzElGuidedRoute( ...
        workspace, startState, stopState, limits, options)
%PLANAZELGUIDEDROUTE Retime and validate a user-supplied waypoint route.
%
% GuidePath_deg is an N-by-2 azimuth/elevation array in options. Every
% segment uses a synchronized rest-to-rest triangular or trapezoidal motion
% profile. The route is sampled and collision-checked like other continuous
% planner results.

timer = tic;
result = failedResult("No collision-free guided trajectory was found.");
if any(abs([startState.velocity_deg_s, stopState.velocity_deg_s, ...
        startState.acceleration_deg_s2, ...
        stopState.acceleration_deg_s2]) > 1e-12)
    result.Message = "Guided routes require zero boundary velocity " + ...
        "and acceleration.";
    return;
end

points = [ ...
    startState.position_deg; ...
    options.GuidePath_deg; ...
    stopState.position_deg];
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    for pointIndex = 2:size(points, 1)
        delta = mod(points(pointIndex, 1) - points(pointIndex - 1, 1) + ...
            span / 2, span) - span / 2;
        points(pointIndex, 1) = points(pointIndex - 1, 1) + delta;
    end
end
if any(points(:, 2) < limits.elevation_deg(1) | ...
        points(:, 2) > limits.elevation_deg(2)) || ...
        (~options.AllowAzimuthWrap && ...
        any(points(:, 1) < limits.azimuth_deg(1) | ...
        points(:, 1) > limits.azimuth_deg(2)))
    result.Message = "GuidePath_deg contains a point outside the limits.";
    return;
end

delta = diff(points, 1, 1);
[duration, peakRate, acceleration] = ...
    motionParameters(delta.', limits);
minimumDuration_s = sum(duration);
availableDuration_s = stopState.time_s - startState.time_s;
slack_s = availableDuration_s - minimumDuration_s;
if slack_s < -1e-9
    result.Message = sprintf( ...
        "Guided route needs %.3f s but only %.3f s is available.", ...
        minimumDuration_s, availableDuration_s);
    return;
end

candidateCount = max(1, min(100, floor(max(0, slack_s)) + 1));
motionStarts = linspace( ...
    startState.time_s, startState.time_s + max(0, slack_s), ...
    candidateCount);
for candidate = 1:candidateCount
    segmentStart_s = motionStarts(candidate) + ...
        [0, cumsum(duration(1:end - 1))];
    profile = makeProfile( ...
        startState.time_s, stopState.time_s, points, delta, ...
        segmentStart_s, duration, peakRate, acceleration, options);
    collisionOptions = options;
    if isfield(options, "CollisionCheckStep_s") && ...
            ~isempty(options.CollisionCheckStep_s)
        collisionOptions.SampleTime_s = min( ...
            options.SampleTime_s, options.CollisionCheckStep_s);
    end
    collisionProfile = makeProfile( ...
        startState.time_s, stopState.time_s, points, delta, ...
        segmentStart_s, duration, peakRate, acceleration, ...
        collisionOptions);
    if profileCollisionFree(workspace, collisionProfile, options)
        length_deg = sum(hypot(delta(:, 1), delta(:, 2)));
        directDelta = points(end, :) - points(1, :);
        lowerBound_deg = hypot(directDelta(1), directDelta(2));
        arrivalTime_s = segmentStart_s + duration;
        result = successfulResult( ...
            profile, length_deg, lowerBound_deg, ...
            candidate, toc(timer), points, arrivalTime_s);
        return;
    end
    if toc(timer) >= options.MaxSearchTime_s
        break;
    end
end
result.CandidateCount = min(candidateCount, candidate);
result.SearchElapsed_s = toc(timer);
end

function profile = makeProfile( ...
        startTime_s, stopTime_s, points, delta, segmentStart_s, ...
        duration, peakRate, acceleration, options)
time_s = (startTime_s:options.SampleTime_s:stopTime_s).';
if time_s(end) < stopTime_s
    time_s(end + 1, 1) = stopTime_s;
end
[progress, rate, accelerationValue] = motionProfile( ...
    time_s, segmentStart_s, duration, peakRate, acceleration);
unwrappedPosition = points(1, :) + progress * delta;
velocity = rate * delta;
accelerationOutput = accelerationValue * delta;
position = unwrappedPosition;
if options.AllowAzimuthWrap
    position(:, 1) = mod(position(:, 1) + 180, 360) - 180;
end
accelerationOutput([1 end], :) = 0;
profile = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "positionUnwrapped_deg", unwrappedPosition, ...
    "velocity_deg_s", velocity, ...
    "acceleration_deg_s2", accelerationOutput, ...
    "isWaiting", ...
    all(abs(velocity) <= 1e-10, 2) & ...
    all(abs(accelerationOutput) <= 1e-10, 2));
end

function [progress, rate, accelerationValue] = motionProfile( ...
        time_s, startTime, duration, peakRate, acceleration)
tau = time_s - startTime;
accelerationTime = peakRate ./ acceleration;
accelerationDistance = 0.5 .* acceleration .* accelerationTime.^2;
cruiseTime = max(0, duration - 2 .* accelerationTime);
progress = zeros(size(tau));
rate = zeros(size(tau));
accelerationValue = zeros(size(tau));

accelerationMatrix = repmat(acceleration, numel(time_s), 1);
accelerationTimeMatrix = repmat( ...
    accelerationTime, numel(time_s), 1);
accelerationDistanceMatrix = repmat( ...
    accelerationDistance, numel(time_s), 1);
peakRateMatrix = repmat(peakRate, numel(time_s), 1);
durationMatrix = repmat(duration, numel(time_s), 1);

accelerating = tau > 0 & tau < accelerationTime;
progress(accelerating) = 0.5 .* ...
    accelerationMatrix(accelerating) .* tau(accelerating).^2;
rate(accelerating) = ...
    accelerationMatrix(accelerating) .* tau(accelerating);
accelerationValue(accelerating) = accelerationMatrix(accelerating);

cruising = tau >= accelerationTime & ...
    tau < accelerationTime + cruiseTime;
progress(cruising) = accelerationDistanceMatrix(cruising) + ...
    peakRateMatrix(cruising) .* ...
    (tau(cruising) - accelerationTimeMatrix(cruising));
rate(cruising) = peakRateMatrix(cruising);

decelerating = tau >= accelerationTime + cruiseTime & tau < duration;
remaining = durationMatrix - tau;
progress(decelerating) = 1 - 0.5 .* ...
    accelerationMatrix(decelerating) .* remaining(decelerating).^2;
rate(decelerating) = ...
    accelerationMatrix(decelerating) .* remaining(decelerating);
accelerationValue(decelerating) = -accelerationMatrix(decelerating);
progress(tau >= duration) = 1;
end

function [duration, peakRate, acceleration] = ...
        motionParameters(delta, limits)
absoluteDelta = abs(delta);
rateCandidate = inf(size(delta));
accelerationCandidate = inf(size(delta));
nonzero = absoluteDelta > 1e-12;
rateLimits = limits.maxVelocity_deg_s(:);
accelerationLimits = limits.maxAcceleration_deg_s2(:);
for axisIndex = 1:2
    active = nonzero(axisIndex, :);
    rateCandidate(axisIndex, active) = ...
        rateLimits(axisIndex) ./ absoluteDelta(axisIndex, active);
    accelerationCandidate(axisIndex, active) = ...
        accelerationLimits(axisIndex) ./ absoluteDelta(axisIndex, active);
end
rateLimit = min(rateCandidate, [], 1);
acceleration = min(accelerationCandidate, [], 1);
stationary = ~isfinite(rateLimit);
rateLimit(stationary) = 0;
acceleration(stationary) = 1;

triangular = rateLimit.^2 ./ acceleration >= 1;
accelerationTime = rateLimit ./ acceleration;
accelerationTime(triangular) = sqrt(1 ./ acceleration(triangular));
peakRate = acceleration .* accelerationTime;
accelerationDistance = acceleration .* accelerationTime.^2;
cruiseTime = zeros(size(rateLimit));
cruiseTime(~triangular) = ...
    (1 - accelerationDistance(~triangular)) ./ peakRate(~triangular);
duration = 2 .* accelerationTime + cruiseTime;
duration(stationary) = 0;
end

function yes = profileCollisionFree(workspace, profile, options)
blocked = queryAzElTimeObstacle(workspace, ...
    profile.position_deg(:, 1), profile.position_deg(:, 2), ...
    profile.time_s, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
yes = ~any(blocked);
end

function result = successfulResult( ...
        profile, lengthDeg, lowerBoundDeg, candidateCount, ...
        elapsed_s, points, arrivalTime_s)
history = [ ...
    points(2:end - 1, :), ...
    arrivalTime_s(1:end - 1).'];
result = struct( ...
    "Success", true, ...
    "Message", sprintf( ...
    "Guided route found (<= %.3fx global optimum lower bound).", ...
    max(1, lengthDeg / max(lowerBoundDeg, eps))), ...
    "Method", "guidedWaypointRoute", ...
    "OptimalGlobally", false, ...
    "AngularPathLengthDeg", lengthDeg, ...
    "AngularLowerBoundDeg", lowerBoundDeg, ...
    "SuboptimalityBound", ...
    max(1, lengthDeg / max(lowerBoundDeg, eps)), ...
    "CandidateCount", candidateCount, ...
    "SearchElapsed_s", elapsed_s, ...
    "Profile", profile, ...
    "Waypoint", struct(), ...
    "WaypointHistory", history);
end

function result = failedResult(message)
result = struct( ...
    "Success", false, ...
    "Message", string(message), ...
    "Method", "guidedWaypointRoute", ...
    "OptimalGlobally", false, ...
    "AngularPathLengthDeg", Inf, ...
    "AngularLowerBoundDeg", NaN, ...
    "SuboptimalityBound", Inf, ...
    "CandidateCount", 0, ...
    "SearchElapsed_s", 0, ...
    "Profile", struct(), ...
    "Waypoint", struct(), ...
    "WaypointHistory", zeros(0, 3));
end
