function result = planAzElMinimumDistance( ...
        workspace, startState, stopState, limits, options)
%PLANAZELMINIMUMDISTANCE Find a short continuous az/el avoidance path.
%
% This planner first tests retimings of the globally shortest straight
% segment. If those are blocked, it searches dynamically feasible two-leg
% paths through a coarse-to-fine az/el/time waypoint grid. Every returned
% sample is rechecked against the packed moving obstacles at SampleTime_s.

timer = tic;
result = failedResult("No minimum-distance trajectory was found.");
if any(abs([startState.velocity_deg_s, stopState.velocity_deg_s, ...
        startState.acceleration_deg_s2, ...
        stopState.acceleration_deg_s2]) > 1e-12)
    result.Message = "Continuous minimum-distance search requires zero " + ...
        "boundary velocity and acceleration; lattice fallback required.";
    return;
end

startTime_s = startState.time_s;
stopTime_s = stopState.time_s;
startPosition = startState.position_deg;
goalPosition = unwrappedGoal( ...
    startPosition, stopState.position_deg, limits, options);
directDelta = goalPosition - startPosition;
lowerBound_deg = hypot(directDelta(1), directDelta(2));
candidateCount = 0;

[direct, tested] = searchDirectTimings( ...
    workspace, startTime_s, stopTime_s, startPosition, ...
    directDelta, limits, options);
candidateCount = candidateCount + tested;
if direct.Success
    result = successfulResult(direct.Profile, lowerBound_deg, ...
        lowerBound_deg, candidateCount, toc(timer), ...
        true, zeros(0, 3));
    return;
end

[azimuthGrid, elevationGrid, timeGrid] = coarseWaypointGrid( ...
    workspace, startTime_s, stopTime_s, startPosition, ...
    goalPosition, limits, options);
[best, tested] = searchWaypointGrid( ...
    workspace, startTime_s, stopTime_s, startPosition, goalPosition, ...
    limits, options, azimuthGrid, elevationGrid, timeGrid);
candidateCount = candidateCount + tested;
if ~best.Success
    result.Message = "No collision-free straight or one-waypoint path " + ...
        "was found; lattice fallback required.";
    result.CandidateCount = candidateCount;
    result.SearchElapsed_s = toc(timer);
    return;
end

refinement = [ ...
    12, 12, 20, 2, 2; ...
    3, 3, 5, 1, 1; ...
    1.5, 1.5, 3, 0.5, 0.5];
waypointHistory = [ ...
    best.WaypointAzimuthDeg, ...
    best.WaypointElevationDeg, ...
    best.WaypointTime_s];
for level = 1:size(refinement, 1)
    if toc(timer) >= options.MaxSearchTime_s
        break;
    end
    azimuthGrid = centeredGrid(best.WaypointAzimuthDeg, ...
        refinement(level, 1), refinement(level, 4), ...
        azimuthSearchLimits(startPosition, goalPosition, ...
        limits, options));
    elevationGrid = centeredGrid(best.WaypointElevationDeg, ...
        refinement(level, 2), refinement(level, 4), ...
        limits.elevation_deg);
    timeGrid = centeredGrid(best.WaypointTime_s, ...
        refinement(level, 3), refinement(level, 5), ...
        [startTime_s, stopTime_s]);
    [refined, tested] = searchWaypointGrid( ...
        workspace, startTime_s, stopTime_s, ...
        startPosition, goalPosition, limits, options, ...
        azimuthGrid, elevationGrid, timeGrid);
    candidateCount = candidateCount + tested;
    if refined.Success && refined.LengthDeg < best.LengthDeg
        best = refined;
        waypointHistory(end + 1, :) = [ ...
            best.WaypointAzimuthDeg, ...
            best.WaypointElevationDeg, ...
            best.WaypointTime_s]; %#ok<AGROW>
    end
end

result = successfulResult(best.Profile, best.LengthDeg, ...
    lowerBound_deg, candidateCount, toc(timer), ...
    false, waypointHistory);
result.Waypoint = struct( ...
    "time_s", best.WaypointTime_s, ...
    "position_deg", [ ...
    best.WaypointAzimuthDeg, best.WaypointElevationDeg]);
end

function [best, candidateCount] = searchDirectTimings( ...
        workspace, startTime_s, stopTime_s, startPosition, ...
        delta, limits, options)
best = emptyCandidate();
[duration, peakRate, acceleration] = ...
    motionParameters(delta(:), limits);
available = stopTime_s - startTime_s - duration;
if available < -1e-9
    candidateCount = 0;
    return;
end
if all([workspace.Obstacles.PackedVertexCount] == 0)
    starts = startTime_s;
else
    count = max(2, min(200, floor(max(0, available) / 0.5) + 1));
    starts = linspace(startTime_s, startTime_s + max(0, available), count);
end
candidateCount = numel(starts);
checkTime = searchTimeVector(startTime_s, stopTime_s, options);
progress = motionProgress( ...
    checkTime, starts, repmat(duration, size(starts)), ...
    repmat(peakRate, size(starts)), ...
    repmat(acceleration, size(starts)));
azimuth = startPosition(1) + progress .* delta(1);
elevation = startPosition(2) + progress .* delta(2);
free = collisionFreeColumns( ...
    workspace, azimuth, elevation, checkTime, options);
for candidate = find(free)
    profile = oneLegProfile( ...
        startTime_s, stopTime_s, starts(candidate), ...
        startPosition, delta, duration, peakRate, acceleration, options);
    if profileCollisionFree(workspace, profile, options)
        best.Success = true;
        best.LengthDeg = hypot(delta(1), delta(2));
        best.Profile = profile;
        return;
    end
end
end

function [best, candidateCount] = searchWaypointGrid( ...
        workspace, startTime_s, stopTime_s, startPosition, goalPosition, ...
        limits, options, azimuthGrid, elevationGrid, timeGrid)
[waypointTime, waypointAzimuth, waypointElevation] = ndgrid( ...
    timeGrid, azimuthGrid, elevationGrid);
waypointTime = waypointTime(:).';
waypointAzimuth = waypointAzimuth(:).';
waypointElevation = waypointElevation(:).';
firstDelta = [ ...
    waypointAzimuth - startPosition(1); ...
    waypointElevation - startPosition(2)];
secondDelta = [ ...
    goalPosition(1) - waypointAzimuth; ...
    goalPosition(2) - waypointElevation];
[firstDuration, firstRate, firstAcceleration] = ...
    motionParameters(firstDelta, limits);
[secondDuration, secondRate, secondAcceleration] = ...
    motionParameters(secondDelta, limits);
firstStart = waypointTime - firstDuration;
secondStop = waypointTime + secondDuration;
feasible = firstStart >= startTime_s - 1e-9 & ...
    secondStop <= stopTime_s + 1e-9;

waypointTime = waypointTime(feasible);
waypointAzimuth = waypointAzimuth(feasible);
waypointElevation = waypointElevation(feasible);
firstDelta = firstDelta(:, feasible);
secondDelta = secondDelta(:, feasible);
firstDuration = firstDuration(feasible);
firstRate = firstRate(feasible);
firstAcceleration = firstAcceleration(feasible);
secondDuration = secondDuration(feasible);
secondRate = secondRate(feasible);
secondAcceleration = secondAcceleration(feasible);
firstStart = firstStart(feasible);
candidateCount = numel(waypointTime);
best = emptyCandidate();
if candidateCount == 0
    return;
end

checkTime = searchTimeVector(startTime_s, stopTime_s, options);
freeCandidates = zeros(0, 1);
freeLengths = zeros(0, 1);
batchSize = 600;
for first = 1:batchSize:candidateCount
    index = first:min(first + batchSize - 1, candidateCount);
    firstProgress = motionProgress( ...
        checkTime, firstStart(index), firstDuration(index), ...
        firstRate(index), firstAcceleration(index));
    secondProgress = motionProgress( ...
        checkTime, waypointTime(index), secondDuration(index), ...
        secondRate(index), secondAcceleration(index));
    azimuth = startPosition(1) + ...
        firstProgress .* firstDelta(1, index) + ...
        secondProgress .* secondDelta(1, index);
    elevation = startPosition(2) + ...
        firstProgress .* firstDelta(2, index) + ...
        secondProgress .* secondDelta(2, index);
    free = collisionFreeColumns( ...
        workspace, azimuth, elevation, checkTime, options);
    selected = index(free);
    lengths = hypot(firstDelta(1, selected), ...
        firstDelta(2, selected)) + ...
        hypot(secondDelta(1, selected), secondDelta(2, selected));
    freeCandidates = [freeCandidates; selected(:)]; %#ok<AGROW>
    freeLengths = [freeLengths; lengths(:)]; %#ok<AGROW>
end
if isempty(freeCandidates)
    return;
end
[~, order] = sort(freeLengths);
for orderIndex = reshape(order, 1, [])
    candidate = freeCandidates(orderIndex);
    profile = twoLegProfile( ...
        startTime_s, stopTime_s, waypointTime(candidate), ...
        startPosition, goalPosition, ...
        [waypointAzimuth(candidate), waypointElevation(candidate)], ...
        firstDuration(candidate), firstRate(candidate), ...
        firstAcceleration(candidate), secondDuration(candidate), ...
        secondRate(candidate), secondAcceleration(candidate), options);
    if profileCollisionFree(workspace, profile, options)
        best.Success = true;
        best.LengthDeg = freeLengths(orderIndex);
        best.Profile = profile;
        best.WaypointTime_s = waypointTime(candidate);
        best.WaypointAzimuthDeg = waypointAzimuth(candidate);
        best.WaypointElevationDeg = waypointElevation(candidate);
        return;
    end
end
end

function profile = oneLegProfile( ...
        startTime_s, stopTime_s, motionStart_s, ...
        startPosition, delta, duration, peakRate, acceleration, options)
time_s = outputTimeVector(startTime_s, stopTime_s, options.SampleTime_s);
[progress, progressRate, progressAcceleration] = motionProfile( ...
    time_s, motionStart_s, duration, peakRate, acceleration);
profile = makeProfile(time_s, ...
    startPosition + progress .* delta, ...
    progressRate .* delta, ...
    progressAcceleration .* delta, options);
end

function profile = twoLegProfile( ...
        startTime_s, stopTime_s, waypointTime_s, ...
        startPosition, goalPosition, waypointPosition, ...
        firstDuration, firstRate, firstAcceleration, ...
        secondDuration, secondRate, secondAcceleration, options)
time_s = outputTimeVector(startTime_s, stopTime_s, options.SampleTime_s);
firstStart = waypointTime_s - firstDuration;
[firstProgress, firstProgressRate, firstProgressAcceleration] = ...
    motionProfile(time_s, firstStart, firstDuration, ...
    firstRate, firstAcceleration);
[secondProgress, secondProgressRate, secondProgressAcceleration] = ...
    motionProfile(time_s, waypointTime_s, secondDuration, ...
    secondRate, secondAcceleration);
firstDelta = waypointPosition - startPosition;
secondDelta = goalPosition - waypointPosition;
profile = makeProfile(time_s, ...
    startPosition + firstProgress .* firstDelta + ...
    secondProgress .* secondDelta, ...
    firstProgressRate .* firstDelta + ...
    secondProgressRate .* secondDelta, ...
    firstProgressAcceleration .* firstDelta + ...
    secondProgressAcceleration .* secondDelta, options);
end

function profile = makeProfile( ...
        time_s, unwrappedPosition, velocity, acceleration, options)
position = unwrappedPosition;
if options.AllowAzimuthWrap
    position(:, 1) = wrapAzimuth(position(:, 1));
end
profile = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "positionUnwrapped_deg", unwrappedPosition, ...
    "velocity_deg_s", velocity, ...
    "acceleration_deg_s2", acceleration);
profile.acceleration_deg_s2([1 end], :) = 0;
profile.isWaiting = all(abs(profile.velocity_deg_s) <= 1e-10, 2) & ...
    all(abs(profile.acceleration_deg_s2) <= 1e-10, 2);
end

function free = collisionFreeColumns( ...
        workspace, azimuth, elevation, time_s, options)
wrappedAzimuth = azimuth;
if options.AllowAzimuthWrap
    wrappedAzimuth = wrapAzimuth(wrappedAzimuth);
end
queryTime = repmat(time_s, 1, size(azimuth, 2));
blocked = queryAzElTimeObstacle(workspace, ...
    wrappedAzimuth(:), elevation(:), queryTime(:), struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
blocked = reshape(blocked, size(azimuth));
free = ~any(blocked, 1);
end

function yes = profileCollisionFree(workspace, profile, options)
blocked = queryAzElTimeObstacle(workspace, ...
    profile.position_deg(:, 1), profile.position_deg(:, 2), ...
    profile.time_s, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", 1));
yes = ~any(blocked);
end

function [duration, peakRate, acceleration] = ...
        motionParameters(delta, limits)
absoluteDelta = abs(delta);
rateCandidate = inf(size(delta));
accelerationCandidate = inf(size(delta));
nonzero = absoluteDelta > 1e-12;
rateLimits = limits.maxVelocity_deg_s(:);
accelerationLimits = limits.maxAcceleration_deg_s2(:);
for axisIndex = 1:2
    active = nonzero(axisIndex, :);
    rateCandidate(axisIndex, active) = ...
        rateLimits(axisIndex) ./ absoluteDelta(axisIndex, active);
    accelerationCandidate(axisIndex, active) = ...
        accelerationLimits(axisIndex) ./ absoluteDelta(axisIndex, active);
end
rateLimit = min(rateCandidate, [], 1);
acceleration = min(accelerationCandidate, [], 1);
stationary = ~isfinite(rateLimit);
rateLimit(stationary) = 0;
acceleration(stationary) = 1;

triangular = rateLimit.^2 ./ acceleration >= 1;
accelerationTime = rateLimit ./ acceleration;
accelerationTime(triangular) = sqrt(1 ./ acceleration(triangular));
peakRate = acceleration .* accelerationTime;
accelerationDistance = acceleration .* accelerationTime.^2;
cruiseTime = zeros(size(rateLimit));
cruiseTime(~triangular) = ...
    (1 - accelerationDistance(~triangular)) ./ peakRate(~triangular);
duration = 2 .* accelerationTime + cruiseTime;
duration(stationary) = 0;
end

function progress = motionProgress( ...
        time_s, startTime, duration, peakRate, acceleration)
[progress, ~, ~] = motionProfile( ...
    time_s, startTime, duration, peakRate, acceleration);
end

function [progress, rate, accelerationValue] = motionProfile( ...
        time_s, startTime, duration, peakRate, acceleration)
tau = time_s - startTime;
accelerationTime = peakRate ./ acceleration;
accelerationDistance = 0.5 .* acceleration .* accelerationTime.^2;
cruiseTime = max(0, duration - 2 .* accelerationTime);
progress = zeros(size(tau));
rate = zeros(size(tau));
accelerationValue = zeros(size(tau));

accelerationMatrix = repmat(acceleration, numel(time_s), 1);
accelerationTimeMatrix = repmat( ...
    accelerationTime, numel(time_s), 1);
accelerationDistanceMatrix = repmat( ...
    accelerationDistance, numel(time_s), 1);
peakRateMatrix = repmat(peakRate, numel(time_s), 1);
durationMatrix = repmat(duration, numel(time_s), 1);

accelerating = tau > 0 & tau < accelerationTime;
progress(accelerating) = 0.5 .* ...
    accelerationMatrix(accelerating) .* tau(accelerating).^2;
rate(accelerating) = ...
    accelerationMatrix(accelerating) .* tau(accelerating);
accelerationValue(accelerating) = accelerationMatrix(accelerating);

cruising = tau >= accelerationTime & ...
    tau < accelerationTime + cruiseTime;
progress(cruising) = accelerationDistanceMatrix(cruising) + ...
    peakRateMatrix(cruising) .* ...
    (tau(cruising) - accelerationTimeMatrix(cruising));
rate(cruising) = peakRateMatrix(cruising);

decelerating = tau >= accelerationTime + cruiseTime & tau < duration;
remaining = durationMatrix - tau;
progress(decelerating) = 1 - 0.5 .* ...
    accelerationMatrix(decelerating) .* remaining(decelerating).^2;
rate(decelerating) = ...
    accelerationMatrix(decelerating) .* remaining(decelerating);
accelerationValue(decelerating) = -accelerationMatrix(decelerating);
progress(tau >= duration) = 1;
end

function [azimuthGrid, elevationGrid, timeGrid] = coarseWaypointGrid( ...
        workspace, startTime_s, stopTime_s, startPosition, ...
        goalPosition, limits, options)
[obstacleAzimuth, obstacleElevation] = obstacleBounds( ...
    workspace, mean([startPosition(1), goalPosition(1)]), options);
azimuthValues = [ ...
    startPosition(1), goalPosition(1), obstacleAzimuth(:).'];
elevationValues = [ ...
    startPosition(2), goalPosition(2), obstacleElevation(:).'];
azimuthLimits = azimuthSearchLimits( ...
    startPosition, goalPosition, limits, options);
azimuthRange = [min(azimuthValues) - 20, max(azimuthValues) + 20];
azimuthRange = [ ...
    max(azimuthRange(1), azimuthLimits(1)), ...
    min(azimuthRange(2), azimuthLimits(2))];
elevationRange = [ ...
    max(min(elevationValues) - 20, limits.elevation_deg(1)), ...
    min(max(elevationValues) + 20, limits.elevation_deg(2))];
azimuthGrid = inclusiveGrid(azimuthRange, 10);
elevationGrid = inclusiveGrid(elevationRange, 10);
duration = stopTime_s - startTime_s;
timeGrid = inclusiveGrid([ ...
    startTime_s + 0.2 * duration, ...
    stopTime_s - 0.05 * duration], max(5, duration / 30));
end

function [azimuth, elevation] = obstacleBounds( ...
        workspace, referenceAzimuth, options)
azimuth = zeros(0, 1);
elevation = zeros(0, 1);
for obstacle = reshape(workspace.Obstacles, 1, [])
    bounds = double(obstacle.BoundsDeg);
    valid = all(isfinite(bounds), 2);
    currentAzimuth = [bounds(valid, 1); bounds(valid, 2)];
    if options.AllowAzimuthWrap
        currentAzimuth = referenceAzimuth + mod( ...
            currentAzimuth - referenceAzimuth + 180, 360) - 180;
    end
    azimuth = [azimuth; currentAzimuth]; %#ok<AGROW>
    elevation = [ ...
        elevation; bounds(valid, 3); bounds(valid, 4)]; %#ok<AGROW>
end
if isempty(azimuth)
    azimuth = referenceAzimuth;
    elevation = 0;
end
end

function limitsOut = azimuthSearchLimits( ...
        startPosition, goalPosition, limits, options)
if options.AllowAzimuthWrap
    center = mean([startPosition(1), goalPosition(1)]);
    limitsOut = center + [-180 180];
else
    limitsOut = limits.azimuth_deg;
end
end

function values = inclusiveGrid(range, step)
if range(2) <= range(1)
    values = mean(range);
    return;
end
values = range(1):step:range(2);
if values(end) < range(2) - 1e-9
    values(end + 1) = range(2);
end
end

function values = centeredGrid(center, radius, step, limits)
range = [max(center - radius, limits(1)), ...
    min(center + radius, limits(2))];
values = inclusiveGrid(range, step);
if all(abs(values - center) > 1e-9)
    values = sort([values center]);
end
end

function time_s = searchTimeVector(startTime_s, stopTime_s, options)
step = max(options.SampleTime_s, 0.5);
time_s = outputTimeVector(startTime_s, stopTime_s, step);
end

function time_s = outputTimeVector(startTime_s, stopTime_s, step)
time_s = (startTime_s:step:stopTime_s).';
if time_s(end) < stopTime_s
    time_s(end + 1, 1) = stopTime_s;
end
end

function goal = unwrappedGoal(start, requested, limits, options)
goal = requested;
if options.AllowAzimuthWrap
    span = diff(limits.azimuth_deg);
    delta = mod(requested(1) - start(1) + span / 2, span) - span / 2;
    goal(1) = start(1) + delta;
end
end

function azimuth = wrapAzimuth(azimuth)
azimuth = mod(azimuth + 180, 360) - 180;
end

function result = successfulResult( ...
        profile, lengthDeg, lowerBoundDeg, candidateCount, ...
        elapsed_s, globallyOptimal, waypointHistory)
result = struct( ...
    "Success", true, ...
    "Message", "", ...
    "Method", "continuousWaypointSearch", ...
    "OptimalGlobally", globallyOptimal, ...
    "AngularPathLengthDeg", lengthDeg, ...
    "AngularLowerBoundDeg", lowerBoundDeg, ...
    "SuboptimalityBound", max(1, lengthDeg / max(lowerBoundDeg, eps)), ...
    "CandidateCount", candidateCount, ...
    "SearchElapsed_s", elapsed_s, ...
    "Profile", profile, ...
    "Waypoint", struct(), ...
    "WaypointHistory", waypointHistory);
if globallyOptimal
    result.Message = "Globally shortest straight angular path found.";
else
    result.Message = sprintf( ...
        "Minimum-distance waypoint path found (<= %.3fx global optimum).", ...
        result.SuboptimalityBound);
end
end

function result = failedResult(message)
result = struct( ...
    "Success", false, ...
    "Message", string(message), ...
    "Method", "continuousWaypointSearch", ...
    "OptimalGlobally", false, ...
    "AngularPathLengthDeg", Inf, ...
    "AngularLowerBoundDeg", NaN, ...
    "SuboptimalityBound", Inf, ...
    "CandidateCount", 0, ...
    "SearchElapsed_s", 0, ...
    "Profile", struct(), ...
    "Waypoint", struct(), ...
    "WaypointHistory", zeros(0, 3));
end

function candidate = emptyCandidate()
candidate = struct( ...
    "Success", false, ...
    "LengthDeg", Inf, ...
    "Profile", struct(), ...
    "WaypointTime_s", NaN, ...
    "WaypointAzimuthDeg", NaN, ...
    "WaypointElevationDeg", NaN);
end
