function tests = testAzElPlannerAgent
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
set(0, "DefaultFigureVisible", "off");
end

function teardownOnce(~)
close all force;
end

function testBundledAgentHasAuditableContract(testCase)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
artifactFile = fullfile(packageRoot, ...
    "models", "azElPlannerAgent.mat");
verifyTrue(testCase, isfile(artifactFile));
savedData = load(artifactFile, "agentArtifact");
agentArtifact = savedData.agentArtifact;

verifyEqual(testCase, ...
    agentArtifact.Format, "AzElPlannerSelectionAgent");
verifyTrue(testCase, agentArtifact.ExactValidationRequired);
verifyEqual(testCase, numel(agentArtifact.Profiles), 3);
verifyEqual(testCase, ...
    string({agentArtifact.Profiles.Name}), ...
    ["fast" "balanced" "precise"]);
verifyGreaterThanOrEqual(testCase, ...
    agentArtifact.TrainingReport.TrainingAccuracy, 0.8);
verifyEqual(testCase, ...
    unique(agentArtifact.TrainingReport.SelectedProfileNames), ...
    ["balanced"; "fast"; "precise"]);
end

function testDeploymentReturnsOnlyExactValidatedRoute(testCase)
[azElData, initialState, goalState, axisLimits] = narrowPassageProblem();
plan = planAzElWithAgent( ...
    azElData, initialState, goalState, axisLimits, struct( ...
        "AgentPrintDiagnostics", false, ...
        "AgentMaxSearchTime_s", 20));

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.exactCollisionValidated);
verifyNotEmpty(testCase, plan.agent.Attempts);
verifyEqual(testCase, ...
    plan.agent.SelectedProfileName, ...
    plan.agent.Attempts(end).ProfileName);
verifyTrue(testCase, ...
    plan.agent.Attempts(end).ExactCollisionValidated);
occupied = queryAzElTimeObstacle( ...
    plan.workspace, plan.position_deg(:, 1), ...
    plan.position_deg(:, 2), plan.time_s);
verifyFalse(testCase, any(occupied));
end

function testTrainerProducesReloadableAgent(testCase)
temporaryArtifactFile = string(tempname) + ".mat";
cleanup = onCleanup(@() deleteTemporaryArtifact( ...
    temporaryArtifactFile));
agentArtifact = trainAzElPlannerAgent( ...
    temporaryArtifactFile, struct( ...
        "CurriculumScenariosPerClass", 2, ...
        "RandomSeed", 31, ...
        "Verbose", false));
savedData = load(temporaryArtifactFile, "agentArtifact");

verifyEqual(testCase, ...
    savedData.agentArtifact.Format, ...
    "AzElPlannerSelectionAgent");
verifyEqual(testCase, ...
    savedData.agentArtifact.FeatureNames, ...
    agentArtifact.FeatureNames);
verifyEqual(testCase, ...
    savedData.agentArtifact.TrainingReport.ScenarioCount, 6);
verifyGreaterThanOrEqual(testCase, ...
    savedData.agentArtifact.TrainingReport.TrainingAccuracy, 0.8);
end

function [azElData, initialState, goalState, axisLimits] = narrowPassageProblem()
% Shared by deployment checks so every assertion sees identical geometry.
sampleTime_s = (0:1:20).';
wallAzimuth_deg = [ ...
    -3.4; 2.4; 2.4; -3.4; -3.4; NaN; ...
    -3.4; 2.4; 2.4; -3.4; -3.4];
wallElevation_deg = [ ...
    -10; -10; -3.7; -3.7; -10; NaN; ...
    -2.3; -2.3; 10; 10; -2.3];
azElData = makeAzElObstacleData( ...
    "Agent test wall", sampleTime_s, ...
    repmat({wallAzimuth_deg}, numel(sampleTime_s), 1), ...
    repmat({wallElevation_deg}, numel(sampleTime_s), 1));
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
axisLimits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [5 5]);
end

function deleteTemporaryArtifact(temporaryArtifactFile)
% onCleanup reaches this from both successful and failed training tests.
if isfile(temporaryArtifactFile)
    delete(temporaryArtifactFile);
end
end
