function tests = testAzElAdaptiveAStar
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function testDirectPathUsesExactCertificate(testCase)
time_s = (0:10).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
[startState, stopState, limits] = standardProblem(10);

plan = planAzElAdaptiveAStar( ...
    data, startState, stopState, limits, struct( ...
    "SampleTime_s", 0.25, ...
    "Objective", "minimumAngularDistance", ...
    "GridStepSchedule_deg", [4 2 1]));

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.optimalGlobally);
verifyEqual(testCase, plan.angularPathLength_deg, 8, "AbsTol", 1e-9);
verifyEqual(testCase, plan.selectedGridStep_deg, 4);
verifyPlan(testCase, plan);
end

function testMovingWallProducesDynamicDetour(testCase)
time_s = (0:20).';
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    center = 0.35 * sin(time_s(k) / 3);
    azimuth{k} = [-1; 1; 1; -1; -1];
    elevation{k} = center + [-2; -2; 2; 2; -2];
end
data = makeAzElObstacleData( ...
    "Moving wall", time_s, azimuth, elevation);
[startState, stopState, limits] = standardProblem(20);

plan = planAzElAdaptiveAStar( ...
    data, startState, stopState, limits, struct( ...
    "SampleTime_s", 0.25, ...
    "GridStepSchedule_deg", [2 1], ...
    "SafetyMargin_deg", 0.1, ...
    "MaxSearchTime_s", 8));

verifyTrue(testCase, plan.success);
verifyGreaterThan(testCase, plan.angularPathLength_deg, 8);
verifyGreaterThan(testCase, plan.expandedNodeCount, 0);
verifyPlan(testCase, plan);
end

function testWrappedAzimuthUsesShortChord(testCase)
time_s = (0:20).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
startState = boundaryState(0, [170 0]);
stopState = boundaryState(20, [-170 0]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);

plan = planAzElAdaptiveAStar( ...
    data, startState, stopState, limits, struct( ...
    "SampleTime_s", 0.25, ...
    "AllowAzimuthWrap", true));

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.angularPathLength_deg, 20, "AbsTol", 1e-9);
verifyEqual(testCase, plan.positionUnwrapped_deg(end, 1), ...
    190, "AbsTol", 1e-9);
verifyPlan(testCase, plan);
end

function testEnabledTerminalCaptureMatchesNonzeroRate(testCase)
time_s = (0:10).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
startState = boundaryState(0, [0 0]);
stopState = boundaryState(10, [5 0]);
stopState.velocity_deg_s = [0.5 0];
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-5 5], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);

plan = planAzElAdaptiveAStar( ...
    data, startState, stopState, limits, struct( ...
    "AllowNonzeroTerminalState", true, ...
    "SampleTime_s", 0.1, ...
    "GridStepSchedule_deg", 1, ...
    "MaxSearchTime_s", 8));

verifyTrue(testCase, plan.success);
verifyEqual(testCase, ...
    plan.position_deg(end, :), [5 0], "AbsTol", 1e-9);
verifyEqual(testCase, ...
    plan.velocity_deg_s(end, :), [0.5 0], "AbsTol", 1e-9);
verifyEqual(testCase, ...
    plan.acceleration_deg_s2(end, :), [0 0], "AbsTol", 1e-9);
verifyPlan(testCase, plan);
end

function verifyPlan(testCase, plan)
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", plan.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
verifyFalse(testCase, any(blocked));
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.velocity_deg_s), [], 1), ...
    plan.limits.maxVelocity_deg_s + 1e-8);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.acceleration_deg_s2), [], 1), ...
    plan.limits.maxAcceleration_deg_s2 + 1e-8);
end

function [startState, stopState, limits] = standardProblem(stopTime)
startState = boundaryState(0, [-4 0]);
stopState = boundaryState(stopTime, [4 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-5 5], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
