function tests = testAzElStaticDijkstra
%% Section 0: Header & Readme
% SYNTAX
%   results = runtests("testAzElStaticDijkstra.m")
%**************************************************************************
% PURPOSE
%   - Verify goal-rooted static Dijkstra propagation and diagnostics.
%**************************************************************************
% INPUTS
%   - None; MATLAB supplies local function-test fixtures.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Local tests discovered by functiontests.
%**************************************************************************
% UNITS
%   - Test quantities follow the planner's degree/second conventions.
%% Section 1: Register Local Tests
tests = functiontests(localfunctions);
end

function setupOnce(~)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(packageRoot));
end

function teardown(~)
close all force;
end

function testFiveTurnSpiralUsesGoalRootedDijkstraWithoutGuide(testCase)
set(0, "DefaultFigureVisible", "off");
result = example05FiveTurnSpiral();

verifyTrue(testCase, result.plan.success);
verifyEqual(testCase, ...
    result.plan.method, "adaptiveGoalRootedDijkstra");
verifyEqual(testCase, ...
    result.plan.topologySearch.Method, "goalRootedDijkstra");
verifyTrue(testCase, result.plan.topologyOptimalOnLattice);
verifyFalse(testCase, isfield(result.plan.options, "GuidePath_deg"));
verifyFalse(testCase, ...
    isfield(result.plan.options, "DirectionAngles_deg"));
verifyEqual(testCase, result.blockedSampleCount, 0);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.windingTurns, 4);
verifyLessThan(testCase, result.plan.angularPathLength_deg, 250);
verifyLessThan(testCase, ...
    result.diagnostics.motionCompletionTime_s, 200);
verifyLessThan(testCase, ...
    result.plan.topologySearch.SearchElapsed_s, 30);
end

function testAzimuthWrapUsesShortSeamRoute(testCase)
time_s = (0:1:30).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = obstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
initialState = boundaryState(0, [170 0]);
goalState = boundaryState(30, [-170 0]);
axisLimits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance");

plan = planAzElDijkstra( ...
    azElData, initialState, goalState, axisLimits, options);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, "adaptiveGoalRootedDijkstra");
verifyEqual(testCase, plan.position_deg(end, 1), -170, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.positionUnwrapped_deg(end, 1), 190, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.angularPathLength_deg, 20, ...
    "AbsTol", 1e-9);
end

function testCostToGoalStrictlyDecreasesAlongLatticePath(testCase)
time_s = (0:1:20).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = obstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
initialState = boundaryState(0, [-4 0]);
goalState = boundaryState(20, [4 0]);
axisLimits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-5 5], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", 1, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance");

plan = planAzElDijkstra( ...
    azElData, initialState, goalState, axisLimits, options);
topology = plan.topologySearch;
pathCost_deg = topology.CostToGoal_deg(topology.GridNodePath);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, pathCost_deg(end), 0, "AbsTol", 1e-12);
verifyTrue(testCase, all(diff(pathCost_deg) < 0));
verifyTrue(testCase, ...
    topology.SettledMask(topology.InitialGridNode));
verifyEqual(testCase, topology.LatticeDistance_deg, 8, ...
    "AbsTol", 1e-12);
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function data = obstacleData(name, time_s, azimuth, elevation)
data = struct( ...
    "targetName", string(name), ...
    "time_s", double(time_s(:)), ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", repmat("visible", numel(time_s), 1));
end
