function tests = testAzElBidirectionalKinodynamicRRTStar
%% Section 0: Header & Readme
% SYNTAX
%   results = runtests("testAzElBidirectionalKinodynamicRRTStar.m")
%**************************************************************************
% PURPOSE
%   - Verify independent bidirectional RRT* search, validation, defaults,
%     and stable public result schemas.
%**************************************************************************
% INPUTS
%   - None; MATLAB supplies local function-test fixtures.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Local tests discovered by functiontests.
%**************************************************************************
% UNITS
%   - Test quantities follow the planner's degree/second conventions.

%% Section 1: Register Local Tests
tests = functiontests(localfunctions);
end

function setupOnce(~)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(packageRoot));
end

function testDirectTrajectoryCertifiesAngularLowerBound(testCase)
time_s = (0:10).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = makeAzElObstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
initialState = restState(0, [-2 1]);
goalState = restState(10, [3 4]);
limits = standardLimits([-10 10], [-10 10]);

plan = planAzElBidirectionalKinodynamicRRTStar( ...
    azElData, initialState, goalState, limits, struct( ...
    "RandomSeed", 11, ...
    "MaxSearchTime_s", 2));

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.optimalGlobally);
verifyFalse(testCase, isfield(plan.options, "GoalBias"));
verifyEqual(testCase, plan.angularPathLength_deg, hypot(5, 3), ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.blockedValidationSampleCount, 0);
verifyEqual(testCase, plan.obstacleField, plan.workspace);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.velocity_deg_s), [], 1), ...
    limits.maxVelocity_deg_s + 1e-9);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.acceleration_deg_s2), [], 1), ...
    limits.maxAcceleration_deg_s2 + 1e-9);
end

function testBidirectionalTreesDetourAroundStaticBlock(testCase)
time_s = (0:40).';
azElData = makeAzElObstacleData( ...
    "Central blocker", time_s, ...
    [-1; 1; 1; -1; -1], [43; 43; 47; 47; 43]);
initialState = restState(0, [-6 45]);
goalState = restState(40, [6 45]);
limits = standardLimits([-10 10], [40 50]);
options = struct( ...
    "SafetyMargin_deg", 0.1, ...
    "RandomSeed", 7, ...
    "StepSize_deg", 3, ...
    "RewireRadius_deg", 5, ...
    "ConnectionRadius_deg", 7, ...
    "MaxIterations", 3000, ...
    "IterationsAfterFirstSolution", 100, ...
    "MaxSearchTime_s", 12);

plan = planAzElBidirectionalKinodynamicRRTStar( ...
    azElData, initialState, goalState, limits, options);

verifyTrue(testCase, plan.success, plan.message);
verifyGreaterThan(testCase, plan.forwardTree.Count, 1);
verifyGreaterThan(testCase, plan.backwardTree.Count, 1);
verifyEqual(testCase, plan.forwardTree.CreationIteration(1), uint32(0));
verifyEqual(testCase, plan.backwardTree.CreationIteration(1), uint32(0));
verifyGreaterThan(testCase, ...
    plan.forwardTree.CreationIteration(2:end), uint32(0));
verifyGreaterThan(testCase, ...
    plan.backwardTree.CreationIteration(2:end), uint32(0));
verifyLessThanOrEqual(testCase, ...
    double(plan.forwardTree.CreationIteration), plan.completedIterations);
verifyLessThanOrEqual(testCase, ...
    double(plan.backwardTree.CreationIteration), plan.completedIterations);
verifyGreaterThan(testCase, plan.angularPathLength_deg, 12);
verifyEqual(testCase, plan.blockedValidationSampleCount, 0);
blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct("SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
verifyFalse(testCase, any(blocked));
end

function testRrtDoesNotDelegateOrAcceptRouteGuidance(testCase)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
rrtSource = string(fileread(fullfile( ...
    packageRoot, "planAzElBidirectionalKinodynamicRRTStar.m")));
dijkstraSource = string(fileread(fullfile( ...
    packageRoot, "planAzElDijkstra.m")));

verifyFalse(testCase, contains(rrtSource, "planAzElDijkstra"));
verifyFalse(testCase, contains( ...
    dijkstraSource, "planAzElBidirectionalKinodynamicRRTStar"));
for forbiddenInput = [ ...
        """GuidePath_deg""", """StateCorridor""", ...
        """DirectionAngles_deg""", """GoalBias"""]
    verifyFalse(testCase, contains(rrtSource, forbiddenInput));
end
end

function testDefaultsAndFailuresUseStablePublicSchema(testCase)
limits = standardLimits([-10 10], [-10 10]);
defaults = planAzElBidirectionalKinodynamicRRTStar(limits, "defaults");
verifyEqual(testCase, defaults.RandomSeed, 5489);
verifyEqual(testCase, defaults.AllowAzimuthWrap, false);

time_s = (0:10).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
clearData = makeAzElObstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
initialState = restState(0, [-2 0]);
goalState = restState(10, [2 0]);
successPlan = planAzElBidirectionalKinodynamicRRTStar( ...
    clearData, initialState, goalState, limits, struct( ...
    "MaxIterations", 0, ...
    "MaxSearchTime_s", 1));

blockedData = makeAzElObstacleData( ...
    "Full field", time_s, ...
    [-10; 10; 10; -10; -10], [-10; -10; 10; 10; -10]);
failurePlan = planAzElBidirectionalKinodynamicRRTStar( ...
    blockedData, initialState, goalState, limits, struct( ...
    "TimePaddingSamples", 0, ...
    "MaxIterations", 0, ...
    "MaxSearchTime_s", 1));

verifyTrue(testCase, successPlan.success);
verifyFalse(testCase, failurePlan.success);
verifyEqual(testCase, sort(string(fieldnames(failurePlan))), ...
    sort(string(fieldnames(successPlan))));
verifyEqual(testCase, failurePlan.obstacleField, failurePlan.workspace);
end

function state = restState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function limits = standardLimits(azimuth_deg, elevation_deg)
limits = struct( ...
    "azimuth_deg", azimuth_deg, ...
    "elevation_deg", elevation_deg, ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
end
