function tests = testStandaloneExampleAnimations
%% Section 0: Header & Readme
% SYNTAX
%   results = runtests("testStandaloneExampleAnimations.m")
%**************************************************************************
% PURPOSE
%   - Verify numbered-example discovery, advertised planner routing,
%     animation integration, and scenario-specific regression checks.
%**************************************************************************
% INPUTS
%   - None; MATLAB supplies local function-test fixtures.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Local tests discovered by functiontests.
%**************************************************************************
% UNITS
%   - Test quantities follow the examples' degree/second conventions.

%% Section 1: Register Local Tests
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function teardown(~)
close all force;
end

function testExampleNumbersAreConsecutiveAndCallable(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
examples = dir(fullfile(folder, "example*.m"));
names = sort(string({examples.name}));
numbers = zeros(numel(names), 1);
for exampleIndex = 1:numel(names)
    token = regexp(names(exampleIndex), "^example(\d\d).+\.m$", ...
        "tokens", "once");
    verifyNotEmpty(testCase, token, ...
        sprintf('%s does not use the exampleNNName convention.', ...
        names(exampleIndex)));
    numbers(exampleIndex) = str2double(token{1});
    functionName = erase(names(exampleIndex), ".m");
    verifyNotEmpty(testCase, which(functionName), ...
        sprintf('%s is not callable.', functionName));
end
verifyEqual(testCase, numbers, (1:numel(names)).');
end

function testEveryExampleUsesCommonAnimationPath(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
examples = dir(fullfile(folder, "example*.m"));
verifyGreaterThan(testCase, numel(examples), 0);
for exampleIndex = 1:numel(examples)
    source = string(fileread( ...
        fullfile(folder, examples(exampleIndex).name)));
    usesAnimator = contains(source, "animateAzElAvoidancePlan");
    usesGauntletRunner = contains(source, "runAzElGauntletCase");
    verifyTrue(testCase, usesAnimator || usesGauntletRunner, ...
        sprintf('%s has no 2-D/3-D animation path.', ...
        examples(exampleIndex).name));
end
end

function testEveryExampleUsesItsAdvertisedPlanner(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
examples = dir(fullfile(folder, "example*.m"));
rrtExampleNames = [ ...
    "example03KinodynamicDetour.m", ...
    "example04DynamicSafeIntervals.m"];
for exampleIndex = 1:numel(examples)
    source = string(fileread( ...
        fullfile(examples(exampleIndex).folder, ...
        examples(exampleIndex).name)));
    if ismember(string(examples(exampleIndex).name), rrtExampleNames)
        verifyTrue(testCase, contains( ...
            source, "planAzElBidirectionalKinodynamicRRTStar"), ...
            sprintf('%s does not call bidirectional RRT*.', ...
            examples(exampleIndex).name));
        verifyFalse(testCase, contains(source, "planAzElDijkstra"), ...
            sprintf('%s still delegates to Dijkstra.', ...
            examples(exampleIndex).name));
        continue;
    end
    usesPlanner = contains(source, "planAzElDijkstra");
    usesRunner = contains(source, "runAzElGauntletCase");
    usesInterceptWrapper = ...
        contains(source, "planAzElMovingTargetIntercept");
    verifyTrue(testCase, ...
        usesPlanner || usesRunner || usesInterceptWrapper, ...
        sprintf('%s bypasses its documented Dijkstra path.', ...
        examples(exampleIndex).name));
end
end

function testRrtExamplesExecuteRrtAndValidateCollision(testCase)
viewOptions = struct( ...
    "FigureVisible", "off", ...
    "PauseSeconds", 0, ...
    "MaximumAnimationFrames", 2, ...
    "MaximumDisplayedSlices", 2);

staticPlan = example03KinodynamicDetour(viewOptions);
dynamicResult = example04DynamicSafeIntervals(viewOptions);

verifyEqual(testCase, ...
    staticPlan.method, "bidirectionalKinodynamicRRTStar");
verifyGreaterThan(testCase, staticPlan.forwardTree.Count, 1);
verifyGreaterThan(testCase, staticPlan.backwardTree.Count, 1);
verifyEqual(testCase, staticPlan.blockedValidationSampleCount, 0);
verifyEqual(testCase, ...
    dynamicResult.plan.method, "bidirectionalKinodynamicRRTStar");
verifyGreaterThan(testCase, dynamicResult.plan.forwardTree.Count, 1);
verifyGreaterThan(testCase, dynamicResult.plan.backwardTree.Count, 1);
verifyEqual(testCase, dynamicResult.blockedSampleCount, 0);
end

function testApiObstacleExampleCompletesBlockedChordDetour(testCase)
time_s = (2700:5:3000).';
azElData = makeAzElObstacleData( ...
    "API regression blocker", time_s, ...
    [10; 30; 30; 10; 10], [20; 20; 50; 50; 20]);
viewOptions = struct( ...
    "FigureVisible", "off", ...
    "PauseSeconds", 0, ...
    "MaximumAnimationFrames", 2, ...
    "MaximumDisplayedSlices", 2);

plan = example01PlanFromAzElData(azElData, viewOptions);

verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, "adaptiveGoalRootedDijkstra");
verifyEqual(testCase, plan.selectedGridStep_deg, 1);
verifyLessThan(testCase, plan.searchElapsed_s, ...
    plan.options.MaxSearchTime_s);
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", plan.options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
verifyFalse(testCase, any(blocked));
end

function testPlannerFilesAreConsolidated(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
publicPlannerFiles = dir(fullfile(root, "planAzEl*.m"));
verifyEqual(testCase, sort(string({publicPlannerFiles.name})), ...
    sort(["planAzElBidirectionalKinodynamicRRTStar.m", ...
    "planAzElDijkstra.m", ...
    "planAzElMovingTargetIntercept.m"]));
privatePlannerFiles = dir(fullfile(root, "private", "*.m"));
verifyEqual(testCase, sort(string({privatePlannerFiles.name})), ...
    sort(["finalizeAzElPlanFailure.m", ...
    "isAzElTimeObstacleWorkspaceStatic.m", ...
    "searchAzElSafeIntervalDijkstra.m"]));
end

function testDefaultOptionsForceCombinedView(testCase)
options = defaultAzElAnimationOptions(struct( ...
    "ViewMode", "2d", ...
    "FigureVisible", "off"));

verifyEqual(testCase, options.ViewMode, "combined");
end

function testCombinedAnimatorCreatesBothAxes(testCase)
time_s = (0:2).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", [-1 0; 0 0; 1 0], ...
    "workspace", buildAzElTimeObstacleWorkspace(data), ...
    "limits", struct( ...
    "azimuth_deg", [-2 2], ...
    "elevation_deg", [-1 1]));
handles = animateAzElAvoidancePlan(data, plan, ...
    defaultAzElAnimationOptions(struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "PauseSeconds", 0)));

verifyTrue(testCase, isgraphics(handles.AzElAxes, "axes"));
verifyTrue(testCase, isgraphics(handles.WorkspaceAxes, "axes"));
verifyEqual(testCase, handles.Options.ViewMode, "combined");
end

function testDenseObstacleSceneUsesCompactLegend(testCase)
time_s = (0:1).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = repmat(makeAzElObstacleData( ...
    "Obstacle", time_s, empty, empty), 7, 1);
for obstacleIndex = 1:numel(data)
    data(obstacleIndex).targetName = "Obstacle " + obstacleIndex;
end
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", [0 0; 1 0], ...
    "workspace", buildAzElTimeObstacleWorkspace(data), ...
    "limits", struct( ...
    "azimuth_deg", [-2 2], ...
    "elevation_deg", [-1 1]));
handles = animateAzElAvoidancePlan(data, plan, struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "PauseSeconds", 0, ...
    "MaximumObstacleLegendEntries", 6));

verifyTrue(testCase, ...
    isgraphics(handles.TwoDimensional.ObstacleLegend, "line"));
verifyEqual(testCase, ...
    string(get(handles.TwoDimensional.ObstacleLegend, "DisplayName")), ...
    "7 scenario obstacles");
verifyTrue(testCase, all(string(get( ...
    handles.TwoDimensional.ObstacleBoundaries, ...
    "HandleVisibility")) == "off"));
end

function testAnimatorShowsLatticeContenderAndSelectedRoute(testCase)
time_s = (0:2).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
attemptTemplate = struct( ...
    "GridStep_deg", 2, ...
    "PrimitiveRadii_deg", [2 4], ...
    "Success", true, ...
    "Message", "valid", ...
    "ExpandedNodeCount", 1, ...
    "GeneratedNodeCount", 2, ...
    "SearchElapsed_s", 0.1, ...
    "TerminationReason", "goalReached", ...
    "ObjectiveCost", 3, ...
    "CandidateTime_s", time_s, ...
    "CandidatePosition_deg", [-1 0; 0 0.5; 1 0], ...
    "Selected", false);
selectedAttempt = attemptTemplate;
selectedAttempt.GridStep_deg = 1;
selectedAttempt.ObjectiveCost = 2;
selectedAttempt.CandidatePosition_deg = [-1 0; 0 0; 1 0];
selectedAttempt.Selected = true;
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", selectedAttempt.CandidatePosition_deg, ...
    "workspace", buildAzElTimeObstacleWorkspace(data), ...
    "limits", struct( ...
        "azimuth_deg", [-2 2], ...
        "elevation_deg", [-1 1]), ...
    "selectedGridStep_deg", 1, ...
    "resolutionAttempts", [attemptTemplate; selectedAttempt], ...
    "safeIntervalSearch", struct("EventTimes_s", time_s));

handles = animateAzElAvoidancePlan(data, plan, struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "PauseSeconds", 0));

verifyTrue(testCase, ...
    isgraphics(handles.TwoDimensional.Discretization, "line"));
verifyEqual(testCase, ...
    numel(handles.TwoDimensional.CandidateRoutes), 1);
verifyTrue(testCase, ...
    isgraphics(handles.TwoDimensional.SelectedRoute, "line"));
verifyTrue(testCase, ...
    isgraphics(handles.ThreeDimensional.Discretization, "line"));
verifyEqual(testCase, ...
    numel(handles.ThreeDimensional.CandidateRoutes), 1);
verifyTrue(testCase, ...
    isgraphics(handles.ThreeDimensional.SelectedRoute, "line"));
end

function testGauntletsDoNotInjectRoutes(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
supportFolder = fullfile(folder, "support");
files = [ ...
    dir(fullfile(folder, "example*.m")); ...
    dir(fullfile(supportFolder, "make*Gauntlet.m"))];
[~, uniqueIndex] = unique({files.name}, "stable");
files = files(uniqueIndex);
for fileIndex = 1:numel(files)
    source = string(fileread( ...
        fullfile(files(fileIndex).folder, files(fileIndex).name)));
    verifyEmpty(testCase, regexp(source, ...
        """GuidePath_deg""\s*,|""StateCorridor""\s*,|" + ...
        """ReferencePath[^""]*""\s*,", ...
        "match"), sprintf('%s injects a route or search corridor.', ...
        files(fileIndex).name));
    direction = regexp(source, ...
        '"DirectionAngles_deg"\s*,\s*([^,\r\n]+)', ...
        "tokens");
    for directionIndex = 1:numel(direction)
        value = erase(string(direction{directionIndex}{1}), " ");
        verifyEqual(testCase, value, "0:45:315", ...
            sprintf('%s uses an asymmetric direction hint.', ...
            files(fileIndex).name));
    end
end
end

function testStopGoMovesImmediatelyAfterFinalGate(testCase)
set(0, "DefaultFigureVisible", "off");
result = example06StopGoGates();

verifyEqual(testCase, result.blockedSampleCount, 0);
verifyEqual(testCase, result.plan.angularPathLength_deg, 24, ...
    "AbsTol", 1e-9);
verifyLessThanOrEqual(testCase, ...
    result.diagnostics.firstSettledGoalTime_s, 37.5);
afterClearBeforeGoal = result.plan.time_s > 36 & ...
    result.plan.time_s < result.diagnostics.firstSettledGoalTime_s;
verifyFalse(testCase, any( ...
    result.plan.isWaiting(afterClearBeforeGoal)));
end

function testCrossyRoadTrafficRendezvous(testCase)
result = example14MovingRendezvousAndTrail(struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "MaximumDisplayedSlices", 12, ...
    "PauseSeconds", 0));

verifyTrue(testCase, result.plan.success);
verifyEqual(testCase, result.diagnostics.vehicleCount, 48);
verifyEqual(testCase, result.diagnostics.rowCount, 12);
verifyEqual(testCase, result.diagnostics.vehiclesPerRow, 4);
verifyEqual(testCase, result.diagnostics.endPacingRowIndices, 9:12);
verifyEqual(testCase, result.diagnostics.endPacingVehicleIndices, 33:48);
verifyEqual(testCase, result.diagnostics.crossedRowCount, 12);
verifyEqual(testCase, result.diagnostics.movingRowCount, 4);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.totalDirectionReversals, 16);
verifyEqual(testCase, result.diagnostics.overlapSampleCount, 0);
verifyGreaterThan(testCase, ...
    result.diagnostics.minimumVehicleClearance_deg, 0);
verifyGreaterThan(testCase, ...
    result.diagnostics.minimumWallClearance_deg, 0);
verifyEqual(testCase, ...
    result.diagnostics.centerCorridorWidth_deg, 0.9, "AbsTol", 1e-12);
verifyEqual(testCase, ...
    result.diagnostics.wallCorridorWidth_deg, 16, "AbsTol", 1e-12);
verifyEqual(testCase, ...
    result.diagnostics.minimumSameRowEdgeGap_deg, 0.9, ...
    "AbsTol", 1e-12);
verifyEqual(testCase, ...
    result.diagnostics.maximumSameRowEdgeGap_deg, 2.8, ...
    "AbsTol", 1e-12);
verifyGreaterThan(testCase, ...
    result.diagnostics.maximumSameRowEdgeGap_deg, ...
    3 * result.diagnostics.minimumSameRowEdgeGap_deg);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.trackingDuration_s, 8);
verifyGreaterThan(testCase, ...
    result.diagnostics.targetSpeedRange_deg_s, 0.2);
verifyTrue(testCase, result.plan.trackingTerminatedByObstacle);
verifyEqual(testCase, result.blockedSampleCount, 0);
verifyGreaterThanOrEqual(testCase, min(result.plan.position_deg(:, 1)), -1.5);
verifyLessThanOrEqual(testCase, max(result.plan.position_deg(:, 1)), 1.5);
end

function testSpinningRodSpiralUsesProtectedNotches(testCase)
result = example15SpinningRodSpiral(struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "MaximumDisplayedSlices", 10, ...
    "PauseSeconds", 0));

verifyTrue(testCase, result.plan.success);
verifyEqual(testCase, result.blockedSampleCount, 0);
verifyGreaterThanOrEqual(testCase, result.diagnostics.windingTurns, 0.8);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.waitingNotchCount, 1);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.protectedWaiting_s, 1);
verifyGreaterThan(testCase, ...
    result.diagnostics.rodAngularRate_deg_s, ...
    result.diagnostics.maximumBoresightAngularRate_deg_s);
verifyFalse(testCase, isfield(result.plan.options, "GuidePath_deg"));
verifyEmpty(testCase, result.plan.options.DirectionAngles_deg);
verifyTrue(testCase, ...
    all(isgraphics(result.view.NotchBoundaries2D, "line")));
verifyTrue(testCase, ...
    all(isgraphics(result.view.NotchColumns3D, "line")));
end
