function tests = testAzElWorkspacePyramid
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function testRasterMatchesPackedPolygonQueryAtCellCenters(testCase)
data = staticSquareData();
workspace = buildAzElTimeObstacleWorkspace(data);
gridSpec = struct( ...
    "AzimuthLimitsDeg", [-4 4], ...
    "ElevationLimitsDeg", [-4 4], ...
    "CellSizeDeg", 1, ...
    "TimeSeconds", data.time_s);
grid = rasterizeAzElTimeWorkspace( ...
    workspace, gridSpec, struct( ...
    "TimeMapping", "nearest", ...
    "OutOfRangeTime", "free"));
[azimuth, elevation] = meshgrid( ...
    grid.AzimuthCentersDeg, grid.ElevationCentersDeg);

for k = 1:numel(grid.TimeSeconds)
    expected = queryAzElTimeObstacle(workspace, ...
        azimuth, elevation, grid.TimeSeconds(k));
    verifyEqual(testCase, grid.Occupancy(:, :, k), expected);
end
end

function testCoarsePyramidReducesGlobalVoxelCount(testCase)
data = movingSquareData();
workspace = buildAzElTimeObstacleWorkspace(data);
pyramid = buildAzElTimeWorkspacePyramid( ...
    workspace, standardGridSpec(), struct( ...
    "CoarseCellSizeDeg", 2, ...
    "FineCellSizeDeg", 0.25, ...
    "MaximumCoarseTimeSamples", 11));

verifyEqual(testCase, pyramid.Format, ...
    "AzElTimeWorkspacePyramid");
verifyLessThanOrEqual(testCase, ...
    pyramid.Stats.CoarseTimeSampleCount, 11);
verifyEqual(testCase, ...
    pyramid.Stats.SourceTimeSampleCount, numel(data.time_s));
verifyGreaterThan(testCase, ...
    pyramid.Stats.RefinementCandidateVoxelCount, 0);
verifyGreaterThan(testCase, ...
    pyramid.Stats.UniformFineToCoarseRatio, 100);
verifyEmpty(testCase, pyramid.FinePatches);
end

function testFinePatchOverridesOnlyItsRegion(testCase)
data = movingSquareData();
workspace = buildAzElTimeObstacleWorkspace(data);
pyramid = buildAzElTimeWorkspacePyramid( ...
    workspace, standardGridSpec(), struct( ...
    "CoarseCellSizeDeg", 2, ...
    "FineCellSizeDeg", 0.5, ...
    "MaximumCoarseTimeSamples", 11));
region = struct( ...
    "AzimuthLimitsDeg", [-4 4], ...
    "ElevationLimitsDeg", [-4 4], ...
    "TimeLimitsSeconds", [20 80]);
[pyramid, patch] = refineAzElTimeWorkspacePyramid( ...
    pyramid, workspace, region, struct( ...
    "MaximumTimeSamples", 13));

verifyEqual(testCase, pyramid.Stats.FinePatchCount, 1);
verifyLessThanOrEqual(testCase, patch.UsedTimeSampleCount, 13);
verifyTrue(testCase, patch.TimeWasDecimated);
verifyGreaterThan(testCase, ...
    pyramid.Stats.FinePatchVoxelCount, 0);

[occupied, info] = queryAzElTimeWorkspacePyramid( ...
    pyramid, 0, 0, 50);
verifyTrue(testCase, occupied);
verifyFalse(testCase, info.NeedsRefinement);
verifyEqual(testCase, info.Level, "fine-1");
verifyEqual(testCase, squeeze(info.CellSizeDeg), [0.5; 0.5]);

[outsideOccupied, outsideInfo] = queryAzElTimeWorkspacePyramid( ...
    pyramid, -9, -7, 50);
verifyFalse(testCase, outsideOccupied);
verifyEqual(testCase, outsideInfo.Level, "coarse");

firstPage = pyramid.RefinementCandidateMask(:, :, 1);
candidateLinear = find(firstPage, 1);
verifyNotEmpty(testCase, candidateLinear);
[row, column] = ind2sub(size(firstPage), candidateLinear);
[candidateOccupied, candidateInfo] = ...
    queryAzElTimeWorkspacePyramid(pyramid, ...
    pyramid.Coarse.AzimuthCentersDeg(column), ...
    pyramid.Coarse.ElevationCentersDeg(row), ...
    pyramid.Coarse.TimeSeconds(1));
verifyTrue(testCase, candidateInfo.NeedsRefinement);
verifyTrue(testCase, candidateOccupied);
end

function testFinePatchMemoryGuard(testCase)
data = movingSquareData();
workspace = buildAzElTimeObstacleWorkspace(data);
pyramid = buildAzElTimeWorkspacePyramid( ...
    workspace, standardGridSpec());
region = struct( ...
    "AzimuthLimitsDeg", [-10 10], ...
    "ElevationLimitsDeg", [-8 8], ...
    "TimeLimitsSeconds", [0 100]);

verifyError(testCase, @() refineAzElTimeWorkspacePyramid( ...
    pyramid, workspace, region, struct( ...
    "CellSizeDeg", 0.25, ...
    "MaximumTimeSamples", 50, ...
    "MaximumFineVoxels", 10)), ...
    "refineAzElTimeWorkspacePyramid:FineGridTooLarge");
end

function data = staticSquareData()
time_s = (0:2).';
azimuth = repmat({[-1.2; 1.2; 1.2; -1.2; -1.2]}, ...
    numel(time_s), 1);
elevation = repmat({[-1.2; -1.2; 1.2; 1.2; -1.2]}, ...
    numel(time_s), 1);
data = makeAzElObstacleData( ...
    "Static square", time_s, azimuth, elevation);
end

function data = movingSquareData()
time_s = (0:100).';
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    center = -3 + 6 * time_s(k) / time_s(end);
    azimuth{k} = center + [-1; 1; 1; -1; -1];
    elevation{k} = [-1; -1; 1; 1; -1];
end
data = makeAzElObstacleData( ...
    "Moving square", time_s, azimuth, elevation);
end

function gridSpec = standardGridSpec()
gridSpec = struct( ...
    "AzimuthLimitsDeg", [-10 10], ...
    "ElevationLimitsDeg", [-8 8], ...
    "TimeLimitsSeconds", [0 100]);
end
