function tests = testRandomBlinkingChessboard
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function teardown(~)
close all force;
end

function testExplicitSeedReproducesCompleteCase(testCase)
first = makeRandomBlinkingChessboardGauntlet(24681357);
second = makeRandomBlinkingChessboardGauntlet(24681357);

verifyEqual(testCase, first.seed, second.seed);
verifyEqual(testCase, ...
    first.geometry.cellOpen, second.geometry.cellOpen);
verifyEqual(testCase, ...
    first.target.position_deg, second.target.position_deg);
verifyEqual(testCase, ...
    first.startState.position_deg, second.startState.position_deg);
end

function testImplicitSeedChangesFieldAndTarget(testCase)
first = makeRandomBlinkingChessboardGauntlet();
pause(0.01);
second = makeRandomBlinkingChessboardGauntlet();

verifyNotEqual(testCase, first.seed, second.seed);
sameField = isequal( ...
    first.geometry.cellOpen, second.geometry.cellOpen);
sameTarget = isequal( ...
    first.target.position_deg, second.target.position_deg);
verifyFalse(testCase, sameField && sameTarget);
end

function testEveryCellBlinksAndTargetMayCrossClosedCells(testCase)
problem = makeRandomBlinkingChessboardGauntlet();
cellOpen = problem.geometry.cellOpen;

verifyTrue(testCase, all(any(cellOpen, 1)));
verifyTrue(testCase, all(any(~cellOpen, 1)));
verifyGreaterThanOrEqual(testCase, ...
    numel(problem.geometry.switchTimes_s), 5);
[~, startCell] = min(sum(( ...
    problem.geometry.cellCenters_deg - ...
    problem.startState.position_deg).^2, 2));
generation = problem.geometry.generationOptions;
firstTransferWindow_s = problem.geometry.switchTimes_s(1) - ...
    generation.OverlapDuration_s + generation.TransitionJitter_s;
initialWindow = problem.target.time_s <= firstTransferWindow_s + 1e-9;
verifyTrue(testCase, all(cellOpen(initialWindow, startCell)));
obstacleField = buildAzElTimeObstacleField(problem.azElData);
targetBlocked = queryAzElTimeObstacle(obstacleField, ...
    problem.target.position_deg(:, 1), ...
    problem.target.position_deg(:, 2), problem.target.time_s, ...
    struct("SafetyMarginDeg", problem.options.SafetyMargin_deg));
verifyGreaterThan(testCase, nnz(targetBlocked), 0);
end

function testFreshUnfilteredRandomBatch(testCase)
report = runRandomBlinkingChessboardStressTest(5);

verifyEqual(testCase, numel(report.cases), 5);
verifyEqual(testCase, numel(unique(report.caseSeeds)), 5);
verifyGreaterThanOrEqual(testCase, report.successRate, 0.8, ...
    sprintf('Replay randomized root seed %u.', ...
    uint32(report.rootSeed)));
successful = report.cases([report.cases.success]);
verifyGreaterThanOrEqual(testCase, ...
    [successful.cellTransferCount], ...
    2 * ones(1, numel(successful)));
verifyEqual(testCase, ...
    [successful.blockedSampleCount], ...
    zeros(1, numel(successful)));
verifyGreaterThan(testCase, ...
    [successful.blockedTargetSampleCount], ...
    zeros(1, numel(successful)));
end

function testMovingTargetAppearsInBothAnimationViews(testCase)
time_s = (0:2).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", [-1 0; 0 0; 1 0], ...
    "obstacleField", buildAzElTimeObstacleField(data), ...
    "limits", struct( ...
    "azimuth_deg", [-2 2], ...
    "elevation_deg", [-2 2]));
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [1 1; 0 1; -1 1]);
handles = animateAzElAvoidancePlan(data, plan, struct( ...
    "ViewMode", "combined", ...
    "MovingTarget", target, ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 2, ...
    "PauseSeconds", 0));

verifyTrue(testCase, ...
    isgraphics(handles.TwoDimensional.CurrentTarget, "line"));
verifyTrue(testCase, ...
    isgraphics(handles.ThreeDimensional.CurrentTarget, "line"));
verifyEqual(testCase, ...
    handles.TwoDimensional.CurrentTarget.XData, -1, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, ...
    handles.ThreeDimensional.CurrentTarget.ZData, 2, ...
    "AbsTol", 1e-9);
end
