function tests = testStandaloneExampleAnimations
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function teardown(~)
close all force;
end

function testExampleNumbersAreConsecutiveAndCallable(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
examples = dir(fullfile(folder, "example*.m"));
names = sort(string({examples.name}));
numbers = zeros(numel(names), 1);
for k = 1:numel(names)
    token = regexp(names(k), "^example(\d\d).+\.m$", ...
        "tokens", "once");
    verifyNotEmpty(testCase, token, ...
        sprintf('%s does not use the exampleNNName convention.', names(k)));
    numbers(k) = str2double(token{1});
    functionName = erase(names(k), ".m");
    verifyNotEmpty(testCase, which(functionName), ...
        sprintf('%s is not callable.', functionName));
end
verifyEqual(testCase, numbers, (1:numel(names)).');
end

function testEveryExampleUsesCommonAnimationPath(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
examples = dir(fullfile(folder, "example*.m"));
verifyGreaterThan(testCase, numel(examples), 0);
for k = 1:numel(examples)
    source = string(fileread(fullfile(folder, examples(k).name)));
    usesAnimator = contains(source, "animateAzElAvoidancePlan");
    usesGauntletRunner = contains(source, "runAzElGauntletCase");
    verifyTrue(testCase, usesAnimator || usesGauntletRunner, ...
        sprintf('%s has no 2-D/3-D animation path.', examples(k).name));
end
end

function testEveryExampleUsesUnifiedAdaptiveAStar(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
examples = dir(fullfile(folder, "example*.m"));
for k = 1:numel(examples)
    source = string(fileread( ...
        fullfile(examples(k).folder, examples(k).name)));
    usesPlanner = contains(source, "planAzElAdaptiveAStar");
    usesRunner = contains(source, "runAzElGauntletCase");
    usesInterceptWrapper = ...
        contains(source, "planAzElMovingTargetIntercept");
    verifyTrue(testCase, ...
        usesPlanner || usesRunner || usesInterceptWrapper, ...
        sprintf('%s bypasses unified adaptive A*.', examples(k).name));
    verifyEmpty(testCase, regexp(source, ...
        "planAzElAutonomousCorridor", ...
        "match"), sprintf('%s calls a different planner.', ...
        examples(k).name));
end
end

function testDefaultOptionsForceCombinedView(testCase)
options = defaultAzElAnimationOptions(struct( ...
    "ViewMode", "2d", ...
    "FigureVisible", "off"));

verifyEqual(testCase, options.ViewMode, "combined");
end

function testCombinedAnimatorCreatesBothAxes(testCase)
time_s = (0:2).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", [-1 0; 0 0; 1 0], ...
    "workspace", buildAzElTimeObstacleWorkspace(data), ...
    "limits", struct( ...
    "azimuth_deg", [-2 2], ...
    "elevation_deg", [-1 1]));
handles = animateAzElAvoidancePlan(data, plan, ...
    defaultAzElAnimationOptions(struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "PauseSeconds", 0)));

verifyTrue(testCase, isgraphics(handles.AzElAxes, "axes"));
verifyTrue(testCase, isgraphics(handles.WorkspaceAxes, "axes"));
verifyEqual(testCase, handles.Options.ViewMode, "combined");
end

function testAnimatorShowsLatticeContenderAndSelectedRoute(testCase)
time_s = (0:2).';
empty = repmat({zeros(0, 1)}, numel(time_s), 1);
data = makeAzElObstacleData("Empty", time_s, empty, empty);
attemptTemplate = struct( ...
    "GridStep_deg", 2, ...
    "PrimitiveRadii_deg", [2 4], ...
    "Success", true, ...
    "Message", "valid", ...
    "ExpandedNodeCount", 1, ...
    "GeneratedNodeCount", 2, ...
    "SearchElapsed_s", 0.1, ...
    "TerminationReason", "goalReached", ...
    "ObjectiveCost", 3, ...
    "CandidateTime_s", time_s, ...
    "CandidatePosition_deg", [-1 0; 0 0.5; 1 0], ...
    "Selected", false);
selectedAttempt = attemptTemplate;
selectedAttempt.GridStep_deg = 1;
selectedAttempt.ObjectiveCost = 2;
selectedAttempt.CandidatePosition_deg = [-1 0; 0 0; 1 0];
selectedAttempt.Selected = true;
plan = struct( ...
    "success", true, ...
    "time_s", time_s, ...
    "position_deg", selectedAttempt.CandidatePosition_deg, ...
    "workspace", buildAzElTimeObstacleWorkspace(data), ...
    "limits", struct( ...
        "azimuth_deg", [-2 2], ...
        "elevation_deg", [-1 1]), ...
    "selectedGridStep_deg", 1, ...
    "resolutionAttempts", [attemptTemplate; selectedAttempt], ...
    "safeIntervalSearch", struct("EventTimes_s", time_s));

handles = animateAzElAvoidancePlan(data, plan, struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "PauseSeconds", 0));

verifyTrue(testCase, ...
    isgraphics(handles.TwoDimensional.Discretization, "line"));
verifyEqual(testCase, ...
    numel(handles.TwoDimensional.CandidateRoutes), 1);
verifyTrue(testCase, ...
    isgraphics(handles.TwoDimensional.SelectedRoute, "line"));
verifyTrue(testCase, ...
    isgraphics(handles.ThreeDimensional.Discretization, "line"));
verifyEqual(testCase, ...
    numel(handles.ThreeDimensional.CandidateRoutes), 1);
verifyTrue(testCase, ...
    isgraphics(handles.ThreeDimensional.SelectedRoute, "line"));
end

function testGauntletsDoNotInjectRoutes(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
folder = fullfile(root, "examples");
supportFolder = fullfile(folder, "support");
files = [ ...
    dir(fullfile(folder, "example*.m")); ...
    dir(fullfile(supportFolder, "make*Gauntlet.m"))];
[~, uniqueIndex] = unique({files.name}, "stable");
files = files(uniqueIndex);
for k = 1:numel(files)
    source = string(fileread(fullfile(files(k).folder, files(k).name)));
    verifyEmpty(testCase, regexp(source, ...
        """GuidePath_deg""\s*,|""StateCorridor""\s*,|" + ...
        """ReferencePath[^""]*""\s*,|@planAzElGuidedRoute", ...
        "match"), sprintf('%s injects a route or search corridor.', ...
        files(k).name));
    direction = regexp(source, ...
        '"DirectionAngles_deg"\s*,\s*([^,\r\n]+)', ...
        "tokens");
    for directionIndex = 1:numel(direction)
        value = erase(string(direction{directionIndex}{1}), " ");
        verifyEqual(testCase, value, "0:45:315", ...
            sprintf('%s uses an asymmetric direction hint.', ...
            files(k).name));
    end
end
end

function testStopGoMovesImmediatelyAfterFinalGate(testCase)
set(0, "DefaultFigureVisible", "off");
result = example06StopGoGates();

verifyEqual(testCase, result.blockedSampleCount, 0);
verifyEqual(testCase, result.plan.angularPathLength_deg, 24, ...
    "AbsTol", 1e-9);
verifyLessThanOrEqual(testCase, ...
    result.diagnostics.firstSettledGoalTime_s, 37.5);
afterClearBeforeGoal = result.plan.time_s > 36 & ...
    result.plan.time_s < result.diagnostics.firstSettledGoalTime_s;
verifyFalse(testCase, any( ...
    result.plan.isWaiting(afterClearBeforeGoal)));
end

function testTwelveVehicleTrafficRendezvous(testCase)
result = example14MovingRendezvousAndTrail(struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "MaximumDisplayedSlices", 12, ...
    "PauseSeconds", 0));

verifyTrue(testCase, result.plan.success);
verifyEqual(testCase, result.diagnostics.vehicleCount, 12);
verifyEqual(testCase, result.diagnostics.rowCount, 4);
verifyEqual(testCase, result.diagnostics.vehiclesPerRow, 3);
verifyEqual(testCase, result.diagnostics.endPacingVehicleIndices, 9:12);
verifyEqual(testCase, result.diagnostics.crossedRowCount, 4);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.totalDirectionReversals, 12);
verifyGreaterThanOrEqual(testCase, ...
    result.diagnostics.trackingDuration_s, 8);
verifyGreaterThan(testCase, ...
    result.diagnostics.targetSpeedRange_deg_s, 0.2);
verifyTrue(testCase, result.plan.trackingTerminatedByObstacle);
verifyEqual(testCase, result.blockedSampleCount, 0);
end
