function tests = testAzElPlannerAgent
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
set(0, "DefaultFigureVisible", "off");
end

function teardownOnce(~)
close all force;
end

function testBundledAgentHasAuditableContract(testCase)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
artifactFile = fullfile(packageRoot, ...
    "models", "azElPlannerAgent.mat");
verifyTrue(testCase, isfile(artifactFile));
savedData = load(artifactFile, "agentArtifact");
agentArtifact = savedData.agentArtifact;

verifyEqual(testCase, ...
    agentArtifact.Format, "AzElPlannerSelectionAgent");
verifyEqual(testCase, agentArtifact.Version, 3);
verifyTrue(testCase, agentArtifact.ExactValidationRequired);
verifyEqual(testCase, numel(agentArtifact.Profiles), 10);
verifyEqual(testCase, ...
    string({agentArtifact.Profiles.Name}), ...
    ["fast" "balanced" "precise" "topologyFine" ...
    "dynamicSparseSweep" "dynamicLocalMotion" ...
    "dynamicTiming" "dynamicPursuit" "dynamicDense" ...
    "dynamicLongHorizon"]);
verifyEqual(testCase, ...
    string({agentArtifact.Profiles.Mode}), ...
    ["static" "static" "static" "static" ...
    "dynamic" "dynamic" "dynamic" "dynamic" "dynamic" "dynamic"]);
verifyGreaterThanOrEqual(testCase, ...
    agentArtifact.TrainingReport.TrainingAccuracy, 0.8);
verifyEqual(testCase, ...
    agentArtifact.TrainingReport.ScenarioCount, 36);
verifyEqual(testCase, ...
    agentArtifact.TrainingReport.ValidationScenarioCount, 18);
verifyGreaterThanOrEqual(testCase, ...
    agentArtifact.TrainingReport.ValidationAccuracy, 0.9);
verifyEqual(testCase, ...
    agentArtifact.TrainingReport.NearBestPathRatio, 1.05);
verifyEqual(testCase, ...
    unique(agentArtifact.TrainingReport.SelectedProfileNames), ...
    ["balanced"; "fast"; "precise"]);
end

function testDeploymentReturnsOnlyExactValidatedRoute(testCase)
[azElData, initialState, goalState, axisLimits] = narrowPassageProblem();
plan = planAzElWithAgent( ...
    azElData, initialState, goalState, axisLimits, struct( ...
        "AgentPrintDiagnostics", false, ...
        "AgentMaxSearchTime_s", 20));

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.exactCollisionValidated);
verifyNotEmpty(testCase, plan.agent.Attempts);
verifyEqual(testCase, ...
    plan.agent.SelectedProfileName, ...
    plan.agent.Attempts(end).ProfileName);
verifyTrue(testCase, ...
    plan.agent.Attempts(end).ExactCollisionValidated);
verifyEqual(testCase, plan.agent.ProblemMode, "static");
occupied = queryAzElTimeObstacle( ...
    plan.workspace, plan.position_deg(:, 1), ...
    plan.position_deg(:, 2), plan.time_s);
verifyFalse(testCase, any(occupied));
end

function testTrainerProducesReloadableAgent(testCase)
temporaryArtifactFile = string(tempname) + ".mat";
cleanup = onCleanup(@() deleteTemporaryArtifact( ...
    temporaryArtifactFile));
agentArtifact = trainAzElPlannerAgent( ...
    temporaryArtifactFile, struct( ...
        "CurriculumScenariosPerClass", 2, ...
        "ValidationScenariosPerClass", 2, ...
        "RandomSeed", 31, ...
        "Verbose", false));
savedData = load(temporaryArtifactFile, "agentArtifact");

verifyEqual(testCase, ...
    savedData.agentArtifact.Format, ...
    "AzElPlannerSelectionAgent");
verifyEqual(testCase, ...
    savedData.agentArtifact.FeatureNames, ...
    agentArtifact.FeatureNames);
verifyEqual(testCase, ...
    savedData.agentArtifact.TrainingReport.ScenarioCount, 6);
verifyEqual(testCase, ...
    savedData.agentArtifact.TrainingReport.ValidationScenarioCount, 6);
verifyGreaterThanOrEqual(testCase, ...
    savedData.agentArtifact.TrainingReport.TrainingAccuracy, 0.8);
end

function testRandomScenarioGeneratorIsReproducible(testCase)
families = [ ...
    "wall", "slalom", "trap", "movingGates", "rotatingRods"];
for familyIndex = 1:numel(families)
    scenarioSeed = 81000 + familyIndex;
    firstProblem = makeRandomAzElPlannerScenario( ...
        scenarioSeed, families(familyIndex));
    secondProblem = makeRandomAzElPlannerScenario( ...
        scenarioSeed, families(familyIndex));
    verifyEqual(testCase, firstProblem, secondProblem);
end
end

function testBundledRandomizedValidationEvidence(testCase)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
resultFile = fullfile(packageRoot, "benchmarks", "results", ...
    "randomizedAgentValidation.mat");
verifyTrue(testCase, isfile(resultFile));
savedResult = load(resultFile, "report");
report = savedResult.report;

verifyEqual(testCase, ...
    report.Format, "RandomizedAzElPlannerAgentValidation");
verifyEqual(testCase, report.RootSeed, 20260802);
verifyEqual(testCase, report.ScenarioCount, 100);
verifyEqual(testCase, report.GenerationFailureCount, 0);
verifyEqual(testCase, report.AgentSuccessCount, 100);
verifyEqual(testCase, report.OverallSuccessRate, 1);
verifyEqual(testCase, report.ConditionalSuccessRate, 1);
verifyEqual(testCase, report.UnsafeAcceptanceCount, 0);
verifyLessThanOrEqual(testCase, report.PathRatio95, 1.10);
verifyTrue(testCase, report.AcceptancePassed);
verifyEqual(testCase, ...
    report.FamilySummary.ScenarioCount, 20 * ones(5, 1));
end

function testMovingWorkspaceUsesDynamicPolicy(testCase)
time_s = (0:0.5:12).';
centerAzimuth_deg = -2 + 4 * time_s / time_s(end);
azimuthByTime = cell(numel(time_s), 1);
elevationByTime = cell(numel(time_s), 1);
for sampleIndex = 1:numel(time_s)
    center = centerAzimuth_deg(sampleIndex);
    azimuthByTime{sampleIndex} = [ ...
        center - 0.5; center + 0.5; center + 0.5; ...
        center - 0.5; center - 0.5];
    elevationByTime{sampleIndex} = [-3; -3; -2; -2; -3];
end
azElData = makeAzElObstacleData( ...
    "Moving policy test", time_s, ...
    azimuthByTime, elevationByTime);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-5 2], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 12, ...
    "position_deg", [5 2], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
axisLimits = struct( ...
    "azimuth_deg", [-6 6], ...
    "elevation_deg", [-4 4], ...
    "maxVelocity_deg_s", [3 3], ...
    "maxAcceleration_deg_s2", [3 3]);
plan = planAzElWithAgent( ...
    azElData, initialState, goalState, axisLimits, struct( ...
        "AgentFallback", false, ...
        "AgentMaxSearchTime_s", 10, ...
        "AgentPrintDiagnostics", false));

verifyEqual(testCase, plan.agent.ProblemMode, "dynamic");
verifyEqual(testCase, ...
    plan.agent.SelectionSource, "dynamicModePolicy");
verifyEqual(testCase, ...
    plan.agent.RankedProfileNames(1), "dynamicSparseSweep");
verifyEqual(testCase, ...
    plan.agent.FeatureDiagnostics.DynamicObstacleCount, 1);
end

function [azElData, initialState, goalState, axisLimits] = narrowPassageProblem()
% Shared by deployment checks so every assertion sees identical geometry.
sampleTime_s = (0:1:20).';
wallAzimuth_deg = [ ...
    -3.4; 2.4; 2.4; -3.4; -3.4; NaN; ...
    -3.4; 2.4; 2.4; -3.4; -3.4];
wallElevation_deg = [ ...
    -10; -10; -3.7; -3.7; -10; NaN; ...
    -2.3; -2.3; 10; 10; -2.3];
azElData = makeAzElObstacleData( ...
    "Agent test wall", sampleTime_s, ...
    repmat({wallAzimuth_deg}, numel(sampleTime_s), 1), ...
    repmat({wallElevation_deg}, numel(sampleTime_s), 1));
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
axisLimits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [5 5]);
end

function deleteTemporaryArtifact(temporaryArtifactFile)
% onCleanup reaches this from both successful and failed training tests.
if isfile(temporaryArtifactFile)
    delete(temporaryArtifactFile);
end
end
