function tests = testAzElMovingTargetIntercept
%% Section 0: Header & Readme
% SYNTAX
%   results = runtests("testAzElMovingTargetIntercept.m")
%**************************************************************************
% PURPOSE
%   - Verify nonzero terminal capture and post-intercept tracking behavior.
%**************************************************************************
% INPUTS
%   - None; MATLAB supplies local function-test fixtures.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Local tests discovered by functiontests.
%**************************************************************************
% UNITS
%   - Test quantities follow the planner's degree/second conventions.
%% Section 1: Register Local Tests
tests = functiontests(localfunctions);
end

function setupOnce(~)
packageRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(packageRoot));
end

function testMatchesNonzeroVelocityAndTracksToRequestedEnd(testCase)
[data, startState, target, limits, options] = ...
    constantVelocityProblem(false);
options.TrackingEndTime_s = 24;
plan = planAzElMovingTargetIntercept( ...
    data, startState, target, limits, options);

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.trackingSuccess);
verifyEqual(testCase, ...
    plan.trackingTerminationReason, "trackingWindowComplete");
verifyEqual(testCase, plan.trackingEndTime_s, 24, "AbsTol", 1e-9);
verifyEqual(testCase, ...
    plan.velocity_deg_s(end, :), [0.3 0], "AbsTol", 1e-9);
verifyLessThanOrEqual(testCase, ...
    plan.catchVelocityError_deg_s, ...
    options.CatchVelocityTolerance_deg_s);
verifyPlanIsFree(testCase, plan, options);
end

function testTrackingStopsBeforeObstacle(testCase)
[data, startState, target, limits, options] = ...
    constantVelocityProblem(true);
plan = planAzElMovingTargetIntercept( ...
    data, startState, target, limits, options);

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.trackingSuccess);
verifyTrue(testCase, plan.trackingTerminatedByObstacle);
verifyEqual(testCase, plan.trackingTerminationReason, "obstacle");
verifyLessThan(testCase, plan.trackingEndTime_s, target.time_s(end));
verifyPlanIsFree(testCase, plan, options);
end

function [data, startState, target, limits, options] = ...
        constantVelocityProblem(includeBlocker)
time_s = (0:0.5:30).';
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [-2 + 0.3 * time_s, 2 + 0 * time_s], ...
    "velocity_deg_s", repmat([0.3 0], numel(time_s), 1), ...
    "acceleration_deg_s2", zeros(numel(time_s), 2));
if includeBlocker
    azimuth = [5; 6; 6; 5; 5];
    elevation = [1.5; 1.5; 2.5; 2.5; 1.5];
else
    azimuth = zeros(0, 1);
    elevation = zeros(0, 1);
end
data = makeAzElObstacleData( ...
    "Tracking blocker", time_s, azimuth, elevation);
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-8 -3], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-20 20], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "EarliestInterceptTime_s", 10, ...
    "LatestInterceptTime_s", 14, ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 3, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "MatchTargetVelocity", true, ...
    "MatchTargetAcceleration", true, ...
    "ContinueTrackingAfterIntercept", true, ...
    "TrackingEndTime_s", 30, ...
    "TrackingSampleTime_s", 0.2, ...
    "CatchTolerance_deg", 0.05, ...
    "CatchVelocityTolerance_deg_s", 0.01, ...
    "CatchAccelerationTolerance_deg_s2", 0.01, ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", [2 1], ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.05, ...
    "SafetyMargin_deg", 0.1, ...
    "MaxSearchTime_s", 8);
end

function verifyPlanIsFree(testCase, plan, options)
blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
verifyFalse(testCase, any(blocked));
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.velocity_deg_s), [], 1), ...
    plan.limits.maxVelocity_deg_s + 1e-8);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.acceleration_deg_s2), [], 1), ...
    plan.limits.maxAcceleration_deg_s2 + 1e-8);
end
