function tests = testAzElPlanningSummary
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function teardown(~)
close all force;
end

function testSummaryBuildsDijkstraLatticeAndFinalSelection(testCase)
[azElData, plan] = dijkstraFixture();
handles = animateAzElAvoidancePlan(azElData, plan, struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 3, ...
    "PauseSeconds", 0, ...
    "ShowPlanningSummary", true));

verifyEqual(testCase, handles.Options.DiscretizationMode, "build");
verifyTrue(testCase, isgraphics(handles.SummaryTitle));
verifyEqual(testCase, handles.PlanningSummary.SearchType, ...
    "Dijkstra lattice");
verifyEqual(testCase, handles.PlanningSummary.ValidContenderCount, 1);
verifyEqual(testCase, handles.PlanningSummary.PackedSliceCount, 3);
verifyNotEmpty(testCase, handles.TwoDimensional.Discretization);
layerStatus = get( ...
    handles.TwoDimensional.Discretization(1), "UserData");
verifyTrue(testCase, layerStatus.Complete);
verifyGreaterThan(testCase, layerStatus.TotalItemCount, 0);
verifyEqual(testCase, ...
    string(get(handles.TwoDimensional.SelectedRoute, "Visible")), "on");
verifyTrue(testCase, contains(string(handles.SummaryTitle.String), ...
    "Selected:"));
end

function testLegacySwitchTurnsEveryDiscretizationLayerOff(testCase)
[azElData, plan] = dijkstraFixture();
handles = animateAzElAvoidancePlan(azElData, plan, struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 1, ...
    "PauseSeconds", 0, ...
    "ShowPlanningSummary", true, ...
    "ShowDiscretization", false));

verifyEqual(testCase, handles.Options.DiscretizationMode, "off");
verifyEmpty(testCase, handles.TwoDimensional.Discretization);
verifyEmpty(testCase, handles.ThreeDimensional.Discretization);
end

function testSummaryDisplaysBothRrtTreesInTwoAndThreeDimensions(testCase)
time_s = (0:4).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = makeAzElObstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
forwardTree = struct( ...
    "Position_deg", [-1 0; -0.5 0.5; 0 0], ...
    "Time_s", [0; 1; 2], ...
    "ParentIndex", uint32([0; 1; 2]), ...
    "CreationIteration", [0; 1; 3]);
backwardTree = struct( ...
    "Position_deg", [1 0; 0.5 -0.5; 0 0], ...
    "Time_s", [4; 3; 2], ...
    "ParentIndex", uint32([0; 1; 2]), ...
    "CreationIteration", [0; 2; 4]);
plan = struct( ...
    "success", true, ...
    "method", "bidirectionalKinodynamicRRTStar", ...
    "time_s", time_s, ...
    "position_deg", [-1 0; -0.5 0.2; 0 0; 0.5 -0.2; 1 0], ...
    "obstacleField", buildAzElTimeObstacleField(azElData), ...
    "limits", struct( ...
    "azimuth_deg", [-2 2], ...
    "elevation_deg", [-1 1]), ...
    "forwardTree", forwardTree, ...
    "backwardTree", backwardTree);
handles = animateAzElAvoidancePlan(azElData, plan, struct( ...
    "FigureVisible", "off", ...
    "MaximumAnimationFrames", 5, ...
    "PauseSeconds", 0, ...
    "ShowPlanningSummary", true));

verifyEqual(testCase, handles.PlanningSummary.SearchType, ...
    "bidirectional RRT*");
verifyEqual(testCase, numel(handles.TwoDimensional.Discretization), 2);
verifyEqual(testCase, numel(handles.ThreeDimensional.Discretization), 2);
for treeIndex = 1:2
    twoDimensionalStatus = get( ...
        handles.TwoDimensional.Discretization(treeIndex), "UserData");
    threeDimensionalStatus = get( ...
        handles.ThreeDimensional.Discretization(treeIndex), "UserData");
    verifyTrue(testCase, twoDimensionalStatus.Complete);
    verifyTrue(testCase, threeDimensionalStatus.Complete);
    verifyEqual(testCase, twoDimensionalStatus.TotalItemCount, 2);
    verifyEqual(testCase, threeDimensionalStatus.TotalItemCount, 2);
    verifyNotEmpty(testCase, get( ...
        handles.ThreeDimensional.Discretization(treeIndex), "ZData"));
end
end

function [azElData, plan] = dijkstraFixture()
% Three tests share this minimal successful plan; one constructor keeps its
% candidate metadata and lattice contract synchronized.
time_s = (0:2).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = makeAzElObstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
alternateAttempt = struct( ...
    "Success", true, ...
    "Selected", false, ...
    "CandidateTime_s", time_s, ...
    "CandidatePosition_deg", [-1 0; 0 0.5; 1 0]);
selectedAttempt = alternateAttempt;
selectedAttempt.Selected = true;
selectedAttempt.CandidatePosition_deg = [-1 0; 0 0; 1 0];
plan = struct( ...
    "success", true, ...
    "method", "progressiveSafeIntervalDijkstra", ...
    "time_s", time_s, ...
    "position_deg", selectedAttempt.CandidatePosition_deg, ...
    "obstacleField", buildAzElTimeObstacleField(azElData), ...
    "limits", struct( ...
    "azimuth_deg", [-2 2], ...
    "elevation_deg", [-1 1]), ...
    "selectedGridStep_deg", 1, ...
    "resolutionAttempts", [alternateAttempt; selectedAttempt], ...
    "safeIntervalSearch", struct("EventTimes_s", time_s));
end
