function tests = testAzElBidirectionalKinodynamicRRTStar
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function testDirectTrajectoryCertifiesAngularLowerBound(testCase)
time_s = (0:10).';
emptyBoundary = repmat({zeros(0, 1)}, numel(time_s), 1);
azElData = makeAzElObstacleData( ...
    "Empty", time_s, emptyBoundary, emptyBoundary);
initialState = restState(0, [-2 1]);
goalState = restState(10, [3 4]);
limits = standardLimits([-10 10], [-10 10]);

plan = planAzElBidirectionalKinodynamicRRTStar( ...
    azElData, initialState, goalState, limits, struct( ...
    "RandomSeed", 11, ...
    "MaxSearchTime_s", 2));

verifyTrue(testCase, plan.success);
verifyTrue(testCase, plan.optimalGlobally);
verifyFalse(testCase, isfield(plan.options, "GoalBias"));
verifyEqual(testCase, plan.angularPathLength_deg, hypot(5, 3), ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.blockedValidationSampleCount, 0);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.velocity_deg_s), [], 1), ...
    limits.maxVelocity_deg_s + 1e-9);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.acceleration_deg_s2), [], 1), ...
    limits.maxAcceleration_deg_s2 + 1e-9);
end

function testBidirectionalTreesDetourAroundStaticBlock(testCase)
time_s = (0:40).';
azElData = makeAzElObstacleData( ...
    "Central blocker", time_s, ...
    [-1; 1; 1; -1; -1], [43; 43; 47; 47; 43]);
initialState = restState(0, [-6 45]);
goalState = restState(40, [6 45]);
limits = standardLimits([-10 10], [40 50]);
options = struct( ...
    "SafetyMargin_deg", 0.1, ...
    "RandomSeed", 7, ...
    "StepSize_deg", 3, ...
    "RewireRadius_deg", 5, ...
    "ConnectionRadius_deg", 7, ...
    "MaxIterations", 3000, ...
    "IterationsAfterFirstSolution", 100, ...
    "MaxSearchTime_s", 12);

plan = planAzElBidirectionalKinodynamicRRTStar( ...
    azElData, initialState, goalState, limits, options);

verifyTrue(testCase, plan.success, plan.message);
verifyGreaterThan(testCase, plan.forwardTree.Count, 1);
verifyGreaterThan(testCase, plan.backwardTree.Count, 1);
verifyGreaterThan(testCase, plan.angularPathLength_deg, 12);
verifyEqual(testCase, plan.blockedValidationSampleCount, 0);
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct("SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
verifyFalse(testCase, any(blocked));
end

function testRrtDoesNotDelegateOrAcceptRouteGuidance(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
rrtSource = string(fileread(fullfile( ...
    root, "planAzElBidirectionalKinodynamicRRTStar.m")));
dijkstraSource = string(fileread(fullfile(root, "planAzElDijkstra.m")));

verifyFalse(testCase, contains(rrtSource, "planAzElDijkstra"));
verifyFalse(testCase, contains( ...
    dijkstraSource, "planAzElBidirectionalKinodynamicRRTStar"));
for forbiddenInput = [ ...
        """GuidePath_deg""", """StateCorridor""", ...
        """DirectionAngles_deg""", """GoalBias"""]
    verifyFalse(testCase, contains(rrtSource, forbiddenInput));
end
end

function state = restState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function limits = standardLimits(azimuth_deg, elevation_deg)
limits = struct( ...
    "azimuth_deg", azimuth_deg, ...
    "elevation_deg", elevation_deg, ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
end
