function tests = testAzElSafeIntervalPlanner
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(root));
end

function [azElData, initialState, goalState, limits, options] = ...
        standardProblem()
time_s = (0:10).';
azElData = makeAzElObstacleData("Empty", time_s, zeros(0, 1), zeros(0, 1));
initialState = boundaryState(0, [-4 0]);
goalState = boundaryState(10, [4 0]);
limits = struct( ...
    "azimuth_deg", [-10 10], ...
    "elevation_deg", [-5 5], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "GridStep_deg", 1, ...
    "SampleTime_s", 0.5, ...
    "MaxSearchTime_s", 8, ...
    "PrintFailureSuggestions", false);
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function verifyPlanIsFree(testCase, plan, safetyMargin_deg)
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct("SafetyMarginDeg", safetyMargin_deg, "TimePaddingSamples", 1));
verifyEqual(testCase, nnz(blocked), 0);
verifyLessThanOrEqual(testCase, max(abs(plan.velocity_deg_s), [], 1), ...
    plan.limits.maxVelocity_deg_s + 1e-8);
verifyLessThanOrEqual(testCase, ...
    max(abs(plan.acceleration_deg_s2), [], 1), ...
    plan.limits.maxAcceleration_deg_s2 + 1e-8);
end

function testEmptyFieldStraightLineIsOptimal(testCase)
[azElData, initialState, goalState, limits, options] = standardProblem();
plan = planAzElSafeIntervalAStar( ...
    azElData, initialState, goalState, limits, options);
verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, "safeIntervalAStar");
verifyEqual(testCase, plan.angularPathLength_deg, 8, "AbsTol", 1e-9);
verifyTrue(testCase, plan.optimalGlobally);
verifyEqual(testCase, plan.position_deg(end, :), ...
    goalState.position_deg, "AbsTol", 1e-9);
verifyPlanIsFree(testCase, plan, 0);
end

function testStaticDetourAvoidsBlockerExactly(testCase)
time_s = (0:40).';
azElData = makeAzElObstacleData("Central blocker", time_s, ...
    [-1; 1; 1; -1; -1], [43; 43; 47; 47; 43]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [40 50], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "GridStep_deg", 1, ...
    "SafetyMargin_deg", 0.1, ...
    "AllowAzimuthWrap", false, ...
    "MaxSearchTime_s", 30, ...
    "PrintFailureSuggestions", false);
plan = planAzElSafeIntervalAStar(azElData, boundaryState(0, [-6 45]), ...
    boundaryState(40, [6 45]), limits, options);
verifyTrue(testCase, plan.success);
verifyGreaterThan(testCase, plan.angularPathLength_deg, 12);
verifyPlanIsFree(testCase, plan, options.SafetyMargin_deg);
end

function testMovingWallForcesTimedCrossing(testCase)
time_s = (0:0.5:30).';
sampleCount = numel(time_s);
azimuth = cell(sampleCount, 1);
elevation = cell(sampleCount, 1);
% A full-height wall blocks azimuth zero except for a short opening that
% sweeps upward in elevation, so the crossing must be timed, not routed.
for k = 1:sampleCount
    gapCenter = -4 + 0.4 * time_s(k);
    azimuth{k} = [-0.5; 0.5; 0.5; -0.5; -0.5; NaN; ...
        -0.5; 0.5; 0.5; -0.5; -0.5];
    elevation{k} = [-6; -6; gapCenter - 1; gapCenter - 1; -6; NaN; ...
        gapCenter + 1; gapCenter + 1; 6; 6; gapCenter + 1];
end
azElData = struct( ...
    "targetName", "Sweeping gap wall", ...
    "time_s", time_s, ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", "visible");
limits = struct( ...
    "azimuth_deg", [-8 8], ...
    "elevation_deg", [-6 6], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2]);
options = struct( ...
    "GridStep_deg", 1, ...
    "SampleTime_s", 0.25, ...
    "SafetyMargin_deg", 0.1, ...
    "MaxSearchTime_s", 30, ...
    "PrintFailureSuggestions", false);
plan = planAzElSafeIntervalAStar(azElData, boundaryState(0, [-5 0]), ...
    boundaryState(30, [5 0]), limits, options);
verifyTrue(testCase, plan.success);
verifyPlanIsFree(testCase, plan, options.SafetyMargin_deg);
end

function testWrappedSeamUsesShortWay(testCase)
[azElData, ~, ~, ~, options] = standardProblem();
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-20 20], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options.AllowAzimuthWrap = true;
options.MaxSearchTime_s = 20;
plan = planAzElSafeIntervalAStar(azElData, boundaryState(0, [170 0]), ...
    boundaryState(20, [-170 0]), limits, options);
verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.angularPathLength_deg, 20, "AbsTol", 1e-9);
verifyEqual(testCase, plan.positionUnwrapped_deg(end, 1), 190, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, plan.position_deg(end, 1), -170, "AbsTol", 1e-9);
end

function testTerminalCaptureMatchesGoalDynamics(testCase)
[azElData, ~, ~, ~, ~] = standardProblem();
limits = struct( ...
    "azimuth_deg", [-20 20], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
goalState = struct( ...
    "time_s", 10, ...
    "position_deg", [1.6 2], ...
    "velocity_deg_s", [0.3 0], ...
    "acceleration_deg_s2", [0 0]);
options = struct( ...
    "GridStep_deg", 1, ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.05, ...
    "AllowNonzeroTerminalState", true, ...
    "MaxSearchTime_s", 20, ...
    "PrintFailureSuggestions", false);
plan = planAzElSafeIntervalAStar(azElData, boundaryState(0, [-8 -3]), ...
    goalState, limits, options);
verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.position_deg(end, :), ...
    goalState.position_deg, "AbsTol", 1e-6);
verifyEqual(testCase, plan.velocity_deg_s(end, :), ...
    goalState.velocity_deg_s, "AbsTol", 1e-6);
verifyPlanIsFree(testCase, plan, 0);
end

function testWaitingAppearsForTimedGate(testCase)
problem = makeStopGoGatesGauntlet();
problem.options.PrintFailureSuggestions = false;
plan = planAzElSafeIntervalAStar(problem.azElData, problem.startState, ...
    problem.stopState, problem.limits, problem.options);
verifyTrue(testCase, plan.success);
verifyGreaterThanOrEqual(testCase, ...
    nnz(diff([false; plan.isWaiting; false]) == 1), 3);
verifyPlanIsFree(testCase, plan, problem.options.SafetyMargin_deg);
end

function testImpossibleDeadlineReturnsAssessment(testCase)
[azElData, initialState, ~, limits, options] = standardProblem();
plan = planAzElSafeIntervalAStar(azElData, initialState, ...
    boundaryState(0.5, [4 0]), limits, options);
verifyFalse(testCase, plan.success);
verifyTrue(testCase, isfield(plan, "failureAssessment"));
verifyEqual(testCase, plan.failureAssessment.reasonCode, ...
    "kinematicallyUnreachable");
end

function testInterceptWrapperAcceptsPlannerFcn(testCase)
time_s = (0:0.5:30).';
azElData = makeAzElObstacleData("Empty", time_s, zeros(0, 1), ...
    zeros(0, 1));
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [-2 + 0.3 * time_s, repmat(2, numel(time_s), 1)]);
limits = struct( ...
    "azimuth_deg", [-20 20], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "EarliestInterceptTime_s", 10, ...
    "LatestInterceptTime_s", 14, ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 3, ...
    "PerAttemptMaxSearchTime_s", 8, ...
    "CatchTolerance_deg", 0.05, ...
    "GridStep_deg", 1, ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.05, ...
    "SafetyMargin_deg", 0.1, ...
    "MaxSearchTime_s", 8, ...
    "PrintFailureSuggestions", false, ...
    "PlannerFcn", @planAzElSafeIntervalAStar);
plan = planAzElMovingTargetIntercept(azElData, ...
    boundaryState(0, [-8 -3]), target, limits, options);
verifyTrue(testCase, plan.success);
verifyEqual(testCase, plan.method, "safeIntervalAStar");
verifyLessThanOrEqual(testCase, plan.catchError_deg, 0.05);
end
