%% Example 24: wait for a moving az/el obstacle to clear
% A full-height gate blocks every elevation through t=6 s. The boresight
% can approach the gate, but a collision-free solution must stop and wait.
suiteRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(suiteRoot);
startupOrekitSuite();

epoch = datetime(2026, 1, 1, 0, 0, 0, "TimeZone", "UTC");
sampleCount = 21;
azimuth = cell(sampleCount, 1);
elevation = cell(sampleCount, 1);
for k = 1:sampleCount
    if k <= 7
        azimuth{k} = [-1; 1; 1; -1; -1];
        elevation{k} = [39; 39; 51; 51; 39];
    else
        azimuth{k} = zeros(0, 1);
        elevation{k} = zeros(0, 1);
    end
end
gateData = struct( ...
    "targetName", "Closing gate", ...
    "time_s", (0:sampleCount - 1).', ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", repmat("visible", sampleCount, 1));
obstacleWorkspace = buildAzElTimeObstacleWorkspace(gateData, struct( ...
    "ReferenceTime", epoch));

plannerLimits = struct( ...
    "AzimuthLimitsDeg", [-180 180], ...
    "ElevationLimitsDeg", [40 50], ...
    "AzimuthRateLimitDegPerSec", 2, ...
    "ElevationRateLimitDegPerSec", 2, ...
    "AzimuthAccelerationLimitDegPerSec2", 1, ...
    "ElevationAccelerationLimitDegPerSec2", 1);
plannerOptions = struct( ...
    "TimeStepSeconds", 1, ...
    "CollisionCheckStepSeconds", 0.2, ...
    "TimePaddingSamples", 0, ...
    "MaxPlanningTimeSeconds", 20);
startState = struct( ...
    "AzimuthDeg", -4, "ElevationDeg", 45, "Time", epoch);
goalState = struct("AzimuthDeg", 4, "ElevationDeg", 45);

waitPlan = planAzElKinodynamicAStar( ...
    obstacleWorkspace, startState, goalState, ...
    plannerLimits, plannerOptions);
assert(waitPlan.Success, waitPlan.Message);
steeringCommand = waitPlan.SteeringProfile;
fprintf("Gate plan: %.0f s total, %.0f s held at zero rate.\n", ...
    waitPlan.CostSeconds, ...
    nnz(waitPlan.Path.IsWaiting) * plannerOptions.TimeStepSeconds);

%% The 3-D path shows the hold occurring before the gate disappears
workspaceView = plotAzElTimeObstacleWorkspace( ...
    obstacleWorkspace, struct( ...
    "TimeUnit", "seconds", ...
    "MaximumDisplayedSlices", sampleCount));
pathTime = waitPlan.Path.TimeSecondsFromReference / workspaceView.TimeScale;
plot3(workspaceView.Axes, ...
    waitPlan.Path.AzimuthDeg, ...
    waitPlan.Path.ElevationDeg, ...
    pathTime, ...
    "-o", "Color", [0 0.55 0.8], "MarkerFaceColor", [0 0.55 0.8], ...
    "LineWidth", 2.5, "DisplayName", "Path with wait");
legend(workspaceView.Axes, "Location", "best");
title(workspaceView.Axes, "Boresight waits for the az/el gate to clear");

%% The 2-D command exposes the wait as a flat azimuth segment
figure("Color", "w", "Name", "Wait steering command");
tiledlayout(2, 1, "TileSpacing", "compact");
nexttile;
plot(waitPlan.Path.ElapsedSeconds, ...
    waitPlan.Path.AzimuthUnwrappedDeg, "-o", "LineWidth", 1.8);
hold on;
xline(6, "--", "Gate clears");
grid on;
ylabel("Azimuth (deg)");
title("Boresight steering command");
nexttile;
plot(waitPlan.Path.ElapsedSeconds, waitPlan.Path.ElevationDeg, ...
    "-o", "LineWidth", 1.8);
hold on;
xline(6, "--", "Gate clears");
grid on;
xlabel("Time from plan start (s)");
ylabel("Elevation (deg)");
