%% Example 23: kinodynamic boresight avoidance around Vietnam
% Build the real moving Vietnam obstacle from Example 22, then find the
% minimum-time path on a rate/acceleration-limited az/el/time lattice.
suiteRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(suiteRoot);
startupOrekitSuite();

startTime = datetime(2023, 9, 17, 5, 31, 0, "TimeZone", "UTC");
stopTime = datetime(2023, 9, 17, 9, 0, 0, "TimeZone", "UTC");
cfg = ScenarioConfig("Name", "Vietnam boresight avoidance", ...
    "Epoch", startTime, "StopTime", stopTime, ...
    "TimeStep", seconds(10));
scenario = MissionScenario(cfg);

earthEquatorialRadiusMeters = 6378137.0;
sat = SatelliteObject.fromKeplerian("sat1", ...
    earthEquatorialRadiusMeters + 900e3, 0, 98.6, 20, 0, 0);
sat.PropagatorType = "EcksteinHechler";
sat.Attitude = "NadirSun";

sensor = SensorObject.simpleConic("SatAEsensor", "sat1", 1);
sensor.PointingMode = "Nadir";
sensor.FieldOfRegardDeg = 70;
sensor.MinElevationDeg = 5;
sensor.AzimuthRateLimitDegPerSec = 2;
sensor.ElevationRateLimitDegPerSec = 2;
sensor.AzimuthAccelerationLimitDegPerSec2 = 0.2;
sensor.ElevationAccelerationLimitDegPerSec2 = 0.2;
sensor.MountOffsetMeters = [0 0 2000];
sat = sat.addSensor(sensor);

latitudeDeg = [ ...
    21.6409, 23.2462, 22.4436, 20.8382, 19.8349, 18.4303, 15.6209, ...
    13.0792, 10.2029, 8.66451, 10.6712, 11.6076, 15.3534, 19.0322, 21.0389];
longitudeDeg = [ ...
    107.993, 105.328, 102.664, 103.996, 104.44, 104.631, 107.105, ...
    106.724, 104.821, 104.757, 106.851, 109.072, 108.945, 105.646, 106.724];
vietnam = AreaTargetObject("Vietnam", latitudeDeg, longitudeDeg, 0);
scenario = scenario.addObject(sat);
scenario = scenario.addObject(vietnam);
scenario = scenario.propagate();

projectionOptions = struct( ...
    "TimeStepSeconds", 1, ...
    "AccessIndex", 1, ...
    "AccessPaddingSeconds", 1, ...
    "MaximumBoundaryStepDeg", 0.15, ...
    "AttitudeMode", "NadirSun");
azElData = computeAreaTargetAzElSweep( ...
    scenario, "sat1", "SatAEsensor", "Vietnam", projectionOptions);
obstacleWorkspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
    "MaximumVerticesPerRegion", 64, ...
    "ReferenceTime", startTime));

plannerLimits = struct( ...
    "AzimuthLimitsDeg", [-150 150], ...
    "ElevationLimitsDeg", [20 90], ...
    "AzimuthRateLimitDegPerSec", sensor.AzimuthRateLimitDegPerSec, ...
    "ElevationRateLimitDegPerSec", sensor.ElevationRateLimitDegPerSec, ...
    "AzimuthAccelerationLimitDegPerSec2", ...
    sensor.AzimuthAccelerationLimitDegPerSec2, ...
    "ElevationAccelerationLimitDegPerSec2", ...
    sensor.ElevationAccelerationLimitDegPerSec2);
plannerOptions = struct( ...
    "TimeStepSeconds", 5, ...
    "CollisionCheckStepSeconds", 1, ...
    "TimePaddingSamples", 1, ...
    "MaxPlanningTimeSeconds", 80);
startState = struct( ...
    "AzimuthDeg", -40, ...
    "ElevationDeg", 30, ...
    "Time", startTime + seconds(azElData.time_s(1)));
goalState = struct("AzimuthDeg", 10, "ElevationDeg", 30);

avoidancePlan = planAzElKinodynamicAStar( ...
    obstacleWorkspace, startState, goalState, ...
    plannerLimits, plannerOptions);
assert(avoidancePlan.Success, avoidancePlan.Message);
steeringCommand = avoidancePlan.SteeringProfile;
fprintf("Vietnam avoidance: %.0f s, %d expanded nodes.\n", ...
    avoidancePlan.CostSeconds, avoidancePlan.ExpandedNodeCount);

%% Show the collision-free path in the 3-D workspace
workspaceView = plotAzElTimeObstacleWorkspace( ...
    obstacleWorkspace, struct( ...
    "MaximumDisplayedSlices", 100, ...
    "EnvelopeFaceAlpha", 0.1));
pathTime = avoidancePlan.Path.TimeSecondsFromReference / ...
    workspaceView.TimeScale;
plot3(workspaceView.Axes, ...
    avoidancePlan.Path.AzimuthDeg, ...
    avoidancePlan.Path.ElevationDeg, ...
    pathTime, ...
    "-o", "Color", [0 0.55 0.8], "MarkerFaceColor", [0 0.55 0.8], ...
    "LineWidth", 2.5, "DisplayName", "Kinodynamic A* path");
legend(workspaceView.Axes, "Location", "best");
title(workspaceView.Axes, ...
    "Vietnam moving obstacle and collision-free boresight path");

%% The operational output is only azimuth and elevation versus time
figure("Color", "w", "Name", "Vietnam boresight steering command");
tiledlayout(2, 1, "TileSpacing", "compact");
nexttile;
plot(avoidancePlan.Path.ElapsedSeconds, ...
    avoidancePlan.Path.AzimuthUnwrappedDeg, "-o", "LineWidth", 1.8);
grid on;
ylabel("Azimuth (deg)");
title("Boresight steering command");
nexttile;
plot(avoidancePlan.Path.ElapsedSeconds, ...
    avoidancePlan.Path.ElevationDeg, "-o", "LineWidth", 1.8);
grid on;
xlabel("Time from plan start (s)");
ylabel("Elevation (deg)");
