function result = example_22_areaTargetAzElSweep(azElData)
%EXAMPLE_22_AREATARGETAZELSWEEP Build and inspect an az/el/time obstacle.
%
% result = example_22_areaTargetAzElSweep(azElData)
%
% This version only needs the compact output from calculateAreaTargetAzEl:
%   targetName, time_s, az_deg, el_deg, status
%
% time_s remains the numeric time coordinate used by
% queryAzElTimeObstacle.

suiteRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(suiteRoot, "src")));

data = normalizeAzElTimeObstacleData(azElData);
fprintf("Input target %s contains %d az/el slices from %.3f to %.3f s.\n", ...
    data.targetName, numel(data.time_s), ...
    data.time_s(1), data.time_s(end));

%% Pack every 2-D slice into an implicit 3-D obstacle
% Storage remains proportional to boundary vertex count. No dense
% azimuth-by-elevation-by-time voxel array is allocated.
obstacleWorkspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
    "MaximumVerticesPerRegion", 64));
fprintf("Packed obstacle uses %.2f MB for %d time slices.\n", ...
    obstacleWorkspace.EstimatedStorageBytes / 1024^2, ...
    obstacleWorkspace.Obstacles(1).SampleCount);

%% Query a representative centerline against the original packed slices
% Replace these azimuth/elevation arrays with an actual boresight candidate
% to test a proposed steering path. Numeric compact time_s can be passed
% directly; datetime is used here so both supported input schemas share the
% same code path.
[candidateAzimuthDeg, candidateElevationDeg] = sliceCenters(data);
[pathBlocked, hitObstacle, collisionDetails] = queryAzElTimeObstacle( ...
    obstacleWorkspace, candidateAzimuthDeg, candidateElevationDeg, ...
    data.time_s, struct( ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", 1));
validCandidate = isfinite(candidateAzimuthDeg) & ...
    isfinite(candidateElevationDeg);
fprintf("%d of %d representative centerline samples are blocked.\n", ...
    nnz(pathBlocked), nnz(validCandidate));

%% Show the 3-D workspace
% Change ViewMode to "2d" or "combined" when both views are useful.
viewMode = "3d";
obstacleView = animateAzElTimeObstacleWorkspace( ...
    azElData, obstacleWorkspace, struct( ...
    "ViewMode", viewMode, ...
    "MaximumAnimationFrames", 600, ...
    "MaximumDisplayedSlices", 100, ...
    "PauseSeconds", 0.005, ...
    "ShowEnvelope", true, ...
    "EnvelopeFaceAlpha", 0.12, ...
    "ShowCombinedSweep", true, ...
    "MaximumSweepSamples", 100, ...
    "ShowVisibilityControls", true));

result = struct( ...
    "Data", data, ...
    "Workspace", obstacleWorkspace, ...
    "CandidateAzimuthDeg", candidateAzimuthDeg, ...
    "CandidateElevationDeg", candidateElevationDeg, ...
    "PathBlocked", pathBlocked, ...
    "HitObstacle", hitObstacle, ...
    "CollisionDetails", collisionDetails, ...
    "View", obstacleView);
end

function [azimuth, elevation] = sliceCenters(data)
n = numel(data.time_s);
azimuth = nan(n, 1);
elevation = nan(n, 1);
for k = 1:n
    azimuthSlice = double(data.az_deg{k}(:));
    elevationSlice = double(data.el_deg{k}(:));
    valid = isfinite(azimuthSlice) & isfinite(elevationSlice);
    if ~any(valid)
        continue;
    end
    azimuth(k) = atan2d(mean(sind(azimuthSlice(valid))), ...
        mean(cosd(azimuthSlice(valid))));
    elevation(k) = mean(elevationSlice(valid));
end
end
