%% Script 204: single sensor scans one area target
script_217_demoSensorTaskingFullWorkflow;
areaTask = {SensorTask("TaskID", "T-AREA-SINGLE", "TaskName", "Single sensor scan", ...
    "TaskType", "ScanAreaTarget", "TargetName", "Denver Metro Area", ...
    "Priority", 7, "RequiredDwellTimeSeconds", 30, ...
    "RequiredCoveragePercent", 20, "AllowedSensorNames", "WideCam-1")};
areaCandidates = generateTaskCandidates(scenario, areaTask, options);
disp(areaCandidates);
