%% Script 205: two sensors track one point target
script_217_demoSensorTaskingFullWorkflow;
multiTask = {SensorTask("TaskID", "T-TWO-SENSOR-POINT", ...
    "TaskName", "Two sensors track Denver", ...
    "TaskType", "MultiSensorTrackPointTarget", "TargetName", "Denver Target", ...
    "Priority", 8, "RequiredDwellTimeSeconds", 120, ...
    "RequiresSimultaneousSensors", true, "RequiredSensorCount", 2, ...
    "AllowedSensorNames", ["WideCam-1"; "WideCam-2"])};
multiCandidates = generateTaskCandidates(scenario, multiTask, options);
disp(multiCandidates);
