%% Script 206: two sensors scan one area target
script_217_demoSensorTaskingFullWorkflow;
multiAreaTask = {SensorTask("TaskID", "T-TWO-SENSOR-AREA", ...
    "TaskName", "Two sensors scan Denver", ...
    "TaskType", "MultiSensorScanAreaTarget", "TargetName", "Denver Metro Area", ...
    "Priority", 8, "RequiredDwellTimeSeconds", 30, ...
    "RequiredCoveragePercent", 40, ...
    "RequiresSimultaneousSensors", false, "RequiredSensorCount", 2, ...
    "AllowedSensorNames", ["WideCam-1"; "WideCam-2"])};
multiAreaCandidates = generateTaskCandidates(scenario, multiAreaTask, options);
disp(multiAreaCandidates);
