function result = demoAdaptiveAzElDiscretization(showFigure, viewMode)
%DEMOADAPTIVEAZELDISCRETIZATION Build and inspect a smart az/el/time mesh.
%
% result = demoAdaptiveAzElDiscretization()
% result = demoAdaptiveAzElDiscretization(false)
% result = demoAdaptiveAzElDiscretization(true, "3d")
%
% viewMode is "2d", "3d", or "combined". The example uses only azElData;
% Orekit and the rest of the repository are not required.

if nargin < 1
    showFigure = true;
end
if nargin < 2
    viewMode = "combined";
end

time_s = (0:1:120).';
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    centerAzimuth = -10 + 20 * time_s(k) / time_s(end);
    centerElevation = 2.5 * sin(time_s(k) / 16);
    azimuth{k} = centerAzimuth + [-2; 2; 2; -2; -2];
    elevation{k} = centerElevation + [-3; -3; 3; 3; -3];
end
azElData = makeAzElObstacleData( ...
    "Moving rectangle", time_s, azimuth, elevation);
workspace = buildAzElTimeObstacleWorkspace(azElData);

gridSpec = struct( ...
    "AzimuthLimitsDeg", [-24 24], ...
    "ElevationLimitsDeg", [-14 14], ...
    "TimeLimitsSeconds", [0 120]);
mesh = buildAdaptiveAzElTimeMesh(workspace, gridSpec, struct( ...
    "InitialCellSizeDeg", [8 7], ...
    "MinimumCellSizeDeg", [0.5 0.4375], ...
    "MaximumTimeSamples", 61, ...
    "SafetyMarginDeg", 0.1, ...
    "TimePaddingSamples", 1));

fprintf("Adaptive leaves: %d (levels 0-%d)\n", ...
    mesh.LeafCount, mesh.Stats.MaximumLevel);
fprintf("Cell sizes: %.3g-%.3g deg azimuth, %.3g-%.3g deg elevation\n", ...
    mesh.Stats.MinimumCellSizeDeg(1), ...
    mesh.Stats.MaximumCellSizeDeg(1), ...
    mesh.Stats.MinimumCellSizeDeg(2), ...
    mesh.Stats.MaximumCellSizeDeg(2));
fprintf("Cell-time states: %d adaptive versus %.0f dense minimum-grid voxels\n", ...
    mesh.Stats.AdaptiveCellTimeSamples, ...
    mesh.Stats.DenseMinimumGridVoxelEstimate);
fprintf("Compression ratio: %.1fx\n", ...
    mesh.Stats.DenseMinimumGridVoxelEstimate / ...
    mesh.Stats.AdaptiveCellTimeSamples);

handles = struct();
if showFigure
    handles = plotAdaptiveAzElTimeMesh(mesh, struct( ...
        "ViewMode", viewMode, ...
        "VolumeContent", "free", ...
        "FaceAlpha", 0.10, ...
        "ShowCellEdges", false));
end
result = struct( ...
    "azElData", azElData, ...
    "workspace", workspace, ...
    "mesh", mesh, ...
    "handles", handles);
end
