function result = demoCoarseToFineWorkspace(showFigure)
%DEMOCOARSETOFINEWORKSPACE Build, inspect, and locally refine a workspace.
%
% result = demoCoarseToFineWorkspace()
% result = demoCoarseToFineWorkspace(false)
%
% This demonstration is Orekit-independent. It shows the three distinct
% representations:
%   1. azElData: readable polygons at every source time.
%   2. workspace: packed polygons used by exact collision queries.
%   3. pyramid: coarse global occupancy plus a selected fine patch.

if nargin < 1
    showFigure = true;
end

time_s = (0:120).';
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    centerAz = -8 + 16 * time_s(k) / time_s(end);
    centerEl = 2 * sin(time_s(k) / 14);
    azimuth{k} = centerAz + [-2; 2; 2; -2; -2];
    elevation{k} = centerEl + [-3; -3; 3; 3; -3];
end
azElData = makeAzElObstacleData( ...
    "Moving rectangle", time_s, azimuth, elevation);

workspace = buildAzElTimeObstacleWorkspace(azElData);
gridSpec = struct( ...
    "AzimuthLimitsDeg", [-20 20], ...
    "ElevationLimitsDeg", [-12 12], ...
    "TimeLimitsSeconds", [0 120]);
pyramid = buildAzElTimeWorkspacePyramid( ...
    workspace, gridSpec, struct( ...
    "CoarseCellSizeDeg", 2, ...
    "FineCellSizeDeg", 0.25, ...
    "MaximumCoarseTimeSamples", 25));

region = struct( ...
    "AzimuthLimitsDeg", [-8 8], ...
    "ElevationLimitsDeg", [-6 6], ...
    "TimeLimitsSeconds", [30 70]);
[pyramid, patch] = refineAzElTimeWorkspacePyramid( ...
    pyramid, workspace, region, struct( ...
    "MaximumTimeSamples", 41));

fprintf("Packed workspace: %d obstacle, %d source times, %.1f KiB\n", ...
    workspace.ObstacleCount, numel(time_s), ...
    workspace.EstimatedStorageBytes / 1024);
fprintf("Coarse raster: %d x %d x %d = %d voxels\n", ...
    pyramid.Stats.CoarseGridSize(1), ...
    pyramid.Stats.CoarseGridSize(2), ...
    pyramid.Stats.CoarseGridSize(3), ...
    pyramid.Stats.CoarseVoxelCount);
fprintf("Uniform fine estimate: %.0f voxels (%.1fx the coarse raster)\n", ...
    pyramid.Stats.UniformFineVoxelCountEstimate, ...
    pyramid.Stats.UniformFineToCoarseRatio);
fprintf("Local fine patch: %d x %d x %d = %d voxels\n", ...
    size(patch.Grid.Occupancy, 1), ...
    size(patch.Grid.Occupancy, 2), ...
    size(patch.Grid.Occupancy, 3), ...
    numel(patch.Grid.Occupancy));

handles = struct();
if showFigure
    handles = plotAzElTimeWorkspacePyramid(pyramid);
end
result = struct( ...
    "azElData", azElData, ...
    "workspace", workspace, ...
    "pyramid", pyramid, ...
    "patch", patch, ...
    "handles", handles);
end
