function result = example08AlternatingSlalom()
%EXAMPLE08ALTERNATINGSLALOM Weave through alternating barriers.

time_s = (0:0.5:60).';
centers = [-9, -3, 3, 9];
passAbove = [true, false, true, false];
obstacles = cell(numel(centers), 1);
for obstacleIndex = 1:numel(centers)
    [azimuth, elevation] = slalomBarrier( ...
        centers(obstacleIndex), passAbove(obstacleIndex));
    obstacles{obstacleIndex} = makeAzElObstacleData( ...
        "Slalom " + obstacleIndex, time_s, azimuth, elevation);
end
azElData = combineAzElObstacles(obstacles);
startState = boundaryState(0, [-15, 0]);
stopState = boundaryState(60, [15, 0]);
limits = struct( ...
    "azimuth_deg", [-17, 17], ...
    "elevation_deg", [-7, 7], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0.25, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 75, ...
    "MaxExpansions", 1000000);

result = runAzElGauntletCase( ...
    "Gauntlet 4", ...
    "four-barrier alternating slalom", ...
    azElData, startState, stopState, limits, options);
path = result.plan.positionUnwrapped_deg;
crossingElevation = zeros(size(centers));
for obstacleIndex = 1:numel(centers)
    [~, sample] = min(abs(path(:, 1) - centers(obstacleIndex)));
    crossingElevation(obstacleIndex) = path(sample, 2);
end
result.diagnostics.crossingElevation_deg = crossingElevation;
expectedSign = [1, -1, 1, -1];
if any(sign(crossingElevation) ~= expectedSign) || ...
        any(abs(crossingElevation) < 1.25)
    error("example08AlternatingSlalom:WrongPassSide", ...
        "The route did not alternate through all four slalom openings.");
end
fprintf("  Crossing elevations: %s deg\n", ...
    mat2str(crossingElevation, 3));
end

function [azimuth, elevation] = slalomBarrier(center, passAbove)
azimuth = center + 1.25 * [-1; 1; 1; -1; -1];
if passAbove
    elevation = [-7; -7; 1; 1; -7];
else
    elevation = [-1; -1; 7; 7; -1];
end
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
