function result = example16TrainedPlannerAgent(viewOptions)
%EXAMPLE16TRAINEDPLANNERAGENT Deploy the saved profile-selection agent.
%
% result = example16TrainedPlannerAgent()
%
% The agent ranks search profiles for a narrow-passage problem. The chosen
% Dijkstra search still validates every trajectory sample against the
% original polygon obstacle before the example accepts the result.

if nargin < 1
    viewOptions = struct();
end
sampleTime_s = (0:1:20).';
axisLimits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-10 10], ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [5 5]);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);

% This wall touches both elevation limits. Its 1.4-degree opening is
% centered on a one-degree lattice row but not a two-degree row, making the
% classifier's fast-versus-balanced decision observable.
wallAzimuth_deg = [ ...
    -3.4; 2.4; 2.4; -3.4; -3.4; NaN; ...
    -3.4; 2.4; 2.4; -3.4; -3.4];
wallElevation_deg = [ ...
    -10; -10; -3.7; -3.7; -10; NaN; ...
    -2.3; -2.3; 10; 10; -2.3];
azimuthByTime = repmat({wallAzimuth_deg}, numel(sampleTime_s), 1);
elevationByTime = repmat({wallElevation_deg}, numel(sampleTime_s), 1);
azElData = makeAzElObstacleData( ...
    "Narrow training-style wall", sampleTime_s, ...
    azimuthByTime, elevationByTime);

plan = planAzElWithAgent( ...
    azElData, initialState, goalState, axisLimits, struct( ...
        "AgentPrintDiagnostics", true, ...
        "AgentMaxSearchTime_s", 20));
if ~plan.success
    error("example16TrainedPlannerAgent:NoPath", "%s", plan.message);
end
if ~plan.exactCollisionValidated
    error("example16TrainedPlannerAgent:UnvalidatedPath", ...
        "The deployed agent returned an unvalidated path.");
end

animationOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 180, ...
    "ShowPlanningSummary", true, ...
    "DiscretizationMode", "build"));
animationHandles = animateAzElAvoidancePlan( ...
    azElData, plan, animationOptions);
result = struct( ...
    "azElData", azElData, ...
    "plan", plan, ...
    "animationHandles", animationHandles);
end
