function [result, handles] = example03KinodynamicDetour(viewOptions)
%EXAMPLE03KINODYNAMICDETOUR Use adaptive A* around a static block.
%
% The fixed endpoint and obstacle are deliberately simple, but the returned
% command must still satisfy rate, acceleration, time, and collision limits.

if nargin < 1
    viewOptions = struct();
end

time_s = (0:40).';
obstacleAzimuth = [-1; 1; 1; -1; -1];
obstacleElevation = [43; 43; 47; 47; 43];
azElData = makeAzElObstacleData( ...
    "Central blocker", time_s, obstacleAzimuth, obstacleElevation);
startState = boundaryState(0, [-6, 45]);
stopState = boundaryState(40, [6, 45]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [40, 50], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [1, 1]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "GridStep_deg", 1, ...
    "SafetyMargin_deg", 0.1, ...
    "MaxSearchTime_s", 60);

result = planAzElAdaptiveAStar( ...
    azElData, startState, stopState, limits, options);
if ~result.success
    error("example03KinodynamicDetour:NoPath", ...
        "Adaptive A* failed: %s", result.message);
end

blocked = queryAzElTimeObstacle(result.workspace, ...
    result.position_deg(:, 1), result.position_deg(:, 2), ...
    result.time_s, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", result.options.TimePaddingSamples));
if any(blocked)
    error("example03KinodynamicDetour:Collision", ...
        "The returned command contains %d blocked samples.", nnz(blocked));
end

handles = animateAzElAvoidancePlan( ...
    azElData, result, defaultAzElAnimationOptions( ...
    viewOptions, struct( ...
    "MaximumAnimationFrames", 120, ...
    "MaximumDisplayedSlices", 80)));
result.animationHandles = handles;
fprintf("Adaptive A* detour: %.3f deg, %.3f s, %d expansions.\n", ...
    result.angularPathLength_deg, result.searchElapsed_s, ...
    result.expandedNodeCount);
end

function state = boundaryState(time_s, position_deg)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
