function result = example15SpinningRodSpiral(viewOptions)
%EXAMPLE15SPINNINGRODSPIRAL Time a faster rod through a notched spiral.
%
% result = example15SpinningRodSpiral()
% result = example15SpinningRodSpiral(viewOptions)
%
% A fast sector-shaped rod repeatedly sweeps a two-turn spiral. Three
% recessed, rod-protected notches let the boresight stop safely until the
% rod passes. The Dijkstra planner receives no guide path or corridor.

if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 500, ...
    "MaximumDisplayedSlices", 140, ...
    "PauseSeconds", 0.01, ...
    "ObstacleFaceAlpha", 0.05, ...
    "ShowObstacleSlices", true, ...
    "ShowFuturePath", true));

problem = makeSpinningRodSpiralGauntlet();
plan = planAzElDijkstra( ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
if ~plan.success
    error("example15SpinningRodSpiral:NoPath", ...
        "Planner failed: %s", plan.message);
end
diagnostics = analyzeSpinningRodSpiralGauntlet(problem, plan);
if diagnostics.blockedSampleCount > 0
    error("example15SpinningRodSpiral:Collision", ...
        "The planned command contains %d blocked samples.", ...
        diagnostics.blockedSampleCount);
end
if diagnostics.windingTurns < 0.8
    error("example15SpinningRodSpiral:InsufficientTurns", ...
        "The plan accumulated only %.2f spiral turns.", ...
        diagnostics.windingTurns);
end
if diagnostics.waitingNotchCount < 1 || ...
        diagnostics.protectedWaiting_s < 1
    error("example15SpinningRodSpiral:MissingNotchWait", ...
        "The plan did not wait in a protected notch. Total waiting " + ...
        "%.2f s; protected waiting %.2f s; notch waits %s s.", ...
        diagnostics.totalWaiting_s, diagnostics.protectedWaiting_s, ...
        mat2str(diagnostics.notchWait_s, 4));
end
if diagnostics.rodAngularRate_deg_s <= ...
        diagnostics.maximumBoresightAngularRate_deg_s
    error("example15SpinningRodSpiral:RodNotFaster", ...
        "The rod did not rotate faster than the planned boresight.");
end
if isfield(plan.options, "GuidePath_deg") || ...
        isfield(plan.options, "DirectionAngles_deg")
    error("example15SpinningRodSpiral:ExternalGuideUsed", ...
        "The spinning-rod spiral must use unguided Dijkstra.");
end
view = animateAzElAvoidancePlan( ...
    problem.azElData, plan, viewOptions);
view = addNotchOverlays(view, problem);
result = problem;
result.plan = plan;
result.diagnostics = diagnostics;
result.blockedSampleCount = diagnostics.blockedSampleCount;
result.view = view;
fprintf([ ...
    'Spinning-rod spiral: %.2f turns, %.2f s protected waiting in ' ...
    '%d notches, %.2f s search.\n'], ...
    diagnostics.windingTurns, diagnostics.protectedWaiting_s, ...
    diagnostics.waitingNotchCount, plan.searchElapsed_s);
end

function view = addNotchOverlays(view, problem)
centers = problem.geometry.notchCenters_deg;
radius = problem.geometry.notchSafeRadius_deg;
angle = linspace(0, 2 * pi, 49).';
view.NotchBoundaries2D = gobjects(size(centers, 1), 1);
view.NotchColumns3D = gobjects(size(centers, 1), 1);
for notch = 1:size(centers, 1)
    x = centers(notch, 1) + radius * cos(angle);
    y = centers(notch, 2) + radius * sin(angle);
    label = "";
    visibility = "off";
    if notch == 1
        label = "Protected notch";
        visibility = "on";
    end
    view.NotchBoundaries2D(notch) = plot( ...
        view.AzElAxes, x, y, ":", ...
        "Color", [0.10 0.55 0.25], "LineWidth", 1.8, ...
        "DisplayName", label, "HandleVisibility", visibility);
    view.NotchColumns3D(notch) = plot3( ...
        view.ObstacleFieldAxes, ...
        centers(notch, 1) * [1 1], ...
        centers(notch, 2) * [1 1], ...
        [problem.startState.time_s problem.stopState.time_s], ":", ...
        "Color", [0.10 0.55 0.25], "LineWidth", 1.2, ...
        "HandleVisibility", "off");
end
legend(view.AzElAxes, "show", "Location", "best");
end
