function result = example04DynamicSafeIntervals(viewOptions)
%EXAMPLE04DYNAMICSAFEINTERVALS Plan through two moving az/el/time volumes.
%
% The example is standalone: it creates canonical azElData directly,
% plans a constrained boresight command, validates it, and animates both
% the current 2-D geometry and the accumulated 3-D space-time volume.

if nargin < 1
    viewOptions = struct();
end

time_s = (0:30).';
wallAzimuth = cell(numel(time_s), 1);
wallElevation = cell(numel(time_s), 1);
lowerAzimuth = cell(numel(time_s), 1);
lowerElevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    wallAzimuth{k} = [-1; 1; 1; -1; -1];
    wallElevation{k} = ...
        0.45 * sin(time_s(k) / 4) + [-2; -2; 2; 2; -2];
    lowerAzimuth{k} = [2; 4; 4; 2; 2];
    lowerElevation{k} = ...
        -3.2 + 0.35 * cos(time_s(k) / 5) + ...
        [-1; -1; 1; 1; -1];
end
azElData = { ...
    makeAzElObstacleData( ...
    "Oscillating center wall", time_s, ...
    wallAzimuth, wallElevation), ...
    makeAzElObstacleData( ...
    "Moving lower wall", time_s, ...
    lowerAzimuth, lowerElevation)};

startState = boundaryState(0, [-6 0]);
stopState = boundaryState(30, [6 0]);
limits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-6 6], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "GridStep_deg", 1, ...
    "SafetyMargin_deg", 0.15, ...
    "MaxSearchTime_s", 10);

plan = planAzElDijkstra( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("example04DynamicSafeIntervals:NoPath", ...
        "Planner failed: %s", plan.message);
end
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blocked)
    error("example04DynamicSafeIntervals:Collision", ...
        "The returned command contains %d blocked samples.", ...
        nnz(blocked));
end

view = animateAzElAvoidancePlan(azElData, plan, ...
    defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 120, ...
    "MaximumDisplayedSlices", 80, ...
    "PauseSeconds", 0)));
result = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "blockedSampleCount", nnz(blocked), ...
    "view", view);
fprintf(['Dynamic safe-interval Dijkstra: %.3f deg, %.3f s search, ' ...
    '%d expansions, %s.\n'], ...
    plan.angularPathLength_deg, plan.searchElapsed_s, ...
    plan.expandedNodeCount, plan.method);
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
