function result = example04DynamicSafeIntervals(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   result = example04DynamicSafeIntervals()
%   result = example04DynamicSafeIntervals(viewOptions)
%**************************************************************************
% PURPOSE
%   - Demonstrate safe-interval Dijkstra through two moving obstacle volumes.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Partial animation options.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Problem inputs, successful plan, independent safety count, and view.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Sample The Moving Obstacles
if nargin < 1
    viewOptions = struct();
end

time_s = (0:30).';
wallAzimuth = cell(numel(time_s), 1);
wallElevation = cell(numel(time_s), 1);
lowerAzimuth = cell(numel(time_s), 1);
lowerElevation = cell(numel(time_s), 1);
for sampleIndex = 1:numel(time_s)
    wallAzimuth{sampleIndex} = [-1; 1; 1; -1; -1];
    wallElevation{sampleIndex} = 0.45 * ...
        sin(time_s(sampleIndex) / 4) + [-2; -2; 2; 2; -2];
    lowerAzimuth{sampleIndex} = [2; 4; 4; 2; 2];
    lowerElevation{sampleIndex} = -3.2 + ...
        0.35 * cos(time_s(sampleIndex) / 5) + ...
        [-1; -1; 1; 1; -1];
end
azElData = { ...
    makeAzElObstacleData( ...
    "Oscillating center wall", time_s, ...
    wallAzimuth, wallElevation), ...
    makeAzElObstacleData( ...
    "Moving lower wall", time_s, ...
    lowerAzimuth, lowerElevation)};

%% Section 2: Define The Planning Request
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-6 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
stopState = struct( ...
    "time_s", 30, ...
    "position_deg", [6 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-6 6], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "SampleTime_s", 0.25, ...
    "GridStep_deg", 1, ...
    "SafetyMargin_deg", 0.15, ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 10);

%% Section 3: Plan & Independently Validate The Command
plan = planAzElDijkstra( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("example04DynamicSafeIntervals:NoPath", ...
        "Planner failed: %s", plan.message);
end
blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blocked)
    error("example04DynamicSafeIntervals:Collision", ...
        "The returned command contains %d blocked samples.", ...
        nnz(blocked));
end

%% Section 4: Animate, Package & Report The Result
view = animateAzElAvoidancePlan(azElData, plan, ...
    defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 120, ...
    "MaximumDisplayedSlices", 80, ...
    "PauseSeconds", 0)));
result = struct( ...
    "azElData", {azElData}, ...
    "startState", startState, ...
    "stopState", stopState, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "blockedSampleCount", nnz(blocked), ...
    "view", view);
fprintf(['Dynamic safe-interval Dijkstra: %.3f deg, %.3f s search, ' ...
    '%d expansions, %s.\n'], ...
    plan.angularPathLength_deg, plan.searchElapsed_s, ...
    plan.expandedNodeCount, plan.method);
end
