function result = example15SpinningRodSpiral(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   result = example15SpinningRodSpiral()
%   result = example15SpinningRodSpiral(viewOptions)
%**************************************************************************
% PURPOSE
%   - Plan through a notched spiral swept by a faster rotating rod.
%   - Verify unguided winding and protected waiting in the notches.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Partial animation options.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Generated problem, successful plan, diagnostics, and view handles.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Resolve The Animation & Generate The Problem
if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 500, ...
    "MaximumDisplayedSlices", 140, ...
    "PauseSeconds", 0.01, ...
    "ObstacleFaceAlpha", 0.05, ...
    "ShowObstacleSlices", true, ...
    "ShowFuturePath", true));

problem = makeSpinningRodSpiralGauntlet();

%% Section 2: Plan & Verify Winding, Waiting & Safety
plan = planAzElDijkstra( ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
if ~plan.success
    error("example15SpinningRodSpiral:NoPath", ...
        "Planner failed: %s", plan.message);
end
diagnostics = analyzeSpinningRodSpiralGauntlet(problem, plan);
if diagnostics.blockedSampleCount > 0
    error("example15SpinningRodSpiral:Collision", ...
        "The planned command contains %d blocked samples.", ...
        diagnostics.blockedSampleCount);
end
if diagnostics.windingTurns < 0.8
    error("example15SpinningRodSpiral:InsufficientTurns", ...
        "The plan accumulated only %.2f spiral turns.", ...
        diagnostics.windingTurns);
end
if diagnostics.waitingNotchCount < 1 || ...
        diagnostics.protectedWaiting_s < 1
    error("example15SpinningRodSpiral:MissingNotchWait", ...
        "The plan did not wait in a protected notch. Total waiting " + ...
        "%.2f s; protected waiting %.2f s; notch waits %s s.", ...
        diagnostics.totalWaiting_s, diagnostics.protectedWaiting_s, ...
        mat2str(diagnostics.notchWait_s, 4));
end
if diagnostics.rodAngularRate_deg_s <= ...
        diagnostics.maximumBoresightAngularRate_deg_s
    error("example15SpinningRodSpiral:RodNotFaster", ...
        "The rod did not rotate faster than the planned boresight.");
end
if isfield(plan.options, "GuidePath_deg") || ...
        isfield(plan.options, "DirectionAngles_deg")
    error("example15SpinningRodSpiral:ExternalGuideUsed", ...
        "The spinning-rod spiral must use unguided Dijkstra.");
end

%% Section 3: Animate, Annotate & Report The Result
view = animateAzElAvoidancePlan( ...
    problem.azElData, plan, viewOptions);
view = addNotchOverlays(view, problem);
result = problem;
result.plan = plan;
result.diagnostics = diagnostics;
result.blockedSampleCount = diagnostics.blockedSampleCount;
result.view = view;
fprintf([ ...
    'Spinning-rod spiral: %.2f turns, %.2f s protected waiting in ' ...
    '%d notches, %.2f s search.\n'], ...
    diagnostics.windingTurns, diagnostics.protectedWaiting_s, ...
    diagnostics.waitingNotchCount, plan.searchElapsed_s);
end

%% Section 4: Local Visualization Functions
function view = addNotchOverlays(view, problem)
notchCenters_deg = problem.geometry.notchCenters_deg;
notchRadius_deg = problem.geometry.notchSafeRadius_deg;
circleAngle_rad = linspace(0, 2 * pi, 49).';
view.NotchBoundaries2D = gobjects(size(notchCenters_deg, 1), 1);
view.NotchColumns3D = gobjects(size(notchCenters_deg, 1), 1);
for notchIndex = 1:size(notchCenters_deg, 1)
    notchAzimuth_deg = notchCenters_deg(notchIndex, 1) + ...
        notchRadius_deg * cos(circleAngle_rad);
    notchElevation_deg = notchCenters_deg(notchIndex, 2) + ...
        notchRadius_deg * sin(circleAngle_rad);
    displayName = "";
    handleVisibility = "off";
    if notchIndex == 1
        displayName = "Protected notch";
        handleVisibility = "on";
    end
    view.NotchBoundaries2D(notchIndex) = plot( ...
        view.AzElAxes, notchAzimuth_deg, notchElevation_deg, ":", ...
        "Color", [0.10 0.55 0.25], "LineWidth", 1.8, ...
        "DisplayName", displayName, ...
        "HandleVisibility", handleVisibility);
    view.NotchColumns3D(notchIndex) = plot3( ...
        view.ObstacleFieldAxes, ...
        notchCenters_deg(notchIndex, 1) * [1 1], ...
        notchCenters_deg(notchIndex, 2) * [1 1], ...
        [problem.startState.time_s problem.stopState.time_s], ":", ...
        "Color", [0.10 0.55 0.25], "LineWidth", 1.2, ...
        "HandleVisibility", "off");
end
legend(view.AzElAxes, "show", "Location", "best");
end
