function plan = example02VietnamChinaAvoidance( ...
        vietnamAzElData, chinaAzElData, viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   plan = example02VietnamChinaAvoidance()
%   plan = example02VietnamChinaAvoidance(vietnam, china)
%   plan = example02VietnamChinaAvoidance(vietnam, china, viewOptions)
%**************************************************************************
% PURPOSE
%   - Plan around independent Vietnam and China obstacle records.
%   - Demonstrate bundled geographic outlines when no data is supplied.
%**************************************************************************
% INPUTS
%   - vietnam, china (canonical scalar obstacle structs, optional)
%       Independent calculateAreaTargetAzEl-style records.
%   - viewOptions (scalar struct, optional)
%       Partial animation options.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Successful Dijkstra plan plus animation handles.
%**************************************************************************
% UNITS
%   - Boundaries and commands are degrees; times are seconds.
%   - The no-input longitude/latitude translation is illustrative, not a
%     physical sensor-frame projection.

%% Section 1: Resolve Example Inputs
if nargin == 0
    [vietnamAzElData, chinaAzElData] = demoCountryProjections();
    viewOptions = struct();
elseif nargin == 2
    viewOptions = struct();
elseif nargin ~= 3
    error("example02VietnamChinaAvoidance:InvalidInputCount", ...
        "Provide both Vietnam and China azElData structs, or no inputs.");
end

%% Section 2: Normalize Obstacles & Their Shared Time Window
azElData = combineAzElObstacles( ...
    vietnamAzElData, chinaAzElData);
if numel(azElData) ~= 2
    error("example02VietnamChinaAvoidance:InvalidObstacleCount", ...
        "The example requires exactly one Vietnam and one China obstacle.");
end

obstacleStartTime_s = zeros(numel(azElData), 1);
obstacleStopTime_s = zeros(numel(azElData), 1);
for obstacleIndex = 1:numel(azElData)
    obstacleStartTime_s(obstacleIndex) = azElData(obstacleIndex).time_s(1);
    obstacleStopTime_s(obstacleIndex) = azElData(obstacleIndex).time_s(end);
end
startTime_s = max(obstacleStartTime_s);
stopTime_s = min(obstacleStopTime_s);
if stopTime_s - startTime_s < 150
    error("example02VietnamChinaAvoidance:ShortOverlap", ...
        ["Vietnam and China must have at least 150 seconds of " ...
        "overlapping azElData."]);
end

%% Section 3: Define & Run The Planning Request
startState = struct( ...
    "time_s", startTime_s, ...
    "position_deg", [-30, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
stopState = struct( ...
    "time_s", stopTime_s, ...
    "position_deg", [80, 80], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-90, 90], ...
    "maxVelocity_deg_s", [1, 1], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 1, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance", ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 30, ...
    "MaximumVerticesPerRegion", 500);

plan = planAzElDijkstra( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("example02VietnamChinaAvoidance:NoPath", ...
        "%s", plan.message);
end
if plan.obstacleField.ObstacleCount ~= 2
    error("example02VietnamChinaAvoidance:ObstacleFieldMismatch", ...
        "Expected two independently packed obstacles.");
end

%% Section 4: Report & Animate The Validated Plan
obstacleNames = string({plan.obstacleField.Obstacles.Name});
fprintf("Packed obstacles: %s\n", strjoin(obstacleNames, ", "));
fprintf("Path length: %.3f deg (<= %.3fx global optimum).\n", ...
    plan.angularPathLength_deg, plan.suboptimalityBound);
animationHandles = animateAzElAvoidancePlan( ...
    azElData, plan, defaultAzElAnimationOptions( ...
    viewOptions, struct( ...
    "MaximumAnimationFrames", 240, ...
    "MaximumDisplayedSlices", 120)));
title(animationHandles.AzElAxes, ...
    "ADM0 boundaries in the demo az/el map");
plan.animationHandles = animationHandles;
end

%% Section 5: Local Demonstration Functions
% These helpers own the optional geographic demo path. They do not alter
% caller-supplied azElData or participate in planning.
function [vietnam, china] = demoCountryProjections()
time_s = (2700:1:3000).';
vietnamBoundary = loadCountryBoundaryLatLon("Vietnam");
chinaBoundary = loadCountryBoundaryLatLon("China");
vietnam = geographicDemoObstacle(vietnamBoundary, time_s);
china = geographicDemoObstacle(chinaBoundary, time_s);
fprintf("Boundary vertices: Vietnam %d, China %d.\n", ...
    vietnamBoundary.vertexCount, chinaBoundary.vertexCount);
end

function data = geographicDemoObstacle(boundary, time_s)
sampleCount = numel(time_s);
azimuthBoundary = boundary.longitude_deg - 110;
elevationBoundary = boundary.latitude_deg;
azimuth = repmat({azimuthBoundary}, sampleCount, 1);
elevation = repmat({elevationBoundary}, sampleCount, 1);
data = struct( ...
    "targetName", boundary.name, ...
    "time_s", time_s, ...
    "az_deg", {azimuth}, ...
    "el_deg", {elevation}, ...
    "status", repmat("visible", sampleCount, 1));
end
