function plan = example01PlanFromAzElData(azElData, viewOptions)
%EXAMPLE01PLANFROMAZELDATA Run the dispatcher from one or more obstacles.
%
% azElData may be a scalar struct, struct array, or cell collection.

if nargin < 2
    viewOptions = struct();
end

startState = struct( ...
    "time_s", 2700, ...
    "position_deg", [-30, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);

stopState = struct( ...
    "time_s", 3000, ...
    "position_deg", [80, 80], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);

limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-90, 90], ...
    "maxVelocity_deg_s", [1, 1], ...
    "maxAcceleration_deg_s2", [3, 3]);

options = struct( ...
    "SampleTime_s", 0.1, ...
    "GuideGridStep_deg", 0.1, ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance");

plan = planAzElSpaceTimeFunnel( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("example01PlanFromAzElData:NoPath", "%s", plan.message);
end
plan.animationHandles = animateAzElAvoidancePlan( ...
    azElData, plan, defaultAzElAnimationOptions( ...
    viewOptions, struct("MaximumAnimationFrames", 240)));
end
