function result = example18JointBoundedJerkStudy(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   result = example18JointBoundedJerkStudy()
%   result = example18JointBoundedJerkStudy(viewOptions)
%**************************************************************************
% PURPOSE
%   - Demonstrate one search that chooses the az/el route and its velocity,
%     acceleration, time, and bounded-jerk history together.
%   - Compare the result with the earlier path-first continuous clock using
%     stored geometric/kinematic bounds and reproducible regression limits.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Partial animation options shared by every study figure.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Problem, both plans, stored reference, diagnostics, and graphics.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build A Small Circular Detour With One Legal Side
% The circular obstacle touches the lower elevation boundary. Its safety
% envelope extends below that boundary, so neither planner can squeeze under
% it. This leaves one unambiguous upper detour and makes an independent
% tangent-plus-arc distance lower bound available.
if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 180, ...
    "MaximumDisplayedSlices", 40, ...
    "PauseSeconds", 0.01, ...
    "ShowFuturePath", true));
missionEndTime_s = 18;
time_s = (0:0.25:missionEndTime_s).';
obstacleRadius_deg = 3;
safetyMargin_deg = 0.5;
circleAngle_rad = linspace(0, 2 * pi, 145).';
circleAzimuth_deg = obstacleRadius_deg * cos(circleAngle_rad);
circleElevation_deg = obstacleRadius_deg * sin(circleAngle_rad);
azElData = makeAzElObstacleData( ...
    "Static three-degree circular obstacle", time_s, ...
    circleAzimuth_deg, circleElevation_deg);

%% Section 2: State The Common Physical Request
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", [10 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-12 12], ...
    "elevation_deg", [-3 8], ...
    "maxVelocity_deg_s", [4 4], ...
    "maxAcceleration_deg_s2", [2 2]);
commonOptions = struct( ...
    "SampleTime_s", 0.05, ...
    "ValidationStep_s", 0.05, ...
    "CollisionCheckStep_s", 0.05, ...
    "GridStep_deg", 0.5, ...
    "GridStepSchedule_deg", 0.5, ...
    "SafetyMargin_deg", safetyMargin_deg, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "FallbackToProfile", false, ...
    "MaxSearchTime_s", 60, ...
    "MaxExpansions", 750000, ...
    "MaximumVerticesPerRegion", 500);

%% Section 3: Define The Joint Search & Maintained Baseline
% The joint search starts coarsely, then spends the remaining budget on a
% finer lattice. Its time step may grow from the requested 0.5 seconds so a
% single jerk action cannot exceed acceleration or jerk limits.
jointOptions = commonOptions;
jointOptions.MotionMode = "jointStateSpaceKinematic";
jointOptions.JointKinematicPositionStep_deg = 0.25;
jointOptions.JointKinematicPositionStepSchedule_deg = [0.5 0.25];
jointOptions.JointKinematicTimeStep_s = 0.5;
jointOptions.JointKinematicMaximumJerk_deg_s3 = [8 8];
jointOptions.JointKinematicTimeWeight = 0.5;
jointOptions.JointKinematicDistanceWeight = 0.5;

baselineOptions = commonOptions;
baselineOptions.MotionMode = "pathFirstThenKinematic";
baselineOptions.PathFirstTimeScaling = "minimumTime";

%% Section 4: Plan Both Commands
jointPlan = planAzElDijkstra( ...
    azElData, initialState, goalState, limits, jointOptions);
if ~jointPlan.success
    error("example18JointBoundedJerkStudy:JointSearchFailed", ...
        "Joint physical-state search failed: %s", jointPlan.message);
end
baselinePlan = planAzElDijkstra( ...
    azElData, initialState, goalState, limits, baselineOptions);
if ~baselinePlan.success
    error("example18JointBoundedJerkStudy:BaselineFailed", ...
        "Path-first baseline failed: %s", baselinePlan.message);
end
if jointPlan.method ~= "jointStateSpaceKinematicAStar" || ...
        jointPlan.retiming.MotionStyle ~= "jointStateSpaceKinematic"
    error("example18JointBoundedJerkStudy:WrongMode", ...
        "The study silently selected a different motion mode.");
end

%% Section 5: Recheck Geometry & The Exact State Equations
jointBlocked = queryAzElTimeObstacle(jointPlan.obstacleField, ...
    jointPlan.position_deg(:, 1), jointPlan.position_deg(:, 2), ...
    jointPlan.time_s, struct( ...
    "SafetyMarginDeg", safetyMargin_deg, ...
    "TimePaddingSamples", jointPlan.options.TimePaddingSamples));
baselineBlocked = queryAzElTimeObstacle(baselinePlan.obstacleField, ...
    baselinePlan.position_deg(:, 1), baselinePlan.position_deg(:, 2), ...
    baselinePlan.time_s, struct( ...
    "SafetyMarginDeg", safetyMargin_deg, ...
    "TimePaddingSamples", baselinePlan.options.TimePaddingSamples));
if any(jointBlocked) || any(baselineBlocked)
    error("example18JointBoundedJerkStudy:Collision", ...
        "Joint/baseline blocked samples: %d/%d.", ...
        nnz(jointBlocked), nnz(baselineBlocked));
end

stateSearch = jointPlan.retiming.StateSpaceSearch;
stateTimeStep_s = stateSearch.TimeStep_s;
positionResidual_deg = diff(stateSearch.PositionUnwrapped_deg) - ...
    stateSearch.Velocity_deg_s(1:end - 1, :) * stateTimeStep_s - ...
    0.5 * stateSearch.Acceleration_deg_s2(1:end - 1, :) * ...
    stateTimeStep_s^2 - (1 / 6) * stateSearch.JerkCommand_deg_s3 * ...
    stateTimeStep_s^3;
velocityResidual_deg_s = diff(stateSearch.Velocity_deg_s) - ...
    stateSearch.Acceleration_deg_s2(1:end - 1, :) * stateTimeStep_s - ...
    0.5 * stateSearch.JerkCommand_deg_s3 * stateTimeStep_s^2;
accelerationResidual_deg_s2 = diff( ...
    stateSearch.Acceleration_deg_s2) - ...
    stateSearch.JerkCommand_deg_s3 * stateTimeStep_s;
maximumStateEquationResidual = max(abs([ ...
    positionResidual_deg(:); velocityResidual_deg_s(:); ...
    accelerationResidual_deg_s2(:)]));

%% Section 6: Compare With Independent Bounds & Stored Results
reference = storedJointBoundedJerkReference();
jointCompletionTime_s = jointPlan.retiming.MinimumManeuverTime_s;
baselineCompletionTime_s = baselinePlan.retiming.MinimumManeuverTime_s;
jointDistanceRatio = jointPlan.angularPathLength_deg / ...
    reference.absoluteDistanceLowerBound_deg;
jointTimeRatio = jointCompletionTime_s / ...
    reference.absoluteTimeLowerBound_s;
jointCombinedRatio = sqrt(jointDistanceRatio * jointTimeRatio);
baselineDistanceRatio = baselinePlan.angularPathLength_deg / ...
    reference.absoluteDistanceLowerBound_deg;
baselineTimeRatio = baselineCompletionTime_s / ...
    reference.absoluteTimeLowerBound_s;
baselineCombinedRatio = sqrt( ...
    baselineDistanceRatio * baselineTimeRatio);
jointMaximumJerk_deg_s3 = max(abs(jointPlan.jerk_deg_s3), [], 1);
baselineFiniteDifferenceJerk_deg_s3 = max(abs(diff( ...
    baselinePlan.acceleration_deg_s2) / commonOptions.SampleTime_s), [], 1);
resolutionAttempts = ...
    jointPlan.motionPlanning.JointStateResolutionAttempts;
selectedResolution_deg = resolutionAttempts([resolutionAttempts.Selected]). ...
    PositionStep_deg;

regressed = jointPlan.angularPathLength_deg > ...
    reference.maximumVerifiedPathLength_deg + 1e-9 || ...
    jointCompletionTime_s > ...
    reference.maximumVerifiedCompletionTime_s + 1e-9 || ...
    jointCombinedRatio > ...
    reference.maximumVerifiedCombinedRatio + 1e-9;
if regressed
    error("example18JointBoundedJerkStudy:Regression", ...
        ["Joint result %.3f deg / %.3f s / %.4f combined exceeds " ...
        "the stored verified envelope."], ...
        jointPlan.angularPathLength_deg, jointCompletionTime_s, ...
        jointCombinedRatio);
end
if maximumStateEquationResidual > 1e-10 || ...
        any(jointMaximumJerk_deg_s3 > ...
        jointOptions.JointKinematicMaximumJerk_deg_s3 + 1e-9)
    error("example18JointBoundedJerkStudy:PhysicalReceipt", ...
        "The bounded-jerk state receipts failed independent checks.");
end
if selectedResolution_deg ~= 0.25 || ...
        jointCombinedRatio >= baselineCombinedRatio || ...
        max(jointMaximumJerk_deg_s3) >= ...
        max(baselineFiniteDifferenceJerk_deg_s3) / 5
    error("example18JointBoundedJerkStudy:StudyOutcome", ...
        "The adaptive joint search did not improve the expected tradeoff.");
end

diagnostics = struct( ...
    "jointBlockedSampleCount", nnz(jointBlocked), ...
    "baselineBlockedSampleCount", nnz(baselineBlocked), ...
    "jointCompletionTime_s", jointCompletionTime_s, ...
    "baselineCompletionTime_s", baselineCompletionTime_s, ...
    "jointDistanceRatio", jointDistanceRatio, ...
    "jointTimeRatio", jointTimeRatio, ...
    "jointCombinedRatio", jointCombinedRatio, ...
    "baselineDistanceRatio", baselineDistanceRatio, ...
    "baselineTimeRatio", baselineTimeRatio, ...
    "baselineCombinedRatio", baselineCombinedRatio, ...
    "jointMaximumJerk_deg_s3", jointMaximumJerk_deg_s3, ...
    "baselineFiniteDifferenceJerk_deg_s3", ...
        baselineFiniteDifferenceJerk_deg_s3, ...
    "maximumStateEquationResidual", maximumStateEquationResidual, ...
    "selectedResolution_deg", selectedResolution_deg, ...
    "expandedJointStateCount", stateSearch.ExpandedNodeCount, ...
    "generatedJointStateCount", stateSearch.GeneratedNodeCount);

%% Section 7: Animate The Winner & Plot The Comparison
view = animateAzElAvoidancePlan(azElData, jointPlan, viewOptions);
comparisonFigure = figure( ...
    "Color", "w", ...
    "Visible", viewOptions.FigureVisible, ...
    "Name", "Example 18 - joint bounded-jerk study", ...
    "Position", [80 60 1400 850]);
comparisonLayout = tiledlayout(comparisonFigure, 2, 2, ...
    "TileSpacing", "compact", "Padding", "compact");
title(comparisonLayout, sprintf([ ...
    'Joint state-space %.1f s / %.2f deg / %.3f combined ratio | ' ...
    'baseline %.1f s / %.2f deg / %.3f'], ...
    jointCompletionTime_s, jointPlan.angularPathLength_deg, ...
    jointCombinedRatio, baselineCompletionTime_s, ...
    baselinePlan.angularPathLength_deg, baselineCombinedRatio));

pathAxes = nexttile(comparisonLayout, 1);
hold(pathAxes, "on");
plot(pathAxes, circleAzimuth_deg, circleElevation_deg, ...
    "Color", [0 0.45 0.74], "LineWidth", 2, ...
    "DisplayName", "Circular obstacle");
plot(pathAxes, baselinePlan.positionUnwrapped_deg(:, 1), ...
    baselinePlan.positionUnwrapped_deg(:, 2), "--", ...
    "Color", [0.45 0.45 0.45], "LineWidth", 1.8, ...
    "DisplayName", "Path-first clock");
plot(pathAxes, jointPlan.positionUnwrapped_deg(:, 1), ...
    jointPlan.positionUnwrapped_deg(:, 2), ...
    "Color", [0.85 0.33 0.10], "LineWidth", 2.3, ...
    "DisplayName", "Joint bounded-jerk");
axis(pathAxes, "equal");
xlim(pathAxes, limits.azimuth_deg);
ylim(pathAxes, limits.elevation_deg);
grid(pathAxes, "on");
xlabel(pathAxes, "Azimuth (deg)");
ylabel(pathAxes, "Elevation (deg)");
legend(pathAxes, "Location", "eastoutside");

speedAxes = nexttile(comparisonLayout, 2);
hold(speedAxes, "on");
plot(speedAxes, baselinePlan.time_s, hypot( ...
    baselinePlan.velocity_deg_s(:, 1), ...
    baselinePlan.velocity_deg_s(:, 2)), "--", ...
    "Color", [0.45 0.45 0.45], "LineWidth", 1.8, ...
    "DisplayName", "Path-first speed");
plot(speedAxes, jointPlan.time_s, hypot( ...
    jointPlan.velocity_deg_s(:, 1), jointPlan.velocity_deg_s(:, 2)), ...
    "Color", [0.85 0.33 0.10], "LineWidth", 2.2, ...
    "DisplayName", "Joint speed");
grid(speedAxes, "on");
xlabel(speedAxes, "Time (s)");
ylabel(speedAxes, "Angular speed (deg/s)");
legend(speedAxes, "Location", "eastoutside");

accelerationAxes = nexttile(comparisonLayout, 3);
hold(accelerationAxes, "on");
plot(accelerationAxes, baselinePlan.time_s, hypot( ...
    baselinePlan.acceleration_deg_s2(:, 1), ...
    baselinePlan.acceleration_deg_s2(:, 2)), "--", ...
    "Color", [0.45 0.45 0.45], "LineWidth", 1.8, ...
    "DisplayName", "Path-first acceleration");
plot(accelerationAxes, jointPlan.time_s, hypot( ...
    jointPlan.acceleration_deg_s2(:, 1), ...
    jointPlan.acceleration_deg_s2(:, 2)), ...
    "Color", [0.85 0.33 0.10], "LineWidth", 2.2, ...
    "DisplayName", "Joint acceleration");
grid(accelerationAxes, "on");
xlabel(accelerationAxes, "Time (s)");
ylabel(accelerationAxes, "Acceleration (deg/s^2)");
legend(accelerationAxes, "Location", "eastoutside");

jerkAxes = nexttile(comparisonLayout, 4);
hold(jerkAxes, "on");
baselineJerk_deg_s3 = [zeros(1, 2); diff( ...
    baselinePlan.acceleration_deg_s2) / commonOptions.SampleTime_s];
plot(jerkAxes, baselinePlan.time_s, hypot( ...
    baselineJerk_deg_s3(:, 1), baselineJerk_deg_s3(:, 2)), "--", ...
    "Color", [0.45 0.45 0.45], "LineWidth", 1.4, ...
    "DisplayName", "Path-first sampled jerk");
plot(jerkAxes, jointPlan.time_s, hypot( ...
    jointPlan.jerk_deg_s3(:, 1), jointPlan.jerk_deg_s3(:, 2)), ...
    "Color", [0.85 0.33 0.10], "LineWidth", 2.2, ...
    "DisplayName", "Joint commanded jerk");
grid(jerkAxes, "on");
xlabel(jerkAxes, "Time (s)");
ylabel(jerkAxes, "Jerk magnitude (deg/s^3)");
legend(jerkAxes, "Location", "eastoutside");

result = struct( ...
    "azElData", azElData, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits, ...
    "jointOptions", jointOptions, ...
    "baselineOptions", baselineOptions, ...
    "jointPlan", jointPlan, ...
    "baselinePlan", baselinePlan, ...
    "reference", reference, ...
    "diagnostics", diagnostics, ...
    "view", view, ...
    "comparisonFigure", comparisonFigure, ...
    "comparisonAxes", [pathAxes speedAxes accelerationAxes jerkAxes]);

fprintf("Joint bounded-jerk state-space study:\n");
fprintf("  Joint path / time: %.6f deg / %.3f s\n", ...
    jointPlan.angularPathLength_deg, jointCompletionTime_s);
fprintf("  Absolute-bound distance / time ratios: %.6f / %.6f\n", ...
    jointDistanceRatio, jointTimeRatio);
fprintf("  Joint / baseline combined ratios: %.6f / %.6f\n", ...
    jointCombinedRatio, baselineCombinedRatio);
fprintf("  Joint / sampled-baseline peak jerk: %.3f / %.3f deg/s^3\n", ...
    max(jointMaximumJerk_deg_s3), ...
    max(baselineFiniteDifferenceJerk_deg_s3));
fprintf("  Selected joint resolution: %.3f deg; states %d/%d\n", ...
    selectedResolution_deg, stateSearch.ExpandedNodeCount, ...
    stateSearch.GeneratedNodeCount);
end

function reference = storedJointBoundedJerkReference()
%% Section 0: Header & Readme
% PURPOSE
%   - Preserve independent lower bounds and the verified study envelope so
%     future solver changes cannot silently make this example worse.
endpointRadius_deg = 10;
protectedObstacleRadius_deg = 3.5;
tangentLength_deg = sqrt( ...
    endpointRadius_deg^2 - protectedObstacleRadius_deg^2);
protectedArcAngle_rad = pi - 2 * acos( ...
    protectedObstacleRadius_deg / endpointRadius_deg);
absoluteDistanceLowerBound_deg = 2 * tangentLength_deg + ...
    protectedObstacleRadius_deg * protectedArcAngle_rad;
absoluteTimeLowerBound_s = 7;
reference = struct( ...
    "absoluteDistanceLowerBound_deg", ...
        absoluteDistanceLowerBound_deg, ...
    "absoluteTimeLowerBound_s", absoluteTimeLowerBound_s, ...
    "maximumVerifiedPathLength_deg", 22.30, ...
    "maximumVerifiedCompletionTime_s", 10.0, ...
    "maximumVerifiedCombinedRatio", 1.23);
end
