function result = example17KinematicStateSpaceStudy(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   result = example17KinematicStateSpaceStudy()
%   result = example17KinematicStateSpaceStudy(viewOptions)
%**************************************************************************
% PURPOSE
%   - Compare the established waypoint start-stop profile with an
%     experimental Dijkstra search that carries path speed through turns.
%   - Verify the winning progress, velocity, time, and acceleration-action
%     states against their discrete physical equations and exact polygons.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Partial animation options. FigureVisible is shared by study plots.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Common problem, both plans, physical diagnostics, and view handles.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build One Unambiguous Circular Detour
% A five-degree circle touches the lower elevation boundary. With the
% one-degree safety margin, a legal command cannot squeeze underneath it;
% both planners must solve the same upper detour instead of choosing
% opposite sides of a symmetric obstacle.
if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 180, ...
    "MaximumDisplayedSlices", 40, ...
    "PauseSeconds", 0.01, ...
    "ShowFuturePath", true));
time_s = (0:0.25:20).';
circleAngle_rad = linspace(0, 2 * pi, 181).';
circleAzimuth_deg = 5 * cos(circleAngle_rad);
circleElevation_deg = 5 * sin(circleAngle_rad);
azElData = makeAzElObstacleData( ...
    "Static five-degree circular obstacle", time_s, ...
    circleAzimuth_deg, circleElevation_deg);

%% Section 2: Define One Request & Two Motion Policies
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-20 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [20 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-22 22], ...
    "elevation_deg", [-5 12], ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [2 2]);
commonOptions = struct( ...
    "SampleTime_s", 0.05, ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", 1, ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "FallbackToProfile", false, ...
    "MaxSearchTime_s", 20, ...
    "MaxExpansions", 300000, ...
    "MaximumVerticesPerRegion", 500);

% The study lattice is deliberately tied to the constant-acceleration
% equations. A 0.25-degree progress cell and 0.5-second step create a
% 2 deg/s^2 acceleration action and a 1 deg/s velocity increment:
%
%   acceleration step = 2 * progress step / time step^2
%   velocity step     = acceleration step * time step
studyOptions = commonOptions;
studyOptions.MotionMode = "pathStateSpaceKinematic";
studyOptions.KinematicTimeStep_s = 0.5;
studyOptions.KinematicProgressStep_deg = 0.25;
baselineOptions = commonOptions;
baselineOptions.MotionMode = "profile";

%% Section 3: Run The Physical-State Study & Existing Baseline
studyPlan = planAzElDijkstra( ...
    azElData, initialState, goalState, limits, studyOptions);
if ~studyPlan.success
    error("example17KinematicStateSpaceStudy:StudyFailed", ...
        "Velocity-state Dijkstra failed: %s", studyPlan.message);
end
baselinePlan = planAzElDijkstra( ...
    azElData, initialState, goalState, limits, baselineOptions);
if ~baselinePlan.success
    error("example17KinematicStateSpaceStudy:BaselineFailed", ...
        "Start-stop baseline failed: %s", baselinePlan.message);
end
if studyPlan.method ~= "pathStateSpaceKinematicDijkstra" || ...
        studyPlan.retiming.MotionStyle ~= "pathStateSpaceKinematic"
    error("example17KinematicStateSpaceStudy:WrongStudyMode", ...
        "The study silently selected a different motion policy.");
end

%% Section 4: Independently Validate Both Commands
studyBlocked = queryAzElTimeObstacle(studyPlan.obstacleField, ...
    studyPlan.position_deg(:, 1), studyPlan.position_deg(:, 2), ...
    studyPlan.time_s, struct( ...
    "SafetyMarginDeg", studyOptions.SafetyMargin_deg, ...
    "TimePaddingSamples", studyPlan.options.TimePaddingSamples));
baselineBlocked = queryAzElTimeObstacle(baselinePlan.obstacleField, ...
    baselinePlan.position_deg(:, 1), baselinePlan.position_deg(:, 2), ...
    baselinePlan.time_s, struct( ...
    "SafetyMarginDeg", baselineOptions.SafetyMargin_deg, ...
    "TimePaddingSamples", baselinePlan.options.TimePaddingSamples));
if any(studyBlocked) || any(baselineBlocked)
    error("example17KinematicStateSpaceStudy:Collision", ...
        "Study/baseline blocked samples: %d/%d.", ...
        nnz(studyBlocked), nnz(baselineBlocked));
end

%% Section 5: Audit The Physical State Receipts
stateSearch = studyPlan.retiming.StateSpaceSearch;
progressResidual_deg = diff(stateSearch.ProgressDistance_deg) - ...
    0.5 * (stateSearch.PathSpeed_deg_s(1:end - 1) + ...
    stateSearch.PathSpeed_deg_s(2:end)) * stateSearch.TimeStep_s;
velocityResidual_deg_s = diff(stateSearch.PathSpeed_deg_s) - ...
    stateSearch.AccelerationCommand_deg_s2 * stateSearch.TimeStep_s;
maximumProgressResidual_deg = max(abs(progressResidual_deg));
maximumVelocityResidual_deg_s = max(abs(velocityResidual_deg_s));

studyMovingIndices = find(~studyPlan.isWaiting);
baselineMovingIndices = find(~baselinePlan.isWaiting);
studyInteriorWait = studyPlan.isWaiting( ...
    studyMovingIndices(1):studyMovingIndices(end));
baselineInteriorWait = baselinePlan.isWaiting( ...
    baselineMovingIndices(1):baselineMovingIndices(end));
studyInteriorStopCount = nnz(diff( ...
    [false; studyInteriorWait; false]) == 1);
baselineInteriorStopCount = nnz(diff( ...
    [false; baselineInteriorWait; false]) == 1);
studyCompletionTime_s = studyPlan.retiming.MinimumManeuverTime_s;
baselineCompletionTime_s = baselinePlan.retiming.MinimumManeuverTime_s;
motionTimeRatio = studyCompletionTime_s / baselineCompletionTime_s;
searchTimeRatio = studyPlan.searchElapsed_s / ...
    max(baselinePlan.searchElapsed_s, eps);

% The study is successful only when its physical receipts close exactly,
% it carries velocity through the detour, and that continuity produces a
% genuinely earlier completion than the existing start-stop command.
if maximumProgressResidual_deg > 1e-10 || ...
        maximumVelocityResidual_deg_s > 1e-10
    error("example17KinematicStateSpaceStudy:DynamicsResidual", ...
        "Discrete progress/velocity residuals are %.3g deg and %.3g deg/s.", ...
        maximumProgressResidual_deg, maximumVelocityResidual_deg_s);
end
if studyInteriorStopCount ~= 0 || baselineInteriorStopCount < 1 || ...
        studyCompletionTime_s >= baselineCompletionTime_s - 0.5
    error("example17KinematicStateSpaceStudy:NoMotionImprovement", ...
        ["Expected zero study stops and an earlier finish; measured " ...
        "%d/%d stops and %.3f/%.3f s."], ...
        studyInteriorStopCount, baselineInteriorStopCount, ...
        studyCompletionTime_s, baselineCompletionTime_s);
end

diagnostics = struct( ...
    "studyBlockedSampleCount", nnz(studyBlocked), ...
    "baselineBlockedSampleCount", nnz(baselineBlocked), ...
    "studyInteriorStopCount", studyInteriorStopCount, ...
    "baselineInteriorStopCount", baselineInteriorStopCount, ...
    "studyCompletionTime_s", studyCompletionTime_s, ...
    "baselineCompletionTime_s", baselineCompletionTime_s, ...
    "motionTimeRatio", motionTimeRatio, ...
    "searchTimeRatio", searchTimeRatio, ...
    "maximumProgressResidual_deg", maximumProgressResidual_deg, ...
    "maximumVelocityResidual_deg_s", maximumVelocityResidual_deg_s, ...
    "physicalStateDimensionCount", ...
        numel(stateSearch.StateDimensionNames), ...
    "expandedPhysicalStateCount", stateSearch.ExpandedNodeCount, ...
    "generatedPhysicalStateCount", stateSearch.GeneratedNodeCount);

%% Section 6: Animate The Study & Plot The Comparison
view = animateAzElAvoidancePlan(azElData, studyPlan, viewOptions);
comparisonFigure = figure( ...
    "Color", "w", ...
    "Visible", viewOptions.FigureVisible, ...
    "Name", "Example 17 - physical-state motion study", ...
    "Position", [100 80 1350 780]);
comparisonLayout = tiledlayout(comparisonFigure, 2, 1, ...
    "TileSpacing", "compact", "Padding", "compact");
title(comparisonLayout, sprintf([ ...
    'Velocity-state Dijkstra %.1f s vs start-stop %.1f s | ' ...
    'motion ratio %.3f'], studyCompletionTime_s, ...
    baselineCompletionTime_s, motionTimeRatio));

pathAxes = nexttile(comparisonLayout, 1);
hold(pathAxes, "on");
plot(pathAxes, circleAzimuth_deg, circleElevation_deg, ...
    "Color", [0 0.45 0.74], "LineWidth", 2, ...
    "DisplayName", "Circular obstacle");
plot(pathAxes, baselinePlan.positionUnwrapped_deg(:, 1), ...
    baselinePlan.positionUnwrapped_deg(:, 2), "--", ...
    "Color", [0.45 0.45 0.45], "LineWidth", 1.8, ...
    "DisplayName", "Start-stop path");
plot(pathAxes, studyPlan.positionUnwrapped_deg(:, 1), ...
    studyPlan.positionUnwrapped_deg(:, 2), ...
    "Color", [0.85 0.33 0.10], "LineWidth", 2.5, ...
    "DisplayName", "Velocity-state path");
axis(pathAxes, "equal");
xlim(pathAxes, limits.azimuth_deg);
ylim(pathAxes, [-6 11]);
grid(pathAxes, "on");
xlabel(pathAxes, "Azimuth (deg)");
ylabel(pathAxes, "Elevation (deg)");
legend(pathAxes, "Location", "eastoutside");

speedAxes = nexttile(comparisonLayout, 2);
hold(speedAxes, "on");
baselineSpeed_deg_s = hypot( ...
    baselinePlan.velocity_deg_s(:, 1), ...
    baselinePlan.velocity_deg_s(:, 2));
studySpeed_deg_s = hypot(studyPlan.velocity_deg_s(:, 1), ...
    studyPlan.velocity_deg_s(:, 2));
plot(speedAxes, baselinePlan.time_s - initialState.time_s, ...
    baselineSpeed_deg_s, "--", "Color", [0.45 0.45 0.45], ...
    "LineWidth", 1.8, "DisplayName", "Start-stop speed");
plot(speedAxes, studyPlan.time_s - initialState.time_s, ...
    studySpeed_deg_s, "Color", [0.85 0.33 0.10], ...
    "LineWidth", 2.2, "DisplayName", "Velocity-state speed");
grid(speedAxes, "on");
xlabel(speedAxes, "Elapsed time (s)");
ylabel(speedAxes, "Angular speed (deg/s)");
legend(speedAxes, "Location", "eastoutside");

kinematics = plotAzElPlanKinematics(studyPlan, struct( ...
    "FigureVisible", viewOptions.FigureVisible, ...
    "Title", "Example 17 - velocity-state command kinematics"));
result = struct( ...
    "azElData", azElData, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits, ...
    "studyOptions", studyOptions, ...
    "baselineOptions", baselineOptions, ...
    "studyPlan", studyPlan, ...
    "baselinePlan", baselinePlan, ...
    "diagnostics", diagnostics, ...
    "view", view, ...
    "comparisonFigure", comparisonFigure, ...
    "comparisonAxes", [pathAxes speedAxes], ...
    "kinematics", kinematics);

fprintf("Kinematic state-space motion study:\n");
fprintf("  Motion completion: %.3f s state-space / %.3f s start-stop\n", ...
    studyCompletionTime_s, baselineCompletionTime_s);
fprintf("  Interior stops: %d state-space / %d start-stop\n", ...
    studyInteriorStopCount, baselineInteriorStopCount);
fprintf("  Motion-time ratio: %.6f (smaller is better)\n", ...
    motionTimeRatio);
fprintf("  Search-time ratio: %.3f (study cost made explicit)\n", ...
    searchTimeRatio);
fprintf("  Physical states expanded/generated: %d/%d\n", ...
    stateSearch.ExpandedNodeCount, stateSearch.GeneratedNodeCount);
fprintf("  Progress/velocity equation residuals: %.3g deg / %.3g deg/s\n", ...
    maximumProgressResidual_deg, maximumVelocityResidual_deg_s);
end
