function result = example14MovingRendezvousAndTrail(viewOptions)
%EXAMPLE14MOVINGRENDEZVOUSANDTRAIL Cross four traffic rows and chase a target.
%
% Twelve vehicles occupy four horizontal traffic rows. Each row contains two
% vehicles that travel in opposite phases and one vehicle that paces near an
% alternating row end. The target accelerates, slows, and curves upward
% through all four rows. The boresight independently plans through traffic,
% matches the target's nonzero velocity and acceleration, then chases it
% until the final pacing vehicle makes continued tracking unsafe.

if nargin < 1
    viewOptions = struct();
end

time_s = (0:0.5:76).';
targetPhaseAz = 0.12 * time_s;
targetPhaseEl = 0.11 * time_s - 0.40;
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [ ...
        -14 + 0.38 * time_s + 1.60 * sin(targetPhaseAz), ...
        -6 + 0.16 * time_s + 1.40 * sin(targetPhaseEl)], ...
    "velocity_deg_s", [ ...
        0.38 + 0.192 * cos(targetPhaseAz), ...
        0.16 + 0.154 * cos(targetPhaseEl)], ...
    "acceleration_deg_s2", [ ...
        -0.02304 * sin(targetPhaseAz), ...
        -0.01694 * sin(targetPhaseEl)]);

[vehicleData, trafficDiagnostics] = ...
    makeTwelveVehicleTraffic(time_s);
azElData = combineAzElObstacles(vehicleData);

startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-16.5 -8], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-18 18], ...
    "elevation_deg", [-9 9], ...
    "maxVelocity_deg_s", [2.2 2.2], ...
    "maxAcceleration_deg_s2", [1.2 1.2]);
options = struct( ...
    "EarliestInterceptTime_s", 44, ...
    "LatestInterceptTime_s", 56, ...
    "InterceptTimeStep_s", 4, ...
    "MaximumInterceptAttempts", 4, ...
    "PerAttemptMaxSearchTime_s", 20, ...
    "CatchTolerance_deg", 0.06, ...
    "CatchVelocityTolerance_deg_s", 0.015, ...
    "CatchAccelerationTolerance_deg_s2", 0.015, ...
    "MatchTargetVelocity", true, ...
    "MatchTargetAcceleration", true, ...
    "ContinueTrackingAfterIntercept", true, ...
    "TrackingEndTime_s", 74, ...
    "TrackingSampleTime_s", 0.2, ...
    "GridStep_deg", 2, ...
    "GridStepSchedule_deg", [4 2], ...
    "PrimitiveRadiusMultipliers", [1 2 3], ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.05, ...
    "CollisionCheckStep_s", 0.08, ...
    "SafetyMargin_deg", 0.12, ...
    "MaximumSafeIntervalSamples", 120, ...
    "MaxSearchTime_s", 20);

plan = planAzElMovingTargetIntercept( ...
    azElData, startState, target, limits, options);
if ~plan.success
    for attempt = reshape(plan.interceptAttempts, 1, [])
        fprintf('  Intercept %.1f s: %s\n', ...
            attempt.time_s, attempt.message);
    end
    error("example14MovingRendezvousAndTrail:NoIntercept", ...
        "Twelve-vehicle rendezvous failed: %s", plan.message);
end
if plan.catchVelocityError_deg_s > ...
        options.CatchVelocityTolerance_deg_s
    error("example14MovingRendezvousAndTrail:VelocityMismatch", ...
        "Capture velocity error is %.6f deg/s.", ...
        plan.catchVelocityError_deg_s);
end
if plan.catchAccelerationError_deg_s2 > ...
        options.CatchAccelerationTolerance_deg_s2
    error("example14MovingRendezvousAndTrail:AccelerationMismatch", ...
        "Capture acceleration error is %.6f deg/s^2.", ...
        plan.catchAccelerationError_deg_s2);
end
if ~plan.trackingSuccess || ~plan.trackingTerminatedByObstacle || ...
        plan.trackingEndTime_s - plan.interceptTime_s < 8
    error("example14MovingRendezvousAndTrail:UnexpectedTrackingEnd", ...
        "Expected at least eight seconds of chase before row-end traffic.");
end

blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blocked)
    error("example14MovingRendezvousAndTrail:Collision", ...
        "The twelve-vehicle command contains %d blocked samples.", ...
        nnz(blocked));
end

targetSpeed_deg_s = hypot( ...
    target.velocity_deg_s(:, 1), target.velocity_deg_s(:, 2));
diagnostics = trafficDiagnostics;
diagnostics.targetMinimumSpeed_deg_s = min(targetSpeed_deg_s);
diagnostics.targetMaximumSpeed_deg_s = max(targetSpeed_deg_s);
diagnostics.targetSpeedRange_deg_s = ...
    max(targetSpeed_deg_s) - min(targetSpeed_deg_s);
diagnostics.trackingDuration_s = ...
    plan.trackingEndTime_s - plan.interceptTime_s;
diagnostics.crossedRowCount = countCrossedRows( ...
    target.position_deg(:, 2), trafficDiagnostics.rowElevation_deg);

if diagnostics.vehicleCount ~= 12 || ...
        diagnostics.rowCount ~= 4 || ...
        diagnostics.crossedRowCount ~= 4 || ...
        diagnostics.totalDirectionReversals < 12
    error("example14MovingRendezvousAndTrail:TrafficConstruction", ...
        "The example did not construct four reversing three-vehicle rows.");
end

viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 300, ...
    "MaximumDisplayedSlices", 144, ...
    "PauseSeconds", 0.01, ...
    "MovingTarget", target));
view = animateAzElAvoidancePlan(azElData, plan, viewOptions);
result = struct( ...
    "azElData", azElData, ...
    "startState", startState, ...
    "target", target, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "diagnostics", diagnostics, ...
    "blockedSampleCount", nnz(blocked), ...
    "view", view);
fprintf([ ...
    'Twelve-vehicle rendezvous: crossed %d rows, capture %.1f s, ' ...
    'chase %.1f s, stop reason %s, target speed %.3f-%.3f deg/s.\n'], ...
    diagnostics.crossedRowCount, plan.interceptTime_s, ...
    diagnostics.trackingDuration_s, plan.trackingTerminationReason, ...
    diagnostics.targetMinimumSpeed_deg_s, ...
    diagnostics.targetMaximumSpeed_deg_s);
end

function [vehicles, diagnostics] = makeTwelveVehicleTraffic(time_s)
rowElevation_deg = [-5 -2 2 5];
vehicles = cell(12, 1);
velocityParts = cell(12, 1);
cursor = 0;
for row = 1:numel(rowElevation_deg)
    omega = 0.145 + 0.012 * row;
    phase = 0.55 * (row - 1);
    for laneVehicle = 1:2
        cursor = cursor + 1;
        opposingPhase = phase + (laneVehicle - 1) * pi;
        centerAzimuth = 11.4 * sin(omega * time_s + opposingPhase);
        centerElevation = rowElevation_deg(row) + ...
            0.18 * sin(0.08 * time_s + opposingPhase);
        vehicles{cursor} = movingRectangle( ...
            sprintf('Row %d crossing vehicle %d', row, laneVehicle), ...
            time_s, centerAzimuth, centerElevation, 0.75, 0.30);
        velocityParts{cursor} = ...
            11.4 * omega * cos(omega * time_s + opposingPhase);
    end
end

% The final four vehicles guard alternating ends of the four rows. Their
% inward/outward pacing creates late gaps instead of fixed end barriers.
for row = 1:numel(rowElevation_deg)
    cursor = cursor + 1;
    side = 1;
    if mod(row, 2) == 1
        side = -1;
    end
    omega = 0.19 + 0.01 * row;
    phase = 0.80 * row;
    inwardDistance = 1.35 + 1.15 * sin(omega * time_s + phase);
    centerAzimuth = side * (13.7 - inwardDistance);
    centerElevation = rowElevation_deg(row) + ...
        0.48 * sin(0.13 * time_s + phase);
    vehicles{cursor} = movingRectangle( ...
        sprintf('Row %d end pacing vehicle', row), ...
        time_s, centerAzimuth, centerElevation, 0.68, 0.38);
    velocityParts{cursor} = ...
        -side * 1.15 * omega * cos(omega * time_s + phase);
end

reversals = cellfun(@countDirectionReversals, velocityParts);
diagnostics = struct( ...
    "vehicleCount", numel(vehicles), ...
    "rowCount", numel(rowElevation_deg), ...
    "vehiclesPerRow", 3, ...
    "rowElevation_deg", rowElevation_deg, ...
    "directionReversalsByVehicle", reversals, ...
    "totalDirectionReversals", sum(reversals), ...
    "endPacingVehicleIndices", 9:12);
end

function data = movingRectangle( ...
        name, time_s, centerAzimuth, centerElevation, ...
        halfWidth, halfHeight)
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    azimuth{k} = centerAzimuth(k) + ...
        halfWidth * [-1; 1; 1; -1; -1];
    elevation{k} = centerElevation(k) + ...
        halfHeight * [-1; -1; 1; 1; -1];
end
data = makeAzElObstacleData(name, time_s, azimuth, elevation);
end

function count = countDirectionReversals(velocity)
signValue = sign(velocity(:));
signValue(signValue == 0) = 1;
count = nnz(diff(signValue) ~= 0);
end

function count = countCrossedRows(targetElevation_deg, rowElevation_deg)
minimum = min(targetElevation_deg);
maximum = max(targetElevation_deg);
count = nnz(rowElevation_deg >= minimum & rowElevation_deg <= maximum);
end
