function result = example05FiveTurnSpiral()
%EXAMPLE05FIVETURNSPIRAL Enter the center of a five-turn spiral.

problem = makeFiveTurnSpiralGauntlet();

result = runAzElGauntletCase("Gauntlet 1", ...
    "autonomously enter a five-turn spiral", problem.azElData, ...
    problem.startState, problem.stopState, problem.limits, ...
    problem.options);
hasDirectionHint = isfield( ...
    result.plan.options, "DirectionAngles_deg") && ...
    ~isempty(result.plan.options.DirectionAngles_deg);
if result.plan.method ~= "adaptiveGoalRootedDijkstra" || ...
        isfield(result.plan.options, "GuidePath_deg") || hasDirectionHint
    error("example05FiveTurnSpiral:ExternalGuideUsed", ...
        "The spiral test must use unguided goal-rooted Dijkstra.");
end
routePosition_deg = result.plan.positionUnwrapped_deg;
radialDistance_deg = hypot( ...
    routePosition_deg(:, 1), routePosition_deg(:, 2));
% Exclude only the final approach to the origin, where polar angle is
% undefined. A larger cutoff would incorrectly discard the inner turns.
insideSpiral = radialDistance_deg >= 0.75;
polarAngle_rad = unwrap(atan2(routePosition_deg(insideSpiral, 2), ...
    routePosition_deg(insideSpiral, 1)));
result.diagnostics.windingTurns = abs( ...
    polarAngle_rad(end) - polarAngle_rad(1)) / (2 * pi);
if result.diagnostics.windingTurns < 4.0
    error("example05FiveTurnSpiral:InsufficientTurns", ...
        "The path accumulated only %.2f spiral turns.", ...
        result.diagnostics.windingTurns);
end
movingSample = ~result.plan.isWaiting;
lastMovingSample = find(movingSample, 1, "last");
result.diagnostics.motionCompletionTime_s = ...
    result.plan.time_s(lastMovingSample);
fprintf("  Spiral turns followed: %.2f\n", ...
    result.diagnostics.windingTurns);
fprintf("  Motion complete at %.1f s; topology search %.2f s.\n", ...
    result.diagnostics.motionCompletionTime_s, ...
    result.plan.topologySearch.SearchElapsed_s);
end
