function result = example16NoWrapRisingDiskEfficiency(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   result = example16NoWrapRisingDiskEfficiency()
%   result = example16NoWrapRisingDiskEfficiency(viewOptions)
%**************************************************************************
% PURPOSE
%   - Demonstrate a smooth, nearly shortest no-wrap crossing from -175 to
%     +175 degrees around one large, slowly rising obstacle.
%   - Compare every run with stored absolute path-length and completion-time
%     lower bounds, plus the best verified planner result from this example.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Partial animation options. FigureVisible is also applied to the
%       equal-scale geometry and position/velocity/acceleration reports.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Problem inputs, successful plan, stored reference, efficiency
%       ratios, smoothness diagnostics, and graphics handles.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Draw One Large Disk That Slowly Moves Up
% This example deliberately uses a full -180-to-180 azimuth range but turns
% wrapping off. The solver must therefore travel roughly 350 degrees across
% the plot; it cannot take the tempting 10-degree seam shortcut.
if nargin < 1
    viewOptions = struct();
end
viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 240, ...
    "MaximumDisplayedSlices", 90, ...
    "PauseSeconds", 0.01, ...
    "ShowFuturePath", true, ...
    "ShowObstacleSlices", true, ...
    "ObstacleFaceAlpha", 0.08));

obstacleRadius_deg = 35;
obstacleRiseRate_deg_s = 0.02;
missionEndTime_s = 45;
time_s = (0:0.25:missionEndTime_s).';
circleAngle_rad = linspace(0, 2 * pi, 361).';
obstacleAzimuth_deg = cell(numel(time_s), 1);
obstacleElevation_deg = cell(numel(time_s), 1);
for timeIndex = 1:numel(time_s)
    centerElevation_deg = obstacleRiseRate_deg_s * time_s(timeIndex);
    obstacleAzimuth_deg{timeIndex} = ...
        obstacleRadius_deg * cos(circleAngle_rad);
    obstacleElevation_deg{timeIndex} = centerElevation_deg + ...
        obstacleRadius_deg * sin(circleAngle_rad);
end
azElData = makeAzElObstacleData( ...
    "Large disk rising at 0.02 deg/s", time_s, ...
    obstacleAzimuth_deg, obstacleElevation_deg);

%% Section 2: State The No-Wrap, Rest-To-Rest Planning Request
% The elevation range exposes the complete 35-degree-radius circle. Its
% one-degree safety envelope extends to -36 degrees, just beyond the
% -35-degree lower limit. Even after the slow rise, that safety envelope
% still overlaps the lower boundary at the deadline. The full circle is
% therefore visible, but no legal path can pass underneath it. This removes
% the usual above-versus-below ambiguity and makes the absolute upper-route
% distance available in closed form.
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-175 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", [175 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-180 180], ...
    "elevation_deg", [-35 90], ...
    "maxVelocity_deg_s", [12 12], ...
    "maxAcceleration_deg_s2", [6 6]);
% This benchmark asks a moving-obstacle search to compare two grid levels.
% Sixty seconds keeps both passes available on slower machines.
options = struct( ...
    "SampleTime_s", 0.05, ...
    "GridStep_deg", 2.5, ...
    "GridStepSchedule_deg", [5 2.5], ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 2, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 60, ...
    "MaxExpansions", 1000000, ...
    "MaximumVerticesPerRegion", 500);

%% Section 3: Load The Stored Absolute-Best Reference
% Two independent lower bounds are useful here because degrees and seconds
% should never be added directly:
%
% 1. Path length: two tangents plus the short upper arc around the disk at
%    its lowest position. The one-degree safety margin is included. Since
%    the disk only rises, a real upper crossing cannot be shorter.
% 2. Completion time: the exact one-axis rest-to-rest time for the required
%    350-degree azimuth change. Obstacles and elevation motion can only add
%    work, so no valid two-axis command can finish sooner.
%
% The reference also freezes the best verified result produced when this
% benchmark was introduced. Future runs must remain close to the absolute
% bounds and may not silently regress beyond that verified result.
absoluteBest = storedNoWrapRisingDiskReference();

%% Section 4: Plan & Independently Check Every Returned Sample
plan = planAzElDijkstra( ...
    azElData, initialState, goalState, limits, options);
if ~plan.success
    error("example16NoWrapRisingDiskEfficiency:NoPath", ...
        "Planner failed: %s", plan.message);
end
if plan.motionPlanning.RequestedMode ~= "jointParetoKinematic" || ...
        ~plan.motionPlanning.ParetoRefinementAttempted || ...
        ~plan.motionPlanning.ParetoRefinementSucceeded
    error("example16NoWrapRisingDiskEfficiency:WrongMotionMode", ...
        "The example must run joint bounded-jerk search followed by " + ...
        "continuous Pareto refinement.");
end
if plan.options.AllowAzimuthWrap
    error("example16NoWrapRisingDiskEfficiency:WrappingEnabled", ...
        "This benchmark is meaningful only when azimuth wrapping is off.");
end

blocked = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blocked)
    error("example16NoWrapRisingDiskEfficiency:Collision", ...
        "The returned command contains %d blocked samples.", nnz(blocked));
end

% This second clearance calculation knows that the generated obstacle is a
% circle. It is intentionally independent of the packed-polygon query above
% and therefore catches mistakes in either representation.
obstacleCenterElevation_deg = ...
    obstacleRiseRate_deg_s * plan.time_s;
circleClearance_deg = hypot(plan.position_deg(:, 1), ...
    plan.position_deg(:, 2) - obstacleCenterElevation_deg) - ...
    obstacleRadius_deg;
minimumCircleClearance_deg = min(circleClearance_deg);
if minimumCircleClearance_deg < options.SafetyMargin_deg - 1e-3
    error("example16NoWrapRisingDiskEfficiency:InsufficientClearance", ...
        "Minimum independent circle clearance is only %.6f deg.", ...
        minimumCircleClearance_deg);
end

%% Section 5: Measure Distance, Time & Smooth Obstacle Transit
pathLengthRatio = plan.angularPathLength_deg / ...
    absoluteBest.minimumPathLength_deg;
completionTimeRatio = plan.retiming.MinimumManeuverTime_s / ...
    absoluteBest.minimumCompletionTime_s;
% The geometric mean gives distance and time equal dimensionless weight.
% A value of one would meet both lower bounds simultaneously; 1.02 means
% the combined result is about two percent above that unattainable ideal.
combinedEfficiencyRatio = sqrt( ...
    pathLengthRatio * completionTimeRatio);

movingSampleIndices = find(~plan.isWaiting);
firstMovingSample = movingSampleIndices(1);
lastMovingSample = movingSampleIndices(end);
interiorWaiting = plan.isWaiting(firstMovingSample:lastMovingSample);
interiorStopCount = nnz(diff([false; interiorWaiting; false]) == 1);

speed_deg_s = hypot( ...
    plan.velocity_deg_s(:, 1), plan.velocity_deg_s(:, 2));
isPassingObstacle = abs(plan.position_deg(:, 1)) <= ...
    obstacleRadius_deg + options.SafetyMargin_deg;
obstacleTransitSpeedRatio = min(speed_deg_s(isPassingObstacle)) / ...
    max(speed_deg_s(isPassingObstacle));
velocityStep_deg_s = diff(plan.velocity_deg_s, 1, 1);
maximumVelocityStep_deg_s = max(hypot( ...
    velocityStep_deg_s(:, 1), velocityStep_deg_s(:, 2)));

diagnostics = struct( ...
    "blockedSampleCount", nnz(blocked), ...
    "minimumCircleClearance_deg", minimumCircleClearance_deg, ...
    "pathLengthRatio", pathLengthRatio, ...
    "completionTimeRatio", completionTimeRatio, ...
    "combinedEfficiencyRatio", combinedEfficiencyRatio, ...
    "interiorStopCount", interiorStopCount, ...
    "obstacleTransitSpeedRatio", obstacleTransitSpeedRatio, ...
    "maximumVelocityStep_deg_s", maximumVelocityStep_deg_s, ...
    "maximumVelocity_deg_s", max(abs(plan.velocity_deg_s), [], 1), ...
    "maximumAcceleration_deg_s2", ...
        max(abs(plan.acceleration_deg_s2), [], 1));

if pathLengthRatio > absoluteBest.maximumPathLengthRatio || ...
        completionTimeRatio > absoluteBest.maximumCompletionTimeRatio || ...
        combinedEfficiencyRatio > ...
        absoluteBest.maximumCombinedEfficiencyRatio
    error("example16NoWrapRisingDiskEfficiency:EfficiencyRegression", ...
        ["Efficiency ratios regressed: path %.6f, time %.6f, " ...
        "combined %.6f."], pathLengthRatio, completionTimeRatio, ...
        combinedEfficiencyRatio);
end
if plan.angularPathLength_deg > ...
        absoluteBest.bestVerifiedPathLength_deg + ...
        absoluteBest.pathRegressionTolerance_deg || ...
        plan.retiming.MinimumManeuverTime_s > ...
        absoluteBest.bestVerifiedCompletionTime_s + ...
        absoluteBest.timeRegressionTolerance_s
    error("example16NoWrapRisingDiskEfficiency:StoredBestRegression", ...
        "The plan is worse than the stored verified distance/time result.");
end
if interiorStopCount ~= 0 || obstacleTransitSpeedRatio < 0.97
    error("example16NoWrapRisingDiskEfficiency:UnnecessarySlowdown", ...
        ["Expected no interior stop and at least 97%% of obstacle-zone " ...
        "speed; measured %d stops and %.2f%%."], ...
        interiorStopCount, 100 * obstacleTransitSpeedRatio);
end

%% Section 6: Animate, Plot Kinematics & Print The Report
view = animateAzElAvoidancePlan(azElData, plan, viewOptions);
hold(view.AzElAxes, "on");
referencePathHandle = plot(view.AzElAxes, ...
    absoluteBest.path_deg(:, 1), absoluteBest.path_deg(:, 2), ...
    "--", "Color", [0.1 0.1 0.1], "LineWidth", 1.4, ...
    "DisplayName", "Absolute distance lower bound");

% The synchronized animation must fit a 350-degree path beside its 3-D
% view, so its 2-D pane uses the available rectangle. This separate report
% uses an equal data scale: one azimuth degree and one elevation degree have
% the same screen length, proving that the generated obstacle is a circle.
geometryFigure = figure( ...
    "Color", "w", ...
    "Visible", viewOptions.FigureVisible, ...
    "Name", "Example 16 - equal-scale circular obstacle", ...
    "Position", [80 120 1700 500]);
geometryAxes = axes(geometryFigure);
hold(geometryAxes, "on");
initialCircleHandle = plot(geometryAxes, ...
    obstacleAzimuth_deg{1}, obstacleElevation_deg{1}, ...
    "Color", [0 0.45 0.74], "LineWidth", 2.2, ...
    "DisplayName", "Circular obstacle at t = 0 s");
finalCircleHandle = plot(geometryAxes, ...
    obstacleAzimuth_deg{end}, obstacleElevation_deg{end}, ...
    ":", "Color", [0 0.45 0.74], "LineWidth", 2.2, ...
    "DisplayName", "Circular obstacle at t = 45 s");
equalScaleReferenceHandle = plot(geometryAxes, ...
    absoluteBest.path_deg(:, 1), absoluteBest.path_deg(:, 2), ...
    "--", "Color", [0.15 0.15 0.15], "LineWidth", 1.5, ...
    "DisplayName", "Absolute distance lower bound");
solverPathHandle = plot(geometryAxes, ...
    plan.positionUnwrapped_deg(:, 1), plan.positionUnwrapped_deg(:, 2), ...
    "Color", [0.85 0.33 0.10], "LineWidth", 2.5, ...
    "DisplayName", "Solver path");
startHandle = plot(geometryAxes, ...
    initialState.position_deg(1), initialState.position_deg(2), ...
    "s", "MarkerFaceColor", [0.20 0.65 0.30], ...
    "MarkerEdgeColor", "k", "MarkerSize", 8, ...
    "DisplayName", "Start");
goalHandle = plot(geometryAxes, ...
    goalState.position_deg(1), goalState.position_deg(2), ...
    "d", "MarkerFaceColor", [0.85 0.20 0.20], ...
    "MarkerEdgeColor", "k", "MarkerSize", 8, ...
    "DisplayName", "Goal");
axis(geometryAxes, "equal");
xlim(geometryAxes, limits.azimuth_deg);
ylim(geometryAxes, [-40 50]);
grid(geometryAxes, "on");
xlabel(geometryAxes, "Azimuth (deg)");
ylabel(geometryAxes, "Elevation (deg)");
title(geometryAxes, sprintf([ ...
    'Equal-scale circular obstacle | path ratio %.6f | ' ...
    'time ratio %.6f | 0 interior stops'], ...
    pathLengthRatio, completionTimeRatio));
legend(geometryAxes, "Location", "eastoutside");
geometry = struct( ...
    "Figure", geometryFigure, ...
    "Axes", geometryAxes, ...
    "InitialCircle", initialCircleHandle, ...
    "FinalCircle", finalCircleHandle, ...
    "AbsoluteBestPath", equalScaleReferenceHandle, ...
    "SolverPath", solverPathHandle, ...
    "Start", startHandle, ...
    "Goal", goalHandle);

kinematics = plotAzElPlanKinematics(plan, struct( ...
    "FigureVisible", viewOptions.FigureVisible, ...
    "Title", "Example 16 - smooth no-wrap rising-disk crossing"));
result = struct( ...
    "azElData", azElData, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits, ...
    "options", options, ...
    "absoluteBest", absoluteBest, ...
    "plan", plan, ...
    "diagnostics", diagnostics, ...
    "view", view, ...
    "geometry", geometry, ...
    "referencePathHandle", referencePathHandle, ...
    "kinematics", kinematics);

fprintf("No-wrap rising-disk efficiency report:\n");
fprintf("  Path: %.6f deg / %.6f deg absolute bound = %.6f\n", ...
    plan.angularPathLength_deg, absoluteBest.minimumPathLength_deg, ...
    pathLengthRatio);
fprintf("  Time: %.6f s / %.6f s absolute bound = %.6f\n", ...
    plan.retiming.MinimumManeuverTime_s, ...
    absoluteBest.minimumCompletionTime_s, completionTimeRatio);
fprintf("  Combined equal-weight ratio: %.6f (1.0 is ideal)\n", ...
    combinedEfficiencyRatio);
fprintf("  Obstacle transit: %.2f%% speed retained, %d interior stops\n", ...
    100 * obstacleTransitSpeedRatio, interiorStopCount);
fprintf("  Independent clearance: %.6f deg; blocked samples: %d\n", ...
    minimumCircleClearance_deg, nnz(blocked));
end

function absoluteBest = storedNoWrapRisingDiskReference()
%% Section 0: Header & Readme
% SYNTAX
%   absoluteBest = storedNoWrapRisingDiskReference()
%**************************************************************************
% PURPOSE
%   - Keep the analytic lower bounds, reference path, accepted ratios, and
%     verified regression baseline beside the example that depends on them.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - absoluteBest (scalar struct)
%       Stored path/time certificates and comparison tolerances.
%**************************************************************************
% UNITS
%   - Path values are degrees; time values are seconds.
endpointAzimuthMagnitude_deg = 175;
inflatedObstacleRadius_deg = 36;
minimumPathLength_deg = 357.432168737952;
minimumCompletionTime_s = 31.166666666667;

% Recalculate the two closed-form values before using the stored decimals.
% If a future edit changes scenario constants without updating this report,
% the example fails here instead of presenting an obsolete comparison.
calculatedPathLength_deg = 2 * sqrt( ...
    endpointAzimuthMagnitude_deg^2 - inflatedObstacleRadius_deg^2) + ...
    2 * inflatedObstacleRadius_deg * asin( ...
    inflatedObstacleRadius_deg / endpointAzimuthMagnitude_deg);
horizontalTravel_deg = 2 * endpointAzimuthMagnitude_deg;
maximumAzimuthRate_deg_s = 12;
maximumAzimuthAcceleration_deg_s2 = 6;
calculatedCompletionTime_s = horizontalTravel_deg / ...
    maximumAzimuthRate_deg_s + maximumAzimuthRate_deg_s / ...
    maximumAzimuthAcceleration_deg_s2;
if abs(calculatedPathLength_deg - minimumPathLength_deg) > 1e-12 || ...
        abs(calculatedCompletionTime_s - ...
        minimumCompletionTime_s) > 1e-12
    error("example16NoWrapRisingDiskEfficiency:StaleReference", ...
        "Stored absolute-best constants no longer match their derivation.");
end

contactAzimuthMagnitude_deg = inflatedObstacleRadius_deg^2 / ...
    endpointAzimuthMagnitude_deg;
contactElevation_deg = inflatedObstacleRadius_deg * sqrt(1 - ...
    (inflatedObstacleRadius_deg / endpointAzimuthMagnitude_deg)^2);
leftContact_deg = [-contactAzimuthMagnitude_deg contactElevation_deg];
rightContact_deg = [contactAzimuthMagnitude_deg contactElevation_deg];
lineFraction = linspace(0, 1, 301).';
leftLine_deg = [-endpointAzimuthMagnitude_deg 0] + ...
    lineFraction .* (leftContact_deg - ...
    [-endpointAzimuthMagnitude_deg 0]);
leftContactAngle_rad = atan2( ...
    leftContact_deg(2), leftContact_deg(1));
rightContactAngle_rad = atan2( ...
    rightContact_deg(2), rightContact_deg(1));
arcAngle_rad = linspace( ...
    leftContactAngle_rad, rightContactAngle_rad, 301).';
arc_deg = inflatedObstacleRadius_deg * ...
    [cos(arcAngle_rad), sin(arcAngle_rad)];
rightLine_deg = rightContact_deg + lineFraction .* ...
    ([endpointAzimuthMagnitude_deg 0] - rightContact_deg);
referencePath_deg = [ ...
    leftLine_deg; arc_deg(2:end, :); rightLine_deg(2:end, :)];

absoluteBest = struct( ...
    "meaning", ["Independent mathematical lower bounds; no legal " ...
        "trajectory can have a smaller value."], ...
    "minimumPathLength_deg", minimumPathLength_deg, ...
    "minimumCompletionTime_s", minimumCompletionTime_s, ...
    "path_deg", referencePath_deg, ...
    "bestVerifiedPathLength_deg", 358.381467136, ...
    "bestVerifiedCompletionTime_s", 31.979592991, ...
    "maximumPathLengthRatio", 1.01, ...
    "maximumCompletionTimeRatio", 1.05, ...
    "maximumCombinedEfficiencyRatio", 1.03, ...
    "pathRegressionTolerance_deg", 0.01, ...
    "timeRegressionTolerance_s", 0.02);
end
