function result = example14MovingRendezvousAndTrail(viewOptions)
%EXAMPLE14MOVINGRENDEZVOUSANDTRAIL Match a moving target and trail safely.
%
% The boresight approaches around one static obstacle, captures a target
% with nonzero azimuth rate, and follows it until a second obstacle blocks
% the target path.

if nargin < 1
    viewOptions = struct();
end
time_s = (0:0.25:40).';
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [-2 + 0.3 * time_s, 3 + 0 * time_s], ...
    "velocity_deg_s", repmat([0.3 0], numel(time_s), 1), ...
    "acceleration_deg_s2", zeros(numel(time_s), 2));

approachBlocker = makeAzElObstacleData( ...
    "Approach blocker", time_s, ...
    [-2; 1; 1; -2; -2], [-1; -1; 1.5; 1.5; -1]);
trackingBlocker = makeAzElObstacleData( ...
    "Tracking blocker", time_s, ...
    [6.5; 8; 8; 6.5; 6.5], [2.2; 2.2; 3.8; 3.8; 2.2]);
azElData = combineAzElObstacles(approachBlocker, trackingBlocker);

startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-9 -3], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-15 15], ...
    "elevation_deg", [-8 8], ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1]);
options = struct( ...
    "EarliestInterceptTime_s", 12, ...
    "LatestInterceptTime_s", 20, ...
    "InterceptTimeStep_s", 2, ...
    "MaximumInterceptAttempts", 5, ...
    "PerAttemptMaxSearchTime_s", 12, ...
    "CatchTolerance_deg", 0.05, ...
    "CatchVelocityTolerance_deg_s", 0.01, ...
    "CatchAccelerationTolerance_deg_s2", 0.01, ...
    "MatchTargetVelocity", true, ...
    "MatchTargetAcceleration", true, ...
    "ContinueTrackingAfterIntercept", true, ...
    "TrackingEndTime_s", 38, ...
    "TrackingSampleTime_s", 0.2, ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", [2 1], ...
    "PrimitiveRadiusMultipliers", [1 2 4], ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.05, ...
    "SafetyMargin_deg", 0.15, ...
    "MaxSearchTime_s", 12);

plan = planAzElMovingTargetIntercept( ...
    azElData, startState, target, limits, options);
if ~plan.success
    error("example14MovingRendezvousAndTrail:NoIntercept", ...
        "Moving rendezvous failed: %s", plan.message);
end
if plan.catchVelocityError_deg_s > ...
        options.CatchVelocityTolerance_deg_s
    error("example14MovingRendezvousAndTrail:VelocityMismatch", ...
        "Capture velocity error is %.6f deg/s.", ...
        plan.catchVelocityError_deg_s);
end
if ~plan.trackingSuccess || ~plan.trackingTerminatedByObstacle
    error("example14MovingRendezvousAndTrail:UnexpectedTrackingEnd", ...
        "Expected safe tracking to end at the downstream obstacle.");
end
blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blocked)
    error("example14MovingRendezvousAndTrail:Collision", ...
        "The rendezvous command contains %d blocked samples.", ...
        nnz(blocked));
end

viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 220, ...
    "MaximumDisplayedSlices", 80, ...
    "PauseSeconds", 0.01, ...
    "MovingTarget", target));
view = animateAzElAvoidancePlan(azElData, plan, viewOptions);
result = struct( ...
    "azElData", azElData, ...
    "startState", startState, ...
    "target", target, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "blockedSampleCount", nnz(blocked), ...
    "view", view);
fprintf([ ...
    'Moving rendezvous: capture %.1f s at %.3f deg/s, ' ...
    'track to %.1f s, stop reason %s.\n'], ...
    plan.interceptTime_s, norm(plan.targetVelocityAtIntercept_deg_s), ...
    plan.trackingEndTime_s, plan.trackingTerminationReason);
end
