function result = example_simple_azEl_time_kinodynamic_dijkstra()
%% Section 0: Header & Readme
% SYNTAX
%   result = example_simple_azEl_time_kinodynamic_dijkstra()
%**************************************************************************
% PURPOSE
%   - Demonstrate the simple seven-coordinate Dijkstra lattice against a
%     gate that occupies the full elevation range and then disappears.
%   - Make true holding visible before the dynamically feasible slew.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planner result and visualization handles.
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.

%% Section 1: Build A Time-Varying Full-Height Gate
plannerRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(plannerRoot));
time_s = (0:8).';
azimuthBoundaryByTime_deg = cell(numel(time_s), 1);
elevationBoundaryByTime_deg = cell(numel(time_s), 1);
for timeIndex = 1:numel(time_s)
    if time_s(timeIndex) <= 2
        azimuthBoundaryByTime_deg{timeIndex} = [0.5; 1.5; 1.5; 0.5; 0.5];
        elevationBoundaryByTime_deg{timeIndex} = [-2; -2; 2; 2; -2];
    else
        azimuthBoundaryByTime_deg{timeIndex} = zeros(0, 1);
        elevationBoundaryByTime_deg{timeIndex} = zeros(0, 1);
    end
end
azElData = makeAzElObstacleData( ...
    "Gate clears after two seconds", time_s, ...
    azimuthBoundaryByTime_deg, elevationBoundaryByTime_deg);

%% Section 2: Define Exact Endpoint States And Limits
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
destinationState = struct( ...
    "time_s", 6, ...
    "position_deg", [2, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-2, 2], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [1, 1], ...
    "maxJerk_deg_s3", [1, 1]);
options = struct( ...
    "timeStep_s", 1, ...
    "positionStep_deg", [0.5, 0.5], ...
    "positionStepSchedule_deg", [4, 2, 1, 0.5], ...
    "velocityStep_deg_s", [0.5, 0.5], ...
    "accelerationStep_deg_s2", [1, 1], ...
    "positionTolerance_deg", [0.25, 0.25], ...
    "velocityTolerance_deg_s", [0.25, 0.25], ...
    "accelerationTolerance_deg_s2", [0.25, 0.25], ...
    "collisionCheckStep_s", 0.2, ...
    "maximumGeneratedStates", 50000, ...
    "maximumExpandedStates", 50000);

%% Section 3: Plan And Inspect The Search
plan = planSimpleAzElTimeKinodynamicDijkstra( ...
    azElData, initialState, destinationState, limits, options);
assert(plan.success, plan.message);
assert(any(plan.isWaiting), ...
    "The exact-time gate scenario should contain at least one true hold.");
fprintf("Simple Dijkstra expanded %d and generated %d states.\n", ...
    plan.expandedStateCount, plan.generatedStateCount);
fprintf("Trajectory cost %.1f s with %d true-hold samples.\n", ...
    plan.totalCost, nnz(plan.isWaiting));
fprintf("Grid refinement: %s deg; selected %.1f deg.\n", ...
    mat2str(plan.gridRefinement.Schedule_deg), ...
    plan.gridRefinement.SelectedPositionStep_deg);

%% Section 4: Visualize Occupancy, Search, And Kinematics
plotHandles = plotSimpleAzElTimeKinodynamicDijkstra(plan);
result = struct( ...
    "azElData", azElData, ...
    "initialState", initialState, ...
    "destinationState", destinationState, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "plotHandles", plotHandles);
end
