function result = example06StopGoGates()
%EXAMPLE06STOPGOGATES Pass three sequentially opening gates.

problem = makeStopGoGatesGauntlet();
openWindows = problem.geometry.openWindows_s;
stopState = problem.stopState;

result = runAzElGauntletCase( ...
    "Gauntlet 2", ...
    "stop-go-stop-go through timed gates", ...
    problem.azElData, problem.startState, stopState, ...
    problem.limits, problem.options);
waiting = result.plan.isWaiting;
result.diagnostics.waitingEpisodeCount = ...
    nnz(diff([false; waiting; false]) == 1);
firstSettledGoal = find( ...
    abs(result.plan.position_deg(:, 1) - ...
        stopState.position_deg(1)) <= 1e-9 & ...
    abs(result.plan.position_deg(:, 2) - ...
        stopState.position_deg(2)) <= 1e-9 & ...
    all(abs(result.plan.velocity_deg_s) <= 1e-9, 2), 1);
result.diagnostics.firstSettledGoalTime_s = ...
    result.plan.time_s(firstSettledGoal);
if result.diagnostics.waitingEpisodeCount < 3
    error("example06StopGoGates:TooFewStops", ...
        "Expected at least three stopped intervals, found %d.", ...
        result.diagnostics.waitingEpisodeCount);
end
waitedAfterFinalGate = waiting & ...
    result.plan.time_s > openWindows(end, 2) & ...
    result.plan.time_s < result.diagnostics.firstSettledGoalTime_s;
if any(waitedAfterFinalGate) || ...
        result.diagnostics.firstSettledGoalTime_s > 37.5 + 1e-9
    error("example06StopGoGates:LateFinalSlew", ...
        "The planner waited after clearing the final gate.");
end
fprintf("  Stopped intervals: %d\n", ...
    result.diagnostics.waitingEpisodeCount);
fprintf("  Final gate cleared and goal settled at %.1f s.\n", ...
    result.diagnostics.firstSettledGoalTime_s);
end
