function result = example09UTrapEscape()
%EXAMPLE09UTRAPESCAPE Move away from the goal to escape a U-trap.

problem = makeUTrapEscapeGauntlet();

result = runAzElGauntletCase( ...
    "Gauntlet 5", ...
    "U-trap escape by backtracking", ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
result.diagnostics.minimumAzimuth_deg = ...
    min(result.plan.positionUnwrapped_deg(:, 1));
result.diagnostics.minimumElevation_deg = ...
    min(result.plan.position_deg(:, 2));
result.diagnostics.maximumElevation_deg = ...
    max(result.plan.position_deg(:, 2));
if result.diagnostics.minimumAzimuth_deg > -6.25
    error("example09UTrapEscape:DidNotBacktrack", ...
        "The route did not move left far enough to escape the U-trap.");
end
if result.plan.angularPathLength_deg >= 33 || ...
        max(abs(result.plan.position_deg(:, 2))) >= 7
    error("example09UTrapEscape:LongEscape", ...
        "The planner did not find a compact wall-hugging escape.");
end
fprintf("  Furthest move away from goal: azimuth %.2f deg.\n", ...
    result.diagnostics.minimumAzimuth_deg);
fprintf("  Compact wall-hugging escape length: %.3f deg.\n", ...
    result.plan.angularPathLength_deg);
end
