function result = example05FiveTurnSpiral()
%% Section 0: Header & Readme
% SYNTAX
%   result = example05FiveTurnSpiral()
%**************************************************************************
% PURPOSE
%   - Verify that unguided reverse-Dijkstra/A* can enter a five-turn spiral.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planned example, animation handles, and winding diagnostics.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build The Spiral Planning Problem
time_s = (0:0.5:400).';
[wallAzimuth_deg, wallElevation_deg] = spiralWall( ...
    5, 2, 3, 0.4, 241);
azElData = makeAzElObstacleData("Five-turn spiral wall", time_s, ...
    wallAzimuth_deg, wallElevation_deg);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [18, 1.5], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goalState = struct( ...
    "time_s", 400, ...
    "position_deg", [0, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-20, 20], ...
    "elevation_deg", [-20, 20], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", 0.5, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 30, ...
    "MaxExpansions", 1000000, ...
    "MaximumVerticesPerRegion", 500);

%% Section 2: Plan Without External Guidance
result = runAzElGauntletCase("Gauntlet 1", ...
    "autonomously enter a five-turn spiral", azElData, ...
    initialState, goalState, limits, options);
if result.plan.method ~= ...
        "reverseDijkstraForwardKinodynamicAStar" || ...
        ~result.plan.diagnostics.reverseDijkstra.executed || ...
        ~result.plan.diagnostics.forwardAStar.executed || ...
        isfield(result.plan.options, "GuidePath_deg") || ...
        isfield(result.plan.options, "DirectionAngles_deg")
    error("example05FiveTurnSpiral:ExternalGuideUsed", ...
        "The spiral test must use the unguided unified planner.");
end

%% Section 3: Verify Winding & Motion Completion
routePosition_deg = result.plan.positionUnwrapped_deg;
radialDistance_deg = hypot( ...
    routePosition_deg(:, 1), routePosition_deg(:, 2));
% Exclude only the final approach to the origin, where polar angle is
% undefined. A larger cutoff would incorrectly discard the inner turns.
insideSpiral = radialDistance_deg >= 0.75;
polarAngle_rad = unwrap(atan2(routePosition_deg(insideSpiral, 2), ...
    routePosition_deg(insideSpiral, 1)));
result.diagnostics.windingTurns = abs( ...
    polarAngle_rad(end) - polarAngle_rad(1)) / (2 * pi);
if result.diagnostics.windingTurns < 4.0
    error("example05FiveTurnSpiral:InsufficientTurns", ...
        "The path accumulated only %.2f spiral turns.", ...
        result.diagnostics.windingTurns);
end
movingSample = ~result.plan.isWaiting;
lastMovingSample = find(movingSample, 1, "last");
result.diagnostics.motionCompletionTime_s = ...
    result.plan.time_s(lastMovingSample);
fprintf("  Spiral turns followed: %.2f\n", ...
    result.diagnostics.windingTurns);
fprintf("  Motion complete at %.1f s; topology search %.2f s.\n", ...
    result.diagnostics.motionCompletionTime_s, ...
    result.plan.diagnostics.forwardAStar.searchElapsed_s);
end

%% Section 4: Local Geometry Functions
function [azimuth_deg, elevation_deg] = spiralWall( ...
        turnCount, innerRadius_deg, turnSpacing_deg, ...
        wallHalfWidth_deg, sampleCount)
theta_rad = linspace(0, 2 * pi * turnCount, sampleCount).';
radius_deg = innerRadius_deg + ...
    turnSpacing_deg * theta_rad / (2 * pi);
centerAzimuth_deg = radius_deg .* cos(theta_rad);
centerElevation_deg = radius_deg .* sin(theta_rad);
tangentAzimuth_deg = gradient(centerAzimuth_deg);
tangentElevation_deg = gradient(centerElevation_deg);
tangentMagnitude_deg = hypot(tangentAzimuth_deg, tangentElevation_deg);
normalAzimuth = -tangentElevation_deg ./ tangentMagnitude_deg;
normalElevation = tangentAzimuth_deg ./ tangentMagnitude_deg;
leftAzimuth_deg = centerAzimuth_deg + ...
    wallHalfWidth_deg * normalAzimuth;
leftElevation_deg = centerElevation_deg + ...
    wallHalfWidth_deg * normalElevation;
rightAzimuth_deg = centerAzimuth_deg - ...
    wallHalfWidth_deg * normalAzimuth;
rightElevation_deg = centerElevation_deg - ...
    wallHalfWidth_deg * normalElevation;
azimuth_deg = [ ...
    leftAzimuth_deg; flipud(rightAzimuth_deg); leftAzimuth_deg(1)];
elevation_deg = [ ...
    leftElevation_deg; flipud(rightElevation_deg); leftElevation_deg(1)];
end
