function result = example06StopGoGates()
%EXAMPLE06STOPGOGATES Pass three sequentially opening gates.

time_s = (0:0.5:45).';
gateCenters = [-6, 0, 6];
openWindows = [8, 12; 20, 24; 32, 36];
obstacles = cell(3, 1);
for gateIndex = 1:3
    [azimuth, elevation] = temporalGate( ...
        time_s, gateCenters(gateIndex), ...
        openWindows(gateIndex, :));
    obstacles{gateIndex} = makeAzElObstacleData( ...
        "Gate " + gateIndex, time_s, azimuth, elevation);
end
azElData = combineAzElObstacles(obstacles);
startState = boundaryState(0, [-12, 0]);
stopState = boundaryState(45, [12, 0]);
limits = struct( ...
    "azimuth_deg", [-14, 14], ...
    "elevation_deg", [-1, 1], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [2, 2]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GuideGridStep_deg", 0.5, ...
    "SafetyMargin_deg", 0.1, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 60, ...
    "GuideMaxExpansions", 750000);

result = runAzElGauntletCase( ...
    "Gauntlet 2", ...
    "stop-go-stop-go through timed gates", ...
    azElData, startState, stopState, limits, options);
waiting = result.plan.isWaiting;
result.diagnostics.waitingEpisodeCount = ...
    nnz(diff([false; waiting; false]) == 1);
firstSettledGoal = find( ...
    abs(result.plan.position_deg(:, 1) - ...
        stopState.position_deg(1)) <= 1e-9 & ...
    abs(result.plan.position_deg(:, 2) - ...
        stopState.position_deg(2)) <= 1e-9 & ...
    all(abs(result.plan.velocity_deg_s) <= 1e-9, 2), 1);
result.diagnostics.firstSettledGoalTime_s = ...
    result.plan.time_s(firstSettledGoal);
if result.diagnostics.waitingEpisodeCount < 3
    error("example06StopGoGates:TooFewStops", ...
        "Expected at least three stopped intervals, found %d.", ...
        result.diagnostics.waitingEpisodeCount);
end
waitedAfterFinalGate = waiting & ...
    result.plan.time_s > openWindows(end, 2) & ...
    result.plan.time_s < result.diagnostics.firstSettledGoalTime_s;
if any(waitedAfterFinalGate) || ...
        result.diagnostics.firstSettledGoalTime_s > 37.5 + 1e-9
    error("example06StopGoGates:LateFinalSlew", ...
        "The planner waited after clearing the final gate.");
end
fprintf("  Stopped intervals: %d\n", ...
    result.diagnostics.waitingEpisodeCount);
fprintf("  Final gate cleared and goal settled at %.1f s.\n", ...
    result.diagnostics.firstSettledGoalTime_s);
end

function [azimuth, elevation] = temporalGate( ...
        time_s, centerAzimuth, openWindow)
sampleCount = numel(time_s);
azimuth = cell(sampleCount, 1);
elevation = cell(sampleCount, 1);
closedAzimuth = centerAzimuth + 0.75 * [-1; 1; 1; -1; -1];
closedElevation = [-2; -2; 2; 2; -2];
for sample = 1:sampleCount
    if time_s(sample) >= openWindow(1) && ...
            time_s(sample) <= openWindow(2)
        azimuth{sample} = zeros(0, 1);
        elevation{sample} = zeros(0, 1);
    else
        azimuth{sample} = closedAzimuth;
        elevation{sample} = closedElevation;
    end
end
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end
