function result = example09UTrapEscape()
%% Section 0: Header & Readme
% SYNTAX
%   result = example09UTrapEscape()
%**************************************************************************
% PURPOSE
%   - Verify that Dijkstra backtracks away from the goal to escape a U-trap.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planned example, animation handles, and backtracking diagnostics.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build The U-Shaped Obstacle
time_s = (0:0.5:60).';
regions = { ...
    [3, -6; 6, -6; 6, 6; 3, 6; 3, -6], ...
    [-6, 5; 6, 5; 6, 6; -6, 6; -6, 5], ...
    [-6, -6; 6, -6; 6, -5; -6, -5; -6, -6]};
[azimuth_deg, elevation_deg] = joinRegions(regions);
azElData = makeAzElObstacleData( ...
    "U-shaped trap", time_s, azimuth_deg, elevation_deg);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goalState = struct( ...
    "time_s", 60, ...
    "position_deg", [15, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-10, 18], ...
    "elevation_deg", [-10, 10], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.125, ...
    "GridStepSchedule_deg", [1, 0.5, 0.25, 0.125], ...
    "SafetyMargin_deg", 0.25, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 60, ...
    "MaxExpansions", 1000000);

%% Section 2: Plan & Verify Backtracking Quality
result = runAzElGauntletCase( ...
    "Gauntlet 5", ...
    "U-trap escape by backtracking", ...
    azElData, initialState, goalState, limits, options);
result.diagnostics.minimumAzimuth_deg = ...
    min(result.plan.positionUnwrapped_deg(:, 1));
result.diagnostics.minimumElevation_deg = ...
    min(result.plan.position_deg(:, 2));
result.diagnostics.maximumElevation_deg = ...
    max(result.plan.position_deg(:, 2));
if result.diagnostics.minimumAzimuth_deg > -6.25
    error("example09UTrapEscape:DidNotBacktrack", ...
        "The route did not move left far enough to escape the U-trap.");
end
if result.plan.angularPathLength_deg >= 33 || ...
        max(abs(result.plan.position_deg(:, 2))) >= 7
    error("example09UTrapEscape:LongEscape", ...
        "The planner did not find a compact wall-hugging escape.");
end
fprintf("  Furthest move away from goal: azimuth %.2f deg.\n", ...
    result.diagnostics.minimumAzimuth_deg);
fprintf("  Compact wall-hugging escape length: %.3f deg.\n", ...
    result.plan.angularPathLength_deg);
end

%% Section 3: Local Geometry Functions
function [azimuth_deg, elevation_deg] = joinRegions(regions_deg)
regionCount = numel(regions_deg);
regionRowCount = zeros(regionCount, 1);
for regionIndex = 1:regionCount
    regionRowCount(regionIndex) = size(regions_deg{regionIndex}, 1);
end
packedRowCount = sum(regionRowCount) + regionCount - 1;
combinedBoundary_deg = nan(packedRowCount, 2);
nextOutputRow = 1;
for regionIndex = 1:regionCount
    outputRows = nextOutputRow:( ...
        nextOutputRow + regionRowCount(regionIndex) - 1);
    combinedBoundary_deg(outputRows, :) = regions_deg{regionIndex};
    nextOutputRow = outputRows(end) + 2;
end
azimuth_deg = combinedBoundary_deg(:, 1);
elevation_deg = combinedBoundary_deg(:, 2);
end
