function result = example06StopGoGates()
%% Section 0: Header & Readme
% SYNTAX
%   result = example06StopGoGates()
%**************************************************************************
% PURPOSE
%   - Verify explicit stop-go behavior through three sequentially open gates.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planned example, animation handles, and waiting diagnostics.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Sample The Timed Gates
time_s = (0:0.5:45).';
gateCenters_deg = [-6, 0, 6];
openWindows_s = [8, 12; 20, 24; 32, 36];
obstacles = cell(3, 1);
for gateIndex = 1:3
    [azimuth_deg, elevation_deg] = temporalGate( ...
        time_s, gateCenters_deg(gateIndex), ...
        openWindows_s(gateIndex, :));
    obstacles{gateIndex} = makeAzElObstacleData( ...
        "Gate " + gateIndex, time_s, azimuth_deg, elevation_deg);
end
azElData = combineAzElObstacles(obstacles);

%% Section 2: Define The Planning Request
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-12, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
stopState = struct( ...
    "time_s", 45, ...
    "position_deg", [12, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-14, 14], ...
    "elevation_deg", [-1, 1], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [2, 2]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", 0.1, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 60, ...
    "MaxExpansions", 750000);

%% Section 3: Plan & Verify Stop-Go Behavior
result = runAzElGauntletCase( ...
    "Gauntlet 2", ...
    "stop-go-stop-go through timed gates", ...
    azElData, startState, stopState, limits, options);
waiting = result.plan.isWaiting;
result.diagnostics.waitingEpisodeCount = ...
    nnz(diff([false; waiting; false]) == 1);
firstSettledGoal = find( ...
    abs(result.plan.position_deg(:, 1) - ...
        stopState.position_deg(1)) <= 1e-9 & ...
    abs(result.plan.position_deg(:, 2) - ...
        stopState.position_deg(2)) <= 1e-9 & ...
    all(abs(result.plan.velocity_deg_s) <= 1e-9, 2), 1);
result.diagnostics.firstSettledGoalTime_s = ...
    result.plan.time_s(firstSettledGoal);
if result.diagnostics.waitingEpisodeCount < 3
    error("example06StopGoGates:TooFewStops", ...
        "Expected at least three stopped intervals, found %d.", ...
        result.diagnostics.waitingEpisodeCount);
end
waitedAfterFinalGate = waiting & ...
    result.plan.time_s > openWindows_s(end, 2) & ...
    result.plan.time_s < result.diagnostics.firstSettledGoalTime_s;
if any(waitedAfterFinalGate) || ...
        result.diagnostics.firstSettledGoalTime_s > 37.5 + 1e-9
    error("example06StopGoGates:LateFinalSlew", ...
        "The planner waited after clearing the final gate.");
end
fprintf("  Stopped intervals: %d\n", ...
    result.diagnostics.waitingEpisodeCount);
fprintf("  Final gate cleared and goal settled at %.1f s.\n", ...
    result.diagnostics.firstSettledGoalTime_s);
end

%% Section 4: Local Geometry Functions
function [azimuth_deg, elevation_deg] = temporalGate( ...
        time_s, centerAzimuth_deg, openWindow_s)
sampleCount = numel(time_s);
azimuth_deg = cell(sampleCount, 1);
elevation_deg = cell(sampleCount, 1);
closedAzimuth_deg = centerAzimuth_deg + ...
    0.75 * [-1; 1; 1; -1; -1];
closedElevation_deg = [-2; -2; 2; 2; -2];
for sampleIndex = 1:sampleCount
    isInsideOpenWindow = time_s(sampleIndex) >= openWindow_s(1) && ...
        time_s(sampleIndex) <= openWindow_s(2);
    if isInsideOpenWindow
        azimuth_deg{sampleIndex} = zeros(0, 1);
        elevation_deg{sampleIndex} = zeros(0, 1);
    else
        azimuth_deg{sampleIndex} = closedAzimuth_deg;
        elevation_deg{sampleIndex} = closedElevation_deg;
    end
end
end
