function result = example08AlternatingSlalom()
%% Section 0: Header & Readme
% SYNTAX
%   result = example08AlternatingSlalom()
%**************************************************************************
% PURPOSE
%   - Verify alternating pass-side decisions through four static barriers.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planned example, animation handles, and crossing diagnostics.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build The Alternating Barriers
time_s = (0:0.5:60).';
barrierCenters_deg = [-9, -3, 3, 9];
passesAboveBarrier = [true, false, true, false];
obstacles = cell(numel(barrierCenters_deg), 1);
for obstacleIndex = 1:numel(barrierCenters_deg)
    [azimuth_deg, elevation_deg] = slalomBarrier( ...
        barrierCenters_deg(obstacleIndex), ...
        passesAboveBarrier(obstacleIndex));
    obstacles{obstacleIndex} = makeAzElObstacleData( ...
        "Slalom " + obstacleIndex, time_s, azimuth_deg, elevation_deg);
end
azElData = combineAzElObstacles(obstacles);

%% Section 2: Define The Planning Request
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-15, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
stopState = struct( ...
    "time_s", 60, ...
    "position_deg", [15, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-17, 17], ...
    "elevation_deg", [-7, 7], ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0.25, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 75, ...
    "MaxExpansions", 1000000);

%% Section 3: Plan & Verify Each Crossing Side
result = runAzElGauntletCase( ...
    "Gauntlet 4", ...
    "four-barrier alternating slalom", ...
    azElData, startState, stopState, limits, options);
routePosition_deg = result.plan.positionUnwrapped_deg;
crossingElevation_deg = zeros(size(barrierCenters_deg));
for obstacleIndex = 1:numel(barrierCenters_deg)
    [~, nearestSample] = min(abs( ...
        routePosition_deg(:, 1) - barrierCenters_deg(obstacleIndex)));
    crossingElevation_deg(obstacleIndex) = routePosition_deg( ...
        nearestSample, 2);
end
result.diagnostics.crossingElevation_deg = crossingElevation_deg;
expectedSign = [1, -1, 1, -1];
if any(sign(crossingElevation_deg) ~= expectedSign) || ...
        any(abs(crossingElevation_deg) < 1.25)
    error("example08AlternatingSlalom:WrongPassSide", ...
        "The route did not alternate through all four slalom openings.");
end
fprintf("  Crossing elevations: %s deg\n", ...
    mat2str(crossingElevation_deg, 3));
end

%% Section 4: Local Geometry Functions
function [azimuth_deg, elevation_deg] = slalomBarrier( ...
        centerAzimuth_deg, passAbove)
azimuth_deg = centerAzimuth_deg + 1.25 * [-1; 1; 1; -1; -1];
if passAbove
    elevation_deg = [-7; -7; 1; 1; -7];
else
    elevation_deg = [-1; -1; 7; 7; -1];
end
end
