function result = example07WrappedAzimuthSeam()
%% Section 0: Header & Readme
% SYNTAX
%   result = example07WrappedAzimuthSeam()
%**************************************************************************
% PURPOSE
%   - Verify continuous detouring across the periodic azimuth boundary.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planned example, animation handles, and seam diagnostics.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build The Wrapped Planning Problem
time_s = (0:0.5:30).';
[azimuth_deg, elevation_deg] = seamObstacle();
azElData = makeAzElObstacleData( ...
    "Wrapped seam blocker", time_s, azimuth_deg, elevation_deg);
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [170, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
stopState = struct( ...
    "time_s", 30, ...
    "position_deg", [-170, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-20, 20], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [2, 2]);
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", 0.5, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance", ...
    "MotionMode", "jointParetoKinematic", ...
    "PathFirstTimeScaling", "minimumTime", ...
    "JointKinematicAttemptTime_s", 1, ...
    "FallbackToProfile", true, ...
    "MaxSearchTime_s", 30);

%% Section 2: Plan & Verify Seam Continuity
result = runAzElGauntletCase( ...
    "Gauntlet 3", ...
    "wrapped-azimuth seam detour", ...
    azElData, startState, stopState, limits, options);
unwrappedAzimuth = result.plan.positionUnwrapped_deg(:, 1);
result.diagnostics.maximumUnwrappedStep_deg = ...
    max(abs(diff(unwrappedAzimuth)));
result.diagnostics.maximumElevationDetour_deg = ...
    max(abs(result.plan.position_deg(:, 2)));
if result.diagnostics.maximumUnwrappedStep_deg > 2 || ...
        result.diagnostics.maximumElevationDetour_deg < 5
    error("example07WrappedAzimuthSeam:InvalidDetour", ...
        "The seam path is discontinuous or did not clear the blocker.");
end
fprintf("  Maximum unwrapped step %.2f deg; elevation detour %.2f deg.\n", ...
    result.diagnostics.maximumUnwrappedStep_deg, ...
    result.diagnostics.maximumElevationDetour_deg);
end

%% Section 3: Local Geometry Functions
function [azimuth_deg, elevation_deg] = seamObstacle()
positiveRegion_deg = [ ...
    174, -5; ...
    180, -5; ...
    180, 5; ...
    174, 5; ...
    174, -5];
negativeRegion_deg = [ ...
    -180, -5; ...
    -174, -5; ...
    -174, 5; ...
    -180, 5; ...
    -180, -5];
combinedBoundary_deg = [ ...
    positiveRegion_deg; NaN, NaN; negativeRegion_deg];
azimuth_deg = combinedBoundary_deg(:, 1);
elevation_deg = combinedBoundary_deg(:, 2);
end
