function result = example14MovingRendezvousAndTrail(viewOptions)
%EXAMPLE14MOVINGRENDEZVOUSANDTRAIL Cross twelve traffic rows and chase a target.
%
% Forty-eight vehicles occupy twelve dense horizontal traffic rows. Each row
% is a compact four-vehicle convoy whose fixed spacing prevents overlap.
% Rows use different speeds and phases, and every convoy slows, reverses, and
% speeds up as it paces between road ends. Rows 9-12 form the end-pacing
% group. The target curves upward through all twelve rows; the boresight
% independently plans through traffic, matches its nonzero velocity and
% acceleration, and chases it until final-row traffic closes the gap.

if nargin < 1
    viewOptions = struct();
end

time_s = (0:0.5:76).';
targetPhaseAz = 0.12 * time_s;
targetPhaseEl = 0.11 * time_s - 0.40;
target = struct( ...
    "time_s", time_s, ...
    "position_deg", [ ...
        -14 + 0.38 * time_s + 1.60 * sin(targetPhaseAz), ...
        -6 + 0.16 * time_s + 1.40 * sin(targetPhaseEl)], ...
    "velocity_deg_s", [ ...
        0.38 + 0.192 * cos(targetPhaseAz), ...
        0.16 + 0.154 * cos(targetPhaseEl)], ...
    "acceleration_deg_s2", [ ...
        -0.02304 * sin(targetPhaseAz), ...
        -0.01694 * sin(targetPhaseEl)]);

[vehicleData, trafficDiagnostics] = ...
    makeCrossyRoadTraffic(time_s);
azElData = combineAzElObstacles(vehicleData);

startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-16.5 -8], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "azimuth_deg", [-18 18], ...
    "elevation_deg", [-9 9], ...
    "maxVelocity_deg_s", [2.2 2.2], ...
    "maxAcceleration_deg_s2", [1.2 1.2]);
options = struct( ...
    "EarliestInterceptTime_s", 48, ...
    "LatestInterceptTime_s", 56, ...
    "InterceptTimeStep_s", 4, ...
    "MaximumInterceptAttempts", 3, ...
    "PerAttemptMaxSearchTime_s", 120, ...
    "CatchTolerance_deg", 0.06, ...
    "CatchVelocityTolerance_deg_s", 0.015, ...
    "CatchAccelerationTolerance_deg_s2", 0.015, ...
    "MatchTargetVelocity", true, ...
    "MatchTargetAcceleration", true, ...
    "ContinueTrackingAfterIntercept", true, ...
    "TrackingEndTime_s", 74, ...
    "TrackingSampleTime_s", 0.2, ...
    "GridStep_deg", 2, ...
    "GridStepSchedule_deg", 2, ...
    "PrimitiveRadiusMultipliers", [1 2], ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.05, ...
    "CollisionCheckStep_s", 0.08, ...
    "SafetyMargin_deg", 0.12, ...
    "MaximumSafeIntervalSamples", 40, ...
    "MaxSearchTime_s", 120);

plan = planAzElMovingTargetIntercept( ...
    azElData, startState, target, limits, options);
if ~plan.success
    for attempt = reshape(plan.interceptAttempts, 1, [])
        fprintf('  Intercept %.1f s: %s\n', ...
            attempt.time_s, attempt.message);
    end
    error("example14MovingRendezvousAndTrail:NoIntercept", ...
        "Forty-eight-vehicle rendezvous failed: %s", plan.message);
end
if plan.catchVelocityError_deg_s > ...
        options.CatchVelocityTolerance_deg_s
    error("example14MovingRendezvousAndTrail:VelocityMismatch", ...
        "Capture velocity error is %.6f deg/s.", ...
        plan.catchVelocityError_deg_s);
end
if plan.catchAccelerationError_deg_s2 > ...
        options.CatchAccelerationTolerance_deg_s2
    error("example14MovingRendezvousAndTrail:AccelerationMismatch", ...
        "Capture acceleration error is %.6f deg/s^2.", ...
        plan.catchAccelerationError_deg_s2);
end
if ~plan.trackingSuccess || ~plan.trackingTerminatedByObstacle || ...
        plan.trackingEndTime_s - plan.interceptTime_s < 8
    error("example14MovingRendezvousAndTrail:UnexpectedTrackingEnd", ...
        "Expected at least eight seconds of chase before row-end traffic. " + ...
        "Capture %.1f s, tracking end %.1f s, reason %s.", ...
        plan.interceptTime_s, plan.trackingEndTime_s, ...
        plan.trackingTerminationReason);
end

blocked = queryAzElTimeObstacle(plan.workspace, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blocked)
    error("example14MovingRendezvousAndTrail:Collision", ...
        "The forty-eight-vehicle command contains %d blocked samples.", ...
        nnz(blocked));
end

targetSpeed_deg_s = hypot( ...
    target.velocity_deg_s(:, 1), target.velocity_deg_s(:, 2));
diagnostics = trafficDiagnostics;
diagnostics.targetMinimumSpeed_deg_s = min(targetSpeed_deg_s);
diagnostics.targetMaximumSpeed_deg_s = max(targetSpeed_deg_s);
diagnostics.targetSpeedRange_deg_s = ...
    max(targetSpeed_deg_s) - min(targetSpeed_deg_s);
diagnostics.trackingDuration_s = ...
    plan.trackingEndTime_s - plan.interceptTime_s;
diagnostics.crossedRowCount = countCrossedRows( ...
    target.position_deg(:, 2), trafficDiagnostics.rowElevation_deg);

if diagnostics.vehicleCount ~= 48 || ...
        diagnostics.rowCount ~= 12 || ...
        diagnostics.vehiclesPerRow ~= 4 || ...
        diagnostics.crossedRowCount ~= 12 || ...
        diagnostics.totalDirectionReversals < 48 || ...
        diagnostics.overlapSampleCount ~= 0 || ...
        diagnostics.minimumVehicleClearance_deg <= 0
    error("example14MovingRendezvousAndTrail:TrafficConstruction", ...
        "The example did not construct twelve dense nonoverlapping rows.");
end

viewOptions = defaultAzElAnimationOptions(viewOptions, struct( ...
    "MaximumAnimationFrames", 300, ...
    "MaximumDisplayedSlices", 144, ...
    "PauseSeconds", 0.01, ...
    "MovingTarget", target));
view = animateAzElAvoidancePlan(azElData, plan, viewOptions);
result = struct( ...
    "azElData", azElData, ...
    "startState", startState, ...
    "target", target, ...
    "limits", limits, ...
    "options", options, ...
    "plan", plan, ...
    "diagnostics", diagnostics, ...
    "blockedSampleCount", nnz(blocked), ...
    "view", view);
fprintf([ ...
    'Crossy Road rendezvous: crossed %d rows and %d vehicles, capture %.1f s, ' ...
    'chase %.1f s, stop reason %s, target speed %.3f-%.3f deg/s.\n'], ...
    diagnostics.crossedRowCount, diagnostics.vehicleCount, ...
    plan.interceptTime_s, ...
    diagnostics.trackingDuration_s, plan.trackingTerminationReason, ...
    diagnostics.targetMinimumSpeed_deg_s, ...
    diagnostics.targetMaximumSpeed_deg_s);
end

function [vehicles, diagnostics] = makeCrossyRoadTraffic(time_s)
rowElevation_deg = linspace(-5.6, 5.4, 12);
halfWidth_deg = 0.90;
halfHeight_deg = 0.36;
horizontalEdgeGap_deg = 0.40;
centerSpacing_deg = 2 * halfWidth_deg + horizontalEdgeGap_deg;
convoyOffset_deg = centerSpacing_deg * [-1.5 -0.5 0.5 1.5];
rowCount = numel(rowElevation_deg);
vehiclesPerRow = numel(convoyOffset_deg);
vehicleCount = rowCount * vehiclesPerRow;
vehicles = cell(vehicleCount, 1);
velocityParts = cell(vehicleCount, 1);
centerAzimuth_deg = zeros(numel(time_s), vehicleCount);
centerElevation_deg = zeros(numel(time_s), vehicleCount);
rowCenterAzimuth_deg = zeros(numel(time_s), rowCount);
rowCenterVelocity_deg_s = zeros(numel(time_s), rowCount);
rowPhase_rad = mod(0.20 + (0:rowCount - 1) * 1.31, 2 * pi);
rowOmega_rad_s = linspace(0.125, 0.205, rowCount);

% The last four rows reach alternating road ends during the chase. Keeping
% this timing in the obstacle definition, rather than as a planner hint,
% makes the interception test exercise genuine moving-obstacle prediction.
endPacingRows = 9:12;
endPacingTimes_s = [58 62 66 70];
endPacingSigns = [-1 1 -1 1];
for k = 1:numel(endPacingRows)
    row = endPacingRows(k);
    rowPhase_rad(row) = endPacingSigns(k) * pi / 2 - ...
        rowOmega_rad_s(row) * endPacingTimes_s(k);
end

cursor = 0;
for row = 1:numel(rowElevation_deg)
    omega = rowOmega_rad_s(row);
    phase = rowPhase_rad(row);
    rowCenterAzimuth_deg(:, row) = ...
        8.2 * sin(omega * time_s + phase);
    rowCenterVelocity_deg_s(:, row) = ...
        8.2 * omega * cos(omega * time_s + phase);
    for laneVehicle = 1:vehiclesPerRow
        cursor = cursor + 1;
        centerAzimuth = rowCenterAzimuth_deg(:, row) + ...
            convoyOffset_deg(laneVehicle);
        centerElevation = rowElevation_deg(row) + ...
            zeros(size(time_s));
        centerAzimuth_deg(:, cursor) = centerAzimuth;
        centerElevation_deg(:, cursor) = centerElevation;
        vehicles{cursor} = movingRectangle( ...
            sprintf('Row %02d vehicle %d', row, laneVehicle), ...
            time_s, centerAzimuth, centerElevation, ...
            halfWidth_deg, halfHeight_deg);
        velocityParts{cursor} = rowCenterVelocity_deg_s(:, row);
    end
end

reversals = cellfun(@countDirectionReversals, velocityParts);
[overlapSampleCount, minimumClearance_deg] = vehicleOverlapDiagnostics( ...
    centerAzimuth_deg, centerElevation_deg, ...
    halfWidth_deg, halfHeight_deg);
diagnostics = struct( ...
    "vehicleCount", numel(vehicles), ...
    "rowCount", numel(rowElevation_deg), ...
    "vehiclesPerRow", vehiclesPerRow, ...
    "rowElevation_deg", rowElevation_deg, ...
    "directionReversalsByVehicle", reversals, ...
    "totalDirectionReversals", sum(reversals), ...
    "endPacingRowIndices", endPacingRows, ...
    "endPacingVehicleIndices", ...
        (endPacingRows(1) - 1) * vehiclesPerRow + 1:vehicleCount, ...
    "vehicleHalfSize_deg", [halfWidth_deg halfHeight_deg], ...
    "sameRowEdgeGap_deg", ...
        centerSpacing_deg - 2 * halfWidth_deg, ...
    "overlapSampleCount", overlapSampleCount, ...
    "minimumVehicleClearance_deg", minimumClearance_deg);
end

function data = movingRectangle( ...
        name, time_s, centerAzimuth, centerElevation, ...
        halfWidth, halfHeight)
azimuth = cell(numel(time_s), 1);
elevation = cell(numel(time_s), 1);
for k = 1:numel(time_s)
    azimuth{k} = centerAzimuth(k) + ...
        halfWidth * [-1; 1; 1; -1; -1];
    elevation{k} = centerElevation(k) + ...
        halfHeight * [-1; -1; 1; 1; -1];
end
data = makeAzElObstacleData(name, time_s, azimuth, elevation);
end

function count = countDirectionReversals(velocity)
signValue = sign(velocity(:));
signValue(signValue == 0) = 1;
count = nnz(diff(signValue) ~= 0);
end

function [overlapCount, minimumClearance] = vehicleOverlapDiagnostics( ...
        centerAzimuth, centerElevation, halfWidth, halfHeight)
vehicleCount = size(centerAzimuth, 2);
overlapCount = 0;
minimumClearance = Inf;
for first = 1:vehicleCount - 1
    for second = first + 1:vehicleCount
        azimuthGap = abs(centerAzimuth(:, first) - ...
            centerAzimuth(:, second)) - 2 * halfWidth;
        elevationGap = abs(centerElevation(:, first) - ...
            centerElevation(:, second)) - 2 * halfHeight;
        overlapCount = overlapCount + ...
            nnz(azimuthGap < 0 & elevationGap < 0);
        minimumClearance = min( ...
            minimumClearance, min(max(azimuthGap, elevationGap)));
    end
end
end

function count = countCrossedRows(targetElevation_deg, rowElevation_deg)
minimum = min(targetElevation_deg);
maximum = max(targetElevation_deg);
count = nnz(rowElevation_deg >= minimum & rowElevation_deg <= maximum);
end
