function [result, handles] = example03KinodynamicARAStar(viewOptions)
%EXAMPLE03KINODYNAMICARASTAR Run and visualize a bounded anytime detour.
%
% This example creates azElData directly and does not use Orekit. ARA*
% first returns a bounded path quickly, then repairs the same search until
% it certifies the exact optimum on the configured kinodynamic lattice.

if nargin < 1
    viewOptions = struct();
end
epoch = datetime(2026, 1, 1, 0, 0, 0, "TimeZone", "UTC");
time_s = (0:40).';
obstacleAzimuth = [-1; 1; 1; -1; -1];
obstacleElevation = [43; 43; 47; 47; 43];
azElData = makeAzElObstacleData( ...
    "Central blocker", time_s, obstacleAzimuth, obstacleElevation);
workspace = buildAzElTimeObstacleWorkspace(azElData, struct( ...
    "ReferenceTime", epoch));

startState = struct( ...
    "AzimuthDeg", -6, ...
    "ElevationDeg", 45, ...
    "Time", epoch);
goalState = struct( ...
    "AzimuthDeg", 6, ...
    "ElevationDeg", 45);
limits = struct( ...
    "AzimuthLimitsDeg", [-180 180], ...
    "ElevationLimitsDeg", [40 50], ...
    "AzimuthRateLimitDegPerSec", 2, ...
    "ElevationRateLimitDegPerSec", 2, ...
    "AzimuthAccelerationLimitDegPerSec2", 1, ...
    "ElevationAccelerationLimitDegPerSec2", 1);
options = struct( ...
    "TimeStepSeconds", 1, ...
    "CollisionCheckStepSeconds", 0.2, ...
    "MaxPlanningTimeSeconds", 30, ...
    "EpsilonSchedule", [2.5 2 1.5 1], ...
    "MaxExpansions", 200000, ...
    "MaxWallTimeSeconds", 60);

result = planAzElKinodynamicARAStar( ...
    workspace, startState, goalState, limits, options);
if ~result.Success
    error("example03KinodynamicARAStar:NoPath", ...
        "ARA* failed: %s", result.Message);
end

animationPlan = struct( ...
    "success", true, ...
    "time_s", double(result.Path.ElapsedSeconds), ...
    "position_deg", [ ...
    result.Path.AzimuthDeg, result.Path.ElevationDeg], ...
    "workspace", workspace, ...
    "limits", struct( ...
    "azimuth_deg", limits.AzimuthLimitsDeg, ...
    "elevation_deg", limits.ElevationLimitsDeg));
animationHandles = animateAzElAvoidancePlan( ...
    azElData, animationPlan, defaultAzElAnimationOptions( ...
    viewOptions, struct( ...
    "MaximumAnimationFrames", 120, ...
    "MaximumDisplayedSlices", 80)));

figureHandle = figure( ...
    "Name", "Kinodynamic ARA* example", ...
    "Color", "white");
layout = tiledlayout(figureHandle, 1, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

pathAxes = nexttile(layout);
hold(pathAxes, "on");
fill(pathAxes, obstacleAzimuth, obstacleElevation, ...
    [0.85 0.25 0.30], ...
    "FaceAlpha", 0.18, ...
    "EdgeColor", [0.72 0.12 0.18], ...
    "LineWidth", 1.25, ...
    "DisplayName", "Obstacle");
plot(pathAxes, result.Path.AzimuthUnwrappedDeg, ...
    result.Path.ElevationDeg, ...
    "k-", ...
    "LineWidth", 2.2, ...
    "DisplayName", "Final ARA* path");
scatter(pathAxes, startState.AzimuthDeg, startState.ElevationDeg, ...
    55, [0.10 0.65 0.20], "filled", ...
    "DisplayName", "Start");
scatter(pathAxes, goalState.AzimuthDeg, goalState.ElevationDeg, ...
    55, [0.85 0.10 0.10], "filled", ...
    "DisplayName", "Goal");
grid(pathAxes, "on");
axis(pathAxes, "equal");
xlim(pathAxes, [-7 7]);
ylim(pathAxes, limits.ElevationLimitsDeg);
xlabel(pathAxes, "Azimuth (deg)");
ylabel(pathAxes, "Elevation (deg)");
title(pathAxes, "Certified kinodynamic detour");
legend(pathAxes, "Location", "best");

historyAxes = nexttile(layout);
history = result.SolutionHistory;
iteration = history.Iteration;
yyaxis(historyAxes, "left");
costLine = plot(historyAxes, iteration, history.ObjectiveCost, ...
    "o-", ...
    "LineWidth", 1.8, ...
    "MarkerFaceColor", [0.05 0.45 0.80], ...
    "DisplayName", "Objective cost");
ylabel(historyAxes, result.ObjectiveCostUnits);
yyaxis(historyAxes, "right");
boundLine = plot(historyAxes, iteration, ...
    history.CertifiedSuboptimalityBound, ...
    "s-", ...
    "LineWidth", 1.8, ...
    "MarkerFaceColor", [0.85 0.45 0.10], ...
    "DisplayName", "Certified bound");
ylabel(historyAxes, "Maximum lattice suboptimality");
xticks(historyAxes, iteration);
xticklabels(historyAxes, compose("%.3g", history.RequestedEpsilon));
xlabel(historyAxes, "Requested epsilon");
grid(historyAxes, "on");
title(historyAxes, "ARA* repair history");
legend(historyAxes, [costLine, boundLine], "Location", "best");

handles = struct( ...
    "Figure", figureHandle, ...
    "Layout", layout, ...
    "PathAxes", pathAxes, ...
    "HistoryAxes", historyAxes, ...
    "Animation", animationHandles);
result.AnimationPlan = animationPlan;

fprintf("ARA*: %.3f %s, %.6gx certified bound, %d expansions.\n", ...
    result.ObjectiveCost, result.ObjectiveCostUnits, ...
    result.SuboptimalityBound, result.ExpandedNodeCount);
end
