function plan = example01PlanFromAzElData(azElData, viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   plan = example01PlanFromAzElData(azElData)
%   plan = example01PlanFromAzElData(azElData, viewOptions)
%**************************************************************************
% PURPOSE
%   - Demonstrate a complete Dijkstra planning call from caller-supplied
%     obstacle data over the full azimuth/elevation field of regard.
%   - Independently validate the returned command before animation.
%**************************************************************************
% INPUTS
%   - azElData (canonical obstacle collection)
%       Scalar struct, struct array, or nested cell collection.
%   - viewOptions (scalar struct, optional)
%       Partial animateAzElAvoidancePlan options.
%**************************************************************************
% OUTPUTS
%   - plan (scalar struct)
%       Successful Dijkstra plan plus animation handles.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Define The Planning Request
% This example reads like a small planning report: define the two endpoint
% states, state the hardware limits, and then state how much search detail
% is appropriate for a full-field demonstration.
if nargin < 2
    viewOptions = struct();
end

startState = struct( ...
    "time_s", 2700, ...
    "position_deg", [-30, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);

stopState = struct( ...
    "time_s", 3000, ...
    "position_deg", [80, 80], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);

limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-90, 90], ...
    "maxVelocity_deg_s", [1, 1], ...
    "maxAcceleration_deg_s2", [3, 3]);

options = struct( ...
    "SampleTime_s", 0.1, ...
    "GridStep_deg", 1, ...
    "GridStepSchedule_deg", [2 1], ...
    "SafetyMargin_deg", 1, ...
    "AllowAzimuthWrap", true, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", 20);

% SampleTime_s controls how often the final command is reported; it does
% not need to equal the search grid spacing. Searching the entire sky on a
% 0.1-degree grid creates millions of positions and can exhaust the default
% wall-time budget. The two-degree pass finds the route family quickly, and
% the one-degree pass improves it before exact polygon validation.

%% Section 2: Plan & Independently Validate The Command
% The planner performs its own dense validation. This second check belongs
% in the example as an easy-to-see acceptance test for caller-supplied data.
plan = planAzElDijkstra( ...
    azElData, startState, stopState, limits, options);
if ~plan.success
    error("example01PlanFromAzElData:NoPath", "%s", plan.message);
end
blockedCommandSamples = queryAzElTimeObstacle(plan.obstacleField, ...
    plan.position_deg(:, 1), plan.position_deg(:, 2), plan.time_s, ...
    struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", plan.options.TimePaddingSamples));
if any(blockedCommandSamples)
    error("example01PlanFromAzElData:Collision", ...
        "The returned command contains %d blocked samples.", ...
        nnz(blockedCommandSamples));
end

%% Section 3: Animate The Result
plan.animationHandles = animateAzElAvoidancePlan( ...
    azElData, plan, defaultAzElAnimationOptions( ...
    viewOptions, struct("MaximumAnimationFrames", 240)));
end
