function [result, handles] = example03KinodynamicDetour(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   [result, handles] = example03KinodynamicDetour()
%   [result, handles] = example03KinodynamicDetour(viewOptions)
%**************************************************************************
% PURPOSE
%   - Demonstrate both RRT* trees finding a static kinodynamic detour.
%   - Independently validate the sampled command against the packed polygon.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Partial animation options.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Successful bidirectional RRT* plan plus animation handles.
%   - handles (scalar struct)
%       Figure and axes handles from animateAzElAvoidancePlan.
%**************************************************************************
% UNITS
%   - Angular quantities are degrees; temporal quantities are seconds.

%% Section 1: Build The Static Planning Problem
if nargin < 1
    viewOptions = struct();
end

time_s = (0:40).';
obstacleAzimuth = [-1; 1; 1; -1; -1];
obstacleElevation = [43; 43; 47; 47; 43];
azElData = makeAzElObstacleData( ...
    "Central blocker", time_s, obstacleAzimuth, obstacleElevation);
startState = struct( ...
    "time_s", 0, ...
    "position_deg", [-6, 45], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
stopState = struct( ...
    "time_s", 40, ...
    "position_deg", [6, 45], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [40, 50], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [1, 1]);
options = struct( ...
    "SampleTime_s", 0.2, ...
    "ValidationStep_s", 0.1, ...
    "CollisionCheckStep_s", 0.25, ...
    "SafetyMargin_deg", 0.1, ...
    "RandomSeed", 7, ...
    "StepSize_deg", 3, ...
    "RewireRadius_deg", 5, ...
    "ConnectionRadius_deg", 7, ...
    "MaxIterations", 3000, ...
    "IterationsAfterFirstSolution", 100, ...
    "MaxSearchTime_s", 12);

%% Section 2: Plan & Independently Validate The Command
result = planAzElBidirectionalKinodynamicRRTStar( ...
    azElData, startState, stopState, limits, options);
if ~result.success
    error("example03KinodynamicDetour:NoPath", ...
        "Bidirectional RRT* failed: %s", result.message);
end

blocked = queryAzElTimeObstacle(result.obstacleField, ...
    result.position_deg(:, 1), result.position_deg(:, 2), ...
    result.time_s, struct( ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "TimePaddingSamples", result.options.TimePaddingSamples));
if any(blocked)
    error("example03KinodynamicDetour:Collision", ...
        "The returned command contains %d blocked samples.", nnz(blocked));
end

%% Section 3: Animate & Report The Result
handles = animateAzElAvoidancePlan( ...
    azElData, result, defaultAzElAnimationOptions( ...
    viewOptions, struct( ...
    "MaximumAnimationFrames", 120, ...
    "MaximumDisplayedSlices", 80)));
result.animationHandles = handles;
fprintf("Bidirectional RRT* detour: %.3f deg, %.3f s, %d nodes.\n", ...
    result.angularPathLength_deg, result.searchElapsed_s, ...
    result.generatedNodeCount);
end
