function result = example05FiveTurnSpiral()
%EXAMPLE05FIVETURNSPIRAL Enter the center of a five-turn spiral.

time_s = (0:0.5:400).';
[wallAzimuth, wallElevation] = spiralWall( ...
    5, 2, 3, 0.4, 241);
azElData = makeAzElObstacleData( ...
    "Five-turn spiral wall", time_s, ...
    wallAzimuth, wallElevation);
startState = boundaryState(0, [18, 1.5]);
stopState = boundaryState(400, [0, 0]);
limits = standardLimits([-20, 20], [-20, 20]);
options = standardOptions(0.5, 30);

result = runAzElGauntletCase( ...
    "Gauntlet 1", ...
    "autonomously enter a five-turn spiral", ...
    azElData, startState, stopState, limits, options);
hasDirectionHint = ...
    isfield(result.plan.options, "DirectionAngles_deg") && ...
    ~isempty(result.plan.options.DirectionAngles_deg);
if result.plan.method ~= "adaptiveAnyAngleAStar" || ...
        isfield(result.plan.options, "GuidePath_deg") || hasDirectionHint
    error("example05FiveTurnSpiral:ExternalGuideUsed", ...
        "The spiral test must use unguided adaptive A* search.");
end
position = result.plan.positionUnwrapped_deg;
radius = hypot(position(:, 1), position(:, 2));
% Exclude only the final approach to the origin, where polar angle is
% undefined. A larger cutoff would incorrectly discard the inner turns.
inside = radius >= 0.75;
angle = unwrap(atan2(position(inside, 2), position(inside, 1)));
result.diagnostics.windingTurns = ...
    abs(angle(end) - angle(1)) / (2 * pi);
if result.diagnostics.windingTurns < 4.0
    error("example05FiveTurnSpiral:InsufficientTurns", ...
        "The path accumulated only %.2f spiral turns.", ...
        result.diagnostics.windingTurns);
end
moving = ~result.plan.isWaiting;
result.diagnostics.motionCompletionTime_s = ...
    result.plan.time_s(find(moving, 1, "last"));
fprintf("  Spiral turns followed: %.2f\n", ...
    result.diagnostics.windingTurns);
fprintf("  Motion complete at %.1f s; topology search %.2f s.\n", ...
    result.diagnostics.motionCompletionTime_s, ...
    result.plan.topologySearch.SearchElapsed_s);
end

function [azimuth, elevation] = spiralWall( ...
        turnCount, innerRadius, turnSpacing, halfWidth, sampleCount)
theta = linspace(0, 2 * pi * turnCount, sampleCount).';
radius = innerRadius + turnSpacing * theta / (2 * pi);
centerAzimuth = radius .* cos(theta);
centerElevation = radius .* sin(theta);
deltaAzimuth = gradient(centerAzimuth);
deltaElevation = gradient(centerElevation);
lengthValue = hypot(deltaAzimuth, deltaElevation);
normalAzimuth = -deltaElevation ./ lengthValue;
normalElevation = deltaAzimuth ./ lengthValue;
leftAzimuth = centerAzimuth + halfWidth * normalAzimuth;
leftElevation = centerElevation + halfWidth * normalElevation;
rightAzimuth = centerAzimuth - halfWidth * normalAzimuth;
rightElevation = centerElevation - halfWidth * normalElevation;
azimuth = [leftAzimuth; flipud(rightAzimuth); leftAzimuth(1)];
elevation = [ ...
    leftElevation; flipud(rightElevation); leftElevation(1)];
end

function state = boundaryState(time_s, position)
state = struct( ...
    "time_s", time_s, ...
    "position_deg", position, ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
end

function limits = standardLimits(azimuthLimits, elevationLimits)
limits = struct( ...
    "azimuth_deg", azimuthLimits, ...
    "elevation_deg", elevationLimits, ...
    "maxVelocity_deg_s", [3, 3], ...
    "maxAcceleration_deg_s2", [3, 3]);
end

function options = standardOptions(safetyMargin, maxSearchTime)
options = struct( ...
    "SampleTime_s", 0.5, ...
    "GridStep_deg", 0.5, ...
    "SafetyMargin_deg", safetyMargin, ...
    "AllowAzimuthWrap", false, ...
    "Objective", "minimumAngularDistance", ...
    "MaxSearchTime_s", maxSearchTime, ...
    "MaxExpansions", 1000000, ...
    "MaximumVerticesPerRegion", 500, ...
    "HeuristicWeight", 1);
end
