function result = example07WrappedAzimuthSeam()
%EXAMPLE07WRAPPEDAZIMUTHSEAM Detour across the azimuth wrap seam.

problem = makeWrappedAzimuthSeamGauntlet();

result = runAzElGauntletCase( ...
    "Gauntlet 3", ...
    "wrapped-azimuth seam detour", ...
    problem.azElData, problem.startState, problem.stopState, ...
    problem.limits, problem.options);
unwrappedAzimuth = result.plan.positionUnwrapped_deg(:, 1);
result.diagnostics.maximumUnwrappedStep_deg = ...
    max(abs(diff(unwrappedAzimuth)));
result.diagnostics.maximumElevationDetour_deg = ...
    max(abs(result.plan.position_deg(:, 2)));
if result.diagnostics.maximumUnwrappedStep_deg > 2 || ...
        result.diagnostics.maximumElevationDetour_deg < 5
    error("example07WrappedAzimuthSeam:InvalidDetour", ...
        "The seam path is discontinuous or did not clear the blocker.");
end
fprintf("  Maximum unwrapped step %.2f deg; elevation detour %.2f deg.\n", ...
    result.diagnostics.maximumUnwrappedStep_deg, ...
    result.diagnostics.maximumElevationDetour_deg);
end
