function findings = runSourceAudit()
%RUNSOURCEAUDIT Reject fixture recognition and forbidden reference coupling.
plannerRoot = fileparts(fileparts(mfilename("fullpath")));
source = fileread(fullfile(plannerRoot, "planAzElTrajectory.m"));
patterns = [ ...
    "example\\d+" ...
    "vietnam" ...
    "china" ...
    "slalom" ...
    "windmill" ...
    "u[- ]?trap" ...
    "spinning rod" ...
    "azElStandaloneExamples" ...
    "reference repo" ...
    "legacy planner"];
findings = strings(0, 1);
for patternIndex = 1:numel(patterns)
    if ~isempty(regexpi(source, patterns(patternIndex), "once"))
        findings(end + 1, 1) = patterns(patternIndex); %#ok<AGROW>
    end
end
assert(isempty(findings), ...
    "Production source contains forbidden recognition text: %s", ...
    strjoin(findings, ", "));
end
