function tests = testOrekitPropagation
%% Section 0: Header & Readme
% SYNTAX
%   tests = testOrekitPropagation
%**************************************************************************
% PURPOSE
%   - Verify Orekit two-body trajectory propagation and validation behavior.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Deterministic integration tests requiring the pinned Orekit runtime.
%**************************************************************************
% UNITS
%   - Positions are metres, velocities are metres per second, and epochs use
%     UTC. ECI is GCRF and ECEF is ITRF using IERS 2010 conventions.
%**************************************************************************

tests = functiontests(localfunctions);
end

function testPropagateItrfState(testCase)
% Verify sample shapes, frames, provenance, and initial-state preservation.

initialEpoch = datetime(2026, 1, 1, 17, 0, 0, "TimeZone", "UTC");
initialState = struct( ...
    "epoch", initialEpoch, ...
    "frame", "ITRF", ...
    "position_m", [7000000, 0, 0], ...
    "velocity_m_s", [0, 7546, 0]);
sampleEpochsUtc = initialEpoch + seconds((0:60:180)');

result = scenario.integrations.orekit.propagateSatelliteTrajectory( ...
    initialState, sampleEpochsUtc);

verifySize(testCase, result.PositionEci_m, [4, 3]);
verifySize(testCase, result.PositionEcef_m, [4, 3]);
verifyEqual(testCase, result.PositionEcef_m(1, :), ...
    initialState.position_m, "AbsTol", 1e-6);
verifyGreaterThan(testCase, ...
    norm(result.PositionEcef_m(end, :) - result.PositionEcef_m(1, :)), ...
    1e5);
verifyEqual(testCase, result.InertialFrame, "GCRF");
verifyEqual(testCase, result.EarthFixedFrame, "ITRF-IERS2010");
verifyEqual(testCase, result.Model, "Orekit-KeplerianPropagator");
verifyEqual(testCase, result.ProviderVersion, "13.1.6");
end

function testRejectUnsupportedFrame(testCase)
% Verify unsupported initial-state frames fail before propagation.

initialEpoch = datetime(2026, 1, 1, "TimeZone", "UTC");
initialState = struct( ...
    "epoch", initialEpoch, ...
    "frame", "GCRF", ...
    "position_m", [7000000, 0, 0], ...
    "velocity_m_s", [0, 7546, 0]);

verifyError(testCase, ...
    @() scenario.integrations.orekit.propagateSatelliteTrajectory( ...
        initialState, initialEpoch), ...
    "propagateSatelliteTrajectory:UnsupportedFrame");
end

function testCreateStateFromClassicalElements(testCase)
% Verify classical orbital elements produce a finite ITRF platform state.

epochUtc = datetime(2026, 1, 1, 17, 0, 0, "TimeZone", "UTC");
elements = struct( ...
    "EpochUtc", epochUtc, ...
    "Altitude_m", 500000, ...
    "Eccentricity", 0.001, ...
    "Inclination_deg", 51.6, ...
    "Raan_deg", 25, ...
    "ArgumentOfPerigee_deg", 10, ...
    "TrueAnomaly_deg", 45);

initialState = ...
    scenario.integrations.orekit.createSatelliteStateFromKeplerian(elements);

verifyEqual(testCase, initialState.epoch, epochUtc);
verifyEqual(testCase, initialState.frame, "ITRF");
verifySize(testCase, initialState.position_m, [1, 3]);
verifySize(testCase, initialState.velocity_m_s, [1, 3]);
verifyTrue(testCase, all(isfinite(initialState.position_m)));
verifyGreaterThan(testCase, norm(initialState.position_m), 6.8e6);
end

function testRejectNonEllipticElements(testCase)
% Verify the authoring contract rejects eccentricity outside an ellipse.

epochUtc = datetime(2026, 1, 1, "TimeZone", "UTC");
elements = struct( ...
    "EpochUtc", epochUtc, ...
    "Altitude_m", 500000, ...
    "Eccentricity", 1, ...
    "Inclination_deg", 0, ...
    "Raan_deg", 0, ...
    "ArgumentOfPerigee_deg", 0, ...
    "TrueAnomaly_deg", 0);

verifyError(testCase, ...
    @() scenario.integrations.orekit.createSatelliteStateFromKeplerian( ...
        elements), ...
    "MATLAB:notLess");
end
