function plan = planAzElAvoidance( ...
        azElData, startState, stopState, limits, options)
%PLANAZELAVOIDANCE Plan an az/el boresight path around moving obstacles.
%
% plan = planAzElAvoidance(azElData, startState, stopState, limits, options)
%
% azElData is one five-field calculateAreaTargetAzEl result, a struct
% array of results, or a cell array of results.
%
% startState and stopState:
%   time_s, position_deg [az el], velocity_deg_s [az el],
%   acceleration_deg_s2 [az el]
%
% limits:
%   azimuth_deg, elevation_deg, maxVelocity_deg_s,
%   maxAcceleration_deg_s2
%
% options:
%   SampleTime_s, GridStep_deg, SafetyMargin_deg, AllowAzimuthWrap
%
% The output time_s and position_deg arrays are the requested 2-D steering
% command over time. positionUnwrapped_deg keeps azimuth continuous through
% the +/-180 degree seam.

startState = normalizeBoundaryState(startState, "startState");
stopState = normalizeBoundaryState(stopState, "stopState");
limits = normalizePublicLimits(limits);
options = normalizePublicOptions(options);

duration_s = stopState.time_s - startState.time_s;
if duration_s <= 0
    error("planAzElAvoidance:InvalidTimeRange", ...
        "stopState.time_s must be later than startState.time_s.");
end
stepCount = duration_s / options.SampleTime_s;
if abs(stepCount - round(stepCount)) > 1e-8
    error("planAzElAvoidance:TimeGridMismatch", ...
        "The start-to-stop duration must be divisible by SampleTime_s.");
end
outputStepCount = round(stepCount);
planningStride = choosePlanningStride( ...
    outputStepCount, options.SampleTime_s);
planningSampleTime_s = planningStride * options.SampleTime_s;
if options.AllowAzimuthWrap && ...
        abs(diff(limits.azimuth_deg) - 360) > 1e-9
    error("planAzElAvoidance:InvalidAzimuthWrap", ...
        "AllowAzimuthWrap requires azimuth_deg to span 360 degrees.");
end

workspace = buildAzElTimeObstacleWorkspace(azElData);
internalLimits = struct( ...
    "AzimuthLimitsDeg", limits.azimuth_deg, ...
    "ElevationLimitsDeg", limits.elevation_deg, ...
    "AzimuthRateLimitDegPerSec", limits.maxVelocity_deg_s(1), ...
    "ElevationRateLimitDegPerSec", limits.maxVelocity_deg_s(2), ...
    "AzimuthAccelerationLimitDegPerSec2", ...
    limits.maxAcceleration_deg_s2(1), ...
    "ElevationAccelerationLimitDegPerSec2", ...
    limits.maxAcceleration_deg_s2(2));

gridStep = options.GridStep_deg;
accelerationLevel = min(1, min(limits.maxVelocity_deg_s ./ ...
    (limits.maxAcceleration_deg_s2 .* planningSampleTime_s)));
activeAcceleration = limits.maxAcceleration_deg_s2 .* accelerationLevel;
basePositionResolution = 0.5 .* ...
    activeAcceleration .* planningSampleTime_s^2;
subdivision = max(1, ceil(basePositionResolution ./ gridStep));
positionResolution = basePositionResolution ./ subdivision;
rateResolution = activeAcceleration .* planningSampleTime_s;

internalStart = struct( ...
    "AzimuthDeg", startState.position_deg(1), ...
    "ElevationDeg", startState.position_deg(2), ...
    "AzimuthRateDegPerSec", startState.velocity_deg_s(1), ...
    "ElevationRateDegPerSec", startState.velocity_deg_s(2), ...
    "AzimuthAccelerationDegPerSec2", startState.acceleration_deg_s2(1), ...
    "ElevationAccelerationDegPerSec2", startState.acceleration_deg_s2(2), ...
    "Time", startState.time_s);
internalGoal = struct( ...
    "AzimuthDeg", stopState.position_deg(1), ...
    "ElevationDeg", stopState.position_deg(2), ...
    "AzimuthRateDegPerSec", stopState.velocity_deg_s(1), ...
    "ElevationRateDegPerSec", stopState.velocity_deg_s(2), ...
    "AzimuthAccelerationDegPerSec2", stopState.acceleration_deg_s2(1), ...
    "ElevationAccelerationDegPerSec2", stopState.acceleration_deg_s2(2), ...
    "EarliestTime", stopState.time_s, ...
    "LatestTime", stopState.time_s, ...
    "PositionToleranceDeg", gridStep ./ 2 + 1e-9, ...
    "RateToleranceDegPerSec", rateResolution ./ 2 + 1e-9, ...
    "AccelerationToleranceDegPerSec2", 1e-9);
internalOptions = struct( ...
    "TimeStepSeconds", planningSampleTime_s, ...
    "MaxPlanningTimeSeconds", duration_s, ...
    "AzimuthWrap", options.AllowAzimuthWrap, ...
    "AzimuthResolutionDeg", positionResolution(1), ...
    "ElevationResolutionDeg", positionResolution(2), ...
    "AzimuthRateResolutionDegPerSec", rateResolution(1), ...
    "ElevationRateResolutionDegPerSec", rateResolution(2), ...
    "AccelerationLevels", [-accelerationLevel 0 accelerationLevel], ...
    "CollisionCheckStepSeconds", options.SampleTime_s, ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", 1, ...
    "SafetyMarginDeg", options.SafetyMargin_deg, ...
    "MaxExpansions", options.MaxExpansions);

search = planAzElKinodynamicAStar( ...
    workspace, internalStart, internalGoal, internalLimits, internalOptions);
plan = publicResult(search, workspace, startState, stopState, ...
    limits, options, positionResolution, rateResolution, ...
    planningSampleTime_s);
end

function stride = choosePlanningStride(outputStepCount, outputDt)
sampleCountTarget = ceil(outputStepCount / 300);
oneSecondTarget = ceil(1 / outputDt);
targetStride = max([1 sampleCountTarget oneSecondTarget]);
targetStride = min([targetStride 20 outputStepCount]);
divisors = find(mod(outputStepCount, 1:targetStride) == 0);
if isempty(divisors)
    stride = 1;
else
    stride = divisors(end);
end
end

function state = normalizeBoundaryState(input, label)
required = ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"];
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(isfield(input, cellstr(required)))
    error("planAzElAvoidance:InvalidState", ...
        "%s must contain time_s, position_deg, velocity_deg_s, and " + ...
        "acceleration_deg_s2.", label);
end
validateattributes(input.time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
fields = ["position_deg", "velocity_deg_s", "acceleration_deg_s2"];
state = struct("time_s", double(input.time_s));
for name = fields
    validateattributes(input.(name), {'numeric'}, ...
        {'vector', 'numel', 2, 'real', 'finite'});
    state.(name) = reshape(double(input.(name)), 1, 2);
end
end

function limits = normalizePublicLimits(input)
required = ["azimuth_deg", "elevation_deg", ...
    "maxVelocity_deg_s", "maxAcceleration_deg_s2"];
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(isfield(input, cellstr(required)))
    error("planAzElAvoidance:InvalidLimits", ...
        "limits is missing a required field.");
end
validateattributes(input.azimuth_deg, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'increasing'});
validateattributes(input.elevation_deg, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'increasing'});
validateattributes(input.maxVelocity_deg_s, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'positive'});
validateattributes(input.maxAcceleration_deg_s2, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'positive'});
limits = struct( ...
    "azimuth_deg", reshape(double(input.azimuth_deg), 1, 2), ...
    "elevation_deg", reshape(double(input.elevation_deg), 1, 2), ...
    "maxVelocity_deg_s", ...
    reshape(double(input.maxVelocity_deg_s), 1, 2), ...
    "maxAcceleration_deg_s2", ...
    reshape(double(input.maxAcceleration_deg_s2), 1, 2));
end

function options = normalizePublicOptions(input)
if nargin == 0 || isempty(input)
    input = struct();
end
defaults = struct( ...
    "SampleTime_s", 1, ...
    "GridStep_deg", 0.25, ...
    "SafetyMargin_deg", 0, ...
    "AllowAzimuthWrap", true, ...
    "MaxExpansions", 500000);
options = applyDefaults(input, defaults);
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(options.GridStep_deg, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
if ~any(numel(options.GridStep_deg) == [1 2])
    error("planAzElAvoidance:InvalidGridStep", ...
        "GridStep_deg must be scalar or [azimuth elevation].");
end
if isscalar(options.GridStep_deg)
    options.GridStep_deg = repmat(options.GridStep_deg, 1, 2);
else
    options.GridStep_deg = reshape(options.GridStep_deg, 1, 2);
end
validateattributes(options.SafetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(options.AllowAzimuthWrap, {'logical', 'numeric'}, ...
    {'scalar'});
if options.AllowAzimuthWrap ~= 0 && options.AllowAzimuthWrap ~= 1
    error("planAzElAvoidance:InvalidWrapOption", ...
        "AllowAzimuthWrap must be logical or numeric 0/1.");
end
options.AllowAzimuthWrap = logical(options.AllowAzimuthWrap);
validateattributes(options.MaxExpansions, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
end

function plan = publicResult(search, workspace, startState, stopState, ...
        limits, options, positionResolution, rateResolution, ...
        planningSampleTime_s)
[time_s, position, positionUnwrapped, velocity, acceleration, isWaiting] = ...
    resamplePath(search, options.SampleTime_s, planningSampleTime_s, ...
    limits, options, startState);
plan = struct();
plan.success = search.Success;
plan.message = search.Message;
plan.time_s = time_s;
plan.position_deg = position;
plan.positionUnwrapped_deg = positionUnwrapped;
plan.velocity_deg_s = velocity;
plan.acceleration_deg_s2 = acceleration;
plan.isWaiting = isWaiting;
plan.cost_s = search.CostSeconds;
plan.expandedNodeCount = search.ExpandedNodeCount;
plan.generatedNodeCount = search.GeneratedNodeCount;
plan.startState = startState;
plan.stopState = stopState;
plan.limits = limits;
plan.options = options;
plan.workspace = workspace;
plan.internalPositionResolution_deg = positionResolution;
plan.internalVelocityResolution_deg_s = rateResolution;
plan.internalSampleTime_s = planningSampleTime_s;
plan.searchResult = search;
end

function [time_s, position, positionUnwrapped, velocity, ...
        acceleration, isWaiting] = resamplePath( ...
        search, outputDt, planningDt, limits, options, startState)
if ~search.Success
    time_s = zeros(0, 1);
    position = zeros(0, 2);
    positionUnwrapped = zeros(0, 2);
    velocity = zeros(0, 2);
    acceleration = zeros(0, 2);
    isWaiting = false(0, 1);
    return;
end

path = search.Path;
samplesPerEdge = round(planningDt / outputDt);
edgeCount = height(path) - 1;
sampleCount = edgeCount * samplesPerEdge + 1;
time_s = zeros(sampleCount, 1);
positionUnwrapped = zeros(sampleCount, 2);
velocity = zeros(sampleCount, 2);
acceleration = zeros(sampleCount, 2);
write = 0;
for k = 1:edgeCount
    tau = (0:samplesPerEdge - 1).' * outputDt;
    row = path(k, :);
    next = path(k + 1, :);
    edgeAcceleration = [ ...
        next.AzimuthAccelerationDegPerSec2, ...
        next.ElevationAccelerationDegPerSec2];
    index = write + (1:samplesPerEdge);
    time_s(index) = row.TimeSecondsFromReference + tau;
    positionUnwrapped(index, 1) = row.AzimuthUnwrappedDeg + ...
        row.AzimuthRateDegPerSec .* tau + ...
        0.5 .* edgeAcceleration(1) .* tau.^2;
    positionUnwrapped(index, 2) = row.ElevationDeg + ...
        row.ElevationRateDegPerSec .* tau + ...
        0.5 .* edgeAcceleration(2) .* tau.^2;
    velocity(index, 1) = row.AzimuthRateDegPerSec + ...
        edgeAcceleration(1) .* tau;
    velocity(index, 2) = row.ElevationRateDegPerSec + ...
        edgeAcceleration(2) .* tau;
    acceleration(index, :) = repmat( ...
        edgeAcceleration, samplesPerEdge, 1);
    write = write + samplesPerEdge;
end
time_s(end) = path.TimeSecondsFromReference(end);
positionUnwrapped(end, :) = [ ...
    path.AzimuthUnwrappedDeg(end), path.ElevationDeg(end)];
velocity(end, :) = [ ...
    path.AzimuthRateDegPerSec(end), ...
    path.ElevationRateDegPerSec(end)];
acceleration(end, :) = [ ...
    path.AzimuthAccelerationDegPerSec2(end), ...
    path.ElevationAccelerationDegPerSec2(end)];
acceleration(1, :) = startState.acceleration_deg_s2;

position = positionUnwrapped;
if options.AllowAzimuthWrap
    lower = limits.azimuth_deg(1);
    span = diff(limits.azimuth_deg);
    position(:, 1) = mod(position(:, 1) - lower, span) + lower;
end
tolerance = 1e-10;
isWaiting = all(abs(velocity) <= tolerance, 2) & ...
    all(abs(acceleration) <= tolerance, 2);
end

function output = applyDefaults(input, defaults)
output = input;
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(output, names{k}) || isempty(output.(names{k}))
        output.(names{k}) = defaults.(names{k});
    end
end
end
