function summary = summarizeAccess(accessResult)
%SUMMARIZEACCESS Create a compact summary table for an access result.

summary = table( ...
    string(accessResult.SourceName), string(accessResult.TargetName), ...
    height(accessResult.AccessWindows), accessResult.Duration, ...
    accessResult.MaxElevation, accessResult.MinRange, ...
    'VariableNames', {'Source', 'Target', 'WindowCount', ...
    'TotalDurationSeconds', 'MaxElevationDeg', 'MinRangeKm'});
end
