%% Script 231: animate a scenario with sensor visualization options accepted
script_217_demoSensorTaskingFullWorkflow;
animateScenario(scenario, struct("Play", true, "MaxFrames", 30, ...
    "PauseSeconds", 0.02, "ShowSensorFOV", true, "ShowSensorFOR", true, ...
    "SelectedSatelliteName", "TaskSat-1", "SelectedSensorName", "WideCam-1"));
