function exportSensorAccessReport(sensorAccessResult, filename)
%EXPORTSENSORACCESSREPORT Export sensor access summary and windows.

[~, ~, ext] = fileparts(filename);
if strcmpi(ext, ".mat")
    save(filename, "sensorAccessResult");
    return;
end

windows = sensorAccessResult.AccessWindows;
if isempty(windows)
    windows = table();
end

summary = table( ...
    string(sensorAccessResult.Metadata.ScenarioName), ...
    string(sensorAccessResult.ParentName), ...
    string(sensorAccessResult.SensorName), ...
    string(sensorAccessResult.TargetName), ...
    string(sensorAccessResult.Metadata.SensorType), ...
    string(sensorAccessResult.Metadata.PointingMode), ...
    string(sensorAccessResult.Metadata.FieldOfViewType), ...
    sensorAccessResult.Duration, ...
    height(sensorAccessResult.AccessWindows), ...
    sensorAccessResult.MaxElevation, ...
    sensorAccessResult.MinRange, ...
    sensorAccessResult.MaxOffBoresight, ...
    'VariableNames', {'ScenarioName', 'ParentObject', 'SensorName', ...
    'TargetName', 'SensorType', 'PointingMode', 'FieldOfViewType', ...
    'TotalDurationSeconds', 'WindowCount', 'SummaryMaxElevationDeg', ...
    'SummaryMinRangeKm', 'SummaryMaxOffBoresightDeg'});

if isempty(windows) || width(windows) == 0
    writetable(summary, filename);
else
    summaryRows = repmat(summary, height(windows), 1);
    writetable([summaryRows windows], filename);
end
end
