function exportSensorDefinitions(scenario, filename)
%EXPORTSENSORDEFINITIONS Export attached sensor definitions from a scenario.

rows = {};
for k = 1:numel(scenario.Objects)
    obj = scenario.Objects{k};
    if ~isprop(obj, "Sensors")
        continue;
    end
    for s = 1:numel(obj.Sensors)
        sensor = obj.Sensors{s};
        rows(end + 1, :) = {string(obj.Name), string(obj.ObjectType), ...
            string(sensor.Name), string(sensor.SensorType), ...
            string(sensor.PointingMode), string(sensor.FieldOfViewType), ...
            sensor.ConeHalfAngleDeg, sensor.RectangularHalfAngleXDeg, ...
            sensor.RectangularHalfAngleYDeg, sensor.MinRangeKm, ...
            sensor.MaxRangeKm, sensor.MinElevationDeg}; %#ok<AGROW>
    end
end

variableNames = {'ParentName', 'ParentType', 'SensorName', 'SensorType', ...
    'PointingMode', 'FieldOfViewType', 'ConeHalfAngleDeg', ...
    'RectangularHalfAngleXDeg', 'RectangularHalfAngleYDeg', ...
    'MinRangeKm', 'MaxRangeKm', 'MinElevationDeg'};
if isempty(rows)
    definitions = table(strings(0, 1), strings(0, 1), strings(0, 1), ...
        strings(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
        zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
        'VariableNames', variableNames);
else
    definitions = cell2table(rows, 'VariableNames', variableNames);
end
writetable(definitions, filename);
end
